"use client";
import React, { useState, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import {
  Sparkles,
  Settings2,
  Loader2,
  Eye,
  Search,
  Volume2,
  AlertTriangle,
  FileText,
  FileCode,
  Download,
  X,
} from "lucide-react";
import { CaptionTrackInfo, TranslationLanguageInfo } from "@/features/listening/services/xpSubExtractor";
import { SubtitleSentence, YouTubeVideoItem } from "@/stores/videoStore";
import { speakLessonText } from "@/shared/utils/ttsEngine";
import { Toast } from "@/stores/notificationStore";

interface XpSubExtractorModalProps {
  isOpen: boolean;
  onClose: () => void;
  activeVideo: YouTubeVideoItem | null;
  onInjectSubtitles: (subtitles: SubtitleSentence[]) => void;
  addToast: (toast: Omit<Toast, "id">) => void;
}

function formatSubTime(seconds: number): string {
  if (isNaN(seconds) || seconds < 0) return "00:00";
  const totalSec = Math.floor(seconds);
  const mins = Math.floor(totalSec / 60);
  const secs = totalSec % 60;
  return `${String(mins).padStart(2, "0")}:${String(secs).padStart(2, "0")}`;
}

export const XpSubExtractorModal: React.FC<XpSubExtractorModalProps> = ({
  isOpen,
  onClose,
  activeVideo,
  onInjectSubtitles,
  addToast,
}) => {
  const [isFetchingTracks, setIsFetchingTracks] = useState(false);
  const [xpSubTracks, setXpSubTracks] = useState<CaptionTrackInfo[]>([]);
  const [xpSubTranslations, setXpSubTranslations] = useState<TranslationLanguageInfo[]>([]);
  const [selectedTrackUrl, setSelectedTrackUrl] = useState<string>("");
  const [selectedTargetLang, setSelectedTargetLang] = useState<string>("vi");
  const [isBilingual, setIsBilingual] = useState<boolean>(true);
  const [xpSubPreviewSentences, setXpSubPreviewSentences] = useState<SubtitleSentence[]>([]);
  const [isExtractingPreview, setIsExtractingPreview] = useState<boolean>(false);
  const [xpSubError, setXpSubError] = useState<string | null>(null);
  const [searchPreviewQuery, setSearchPreviewQuery] = useState<string>("");

  useEffect(() => {
    if (!isOpen || !activeVideo) return;

    let isMounted = true;
    setIsFetchingTracks(true);
    setXpSubError(null);
    setXpSubPreviewSentences([]);

    (async () => {
      try {
        const res = await fetch(`/api/youtube/subtitles/tracks?videoId=${activeVideo.id}`);
        if (res.ok) {
          const data = await res.json();
          if (isMounted && data.success && Array.isArray(data.tracks) && data.tracks.length > 0) {
            setXpSubTracks(data.tracks);
            setXpSubTranslations(data.translationLanguages || []);

            let best = data.tracks.find((t: any) => t.languageCode === "en" && !t.isAutoGenerated);
            if (!best) best = data.tracks.find((t: any) => t.languageCode === "en");
            if (!best) best = data.tracks[0];

            if (best) {
              setSelectedTrackUrl(best.baseUrl);
              fetchPreviewSubtitles(best.baseUrl, selectedTargetLang, isBilingual);
            }
            return;
          }
        }
        if (isMounted) setXpSubError("Video YouTube này không có sẵn phụ đề từ YouTube Server.");
      } catch (err: any) {
        if (isMounted) setXpSubError("Không thể kết nối tới Server API trích xuất phụ đề.");
      } finally {
        if (isMounted) setIsFetchingTracks(false);
      }
    })();

    return () => {
      isMounted = false;
    };
  }, [isOpen, activeVideo?.id]);

  const fetchPreviewSubtitles = async (baseUrl: string, targetLang: string, bilingual: boolean) => {
    if (!activeVideo || !baseUrl) return;
    setIsExtractingPreview(true);
    setXpSubError(null);

    try {
      const res = await fetch("/api/youtube/subtitles/inject", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          videoId: activeVideo.id,
          videoTitle: activeVideo.title,
          trackBaseUrl: baseUrl,
          targetLang,
          isBilingual: bilingual,
        }),
      });

      if (res.ok) {
        const data = await res.json();
        if (data.success && Array.isArray(data.subtitles) && data.subtitles.length > 0) {
          setXpSubPreviewSentences(data.subtitles);
          return;
        }
      }
    } catch (e: any) {
      console.warn("Preview fetch warning:", e);
    } finally {
      setIsExtractingPreview(false);
    }
  };

  const handleDownloadXpSubtitle = async (format: "srt" | "vtt" | "txt" | "json") => {
    if (!activeVideo || !selectedTrackUrl) return;

    try {
      addToast({
        type: "info",
        title: `Đang tạo file .${format.toUpperCase()}...`,
        message: "Vui lòng chờ trong giây lát...",
      });

      const res = await fetch("/api/youtube/subtitles/download", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          videoId: activeVideo.id,
          trackBaseUrl: selectedTrackUrl,
          format,
          isBilingual,
          targetLang: selectedTargetLang,
        }),
      });

      if (res.ok) {
        const blob = await res.blob();
        const downloadUrl = window.URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = downloadUrl;
        a.download = `[XP-Sub]_${activeVideo.id}_${isBilingual ? "bilingual" : "mono"}.${format}`;
        document.body.appendChild(a);
        a.click();
        a.remove();
        window.URL.revokeObjectURL(downloadUrl);

        addToast({
          type: "success",
          title: `Tải file .${format.toUpperCase()} thành công!`,
          message: `File đã được lưu vào thư mục Download của thiết bị.`,
        });
      } else {
        addToast({ type: "error", title: "Lỗi tải file", message: "Không thể tạo file tải xuống từ Server." });
      }
    } catch (e) {
      addToast({ type: "error", title: "Lỗi kết nối", message: "Không thể tải file phụ đề." });
    }
  };

  const handleApply = () => {
    if (!activeVideo || xpSubPreviewSentences.length === 0) return;
    onInjectSubtitles(xpSubPreviewSentences);
    onClose();
    addToast({
      type: "success",
      title: `Đã tự động cập nhật ${xpSubPreviewSentences.length} câu phụ đề vào web!`,
      message: "Timeline mốc mili-giây đã xuất hiện chuẩn 100% trên giao diện bài học!",
    });
  };

  if (!isOpen || !activeVideo) return null;

  return (
    <AnimatePresence>
      <div
        className="fixed inset-0 z-50 flex items-center justify-center md:pl-64 p-3 sm:p-4 bg-slate-950/70 backdrop-blur-md"
        onClick={onClose}
      >
        <motion.div
          initial={{ opacity: 0, scale: 0.95, y: 10 }}
          animate={{ opacity: 1, scale: 1, y: 0 }}
          exit={{ opacity: 0, scale: 0.95, y: 10 }}
          onClick={(e) => e.stopPropagation()}
          className="w-full max-w-4xl lg:max-w-5xl bg-white dark:bg-slate-900 rounded-2xl border border-slate-200/90 dark:border-slate-800 shadow-2xl overflow-hidden flex flex-col max-h-[90vh] select-none font-sans"
        >
          {/* Modal Header */}
          <div className="p-4 sm:p-5 border-b border-slate-100 dark:border-slate-800 flex items-center justify-between shrink-0 bg-white dark:bg-slate-900">
            <div className="flex items-center gap-3 min-w-0">
              <div className="w-10 h-10 rounded-xl bg-purple-500/10 text-purple-600 dark:text-purple-400 border border-purple-500/20 flex items-center justify-center shrink-0 shadow-2xs">
                <Sparkles className="w-5 h-5 fill-purple-500/30 text-purple-600 dark:text-purple-400 stroke-[2]" />
              </div>
              <div className="min-w-0">
                <div className="flex items-center gap-2 flex-wrap">
                  <h3 className="text-base font-bold font-display text-slate-900 dark:text-white">
                    XP-Sub AI Extractor Engine
                  </h3>
                  <span className="px-2 py-0.5 rounded-md bg-purple-50 dark:bg-purple-950/60 text-purple-700 dark:text-purple-300 text-[10px] font-mono font-bold border border-purple-200/60 dark:border-purple-800/40">
                    AI ENGINE
                  </span>
                </div>
                <p className="text-xs font-medium text-slate-500 dark:text-slate-400 truncate mt-0.5">
                  Trích xuất & đồng bộ phụ đề song ngữ tự động cho video: {activeVideo.title}
                </p>
              </div>
            </div>
            <button
              type="button"
              onClick={onClose}
              className="p-2 rounded-xl bg-slate-100 hover:bg-slate-200 dark:bg-slate-800 dark:hover:bg-slate-700 text-slate-400 hover:text-slate-700 dark:hover:text-white transition-all cursor-pointer"
              title="Đóng cửa sổ"
            >
              <X className="w-4 h-4" />
            </button>
          </div>

          {/* Modal Body */}
          <div className="p-4 sm:p-5 space-y-4 overflow-y-auto flex-1 min-h-0 text-xs">
            {/* Stage 1: Track & Translation Selection Controls */}
            <div className="p-4 rounded-xl bg-slate-50/90 dark:bg-slate-950/90 border border-slate-200/80 dark:border-slate-800/80 space-y-3.5 shadow-2xs">
              <div className="flex items-center justify-between border-b border-slate-200/60 dark:border-slate-800/80 pb-2.5">
                <span className="font-bold uppercase tracking-wider text-purple-700 dark:text-purple-300 text-[11px] flex items-center gap-1.5 font-display">
                  <Settings2 className="w-3.5 h-3.5 text-purple-600 dark:text-purple-400" /> BƯỚC 1: CHỌN NGUỒN PHỤ ĐỀ & NGÔN NGỮ DỊCH
                </span>
                {isFetchingTracks && (
                  <span className="text-[11px] font-bold text-amber-600 dark:text-amber-400 flex items-center gap-1.5 animate-pulse">
                    <Loader2 className="w-3.5 h-3.5 animate-spin" /> Đang tải dữ liệu từ YouTube...
                  </span>
                )}
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-3.5">
                {/* Track Selection */}
                <div className="space-y-1.5">
                  <label className="font-bold text-slate-700 dark:text-slate-200 block text-[11px]">
                    1. Phụ đề gốc từ YouTube ({xpSubTracks.length} bản khả dụng):
                  </label>
                  <select
                    value={selectedTrackUrl}
                    onChange={(e) => {
                      setSelectedTrackUrl(e.target.value);
                      fetchPreviewSubtitles(e.target.value, selectedTargetLang, isBilingual);
                    }}
                    disabled={isFetchingTracks || xpSubTracks.length === 0}
                    className="w-full p-2.5 rounded-xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-700 text-slate-900 dark:text-white font-bold text-xs shadow-2xs focus:ring-2 focus:ring-purple-500/20 focus:border-purple-500 focus:outline-hidden transition-all"
                  >
                    {xpSubTracks.length === 0 ? (
                      <option value="">-- Đang tìm phụ đề khả dụng --</option>
                    ) : (
                      xpSubTracks.map((t, i) => (
                        <option key={i} value={t.baseUrl}>
                          {t.languageName} {t.isAutoGenerated ? "(Tự động ASR)" : "(Thủ công)"}
                        </option>
                      ))
                    )}
                  </select>
                </div>

                {/* Translation Controls */}
                <div className="space-y-1.5">
                  <div className="flex items-center justify-between">
                    <label className="font-bold text-slate-700 dark:text-slate-200 block text-[11px]">
                      2. Tự động dịch sang Tiếng Việt:
                    </label>
                    <label className="inline-flex items-center gap-1.5 cursor-pointer select-none">
                      <input
                        type="checkbox"
                        checked={isBilingual}
                        onChange={(e) => {
                          setIsBilingual(e.target.checked);
                          fetchPreviewSubtitles(selectedTrackUrl, selectedTargetLang, e.target.checked);
                        }}
                        className="rounded-md border-slate-300 text-purple-600 focus:ring-purple-500 cursor-pointer"
                      />
                      <span className="text-[11px] font-bold text-purple-700 dark:text-purple-300">Song ngữ</span>
                    </label>
                  </div>

                  <select
                    value={selectedTargetLang}
                    onChange={(e) => {
                      setSelectedTargetLang(e.target.value);
                      fetchPreviewSubtitles(selectedTrackUrl, e.target.value, isBilingual);
                    }}
                    disabled={!isBilingual || isFetchingTracks}
                    className="w-full p-2.5 rounded-xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-700 text-slate-900 dark:text-white font-bold text-xs shadow-2xs focus:ring-2 focus:ring-purple-500/20 focus:border-purple-500 focus:outline-hidden disabled:opacity-50 transition-all"
                  >
                    <option value="vi">🇻🇳 Tiếng Việt (Vietnamese)</option>
                    {xpSubTranslations.map((l) => (
                      <option key={l.languageCode} value={l.languageCode}>
                        {l.languageName}
                      </option>
                    ))}
                  </select>
                </div>
              </div>
            </div>

            {/* Stage 2: Interactive Live Preview Terminal */}
            <div className="space-y-2.5">
              <div className="flex items-center justify-between flex-wrap gap-2">
                <span className="font-bold uppercase tracking-wider text-slate-600 dark:text-slate-400 text-[11px] flex items-center gap-1.5 font-display">
                  <Eye className="w-3.5 h-3.5 text-emerald-500" /> BƯỚC 2: XEM TRƯỚC VÀ KIỂM TRA PHỤ ĐỀ (LIVE PREVIEW)
                </span>

                <div className="flex items-center gap-2">
                  <div className="relative">
                    <Search className="w-3.5 h-3.5 absolute left-2.5 top-1/2 -translate-y-1/2 text-slate-400" />
                    <input
                      type="text"
                      value={searchPreviewQuery}
                      onChange={(e) => setSearchPreviewQuery(e.target.value)}
                      placeholder="Lọc từ vựng..."
                      className="h-8 pl-8 pr-3 rounded-xl bg-slate-100 dark:bg-slate-800 border border-slate-200/80 dark:border-slate-700/60 text-xs font-bold focus:outline-hidden focus:ring-2 focus:ring-purple-500/20 w-40"
                    />
                  </div>
                  <span className="px-2.5 py-1 rounded-xl bg-emerald-50 dark:bg-emerald-950/40 text-emerald-700 dark:text-emerald-300 font-mono text-[11px] font-bold border border-emerald-200/80 dark:border-emerald-800/60 shadow-2xs">
                    {xpSubPreviewSentences.length} Câu
                  </span>
                </div>
              </div>

              {/* Preview Container */}
              <div className="border border-slate-200/90 dark:border-slate-800 rounded-xl min-h-[240px] max-h-80 overflow-y-auto bg-slate-50/70 dark:bg-slate-950/70 p-3 font-sans text-xs space-y-2">
                {isExtractingPreview ? (
                  <div className="space-y-2.5">
                    {[1, 2, 3].map((n) => (
                      <div key={n} className="p-3 rounded-xl bg-white dark:bg-slate-900 border border-slate-200/80 dark:border-slate-800 space-y-2 animate-pulse">
                        <div className="h-3.5 bg-slate-200 dark:bg-slate-800 rounded-md w-20" />
                        <div className="h-4 bg-slate-200 dark:bg-slate-700 rounded-md w-3/4" />
                        <div className="h-3.5 bg-slate-100 dark:bg-slate-800 rounded-md w-1/2" />
                      </div>
                    ))}
                  </div>
                ) : xpSubPreviewSentences.length === 0 ? (
                  <div className="py-10 text-center text-slate-400 font-medium">
                    Chưa chọn track phụ đề. Vui lòng chọn track từ danh sách ở Bước 1.
                  </div>
                ) : (
                  xpSubPreviewSentences
                    .filter(
                      (s) =>
                        !searchPreviewQuery ||
                        s.textEn.toLowerCase().includes(searchPreviewQuery.toLowerCase()) ||
                        s.textVn.toLowerCase().includes(searchPreviewQuery.toLowerCase())
                    )
                    .map((s, idx) => (
                      <div
                        key={idx}
                        className="p-3 rounded-xl bg-white dark:bg-slate-900 hover:bg-purple-50/30 dark:hover:bg-purple-950/20 border border-slate-200/80 dark:border-slate-800/80 flex items-start gap-3 group transition-all shadow-2xs"
                      >
                        <span className="px-2 py-0.5 rounded-md bg-purple-50 dark:bg-purple-950/60 text-purple-700 dark:text-purple-300 border border-purple-200/60 dark:border-purple-800/40 text-[10.5px] font-mono font-bold shrink-0">
                          {formatSubTime(s.startTime)}
                        </span>
                        <div className="space-y-0.5 flex-1 min-w-0">
                          <p className="text-slate-900 dark:text-slate-100 font-bold leading-snug break-words">
                            {s.textEn}
                          </p>
                          {s.textVn && (
                            <p className="text-slate-500 dark:text-slate-400 text-[11px] font-medium leading-relaxed">
                              {s.textVn}
                            </p>
                          )}
                        </div>
                        <button
                          type="button"
                          onClick={() => speakLessonText(s.textEn)}
                          className="p-1.5 rounded-lg hover:bg-slate-100 dark:hover:bg-slate-800 text-slate-400 hover:text-purple-600 dark:hover:text-purple-400 transition-colors cursor-pointer shrink-0 opacity-60 group-hover:opacity-100"
                          title="Nghe thử âm thanh"
                        >
                          <Volume2 className="w-4 h-4" />
                        </button>
                      </div>
                    ))
                )}
              </div>
            </div>

            {/* Error Alert */}
            {xpSubError && (
              <div className="p-3 rounded-xl bg-rose-50 dark:bg-rose-950/40 border border-rose-200 dark:border-rose-900/50 text-rose-700 dark:text-rose-300 text-xs font-medium flex items-center gap-2">
                <AlertTriangle className="w-4 h-4 text-rose-500 shrink-0" />
                <span>{xpSubError}</span>
              </div>
            )}
          </div>

          {/* Modal Footer & Action Toolbar */}
          <div className="p-4 sm:p-5 bg-slate-50 dark:bg-slate-950 border-t border-slate-100 dark:border-slate-800 flex flex-wrap items-center justify-between gap-2.5 shrink-0 rounded-b-2xl">
            <button
              type="button"
              onClick={onClose}
              className="h-9 px-4 rounded-xl bg-slate-100 hover:bg-slate-200 dark:bg-slate-800 dark:hover:bg-slate-700 text-slate-700 dark:text-slate-300 text-xs font-bold transition-all cursor-pointer"
            >
              Đóng
            </button>

            <div className="flex flex-wrap items-center gap-2">
              <button
                type="button"
                onClick={() => handleDownloadXpSubtitle("txt")}
                disabled={xpSubPreviewSentences.length === 0}
                className="h-9 px-3 rounded-xl bg-slate-100 hover:bg-slate-200 dark:bg-slate-800 dark:hover:bg-slate-700 text-slate-700 dark:text-slate-300 text-xs font-bold border border-slate-200/80 dark:border-slate-700/60 transition-all cursor-pointer flex items-center gap-1.5 disabled:opacity-40"
              >
                <FileText className="w-3.5 h-3.5 text-slate-500" />
                <span>.TXT</span>
              </button>

              <button
                type="button"
                onClick={() => handleDownloadXpSubtitle("vtt")}
                disabled={xpSubPreviewSentences.length === 0}
                className="h-9 px-3 rounded-xl bg-slate-100 hover:bg-slate-200 dark:bg-slate-800 dark:hover:bg-slate-700 text-slate-700 dark:text-slate-300 text-xs font-bold border border-slate-200/80 dark:border-slate-700/60 transition-all cursor-pointer flex items-center gap-1.5 disabled:opacity-40"
              >
                <FileCode className="w-3.5 h-3.5 text-amber-500" />
                <span>.VTT</span>
              </button>

              <button
                type="button"
                onClick={() => handleDownloadXpSubtitle("srt")}
                disabled={xpSubPreviewSentences.length === 0}
                className="h-9 px-3 rounded-xl bg-emerald-600 hover:bg-emerald-700 text-white text-xs font-bold transition-all cursor-pointer flex items-center gap-1.5 shadow-2xs disabled:opacity-40"
              >
                <Download className="w-3.5 h-3.5" />
                <span>Tải .SRT</span>
              </button>

              <button
                type="button"
                onClick={handleApply}
                disabled={xpSubPreviewSentences.length === 0}
                className="h-9 px-5 rounded-xl bg-[#0059bb] hover:bg-[#004899] disabled:opacity-40 disabled:cursor-not-allowed text-white text-xs font-bold shadow-md shadow-[#0059bb]/20 flex items-center gap-2 transition-all cursor-pointer font-display active:scale-95"
              >
                <Sparkles className="w-4 h-4 text-sky-200 fill-sky-200/40" />
                <span>1-Click Nạp Vào Video (0ms)</span>
              </button>
            </div>
          </div>
        </motion.div>
      </div>
    </AnimatePresence>
  );
};
