const prev20 = require('./expansion_pack_16_30.js');

module.exports = {
  ...prev20,

  // Theme 21: Plants & Fruits (10 extra)
  t_basic_plants_fruits: [
    { word: "pineapple", phonetic: "/ˈpaɪnæpl/", def: "A large juicy tropical fruit consisting of aromatic edible yellow flesh surrounded by a tough segmented skin and topped with a tuft of stiff leaves.", defVn: "quả dứa, trái thơm, khóm", pos: "noun", ex1: "Sweet and tangy ripe pineapple makes refreshing summer juice.", ex1Vn: "Quả dứa chín ngọt thanh và thơm lừng tạo nên món nước ép mùa hè sảng khoái.", ex2: "Grilled pineapple pairs wonderfully with savory barbecue meat.", ex2Vn: "Dứa nướng kết hợp vô cùng tuyệt vời với thịt nướng đậm đà.", syn: ["ananas"], ant: [] },
    { word: "watermelon", phonetic: "/ˈwɔːtərmelən/", def: "The large fruit of a plant of the gourd family, with smooth green skin, sweet watery red pulp, and black seeds.", defVn: "quả dưa hấu", pos: "noun", ex1: "Chilled slices of juicy watermelon quench your thirst on hot summer afternoons.", ex1Vn: "Những miếng dưa hấu ướp lạnh mọng nước giải khát tuyệt vời vào những buổi chiều hè oi bức.", ex2: "Watermelon is packed with refreshing electrolytes and vitamins.", ex2Vn: "Dưa hấu chứa đầy chất điện giải thanh mát và vitamin.", syn: ["melon"], ant: [] },
    { word: "strawberry", phonetic: "/ˈstrɔːberi/", def: "A sweet soft red fruit with a seed-studded surface.", defVn: "quả dâu tây", pos: "noun", ex1: "Fresh Dalat strawberries are renowned for their sweet fragrance and ruby red color.", ex1Vn: "Dâu tây tươi Đà Lạt nổi tiếng với hương thơm ngọt ngào và sắc đỏ như ngọc bích.", ex2: "Top your morning yogurt bowl with fresh sliced strawberries.", ex2Vn: "Hãy phủ dâu tây tươi thái lát lên bát sữa chua buổi sáng của bạn nhé.", syn: [], ant: [] },
    { word: "mango", phonetic: "/ˈmæŋɡoʊ/", def: "A fleshy oval yellowish-red tropical fruit that is eaten ripe or used green in pickles or salads.", defVn: "quả xoài (chín ngọt hoặc chua giòn)", pos: "noun", ex1: "Sweet ripe mangoes blended with condensed milk make heavenly smoothies.", ex1Vn: "Những quả xoài chín ngọt xay cùng sữa đặc tạo nên món sinh tố ngon tuyệt đỉnh.", ex2: "Crispy green mango dipped in chili salt is a beloved street food snack.", ex2Vn: "Xoài xanh giòn chấm muối ớt là món ăn vặt đường phố được muôn người yêu thích.", syn: [], ant: [] },
    { word: "coconut", phonetic: "/ˈkoʊkənʌt/", def: "The large, oval, brown seed of a tropical palm, consisting of a hard woody husk surrounding a white edible layer of flesh and a central cavity containing clear liquid.", defVn: "quả dừa, trái dừa", pos: "noun", ex1: "Drinking sweet fresh coconut water directly from the shell is revitalizing.", ex1Vn: "Uống nước dừa tươi ngọt lành trực tiếp từ quả dừa mang lại cảm giác sảng khoái tràn đầy.", ex2: "Coconut milk gives Vietnamese curry and sweet soups their rich creaminess.", ex2Vn: "Nước cốt dừa tạo độ béo ngậy đậm đà cho món cà ri và các món chè Việt Nam.", syn: [], ant: [] },
    { word: "grape", phonetic: "/ɡreɪp/", def: "A berry, typically green, purple, or black, growing in clusters on a grapevine, eaten as fruit, and used in making wine.", defVn: "quả nho, chùm nho", pos: "noun", ex1: "Seedless purple grapes are crisp, sweet, and bursting with antioxidants.", ex1Vn: "Nho tím không hạt giòn, ngọt và chứa đầy chất chống oxy hóa.", ex2: "A bunch of chilled green grapes makes a nutritious study snack.", ex2Vn: "Một chùm nho xanh ướp lạnh là món ăn nhẹ giàu dinh dưỡng khi học bài.", syn: [], ant: [] },
    { word: "peach", phonetic: "/piːtʃ/", def: "A round stone fruit with juicy yellow or pink flesh, thin fuzzy skin, and a large rough pit.", defVn: "quả đào (thơm ngọt)", pos: "noun", ex1: "Peach lemongrass tea with juicy peach slices is an extremely popular cafe beverage.", ex1Vn: "Trà đào cam sả cùng những lát đào mọng nước là thức uống quán cà phê vô cùng được ưa chuộng.", ex2: "Ripe summer peaches have a velvety skin and floral aroma.", ex2Vn: "Những quả đào mùa hè chín mọng có lớp vỏ mịn như nhung và hương thơm hoa cỏ quyến rũ.", syn: [], ant: [] },
    { word: "blossom", phonetic: "/ˈblɑːsəm/", def: "A flower or a mass of flowers, especially on a tree or bush.", defVn: "hoa nở rộ, đóa hoa trên cây", pos: "noun", ex1: "Pink cherry blossoms and peach blossoms herald the joyous arrival of spring.", ex1Vn: "Hoa anh đào hồng và hoa đào báo hiệu mùa xuân vui tươi đã về.", ex2: "Citrus orange trees burst into sweet fragrant blossoms in April.", ex2Vn: "Những cây cam nở rộ những đóa hoa thơm ngát vào tháng Tư.", syn: ["bloom", "flower"], ant: [] },
    { word: "branch", phonetic: "/bræntʃ/", def: "A part of a tree which grows out from the trunk or from a bough.", defVn: "cành cây, nhánh cây", pos: "noun", ex1: "Birds built a snug woven nest high up on an oak tree branch.", ex1Vn: "Những chú chim đã xây một chiếc tổ dệt ấm cúng trên cành cây sồi cao.", ex2: "The apple tree branches bowed low under the weight of ripe fruit.", ex2Vn: "Những cành cây táo trĩu nặng uốn cong xuống dưới sức nặng của quả chín.", syn: ["bough", "limb"], ant: ["trunk"] },
    { word: "stem", phonetic: "/stem/", def: "The main body or stalk of a plant or shrub, typically rising above ground.", defVn: "thân cây, cuống lá, cọng hoa", pos: "noun", ex1: "Trim the bottom of the rose stems at a forty-five degree angle before placing them in a vase.", ex1Vn: "Cắt vát phần đáy cuống hoa hồng một góc bốn mươi lăm độ trước khi cắm vào bình hoa nhé.", ex2: "Bamboo stems are flexible, lightweight, and remarkably strong.", ex2Vn: "Thân cây tre mềm dẻo, nhẹ nhàng và bền chắc phi thường.", syn: ["stalk", "trunk"], ant: ["root"] }
  ],

  // Theme 22: Health & Medical (10 extra)
  t_basic_health_medical: [
    { word: "bandage", phonetic: "/ˈbændɪdʒ/", def: "A strip of woven material used to bind up a wound or to protect an injured part of the body.", defVn: "băng gạc, băng dán vết thương", pos: "noun", ex1: "Clean the scratch with antiseptic liquid and apply a sterile bandage.", ex1Vn: "Rửa sạch vết xước bằng dung dịch sát trùng và dán một miếng băng gạc vô trùng nhé.", ex2: "The nurse wrapped an elastic bandage securely around the sprained ankle.", ex2Vn: "Y tá đã quấn một dải băng co giãn chắc chắn quanh mắt cá chân bị bong gân.", syn: ["dressing", "plaster"], ant: [] },
    { word: "stethoscope", phonetic: "/ˈsteθəskoʊp/", def: "A medical instrument for listening to the action of someone's heart or breathing.", defVn: "ống nghe y tế (khám tim phổi)", pos: "noun", ex1: "The physician placed the stethoscope gently on my chest to listen to my heartbeat.", ex1Vn: "Bác sĩ nhẹ nhàng đặt ống nghe lên ngực tôi để lắng nghe nhịp tim.", ex2: "A stethoscope is an iconic diagnostic tool carried by every doctor.", ex2Vn: "Ống nghe là công cụ chẩn đoán mang tính biểu tượng mà mỗi bác sĩ đều mang theo.", syn: [], ant: [] },
    { word: "thermometer", phonetic: "/θərˈmɑːmɪtər/", def: "An instrument for measuring and indicating temperature.", defVn: "nhiệt kế (đo thân nhiệt)", pos: "noun", ex1: "The digital electronic thermometer showed a body temperature of 37 degrees Celsius.", ex1Vn: "Chiếc nhiệt kế điện tử kỹ thuật số hiển thị thân nhiệt là 37 độ C.", ex2: "Keep a reliable digital thermometer inside your family medicine cabinet.", ex2Vn: "Hãy để một chiếc nhiệt kế điện tử đáng tin cậy bên trong tủ thuốc gia đình nhé.", syn: [], ant: [] },
    { word: "prescription", phonetic: "/prɪˈskrɪpʃn/", def: "An instruction written by a medical practitioner that authorizes a patient to be provided with a medicine or treatment.", defVn: "đơn thuốc, toa thuốc của bác sĩ", pos: "noun", ex1: "The doctor wrote a detailed prescription for antibiotics and vitamins.", ex1Vn: "Bác sĩ đã kê một đơn thuốc chi tiết gồm kháng sinh và vitamin.", ex2: "Present your valid prescription at the pharmacy counter to collect medication.", ex2Vn: "Xuất trình đơn thuốc hợp lệ tại quầy thuốc để nhận thuốc nhé.", syn: ["recipe", "script"], ant: [] },
    { word: "clinic", phonetic: "/ˈklɪnɪk/", def: "An establishment or hospital department where outpatients are given medical treatment or advice.", defVn: "phòng khám chuyên khoa, trạm y tế", pos: "noun", ex1: "She went to the local dental clinic for her routine six-month teeth cleaning.", ex1Vn: "Cô ấy đến phòng khám nha khoa địa phương để lấy cao răng định kỳ sáu tháng một lần.", ex2: "The community health clinic provides free vaccinations for infants.", ex2Vn: "Trạm y tế cộng đồng cung cấp vắc-xin miễn phí cho trẻ sơ sinh.", syn: ["health center", "infirmary"], ant: [] },
    { word: "ambulance", phonetic: "/ˈæmbjələns/", def: "A vehicle equipped for taking sick or injured people to and from hospital, especially in emergencies.", defVn: "xe cấp cứu, xe cứu thương", pos: "noun", ex1: "Vehicles must yield the right of way immediately when an ambulance flashes its sirens.", ex1Vn: "Các phương tiện giao thông phải nhường đường ngay lập tức khi xe cấp cứu hú còi ưu tiên.", ex2: "Paramedics inside the ambulance administered first-aid during transport.", ex2Vn: "Các nhân viên y tế bên trong xe cứu thương đã thực hiện sơ cứu trong suốt quá trình vận chuyển.", syn: ["emergency vehicle"], ant: [] },
    { word: "symptom", phonetic: "/ˈsɪmptəm/", def: "A physical or mental feature which is regarded as indicating a condition of disease.", defVn: "triệu chứng bệnh, dấu hiệu sức khỏe", pos: "noun", ex1: "A high fever, chills, and dry cough are typical symptoms of influenza.", ex1Vn: "Sốt cao, ớn lạnh và ho khan là những triệu chứng điển hình của bệnh cúm.", ex2: "Consult a qualified doctor if pain symptoms persist for more than three days.", ex2Vn: "Hãy tham khảo ý kiến bác sĩ chuyên khoa nếu các triệu chứng đau kéo dài hơn ba ngày nhé.", syn: ["sign", "indication"], ant: [] },
    { word: "allergy", phonetic: "/ˈælərdʒi/", def: "A damaging immune response by the body to a substance, especially a particular food, pollen, fur, or dust, to which it has become hypersensitive.", defVn: "dị ứng (thức ăn, thời tiết, phấn hoa)", pos: "noun", ex1: "Inform the restaurant server if you have a peanut or seafood allergy.", ex1Vn: "Hãy thông báo cho nhân viên phục vụ nhà hàng nếu bạn bị dị ứng đậu phộng hoặc hải sản nhé.", ex2: "Seasonal pollen allergies cause sneezing and itchy eyes in spring.", ex2Vn: "Dị ứng phấn hoa theo mùa gây hắt hơi và ngứa mắt vào mùa xuân.", syn: ["hypersensitivity"], ant: [] },
    { word: "injection", phonetic: "/ɪnˈdʒekʃn/", def: "An act of injecting someone or something with a hypodermic needle.", defVn: "mũi tiêm, sự tiêm thuốc", pos: "noun", ex1: "Annual flu vaccine injections protect vulnerable elderly citizens.", ex1Vn: "Các mũi tiêm vắc-xin cúm hàng năm bảo vệ người cao tuổi có thể trạng yếu.", ex2: "The gentle nurse administered the painless arm injection quickly.", ex2Vn: "Cô y tá dịu dàng đã tiêm một mũi tiêm không đau vào cánh tay rất nhanh chóng.", syn: ["shot", "jab", "inoculation"], ant: [] },
    { word: "dosage", phonetic: "/ˈdoʊsɪdʒ/", def: "The size or frequency of a dose of a medicine or drug.", defVn: "liều lượng thuốc, liều dùng", pos: "noun", ex1: "Always adhere strictly to the recommended dosage specified on the medication label.", ex1Vn: "Hãy luôn tuân thủ nghiêm ngặt liều lượng khuyến cáo được ghi trên nhãn thuốc nhé.", ex2: "Children require a significantly lower medicine dosage than adults.", ex2Vn: "Trẻ em cần liều lượng thuốc thấp hơn đáng kể so với người lớn.", syn: ["dose", "portion"], ant: [] }
  ],

  // Theme 23: Kitchen Utensils (11 extra)
  t_basic_kitchen_utensils: [
    { word: "kettle", phonetic: "/ˈketl/", def: "A container or device in which water is boiled, having a lid, spout, and handle.", defVn: "ấm đun nước siêu tốc", pos: "noun", ex1: "Boil water in the electric stainless-steel kettle to brew morning green tea.", ex1Vn: "Đun sôi nước trong ấm đun inox siêu tốc để pha trà xanh buổi sáng nhé.", ex2: "The whistle of the stovetop kettle announced that water had reached a rolling boil.", ex2Vn: "Tiếng còi reo của ấm đun trên bếp báo hiệu nước đã sôi sùng sục.", syn: ["teapot", "boiler"], ant: [] },
    { word: "toaster", phonetic: "/ˈtoʊstər/", def: "An electrical device for making toast.", defVn: "máy nướng bánh mì lát", pos: "noun", ex1: "Pop two slices of whole-wheat bread into the toaster for breakfast.", ex1Vn: "Cho hai lát bánh mì nguyên cám vào máy nướng bánh mì cho bữa sáng nhé.", ex2: "The automatic toaster ejects golden crispy toast in two minutes.", ex2Vn: "Máy nướng bánh mì tự động đẩy ra những lát bánh mì giòn vàng rộm sau hai phút.", syn: [], ant: [] },
    { word: "blender", phonetic: "/ˈblendər/", def: "An electric machine used in the kitchen for breaking down foods or making smooth mixtures from them.", defVn: "máy xay sinh tố", pos: "noun", ex1: "Combine fresh mango, banana, and Greek yogurt inside the high-speed blender.", ex1Vn: "Cho xoài tươi, chuối và sữa chua Hy Lạp vào máy xay sinh tố tốc độ cao nhé.", ex2: "Clean the sharp blender blades carefully under warm running water.", ex2Vn: "Vệ sinh các lưỡi dao sắc của máy xay sinh tố cẩn thận dưới vòi nước ấm nhé.", syn: ["mixer", "food processor"], ant: [] },
    { word: "microwave", phonetic: "/ˈmaɪkrəweɪv/", def: "An oven that uses microwaves to cook or heat food quickly.", defVn: "lò vi sóng (hâm nóng thức ăn)", pos: "noun", ex1: "Reheat the leftover vegetable soup in the microwave for two minutes.", ex1Vn: "Hâm nóng món canh rau củ còn thừa trong lò vi sóng trong hai phút nhé.", ex2: "Use microwave-safe ceramic containers when heating meals.", ex2Vn: "Hãy dùng đồ đựng bằng sứ dùng được cho lò vi sóng khi hâm nóng thức ăn nhé.", syn: ["microwave oven"], ant: [] },
    { word: "cutting board", phonetic: "/ˈkʌtɪŋ bɔːrd/", def: "A durable board on which to place material for cutting.", defVn: "chiếc thớt (thái thịt, rau củ)", pos: "noun", ex1: "Use separate wooden and plastic cutting boards for raw meats and fresh salad vegetables.", ex1Vn: "Dùng thớt gỗ và thớt nhựa riêng biệt cho thịt sống và rau làm sa-lát nhé.", ex2: "Wash and sanitize the cutting board thoroughly after preparing poultry.", ex2Vn: "Rửa và khử trùng thớt thật kỹ sau khi sơ chế thịt gia cầm nhé.", syn: ["chopping board"], ant: [] },
    { word: "spatula", phonetic: "/ˈspætʃələ/", def: "An implement with a broad, flat, blunt blade, used for mixing and spreading things, especially in cooking and painting.", defVn: "chiếc xẻng lật thức ăn, phới dẹt", pos: "noun", ex1: "Use a silicone spatula to flip the sunny-side-up eggs without breaking the yolks.", ex1Vn: "Dùng chiếc xẻng lật bằng silicon để lật trứng ốp la mà không làm vỡ lòng đỏ nhé.", ex2: "The baker scraped every drop of batter using a flexible spatula.", ex2Vn: "Thợ làm bánh vét từng giọt bột bánh bằng chiếc phới dẹt dẻo dai.", syn: ["flipper", "turner"], ant: [] },
    { word: "peeler", phonetic: "/ˈpiːlər/", def: "A device for removing the skin from fruit and vegetables.", defVn: "dụng cụ nạo vỏ, dao bào củ quả", pos: "noun", ex1: "Peel the potatoes and carrots swiftly using a stainless steel vegetable peeler.", ex1Vn: "Nạo vỏ khoai tây và cà rốt nhanh thoăn thoắt bằng chiếc dao bào inox nhé.", ex2: "A sharp peeler minimizes food waste while removing tough peels.", ex2Vn: "Một chiếc dao bào sắc bén giúp giảm thiểu lãng phí thực phẩm khi loại bỏ lớp vỏ dai.", syn: ["scraper"], ant: [] },
    { word: "whisk", phonetic: "/wɪsk/", def: "A utensil for whipping eggs or cream.", defVn: "cây đánh trứng, phới lồng đánh kem", pos: "noun", ex1: "Whisk the egg whites and sugar vigorously until stiff peaks form.", ex1Vn: "Đánh lòng trắng trứng và đường thật mạnh tay bằng phới lồng cho đến khi bông cứng nhé.", ex2: "A balloon wire whisk is essential for smooth lump-free sauces.", ex2Vn: "Cây đánh trứng bằng dây thép là dụng cụ thiết yếu để tạo các loại nước sốt sánh mịn không vón cục.", syn: ["beater"], ant: [] },
    { word: "strainer", phonetic: "/ˈstreɪnər/", def: "A device having holes punched in it or made of crossed wires for separating solid matter from a liquid.", defVn: "cái rây lọc, rổ lọc nước", pos: "noun", ex1: "Pour the boiled pasta into a metal strainer over the kitchen sink to drain.", ex1Vn: "Đổ mì luộc vào chiếc rây lọc kim loại trên bồn rửa bát để ráo nước nhé.", ex2: "Use a fine mesh tea strainer to catch loose leaves.", ex2Vn: "Dùng rây lọc mắt nhỏ để giữ lại bã trà rời nhé.", syn: ["colander", "sieve"], ant: [] },
    { word: "measuring cup", phonetic: "/ˈmeʒərɪŋ kʌp/", def: "A cup marked in graded amounts, used to measure ingredients.", defVn: "cốc đong đo lường nguyên liệu", pos: "noun", ex1: "Pour exactly two hundred milliliters of whole milk using the graduated glass measuring cup.", ex1Vn: "Rót đúng hai trăm mi-li-lít sữa tươi bằng cốc đong thủy tinh có vạch chia nhé.", ex2: "Accurate measuring cups are crucial for successful baking recipes.", ex2Vn: "Cốc đong đo lường chính xác là yếu tố then chốt cho sự thành công của các công thức làm bánh.", syn: ["beaker"], ant: [] },
    { word: "grater", phonetic: "/ˈɡreɪtər/", def: "A device having a surface covered with holes edged by sharp points, used for grating cheese and other foods.", defVn: "cái nạo, dụng cụ mài phô mai", pos: "noun", ex1: "Grate fresh Parmesan cheese directly over your hot spaghetti using a box grater.", ex1Vn: "Bào phô mai Parmesan tươi trực tiếp lên đĩa mì Ý nóng hổi bằng chiếc dụng cụ mài nhé.", ex2: "A microplane grater zests lemon and lime rinds effortlessly.", ex2Vn: "Dụng cụ mài nhỏ giúp bào vỏ chanh dễ dàng lấy tinh dầu thơm.", syn: ["shredder"], ant: [] }
  ],

  // Theme 24: Office Tech (10 extra)
  t_basic_office_tech: [
    { word: "monitor", phonetic: "/ˈmɑːnɪtər/", def: "A display screen used to provide visual output from a computer, cable or other video generating device.", defVn: "màn hình máy tính (hiển thị)", pos: "noun", ex1: "Working with dual high-definition monitors boosts daily productivity significantly.", ex1Vn: "Làm việc với hai màn hình máy tính độ phân giải cao giúp tăng năng suất làm việc hàng ngày đáng kể.", ex2: "Adjust your monitor height to eye level to prevent neck fatigue.", ex2Vn: "Điều chỉnh chiều cao màn hình ngang tầm mắt để tránh mỏi cổ nhé.", syn: ["screen", "display"], ant: [] },
    { word: "webcam", phonetic: "/ˈwebkæm/", def: "A video camera connected to a computer, typically used to stream video over the internet.", defVn: "máy ảnh quay phim trên máy tính (webcam)", pos: "noun", ex1: "Switch on your HD webcam and test your audio before joining the international zoom meeting.", ex1Vn: "Bật webcam độ nét cao và kiểm tra âm thanh trước khi tham gia cuộc họp Zoom quốc tế nhé.", ex2: "The built-in laptop webcam automatically adjusts to ambient lighting.", ex2Vn: "Webcam tích hợp trên laptop tự động điều chỉnh theo ánh sáng môi trường.", syn: ["video camera"], ant: [] },
    { word: "microphone", phonetic: "/ˈmaɪkrəfoʊn/", def: "An instrument for converting sound waves into electrical energy variations, which may then be amplified, transmitted, or recorded.", defVn: "mi-crô, micro thu âm", pos: "noun", ex1: "A noise-cancelling USB microphone ensures crystal-clear voice transmission during presentations.", ex1Vn: "Mi-crô cổng USB chống ồn đảm bảo giọng nói trong trẻo rõ ràng trong các bài thuyết trình.", ex2: "Please mute your microphone while the keynote speaker is speaking.", ex2Vn: "Làm ơn tắt tiếng micro của bạn trong khi diễn giả chính đang phát biểu nhé.", syn: ["mic"], ant: [] },
    { word: "printer", phonetic: "/ˈprɪntər/", def: "A machine for printing text or pictures onto paper, especially one linked to a computer.", defVn: "máy in văn phòng (in tài liệu)", pos: "noun", ex1: "Load fifty sheets of A4 paper into the wireless laser printer tray.", ex1Vn: "Nạp năm mươi tờ giấy A4 vào khay máy in laser không dây nhé.", ex2: "Color printers produce high-quality graphics and presentation charts.", ex2Vn: "Máy in màu tạo ra các đồ họa và biểu đồ thuyết trình chất lượng cao.", syn: [], ant: [] },
    { word: "scanner", phonetic: "/ˈskænər/", def: "A device for capturing images from photographic prints, posters, magazine pages, and similar sources for computer editing and display.", defVn: "máy quét tài liệu số (máy scan)", pos: "noun", ex1: "Scan the signed contract with the flatbed document scanner and save it as a PDF.", ex1Vn: "Quét bản hợp đồng đã ký bằng máy quét tài liệu và lưu dưới dạng tệp PDF nhé.", ex2: "Modern office multi-function copiers include fast automatic scanners.", ex2Vn: "Máy photocopy đa năng văn phòng hiện đại đều có máy quét tự động siêu tốc.", syn: [], ant: [] },
    { word: "folder", phonetic: "/ˈfoʊldər/", def: "A folding cover or container for keeping loose papers or digital files together.", defVn: "thư mục máy tính, cặp đựng tài liệu", pos: "noun", ex1: "Organize your project spreadsheets neatly inside categorized cloud folders.", ex1Vn: "Sắp xếp các bảng tính dự án thật gọn gàng bên trong các thư mục đám mây đã được phân loại nhé.", ex2: "Keep all client invoices filed in a dedicated blue folder.", ex2Vn: "Lưu tất cả hóa đơn của khách hàng vào một kẹp hồ sơ màu xanh chuyên dụng.", syn: ["directory", "binder"], ant: [] },
    { word: "spreadsheet", phonetic: "/ˈspredʃiːt/", def: "An electronic document in which data is arranged in the rows and columns of a grid and can be manipulated and used in calculations.", defVn: "bảng tính điện tử (như Excel)", pos: "noun", ex1: "Create a financial spreadsheet to track quarterly expenses and revenues.", ex1Vn: "Tạo một bảng tính tài chính để theo dõi các khoản chi phí và doanh thu hàng quý nhé.", ex2: "Formulas in the digital spreadsheet calculate totals automatically.", ex2Vn: "Các công thức trong bảng tính điện tử tự động tính toán tổng số tiền.", syn: ["worksheet"], ant: [] },
    { word: "document", phonetic: "/ˈdɑːkjumənt/", def: "A piece of written, printed, or electronic matter that provides information or evidence or that serves as an official record.", defVn: "tài liệu, văn bản chính thức", pos: "noun", ex1: "Proofread the legal document thoroughly before affixing your signature.", ex1Vn: "Hãy đọc soát lại tài liệu pháp lý thật kỹ trước khi đặt bút ký tên nhé.", ex2: "Save a backup copy of your confidential text document to encrypted storage.", ex2Vn: "Lưu một bản sao lưu tài liệu văn bản bảo mật vào ổ lưu trữ được mã hóa.", syn: ["file", "record"], ant: [] },
    { word: "projector", phonetic: "/prəˈdʒektər/", def: "A device that is used to project rays of light, especially an apparatus for projecting images on a screen.", defVn: "máy chiếu hội thảo", pos: "noun", ex1: "Connect your laptop to the overhead projector to display the slide presentation.", ex1Vn: "Kết nối máy tính xách tay với máy chiếu để trình chiếu các trang slide nhé.", ex2: "The conference room is equipped with a vivid 4K laser projector.", ex2Vn: "Phòng hội thảo được trang bị một máy chiếu laser 4K sắc nét.", syn: [], ant: [] },
    { word: "server", phonetic: "/ˈsɜːrvər/", def: "A computer or computer program which manages access to a centralized resource or service in a network.", defVn: "máy chủ hệ thống mạng (server)", pos: "noun", ex1: "The company enterprise server securely stores databases and email archives.", ex1Vn: "Máy chủ doanh nghiệp của công ty lưu trữ an toàn các cơ sở dữ liệu và lưu trữ thư điện tử.", ex2: "System engineers maintain twenty-four-hour server uptime.", ex2Vn: "Các kỹ sư hệ thống duy trì thời gian hoạt động của máy chủ 24/24.", syn: ["host computer"], ant: [] }
  ],

  // Theme 25: City & Buildings (10 extra)
  t_basic_city_buildings: [
    { word: "skyscraper", phonetic: "/ˈskaɪskreɪpər/", def: "A very tall building of many storeys.", defVn: "tòa nhà chọc trời, cao ốc", pos: "noun", ex1: "Landmark 81 is the tallest iconic skyscraper in Ho Chi Minh City.", ex1Vn: "Landmark 81 là tòa nhà chọc trời biểu tượng cao nhất tại Thành phố Hồ Chí Minh.", ex2: "Glass skyscrapers shimmer against the twilight urban skyline.", ex2Vn: "Những tòa cao ốc bằng kính lấp lánh trên đường chân trời đô thị lúc hoàng hôn.", syn: ["tower", "high-rise"], ant: [] },
    { word: "monument", phonetic: "/ˈmɑːnjumənt/", def: "A statue, building, or other structure erected to commemorate a notable person or event.", defVn: "tượng đài, đài tưởng niệm", pos: "noun", ex1: "Tourists visit the historic monument to learn about national heroes.", ex1Vn: "Du khách ghé thăm tượng đài lịch sử để tìm hiểu về những vị anh hùng dân tộc.", ex2: "Floral wreaths were placed respectfully at the peace monument.", ex2Vn: "Những vòng hoa tươi được đặt trang nghiêm tại đài tưởng niệm hòa bình.", syn: ["memorial", "statue"], ant: [] },
    { word: "fountain", phonetic: "/ˈfaʊntn/", def: "An ornamental structure in a pool or lake from which one or more jets of water are pumped into the air.", defVn: "đài phun nước công cộng", pos: "noun", ex1: "Illuminated musical water fountains dance to classical melodies in the town square.", ex1Vn: "Đài phun nước nghệ thuật phát sáng nhảy múa theo những giai điệu cổ điển ở quảng trường thị trấn.", ex2: "Children tossed coins into the stone fountain making heartfelt wishes.", ex2Vn: "Những đứa trẻ tung đồng xu vào đài phun nước bằng đá gửi gắm những điều ước chân thành.", syn: ["water feature"], ant: [] },
    { word: "stadium", phonetic: "/ˈsteɪdiəm/", def: "A sports ground with tiers of seats for spectators.", defVn: "sân vận động thể thao", pos: "noun", ex1: "Over forty thousand enthusiastic fans cheered at My Dinh National Stadium.", ex1Vn: "Hơn bốn mươi nghìn người hâm mộ cuồng nhiệt đã reo hò tại Sân vận động Quốc gia Mỹ Đình.", ex2: "The multi-purpose Olympic stadium hosts international track and field championships.", ex2Vn: "Sân vận động Olympic đa năng tổ chức các giải vô địch điền kinh quốc tế.", syn: ["arena", "coliseum"], ant: [] },
    { word: "palace", phonetic: "/ˈpæləs/", def: "A large and impressive building forming the official residence of a ruler, state dignitary, or other person of high rank.", defVn: "cung điện, hoàng cung tráng lệ", pos: "noun", ex1: "The Independence Palace is an architectural landmark steeped in modern Vietnamese history.", ex1Vn: "Dinh Độc Lập là một công trình kiến trúc mang đậm dấu ấn lịch sử hiện đại của Việt Nam.", ex2: "Gilded ceilings and marble corridors adorn the royal palace.", ex2Vn: "Trần nhà dát vàng và những hành lang lát đá cẩm thạch tô điểm cho hoàng cung lộng lẫy.", syn: ["castle", "chateau"], ant: [] },
    { word: "cathedral", phonetic: "/kəˈθiːdrəl/", def: "The principal church of a diocese, with which the bishop is officially associated.", defVn: "nhà thờ lớn, nhà thờ chính tòa", pos: "noun", ex1: "St. Joseph's Cathedral in Hanoi features striking neo-Gothic architecture.", ex1Vn: "Nhà thờ Lớn Hà Nội mang nét kiến trúc Tân Gothic vô cùng ấn tượng.", ex2: "Chime bells from the brick cathedral ring across the city on festive mornings.", ex2Vn: "Tiếng chuông ngân từ nhà thờ chính tòa bằng gạch vang vọng khắp thành phố trong những buổi sáng lễ hội.", syn: ["basilica", "church"], ant: [] },
    { word: "boulevard", phonetic: "/ˈbʊləvɑːrd/", def: "A wide street in a town or city, typically one lined with trees.", defVn: "đại lộ rộng lớn, trục đường chính rợp bóng cây", pos: "noun", ex1: "Nguyen Hue walking boulevard comes alive with street performers and bustling crowds every weekend.", ex1Vn: "Phố đi bộ đại lộ Nguyễn Huệ trở nên sống động với các nghệ sĩ đường phố và đám đông nhộn nhịp mỗi cuối tuần.", ex2: "Tall tamarind and mahogany trees shade the wide city boulevard.", ex2Vn: "Những cây me và xà cừ cao vút tỏa bóng mát xuống đại lộ rộng lớn của thành phố.", syn: ["avenue", "broadway"], ant: ["alley"] },
    { word: "plaza", phonetic: "/ˈplɑːzə/", def: "A public square, marketplace, or similar open space in a built-up area.", defVn: "quảng trường thương mại, khu phức hợp mua sắm mở", pos: "noun", ex1: "Families gather at the pedestrian plaza to enjoy outdoor concerts and street snacks.", ex1Vn: "Các gia đình tụ tập tại quảng trường đi bộ để thưởng thức các buổi hòa nhạc ngoài trời và đồ ăn vặt.", ex2: "The modern central plaza features boutique shops and open-air cafes.", ex2Vn: "Khu quảng trường trung tâm hiện đại có các cửa hàng thời trang và quán cà phê ngoài trời.", syn: ["square", "piazza"], ant: [] },
    { word: "convention center", phonetic: "/kənˈvenʃn ˈsentər/", def: "A large building that is designed to hold a convention, where individuals and groups gather to promote and share common interests.", defVn: "trung tâm hội nghị triển lãm quốc tế", pos: "noun", ex1: "The national convention center hosted a prestigious technology summit with global leaders.", ex1Vn: "Trung tâm hội nghị quốc gia đã đăng cai tổ chức hội nghị thượng đỉnh công nghệ uy tín với các nhà lãnh đạo toàn cầu.", ex2: "Exhibitors set up creative booths across the vast exhibition hall.", ex2Vn: "Các đơn vị tham gia triển lãm dựng các gian hàng sáng tạo khắp sảnh triển lãm rộng lớn.", syn: ["expo center"], ant: [] },
    { word: "town hall", phonetic: "/ˈtaʊn hɔːl/", def: "A building housing the administration of a town.", defVn: "tòa thị chính, trụ sở ủy ban nhân dân thành phố", pos: "noun", ex1: "The colonial-era town hall features an ornate French facade and clock tower.", ex1Vn: "Tòa thị chính thời thuộc địa có mặt tiền kiểu Pháp hoa mỹ cùng tháp đồng hồ.", ex2: "Civic meetings and public forums are convened inside the town hall auditorium.", ex2Vn: "Các cuộc họp dân sự và diễn đàn công chúng được triệu tập bên trong khán phòng tòa thị chính.", syn: ["city hall", "civic center"], ant: [] }
  ],

  // Theme 26: Personality Traits (11 extra)
  t_basic_personality_traits: [
    { word: "creative", phonetic: "/kriˈeɪtɪv/", def: "Relating to or involving the use of the imagination or original ideas to create something.", defVn: "sáng tạo, giàu trí tưởng tượng", pos: "adj", ex1: "She came up with a creative marketing strategy that doubled sales.", ex1Vn: "Cô ấy đã nghĩ ra một chiến lược tiếp thị sáng tạo giúp nhân đôi doanh số bán hàng.", ex2: "Creative artists transform ordinary materials into breathtaking masterpieces.", ex2Vn: "Các nghệ sĩ sáng tạo biến những vật liệu bình thường thành những kiệt tác ngoạn mục.", syn: ["innovative", "imaginative"], ant: ["unimaginative", "dull"] },
    { word: "ambitious", phonetic: "/æmˈbɪʃəs/", def: "Having or showing a strong desire and determination to succeed.", defVn: "có hoài bão lớn, nhiều tham vọng tích cực", pos: "adj", ex1: "The ambitious young entrepreneur founded three thriving green tech startups.", ex1Vn: "Người doanh nhân trẻ giàu hoài bão đã sáng lập ba công ty khởi nghiệp công nghệ xanh rất phát triển.", ex2: "Set ambitious yet achievable learning goals for the new academic year.", ex2Vn: "Hãy đặt ra những mục tiêu học tập giàu tham vọng nhưng hoàn toàn có thể đạt được cho năm học mới nhé.", syn: ["driven", "aspiring"], ant: ["unmotivated", "lazy"] },
    { word: "modest", phonetic: "/ˈmɑːdɪst/", def: "Unassuming or moderate in the estimation of one's abilities or achievements.", defVn: "khiêm tốn, nhũn nhặn", pos: "adj", ex1: "Despite winning international medals, the champion remained delightfully modest.", ex1Vn: "Dù giành được nhiều huy chương quốc tế, nhà vô địch vẫn giữ trọn sự khiêm tốn đáng quý.", ex2: "A modest attitude earns lasting respect from teammates.", ex2Vn: "Thái độ khiêm tốn luôn nhận được sự tôn trọng bền lâu từ các đồng đội.", syn: ["humble", "unassuming"], ant: ["arrogant", "boastful"] },
    { word: "humorous", phonetic: "/ˈhjuːmərəs/", def: "Causing lighthearted laughter and amusement; comic.", defVn: "hài hước, hóm hỉnh, vui tính", pos: "adj", ex1: "Our history teacher tells humorous anecdotes that make lessons unforgettable.", ex1Vn: "Thầy giáo dạy lịch sử của chúng tôi kể những mẩu chuyện cười hóm hỉnh làm cho bài học trở nên khó quên.", ex2: "He has a delightfully humorous personality that makes friends easily.", ex2Vn: "Anh ấy có tính cách hài hước duyên dáng giúp dễ dàng kết bạn với mọi người.", syn: ["witty", "amusing", "funny"], ant: ["serious", "solemn"] },
    { word: "thoughtful", phonetic: "/ˈθɔːtfl/", def: "Showing consideration for the needs of other people; absorbed in thought.", defVn: "chu đáo, biết quan tâm, trầm ngâm suy nghĩ", pos: "adj", ex1: "Thank you for the thoughtful birthday card and handwritten letter.", ex1Vn: "Cảm ơn bạn vì tấm thiệp sinh nhật chu đáo và bức thư viết tay chan chứa tình cảm nhé.", ex2: "A thoughtful leader always listens attentively to team suggestions.", ex2Vn: "Một người lãnh đạo chu đáo luôn chú ý lắng nghe các đề xuất của toàn đội.", syn: ["considerate", "attentive"], ant: ["inconsiderate", "thoughtless"] },
    { word: "reliable", phonetic: "/rɪˈlaɪəbl/", def: "Consistently good in quality or performance; able to be trusted.", defVn: "đáng tin cậy, chắc chắn", pos: "adj", ex1: "He is a reliable friend who always keeps his promises and arrives on time.", ex1Vn: "Anh ấy là một người bạn đáng tin cậy luôn giữ đúng lời hứa và đến đúng giờ.", ex2: "We need a reliable vehicle for our mountain journey.", ex2Vn: "Chúng tôi cần một chiếc xe đáng tin cậy cho chuyến hành trình vượt núi.", syn: ["dependable", "trustworthy"], ant: ["unreliable", "undependable"] },
    { word: "sincere", phonetic: "/sɪnˈsɪr/", def: "Free from pretense or deceit; proceeding from genuine feelings.", defVn: "chân thành, thật lòng", pos: "adj", ex1: "Please accept my most sincere apologies for the unexpected delay.", ex1Vn: "Xin vui lòng nhận lời xin lỗi chân thành nhất của tôi vì sự chậm trễ ngoài ý muốn này nhé.", ex2: "Her warm and sincere words touched everyone in the audience.", ex2Vn: "Những lời nói ấm áp và chân thành của cô ấy đã chạm đến trái tim của mọi khán giả.", syn: ["genuine", "heartfelt"], ant: ["insincere", "fake"] },
    { word: "passionate", phonetic: "/ˈpæʃənət/", def: "Having, showing, or caused by strong feelings or a strong belief.", defVn: "đam mê nhiệt huyết, nồng nàn", pos: "adj", ex1: "She is deeply passionate about environmental conservation and wildlife protection.", ex1Vn: "Cô ấy vô cùng đam mê và nhiệt huyết với việc bảo tồn môi trường và bảo vệ động vật hoang dã.", ex2: "A passionate speech inspired youth to pursue their highest dreams.", ex2Vn: "Một bài diễn văn đầy nhiệt huyết đã truyền cảm hứng cho giới trẻ theo đuổi ước mơ cao đẹp nhất.", syn: ["enthusiastic", "ardent"], ant: ["indifferent", "apathetic"] },
    { word: "adaptable", phonetic: "/əˈdæptəbl/", def: "Able to adjust to new conditions.", defVn: "dễ thích nghi, linh hoạt", pos: "adj", ex1: "Successful international professionals are culturally adaptable and open-minded.", ex1Vn: "Những chuyên gia quốc tế thành đạt là những người dễ thích nghi với văn hóa và có tư duy cởi mở.", ex2: "The adaptable software runs smoothly on both desktop and mobile platforms.", ex2Vn: "Phần mềm linh hoạt chạy mượt mà trên cả nền tảng máy tính và điện thoại di động.", syn: ["flexible", "versatile"], ant: ["rigid", "inflexible"] },
    { word: "diligent", phonetic: "/ˈdɪlɪdʒənt/", def: "Having or showing care and conscientiousness in one's work or duties.", defVn: "chăm chỉ, siêng năng, cần mẫn", pos: "adj", ex1: "Diligent practice every single day is the golden secret to English fluency.", ex1Vn: "Luyện tập chăm chỉ cần mẫn mỗi ngày là bí quyết vàng để nói tiếng Anh trôi chảy.", ex2: "The diligent student earned a top scholarship through relentless effort.", ex2Vn: "Bạn học sinh chăm chỉ đã giành được học bổng hàng đầu nhờ sự nỗ lực không ngừng nghỉ.", syn: ["hardworking", "industrious"], ant: ["lazy", "negligent"] },
    { word: "witty", phonetic: "/ˈwɪti/", def: "Showing or characterized by quick and inventive verbal humor.", defVn: "dí dỏm, nhanh trí, thông minh sắc sảo", pos: "adj", ex1: "His witty remarks kept the dinner guests laughing all evening.", ex1Vn: "Những lời bình luận dí dỏm của anh ấy khiến các vị khách ăn tối cười suốt cả buổi.", ex2: "Oscar Wilde was famous worldwide for his witty plays and aphorisms.", ex2Vn: "Oscar Wilde nổi tiếng khắp thế giới với những vở kịch và danh ngôn dí dỏm sâu cay.", syn: ["clever", "sharp"], ant: ["dull", "foolish"] }
  ],

  // Theme 27: Prepositions & Space (11 extra)
  t_basic_prepositions_positions: [
    { word: "underneath", phonetic: "/ˌʌndərˈniːθ/", def: "Situated directly below or beneath something.", defVn: "ở ngay phía dưới, bên dưới đáy", pos: "preposition", ex1: "The cat hid quietly underneath the warm sofa blanket.", ex1Vn: "Chú mèo nằm trốn tĩnh lặng ở ngay bên dưới tấm chăn sô-pha ấm áp.", ex2: "Check underneath the table for any dropped stationery.", ex2Vn: "Kiểm tra phía dưới gầm bàn xem có rơi rớt dụng cụ học tập nào không nhé.", syn: ["below", "beneath"], ant: ["above", "on top"] },
    { word: "alongside", phonetic: "/əˌlɔːŋˈsaɪd/", def: "Close to the side of; next to; together with.", defVn: "dọc theo bên cạnh, song hành cùng", pos: "preposition", ex1: "A scenic bicycle path runs alongside the tranquil canal.", ex1Vn: "Một con đường dành cho xe đạp ngắm cảnh chạy dọc theo bên cạnh con kênh yên bình.", ex2: "He worked alongside leading international research scientists.", ex2Vn: "Anh ấy đã làm việc song hành cùng các nhà khoa học nghiên cứu quốc tế hàng đầu.", syn: ["beside", "next to"], ant: ["apart from"] },
    { word: "beyond", phonetic: "/bɪˈjɑːnd/", def: "At or to the further side of; more extensive than.", defVn: "ở phía bên kia, vượt xa hơn", pos: "preposition", ex1: "Lush green pine hills stretch far beyond the horizon.", ex1Vn: "Những đồi thông xanh tươi trải dài ra tận phía xa bên kia đường chân trời.", ex2: "Her performance was outstanding and far beyond all expectations.", ex2Vn: "Màn trình diễn của cô ấy rất xuất sắc và vượt xa mọi kỳ vọng ban đầu.", syn: ["past", "further than"], ant: ["within"] },
    { word: "across", phonetic: "/əˈkrɔːs/", def: "From one side to the other side of something with clear limits.", defVn: "băng qua, ở phía bên kia", pos: "preposition", ex1: "Walk carefully across the pedestrian zebra crossing.", ex1Vn: "Hãy đi bộ cẩn thận băng qua vạch sang đường cho người đi bộ nhé.", ex2: "There is a 24-hour convenience store right across the street.", ex2Vn: "Có một cửa hàng tiện lợi mở cửa 24/24 ngay ở phía bên kia đường.", syn: ["over", "through"], ant: [] },
    { word: "throughout", phonetic: "/θruːˈaʊt/", def: "In every part of a place or object; from beginning to end of an event.", defVn: "khắp nơi trong, xuyên suốt", pos: "preposition", ex1: "Traditional folk music was broadcast throughout the entire festival ground.", ex1Vn: "Âm nhạc dân gian truyền thống được phát thanh khắp nơi trong toàn bộ khuôn viên lễ hội.", ex2: "She remained calm, focused, and poised throughout the entire interview.", ex2Vn: "Cô ấy vẫn luôn điềm tĩnh, tập trung và đĩnh đạc xuyên suốt cả buổi phỏng vấn.", syn: ["all over", "all through"], ant: [] },
    { word: "toward", phonetic: "/tɔːrd/", def: "In the direction of someone or something.", defVn: "về hướng, tiến về phía", pos: "preposition", ex1: "The ship sailed smoothly toward the golden sunrise.", ex1Vn: "Con tàu lướt đi êm ả về hướng mặt trời mọc dát vàng.", ex2: "Take small positive steps every day toward achieving your dreams.", ex2Vn: "Hãy tiến từng bước nhỏ tích cực mỗi ngày về hướng đạt được ước mơ của bạn nhé.", syn: ["towards", "in the direction of"], ant: ["away from"] },
    { word: "against", phonetic: "/əˈɡenst/", def: "In contact with and supported by; in opposition to.", defVn: "tựa vào, đối nghịch lại, chống lại", pos: "preposition", ex1: "He leaned his bicycle against the sturdy wooden garden fence.", ex1Vn: "Anh ấy dựng chiếc xe đạp tựa vào hàng rào gỗ chắc chắn trong vườn.", ex2: "Wear a windbreaker to protect against the chilly northern breeze.", ex2Vn: "Hãy mặc một chiếc áo cản gió để chống lại cơn gió bấc se lạnh nhé.", syn: ["versus", "counter to"], ant: ["for", "with"] },
    { word: "within", phonetic: "/wɪˈðɪn/", def: "Inside something, or occurring inside a particular period of time or distance.", defVn: "ở bên trong, trong vòng (thời gian, phạm vi)", pos: "preposition", ex1: "The parcel will be delivered safely within two business days.", ex1Vn: "Bưu kiện sẽ được giao an toàn trong vòng hai ngày làm việc.", ex2: "Find quiet peace and happiness within your own heart.", ex2Vn: "Hãy tìm kiếm sự bình yên tĩnh lặng và niềm hạnh phúc ở bên trong chính trái tim mình.", syn: ["inside", "in"], ant: ["outside", "beyond"] },
    { word: "amidst", phonetic: "/əˈmɪdst/", def: "In the middle of; surrounded by.", defVn: "ở giữa, giữa lòng (cảnh vật, biến cố)", pos: "preposition", ex1: "A tranquil white cottage stood quietly amidst lush flowering orchards.", ex1Vn: "Một ngôi nhà nhỏ màu trắng thanh bình đứng tĩnh lặng giữa lòng những vườn cây ăn quả đang nở rộ.", ex2: "She stayed remarkably composed amidst the bustling rush hour commotion.", ex2Vn: "Cô ấy giữ được sự bình thản đáng nể giữa dòng người tấp nập của giờ cao điểm.", syn: ["among", "in the midst of"], ant: [] },
    { word: "nearby", phonetic: "/ˌnɪrˈbaɪ/", def: "Not far away; close by in distance.", defVn: "ở gần đây, ngay gần", pos: "adverb", ex1: "We stopped for lunch at a cozy noodle restaurant nearby.", ex1Vn: "Chúng tôi dừng chân ăn trưa tại một quán mì ấm cúng ở ngay gần đây.", ex2: "Is there an automated teller machine nearby?", ex2Vn: "Có cây rút tiền tự động nào ở gần đây không bạn?", syn: ["close", "adjacent"], ant: ["far away", "distant"] },
    { word: "surrounding", phonetic: "/səˈraʊndɪŋ/", def: "All around someone or something.", defVn: "bao quanh, xung quanh", pos: "adj", ex1: "Panoramic mountain ranges form the surrounding landscape.", ex1Vn: "Những dãy núi bao la tạo nên cảnh quan thiên nhiên bao quanh khắp nơi.", ex2: "Trees planted in the surrounding park filter city noise.", ex2Vn: "Cây cối trồng trong công viên xung quanh giúp lọc bớt tiếng ồn của đô thị.", syn: ["encircling", "ambient"], ant: [] }
  ],

  // Theme 28: Senses & Perception (10 extra)
  t_basic_senses_perceptions: [
    { word: "aromatic", phonetic: "/ˌærəˈmætɪk/", def: "Having a pleasant and distinctive smell.", defVn: "thơm ngát, ngào ngạt hương thơm", pos: "adj", ex1: "A cup of hot aromatic Vietnamese drip coffee awakens the senses.", ex1Vn: "Một tách cà phê phin Việt Nam nóng thơm ngát đánh thức mọi giác quan.", ex2: "Aromatic basil and lemongrass flavor the savory noodle broth.", ex2Vn: "Húng quế và sả thơm ngào ngạt tạo nên hương vị đậm đà cho nước dùng món mì.", syn: ["fragrant", "perfumed"], ant: ["stinky", "malodorous"] },
    { word: "pungent", phonetic: "/ˈpʌndʒənt/", def: "Having a sharply strong taste or smell.", defVn: "nồng nặc, cay nồng (mùi vị đậm)", pos: "adj", ex1: "Freshly sliced raw onions release a pungent sulfurous vapor.", ex1Vn: "Hành tây sống vừa thái lát tỏa ra một làn hơi cay nồng.", ex2: "Traditional fish sauce has a strong, pungent yet appetizing aroma.", ex2Vn: "Nước mắm truyền thống có mùi nồng đậm đặc trưng nhưng vô cùng ngon miệng.", syn: ["sharp", "piquant"], ant: ["bland", "mild"] },
    { word: "savory", phonetic: "/ˈseɪvəri/", def: "Belonging to the category that is salty or spicy rather than sweet.", defVn: "đậm đà, thơm ngon (món mặn)", pos: "adj", ex1: "Crispy savory pancakes filled with shrimp and pork are popular in Vietnam.", ex1Vn: "Bánh xèo giòn rụm đậm đà nhân tôm thịt là món ăn phổ biến tại Việt Nam.", ex2: "We enjoyed savory grilled barbecue skewers at the night market.", ex2Vn: "Chúng tôi đã thưởng thức những xiên thịt nướng mặn mà thơm ngon tại chợ đêm.", syn: ["umami", "delicious"], ant: ["sweet"] },
    { word: "crunchy", phonetic: "/ˈkrʌntʃi/", def: "Making a sharp noise when bitten or crushed and easily broken.", defVn: "giòn tan, giòn rụm", pos: "adj", ex1: "Fresh cucumber slices and carrot sticks are delightfully crunchy.", ex1Vn: "Những lát dưa chuột tươi và thanh cà rốt ăn rất giòn tan thích thú.", ex2: "Bake the baguettes until the golden crust becomes crispy and crunchy.", ex2Vn: "Nướng bánh mì que cho đến khi lớp vỏ vàng ươm trở nên giòn rụm nhé.", syn: ["crisp", "brittle"], ant: ["soggy", "soft"] },
    { word: "texture", phonetic: "/ˈtekstʃər/", def: "The feel, appearance, or consistency of a surface or a substance.", defVn: "kết cấu, cảm giác bề mặt (mịn, sần, dai)", pos: "noun", ex1: "Silk fabric has an extraordinarily soft and smooth texture.", ex1Vn: "Vải lụa có kết cấu bề mặt vô cùng mềm mại và mượt mà.", ex2: "The creamy pudding has a velvety melt-in-the-mouth texture.", ex2Vn: "Món bánh pudding mềm béo có kết cấu mịn như nhung tan ngay trong miệng.", syn: ["feel", "consistency"], ant: [] },
    { word: "echo", phonetic: "/ˈekoʊ/", def: "A sound or sounds caused by the reflection of sound waves from a surface back to the listener.", defVn: "tiếng vang, âm vang vọng lại", pos: "noun", ex1: "Our cheerful shouts produced a clear echo inside the vast limestone cave.", ex1Vn: "Tiếng reo hò vui vẻ của chúng tôi tạo nên âm vang vọng lại rõ rệt trong hang đá vôi rộng lớn.", ex2: "The sound of church bells echoed across the quiet valley.", ex2Vn: "Tiếng chuông nhà thờ vang vọng khắp thung lũng tĩnh lặng.", syn: ["reverberation", "resonance"], ant: [] },
    { word: "glimpse", phonetic: "/ɡlɪmps/", def: "A momentary or partial view.", defVn: "cái nhìn thoáng qua, thoáng thấy", pos: "noun", ex1: "We caught a fleeting glimpse of a rare wild deer through the pine trees.", ex1Vn: "Chúng tôi thoáng nhìn thấy một chú hươu hoang dã quý hiếm qua những rặng thông.", ex2: "She caught a quick glimpse of herself in the store window reflection.", ex2Vn: "Cô ấy thoáng nhìn thấy hình bóng mình phản chiếu trên ô cửa kính cửa hàng.", syn: ["peek", "glance"], ant: ["gaze"] },
    { word: "fragrance", phonetic: "/ˈfreɪɡrəns/", def: "A pleasant, sweet smell.", defVn: "hương thơm quyến rũ, mùi thơm ngọt ngào", pos: "noun", ex1: "The delicate floral fragrance of blooming jasmine filled the night air.", ex1Vn: "Hương thơm hoa nhài nở rộ thoang thoảng quyến rũ lan tỏa khắp bầu không khí ban đêm.", ex2: "She applied a light splash of citrus fragrance before going out.", ex2Vn: "Cô ấy xịt nhẹ một chút nước hoa hương cam quýt trước khi ra ngoài.", syn: ["scent", "perfume", "aroma"], ant: ["stench", "odor"] },
    { word: "sensation", phonetic: "/senˈseɪʃn/", def: "A physical feeling or perception resulting from something that happens to or comes into contact with the body.", defVn: "cảm giác xúc giác, cảm nhận thể chất", pos: "noun", ex1: "Dipping bare feet into the cool mountain brook caused a tingling sensation.", ex1Vn: "Nhúng đôi chân trần vào dòng suối núi mát lạnh mang lại cảm giác tê rần sảng khoái.", ex2: "Mint candy produces a crisp, cooling sensation in the mouth.", ex2Vn: "Kẹo bạc hà tạo cảm giác the mát sảng khoái trong khoang miệng.", syn: ["feeling", "perception"], ant: ["numbness"] },
    { word: "vision", phonetic: "/ˈvɪʒn/", def: "The faculty or state of being able to see.", defVn: "thị lực, tầm nhìn, khả năng nhìn", pos: "noun", ex1: "Eating vitamin A rich carrots and greens helps maintain sharp vision.", ex1Vn: "Ăn cà rốt và rau xanh giàu vitamin A giúp duy trì thị lực sắc bén.", ex2: "An optometrist tested her 20/20 vision accurately.", ex2Vn: "Bác sĩ đo thị lực đã kiểm tra thị lực 10/10 của cô ấy một cách chính xác.", syn: ["sight", "eyesight"], ant: ["blindness"] }
  ],

  // Theme 29: Vacation & Tourism (10 extra)
  t_basic_vacation_tourism: [
    { word: "souvenir", phonetic: "/ˌsuːvəˈnɪr/", def: "A thing that is kept as a reminder of a person, place, or event.", defVn: "quà lưu niệm, đồ kỷ niệm chuyến đi", pos: "noun", ex1: "I bought handcrafted bamboo bookmarks as memorable souvenirs for my classmates.", ex1Vn: "Tôi đã mua những chiếc kẹp sách bằng tre thủ công làm quà lưu niệm đáng nhớ cho các bạn cùng lớp.", ex2: "Souvenir shops near the temple sell traditional lacquered boxes.", ex2Vn: "Những cửa hàng bán đồ lưu niệm gần chùa bán các hộp sơn mài truyền thống.", syn: ["memento", "keepsake"], ant: [] },
    { word: "sightseeing", phonetic: "/ˈsaɪtsiːɪŋ/", def: "The activity of visiting places of interest in a particular location by tourists.", defVn: "hoạt động tham quan ngắm cảnh", pos: "noun", ex1: "We spent the entire sunny morning sightseeing ancient temples and historic pagodas.", ex1Vn: "Chúng tôi đã dành trọn buổi sáng nắng đẹp để đi tham quan ngắm cảnh các ngôi đền cổ và chùa chiền lịch sử.", ex2: "An open-top double-decker bus is great for city sightseeing tours.", ex2Vn: "Chiếc xe buýt hai tầng mui trần rất tuyệt vời cho các chuyến tham quan thành phố.", syn: ["touring", "excursion"], ant: [] },
    { word: "itinerary", phonetic: "/aɪˈtɪnəreri/", def: "A planned route or journey; a travel timetable.", defVn: "lịch trình chuyến đi, kế hoạch tham quan", pos: "noun", ex1: "Our five-day Da Nang travel itinerary includes visits to Ba Na Hills and Hoi An Ancient Town.", ex1Vn: "Lịch trình du lịch Đà Nẵng năm ngày của chúng tôi bao gồm các chuyến ghé thăm Bà Nà Hills và Phố cổ Hội An.", ex2: "Check the flight departure schedule on your detailed digital itinerary.", ex2Vn: "Kiểm tra giờ khởi hành chuyến bay trên lịch trình điện tử chi tiết của bạn nhé.", syn: ["schedule", "route"], ant: [] },
    { word: "campsite", phonetic: "/ˈkæmpsaɪt/", def: "A place used for camping, especially one equipped with facilities.", defVn: "khu cắm trại, bãi cắm trại dã ngoại", pos: "noun", ex1: "We pitched our waterproof tents at a scenic mountain campsite beside a clear stream.", ex1Vn: "Chúng tôi đã dựng lều chống nước tại một khu cắm trại trên núi tuyệt đẹp cạnh con suối trong vắt.", ex2: "Gathering around a crackling campfire at the campsite is deeply comforting.", ex2Vn: "Quây quần bên đống lửa trại bập bùng tại bãi cắm trại mang lại cảm giác ấm áp dễ chịu.", syn: ["campground"], ant: [] },
    { word: "cruise", phonetic: "/kruːz/", def: "A voyage on a ship or boat taken for pleasure or as a vacation.", defVn: "chuyến du ngoạn bằng du thuyền trên biển", pos: "noun", ex1: "An overnight luxury cruise through Ha Long Bay offers unforgettable views of limestone karsts.", ex1Vn: "Chuyến du ngoạn du thuyền sang trọng qua đêm trên Vịnh Hạ Long mang lại tầm nhìn khó quên về những dãy núi đá vôi.", ex2: "They booked a tropical island cruise for their winter holiday.", ex2Vn: "Họ đã đặt một chuyến du ngoạn đảo nhiệt đới cho kỳ nghỉ đông của mình.", syn: ["voyage", "boat trip"], ant: [] },
    { word: "guidebook", phonetic: "/ˈɡaɪdbʊk/", def: "A book of information about a place, designed for the use of visitors or tourists.", defVn: "sách hướng dẫn du lịch", pos: "noun", ex1: "The Lonely Planet travel guidebook recommended top authentic street food spots.", ex1Vn: "Cuốn sách hướng dẫn du lịch Lonely Planet đã gợi ý các địa điểm ăn uống đường phố ngon chuẩn vị nhất.", ex2: "Flip through the city guidebook map to locate nearest historic landmarks.", ex2Vn: "Mở bản đồ trong sách hướng dẫn thành phố để xác định các địa danh lịch sử gần nhất nhé.", syn: ["handbook", "travel guide"], ant: [] },
    { word: "postcard", phonetic: "/ˈpoʊstkɑːrd/", def: "A card for sending a message by mail without an envelope, typically having a photograph on one side.", defVn: "bưu thiếp phong cảnh (gửi qua bưu điện)", pos: "noun", ex1: "She mailed a glossy postcard featuring the Golden Bridge in Da Nang to her grandmother.", ex1Vn: "Cô ấy đã gửi qua bưu điện một tấm bưu thiếp bóng bẩy in hình Cầu Vàng Đà Nẵng cho bà của mình.", ex2: "Collecting scenic vintage postcards is a charming hobby.", ex2Vn: "Sưu tầm các tấm bưu thiếp phong cảnh xưa cũ là một thú vui tao nhã.", syn: ["picture postcard"], ant: [] },
    { word: "resort", phonetic: "/rɪˈzɔːrt/", def: "A place that is a popular destination for vacations or recreation.", defVn: "khu nghỉ dưỡng sinh thái, resort cao cấp", pos: "noun", ex1: "The seaside resort features an infinity swimming pool overlooking the turquoise ocean.", ex1Vn: "Khu nghỉ dưỡng ven biển có bể bơi vô cực nhìn thẳng ra đại dương xanh màu ngọc bích.", ex2: "Unwind with soothing spa therapies at the mountain eco-resort.", ex2Vn: "Thư giãn với các liệu trình mát-xa xoa dịu tại khu nghỉ dưỡng sinh thái trên núi.", syn: ["retreat", "lodge"], ant: [] },
    { word: "terminal", phonetic: "/ˈtɜːrmɪnl/", def: "A building where passengers embark and disembark, especially at an airport or harbor.", defVn: "nhà ga hành khách (sân bay, bến tàu)", pos: "noun", ex1: "International terminal two handles overseas departures and arrivals smoothly.", ex1Vn: "Nhà ga quốc tế số hai phục vụ các chuyến bay đi và đến nước ngoài một cách thuận lợi.", ex2: "Follow clear multilingual signage inside the modern passenger terminal.", ex2Vn: "Hãy đi theo các bảng chỉ dẫn đa ngôn ngữ rõ ràng bên trong nhà ga hành khách hiện đại nhé.", syn: ["station", "concourse"], ant: [] },
    { word: "destination", phonetic: "/ˌdestɪˈneɪʃn/", def: "The place to which someone or something is going or being sent.", defVn: "điểm đến du lịch, đích đến", pos: "noun", ex1: "Phu Quoc island has emerged as a premier world-class vacation destination.", ex1Vn: "Đảo Phú Quốc đã vươn lên thành một điểm đến nghỉ dưỡng đẳng cấp thế giới.", ex2: "We finally reached our mountain resort destination after a five-hour drive.", ex2Vn: "Cuối cùng chúng tôi đã đến được khu nghỉ dưỡng trên núi sau năm tiếng lái xe.", syn: ["stop", "terminus"], ant: ["origin"] }
  ],

  // Theme 30: Entertainment & Arts (10 extra)
  t_basic_entertainment_arts: [
    { word: "orchestra", phonetic: "/ˈɔːrkɪstrə/", def: "A large group of musicians playing different instruments together, typically led by a conductor.", defVn: "dàn nhạc giao hưởng", pos: "noun", ex1: "The national symphony orchestra performed Beethoven's Ninth Symphony brilliantly.", ex1Vn: "Dàn nhạc giao hưởng quốc gia đã trình diễn Bản giao hưởng số 9 của Beethoven thật xuất sắc.", ex2: "Violins, cellos, flutes, and brass horns blend seamlessly in a symphony orchestra.", ex2Vn: "Vĩ cầm, trung cầm, sáo và kèn đồng hòa quyện nhịp nhàng trong một dàn nhạc giao hưởng.", syn: ["symphony", "ensemble"], ant: [] },
    { word: "gallery", phonetic: "/ˈɡæləri/", def: "A room or building for the display or sale of works of art.", defVn: "phòng trưng bày tranh, phòng tranh nghệ thuật", pos: "noun", ex1: "The contemporary art gallery showcases innovative oil paintings and marble sculptures.", ex1Vn: "Phòng tranh nghệ thuật đương đại trưng bày những bức tranh sơn dầu sáng tạo và tượng điêu khắc cẩm thạch.", ex2: "We met local emerging painters at the gallery opening reception.", ex2Vn: "Chúng tôi đã gặp gỡ các họa sĩ trẻ tài năng tại buổi lễ khai mạc phòng tranh.", syn: ["exhibition hall"], ant: [] },
    { word: "sculpture", phonetic: "/ˈskʌlptʃər/", def: "The art of making two- or three-dimensional representative or abstract forms, especially by carving stone or wood or by casting metal or plaster.", defVn: "tác phẩm điêu khắc, nghệ thuật tạc tượng", pos: "noun", ex1: "Michelangelo's famous David is a breathtaking classical marble sculpture.", ex1Vn: "Tượng David nổi tiếng của Michelangelo là một tác phẩm điêu khắc bằng đá cẩm thạch kinh điển ngoạn mục.", ex2: "Bronze sculptures line the courtyard entrance of the art academy.", ex2Vn: "Những bức tượng điêu khắc bằng đồng đứng dọc lối vào sân trường học viện nghệ thuật.", syn: ["statue", "carving"], ant: [] },
    { word: "rehearsal", phonetic: "/rɪˈhɜːrsl/", def: "A practice or trial performance of a play or other work for later public performance.", defVn: "buổi tổng duyệt, buổi tập luyện biểu diễn", pos: "noun", ex1: "Actors held a rigorous dress rehearsal on the main stage before opening night.", ex1Vn: "Các diễn viên đã tổ chức một buổi tổng duyệt trang phục nghiêm túc trên sân khấu chính trước đêm công diễn.", ex2: "Choir members attended evening vocal rehearsals twice a week.", ex2Vn: "Các thành viên dàn hợp xướng tham gia các buổi tập luyện giọng hát hai lần một tuần vào buổi tối.", syn: ["practice", "run-through"], ant: [] },
    { word: "stage", phonetic: "/steɪdʒ/", def: "A raised floor or platform, typically in a theatre, on which actors, entertainers, or speakers perform.", defVn: "sân khấu biểu diễn", pos: "noun", ex1: "Bright spotlights illuminated the theater stage as the prima ballerina stepped forward.", ex1Vn: "Những ngọn đèn sân khấu rực rỡ chiếu sáng sàn diễn khi nữ diễn viên múa ba lê chính bước ra phía trước.", ex2: "Musicians took a graceful bow on stage after thunderous audience applause.", ex2Vn: "Các nhạc công đã cúi chào duyên dáng trên sân khấu sau tràng pháo tay ròn rã của khán giả.", syn: ["platform", "podium"], ant: [] },
    { word: "soundtrack", phonetic: "/ˈsaʊndtræk/", def: "A recording of the musical accompaniment on a film or television show.", defVn: "nhạc phim, bản thu âm bài hát trong phim", pos: "noun", ex1: "The emotional orchestral soundtrack of the animated movie brought tears to our eyes.", ex1Vn: "Bản nhạc phim giao hưởng đầy cảm xúc của bộ phim hoạt hình đã làm chúng tôi rơm rớm nước mắt.", ex2: "Listen to the instrumental soundtrack while studying to boost concentration.", ex2Vn: "Nghe nhạc phim không lời khi học bài để tăng cường sự tập trung nhé.", syn: ["score", "film music"], ant: [] },
    { word: "performance", phonetic: "/pərˈfɔːrməns/", def: "An act of staging or presenting a play, concert, or other form of entertainment.", defVn: "buổi biểu diễn, màn trình diễn", pos: "noun", ex1: "The circus acrobats delivered a thrilling live performance high above the arena.", ex1Vn: "Các nghệ sĩ xiếc nhào lộn đã mang đến một màn trình diễn trực tiếp thót tim trên không trung đấu trường.", ex2: "Tickets for tonight's musical performance are completely sold out.", ex2Vn: "Vé xem buổi biểu diễn ca nhạc tối nay đã bán hết sạch hoàn toàn.", syn: ["show", "recital"], ant: [] },
    { word: "exhibition", phonetic: "/ˌeksɪˈbɪʃn/", def: "A public display of works of art or items of interest, held in an art gallery or museum or at a trade fair.", defVn: "cuộc triển lãm, hội chợ trưng bày", pos: "noun", ex1: "The international photography exhibition attracted thousands of culture lovers.", ex1Vn: "Triển lãm nhiếp ảnh quốc tế đã thu hút hàng ngàn người yêu văn hóa nghệ thuật.", ex2: "Original manuscripts were displayed securely in glass cases throughout the exhibition.", ex2Vn: "Các bản thảo gốc được trưng bày an toàn trong các tủ kính khắp khu triển lãm.", syn: ["showcase", "display"], ant: [] },
    { word: "actor", phonetic: "/ˈæktər/", def: "A person whose profession is acting on the stage, in movies, or on television.", defVn: "nam diễn viên, diễn viên kịch/điện ảnh", pos: "noun", ex1: "The versatile actor portrayed the historical king with commanding gravitas.", ex1Vn: "Nam diễn viên đa tài đã khắc họa vị vua lịch sử với thần thái uy nghiêm đĩnh đạc.", ex2: "Aspiring young actors attend acting workshops to hone their stage skills.", ex2Vn: "Các diễn viên trẻ giàu khát vọng tham gia các xưởng kịch nghệ để trau dồi kỹ năng sân khấu.", syn: ["performer", "player"], ant: [] },
    { word: "actress", phonetic: "/ˈæktrəs/", def: "A female actor in a film, play, or television programme.", defVn: "nữ diễn viên (sân khấu, điện ảnh)", pos: "noun", ex1: "The acclaimed actress received a standing ovation for her dramatic performance.", ex1Vn: "Nữ diễn viên lừng danh đã nhận được tràng pháo tay đứng nhiệt liệt cho màn hóa thân đầy kịch tính.", ex2: "She won best leading actress at the prestigious international film festival.", ex2Vn: "Cô ấy đã giành giải nữ diễn viên chính xuất sắc nhất tại liên hoan phim quốc tế danh giá.", syn: ["performer", "starlet"], ant: [] }
  ]
};
