const part1A = require('./expansion_pack_1_15.js');

module.exports = {
  ...part1A,

  // Theme 6: Home Objects (10 extra)
  t_basic_home_objects: [
    { word: "attic", phonetic: "/ˈætɪk/", def: "A space or room just below the roof of a building.", defVn: "gác xép, tầng áp mái", pos: "noun", ex1: "We keep vintage photo albums stored in the attic.", ex1Vn: "Chúng tôi cất giữ các album ảnh xưa cũ trên gác xép.", ex2: "She converted the attic into a cozy reading studio.", ex2Vn: "Cô ấy đã cải tạo gác xép thành một góc đọc sách ấm cúng.", syn: ["loft", "garret"], ant: ["basement"] },
    { word: "basement", phonetic: "/ˈbeɪsmənt/", def: "The floor of a building which is partly or entirely below ground level.", defVn: "tầng hầm (nhà ở)", pos: "noun", ex1: "He set up a woodworking workshop in the basement.", ex1Vn: "Anh ấy đã thiết lập một xưởng mộc ở tầng hầm.", ex2: "Keep emergency supplies safely in the dry basement.", ex2Vn: "Hãy cất các đồ dùng dự phòng khẩn cấp an toàn dưới tầng hầm khô ráo.", syn: ["cellar"], ant: ["attic"] },
    { word: "balcony", phonetic: "/ˈbælkəni/", def: "A platform enclosed by a wall or balustrade on the outside of a building.", defVn: "ban công", pos: "noun", ex1: "We grow fragrant herbs and roses on the sunny balcony.", ex1Vn: "Chúng tôi trồng các loại thảo mộc thơm và hoa hồng trên ban công tràn ngập ánh nắng.", ex2: "Enjoy a cup of warm tea on the breezy balcony.", ex2Vn: "Thưởng thức một tách trà ấm ngoài ban công lộng gió nhé.", syn: ["terrace", "veranda"], ant: [] },
    { word: "patio", phonetic: "/ˈpætioʊ/", def: "A paved outdoor area adjoining a house, used for dining or recreation.", defVn: "khoảng sân sau, hiên ngoài trời", pos: "noun", ex1: "We enjoyed barbecue dinner on the garden patio.", ex1Vn: "Chúng tôi đã thưởng thức bữa tối nướng ngoài hiên sân vườn.", ex2: "Outdoor chairs and a table furnish the paved patio.", ex2Vn: "Những chiếc ghế và chiếc bàn ngoài trời trang hoàng khoảng sân hiên lát gạch.", syn: ["courtyard", "terrace"], ant: [] },
    { word: "hallway", phonetic: "/ˈhɔːlweɪ/", def: "A passage or corridor in a building connecting rooms.", defVn: "hành lang, lối đi trong nhà", pos: "noun", ex1: "Framed family portraits line the brightly lit hallway.", ex1Vn: "Các bức ảnh chân dung gia đình đóng khung treo dọc hành lang sáng sủa.", ex2: "Please walk quietly through the apartment hallway.", ex2Vn: "Làm ơn đi lại nhẹ nhàng qua hành lang chung cư nhé.", syn: ["corridor", "passageway"], ant: [] },
    { word: "bookshelf", phonetic: "/ˈbʊkʃelf/", def: "A shelf or set of shelves on which books can be stored.", defVn: "kệ sách, giá sách", pos: "noun", ex1: "Organize novels and dictionaries neatly on the wooden bookshelf.", ex1Vn: "Sắp xếp tiểu thuyết và từ điển gọn gàng trên kệ sách gỗ.", ex2: "His tall bookshelf is filled with world classics.", ex2Vn: "Chiếc giá sách cao của anh chứa đầy các tác phẩm kinh điển thế giới.", syn: ["bookcase"], ant: [] },
    { word: "rug", phonetic: "/rʌɡ/", def: "A floor covering of thick woven material or animal skin, typically not extending over the entire floor.", defVn: "tấm thảm trải sàn (nhỏ)", pos: "noun", ex1: "A soft wool rug warms the hardwood floor beside the bed.", ex1Vn: "Một tấm thảm len mềm mại làm ấm sàn gỗ cạnh giường.", ex2: "Wipe your shoes on the doormat rug before entering.", ex2Vn: "Lau giày trên tấm thảm chùi chân trước khi bước vào nhà nhé.", syn: ["carpet", "mat"], ant: [] },
    { word: "chandelier", phonetic: "/ˌʃændəˈlɪr/", def: "A large decorative hanging light with branches for several light bulbs or candles.", defVn: "đèn chùm lộng lẫy", pos: "noun", ex1: "A sparkling crystal chandelier illuminates the dining hall.", ex1Vn: "Chiếc đèn chùm pha lê lấp lánh thắp sáng cả phòng ăn lớn.", ex2: "The grand chandelier adds timeless elegance to the room.", ex2Vn: "Chiếc đèn chùm tráng lệ mang lại vẻ đẹp sang trọng vượt thời gian cho căn phòng.", syn: ["ceiling light"], ant: [] },
    { word: "curtain", phonetic: "/ˈkɜːrtn/", def: "A piece of material suspended at the top to form a screen, typically movable across a window.", defVn: "rèm cửa, màn cửa", pos: "noun", ex1: "Draw the thick curtains to block out harsh afternoon sun.", ex1Vn: "Kéo rèm cửa dày lại để che bớt ánh nắng gay gắt buổi chiều nhé.", ex2: "She picked sheer white lace curtains for the bedroom.", ex2Vn: "Cô ấy chọn rèm ren trắng tinh khôi cho phòng ngủ.", syn: ["drape", "blind"], ant: [] },
    { word: "doorway", phonetic: "/ˈdɔːrweɪ/", def: "An entrance to a building or room through a door.", defVn: "khung cửa, lối ra vào", pos: "noun", ex1: "He stood in the doorway smiling and welcoming guests.", ex1Vn: "Anh ấy đứng ở khung cửa tươi cười chào đón các vị khách.", ex2: "A wind chime hangs above the front doorway.", ex2Vn: "Một chiếc chuông gió treo phía trên lối ra vào cửa chính.", syn: ["portal", "threshold"], ant: [] }
  ],

  // Theme 9: Emotions & Adjectives (11 extra)
  t_basic_emotions_adjectives: [
    { word: "cheerful", phonetic: "/ˈtʃɪrfl/", def: "Noticeably happy and optimistic.", defVn: "vui tươi, tươi vui, hớn hở", pos: "adj", ex1: "Her cheerful smile always brightens everyone's mood.", ex1Vn: "Nụ cười vui tươi của cô ấy luôn làm rạng rỡ tâm trạng của mọi người.", ex2: "The classroom was filled with cheerful laughter.", ex2Vn: "Lớp học tràn ngập tiếng cười tươi vui.", syn: ["joyful", "upbeat"], ant: ["gloomy", "sad"] },
    { word: "delighted", phonetic: "/dɪˈlaɪtɪd/", def: "Feeling or showing great pleasure.", defVn: "vui sướng, vô cùng hài lòng", pos: "adj", ex1: "We were delighted to hear the wonderful news of your promotion.", ex1Vn: "Chúng tôi rất vui sướng khi nghe tin tuyệt vời bạn vừa được thăng chức.", ex2: "The children were delighted with their holiday presents.", ex2Vn: "Những đứa trẻ vô cùng vui sướng với những món quà ngày lễ.", syn: ["thrilled", "glad"], ant: ["disappointed"] },
    { word: "gloomy", phonetic: "/ˈɡluːmi/", def: "Dark or poorly lit, especially so as to appear depressing or frightening; feeling distressed.", defVn: "u ám, ủ rũ, buồn rầu", pos: "adj", ex1: "A gloomy overcast sky signaled approaching storm clouds.", ex1Vn: "Bầu trời u ám mây xám báo hiệu những cơn bão đang tới gần.", ex2: "Don't look so gloomy; everything will work out fine.", ex2Vn: "Đừng trông ủ rũ buồn rầu như vậy; mọi chuyện rồi sẽ ổn thôi mà.", syn: ["dreary", "somber"], ant: ["cheerful", "bright"] },
    { word: "furious", phonetic: "/ˈfjʊriəs/", def: "Extremely angry; full of fury.", defVn: "tức giận dữ dội, thịnh nộ", pos: "adj", ex1: "He was furious when he discovered the broken vase.", ex1Vn: "Anh ấy đã rất tức giận khi phát hiện chiếc bình hoa bị vỡ.", ex2: "Furious ocean waves crashed against the stone lighthouse.", ex2Vn: "Những con sóng biển giận dữ cuộn trào đập vào ngọn hải đăng bằng đá.", syn: ["enraged", "irate"], ant: ["calm", "peaceful"] },
    { word: "peaceful", phonetic: "/ˈpiːsfl/", def: "Free from disturbance; tranquil.", defVn: "thanh bình, yên ả, hòa bình", pos: "adj", ex1: "The countryside is so peaceful and quiet in early dawn.", ex1Vn: "Vùng nông thôn thật thanh bình và tĩnh lặng lúc rạng đông.", ex2: "She found a peaceful spot beside the stream to meditate.", ex2Vn: "Cô ấy đã tìm được một góc yên bình cạnh dòng suối để tĩnh tâm.", syn: ["serene", "tranquil"], ant: ["chaotic", "noisy"] },
    { word: "nervous", phonetic: "/ˈnɜːrvəs/", def: "Easily agitated or alarmed; tending to be anxious.", defVn: "lo lắng, bồn chồn, hồi hộp", pos: "adj", ex1: "It is natural to feel a bit nervous before speaking on stage.", ex1Vn: "Cảm thấy hơi hồi hộp trước khi phát biểu trên sân khấu là điều tự nhiên.", ex2: "Take three deep breaths whenever you feel nervous.", ex2Vn: "Hãy hít thở sâu ba lần bất cứ khi nào bạn cảm thấy lo lắng nhé.", syn: ["anxious", "tense"], ant: ["confident", "relaxed"] },
    { word: "energetic", phonetic: "/ˌenərˈdʒetɪk/", def: "Showing or involving great activity or vitality.", defVn: "năng động, tràn đầy năng lượng", pos: "adj", ex1: "The energetic golden retriever puppy ran across the lawn.", ex1Vn: "Chú cún tha mồi lông vàng tràn đầy năng lượng chạy lăng xăng khắp bãi cỏ.", ex2: "She is an energetic leader who inspires her entire team.", ex2Vn: "Cô ấy là một người lãnh đạo tràn đầy nhiệt huyết truyền cảm hứng cho cả đội ngũ.", syn: ["vigorous", "dynamic"], ant: ["lethargic", "tired"] },
    { word: "exhausted", phonetic: "/ɪɡˈzɔːstɪd/", def: "Completely drained of physical or mental energy.", defVn: "kiệt sức, mệt lả", pos: "adj", ex1: "After running the full marathon, he felt totally exhausted.", ex1Vn: "Sau khi chạy xong cuộc đua marathon cự ly đầy đủ, anh ấy cảm thấy kiệt sức hoàn toàn.", ex2: "Get some deep sleep when your body is exhausted.", ex2Vn: "Hãy ngủ một giấc thật sâu khi cơ thể bạn đã quá mệt lả nhé.", syn: ["fatigued", "drained"], ant: ["refreshed", "energetic"] },
    { word: "gentle", phonetic: "/ˈdʒentl/", def: "Having or showing a mild, kind, or tender temperament or character.", defVn: "dịu dàng, hiền lành, nhẹ nhàng", pos: "adj", ex1: "A gentle breeze cooled the warm summer afternoon.", ex1Vn: "Một cơn gió nhẹ nhàng xua tan cái nóng chiều mùa hè.", ex2: "She spoke to the frightened kitten with a gentle voice.", ex2Vn: "Cô ấy nói chuyện với chú mèo con đang sợ hãi bằng một giọng thật dịu dàng.", syn: ["tender", "mild"], ant: ["harsh", "rough"] },
    { word: "stubborn", phonetic: "/ˈstʌbərn/", def: "Having or showing dogged determination not to change one's attitude or position.", defVn: "bướng bỉnh, cứng đầu, kiên quyết", pos: "adj", ex1: "Don't be stubborn; listen to helpful advice from doctors.", ex1Vn: "Đừng cứng đầu bướng bỉnh; hãy lắng nghe lời khuyên hữu ích từ bác sĩ nhé.", ex2: "He worked with stubborn perseverance until he solved the riddle.", ex2Vn: "Anh ấy đã kiên trì làm việc với sự ngoan cường cho đến khi giải xong câu đố.", syn: ["obstinate", "resolute"], ant: ["flexible", "compliant"] },
    { word: "generous", phonetic: "/ˈdʒenərəs/", def: "Showing a readiness to give more of something, especially money or kindness, than is strictly necessary.", defVn: "hào phóng, rộng lượng", pos: "adj", ex1: "The generous donor contributed funds to build a local library.", ex1Vn: "Nhà hảo tâm hào phóng đã đóng góp kinh phí để xây dựng thư viện địa phương.", ex2: "She is always generous with her praise and support.", ex2Vn: "Cô ấy luôn hào phóng với những lời khen ngợi và sự giúp đỡ.", syn: ["bountiful", "giving"], ant: ["stingy", "selfish"] }
  ],

  // Theme 10: Time, Days & Seasons (15 extra)
  t_basic_time_calendar: [
    { word: "midnight", phonetic: "/ˈmɪdnaɪt/", def: "Twelve o'clock at night.", defVn: "nửa đêm, 12 giờ đêm", pos: "noun", ex1: "Fireworks lit up the city sky at the stroke of midnight.", ex1Vn: "Pháo hoa thắp sáng bầu trời thành phố đúng vào thời khắc nửa đêm.", ex2: "He finished studying his lesson right around midnight.", ex2Vn: "Anh ấy hoàn thành việc học bài ngay vào khoảng 12 giờ đêm.", syn: [], ant: ["noon"] },
    { word: "noon", phonetic: "/nuːn/", def: "Twelve o'clock in the day; midday.", defVn: "buổi trưa, 12 giờ trưa", pos: "noun", ex1: "The sun is at its highest point in the sky at noon.", ex1Vn: "Mặt trời ở điểm cao nhất trên bầu trời vào lúc 12 giờ trưa.", ex2: "Let's meet for lunch at high noon tomorrow.", ex2Vn: "Hãy gặp nhau ăn trưa vào đúng 12 giờ trưa mai nhé.", syn: ["midday"], ant: ["midnight"] },
    { word: "dawn", phonetic: "/dɔːn/", def: "The first appearance of light in the sky before sunrise.", defVn: "bình minh, rạng đông", pos: "noun", ex1: "Birds begin singing sweetly at the break of dawn.", ex1Vn: "Chim chóc bắt đầu cất tiếng hót líu lo ngọt ngào khi bình minh ló rạng.", ex2: "Farmers head out to the fields before dawn.", ex2Vn: "Các bác nông dân ra đồng trước khi trời rạng đông.", syn: ["daybreak", "sunrise"], ant: ["dusk", "sunset"] },
    { word: "dusk", phonetic: "/dʌsk/", def: "The darker stage of twilight in the evening.", defVn: "hoàng hôn, chạng vạng tối", pos: "noun", ex1: "Streetlights turn on automatically as dusk settles over town.", ex1Vn: "Đèn đường tự động bật sáng khi hoàng hôn chạng vạng buông xuống thị trấn.", ex2: "We strolled along the serene shoreline at dusk.", ex2Vn: "Chúng tôi dạo bước dọc bờ biển thanh bình vào lúc chạng vạng.", syn: ["twilight", "sunset"], ant: ["dawn"] },
    { word: "sunrise", phonetic: "/ˈsʌnraɪz/", def: "The time in the morning when the sun appears or full daylight arrives.", defVn: "mặt trời mọc, rạng sáng", pos: "noun", ex1: "We woke up at five to watch the breathtaking sunrise over the ocean.", ex1Vn: "Chúng tôi thức dậy lúc năm giờ để ngắm cảnh mặt trời mọc ngoạn mục trên đại dương.", ex2: "The sunrise painted the sky in shades of crimson.", ex2Vn: "Mặt trời mọc nhuộm cả bầu trời trong sắc đỏ rực rỡ.", syn: ["daybreak"], ant: ["sunset"] },
    { word: "sunset", phonetic: "/ˈsʌnset/", def: "The time in the evening when the sun disappears or daylight fades.", defVn: "mặt trời lặn, hoàng hôn", pos: "noun", ex1: "Tourists gather on the cliff to photograph the sunset.", ex1Vn: "Du khách tụ tập trên vách đá để chụp ảnh cảnh mặt trời lặn.", ex2: "The golden sunset marked the close of a joyful day.", ex2Vn: "Hoàng hôn dát vàng đánh dấu sự khép lại của một ngày tràn ngập niềm vui.", syn: ["sundown"], ant: ["sunrise"] },
    { word: "weekend", phonetic: "/ˈwiːkend/", def: "Saturday and Sunday, especially regarded as a time for leisure.", defVn: "cuối tuần (Thứ Bảy & Chủ Nhật)", pos: "noun", ex1: "What exciting plans do you have for this upcoming weekend?", ex1Vn: "Bạn có kế hoạch thú vị nào cho dịp cuối tuần sắp tới chưa?", ex2: "We love going for family picnics on the weekend.", ex2Vn: "Chúng tôi rất thích đi dã ngoại cùng gia đình vào dịp cuối tuần.", syn: [], ant: ["weekday"] },
    { word: "weekday", phonetic: "/ˈwiːkdeɪ/", def: "Any day of the week except Sunday, or except Saturday and Sunday.", defVn: "ngày trong tuần (từ Thứ Hai đến Thứ Sáu)", pos: "noun", ex1: "The bank is open on weekdays from eight to five.", ex1Vn: "Ngân hàng mở cửa vào các ngày trong tuần từ tám giờ đến năm giờ.", ex2: "Traffic is typically heavier on weekdays during rush hour.", ex2Vn: "Giao thông thường đông đúc hơn vào các ngày trong tuần trong giờ cao điểm.", syn: ["workday"], ant: ["weekend"] },
    { word: "fortnight", phonetic: "/ˈfɔːrtnaɪt/", def: "A period of two weeks (14 days).", defVn: "hai tuần lễ (14 ngày)", pos: "noun", ex1: "They spent a delightful fortnight holidaying in Dalat.", ex1Vn: "Họ đã dành trọn hai tuần lễ tuyệt vời để đi nghỉ dưỡng ở Đà Lạt.", ex2: "The project will be completed in a fortnight.", ex2Vn: "Dự án sẽ được hoàn thành trong vòng hai tuần nữa.", syn: ["two weeks"], ant: [] },
    { word: "decade", phonetic: "/ˈdekeɪd/", def: "A period of ten years.", defVn: "thập kỷ (10 năm)", pos: "noun", ex1: "Technology has evolved tremendously over the past decade.", ex1Vn: "Công nghệ đã phát triển vượt bậc trong suốt một thập kỷ qua.", ex2: "They celebrated a decade of successful marriage.", ex2Vn: "Họ đã kỷ niệm tròn một thập kỷ hôn nhân hạnh phúc.", syn: [], ant: [] },
    { word: "century", phonetic: "/ˈsentʃəri/", def: "A period of one hundred years.", defVn: "thế kỷ (100 năm)", pos: "noun", ex1: "We are living in the vibrant twenty-first century.", ex1Vn: "Chúng ta đang sống trong thế kỷ hai mươi mốt đầy sôi động.", ex2: "The ancient pagoda was constructed in the seventeenth century.", ex2Vn: "Ngôi chùa cổ kính được xây dựng từ thế kỷ mười bảy.", syn: [], ant: [] },
    { word: "autumn", phonetic: "/ˈɔːtəm/", def: "The third season of the year, when crops and fruits gather and leaves fall.", defVn: "mùa thu", pos: "noun", ex1: "Autumn in Hanoi brings cool breezes and fragrant milk flowers.", ex1Vn: "Mùa thu Hà Nội mang theo những cơn gió heo may mát mẻ và hương hoa sữa nồng nàn.", ex2: "Golden leaves carpet the park paths in autumn.", ex2Vn: "Những chiếc lá vàng trải thảm trên các lối đi công viên vào mùa thu.", syn: ["fall"], ant: ["spring"] },
    { word: "winter", phonetic: "/ˈwɪntər/", def: "The coldest season of the year, between autumn and spring.", defVn: "mùa đông", pos: "noun", ex1: "Bundle up in a warm coat during the chilly winter.", ex1Vn: "Hãy mặc áo khoác ấm áp trong mùa đông giá lạnh nhé.", ex2: "Snow covers the mountain peaks in deep winter.", ex2Vn: "Tuyết phủ kín các đỉnh núi vào giữa mùa đông giá rét.", syn: [], ant: ["summer"] },
    { word: "spring", phonetic: "/sprɪŋ/", def: "The season after winter and before summer, in which vegetation begins to appear.", defVn: "mùa xuân", pos: "noun", ex1: "Spring brings vibrant peach blossoms and joyful Tet reunions.", ex1Vn: "Mùa xuân mang đến hoa đào rực rỡ và những cuộc đoàn viên Tết sum vầy.", ex2: "Nature awakens and flowers bloom profusely in spring.", ex2Vn: "Thiên nhiên bừng tỉnh và muôn hoa đua nở rực rỡ vào mùa xuân.", syn: [], ant: ["autumn"] },
    { word: "summer", phonetic: "/ˈsʌmər/", def: "The warmest season of the year, between spring and autumn.", defVn: "mùa hè, mùa hạ", pos: "noun", ex1: "Summer is the perfect season for beach vacations and swimming.", ex1Vn: "Mùa hè là mùa hoàn hảo cho các chuyến nghỉ dưỡng biển và bơi lội.", ex2: "Students look forward to their long summer holidays.", ex2Vn: "Học sinh rất háo hức mong chờ kỳ nghỉ hè dài ngày của mình.", syn: [], ant: ["winter"] }
  ],

  // Theme 11: Animals (14 extra)
  t_basic_animals: [
    { word: "puppy", phonetic: "/ˈpʌpi/", def: "A young dog, especially one less than a year old.", defVn: "chú cún con, chó con", pos: "noun", ex1: "The playful puppy wagged its tail excitedly.", ex1Vn: "Chú cún con tinh nghịch vẫy đuôi đầy phấn khích.", ex2: "We adopted an adorable golden puppy from the shelter.", ex2Vn: "Chúng tôi đã nhận nuôi một chú cún vàng đáng yêu từ trạm cứu hộ.", syn: ["pup", "doggy"], ant: [] },
    { word: "kitten", phonetic: "/ˈkɪtn/", def: "A young cat.", defVn: "chú mèo con", pos: "noun", ex1: "The tiny fluffy kitten curled up on my lap to sleep.", ex1Vn: "Chú mèo con lông xù bé nhỏ cuộn tròn trên đùi tôi ngủ ngon lành.", ex2: "Kittens love chasing balls of yarn across the floor.", ex2Vn: "Mèo con rất thích đuổi theo những cuộn len lăn trên sàn.", syn: ["kitty"], ant: [] },
    { word: "duckling", phonetic: "/ˈdʌklɪŋ/", def: "A young duck.", defVn: "chú vịt con", pos: "noun", ex1: "Yellow ducklings followed their mother into the pond.", ex1Vn: "Những chú vịt con màu vàng bơi theo sau mẹ xuống ao nước.", ex2: "The story of the ugly duckling teaches self-acceptance.", ex2Vn: "Câu chuyện về chú vịt con xấu xí dạy chúng ta bài học về sự tự tin.", syn: [], ant: [] },
    { word: "lamb", phonetic: "/læm/", def: "A young sheep.", defVn: "chú cừu non", pos: "noun", ex1: "The little white lamb skipped across the green meadow.", ex1Vn: "Chú cừu non lông trắng nhảy chân sáo qua đồng cỏ xanh mướt.", ex2: "Farmers carefully protect newborn lambs in cold weather.", ex2Vn: "Những người nông dân cẩn thận bảo vệ cừu non mới sinh trong thời tiết lạnh.", syn: [], ant: [] },
    { word: "calf", phonetic: "/kæf/", def: "A young bovine animal, especially a domestic cow or bull in its first year.", defVn: "chú bê con, bò con", pos: "noun", ex1: "The brown calf drank fresh milk beside its mother.", ex1Vn: "Chú bê con màu nâu bú sữa tươi cạnh mẹ nó.", ex2: "A healthy newborn calf stood up on its wobbly legs.", ex2Vn: "Chú bê con mới chào đời khỏe mạnh đã đứng dậy trên đôi chân còn lảo đảo.", syn: [], ant: [] },
    { word: "rabbit", phonetic: "/ˈræbɪt/", def: "A burrowing, gregarious, plant-eating mammal with long ears, long hind legs, and a short tail.", defVn: "con thỏ", pos: "noun", ex1: "The white rabbit munched happily on a crunchy carrot.", ex1Vn: "Chú thỏ trắng nhai vui vẻ củ cà rốt giòn rụm.", ex2: "Rabbits have keen hearing thanks to their long upright ears.", ex2Vn: "Loài thỏ có thính giác rất nhạy bén nhờ đôi tai dài dựng đứng.", syn: ["bunny", "hare"], ant: [] },
    { word: "parrot", phonetic: "/ˈpærət/", def: "A mainly tropical bird with bright plumage and a hooked beak, notable for its ability to mimic speech.", defVn: "con vẹt (biết nói)", pos: "noun", ex1: "The colorful parrot can repeat phrases like 'Hello' and 'Good morning'.", ex1Vn: "Chú vẹt sặc sỡ có thể lặp lại các câu như 'Xin chào' và 'Chào buổi sáng'.", ex2: "Tropical parrots have stunning emerald and scarlet feathers.", ex2Vn: "Những chú vẹt nhiệt đới có bộ lông màu ngọc bích và đỏ tươi tuyệt đẹp.", syn: [], ant: [] },
    { word: "hamster", phonetic: "/ˈhæmstər/", def: "A solitary burrowing rodent with a short tail and large cheek pouches.", defVn: "chuột hamster (chuột kiểng)", pos: "noun", ex1: "The furry hamster runs tirelessly on its exercise wheel.", ex1Vn: "Chú chuột hamster lông mịn màng chạy không biết mệt trên bánh xe tập thể dục.", ex2: "Children enjoy caring for friendly pet hamsters.", ex2Vn: "Trẻ em rất thích chăm sóc những chú chuột hamster kiểng thân thiện.", syn: [], ant: [] },
    { word: "sheep", phonetic: "/ʃiːp/", def: "A domesticated ruminant mammal with a thick woolly coat.", defVn: "con cừu", pos: "noun", ex1: "A flock of fluffy sheep grazed peacefully on the hillside.", ex1Vn: "Một đàn cừu lông xù gặm cỏ yên bình trên sườn đồi.", ex2: "Warm winter sweaters are knitted from sheep's wool.", ex2Vn: "Những chiếc áo len mùa đông ấm áp được đan từ lông cừu tự nhiên.", syn: [], ant: [] },
    { word: "goat", phonetic: "/ɡoʊt/", def: "A hardy domesticated ruminant mammal with backward-curving horns and a beard.", defVn: "con dê", pos: "noun", ex1: "The agile mountain goat climbed effortlessly up rocky cliffs.", ex1Vn: "Chú dê núi nhanh nhẹn leo thoăn thoắt lên những vách đá gập ghềnh.", ex2: "Goat milk is nutrient-dense and easy to digest.", ex2Vn: "Sữa dê rất giàu dinh dưỡng và dễ tiêu hóa.", syn: [], ant: [] },
    { word: "donkey", phonetic: "/ˈdɑːŋki/", def: "A domesticated hoofed mammal of the horse family with long ears and a braying call.", defVn: "con lừa", pos: "noun", ex1: "The hardworking donkey carried baskets of fresh fruit up the path.", ex1Vn: "Chú lừa chăm chỉ chở những giỏ trái cây tươi lên con dốc.", ex2: "Donkeys are known for their calm and resilient nature.", ex2Vn: "Loài lừa nổi tiếng với bản tính điềm tĩnh và bền bỉ.", syn: ["mule", "burro"], ant: [] },
    { word: "camel", phonetic: "/ˈkæml/", def: "A large, long-necked ungulate mammal of arid country, with one or two humps on the back.", defVn: "con lạc đà", pos: "noun", ex1: "Camels can travel for days across sandy deserts without water.", ex1Vn: "Lạc đà có thể di chuyển nhiều ngày qua sa mạc cát mà không cần uống nước.", ex2: "Tourists rode camels to watch the sunset over the desert dunes.", ex2Vn: "Du khách cưỡi lạc đà ngắm hoàng hôn buông trên những cồn cát sa mạc.", syn: [], ant: [] },
    { word: "squirrel", phonetic: "/ˈskwɜːrəl/", def: "An agile tree-dwelling rodent with a bushy tail.", defVn: "con sóc", pos: "noun", ex1: "The agile squirrel buried acorns in the garden for winter.", ex1Vn: "Chú sóc nhanh nhẹn chôn những quả sồi trong vườn để dự trữ cho mùa đông.", ex2: "A squirrel leaped gracefully from branch to branch.", ex2Vn: "Một chú sóc nhảy thoăn thoắt và duyên dáng từ cành này sang cành khác.", syn: [], ant: [] },
    { word: "deer", phonetic: "/dɪr/", def: "A hoofed grazing or browsing animal, with branched bony antlers that are shed annually.", defVn: "con hươu, con nai", pos: "noun", ex1: "A gentle deer grazed peacefully near the edge of the forest.", ex1Vn: "Một chú hươu hiền lành gặm cỏ yên bình gần bìa rừng.", ex2: "Spotted deer are protected within the national park wildlife sanctuary.", ex2Vn: "Những chú hươu sao được bảo vệ nghiêm ngặt trong khu bảo tồn thiên nhiên vườn quốc gia.", syn: ["stag", "doe"], ant: [] }
  ],

  // Theme 12: Body Parts (14 extra)
  t_basic_body_parts: [
    { word: "eyebrow", phonetic: "/ˈaɪbraʊ/", def: "The strip of hair growing on the ridge above a person's eye socket.", defVn: "lông mày, chân mày", pos: "noun", ex1: "He raised an eyebrow in curious surprise.", ex1Vn: "Anh ấy nhướng một bên lông mày lên vì ngạc nhiên tò mò.", ex2: "She shapes her eyebrows neatly every morning.", ex2Vn: "Cô ấy tỉa gọn gàng đôi chân mày của mình vào mỗi sáng.", syn: [], ant: [] },
    { word: "eyelash", phonetic: "/ˈaɪlæʃ/", def: "Each of the short curved hairs growing on the edges of the eyelids.", defVn: "lông mi", pos: "noun", ex1: "She has naturally long and curved dark eyelashes.", ex1Vn: "Cô ấy có hàng lông mi đen dài và cong tự nhiên.", ex2: "Eyelashes shield our eyes from airborne dust particles.", ex2Vn: "Lông mi giúp che chắn bảo vệ đôi mắt khỏi những hạt bụi trong không khí.", syn: ["lash"], ant: [] },
    { word: "cheek", phonetic: "/tʃiːk/", def: "Either side of the face below the eye.", defVn: "má, gò má", pos: "noun", ex1: "Her cheeks flushed rosy pink in the cool morning air.", ex1Vn: "Đôi gò má cô ấy ửng hồng trong làn không khí mát mẻ buổi sáng.", ex2: "Grandma gave the baby a tender kiss on the cheek.", ex2Vn: "Bà nhẹ nhàng hôn một nụ hôn dịu dàng lên má em bé.", syn: [], ant: [] },
    { word: "chin", phonetic: "/tʃɪn/", def: "The protruding part of the face below the lower lip.", defVn: "cằm", pos: "noun", ex1: "He rested his chin thoughtfully on his hand while reading.", ex1Vn: "Anh ấy chống cằm trầm ngâm suy nghĩ trong lúc đọc sách.", ex2: "Keep your chin up and stay confident through challenges.", ex2Vn: "Hãy ngẩng cao cằm và giữ vững sự tự tin vượt qua mọi thử thách nhé.", syn: [], ant: [] },
    { word: "forehead", phonetic: "/ˈfɔːrhed/", def: "The part of the face above the eyebrows.", defVn: "trán", pos: "noun", ex1: "Mother touched my forehead gently to check if I had a fever.", ex1Vn: "Mẹ khẽ chạm vào trán tôi để kiểm tra xem tôi có bị sốt không.", ex2: "Wipe sweat from your forehead after working out.", ex2Vn: "Hãy lau mồ hôi trên trán sau khi tập thể dục nhé.", syn: ["brow"], ant: [] },
    { word: "wrist", phonetic: "/rɪst/", def: "The joint connecting the hand with the forearm.", defVn: "cổ tay", pos: "noun", ex1: "He wears a classic leather watch around his left wrist.", ex1Vn: "Anh ấy đeo một chiếc đồng hồ dây da cổ điển trên cổ tay trái.", ex2: "Stretch and rotate your wrists after long typing sessions.", ex2Vn: "Hãy kéo giãn và xoay cổ tay sau những giờ gõ bàn phím kéo dài nhé.", syn: [], ant: [] },
    { word: "elbow", phonetic: "/ˈelboʊ/", def: "The joint between the forearm and the upper arm.", defVn: "khuỷu tay, cùi chỏ", pos: "noun", ex1: "Resting your elbows on the dining table is bad etiquette.", ex1Vn: "Chống khuỷu tay lên bàn ăn là hành vi không lịch sự.", ex2: "He protected his elbows with padded guards while rollerblading.", ex2Vn: "Cậu ấy bảo vệ khuỷu tay bằng miếng đệm bảo hộ khi trượt patin.", syn: [], ant: [] },
    { word: "ankle", phonetic: "/ˈæŋkl/", def: "The joint connecting the foot with the leg.", defVn: "mắt cá chân, cổ chân", pos: "noun", ex1: "High-top athletic shoes provide extra support for the ankle.", ex1Vn: "Giày thể thao cổ cao mang lại sự nâng đỡ tốt hơn cho cổ chân.", ex2: "Be careful not to twist your ankle on uneven stone steps.", ex2Vn: "Hãy cẩn thận kẻo bị trẹo mắt cá chân trên những bậc đá không bằng phẳng nhé.", syn: [], ant: [] },
    { word: "heel", phonetic: "/hiːl/", def: "The back part of the human foot below the ankle.", defVn: "gót chân", pos: "noun", ex1: "Cushioned shoe soles protect your heels from hard impact.", ex1Vn: "Đế giày êm ái bảo vệ gót chân bạn khỏi những va đập mạnh.", ex2: "She wore stylish low-heeled shoes to the ceremony.", ex2Vn: "Cô ấy đi đôi giày gót thấp thanh lịch đến dự buổi lễ.", syn: [], ant: ["toe"] },
    { word: "palm", phonetic: "/pɑːm/", def: "The inner surface of the hand between the wrist and fingers.", defVn: "lòng bàn tay", pos: "noun", ex1: "He held the shiny gold coin in the open palm of his hand.", ex1Vn: "Anh ấy cầm đồng xu vàng sáng bóng trong lòng bàn tay mở rộng.", ex2: "Clap your palms together to the beat of the song.", ex2Vn: "Hãy vỗ hai lòng bàn tay vào nhau theo nhịp điệu bài hát nhé.", syn: [], ant: [] },
    { word: "thumb", phonetic: "/θʌm/", def: "The short, thick first digit of the human hand, opposable to the others.", defVn: "ngón tay cái", pos: "noun", ex1: "Give a thumbs-up sign to show enthusiastic approval.", ex1Vn: "Hãy giơ ngón tay cái lên để thể hiện sự đồng ý nhiệt tình nhé.", ex2: "He accidentally pricked his thumb on a rose thorn.", ex2Vn: "Cậu ấy vô tình bị gai hoa hồng châm vào ngón tay cái.", syn: [], ant: [] },
    { word: "throat", phonetic: "/θroʊt/", def: "The passage which leads from the back of the mouth of a person or animal.", defVn: "cổ họng, họng", pos: "noun", ex1: "Drink warm ginger tea with honey to soothe a sore throat.", ex1Vn: "Uống trà gừng ấm pha mật ong để làm dịu cơn đau họng nhé.", ex2: "Singers practice vocal warm-ups to protect their throat.", ex2Vn: "Các ca sĩ luyện thanh khởi động để bảo vệ cổ họng của mình.", syn: ["pharynx"], ant: [] },
    { word: "chest", phonetic: "/tʃest/", def: "The front surface of a person's body between the neck and the stomach.", defVn: "lồng ngực, ngực", pos: "noun", ex1: "Take a deep breath and feel your chest expand fully.", ex1Vn: "Hít một hơi thật sâu và cảm nhận lồng ngực nở rộng hoàn toàn.", ex2: "He placed his hand over his chest during the national anthem.", ex2Vn: "Anh ấy đặt tay lên ngực trái trong suốt bài quốc ca.", syn: ["torso", "breast"], ant: [] },
    { word: "belly", phonetic: "/ˈbeli/", def: "The front part of the human trunk below the ribs, containing the stomach and bowels.", defVn: "bụng (bụng dạ)", pos: "noun", ex1: "The cat rolled over on its back asking for a gentle belly rub.", ex1Vn: "Chú mèo lật ngửa lưng ra đòi được xoa bụng nhẹ nhàng.", ex2: "A good hearty laugh comes straight from the belly.", ex2Vn: "Một tràng cười sảng khoái xuất phát từ tận đáy lòng.", syn: ["stomach", "tummy", "abdomen"], ant: [] }
  ],

  // Theme 13: Clothing & Outfits (16 extra)
  t_basic_clothes: [
    { word: "sweater", phonetic: "/ˈswetər/", def: "A knitted garment worn on the upper body, typically with long sleeves.", defVn: "áo len, áo chui đầu", pos: "noun", ex1: "Wear a soft cashmere sweater on chilly autumn evenings.", ex1Vn: "Mặc một chiếc áo len cashmere mềm mại vào những buổi tối mùa thu se lạnh.", ex2: "Grandmother knitted a cozy wool sweater for my birthday.", ex2Vn: "Bà đã đan một chiếc áo len ấm áp nhân dịp sinh nhật tôi.", syn: ["jumper", "pullover"], ant: [] },
    { word: "hoodie", phonetic: "/ˈhʊdi/", def: "A hooded sweatshirt or jacket.", defVn: "áo nỉ có mũ trùm đầu (áo hoodie)", pos: "noun", ex1: "Teenagers love wearing comfortable oversized hoodies.", ex1Vn: "Giới trẻ rất thích mặc những chiếc áo hoodie phom rộng thoải mái.", ex2: "Pull up your warm hoodie when the evening wind picks up.", ex2Vn: "Hãy trùm mũ áo hoodie ấm áp lên khi gió chiều bắt đầu thổi mạnh nhé.", syn: ["sweatshirt"], ant: [] },
    { word: "jacket", phonetic: "/ˈdʒækɪt/", def: "An outer garment extending either to the waist or the hips.", defVn: "áo khoác (ngắn ngang hông)", pos: "noun", ex1: "Zip up your leather jacket before riding your motorbike.", ex1Vn: "Kéo khóa chiếc áo khoác da trước khi lái xe máy nhé.", ex2: "She wore a lightweight windproof jacket on the hike.", ex2Vn: "Cô ấy mặc một chiếc áo khoác cản gió siêu nhẹ trong chuyến leo núi.", syn: ["coat", "windbreaker"], ant: [] },
    { word: "scarf", phonetic: "/skɑːrf/", def: "A length or square of fabric worn around the neck or head.", defVn: "khăn quàng cổ, khăn choàng", pos: "noun", ex1: "Wrap a warm wool scarf around your neck in winter.", ex1Vn: "Quấn một chiếc khăn len ấm quanh cổ vào mùa đông nhé.", ex2: "She tied an elegant silk scarf around her handbag.", ex2Vn: "Cô ấy thắt một chiếc khăn lụa thanh lịch quanh quai túi xách.", syn: ["muffler", "shawl"], ant: [] },
    { word: "gloves", phonetic: "/ɡlʌvz/", def: "Coverings for the hand having separate sheaths for each finger and as a whole.", defVn: "đôi găng tay (bảo vệ đôi tay)", pos: "noun", ex1: "Wear thermal leather gloves to keep hands warm in snowy weather.", ex1Vn: "Đeo găng tay da giữ nhiệt để giữ ấm đôi tay trong thời tiết có tuyết.", ex2: "Gardening gloves protect your hands from thorny weeds.", ex2Vn: "Găng tay làm vườn giúp bảo vệ tay bạn khỏi cỏ dại có gai.", syn: ["mittens"], ant: [] },
    { word: "boots", phonetic: "/buːts/", def: "Sturdy footwear covering the foot and ankle, and sometimes the lower or whole leg.", defVn: "đôi bốt, giày cổ cao", pos: "noun", ex1: "Waterproof hiking boots protect your feet on rocky trails.", ex1Vn: "Đôi giày bốt leo núi chống nước bảo vệ đôi chân trên các con đường mòn sỏi đá.", ex2: "She wore stylish leather ankle boots with her jeans.", ex2Vn: "Cô ấy diện đôi bốt da cổ thấp sành điệu cùng quần jean.", syn: ["footwear"], ant: [] },
    { word: "sandals", phonetic: "/ˈsændlz/", def: "Light shoes consisting of a sole fastened to the foot by straps.", defVn: "đôi dép xăng-đan, dép quai hậu", pos: "noun", ex1: "Breathable leather sandals are ideal for tropical summer weather.", ex1Vn: "Dép xăng-đan bằng da thoáng khí rất lý tưởng cho thời tiết mùa hè nhiệt đới.", ex2: "Pack comfortable walking sandals for your beach resort vacation.", ex2Vn: "Hãy mang theo đôi dép xăng-đan đi bộ thoải mái cho kỳ nghỉ dưỡng biển nhé.", syn: ["flip-flops"], ant: ["boots"] },
    { word: "sneakers", phonetic: "/ˈsniːkərz/", def: "Soft shoes with a rubber sole worn for sports or casual occasions.", defVn: "giày thể thao, giày sneaker", pos: "noun", ex1: "Lace up your cushioned sneakers before your morning jog.", ex1Vn: "Buộc dây giày thể thao êm ái trước buổi chạy bộ buổi sáng nhé.", ex2: "White sneakers match effortlessly with almost every casual outfit.", ex2Vn: "Giày sneaker trắng phối đồ cực kỳ dễ dàng với hầu hết mọi trang phục thường ngày.", syn: ["trainers", "tennis shoes"], ant: [] },
    { word: "tie", phonetic: "/taɪ/", def: "A strip of material worn around the collar and tied in a knot at the front.", defVn: "cà vạt (thắt cổ áo)", pos: "noun", ex1: "He wore a navy blue silk tie to the business conference.", ex1Vn: "Anh ấy thắt một chiếc cà vạt lụa màu xanh navy đến dự hội nghị kinh doanh.", ex2: "Learn how to tie a neat Windsor knot on your tie.", ex2Vn: "Hãy học cách thắt nút Windsor gọn gàng trên cà vạt của bạn nhé.", syn: ["necktie"], ant: [] },
    { word: "belt", phonetic: "/belt/", def: "A strip of leather or other material worn around the waist to support clothes.", defVn: "thắt lưng, dây nịt", pos: "noun", ex1: "Fasten your leather belt securely around your trousers.", ex1Vn: "Thắt chặt dây thắt lưng da quanh quần tây nhé.", ex2: "A brown belt matches nicely with brown dress shoes.", ex2Vn: "Thắt lưng màu nâu kết hợp rất ăn ý với giày tây màu nâu.", syn: ["strap", "waistband"], ant: [] },
    { word: "vest", phonetic: "/vest/", def: "A sleeveless garment worn on the upper body, typically over a shirt.", defVn: "áo gile, áo ba lỗ", pos: "noun", ex1: "He wore a formal tailored vest under his suit jacket.", ex1Vn: "Anh ấy mặc một chiếc áo gile may đo lịch lãm bên trong áo vest.", ex2: "Reflective safety vests are mandatory for construction workers.", ex2Vn: "Áo gile bảo hộ phản quang là bắt buộc đối với công nhân xây dựng.", syn: ["waistcoat", "tank top"], ant: [] },
    { word: "raincoat", phonetic: "/ˈreɪnkoʊt/", def: "A coat that repels rain.", defVn: "áo mưa (chống thấm nước)", pos: "noun", ex1: "Always keep a compact raincoat in your scooter trunk.", ex1Vn: "Hãy luôn để một chiếc áo mưa nhỏ gọn trong cốp xe máy nhé.", ex2: "Bright yellow raincoats keep children safe and dry in heavy downpours.", ex2Vn: "Áo mưa màu vàng tươi giúp các em nhỏ khô ráo và an toàn dưới cơn mưa rào nặng hạt.", syn: ["slicker", "mackintosh"], ant: [] },
    { word: "pajamas", phonetic: "/pəˈdʒæməz/", def: "A suit of loose-fitting trousers and jacket for sleeping in.", defVn: "bộ đồ ngủ pijama", pos: "noun", ex1: "Change into cozy silk pajamas before heading to bed.", ex1Vn: "Thay bộ đồ ngủ pijama bằng lụa êm ái trước khi lên giường đi ngủ nhé.", ex2: "Soft cotton pajamas guarantee a comfortable night's rest.", ex2Vn: "Đồ ngủ cotton mềm mại đảm bảo cho bạn một giấc ngủ đêm ngon lành.", syn: ["nightwear", "sleepwear"], ant: [] },
    { word: "uniform", phonetic: "/ˈjuːnɪfɔːrm/", def: "The distinctive clothing worn by members of the same organization or body.", defVn: "đồng phục (học sinh, cơ quan)", pos: "noun", ex1: "Students wear neat white-shirt uniforms to school on Mondays.", ex1Vn: "Học sinh mặc đồng phục áo sơ mi trắng tinh tươm đến trường vào Thứ Hai.", ex2: "Flight attendants look professional in their tailored airline uniforms.", ex2Vn: "Các tiếp viên hàng không trông rất chuyên nghiệp trong bộ đồng phục may đo của hãng.", syn: ["attire", "livery"], ant: [] },
    { word: "suit", phonetic: "/suːt/", def: "A set of outer clothes made of the same fabric, typically consisting of a jacket and trousers or skirt.", defVn: "bộ âu phục, bộ veston", pos: "noun", ex1: "He invested in a tailored dark grey wool suit for job interviews.", ex1Vn: "Anh ấy đã đầu tư một bộ âu phục len màu xám đen may đo cho các buổi phỏng vấn việc làm.", ex2: "A sharp suit makes a commanding first impression in business.", ex2Vn: "Một bộ vest chỉn chu tạo ấn tượng đầu tiên đĩnh đạc trong kinh doanh.", syn: ["tuxedo", "costume"], ant: [] },
    { word: "dress", phonetic: "/dres/", def: "A one-piece garment for a woman or girl that covers the body and extends down over the legs.", defVn: "chiếc váy liền, đầm", pos: "noun", ex1: "She wore a breathtaking floral evening dress to the gala dinner.", ex1Vn: "Cô ấy diện một chiếc đầm dạ hội hoa rực rỡ đến bữa tiệc sang trọng.", ex2: "A breezy linen dress is comfortable for summer seaside walks.", ex2Vn: "Chiếc đầm vải lanh nhẹ mát rất thoải mái cho những buổi dạo bờ biển mùa hè.", syn: ["gown", "frock"], ant: [] }
  ],

  // Theme 14: Places & Directions (17 extra)
  t_basic_places_directions: [
    { word: "library", phonetic: "/ˈlaɪbreri/", def: "A building or room containing collections of books and periodicals for people to read or borrow.", defVn: "thư viện (đọc và mượn sách)", pos: "noun", ex1: "Students study quietly in the university central library.", ex1Vn: "Sinh viên chăm chỉ học tập tĩnh lặng trong thư viện trung tâm trường đại học.", ex2: "You can borrow up to five novels with your library card.", ex2Vn: "Bạn có thể mượn tối đa năm cuốn tiểu thuyết bằng thẻ thư viện.", syn: [], ant: [] },
    { word: "supermarket", phonetic: "/ˈsuːpərmɑːrkɪt/", def: "A large self-service shop selling foods and household goods.", defVn: "siêu thị", pos: "noun", ex1: "We do our weekly grocery shopping at the neighborhood supermarket.", ex1Vn: "Chúng tôi mua sắm hàng tạp hóa hàng tuần tại siêu thị gần nhà.", ex2: "Supermarket shelves are filled with fresh dairy and produce.", ex2Vn: "Các kệ hàng siêu thị chứa đầy sữa tươi và nông sản sạch.", syn: ["grocery store"], ant: [] },
    { word: "pharmacy", phonetic: "/ˈfɑːrməsi/", def: "A shop or hospital dispensary where medicinal drugs are prepared or sold.", defVn: "hiệu thuốc, nhà thuốc tây", pos: "noun", ex1: "Buy prescribed allergy medicines at the 24-hour pharmacy.", ex1Vn: "Mua thuốc chống dị ứng theo đơn tại hiệu thuốc mở cửa 24 giờ nhé.", ex2: "The licensed pharmacist gave clear guidance on dosage.", ex2Vn: "Dược sĩ có chứng chỉ đã hướng dẫn liều dùng rất rõ ràng.", syn: ["drugstore", "chemist"], ant: [] },
    { word: "bakery", phonetic: "/ˈbeɪkəri/", def: "A place where bread and cakes are made or sold.", defVn: "tiệm bánh mì, tiệm bánh ngọt", pos: "noun", ex1: "The neighborhood bakery smells of warm fresh baguettes every morning.", ex1Vn: "Tiệm bánh gần nhà luôn thơm nức mùi bánh mì que nóng hổi mỗi sáng.", ex2: "We ordered a custom strawberry birthday cake from the bakery.", ex2Vn: "Chúng tôi đã đặt một chiếc bánh sinh nhật dâu tây tại tiệm bánh.", syn: ["bakehouse"], ant: [] },
    { word: "bookstore", phonetic: "/ˈbʊkstɔːr/", def: "A shop where books are sold.", defVn: "hiệu sách, nhà sách", pos: "noun", ex1: "I spent hours browsing illustrated dictionaries at the downtown bookstore.", ex1Vn: "Tôi đã dành hàng giờ xem từ điển minh họa tại hiệu sách trung tâm.", ex2: "The local bookstore hosts weekend author meet-and-greets.", ex2Vn: "Hiệu sách địa phương tổ chức các buổi giao lưu tác giả vào dịp cuối tuần.", syn: ["bookseller"], ant: [] },
    { word: "museum", phonetic: "/mjuˈziːəm/", def: "A building in which objects of historical, scientific, artistic, or cultural interest are stored and exhibited.", defVn: "bảo tàng", pos: "noun", ex1: "The national history museum displays ancient bronze drums and pottery.", ex1Vn: "Bảo tàng lịch sử quốc gia trưng bày trống đồng cổ và gốm sứ xưa.", ex2: "Admission to the city art museum is free on Sundays.", ex2Vn: "Vé vào cửa bảo tàng nghệ thuật thành phố được miễn phí vào Chủ Nhật.", syn: ["gallery"], ant: [] },
    { word: "cinema", phonetic: "/ˈsɪnəmə/", def: "A theatre where films are shown for public entertainment.", defVn: "rạp chiếu phim", pos: "noun", ex1: "We booked front-row cinema tickets for the new animated film.", ex1Vn: "Chúng tôi đã đặt vé xem phim ở hàng ghế đầu cho bộ phim hoạt hình mới.", ex2: "Popcorn and soda are popular snacks at the cinema.", ex2Vn: "Bắp rang bơ và nước ngọt là những món ăn vặt phổ biến ở rạp chiếu phim.", syn: ["movie theater"], ant: [] },
    { word: "park", phonetic: "/pɑːrk/", def: "A large public green area in a town, used for recreation.", defVn: "công viên cây xanh", pos: "noun", ex1: "Families stroll and fly colorful kites in the botanical park.", ex1Vn: "Các gia đình dạo bước và thả diều sặc sỡ trong công viên bách thảo.", ex2: "Jogging along tree-lined park trails boosts morning energy.", ex2Vn: "Chạy bộ dọc các lối mòn rợp bóng cây trong công viên giúp tăng năng lượng buổi sáng.", syn: ["gardens"], ant: [] },
    { word: "intersection", phonetic: "/ˌɪntərˈsekʃn/", def: "A point at which two or more things, especially roads, intersect.", defVn: "ngã tư, giao lộ", pos: "noun", ex1: "Slow down and watch for pedestrians when approaching the busy intersection.", ex1Vn: "Hãy giảm tốc độ và quan sát người đi bộ khi đến gần giao lộ đông đúc nhé.", ex2: "Traffic lights at the four-way intersection regulate vehicle flow.", ex2Vn: "Đèn giao thông tại ngã tư bốn ngả điều tiết luồng xe cộ qua lại.", syn: ["crossroad", "junction"], ant: [] },
    { word: "sidewalk", phonetic: "/ˈsaɪdwɔːk/", def: "A paved path for pedestrians at the side of a road.", defVn: "vỉa hè, lề đường dành cho người đi bộ", pos: "noun", ex1: "Always walk on the wide pedestrian sidewalk for safety.", ex1Vn: "Hãy luôn đi trên vỉa hè rộng rãi dành cho người đi bộ để đảm bảo an toàn nhé.", ex2: "Shady trees line the brick sidewalk along the boulevard.", ex2Vn: "Những hàng cây râm mát rợp bóng vỉa hè lát gạch dọc đại lộ.", syn: ["pavement", "footpath"], ant: ["roadway"] },
    { word: "straight", phonetic: "/streɪt/", def: "In a continuous and direct line without bending.", defVn: "thẳng, đi thẳng", pos: "adverb", ex1: "Go straight ahead for two blocks, then turn left.", ex1Vn: "Hãy đi thẳng về phía trước qua hai dãy nhà, rồi rẽ trái nhé.", ex2: "Keep going straight until you see the big clock tower.", ex2Vn: "Tiếp tục đi thẳng cho đến khi bạn nhìn thấy tháp đồng hồ lớn.", syn: ["directly", "forthright"], ant: ["crooked", "curved"] },
    { word: "corner", phonetic: "/ˈkɔːrnər/", def: "A place or angle where two sides or edges meet.", defVn: "góc phố, góc đường, góc phòng", pos: "noun", ex1: "There is a charming coffee shop located right at the street corner.", ex1Vn: "Có một quán cà phê xinh xắn tọa lạc ngay tại góc phố.", ex2: "Turn sharp right around the corner to reach the post office.", ex2Vn: "Rẽ ngoặt sang phải quanh góc đường để đến bưu điện nhé.", syn: ["bend", "angle"], ant: [] },
    { word: "left", phonetic: "/left/", def: "On, towards, or relating to the side of a human body or of a thing which is to the west when facing north.", defVn: "bên trái, rẽ trái", pos: "adverb", ex1: "Turn left at the traffic light to enter Nguyen Hue Boulevard.", ex1Vn: "Rẽ trái tại cột đèn giao thông để vào đường Nguyễn Huệ nhé.", ex2: "The pharmacy is on the left side of the street.", ex2Vn: "Hiệu thuốc nằm ở phía bên tay trái của con đường.", syn: [], ant: ["right"] },
    { word: "right", phonetic: "/raɪt/", def: "On, towards, or relating to the side of a human body or of a thing which is to the east when facing north.", defVn: "bên phải, rẽ phải", pos: "adverb", ex1: "Turn right immediately after passing the central hospital.", ex1Vn: "Rẽ phải ngay sau khi đi qua bệnh viện trung tâm nhé.", ex2: "The bus station is located on your right hand side.", ex2Vn: "Trạm xe buýt nằm ngay phía bên tay phải của bạn.", syn: [], ant: ["left"] },
    { word: "ahead", phonetic: "/əˈhed/", def: "Further forward in space or time.", defVn: "phía trước, thẳng phía trước", pos: "adverb", ex1: "You will spot the entrance gate about one hundred meters ahead.", ex1Vn: "Bạn sẽ nhìn thấy cổng vào ở khoảng một trăm mét phía trước.", ex2: "Plan carefully for the busy semester ahead.", ex2Vn: "Hãy lên kế hoạch cẩn thận cho học kỳ bận rộn phía trước nhé.", syn: ["forward", "frontward"], ant: ["behind"] },
    { word: "behind", phonetic: "/bɪˈhaɪnd/", def: "At or to the back of someone or something.", defVn: "phía sau, đằng sau", pos: "preposition", ex1: "The car parking lot is situated directly behind the building.", ex1Vn: "Bãi đỗ xe ô tô nằm ngay phía sau tòa nhà.", ex2: "Don't leave any personal belongings behind when getting off the bus.", ex2Vn: "Đừng để quên bất kỳ đồ đạc cá nhân nào lại phía sau khi xuống xe buýt nhé.", syn: ["rearward", "back"], ant: ["ahead", "front"] },
    { word: "opposite", phonetic: "/ˈɑːpəzɪt/", def: "Situated on the other or further side when seen from a specified point.", defVn: "đối diện, đối mặt", pos: "preposition", ex1: "The city library is right opposite the leafy public park.", ex1Vn: "Thư viện thành phố nằm ngay đối diện với công viên công cộng rợp bóng cây.", ex2: "They sat opposite each other at the round dining table.", ex2Vn: "Họ ngồi đối diện nhau tại bàn ăn tròn.", syn: ["facing", "across from"], ant: ["adjacent"] }
  ],

  // Theme 15: Weather & Nature (10 extra)
  t_basic_weather_nature: [
    { word: "drizzle", phonetic: "/ˈdrɪzl/", def: "Light rain falling in very fine drops.", defVn: "mưa phùn, mưa bụi nhẹ hạt", pos: "noun", ex1: "A gentle spring drizzle settled over the peach orchards.", ex1Vn: "Cơn mưa phùn mùa xuân dịu dàng buông xuống trên những vườn đào.", ex2: "Take an umbrella even if it's only a light drizzle.", ex2Vn: "Hãy mang theo ô dù ngay cả khi trời chỉ có mưa phùn nhẹ hạt nhé.", syn: ["mist", "light shower"], ant: ["downpour"] },
    { word: "rainbow", phonetic: "/ˈreɪnboʊ/", def: "An arch of colors formed in the sky in certain circumstances, caused by the refraction and dispersion of the sun's light by rain.", defVn: "cầu vồng (bảy sắc rực rỡ)", pos: "noun", ex1: "A brilliant double rainbow stretched across the mountain valley after the rain.", ex1Vn: "Một chiếc cầu vồng đôi rực rỡ vắt ngang qua thung lũng núi sau cơn mưa.", ex2: "The seven vibrant colors of the rainbow inspired her painting.", ex2Vn: "Bảy sắc màu rực rỡ của cầu vồng đã truyền cảm hứng cho bức tranh của cô.", syn: ["arc"], ant: [] },
    { word: "fog", phonetic: "/fɔːɡ/", def: "A thick cloud of tiny water droplets suspended in the atmosphere at or near the earth's surface.", defVn: "sương mù dày đặc", pos: "noun", ex1: "Dense morning fog covered the pine forests in Dalat.", ex1Vn: "Sương mù dày đặc buổi sáng bao phủ những cánh rừng thông ở Đà Lạt.", ex2: "Drivers must switch on fog lights when visibility is low.", ex2Vn: "Người lái xe phải bật đèn sương mù khi tầm nhìn bị hạn chế.", syn: ["mist", "haze"], ant: ["clarity"] },
    { word: "breeze", phonetic: "/briːz/", def: "A gentle wind.", defVn: "làn gió nhẹ, ngọn gió thoảng", pos: "noun", ex1: "A refreshing ocean breeze cooled the warm sandy beach.", ex1Vn: "Làn gió biển mát lành xua tan cái nóng trên bãi cát ấm áp.", ex2: "Windchimes tinkle softly in the evening breeze.", ex2Vn: "Chuông gió leng keng êm ái theo làn gió thoảng buổi chiều tà.", syn: ["draft", "whisper"], ant: ["gale", "tempest"] },
    { word: "frost", phonetic: "/frɔːst/", def: "A deposit of small white ice crystals formed on the ground or other surfaces.", defVn: "sương giá, băng tuyết đọng", pos: "noun", ex1: "Delicate white frost coated the winter window panes.", ex1Vn: "Lớp sương giá trắng muốt tinh xảo bao phủ các ô cửa sổ mùa đông.", ex2: "Winter morning frost glistened on the grass.", ex2Vn: "Sương giá sáng mùa đông lấp lánh trên từng ngọn cỏ.", syn: ["ice crystals"], ant: ["thaw"] },
    { word: "dew", phonetic: "/duː/", def: "Tiny drops of water that form on cool surfaces at night, when atmospheric vapor condenses.", defVn: "giọt sương mai đọng", pos: "noun", ex1: "Sparkling morning dew glistened on the fresh rose petals.", ex1Vn: "Những giọt sương mai lấp lánh đọng trên các cánh hoa hồng tươi.", ex2: "Early birds drink fresh dew from leaf tips.", ex2Vn: "Những chú chim dậy sớm uống những giọt sương tinh khiết từ đầu ngọn lá.", syn: ["droplets"], ant: [] },
    { word: "meadow", phonetic: "/ˈmedoʊ/", def: "A piece of grassland, especially one used for hay or grazing.", defVn: "đồng cỏ xanh tươi, trảng cỏ", pos: "noun", ex1: "Wildflowers bloomed in purple and yellow across the sunny meadow.", ex1Vn: "Hoa dại nở rộ sắc tím và vàng khắp đồng cỏ ngập tràn ánh nắng.", ex2: "Cattle grazed peacefully in the lush alpine meadow.", ex2Vn: "Đàn gia súc gặm cỏ thanh bình trên đồng cỏ xanh tươi trên núi cao.", syn: ["pasture", "grassland"], ant: [] },
    { word: "waterfall", phonetic: "/ˈwɔːtərfɔːl/", def: "A cascade of water falling from a height, formed when a river or stream flows over a precipice.", defVn: "thác nước (hùng vĩ)", pos: "noun", ex1: "Ban Gioc waterfall is one of the most stunning natural wonders in Vietnam.", ex1Vn: "Thác Bản Giốc là một trong những kỳ quan thiên nhiên ngoạn mục nhất Việt Nam.", ex2: "Cool mist rose from the roaring jungle waterfall.", ex2Vn: "Làn sương mát lành bốc lên từ dòng thác nước ầm ào giữa rừng sâu.", syn: ["cascade", "cataract"], ant: [] },
    { word: "riverbank", phonetic: "/ˈrɪvərbæŋk/", def: "The bank of a river.", defVn: "bờ sông, bãi bồi ven sông", pos: "noun", ex1: "Children sat fishing and chatting along the grassy riverbank.", ex1Vn: "Lũ trẻ ngồi câu cá và trò chuyện dọc theo bờ sông đầy cỏ xanh.", ex2: "Willows dip their branches gracefully into the riverbank waters.", ex2Vn: "Những rặng liễu rủ cành duyên dáng xuống làn nước ven bờ sông.", syn: ["riverside"], ant: [] },
    { word: "peak", phonetic: "/piːk/", def: "The pointed top of a mountain.", defVn: "đỉnh núi, đỉnh chóp cao nhất", pos: "noun", ex1: "Fansipan is celebrated as the highest mountain peak in Indochina.", ex1Vn: "Fansipan được tôn vinh là đỉnh núi cao nhất Đông Dương.", ex2: "The snow-capped mountain peak glowed under morning sunlight.", ex2Vn: "Đỉnh núi phủ đầy tuyết trắng tỏa sáng rực rỡ dưới ánh nắng sớm ban mai.", syn: ["summit", "crest"], ant: ["base", "valley"] }
  ]
};
