const prev50 = require('./expansion_pack_46_60.js');

module.exports = {
  ...prev50,

  // Theme 51: Light & Visual Effects (10 extra)
  t_basic_light_visual: [
    { word: "shimmer", phonetic: "/ˈʃɪmər/", def: "Shine with a soft, slightly wavering light.", defVn: "lấp lánh lung linh, tỏa ánh sáng dịu nhẹ", pos: "verb", ex1: "Moonlight made the calm sea surface shimmer like liquid silver.", ex1Vn: "Ánh trăng làm cho mặt biển tĩnh lặng lấp lánh lung linh như một dải bạc lỏng.", ex2: "Her sequined evening dress shimmers under the stage spotlights.", ex2Vn: "Chiếc váy dạ hội đính kim sa của cô ấy lấp lánh rực rỡ dưới ánh đèn sân khấu.", syn: ["glisten", "glimmer", "twinkle"], ant: [] },
    { word: "glisten", phonetic: "/ˈɡlɪsn/", def: "Shine with a sparkling light, especially because of a wet or oily surface.", defVn: "long lanh, lấp lánh giọt sương / nước", pos: "verb", ex1: "Morning dew drops glisten on fresh green grass blades like tiny diamonds.", ex1Vn: "Những giọt sương sớm long lanh trên những ngọn cỏ xanh non như những viên kim cương tí hon.", ex2: "His forehead glistened with sweat after the energetic football match.", ex2Vn: "Trán anh ấy lấm tấm mồ hôi long lanh sau trận đấu bóng đá đầy sôi nổi.", syn: ["sparkle", "shine", "gleam"], ant: [] },
    { word: "gleam", phonetic: "/ɡliːm/", def: "Shine brightly, especially with reflected light.", defVn: "sáng bóng loáng, ánh lên vẻ sạch sẽ", pos: "verb", ex1: "The freshly polished wooden dining table gleamed in the afternoon sunlight.", ex1Vn: "Chiếc bàn ăn bằng gỗ vừa được đánh bóng sáng loáng dưới ánh nắng buổi chiều.", ex2: "A triumphant smile gleamed in her eyes when she solved the riddle.", ex2Vn: "Một nụ cười đắc thắng ánh lên trong đôi mắt cô ấy khi giải được câu đố.", syn: ["shine", "glint", "beam"], ant: ["dull"] },
    { word: "radiant", phonetic: "/ˈreɪdiənt/", def: "Sending out light; shining or glowing brightly.", defVn: "rạng rỡ, tỏa sáng rực rỡ", pos: "adj", ex1: "The radiant tropical sunrise bathed the ocean horizon in vibrant amber and violet tones.", ex1Vn: "Bình minh nhiệt đới rạng rỡ bao phủ đường chân trời đại dương trong những sắc hổ phách và tím rực rỡ.", ex2: "The bride looked breathtakingly radiant in her handmade lace gown.", ex2Vn: "Cô dâu trông rạng ngời lộng lẫy trong chiếc váy ren thủ công tinh xảo.", syn: ["luminous", "brilliant", "glowing"], ant: ["dim", "gloomy"] },
    { word: "luminous", phonetic: "/ˈluːmɪnəs/", def: "Full of or shedding light; bright or shining, especially in the dark.", defVn: "phát sáng trong đêm, dạ quang", pos: "adj", ex1: "Luminous watch hands allow you to read the precise time even in pitch darkness.", ex1Vn: "Kim đồng hồ phát quang dạ quang cho phép bạn xem giờ chính xác ngay cả trong bóng tối đen như mực.", ex2: "The jellyfish floated like a luminous pulsating lantern through deep waters.", ex2Vn: "Chú sứa biển trôi bồng bềnh như một chiếc đèn lồng dạ quang nhấp nháy qua làn nước sâu.", syn: ["glowing", "phosphorescent"], ant: ["dark"] },
    { word: "silhouette", phonetic: "/ˌsɪluˈet/", def: "The dark shape and outline of someone or something visible against a lighter background.", defVn: "hình bóng đen tương phản trên nền sáng (silhouette)", pos: "noun", ex1: "The majestic silhouette of the ancient temple stood out against the golden sunset sky.", ex1Vn: "Hình bóng đen uy nghi của ngôi đền cổ nổi bật trên nền trời hoàng hôn rực rỡ sắc vàng.", ex2: "Palm trees form iconic tropical silhouettes along coastal beaches.", ex2Vn: "Những rặng dừa tạo nên những bóng hình nhiệt đới biểu tượng dọc theo bờ biển.", syn: ["outline", "shadow", "profile"], ant: [] },
    { word: "dim", phonetic: "/dɪm/", def: "Not shining brightly or clearly; low light.", defVn: "mờ ảo, ánh sáng le lói", pos: "adj", ex1: "We enjoyed a cozy candlelit dinner in the dim, romantic atmosphere of the bistro.", ex1Vn: "Chúng tôi tận hưởng bữa tối ấm cúng dưới ánh nến trong không gian mờ ảo lãng mạn của quán ăn nhỏ.", ex2: "Dim lighting in the bedroom signals the brain to prepare for restful sleep.", ex2Vn: "Ánh sáng dịu mờ trong phòng ngủ báo hiệu cho não bộ chuẩn bị cho giấc ngủ an lành.", syn: ["faint", "subdued", "dull"], ant: ["bright", "vivid"] },
    { word: "opaque", phonetic: "/oʊˈpeɪk/", def: "Not able to be seen through; not transparent.", defVn: "mờ đục, không nhìn xuyên qua được", pos: "adj", ex1: "The bathroom shower stall is made of frosted opaque glass for total privacy.", ex1Vn: "Vách tắm đứng trong phòng tắm được làm bằng kính mờ đục để đảm bảo sự riêng tư tuyệt đối.", ex2: "Thick storm clouds formed an opaque gray curtain across the entire mountain range.", ex2Vn: "Những đám mây bão dày đặc tạo thành một bức rèm màu xám đục ngầu che kín cả dãy núi.", syn: ["nontransparent", "cloudy"], ant: ["transparent", "clear"] },
    { word: "translucent", phonetic: "/trænzˈluːsnt/", def: "Allowing light, but not detailed shapes, to pass through; semi-transparent.", defVn: "bán trong suốt (cho ánh sáng xuyên qua mờ mờ)", pos: "adj", ex1: "Translucent white curtains soften harsh direct sunlight into a gentle warm glow.", ex1Vn: "Rèm cửa màu trắng bán trong suốt làm dịu ánh nắng chói chang trực tiếp thành một vầng sáng ấm áp nhẹ nhàng.", ex2: "Thin rice paper wrappers become translucent when dipped in warm water.", ex2Vn: "Bánh tráng mỏng trở nên trong mờ khi được nhúng vào nước ấm.", syn: ["semi-transparent", "sheer"], ant: ["opaque"] },
    { word: "sparkle", phonetic: "/ˈspɑːrkl/", def: "Shine with a series of small flashes of light.", defVn: "lấp lánh ánh kim, lấp lánh sao", pos: "verb", ex1: "Clean turquoise ocean waves sparkle dazzlingly under the midday sun.", ex1Vn: "Những con sóng biển màu ngọc lam trong vắt lấp lánh rực rỡ dưới ánh nắng ban trưa.", ex2: "Holiday lights sparkle along downtown avenues during Christmas week.", ex2Vn: "Đèn trang trí lễ hội lấp lánh rực rỡ dọc các đại lộ trung tâm thành phố trong tuần lễ Giáng sinh.", syn: ["glitter", "twinkle", "flash"], ant: [] }
  ],

  // Theme 52: Body Movements & Gestures (10 extra)
  t_basic_body_movements: [
    { word: "nod", phonetic: "/nɑːd/", def: "Lower and raise one's head slightly and briefly, especially in greeting, assent, or understanding.", defVn: "gật đầu (đồng ý, chào hỏi, hiểu ý)", pos: "verb", ex1: "He nodded in polite agreement when the team proposed the project timeline.", ex1Vn: "Anh ấy đã gật đầu đồng thuận lịch sự khi nhóm đề xuất tiến độ dự án.", ex2: "A simple respectful nod acknowledges someone across a busy room.", ex2Vn: "Một cái gật đầu tôn trọng đơn giản là đủ để chào hỏi một người ở phía bên kia căn phòng đông đúc.", syn: ["bow", "acknowledge", "signal"], ant: ["shake head"] },
    { word: "shrug", phonetic: "/ʃrʌɡ/", def: "Raise one's shoulders slightly and momentarily to express doubt, ignorance, or indifference.", defVn: "nhún vai (thể hiện không biết hoặc không bận tâm)", pos: "verb", ex1: "When asked about the missing keys, he could only shrug helplessly.", ex1Vn: "Khi được hỏi về chùm chìa khóa bị thất lạc, anh ấy chỉ biết nhún vai bất lực.", ex2: "She gave a casual shrug and decided not to worry about minor gossip.", ex2Vn: "Cô ấy nhún vai thản nhiên và quyết định không bận tâm đến những lời đàm tiếu vặt vãnh.", syn: ["dismiss", "disclaim"], ant: [] },
    { word: "blink", phonetic: "/blɪŋk/", def: "Shut and open the eyes quickly.", defVn: "chớp mắt, nháy mắt", pos: "verb", ex1: "Remember to blink frequently when working long hours in front of computer monitors.", ex1Vn: "Hãy nhớ chớp mắt thường xuyên khi làm việc nhiều giờ trước màn hình máy tính nhé.", ex2: "The bright flash of the camera caused everyone to blink simultaneously.", ex2Vn: "Ánh đèn flash sáng chói của máy ảnh đã khiến mọi người đồng loạt chớp mắt.", syn: ["wink", "flutter"], ant: ["stare"] },
    { word: "wink", phonetic: "/wɪŋk/", def: "Close and open one eye quickly, typically as a private signal of affection or humor.", defVn: "nháy một bên mắt (tinh nghịch, ra hiệu)", pos: "verb", ex1: "He gave a playful wink to let his friend know it was just a harmless joke.", ex1Vn: "Anh ấy đã nháy mắt tinh nghịch để cho bạn mình biết đó chỉ là một trò đùa vô hại.", ex2: "Grandpa winked warmly at the children before handing out treats.", ex2Vn: "Ông nội nháy mắt ấm áp với lũ trẻ trước khi phát bánh kẹo.", syn: ["blink", "signal"], ant: [] },
    { word: "stretch", phonetic: "/stretʃ/", def: "Straighten or extend one's body or part of one's body to its full length.", defVn: "vươn vai, giãn cơ thể", pos: "verb", ex1: "Stretch your arms and legs gently every morning to awaken stiff muscles.", ex1Vn: "Hãy vươn vai và duỗi nhẹ tay chân vào mỗi buổi sáng để đánh thức những khối cơ đang uể oải nhé.", ex2: "Yoga poses stretch the spine, improving flexibility and posture.", ex2Vn: "Các tư thế yoga giúp kéo giãn cột sống, cải thiện độ dẻo dai và vóc dáng.", syn: ["extend", "elongate", "reach"], ant: ["contract"] },
    { word: "crouch", phonetic: "/kraʊtʃ/", def: "Adopt a position where the knees are bent and the upper body is brought forward and down.", defVn: "ngồi xổm, khom lưng nép mình", pos: "verb", ex1: "The wildlife photographer crouched quietly behind tall shrubs to snap the deer.", ex1Vn: "Nhiếp ảnh gia thiên nhiên hoang dã khom mình nép nhẹ sau những bụi cây cao để chụp chú hươu.", ex2: "Crouch down low when passing through the cave entrance.", ex2Vn: "Hãy khom người cúi thấp xuống khi đi qua cửa hang động nhé.", syn: ["squat", "hunker", "stoop"], ant: ["stand"] },
    { word: "leap", phonetic: "/liːp/", def: "Jump or spring a long way, to a great height, or with great force.", defVn: "nhảy vọt lên, phóng mình qua", pos: "verb", ex1: "The athletic dancer leaped gracefully across the stage in a breathtaking arc.", ex1Vn: "Vũ công thể thao đã phóng mình nhảy vọt duyên dáng qua sân khấu theo một đường cong ngoạn mục.", ex2: "Dolphins leap high out of ocean waves to communicate with the pod.", ex2Vn: "Cá heo nhảy vọt lên cao khỏi ngọn sóng biển để giao tiếp với cả đàn.", syn: ["jump", "bound", "spring"], ant: [] },
    { word: "crawl", phonetic: "/krɔːl/", def: "Move forward on the hands and knees or by dragging the body close to the ground.", defVn: "bò lê, trườn trên sàn nhà", pos: "verb", ex1: "The seven-month-old baby learned to crawl swiftly across the soft play mat.", ex1Vn: "Em bé bảy tháng tuổi đã biết bò thoăn thoắt qua tấm thảm chơi mềm mại.", ex2: "Spelunkers must crawl through narrow underground limestone tunnels.", ex2Vn: "Những nhà thám hiểm hang động phải bò trườn qua các đường hầm đá vôi hẹp dưới lòng đất.", syn: ["creep", "inch", "slither"], ant: ["run", "walk"] },
    { word: "tiptoe", phonetic: "/ˈtɪptoʊ/", def: "Walk quietly and carefully with one's heels raised and one's weight on the balls of the feet.", defVn: "đi nhón chân, bước nhẹ rón rén", pos: "verb", ex1: "She tiptoed quietly into the nursery so she wouldn't wake the sleeping infant.", ex1Vn: "Cô ấy đã rón rén nhón chân bước nhẹ vào phòng em bé để không làm thức giấc bé đang ngủ say.", ex2: "We tiptoed down the stairs early in the morning to prepare a surprise breakfast.", ex2Vn: "Chúng tôi nhón chân bước xuống cầu thang vào sáng sớm để chuẩn bị bữa sáng bất ngờ.", syn: ["creep", "sneak"], ant: ["stomp"] },
    { word: "stumble", phonetic: "/ˈstʌmbl/", def: "Trip or momentarily lose one's balance; almost fall.", defVn: "vấp ngã, sảy chân suýt té", pos: "verb", ex1: "Watch your step on the rugged mountain trail so you don't stumble over exposed tree roots.", ex1Vn: "Hãy chú ý bước chân trên con đường mòn gồ ghề để không bị vấp vào những chiếc rễ cây trồi lên nhé.", ex2: "He caught his balance quickly after a minor stumble on the curb.", ex2Vn: "Anh ấy đã nhanh chóng lấy lại thăng bằng sau một cú sảy chân nhẹ ở mép vỉa hè.", syn: ["trip", "falter", "lurch"], ant: [] }
  ],

  // Theme 53: Convenience Services & Utilities (10 extra)
  t_basic_convenience_services: [
    { word: "courier", phonetic: "/ˈkʊriər/", def: "A company or employee that transports and delivers packages and documents.", defVn: "nhân viên giao hàng chuyển phát nhanh", pos: "noun", ex1: "The express courier delivered the signed legal documents within two business hours.", ex1Vn: "Nhân viên chuyển phát nhanh đã giao các tài liệu pháp lý có chữ ký trong vòng hai giờ làm việc.", ex2: "Track your parcel in real-time on the international courier company portal.", ex2Vn: "Theo dõi bưu kiện của bạn theo thời gian thực trên cổng thông tin của công ty chuyển phát nhanh quốc tế.", syn: ["delivery person", "messenger"], ant: [] },
    { word: "laundromat", phonetic: "/ˈlɔːndrəmæt/", def: "An establishment with coin-operated or card-operated washing machines and dryers for public use.", defVn: "tiệm giặt ủi tự động (giặt sấy)", pos: "noun", ex1: "Students do their weekly laundry conveniently at the 24-hour self-service laundromat.", ex1Vn: "Sinh viên giặt giũ đồ hàng tuần vô cùng tiện lợi tại tiệm giặt ủi tự động tự phục vụ 24 giờ.", ex2: "Modern laundromats offer high-efficiency tumble dryers and free Wi-Fi.", ex2Vn: "Các tiệm giặt ủi hiện đại trang bị máy sấy quần áo công suất cao và Wi-Fi miễn phí.", syn: ["laundrette", "washhouse"], ant: [] },
    { word: "dry cleaner", phonetic: "/ˈdraɪ kliːnər/", def: "A store or business where clothing and textiles are cleaned with chemical solvents rather than water.", defVn: "tiệm giặt khô là hơi cao cấp", pos: "noun", ex1: "Take your tailored wool suits and silk blouses to a professional dry cleaner.", ex1Vn: "Hãy mang những bộ vest dạ may đo và áo sơ mi lụa đến tiệm giặt khô chuyên nghiệp nhé.", ex2: "The dry cleaner expertly pressed the formal tuxedo for the gala event.", ex2Vn: "Tiệm giặt là đã ủi phẳng phiu bộ lễ phục dạ tiệc một cách vô cùng chuyên nghiệp.", syn: ["cleaner"], ant: [] },
    { word: "locksmith", phonetic: "/ˈlɑːksmɪθ/", def: "A person who makes and repairs locks and keys.", defVn: "thợ sửa khóa, mở khóa khẩn cấp", pos: "noun", ex1: "When I accidentally locked my keys inside the apartment, the 24/7 locksmith arrived in ten minutes.", ex1Vn: "Khi tôi vô tình để quên chìa khóa trong căn hộ, người thợ sửa khóa trực 24/7 đã có mặt chỉ sau mười phút.", ex2: "The skilled locksmith duplicated three spare keys for our new front door.", ex2Vn: "Người thợ khóa lành nghề đã cắt thêm ba chiếc chìa khóa dự phòng cho cửa chính mới của chúng tôi.", syn: ["key maker"], ant: [] },
    { word: "plumber", phonetic: "/ˈplʌmər/", def: "A person who fits and repairs the pipes, fittings, and other apparatus of water supply, sanitation, or heating systems.", defVn: "thợ sửa ống nước", pos: "noun", ex1: "Call a licensed professional plumber immediately to repair the burst kitchen pipe.", ex1Vn: "Hãy gọi thợ sửa ống nước chuyên nghiệp có chứng chỉ ngay lập tức để sửa đường ống bếp bị vỡ nhé.", ex2: "The plumber unclogged the bathroom drainage in twenty minutes.", ex2Vn: "Người thợ sửa ống nước đã thông tắc đường thoát nước nhà tắm trong hai mươi phút.", syn: ["pipefitter"], ant: [] },
    { word: "electrician", phonetic: "/ɪˌlekˈtrɪʃn/", def: "A person who installs and maintains electrical equipment.", defVn: "thợ điện dân dụng và công nghiệp", pos: "noun", ex1: "A certified electrician safely rewired our home's circuit breaker panel.", ex1Vn: "Một người thợ điện có chứng chỉ đã đi lại dây an toàn cho bảng cầu dao tổng của nhà chúng tôi.", ex2: "Never handle exposed high-voltage wiring yourself; always consult a licensed electrician.", ex2Vn: "Đừng bao giờ tự ý đụng vào dây điện cao thế bị hở; hãy luôn nhờ thợ điện có chuyên môn nhé.", syn: ["electrical engineer"], ant: [] },
    { word: "mechanic", phonetic: "/məˈkænɪk/", def: "A person who repairs and maintains machinery, especially motor vehicles.", defVn: "thợ sửa xe cơ giới, thợ máy ô tô/xe máy", pos: "noun", ex1: "The trustworthy auto mechanic replaced the worn brake pads and performed an oil change.", ex1Vn: "Người thợ sửa xe ô tô đáng tin cậy đã thay má phanh bị mòn và tiến hành thay dầu máy.", ex2: "Experienced motorbike mechanics in Hanoi can fix roadside flat tires in minutes.", ex2Vn: "Những người thợ sửa xe máy giàu kinh nghiệm ở Hà Nội có thể vá lốp xe bị thủng dọc đường chỉ trong vài phút.", syn: ["technician", "repairman"], ant: [] },
    { word: "optician", phonetic: "/ɑːpˈtɪʃn/", def: "A person qualified to prescribe and dispense eyeglasses and contact lenses.", defVn: "chuyên viên đo kính mắt, bác sĩ khúc xạ", pos: "noun", ex1: "The optician measured my eye prescription accurately and fitted anti-glare lenses.", ex1Vn: "Chuyên viên đo kính mắt đã kiểm tra độ cận của tôi chuẩn xác và lắp tròng kính chống chói.", ex2: "Visit an optician once a year to keep your eye vision prescription up to date.", ex2Vn: "Hãy đến gặp chuyên viên đo mắt mỗi năm một lần để cập nhật số đo thị lực của bạn nhé.", syn: ["optometrist"], ant: [] },
    { word: "teller", phonetic: "/ˈtelər/", def: "A person employed in a bank to receive and pay out money.", defVn: "giao dịch viên ngân hàng", pos: "noun", ex1: "The polite bank teller assisted us with exchanging foreign currencies at favorable rates.", ex1Vn: "Bạn giao dịch viên ngân hàng lịch sự đã hỗ trợ chúng tôi đổi ngoại tệ với tỷ giá ưu đãi.", ex2: "Automated teller machines perform transactions seamlessly alongside human tellers.", ex2Vn: "Máy rút tiền tự động thực hiện các giao dịch trơn tru song song với các giao dịch viên ngân hàng.", syn: ["bank clerk", "cashier"], ant: [] },
    { word: "tailor", phonetic: "/ˈteɪlər/", def: "A person whose occupation is making, fitting, or altering garments.", defVn: "thợ may trang phục (may đo, chỉnh sửa)", pos: "noun", ex1: "The master tailor altered the suit trousers to achieve a perfect, flattering fit.", ex1Vn: "Bác thợ may bậc thầy đã chỉnh sửa chiếc quần tây để đạt được độ vừa vặn hoàn hảo, tôn dáng.", ex2: "Custom tailors in Hoi An can craft bespoke shirts and suits within twenty-four hours.", ex2Vn: "Những người thợ may thủ công ở Hội An có thể may đo sơ mi và vest theo yêu cầu chỉ trong hai mươi bốn giờ.", syn: ["dressmaker", "seamstress", "clothier"], ant: [] }
  ],

  // Theme 54: Airport & Flight (10 extra)
  t_basic_airport_flight: [
    { word: "terminal", phonetic: "/ˈtɜːrmɪnl/", def: "A building at an airport where passengers transfer between ground transportation and the facilities that allow them to board and disembark from aircraft.", defVn: "nhà ga sân bay (quốc tế/quốc nội)", pos: "noun", ex1: "International flights depart from Terminal Two, while domestic flights use Terminal One.", ex1Vn: "Các chuyến bay quốc tế khởi hành từ Nhà ga số 2, trong khi các chuyến bay nội địa sử dụng Nhà ga số 1.", ex2: "A free automated shuttle train connects airport terminals seamlessly.", ex2Vn: "Một chuyến tàu điện đưa đón tự động miễn phí kết nối giữa các nhà ga sân bay vô cùng thông suốt.", syn: ["airport concourse"], ant: [] },
    { word: "runway", phonetic: "/ˈrʌnweɪ/", def: "A leveled strip of smooth ground, usually paved, on which aircraft take off and land.", defVn: "đường băng sân bay (cho máy bay cất/hạ cánh)", pos: "noun", ex1: "The airplane accelerated powerfully down the asphalt runway before lifting smoothly into the sky.", ex1Vn: "Chiếc máy bay tăng tốc mạnh mẽ trên đường băng trải nhựa trước khi nhấc mình nhẹ nhàng bay vút lên bầu trời.", ex2: "Runway lights guide pilots safely during night landings and dense fog.", ex2Vn: "Hệ thống đèn đường băng dẫn hướng an toàn cho các phi công trong những chuyến hạ cánh ban đêm và sương mù dày.", syn: ["airstrip", "tarmac"], ant: [] },
    { word: "carousel", phonetic: "/ˌkærəˈsel/", def: "A continuous moving circular conveyor belt from which arriving passengers collect their luggage.", defVn: "băng chuyền lấy hành lý (ở sân bay)", pos: "noun", ex1: "Passengers gathered around luggage carousel number four to wait for their checked suitcases.", ex1Vn: "Các hành khách tập trung quanh băng chuyền hành lý số bốn để chờ những chiếc vali ký gửi của mình.", ex2: "Identify your suitcase quickly on the luggage carousel with a bright neon tag.", ex2Vn: "Nhận biết chiếc vali của bạn nhanh chóng trên băng chuyền hành lý bằng một chiếc thẻ đeo dạ quang sáng màu nhé.", syn: ["baggage claim belt"], ant: [] },
    { word: "customs", phonetic: "/ˈkʌstəmz/", def: "The official department that administers and collects the duties levied by a government on imported goods.", defVn: "hải quan sân bay, thủ tục thông quan", pos: "noun", ex1: "Declare any restricted agricultural items or large sums of cash at the airport customs desk.", ex1Vn: "Khai báo các mặt hàng nông sản hạn chế hoặc số tiền mặt lớn tại quầy hải quan sân bay nhé.", ex2: "Going through customs was fast and effortless thanks to electronic biometric gates.", ex2Vn: "Làm thủ tục hải quan diễn ra nhanh chóng và dễ dàng nhờ các cổng sinh trắc học điện tử.", syn: ["duty checkpoint", "border control"], ant: [] },
    { word: "immigration", phonetic: "/ˌɪmɪˈɡreɪʃn/", def: "The place at an airport or border where travelers' passports and visas are checked.", defVn: "quầy xuất nhập cảnh, kiểm tra hộ chiếu", pos: "noun", ex1: "Present your valid passport, tourist visa, and boarding pass to the immigration officer.", ex1Vn: "Xuất trình hộ chiếu còn hạn, thị thực du lịch và thẻ lên máy bay cho nhân viên xuất nhập cảnh nhé.", ex2: "Automated e-gates expedite immigration clearance for frequent international flyers.", ex2Vn: "Cổng tự động e-gate giúp làm thủ tục xuất nhập cảnh nhanh chóng cho những hành khách bay quốc tế thường xuyên.", syn: ["passport control"], ant: [] },
    { word: "layover", phonetic: "/ˈleɪoʊvər/", def: "A period of rest or waiting before a further stage in a journey.", defVn: "chuyến bay quá cảnh, thời gian chờ nối chuyến", pos: "noun", ex1: "We had a delightful four-hour layover at Singapore Changi Airport to explore the indoor waterfall.", ex1Vn: "Chúng tôi đã có bốn giờ quá cảnh thú vị tại Sân bay Changi Singapore để khám phá thác nước trong nhà.", ex2: "Book a flight with a short layover if you want to reach your final destination sooner.", ex2Vn: "Hãy đặt chuyến bay có thời gian nối chuyến ngắn nếu bạn muốn đến điểm đích cuối cùng sớm hơn nhé.", syn: ["stopover", "transit"], ant: ["direct flight"] },
    { word: "turbulence", phonetic: "/ˈtɜːrbjələns/", def: "Violent or unsteady movement of air or water, or of some other fluid.", defVn: "nhiễu động không khí, rung lắc máy bay", pos: "noun", ex1: "Please remain seated and fasten your seatbelt securely during unexpected flight turbulence.", ex1Vn: "Xin vui lòng ngồi yên tại chỗ và thắt chặt dây an toàn trong lúc máy bay gặp rung lắc do nhiễu động không khí bất ngờ.", ex2: "The airplane weathered brief clear-air turbulence without any safety hazard.", ex2Vn: "Chiếc máy bay đã vượt qua đợt nhiễu động không khí ngắn mà không gặp bất kỳ nguy cơ an toàn nào.", syn: ["bumpiness", "roughness"], ant: ["smooth flight"] },
    { word: "cockpit", phonetic: "/ˈkɑːkpɪt/", def: "A compartment for the pilot, and sometimes also the crew, in an aircraft or spacecraft.", defVn: "buồng lái máy bay (phi công)", pos: "noun", ex1: "The captain and first officer monitored flight telemetry systems inside the high-tech cockpit.", ex1Vn: "Cơ trưởng và cơ phó đã theo dõi các hệ thống đo đạc hành trình chuyến bay bên trong buồng lái công nghệ cao.", ex2: "Modern aircraft cockpits feature digital fly-by-wire glass instrumentation.", ex2Vn: "Buồng lái máy bay hiện đại được trang bị các thiết bị hiển thị điện tử kỹ thuật số tối tân.", syn: ["flight deck"], ant: [] },
    { word: "fuselage", phonetic: "/ˈfjuːsəlɑːʒ/", def: "The main body of an aircraft.", defVn: "thân máy bay (chứa hành khách và hàng hóa)", pos: "noun", ex1: "Lightweight carbon-fiber composite materials reinforce the wide-body airplane's fuselage.", ex1Vn: "Vật liệu composite sợi carbon siêu nhẹ giúp gia cố thân của những chiếc máy bay thân rộng.", ex2: "Airlines paint creative promotional artwork across the aircraft fuselage.", ex2Vn: "Các hãng hàng không vẽ những tác phẩm nghệ thuật quảng bá đầy sáng tạo trên khắp thân máy bay.", syn: ["aircraft body"], ant: [] },
    { word: "altitude", phonetic: "/ˈæltɪtuːd/", def: "The height of an object or point in relation to sea level or ground level.", defVn: "độ cao bay (so với mực nước biển)", pos: "noun", ex1: "The commercial jet reached its optimal cruising altitude of thirty-six thousand feet.", ex1Vn: "Chiếc máy bay phản lực thương mại đã đạt đến độ cao hành trình tối ưu là ba mươi sáu ngàn bộ.", ex2: "Cabin air pressure is carefully regulated at high flight altitudes for passenger comfort.", ex2Vn: "Áp suất không khí trong khoang máy bay được điều chỉnh cẩn thận ở độ cao bay lớn để đảm bảo sự thoải mái cho hành khách.", syn: ["elevation", "height"], ant: [] }
  ],

  // Theme 55: Hotel Stay & Hospitality (10 extra)
  t_basic_hotel_stay: [
    { word: "concierge", phonetic: "/koʊnˈsjerʒ/", def: "A hotel staff member whose job is to assist guests by booking tours, making reservations, etc.", defVn: "nhân viên hỗ trợ thông tin khách hàng (concierge)", pos: "noun", ex1: "The knowledgeable hotel concierge recommended hidden culinary gems and booked river cruise tickets for us.", ex1Vn: "Người nhân viên hỗ trợ thông tin am hiểu của khách sạn đã gợi ý những quán ăn ngon giấu kín và đặt vé du thuyền trên sông cho chúng tôi.", ex2: "Ask the concierge desk for complimentary local city maps and transit advice.", ex2Vn: "Hãy hỏi quầy concierge để nhận bản đồ thành phố miễn phí và những lời khuyên về phương tiện công cộng nhé.", syn: ["guest relations", "attendant"], ant: [] },
    { word: "bellhop", phonetic: "/ˈbelhɑːp/", def: "A person employed in a hotel to carry luggage, open doors, and do other errands.", defVn: "nhân viên xách hành lý khách sạn, bellboy", pos: "noun", ex1: "The courteous bellhop loaded our heavy suitcases onto a brass luggage trolley and guided us to our suite.", ex1Vn: "Người nhân viên xách hành lý lịch thiệp đã xếp những chiếc vali nặng của chúng tôi lên xe đẩy bằng đồng và dẫn chúng tôi về phòng hạng sang.", ex2: "It is customary to tip the hotel bellhop for their prompt and helpful assistance.", ex2Vn: "Theo thông lệ, người ta thường gửi tiền bồi dưỡng cho nhân viên xách hành lý vì sự hỗ trợ nhanh nhẹn và chu đáo của họ.", syn: ["porter", "bellboy"], ant: [] },
    { word: "housekeeping", phonetic: "/ˈhaʊskiːpɪŋ/", def: "The department or staff of a hotel responsible for cleaning and maintenance.", defVn: "bộ phận buồng phòng, dọn phòng khách sạn", pos: "noun", ex1: "Hotel housekeeping cleans rooms, replaces fresh plush towels, and replenishes bath amenities daily.", ex1Vn: "Bộ phận buồng phòng khách sạn dọn dẹp phòng, thay khăn tắm mới êm ái và bổ sung đồ dùng tắm hàng ngày.", ex2: "Hang the 'Do Not Disturb' sign on the door handle if you don't require housekeeping today.", ex2Vn: "Treo biển 'Xin đừng làm phiền' lên tay nắm cửa nếu bạn không cần dọn phòng hôm nay nhé.", syn: ["room service", "cleaning staff"], ant: [] },
    { word: "suite", phonetic: "/swiːt/", def: "A set of rooms designated for one person's or family's use or for a particular purpose.", defVn: "phòng suite cao cấp (có phòng khách riêng)", pos: "noun", ex1: "The presidential suite boasts panoramic ocean views, a private jacuzzi, and a spacious terrace.", ex1Vn: "Phòng tổng thống sở hữu tầm nhìn toàn cảnh ra đại dương, bồn sục jacuzzi riêng và ban công rộng thênh thang.", ex2: "Families appreciate booking a two-bedroom suite with a connected living area.", ex2Vn: "Các gia đình rất thích đặt phòng suite hai phòng ngủ có kèm khu vực sinh hoạt chung liên thông.", syn: ["apartment", "luxury room"], ant: ["single room"] },
    { word: "amenities", phonetic: "/əˈmenətiz/", def: "Desirable or useful features of a building, place, or hotel.", defVn: "tiện ích khách sạn (hồ bơi, spa, gym, minibar)", pos: "noun", ex1: "Resort amenities include an infinity swimming pool, tennis courts, a luxury spa, and a fitness center.", ex1Vn: "Các tiện ích của khu nghỉ dưỡng bao gồm hồ bơi vô cực, sân tennis, spa sang trọng và trung tâm thể hình.", ex2: "Complimentary bathroom amenities include organic soaps, shampoo, and bathrobes.", ex2Vn: "Các tiện ích phòng tắm miễn phí bao gồm xà phòng hữu cơ, dầu gội đầu và áo choàng tắm.", syn: ["facilities", "features", "perks"], ant: [] },
    { word: "valet", phonetic: "/væˈleɪ/", def: "A person employed to park cars for guests at a hotel or restaurant.", defVn: "nhân viên đỗ xe hộ, dịch vụ gửi xe valet", pos: "noun", ex1: "Hand your car keys to the hotel valet attendant at the covered entrance foyer.", ex1Vn: "Giao chìa khóa xe của bạn cho nhân viên đỗ xe hộ tại sảnh đón có mái che nhé.", ex2: "Complimentary valet parking is available for all registered hotel guests.", ex2Vn: "Dịch vụ đỗ xe hộ miễn phí luôn sẵn sàng phục vụ tất cả các khách lưu trú đã đăng ký tại khách sạn.", syn: ["parking attendant"], ant: [] },
    { word: "minibar", phonetic: "/ˈmɪnibɑːr/", def: "A small refrigerator in a hotel room, typically stocked with drinks and snacks for the guests.", defVn: "tủ lạnh mini trong phòng khách sạn", pos: "noun", ex1: "The hotel room minibar is stocked with chilled sparkling water, juices, and artisan chocolate.", ex1Vn: "Tủ lạnh mini trong phòng khách sạn luôn có sẵn nước khoáng có ga ướp lạnh, nước ép hoa quả và sô-cô-la thủ công.", ex2: "Check the minibar price list on the desk before enjoying refreshments.", ex2Vn: "Hãy kiểm tra bảng giá tủ lạnh mini trên bàn trước khi thưởng thức đồ ăn nhẹ nhé.", syn: ["mini-fridge"], ant: [] },
    { word: "deposit", phonetic: "/dɪˈpɑːzɪt/", def: "A sum of money paid as a first installment or security on the reservation.", defVn: "tiền đặt cọc phòng, tiền bảo chứng", pos: "noun", ex1: "The hotel holds a refundable security deposit on your credit card upon check-in.", ex1Vn: "Khách sạn sẽ tạm giữ một khoản tiền đặt cọc bảo đảm có thể hoàn lại trên thẻ tín dụng của bạn khi nhận phòng.", ex2: "The initial booking deposit will be deducted from your final checkout invoice.", ex2Vn: "Khoản tiền đặt cọc giữ chỗ ban đầu sẽ được khấu trừ vào hóa đơn thanh toán trả phòng cuối cùng của bạn.", syn: ["advance payment", "security"], ant: ["refund"] },
    { word: "vacancy", phonetic: "/ˈveɪkənsi/", def: "An unoccupied room in a hotel or guesthouse.", defVn: "phòng còn trống (chưa có khách thuê)", pos: "noun", ex1: "The glowing neon sign outside the coastal lodge read 'No Vacancy' during peak holiday weekend.", ex1Vn: "Tấm biển đèn neon sáng rực bên ngoài khu nhà nghỉ ven biển ghi 'Hết phòng' trong suốt dịp cuối tuần nghỉ lễ cao điểm.", ex2: "We called five boutique hotels to inquire about weekend room vacancies.", ex2Vn: "Chúng tôi đã gọi cho năm khách sạn boutique để hỏi về tình trạng phòng trống vào cuối tuần.", syn: ["available room"], ant: ["full house", "no vacancy"] },
    { word: "hospitality", phonetic: "/ˌhɑːspɪˈtæləti/", def: "The friendly and generous reception and entertainment of guests, visitors, or strangers.", defVn: "sự hiếu khách, ngành dịch vụ du lịch khách sạn", pos: "noun", ex1: "Vietnamese people are world-renowned for their genuine warmth and generous hospitality.", ex1Vn: "Người Việt Nam nổi tiếng khắp thế giới bởi sự ấm áp chân thành và lòng hiếu khách nồng hậu.", ex2: "She graduated with honors in international hospitality management.", ex2Vn: "Cô ấy đã tốt nghiệp loại xuất sắc chuyên ngành quản trị dịch vụ du lịch khách sạn quốc tế.", syn: ["warmth", "friendliness", "welcome"], ant: ["hostility", "coldness"] }
  ],

  // Theme 56: Street Food & Culture (10 extra)
  t_basic_street_food_culture: [
    { word: "delicacy", phonetic: "/ˈdelɪkəsi/", def: "Something delightful or pleasing, especially a choice food regarded as rare or expensive.", defVn: "món đặc sản thơm ngon, cao lương mỹ vị", pos: "noun", ex1: "Crispy grilled Vietnamese spring rolls are a beloved culinary delicacy across Southeast Asia.", ex1Vn: "Chả giò chiên giòn rụm của Việt Nam là món đặc sản ẩm thực được muôn người yêu thích khắp Đông Nam Á.", ex2: "Sampling regional street delicacies is the crowning highlight of travel.", ex2Vn: "Thưởng thức những món ăn đặc sản đường phố địa phương là điểm nhấn tuyệt vời nhất của chuyến du lịch.", syn: ["treat", "specialty", "tidbit"], ant: [] },
    { word: "crispiness", phonetic: "/ˈkrɪspinəs/", def: "The quality of being pleasantly firm, dry, and easily broken.", defVn: "độ giòn tan, sự giòn rụm của món ăn", pos: "noun", ex1: "The golden crispiness of the banh mi crust crackles delightfully with every bite.", ex1Vn: "Độ giòn rụm vàng ươm của lớp vỏ bánh mì phát ra tiếng vỡ giòn tan vui tai trong từng miếng cắn.", ex2: "Deep-fry the wontons at the right temperature to achieve lasting crispiness.", ex2Vn: "Chiên ngập dầu hoành thánh ở nhiệt độ thích hợp để đạt được độ giòn tan lâu dài nhé.", syn: ["crunchiness"], ant: ["sogginess"] },
    { word: "savory", phonetic: "/ˈseɪvəri/", def: "Belonging to the category that is salty or spicy rather than sweet.", defVn: "món mặn đậm đà, thơm bùi", pos: "adj", ex1: "Vietnamese broken rice served with grilled pork chop and savory steamed egg meatloaf is iconic.", ex1Vn: "Cơm tấm Việt Nam ăn kèm sườn nướng và chả trứng hấp mặn mà đậm đà là món ăn mang tính biểu tượng.", ex2: "Her savory pancakes are filled with plump shrimp and bean sprouts.", ex2Vn: "Những chiếc bánh xèo mặn mà của cô ấy chứa đầy tôm tươi mọng nước và giá đỗ giòn ngọt.", syn: ["flavorful", "salty", "piquant"], ant: ["sweet"] },
    { word: "succulent", phonetic: "/ˈsʌkjələnt/", def: "Tender, juicy, and tasty food.", defVn: "mọng nước, mềm ngọt (thịt/hải sản)", pos: "adj", ex1: "The skewered grilled pork meatballs were extraordinarily succulent and smoky.", ex1Vn: "Những xiên nem nướng thơm lừng cực kỳ mọng nước, mềm ngọt và đượm hương khói.", ex2: "Fresh oysters served with lime wedges taste succulent and briny.", ex2Vn: "Hàu tươi sống dùng kèm những lát chanh mọng nước có vị ngọt thanh bùi đậm đà hương biển.", syn: ["juicy", "tender", "moist"], ant: ["dry", "tough"] },
    { word: "aroma", phonetic: "/əˈroʊmə/", def: "A pleasant and distinctive smell.", defVn: "mùi thơm ngào ngạt nức mũi (của đồ ăn)", pos: "noun", ex1: "The rich aroma of simmering star anise and cinnamon draws hungry crowds to the pho stall.", ex1Vn: "Mùi thơm nức mũi của hoa hồi và quế đang sôi sùng sục thu hút thực khách đói bụng tấp nập kéo đến quán phở.", ex2: "Freshly roasted coffee beans fill the street with an invigorating aroma.", ex2Vn: "Những hạt cà phê rang tươi thơm lừng tràn ngập khắp con phố với hương thơm đánh thức mọi giác quan.", syn: ["fragrance", "scent", "perfume"], ant: ["stench", "odor"] },
    { word: "vendor", phonetic: "/ˈvendər/", def: "A person or company offering something for sale, especially a street trader.", defVn: "người bán hàng rong, người bán quán vỉa hè", pos: "noun", ex1: "The friendly street vendor serves steaming bowls of spicy beef noodle soup on tiny plastic stools.", ex1Vn: "Người bán hàng rong thân thiện phục vụ những tô bún bò bốc khói cay nồng trên những chiếc ghế nhựa nhỏ xinh.", ex2: "Street food vendors wake up before dawn to prepare fresh handmade ingredients.", ex2Vn: "Các cô chú bán hàng ăn vỉa hè luôn thức dậy trước lúc bình minh để chuẩn bị nguyên liệu thủ công tươi ngon.", syn: ["hawker", "peddler", "merchant"], ant: ["buyer", "customer"] },
    { word: "specialty", phonetic: "/ˈspeʃəlti/", def: "A product, especially a type of food, that a person or place is famous for.", defVn: "món đặc sản trứ danh, sở trường", pos: "noun", ex1: "Cao lau noodles with savory braised pork and crispy crackers are a famous Hoi An specialty.", ex1Vn: "Mì cao lầu ăn cùng thịt xá xíu đậm đà và bánh tráng giòn là món đặc sản trứ danh của Hội An.", ex2: "Every Vietnamese province boasts its own unique culinary specialty.", ex2Vn: "Mỗi tỉnh thành của Việt Nam đều tự hào sở hữu món đặc sản ẩm thực độc đáo của riêng mình.", syn: ["signature dish", "delicacy"], ant: [] },
    { word: "marinade", phonetic: "/ˌmærɪˈneɪd/", def: "A savory, usually acidic sauce in which meat, fish, or other food is soaked before cooking, in order to flavor or soften it.", defVn: "nước sốt ướp thịt cá (cho thấm gia vị)", pos: "noun", ex1: "A marinade of minced shallots, honey, lemongrass, and fish sauce makes barbecued ribs divine.", ex1Vn: "Nước sốt ướp gồm hành tím băm, mật ong, sả và nước mắm làm cho món sườn nướng trở nên ngon tuyệt đỉnh.", ex2: "Let the sliced beef soak in the savory garlic marinade for thirty minutes.", ex2Vn: "Hãy để thịt bò thái lát ngấm trong nước sốt ướp tỏi thơm ngon trong ba mươi phút nhé.", syn: ["seasoning sauce"], ant: [] },
    { word: "condiment", phonetic: "/ˈkɑːndɪmənt/", def: "A substance such as salt, mustard, or pickle that is used to add flavor to food.", defVn: "gia vị nêm kèm (ớt chưng, tương đen, tiêu)", pos: "noun", ex1: "Table condiments at Vietnamese noodle shops include homemade chili oil, pickled garlic, and fresh limes.", ex1Vn: "Gia vị nêm kèm trên bàn tại các quán ăn Việt Nam bao gồm sa tế ớt tự làm, tỏi ngâm giấm và chanh tươi.", ex2: "Add a spoonful of hoisin condiment to your bowl of pho broth.", ex2Vn: "Thêm một thìa tương đen vào tô nước dùng phở của bạn nhé.", syn: ["seasoning", "sauce", "relish"], ant: [] },
    { word: "skewer", phonetic: "/ˈskjuːər/", def: "A long piece of wood or metal used for holding pieces of food, typically meat, together during cooking.", defVn: "xiên que nướng thịt, que xiên", pos: "noun", ex1: "Charcoal-grilled pork skewers sizzling over open embers release an irresistible smoky fragrance.", ex1Vn: "Những que xiên thịt lợn nướng than hoa xèo xèo trên than hồng tỏa ra hương thơm khói ngào ngạt khó cưỡng.", ex2: "Soak wooden skewers in water before grilling to prevent them from scorching.", ex2Vn: "Ngâm các que xiên gỗ vào nước trước khi nướng để ngăn chúng không bị cháy xém nhé.", syn: ["spit", "pin"], ant: [] }
  ],

  // Theme 57: Life Stages & Milestones (10 extra)
  t_basic_life_stages: [
    { word: "infancy", phonetic: "/ˈɪnfənsi/", def: "The early stage of growth or development, typically from birth to age two.", defVn: "thời kỳ sơ sinh, lúc còn ẵm ngửa", pos: "noun", ex1: "During infancy, babies develop rapid motor coordination and emotional bonds with their parents.", ex1Vn: "Trong thời kỳ sơ sinh, các bé phát triển nhanh chóng khả năng phối hợp vận động và mối liên kết cảm xúc với cha mẹ.", ex2: "The mobile app industry was in its infancy two decades ago.", ex2Vn: "Ngành công nghiệp ứng dụng di động mới chỉ ở giai đoạn trứng nước cách đây hai thập kỷ.", syn: ["babyhood", "early childhood"], ant: ["adulthood", "old age"] },
    { word: "toddler", phonetic: "/ˈtɑːdlər/", def: "A young child who is just beginning to walk.", defVn: "trẻ chập chững biết đi (1-3 tuổi)", pos: "noun", ex1: "The energetic toddler took his first steady steps across the living room carpet.", ex1Vn: "Bé con chập chững biết đi đầy hiếu động đã bước những bước đi vững chãi đầu tiên trên thảm phòng khách.", ex2: "Toddlers explore the world around them through tactile play and curiosity.", ex2Vn: "Trẻ nhỏ khám phá thế giới xung quanh thông qua các trò chơi xúc giác và trí tò mò.", syn: ["little child"], ant: [] },
    { word: "adolescence", phonetic: "/ˌædəˈlesns/", def: "The period following the onset of puberty during which a young person develops from a child into an adult.", defVn: "tuổi thiếu niên, tuổi dậy thì", pos: "noun", ex1: "Adolescence is a transformative period of discovering personal identity and building independence.", ex1Vn: "Tuổi thiếu niên là giai đoạn chuyển mình để khám phá bản sắc cá nhân và xây dựng tính tự lập.", ex2: "Supportive parenting helps teenagers navigate the emotional turbulence of adolescence.", ex2Vn: "Sự đồng hành thấu hiểu của cha mẹ giúp các bạn trẻ vượt qua những xáo trộn cảm xúc của tuổi dậy thì.", syn: ["youth", "teens", "puberty"], ant: ["maturity"] },
    { word: "graduation", phonetic: "/ˌɡrædʒuˈeɪʃn/", def: "The receiving or conferring of an academic degree or diploma.", defVn: "lễ tốt nghiệp đại học / học đường", pos: "noun", ex1: "Proud parents cheered happily as university students tossed their caps in the air at graduation.", ex1Vn: "Các bậc cha mẹ tự hào reo hò hạnh phúc khi các tân cử nhân tung mũ lên không trung trong buổi lễ tốt nghiệp.", ex2: "Graduation marks both a proud milestone and the exciting start of professional life.", ex2Vn: "Tốt nghiệp đánh dấu cả một cột mốc đáng tự hào lẫn sự khởi đầu đầy hứng khởi của cuộc sống nghề nghiệp.", syn: ["commencement"], ant: [] },
    { word: "career", phonetic: "/kəˈrɪr/", def: "An occupation undertaken for a significant period of a person's life and with opportunities for progress.", defVn: "sự nghiệp, con đường công danh", pos: "noun", ex1: "She built a stellar career in software engineering through continuous self-learning and passion.", ex1Vn: "Cô ấy đã xây dựng một sự nghiệp rực rỡ trong ngành kỹ thuật phần mềm nhờ tinh thần tự học không ngừng và niềm đam mê.", ex2: "A fulfilling career aligns with your core values and brings genuine social impact.", ex2Vn: "Một sự nghiệp trọn vẹn sẽ đồng điệu với các giá trị cốt lõi của bạn và mang lại những tác động xã hội thiết thực.", syn: ["vocation", "profession", "calling"], ant: [] },
    { word: "marriage", phonetic: "/ˈmærɪdʒ/", def: "The legally or formally recognized union of two people as partners in a personal relationship.", defVn: "hôn nhân, cuộc sống gia đình vợ chồng", pos: "noun", ex1: "A strong, enduring marriage is built on mutual respect, patience, and transparent communication.", ex1Vn: "Một cuộc hôn nhân bền vững và lâu dài được xây dựng trên sự tôn trọng lẫn nhau, lòng kiên nhẫn và giao tiếp minh bạch.", ex2: "They celebrated their silver wedding anniversary marking twenty-five years of happy marriage.", ex2Vn: "Họ đã tổ chức kỷ niệm đám cưới bạc đánh dấu hai mươi lăm năm hôn nhân hạnh phúc.", syn: ["matrimony", "wedlock", "union"], ant: ["divorce"] },
    { word: "retirement", phonetic: "/rɪˈtaɪərmənt/", def: "The action or fact of leaving one's job and ceasing to work.", defVn: "nghỉ hưu, tuổi hưu trí an nhàn", pos: "noun", ex1: "During his peaceful retirement, he tends his organic bonsai garden and travels the world.", ex1Vn: "Trong những năm tháng nghỉ hưu an nhàn, ông chăm sóc vườn cây cảnh bonsai hữu cơ và đi du lịch vòng quanh thế giới.", ex2: "Start saving and investing early to ensure a comfortable, worry-free retirement.", ex2Vn: "Hãy bắt đầu tiết kiệm và đầu tư từ sớm để đảm bảo một cuộc sống hưu trí thoải mái, không âu lo nhé.", syn: ["pension", "superannuation"], ant: ["employment", "work"] },
    { word: "pension", phonetic: "/ˈpenʃn/", def: "A regular payment made during a person's retirement from an investment fund to which that person or their employer has contributed.", defVn: "lương hưu, tiền trợ cấp hưu trí", pos: "noun", ex1: "Senior citizens receive a monthly government pension to cover living and medical expenses.", ex1Vn: "Người cao tuổi nhận lương hưu hàng tháng của nhà nước để trang trải chi phí sinh hoạt và y tế.", ex2: "A well-managed private pension fund yields reliable retirement dividends.", ex2Vn: "Một quỹ lương hưu tư nhân được quản lý tốt sẽ mang lại nguồn lợi nhuận ổn định khi về già.", syn: ["retirement benefit", "annuity"], ant: [] },
    { word: "elderly", phonetic: "/ˈeldərli/", def: "Of a person who is old or past middle age.", defVn: "người cao tuổi, các bậc cao niên", pos: "adj", ex1: "Always offer your bus seat politely to elderly passengers or pregnant women.", ex1Vn: "Hãy luôn luôn lịch sự nhường ghế xe buýt cho các hành khách cao tuổi hoặc phụ nữ mang thai nhé.", ex2: "Community programs organize weekly gentle exercise sessions for the elderly.", ex2Vn: "Các chương trình cộng đồng tổ chức những buổi tập thể dục nhẹ nhàng hàng tuần dành cho người cao tuổi.", syn: ["aged", "senior", "older"], ant: ["young", "youthful"] },
    { word: "longevity", phonetic: "/lɔːnˈdʒevəti/", def: "Long life; long existence or service.", defVn: "sự trường thọ, tuổi thọ cao", pos: "noun", ex1: "A plant-rich diet, daily movement, and close community bonds contribute to Okinawa's remarkable longevity.", ex1Vn: "Chế độ ăn nhiều thực vật, vận động mỗi ngày và sự gắn kết cộng đồng chặt chẽ góp phần tạo nên sự trường thọ đáng kinh ngạc của vùng Okinawa.", ex2: "Wish your grandparents health and longevity on New Year's Day.", ex2Vn: "Hãy chúc ông bà sức khỏe dồi dào và sống lâu trăm tuổi trong ngày đầu năm mới nhé.", syn: ["long life", "durability"], ant: ["short life"] }
  ],

  // Theme 58: Holidays & Festivals (10 extra)
  t_basic_holidays_festivals: [
    { word: "firework", phonetic: "/ˈfaɪərwɜːrk/", def: "A device containing gunpowder and other combustible chemicals that causes a spectacular explosion when ignited.", defVn: "pháo hoa rực rỡ đêm giao thừa", pos: "noun", ex1: "Spectacular New Year fireworks lit up the midnight sky above the sparkling river.", ex1Vn: "Màn pháo hoa đón năm mới tuyệt đẹp đã thắp sáng bầu trời đêm giao thừa phía trên dòng sông lấp lánh.", ex2: "Thousands cheered as colorful fireworks exploded in dazzling patterns.", ex2Vn: "Hàng ngàn người reo hò khi những chùm pháo hoa rực rỡ bừng nở thành những họa tiết lộng lẫy.", syn: ["pyrotechnics"], ant: [] },
    { word: "parade", phonetic: "/pəˈreɪd/", def: "A public procession, especially one with a marching band and decorative floats.", defVn: "cuộc diễu hành lễ hội trên đường phố", pos: "noun", ex1: "The vibrant Independence Day parade featured brass marching bands, traditional dancers, and colorful floral floats.", ex1Vn: "Cuộc diễu hành Ngày Quốc Khánh rực rỡ sắc màu có các đoàn nhạc diễu hành kèn đồng, các vũ công truyền thống và những xe hoa rực rỡ.", ex2: "Children waved miniature flags eagerly as the festival parade marched past.", ex2Vn: "Lũ trẻ hào hứng vẫy những lá cờ nhỏ xíu khi đoàn diễu hành lễ hội đi ngang qua.", syn: ["procession", "march"], ant: [] },
    { word: "reunion", phonetic: "/ˌriːˈjuːniən/", def: "A social gathering attended by members of a certain group of people who have not seen each other for some time.", defVn: "bữa cơm sum họp gia đình, đoàn viên", pos: "noun", ex1: "The Lunar New Year Eve reunion dinner brings three generations together around a bountiful table.", ex1Vn: "Bữa cơm tất niên sum họp đêm giao thừa Tết Nguyên Đán gắn kết ba thế hệ quây quần bên mâm cỗ thịnh soạn.", ex2: "Our high school graduation class held a heartwarming ten-year reunion.", ex2Vn: "Khóa tốt nghiệp cấp ba của chúng tôi đã tổ chức một buổi họp lớp mười năm đầy ấm áp.", syn: ["gathering", "get-together"], ant: ["separation"] },
    { word: "costume", phonetic: "/ˈkɑːstuːm/", def: "A set of clothes in a style typical of a particular country or historical period, or worn to look like a character.", defVn: "trang phục hóa trang, đồ lễ hội", pos: "noun", ex1: "Children dressed up in playful superhero and wizard costumes for the Halloween trick-or-treat walk.", ex1Vn: "Lũ trẻ hóa trang thành những siêu anh hùng và phù thủy tinh nghịch cho chuyến đi xin kẹo lễ hội Halloween.", ex2: "Performers wore exquisite handmade silk costumes representing ancient dynasties.", ex2Vn: "Các nghệ sĩ biểu diễn mặc những bộ trang phục lụa thủ công tinh xảo đại diện cho các triều đại cổ xưa.", syn: ["outfit", "disguise", "attire"], ant: [] },
    { word: "masquerade", phonetic: "/ˌmæskəˈreɪd/", def: "A party, dance, or other festive gathering of persons wearing masks and other disguises.", defVn: "dạ vũ hóa trang, lễ hội đeo mặt nạ", pos: "noun", ex1: "Venice's annual Carnival masquerade ball fills the historic palazzos with mysterious masked revelers.", ex1Vn: "Dạ vũ hóa trang Lễ hội Venice hàng năm tràn ngập các cung điện cổ kính với những người trẩy hội đeo mặt nạ bí ẩn.", ex2: "She wore an elaborate feather-trimmed masquerade mask to the charity gala.", ex2Vn: "Cô ấy đã đeo một chiếc mặt nạ dạ hội đính lông vũ cầu kỳ đến buổi dạ tiệc từ thiện.", syn: ["masked ball"], ant: [] },
    { word: "tradition", phonetic: "/trəˈdɪʃn/", def: "The transmission of customs or beliefs from generation to generation.", defVn: "truyền thống tốt đẹp, phong tục tập quán", pos: "noun", ex1: "Making square sticky rice cakes (Banh Chung) together is a cherished Vietnamese Tet tradition.", ex1Vn: "Cùng nhau gói bánh chưng vuông vức là một nét truyền thống ngày Tết đáng trân quý của người Việt Nam.", ex2: "Respecting elders and honoring ancestors is an enduring cultural tradition.", ex2Vn: "Kính trọng người lớn tuổi và tưởng nhớ tổ tiên là một truyền thống văn hóa trường tồn.", syn: ["custom", "heritage", "practice"], ant: [] },
    { word: "feast", phonetic: "/fiːst/", def: "A large meal, typically one in celebration of something.", defVn: "bữa tiệc thịnh soạn, mâm cỗ linh đình", pos: "noun", ex1: "The hosts prepared a sumptuous festive feast with roasted meats, steamed seafood, and sweet desserts.", ex1Vn: "Chủ nhà đã chuẩn bị một mâm tiệc lễ hội thịnh soạn với các món thịt nướng, hải sản hấp và bánh tráng miệng ngọt ngào.", ex2: "We celebrated the bumper harvest with a village-wide feast under the stars.", ex2Vn: "Chúng tôi đã ăn mừng vụ mùa bội thu bằng một bữa tiệc linh đình của cả làng dưới bầu trời đêm đầy sao.", syn: ["banquet", "celebration meal"], ant: ["famine", "fast"] },
    { word: "carol", phonetic: "/ˈkærəl/", def: "A religious folk song or popular hymn, particularly one associated with Christmas.", defVn: "bài thánh ca mừng Giáng sinh", pos: "noun", ex1: "Choirs sang uplifting Christmas carols beneath the illuminated town square tree.", ex1Vn: "Các dàn hợp xướng đã cất cao những bài thánh ca Giáng sinh hân hoan bên dưới cây thông sáng rực ở quảng trường thị trấn.", ex2: "'Silent Night' is one of the most beloved carols sung around the world.", ex2Vn: "'Đêm Thánh Vô Cùng' là một trong những bài thánh ca được yêu thích nhất được hát vang khắp thế giới.", syn: ["hymn", "chant"], ant: [] },
    { word: "ornament", phonetic: "/ˈɔːrnəmənt/", def: "A thing used to make something look more attractive but having no practical purpose, especially a Christmas tree bauble.", defVn: "vật phẩm trang trí cây thông / nhà cửa", pos: "noun", ex1: "Hang sparkling blown-glass ornaments and golden stars on the fragrant pine branches.", ex1Vn: "Treo những quả cầu thủy tinh trang trí lấp lánh và những ngôi sao vàng lên các cành thông thơm ngát nhé.", ex2: "Handcrafted ceramic ornaments commemorate special family trips.", ex2Vn: "Những món đồ trang trí bằng gốm thủ công kỷ niệm những chuyến du lịch đặc biệt của gia đình.", syn: ["decoration", "trinket", "bauble"], ant: [] },
    { word: "carolling", phonetic: "/ˈkærəlɪŋ/", def: "The activity of singing carols in public places or going from house to house at Christmas.", defVn: "việc đi hát mừng thánh ca Giáng sinh", pos: "noun", ex1: "Going door-to-door carolling spreads cheer and holiday goodwill throughout the neighborhood.", ex1Vn: "Đi từng nhà hát thánh ca mừng Giáng sinh lan tỏa niềm vui và sự ấm áp của kỳ nghỉ lễ khắp khu phố.", ex2: "Hot spiced cocoa awaited the carolling singers when they returned home.", ex2Vn: "Những tách ca-cao nóng thơm lừng đang chờ đón những người đi hát thánh ca khi họ trở về nhà.", syn: ["singing carols"], ant: [] }
  ],

  // Theme 59: Safety & Emergency Rules (10 extra)
  t_basic_safety_emergency: [
    { word: "hydrant", phonetic: "/ˈhaɪdrənt/", def: "An upright water pipe, especially one in a street, with a nozzle to which a fire hose can be attached.", defVn: "trụ nước cứu hỏa trên đường phố", pos: "noun", ex1: "Never park your car in front of a red fire hydrant so emergency fire trucks have instant access.", ex1Vn: "Đừng bao giờ đỗ xe ô tô phía trước trụ nước cứu hỏa màu đỏ để xe chữa cháy khẩn cấp có thể tiếp cận ngay lập tức.", ex2: "Firefighters hooked high-pressure hoses to the municipal water hydrant.", ex2Vn: "Những người lính cứu hỏa đã nối các vòi phun áp lực cao vào trụ nước cứu hỏa của thành phố.", syn: ["fireplug", "water point"], ant: [] },
    { word: "defibrillator", phonetic: "/diːˈfɪbrɪleɪtər/", def: "An apparatus used to control heart fibrillation by application of an electric current to the chest wall or heart.", defVn: "máy sốc tim tự động (AED cấp cứu)", pos: "noun", ex1: "Automated external defibrillators installed in public train stations can save lives during cardiac arrest.", ex1Vn: "Các máy sốc tim tự động được lắp đặt tại các nhà ga công cộng có thể cứu sống tính mạng người bệnh khi bị ngừng tim.", ex2: "The automated voice on the portable defibrillator guides the rescuer through every step.", ex2Vn: "Giọng nói tự động trên máy sốc tim di động hướng dẫn người cứu hộ thực hiện từng bước chi tiết.", syn: ["AED", "cardiac shock device"], ant: [] },
    { word: "stretcher", phonetic: "/ˈstretʃər/", def: "A framework of two poles with a long piece of canvas between them, used for carrying sick, injured, or dead people.", defVn: "cáng cứu thương, cáng khiêng bệnh nhân", pos: "noun", ex1: "Paramedics lifted the injured hiker carefully onto the folding stretcher and loaded him into the ambulance.", ex1Vn: "Các nhân viên y tế đã nâng người đi leo núi bị thương lên chiếc cáng gấp cẩn thận và đưa anh ấy vào xe cấp cứu.", ex2: "Mountain rescue teams use specialized lightweight titanium stretchers.", ex2Vn: "Các đội cứu hộ vùng núi sử dụng những chiếc cáng khiêng chuyên dụng bằng titan siêu nhẹ.", syn: ["gurney", "litter"], ant: [] },
    { word: "siren", phonetic: "/ˈsaɪrən/", def: "A device that makes a loud, prolonged signal or warning sound.", defVn: "còi báo động khẩn cấp (xe cứu hỏa/cứu thương)", pos: "noun", ex1: "Vehicles pulled over promptly to make way when they heard the wailing ambulance siren.", ex1Vn: "Các phương tiện đã nhanh chóng tấp vào lề nhường đường khi nghe thấy tiếng còi xe cấp cứu hú vang.", ex2: "Tornado sirens warned residents to take shelter in underground basements.", ex2Vn: "Còi báo động lốc xoáy đã cảnh báo người dân khẩn trương tìm nơi trú ẩn trong các tầng hầm dưới lòng đất.", syn: ["alarm", "klaxon", "warning signal"], ant: [] },
    { word: "extinguish", phonetic: "/ɪkˈstɪŋɡwɪʃ/", def: "Cause a fire or light to cease to burn or shine.", defVn: "dập tắt ngọn lửa, dập tắt đám cháy", pos: "verb", ex1: "Always douse and completely extinguish campfire embers with water and soil before leaving the campsite.", ex1Vn: "Hãy luôn tưới nước và dập tắt hoàn toàn tàn than lửa trại bằng nước và đất trước khi rời khỏi khu cắm trại nhé.", ex2: "Fire crews worked tirelessly through the night to extinguish the blaze.", ex2Vn: "Các đội cứu hỏa đã làm việc không mệt mỏi suốt đêm để dập tắt ngọn lửa bùng phát.", syn: ["put out", "quench", "smother"], ant: ["ignite", "kindle"] },
    { word: "evacuate", phonetic: "/ɪˈvækjuːeɪt/", def: "Remove someone from a place of danger to a safe place.", defVn: "sơ tán khẩn cấp đến nơi an toàn", pos: "verb", ex1: "Security staff guided all shopping mall visitors to evacuate calmly via designated emergency exits.", ex1Vn: "Nhân viên an ninh đã hướng dẫn tất cả khách tham quan trung tâm thương mại sơ tán bình tĩnh qua các lối thoát hiểm được chỉ định.", ex2: "Coastal towns evacuated residents ahead of the incoming super typhoon.", ex2Vn: "Các thị trấn ven biển đã kịp thời sơ tán người dân trước khi siêu bão đổ bộ vào đất liền.", syn: ["clear", "vacate", "relocate"], ant: [] },
    { word: "hazard", phonetic: "/ˈhæzərd/", def: "A danger or risk.", defVn: "mối nguy hiểm, hiểm họa rủi ro", pos: "noun", ex1: "Spilled cooking oil on the kitchen floor poses a serious slip hazard.", ex1Vn: "Dầu ăn bị đổ ra sàn bếp là một mối nguy hiểm gây trơn trượt rất nghiêm trọng.", ex2: "Wear protective steel-toe boots to protect against occupational hazards on building sites.", ex2Vn: "Hãy đi giày bảo hộ mũi thép để bảo vệ bản thân trước những hiểm họa nghề nghiệp trên công trường xây dựng nhé.", syn: ["danger", "peril", "risk"], ant: ["safety", "security"] },
    { word: "toxic", phonetic: "/ˈtɑːksɪk/", def: "Poisonous; causing unpleasant feelings or harmful health effects.", defVn: "độc hại, có chứa chất độc", pos: "adj", ex1: "Store toxic household cleaning agents in locked upper cabinets away from young children.", ex1Vn: "Cất giữ các chất tẩy rửa gia dụng độc hại trong các tủ khóa trên cao tránh xa tầm tay trẻ nhỏ nhé.", ex2: "Proper ventilation prevents the buildup of toxic paint fumes.", ex2Vn: "Sự thông gió hợp lý giúp ngăn ngừa sự tích tụ của các hơi khói sơn độc hại.", syn: ["poisonous", "noxious", "venomous"], ant: ["nontoxic", "harmless"] },
    { word: "paramedic", phonetic: "/ˌpærəˈmedɪk/", def: "A person trained to give emergency medical care to people who are seriously ill with the aim of stabilizing them before they arrive at the hospital.", defVn: "nhân viên y tế cấp cứu hiện trường", pos: "noun", ex1: "The skilled paramedic administered oxygen and stabilized the patient's vital signs in transit.", ex1Vn: "Người nhân viên cấp cứu lành nghề đã cho thở oxy và ổn định các chỉ số sinh tồn của bệnh nhân trên đường chuyển viện.", ex2: "Paramedics are trained to make critical life-saving decisions under immense pressure.", ex2Vn: "Các nhân viên y tế cấp cứu được đào tạo bài bản để đưa ra những quyết định cứu người sống còn dưới áp lực vô cùng lớn.", syn: ["emergency medical technician", "EMT"], ant: [] },
    { word: "whistle", phonetic: "/ˈwɪsl/", def: "A clear, high-pitched sound made by forcing breath through a small hole between one's lips or teeth, or through an instrument.", defVn: "tiếng còi, cái còi thổi cứu nạn", pos: "noun", ex1: "Carry an emergency safety whistle on your life jacket when kayaking or hiking.", ex1Vn: "Hãy mang theo một chiếc còi cứu hộ an toàn gắn trên áo phao khi chèo thuyền kayak hoặc đi leo núi nhé.", ex2: "The referee blew his loud whistle to halt play immediately.", ex2Vn: "Trọng tài đã thổi một hồi còi đanh thép để dừng trận đấu ngay tức thì.", syn: ["pipe", "hooter"], ant: [] }
  ],

  // Theme 60: Home Appliances & Smart Gadgets (10 extra)
  t_basic_appliances_gadgets: [
    { word: "dehumidifier", phonetic: "/ˌdiːhjuːˈmɪdɪfaɪər/", def: "An electrical appliance that reduces and maintains the level of humidity in the air.", defVn: "máy hút ẩm không khí (chống nồm ẩm)", pos: "noun", ex1: "Running an efficient dehumidifier keeps indoor rooms dry and mold-free during spring humid seasons in Hanoi.", ex1Vn: "Bật một chiếc máy hút ẩm hiệu suất cao giúp các phòng trong nhà luôn khô ráo và không bị ẩm mốc trong những mùa nồm ẩm mùa xuân ở Hà Nội.", ex2: "Empty the dehumidifier water tank once it fills up automatically.", ex2Vn: "Đổ bình chứa nước của máy hút ẩm khi nó tự động báo đầy nhé.", syn: ["moisture absorber"], ant: ["humidifier"] },
    { word: "humidifier", phonetic: "/hjuːˈmɪdɪfaɪər/", def: "A device for keeping the atmosphere moist in a room.", defVn: "máy tạo độ ẩm, máy phun sương", pos: "noun", ex1: "An ultrasonic cool-mist humidifier prevents dry skin and throat irritation in air-conditioned rooms.", ex1Vn: "Máy tạo độ ẩm phun sương mát siêu âm giúp ngăn ngừa khô da và rát cổ họng trong các phòng có điều hòa nhiệt độ.", ex2: "Add a few drops of lavender essential oil to the aroma humidifier.", ex2Vn: "Thêm vài giọt tinh dầu oải hương vào máy phun sương tạo ẩm khuếch tán hương thơm nhé.", syn: ["vaporizer", "mist maker"], ant: ["dehumidifier"] },
    { word: "steamer", phonetic: "/ˈstiːmər/", def: "An appliance in which food or clothing is subjected to steam.", defVn: "bàn là hơi nước đứng / nồi hấp hơi", pos: "noun", ex1: "Use a handheld garment steamer to remove wrinkles from delicate silk dresses in seconds.", ex1Vn: "Dùng bàn là hơi nước cầm tay để ủi phẳng các nếp nhăn trên váy lụa mỏng manh chỉ trong vài giây nhé.", ex2: "A multi-tier bamboo steamer cooks fluffy dim sum and bao buns to perfection.", ex2Vn: "Xửng hấp tre nhiều tầng hấp chín những chiếc bánh dimsum và bánh bao xốp mềm đến độ hoàn hảo.", syn: ["vaporizer", "steam iron"], ant: [] },
    { word: "thermostat", phonetic: "/ˈθɜːrməstæt/", def: "A device that automatically regulates temperature, or that activates a device when the temperature reaches a certain point.", defVn: "bộ điều nhiệt tự động, cảm biến nhiệt độ", pos: "noun", ex1: "The smart learning thermostat adjusts home heating and cooling schedules to save electricity.", ex1Vn: "Bộ điều nhiệt thông minh tự học tự động điều chỉnh lịch trình sưởi và làm mát trong nhà để tiết kiệm điện năng.", ex2: "Set the digital room thermostat to a comfortable twenty-four degrees Celsius.", ex2Vn: "Cài đặt bộ điều nhiệt kỹ thuật số trong phòng ở mức hai mươi tư độ C dễ chịu nhé.", syn: ["temperature controller"], ant: [] },
    { word: "air fryer", phonetic: "/ˈer fraɪər/", def: "A small countertop convection oven designed to simulate deep frying without submerging the food in oil.", defVn: "nồi chiên không dầu (ít dầu mỡ, giòn ngon)", pos: "noun", ex1: "Crispy chicken wings cooked in an air fryer use eighty percent less cooking oil.", ex1Vn: "Cánh gà nướng giòn nấu bằng nồi chiên không dầu sử dụng ít hơn tám mươi phần trăm dầu ăn thông thường.", ex2: "Preheat the air fryer to two hundred degrees for super crunchy French fries.", ex2Vn: "Làm nóng trước nồi chiên không dầu ở hai trăm độ để làm món khoai tây chiên siêu giòn rụm nhé.", syn: ["convection fryer"], ant: ["deep fryer"] },
    { word: "juicer", phonetic: "/ˈdʒuːsər/", def: "An appliance for extracting juice from fruit and vegetables.", defVn: "máy ép hoa quả, máy ép chậm", pos: "noun", ex1: "A cold-press slow juicer preserves natural enzymes and rich vitamins in fresh celery and apple juices.", ex1Vn: "Máy ép chậm ép nguội giữ trọn vẹn các enzym tự nhiên và lượng vitamin dồi dào trong nước ép cần tây và táo tươi.", ex2: "Clean the stainless steel juicer mesh filter immediately after use.", ex2Vn: "Rửa sạch lưới lọc bằng thép không gỉ của máy ép hoa quả ngay sau khi sử dụng nhé.", syn: ["juice extractor", "squeezer"], ant: [] },
    { word: "projector", phonetic: "/prəˈdʒektər/", def: "An apparatus for projecting an optical image on a screen or other surface.", defVn: "máy chiếu phim gia đình / văn phòng", pos: "noun", ex1: "Turn your living room into a private home cinema with a 4K laser projector and screen.", ex1Vn: "Biến phòng khách của bạn thành rạp chiếu phim tại gia riêng tư với một chiếc máy chiếu laser 4K và màn chiếu lớn.", ex2: "Connect your laptop wirelessly to the conference room video projector.", ex2Vn: "Kết nối máy tính xách tay của bạn không dây với máy chiếu video của phòng họp hội nghị nhé.", syn: ["beam projector"], ant: [] },
    { word: "adapter", phonetic: "/əˈdæptər/", def: "A device for connecting pieces of equipment that cannot be connected directly.", defVn: "đầu chuyển đổi phích cắm / cáp kết nối", pos: "noun", ex1: "Pack a universal travel power adapter when traveling across different countries.", ex1Vn: "Hãy mang theo một đầu chuyển đổi nguồn điện du lịch đa năng khi đi du lịch qua các quốc gia khác nhau nhé.", ex2: "Use a USB-C multi-port adapter to connect external monitors and flash drives.", ex2Vn: "Sử dụng đầu chuyển đổi đa cổng USB-C để kết nối màn hình ngoài và ổ cứng di động nhé.", syn: ["connector", "converter"], ant: [] },
    { word: "powerbank", phonetic: "/ˈpaʊərbæŋk/", def: "A portable battery used to recharge mobile devices.", defVn: "pin sạc dự phòng di động", pos: "noun", ex1: "A high-capacity fast-charging powerbank keeps your phone charged throughout long travel days.", ex1Vn: "Pin sạc dự phòng dung lượng cao sạc nhanh giúp điện thoại của bạn luôn đầy pin trong suốt những ngày dài di chuyển.", ex2: "Remember to carry your lithium powerbank in your carry-on bag rather than checked luggage.", ex2Vn: "Hãy nhớ mang pin dự phòng lithium trong hành lý xách tay thay vì để trong hành lý ký gửi nhé.", syn: ["portable charger", "battery pack"], ant: [] },
    { word: "earbuds", phonetic: "/ˈɪrbʌdz/", def: "Very small headphones that are fitted directly into the ear.", defVn: "tai nghe nhét tai không dây (Bluetooth)", pos: "noun", ex1: "Active noise-cancelling wireless earbuds deliver immersive, crystal-clear audio during workouts.", ex1Vn: "Tai nghe nhét tai không dây chống ồn chủ động mang lại âm thanh trong trẻo, chân thực trong suốt các buổi tập luyện.", ex2: "Store your wireless earbuds inside their compact magnetic charging case.", ex2Vn: "Cất tai nghe không dây của bạn vào bên trong hộp sạc từ tính nhỏ gọn của chúng nhé.", syn: ["in-ear earphones", "wireless buds"], ant: ["over-ear headphones"] }
  ]
};
