module.exports = {
  // Theme 1: Chào hỏi & Giao tiếp (Extra 15 words)
  t_basic_greetings: [
    { word: "good luck", phonetic: "/ɡʊd lʌk/", def: "Used to wish someone success before a challenge.", defVn: "chúc may mắn!", pos: "phrase", ex: ["Good luck on your English test today!", "I know you can do it, good luck!"], exVn: ["Chúc bạn may mắn trong bài thi tiếng Anh hôm nay!", "Tôi biết bạn có thể làm được, chúc may mắn nhé!"] },
    { word: "see you soon", phonetic: "/siː juː suːn/", def: "Said when expecting to see someone again shortly.", defVn: "hẹn sớm gặp lại bạn", pos: "phrase", ex: ["I must catch the bus. See you soon!", "Take care and see you soon."], exVn: ["Tôi phải bắt xe buýt rồi. Hẹn sớm gặp lại bạn nhé!", "Bảo trọng và sớm gặp lại nhé."] },
    { word: "how do you do", phonetic: "/haʊ duː juː duː/", def: "A formal greeting used when meeting someone for first time.", defVn: "hân hạnh được gặp ngài (trang trọng)", pos: "phrase", ex: ["How do you do, Mr. Smith? — How do you do.", "It is an honor to meet you, how do you do?"], exVn: ["Hân hạnh được gặp ngài, ông Smith?", "Thật là một vinh dự được gặp ngài!"] },
    { word: "my pleasure", phonetic: "/maɪ ˈpleʒər/", def: "Polite response to thanks, meaning happy to help.", defVn: "đó là niềm vinh hạnh của tôi", pos: "phrase", ex: ["Thank you for dinner! — My pleasure.", "Thanks for guiding us. — My pleasure, anytime!"], exVn: ["Cảm ơn vì bữa tối! — Đó là vinh hạnh của tôi.", "Cảm ơn đã dẫn đường. — Rất hân hạnh, bất cứ lúc nào!"] },
    { word: "have a good weekend", phonetic: "/hæv ə ɡʊd ˈwiːkend/", def: "Wishing someone an enjoyable weekend.", defVn: "chúc bạn cuối tuần vui vẻ!", pos: "phrase", ex: ["See you on Monday! Have a good weekend.", "Thank you, teacher, have a good weekend too!"], exVn: ["Hẹn gặp lại vào thứ Hai! Chúc cuối tuần vui vẻ.", "Cảm ơn thầy, chúc thầy cuối tuần vui vẻ ạ!"] },
    { word: "long time no see", phonetic: "/lɔːŋ taɪm noʊ siː/", def: "Said when meeting after a long time.", defVn: "lâu quá không gặp bạn!", pos: "phrase", ex: ["Long time no see! How is your new job going?", "Minh, long time no see! You look great."], exVn: ["Lâu quá rồi không gặp! Công việc mới thế nào rồi?", "Minh ơi lâu quá không gặp! Trông bạn tuyệt lắm."] },
    { word: "what's up", phonetic: "/wʌts ʌp/", def: "An informal greeting asking what is happening.", defVn: "có chuyện gì thế? dạo này thế nào?", pos: "phrase", ex: ["Hey bro, what's up? — Not much, just studying.", "What's up, everyone?"], exVn: ["Này bạn, có chuyện gì thế? — Đang học bài thôi.", "Mọi người dạo này thế nào rồi?"] },
    { word: "bless you", phonetic: "/bles juː/", def: "Said politely when someone sneezes.", defVn: "chúc bạn sức khỏe (khi hắt hơi)", pos: "phrase", ex: ["*Achoo!* — Bless you!", "Bless you! Do you have a cold?"], exVn: ["*Hắt xì!* — Chúc bạn sức khỏe!", "Chúc bạn mau khỏe! Bạn bị cảm lạnh à?"] },
    { word: "greetings", phonetic: "/ˈɡriːtɪŋz/", def: "A polite word or sign of welcome.", defVn: "lời chào, lời chúc mừng", pos: "noun", ex: ["Season's greetings to your family!", "He sent warm greetings from London."], exVn: ["Gửi lời chúc mùa lễ hội đến gia đình bạn!", "Anh ấy gửi lời chào ấm áp từ Luân Đôn."] },
    { word: "farewell", phonetic: "/ˌferˈwel/", def: "An act of saying goodbye before departure.", defVn: "lời chào tạm biệt chia tay", pos: "noun", ex: ["They threw a farewell party for him.", "She waved a sad farewell at the airport."], exVn: ["Họ đã tổ chức bữa tiệc chia tay cho anh ấy.", "Cô ấy vẫy tay tạm biệt ở sân bay."] },
    { word: "nice day", phonetic: "/naɪs deɪ/", def: "A pleasant and enjoyable day.", defVn: "ngày đẹp trời, ngày tốt lành", pos: "phrase", ex: ["It is a nice day for a walk outside.", "Have a nice day ahead!"], exVn: ["Hôm nay là một ngày đẹp trời để đi dạo.", "Chúc bạn một ngày tốt lành phía trước!"] },
    { word: "see you tomorrow", phonetic: "/siː juː təˈmɔːroʊ/", def: "Said to someone you will see the next day.", defVn: "hẹn gặp lại bạn vào ngày mai", pos: "phrase", ex: ["Class is over. See you tomorrow!", "See you tomorrow at 8 AM sharp."], exVn: ["Lớp học kết thúc rồi. Hẹn gặp ngày mai nhé!", "Hẹn gặp bạn đúng 8 giờ sáng mai."] },
    { word: "pardon me", phonetic: "/ˈpɑːrdn miː/", def: "A polite phrase asking someone to excuse you.", defVn: "xin thứ lỗi cho tôi", pos: "phrase", ex: ["Pardon me, is this seat available?", "Pardon me, I did not catch your name."], exVn: ["Xin thứ lỗi, ghế này còn trống không ạ?", "Xin thứ lỗi, tôi chưa nghe rõ tên bạn."] },
    { word: "have a good trip", phonetic: "/hæv ə ɡʊd trɪp/", def: "Wishing someone a safe and enjoyable journey.", defVn: "chúc bạn có chuyến đi thượng lộ bình an", pos: "phrase", ex: ["Have a good trip to Tokyo!", "Thank you, and have a good trip home."], exVn: ["Chúc bạn có chuyến đi Tokyo vui vẻ!", "Cảm ơn bạn, chúc bạn về nhà bình an nhé."] },
    { word: "all right", phonetic: "/ɔːl raɪt/", def: "Satisfactory; okay.", defVn: "ổn thỏa, được rồi", pos: "adverb", ex: ["Everything will be all right, don't worry.", "Are you feeling all right now?"], exVn: ["Mọi chuyện sẽ ổn thôi, đừng lo lắng.", "Bây giờ bạn thấy ổn chưa?"] }
  ],

  // Theme 2: Giới thiệu & Đại từ
  t_basic_introductions: [
    { word: "these", phonetic: "/ðiːz/", def: "Plural of this; referring to things close by.", defVn: "những cái này, những người này (gần)", pos: "pronoun", ex: ["These apples are sweet and crunchy.", "Are these your keys on the desk?"], exVn: ["Những quả táo này ngọt và giòn.", "Đây có phải chùm chìa khóa của bạn không?"] },
    { word: "those", phonetic: "/ðoʊz/", def: "Plural of that; referring to things farther away.", defVn: "những cái kia, những người kia (xa)", pos: "pronoun", ex: ["Those mountains look beautiful.", "Who are those people over there?"], exVn: ["Những ngọn núi đằng xa trông thật đẹp.", "Những người đứng đằng kia là ai vậy?"] },
    { word: "when", phonetic: "/wen/", def: "Question word asking for time.", defVn: "khi nào, lúc nào (thời gian)", pos: "adverb", ex: ["When is your birthday?", "When does the English class begin?"], exVn: ["Sinh nhật của bạn là khi nào?", "Khi nào lớp học tiếng Anh bắt đầu?"] },
    { word: "why", phonetic: "/waɪ/", def: "Question word asking for reason.", defVn: "tại sao, vì sao (nguyên nhân)", pos: "adverb", ex: ["Why do you want to learn English?", "Why is the sky blue?"], exVn: ["Tại sao bạn muốn học tiếng Anh?", "Tại sao bầu trời lại có màu xanh?"] },
    { word: "how", phonetic: "/haʊ/", def: "Question word asking for manner or method.", defVn: "như thế nào, bằng cách nào", pos: "adverb", ex: ["How do you spell your name?", "How can I improve my pronunciation?"], exVn: ["Bạn đánh vần tên bạn như thế nào?", "Làm thế nào để tôi cải thiện phát âm?"] },
    { word: "birthday", phonetic: "/ˈbɜːrθdeɪ/", def: "The anniversary of one's birth.", defVn: "ngày sinh nhật", pos: "noun", ex: ["Happy birthday to you!", "My birthday is on May fifth."], exVn: ["Chúc mừng sinh nhật bạn!", "Sinh nhật của tôi là vào ngày 5 tháng 5."] },
    { word: "country", phonetic: "/ˈkʌntri/", def: "A nation with government and territory.", defVn: "quốc gia, đất nước", pos: "noun", ex: ["Which country are you from?", "Vietnam is a beautiful country."], exVn: ["Bạn đến từ quốc gia nào?", "Việt Nam là một đất nước tươi đẹp."] },
    { word: "city", phonetic: "/ˈsɪti/", def: "A large town with many inhabitants.", defVn: "thành phố, đô thị", pos: "noun", ex: ["Hanoi is the capital city of Vietnam.", "I love the city atmosphere."], exVn: ["Hà Nội là thủ đô của Việt Nam.", "Tôi yêu bầu không khí của thành phố."] },
    { word: "hometown", phonetic: "/ˈhoʊmtaʊn/", def: "The town of one's birth or youth.", defVn: "quê hương, quê nhà", pos: "noun", ex: ["My hometown is Da Nang by the sea.", "He visits his hometown every summer."], exVn: ["Quê hương tôi là Đà Nẵng bên bờ biển.", "Anh ấy về thăm quê nhà mỗi mùa hè."] },
    { word: "myself", phonetic: "/maɪˈself/", def: "The speaker referring to himself or herself.", defVn: "chính bản thân tôi, tự mình", pos: "pronoun", ex: ["Let me introduce myself to the team.", "I baked this chocolate cake myself."], exVn: ["Hãy để tôi tự giới thiệu bản thân.", "Tôi đã tự tay nướng chiếc bánh sô-cô-la này."] },
    { word: "yourself", phonetic: "/jɔːrˈself/", def: "The person addressed referring to oneself.", defVn: "chính bản thân bạn, tự bạn", pos: "pronoun", ex: ["Take good care of yourself!", "Please introduce yourself in English."], exVn: ["Hãy chăm sóc tốt cho bản thân nhé!", "Xin vui lòng tự giới thiệu bằng tiếng Anh."] },
    { word: "himself", phonetic: "/hɪmˈself/", def: "Used to refer to a male person as the object of an action he performs.", defVn: "chính bản thân anh ấy, tự anh ấy", pos: "pronoun", ex: ["He fixed the computer himself.", "He taught himself how to play piano."], exVn: ["Anh ấy đã tự tay sửa máy tính.", "Anh ấy tự học chơi đàn piano."] },
    { word: "herself", phonetic: "/hɜːrˈself/", def: "Used to refer to a female person as the object of an action she performs.", defVn: "chính bản thân cô ấy, tự cô ấy", pos: "pronoun", ex: ["She bought herself a new bag.", "She prepared dinner all by herself."], exVn: ["Cô ấy đã tự mua cho mình chiếc túi mới.", "Cô ấy tự tay chuẩn bị bữa tối một mình."] },
    { word: "ourselves", phonetic: "/ɑːrˈselvz/", def: "Used by speakers to refer to themselves.", defVn: "chính chúng tôi, tự chúng ta", pos: "pronoun", ex: ["We enjoyed ourselves at the party.", "We must protect ourselves from the cold."], exVn: ["Chúng tôi đã rất vui vẻ tại bữa tiệc.", "Chúng ta phải tự giữ ấm cho bản thân."] },
    { word: "nationality", phonetic: "/ˌnæʃəˈnæləti/", def: "The status of belonging to a particular nation.", defVn: "quốc tịch", pos: "noun", ex: ["What is your nationality? — I am Vietnamese.", "People of different nationalities live here."], exVn: ["Quốc tịch của bạn là gì? — Tôi là người Việt Nam.", "Mọi người từ nhiều quốc tịch cùng sinh sống ở đây."] }
  ],

  // Theme 3: Số đếm & Thứ tự
  t_basic_numbers: [
    { word: "double", phonetic: "/ˈdʌbl/", def: "Twice as much or many; twofold.", defVn: "gấp đôi, nhân đôi", pos: "adj", ex: ["I ordered a double espresso.", "His salary doubled this year."], exVn: ["Tôi gọi một ly espresso gấp đôi.", "Lương của anh ấy đã tăng gấp đôi năm nay."] },
    { word: "pair", phonetic: "/per/", def: "A set of two things used together.", defVn: "một đôi, một cặp", pos: "noun", ex: ["I bought a new pair of white shoes.", "A pair of glasses was on desk."], exVn: ["Tôi mua một đôi giày trắng mới.", "Một chiếc kính mắt đang ở trên bàn."] },
    { word: "dozen", phonetic: "/ˈdʌzn/", def: "A group or set of twelve.", defVn: "một tá (12 cái)", pos: "noun", ex: ["Please buy a dozen fresh eggs.", "She baked two dozen cookies."], exVn: ["Làm ơn mua một tá trứng gà tươi.", "Cô ấy nướng hai tá bánh quy."] },
    { word: "plus", phonetic: "/plʌs/", def: "With addition of (+).", defVn: "cộng thêm, dấu cộng (+)", pos: "preposition", ex: ["Two plus three equals five.", "Total is fifty dollars plus tax."], exVn: ["Hai cộng ba bằng năm.", "Tổng là 50 đô la cộng thuế."] },
    { word: "minus", phonetic: "/ˈmaɪnəs/", def: "With subtraction of (-).", defVn: "trừ đi, dấu trừ (-)", pos: "preposition", ex: ["Ten minus four equals six.", "Temperature is minus five degrees."], exVn: ["Mười trừ bốn bằng sáu.", "Nhiệt độ hiện tại là âm năm độ."] },
    { word: "equal", phonetic: "/ˈiːkwəl/", def: "Being the same in value (=).", defVn: "bằng nhau, dấu bằng (=)", pos: "verb", ex: ["One plus one equals two.", "All people are born equal."], exVn: ["Một cộng một bằng hai.", "Mọi người sinh ra đều bình đẳng."] },
    { word: "many", phonetic: "/ˈmeni/", def: "A large number of items.", defVn: "nhiều (đếm được)", pos: "adj", ex: ["There are many books on the shelf.", "How many languages do you speak?"], exVn: ["Có rất nhiều sách trên kệ.", "Bạn nói được bao nhiêu thứ tiếng?"] },
    { word: "much", phonetic: "/mʌtʃ/", def: "A large amount of something.", defVn: "nhiều (không đếm được)", pos: "adj", ex: ["How much water do you drink a day?", "Thank you so much for your support!"], exVn: ["Bạn uống bao nhiêu nước mỗi ngày?", "Cảm ơn bạn rất nhiều vì sự ủng hộ!"] },
    { word: "few", phonetic: "/fjuː/", def: "A small number of items.", defVn: "ít, một vài (đếm được)", pos: "adj", ex: ["I have a few questions to ask.", "Only a few students arrived early."], exVn: ["Tôi có một vài câu hỏi muốn hỏi.", "Chỉ có một số ít học sinh đến sớm."] },
    { word: "little", phonetic: "/ˈlɪtl/", def: "A small amount of something.", defVn: "ít, một chút (không đếm được)", pos: "adj", ex: ["I speak a little English.", "Add a little sugar to the tea."], exVn: ["Tôi nói được một chút tiếng Anh.", "Hãy cho một chút đường vào trà."] },
    { word: "last", phonetic: "/læst/", def: "Coming after all others in order; final.", defVn: "cuối cùng, vừa qua", pos: "adj", ex: ["This is last lesson of the course.", "I saw him last night at the party."], exVn: ["Đây là bài học cuối cùng của khóa học.", "Tôi đã gặp anh ấy đêm qua."] },
    { word: "fourth", phonetic: "/fɔːrθ/", def: "Constituting number four in a sequence; 4th.", defVn: "thứ tư (4th)", pos: "adj", ex: ["July fourth is Independence Day in the USA.", "Our apartment is on the fourth floor."], exVn: ["Ngày mùng 4 tháng Bảy là ngày Quốc khánh Mỹ.", "Căn hộ của chúng tôi ở tầng bốn."] },
    { word: "fifth", phonetic: "/fɪfθ/", def: "Constituting number five in a sequence; 5th.", defVn: "thứ năm (5th)", pos: "adj", ex: ["He celebrated his fifth wedding anniversary.", "May fifth is a special day."], exVn: ["Anh ấy kỷ niệm 5 năm ngày cưới.", "Ngày 5 tháng 5 là một ngày đặc biệt."] },
    { word: "single", phonetic: "/ˈsɪŋɡl/", def: "Only one; not double or multiple.", defVn: "đơn lẻ, một mình, độc thân", pos: "adj", ex: ["I booked a single room at the hotel.", "Not a single person was late."], exVn: ["Tôi đã đặt một phòng đơn tại khách sạn.", "Không có một ai bị muộn cả."] },
    { word: "triple", phonetic: "/ˈtrɪpl/", def: "Consisting of three equal parts or things.", defVn: "gấp ba, bộ ba", pos: "adj", ex: ["We reserved a triple room for three friends.", "The company tripled its profit."], exVn: ["Chúng tôi đặt phòng ba người cho ba người bạn.", "Công ty đã tăng gấp ba lợi nhuận."] }
  ],

  // Theme 4: Màu sắc & Hình khối
  t_basic_colors_shapes: [
    { word: "gold", phonetic: "/ɡoʊld/", def: "A precious shiny yellow color.", defVn: "màu vàng kim, vàng óng", pos: "adj", ex: ["She wore a shiny gold necklace.", "Autumn leaves shone like gold."], exVn: ["Cô ấy đeo sợi dây chuyền vàng óng.", "Những chiếc lá thu tỏa sáng như vàng."] },
    { word: "silver", phonetic: "/ˈsɪlvər/", def: "A shiny grayish-white metallic color.", defVn: "màu bạc, ánh bạc", pos: "adj", ex: ["He won a silver medal in running.", "The silver moon lit up the night."], exVn: ["Cậu ấy đoạt huy chương bạc môn chạy.", "Mặt trăng ánh bạc thắp sáng màn đêm."] },
    { word: "star", phonetic: "/stɑːr/", def: "A shape with five or six points; celestial body.", defVn: "hình ngôi sao, vì sao", pos: "noun", ex: ["The teacher put a gold star on my paper.", "Stars shine brightly at night."], exVn: ["Cô giáo dán ngôi sao vàng vào bài tôi.", "Các vì sao tỏa sáng lấp lánh ban đêm."] },
    { word: "heart", phonetic: "/hɑːrt/", def: "A symbol of love; organ in chest.", defVn: "hình trái tim, quả tim", pos: "noun", ex: ["She drew a little red heart on letter.", "He has a kind and generous heart."], exVn: ["Cô ấy vẽ hình trái tim đỏ lên bức thư.", "Anh ấy có trái tim nhân hậu."] },
    { word: "diamond", phonetic: "/ˈdaɪəmənd/", def: "A rhombus shape with four equal sides.", defVn: "hình thoi, kim cương", pos: "noun", ex: ["Road signs often have a diamond shape.", "She wore a sparkling diamond ring."], exVn: ["Biển báo đường bộ có hình thoi.", "Cô ấy đeo chiếc nhẫn kim cương lấp lánh."] },
    { word: "oval", phonetic: "/ˈoʊvl/", def: "An egg-shaped curved figure.", defVn: "hình bầu dục, hình ô-van", pos: "noun", ex: ["An egg has an oval shape.", "The mirror in bathroom is oval."], exVn: ["Quả trứng có hình bầu dục.", "Chiếc gương phòng tắm có hình bầu dục."] },
    { word: "line", phonetic: "/laɪn/", def: "A long, narrow mark or band.", defVn: "đường thẳng, dòng kẻ", pos: "noun", ex: ["Draw a straight line with ruler.", "Please stand in a straight line."], exVn: ["Hãy vẽ đường thẳng bằng thước kẻ.", "Xin vui lòng đứng thành hàng thẳng."] },
    { word: "dot", phonetic: "/dɑːt/", def: "A small round mark or spot.", defVn: "chấm tròn, điểm nhỏ", pos: "noun", ex: ["She wore a dress with polka dots.", "Put a dot at end of sentence."], exVn: ["Cô ấy mặc váy chấm bi.", "Đặt dấu chấm ở cuối câu."] },
    { word: "stripe", phonetic: "/straɪp/", def: "A long narrow band differing in color.", defVn: "sọc kẻ, vạch kẻ", pos: "noun", ex: ["A zebra has black and white stripes.", "He wore a shirt with blue stripes."], exVn: ["Ngựa vằn có sọc đen và trắng.", "Anh ấy mặc áo sơ mi sọc xanh."] },
    { word: "pattern", phonetic: "/ˈpætərn/", def: "A repeated decorative design.", defVn: "hoa văn, họa tiết lặp lại", pos: "noun", ex: ["I love the geometric pattern on rug.", "Traditional scarves have floral patterns."], exVn: ["Tôi thích họa tiết hình học trên tấm thảm.", "Khăn quàng truyền thống có hoa văn hoa lá."] },
    { word: "cube", phonetic: "/kjuːb/", def: "A symmetrical three-dimensional shape with six equal square faces.", defVn: "hình lập phương, khối vuông", pos: "noun", ex: ["Put an ice cube into the glass of lemonade.", "Solve the colorful Rubik's cube."], exVn: ["Thả một viên đá lạnh vào ly nước chanh.", "Giải khối Rubik đầy màu sắc."] },
    { word: "cone", phonetic: "/koʊn/", def: "A solid shape that tapers smoothly from a circular base to a point.", defVn: "hình nón, cây kem ốc quế", pos: "noun", ex: ["I ordered an ice cream cone.", "Traffic cones mark the road work."], exVn: ["Tôi đã gọi một cây kem ốc quế.", "Những chiếc cọc tiêu hình nón đánh dấu đoạn đường thi công."] },
    { word: "cylinder", phonetic: "/ˈsɪlɪndər/", def: "A solid geometric figure with straight parallel sides and a circular section.", defVn: "hình trụ, khối trụ", pos: "noun", ex: ["A can of soda has the shape of a cylinder.", "The architectural pillars are tall cylinders."], exVn: ["Lon nước ngọt có hình trụ.", "Những cây cột kiến trúc là những khối trụ cao lớn."] },
    { word: "curve", phonetic: "/kɜːrv/", def: "A line or outline which gradually deviates from being straight.", defVn: "đường cong, khúc cua", pos: "noun", ex: ["Slow down around the sharp road curve.", "Her lips formed a gentle curve of a smile."], exVn: ["Hãy đi chậm lại quanh khúc cua gắt trên đường.", "Khóe môi cô ấy nở nụ cười cong nhẹ nhàng."] },
    { word: "angle", phonetic: "/ˈæŋɡl/", def: "The space between two intersecting lines measured in degrees.", defVn: "góc (hình học), góc nhìn", pos: "noun", ex: ["A right angle measures 90 degrees.", "Take a photo from this creative angle."], exVn: ["Góc vuông có số đo 90 độ.", "Chụp bức ảnh từ góc sáng tạo này nhé."] }
  ],

  // Theme 5: Gia đình & Người thân
  t_basic_family: [
    { word: "nephew", phonetic: "/ˈnefjuː/", def: "The son of one's brother or sister.", defVn: "cháu trai (con của anh/chị/em)", pos: "noun", ex: ["My nephew is starting kindergarten today.", "I bought a toy car for my nephew."], exVn: ["Cháu trai tôi bắt đầu đi mẫu giáo hôm nay.", "Tôi mua ô tô đồ chơi cho cháu trai."] },
    { word: "niece", phonetic: "/niːs/", def: "The daughter of one's brother or sister.", defVn: "cháu gái (con của anh/chị/em)", pos: "noun", ex: ["My niece loves dancing and singing.", "She sent a birthday card to her niece."], exVn: ["Cháu gái tôi rất thích múa hát.", "Cô ấy gửi thiệp sinh nhật cho cháu gái."] },
    { word: "twins", phonetic: "/twɪnz/", def: "Two children born at the same birth.", defVn: "cặp song sinh, sinh đôi", pos: "noun", ex: ["They are identical twins with bright smiles.", "The twins wear matching clothes."], exVn: ["Họ là cặp sinh đôi với nụ cười rạng rỡ.", "Cặp song sinh mặc đồ giống nhau."] },
    { word: "household", phonetic: "/ˈhaʊshoʊld/", def: "A house and occupants regarded as a unit.", defVn: "hộ gia đình, gia quyến", pos: "noun", ex: ["He manages household expenses carefully.", "There are four people in our household."], exVn: ["Anh ấy quản lý chi tiêu gia đình cẩn thận.", "Hộ gia đình chúng tôi có bốn người."] },
    { word: "ancestor", phonetic: "/ˈænsestər/", def: "A person from whom one is descended.", defVn: "tổ tiên, ông bà tổ tiên", pos: "noun", ex: ["We honor ancestors during festivals.", "Our ancestors built this historic village."], exVn: ["Chúng tôi tưởng nhớ tổ tiên trong dịp lễ.", "Tổ tiên chúng tôi đã xây dựng ngôi làng này."] },
    { word: "relative", phonetic: "/ˈrelətɪv/", def: "A person connected by blood or marriage.", defVn: "họ hàng, người thân thích", pos: "noun", ex: ["All our relatives gathered for Tet.", "She visited relatives in Da Nang."], exVn: ["Họ hàng tụ họp đông đủ dịp Tết.", "Cô ấy đến thăm người thân ở Đà Nẵng."] },
    { word: "stepfather", phonetic: "/ˈstepfɑːðər/", def: "A man who is married to one's mother after the divorce or death of one's father.", defVn: "cha dượng", pos: "noun", ex: ["His stepfather is very supportive and kind.", "He has a great relationship with his stepfather."], exVn: ["Cha dượng của anh ấy rất tốt bụng và luôn ủng hộ anh.", "Anh ấy có mối quan hệ rất tốt với cha dượng."] },
    { word: "stepmother", phonetic: "/ˈstepmʌðər/", def: "A woman who is married to one's father after the divorce or death of one's mother.", defVn: "mẹ kế, mẹ ghẻ", pos: "noun", ex: ["Her stepmother helped her with school projects.", "She gets along well with her stepmother."], exVn: ["Mẹ kế đã giúp cô ấy làm bài tập trường học.", "Cô ấy rất hòa thuận với mẹ kế của mình."] },
    { word: "in-laws", phonetic: "/ˈɪn lɔːz/", def: "Relatives by marriage, especially the parents of one's spouse.", defVn: "gia đình bên chồng / bên vợ", pos: "noun", ex: ["We are having Sunday lunch with my in-laws.", "Her in-laws are very warm and welcoming."], exVn: ["Chúng tôi ăn trưa Chủ Nhật cùng nhà thông gia/nhà chồng.", "Gia đình bên chồng của cô ấy rất ấm áp và hiếu khách."] },
    { word: "grandson", phonetic: "/ˈɡrænsʌn/", def: "A son of one's son or daughter.", defVn: "cháu trai (của ông bà)", pos: "noun", ex: ["The grandfather plays chess with his grandson.", "Their grandson is in university."], exVn: ["Người ông chơi cờ vua với cháu trai.", "Cháu trai của họ đang học đại học."] },
    { word: "granddaughter", phonetic: "/ˈɡrændɔːtər/", def: "A daughter of one's son or daughter.", defVn: "cháu gái (của ông bà)", pos: "noun", ex: ["Grandmother knitted a warm scarf for her granddaughter.", "She loves hugging her granddaughter."], exVn: ["Bà đan một chiếc khăn ấm cho cháu gái.", "Bà rất thích ôm đứa cháu gái nhỏ."] }
  ],

  // Theme 6: Nhà cửa & Đồ dùng
  t_basic_home_objects: [
    { word: "cushion", phonetic: "/ˈkʊʃn/", def: "A soft pillow or pad for sitting.", defVn: "đệm ngồi, gối tựa lưng", pos: "noun", ex: ["She placed soft cushions on sofa.", "Sit on floor cushion for comfort."], exVn: ["Cô ấy đặt gối tựa êm ái lên ghế sô-pha.", "Ngồi lên đệm sàn để thấy thoải mái."] },
    { word: "blanket", phonetic: "/ˈblæŋkɪt/", def: "A large piece of warm fabric covering.", defVn: "chiếc chăn ấm, mền", pos: "noun", ex: ["Wrap yourself in a warm blanket.", "She folded the woolen blanket neatly."], exVn: ["Trùm chiếc chăn ấm vào những đêm lạnh.", "Cô ấy gấp chiếc chăn len gọn gàng."] },
    { word: "carpet", phonetic: "/ˈkɑːrpɪt/", def: "A floor covering of thick woven fabric.", defVn: "tấm thảm trải sàn lớn", pos: "noun", ex: ["A soft carpet covers the room floor.", "Take off shoes before stepping on carpet."], exVn: ["Tấm thảm mềm trải khắp sàn phòng.", "Cởi giày trước khi bước lên thảm."] },
    { word: "curtain", phonetic: "/ˈkɜːrtn/", def: "Cloth used to block light from window.", defVn: "rèm cửa sổ, màn che", pos: "noun", ex: ["Open curtains to let sunlight in.", "She drew the curtains when night fell."], exVn: ["Mở rèm cửa đón ánh nắng vào phòng.", "Cô ấy kéo rèm lại khi đêm xuống."] },
    { word: "wardrobe", phonetic: "/ˈwɔːrdroʊb/", def: "A tall cupboard in which clothes are hung.", defVn: "tủ quần áo", pos: "noun", ex: ["Hang winter coats in wardrobe.", "She organized clothes inside wardrobe."], exVn: ["Treo áo khoác vào tủ quần áo.", "Cô ấy sắp xếp quần áo trong tủ."] },
    { word: "drawer", phonetic: "/drɔːr/", def: "A sliding compartment in furniture.", defVn: "ngăn kéo bàn / tủ", pos: "noun", ex: ["Keep keys in top drawer.", "He opened desk drawer to take a pen."], exVn: ["Giữ chìa khóa trong ngăn kéo trên cùng.", "Anh ấy mở ngăn kéo bàn lấy cây bút."] },
    { word: "vase", phonetic: "/veɪs/", def: "A container for holding cut flowers.", defVn: "lọ hoa, bình cắm hoa", pos: "noun", ex: ["A vase filled with fresh red roses.", "Be careful with the ceramic vase."], exVn: ["Bình hoa cắm đầy hoa hồng đỏ tươi.", "Cẩn thận với chiếc bình gốm cắm hoa."] },
    { word: "trash can", phonetic: "/træʃ kæn/", def: "A container for household waste.", defVn: "thùng rác gia đình", pos: "noun", ex: ["Throw the box into trash can.", "Please empty the kitchen trash can."], exVn: ["Vứt chiếc hộp vào thùng rác.", "Làm ơn đổ thùng rác nhà bếp."] },
    { word: "balcony", phonetic: "/ˈbælkəni/", def: "An outside platform on a building.", defVn: "ban công nhà", pos: "noun", ex: ["We drink coffee on the sunny balcony.", "She grows flowers on her balcony."], exVn: ["Chúng tôi uống cà phê trên ban công đầy nắng.", "Cô ấy trồng hoa ở ban công."] },
    { word: "ceiling", phonetic: "/ˈsiːlɪŋ/", def: "The upper interior surface of a room.", defVn: "trần nhà", pos: "noun", ex: ["A fan hangs from high ceiling.", "The living room ceiling is white."], exVn: ["Chiếc quạt treo trên trần nhà cao.", "Trần phòng khách được sơn màu trắng."] },
    { word: "bookshelf", phonetic: "/ˈbʊkʃelf/", def: "A piece of furniture with horizontal shelves for storing books.", defVn: "giá sách, kệ sách", pos: "noun", ex: ["The bookshelf is filled with English storybooks.", "Keep your dictionary on the bookshelf."], exVn: ["Kệ sách đầy ắp truyện tiếng Anh.", "Để cuốn từ điển trên giá sách nhé."] },
    { word: "pillow", phonetic: "/ˈpɪloʊ/", def: "A rectangular cloth bag filled with soft material for resting the head on in bed.", defVn: "cái gối đầu", pos: "noun", ex: ["Rest your head on this soft feather pillow.", "She adjusted her pillow for better sleep."], exVn: ["Tựa đầu lên chiếc gối lông vũ êm ái này.", "Cô ấy chỉnh lại gối để ngủ ngon hơn."] },
    { word: "mirror", phonetic: "/ˈmɪrər/", def: "A reflective surface, now typically of glass coated with a metal amalgam.", defVn: "gương soi", pos: "noun", ex: ["She checked her outfit in the full-length mirror.", "The bathroom mirror is clear and clean."], exVn: ["Cô ấy ngắm lại trang phục trong chiếc gương toàn thân.", "Gương phòng tắm rất trong và sạch sẽ."] },
    { word: "lamp", phonetic: "/læmp/", def: "A device for giving light, especially one consisting of an electric bulb.", defVn: "đèn bàn, đèn ngủ", pos: "noun", ex: ["Turn on the study lamp when reading at night.", "A bedside lamp gives off a soft glow."], exVn: ["Bật đèn học khi đọc sách ban đêm nhé.", "Chiếc đèn ngủ đầu giường tỏa ánh sáng dịu nhẹ."] },
    { word: "clock", phonetic: "/klɑːk/", def: "An instrument to measure and indicate time.", defVn: "đồng hồ treo tường / để bàn", pos: "noun", ex: ["The clock on the wall ticks quietly.", "Look at the clock; it is time for dinner."], exVn: ["Chiếc đồng hồ trên tường kêu tích tắc êm đềm.", "Nhìn đồng hồ xem, đến giờ ăn tối rồi."] }
  ],

  // Theme 7: Động từ hàng ngày
  t_basic_daily_verbs: [
    { word: "cook", phonetic: "/kʊk/", def: "To prepare food by combining and heating ingredients.", defVn: "nấu ăn, chế biến món ăn", pos: "verb", ex: ["My mom cooks dinner every evening.", "He is learning to cook Italian pasta."], exVn: ["Mẹ tôi nấu bữa tối mỗi buổi chiều.", "Anh ấy đang học nấu món mì Ý."] },
    { word: "clean", phonetic: "/kliːn/", def: "To make something free of dirt and clutter.", defVn: "dọn dẹp, lau chùi sạch sẽ", pos: "verb", ex: ["I clean my bedroom every Saturday.", "Please clean your hands before eating."], exVn: ["Tôi dọn phòng ngủ vào mỗi thứ Bảy.", "Làm ơn rửa sạch tay trước khi ăn."] },
    { word: "study", phonetic: "/ˈstʌdi/", def: "To devote time and attention to acquiring knowledge.", defVn: "học tập, nghiên cứu bài học", pos: "verb", ex: ["We study English for an hour daily.", "She is studying hard for the final exam."], exVn: ["Chúng tôi học tiếng Anh một tiếng mỗi ngày.", "Cô ấy đang học chăm chỉ cho kỳ thi cuối kỳ."] },
    { word: "play", phonetic: "/pleɪ/", def: "To engage in activity for enjoyment.", defVn: "chơi đùa, chơi thể thao/nhạc cụ", pos: "verb", ex: ["Children play football in the park.", "He plays the acoustic guitar very well."], exVn: ["Trẻ em chơi bóng đá trong công viên.", "Anh ấy chơi đàn ghi-ta rất hay."] },
    { word: "watch", phonetic: "/wɑːtʃ/", def: "To look at or observe attentively over time.", defVn: "xem, theo dõi (phim, TV, trận đấu)", pos: "verb", ex: ["Let's watch a movie together tonight.", "They watch the soccer match on television."], exVn: ["Tối nay chúng ta cùng xem phim nhé.", "Họ xem trận bóng đá trên truyền hình."] },
    { word: "listen", phonetic: "/ˈlɪsn/", def: "To give attention to sound or action.", defVn: "lắng nghe, nghe nhạc", pos: "verb", ex: ["Listen carefully to the teacher's instructions.", "I love listening to acoustic music."], exVn: ["Hãy lắng nghe kỹ chỉ dẫn của giáo viên.", "Tôi rất thích nghe nhạc acoustic."] },
    { word: "buy", phonetic: "/baɪ/", def: "To obtain in exchange for payment.", defVn: "mua sắm hàng hóa", pos: "verb", ex: ["I need to buy some fresh vegetables.", "She bought a new dress for the party."], exVn: ["Tôi cần mua một ít rau tươi.", "Cô ấy đã mua chiếc váy mới cho bữa tiệc."] },
    { word: "sell", phonetic: "/sel/", def: "To give something in exchange for money.", defVn: "bán hàng, bán đi", pos: "verb", ex: ["The local market sells fresh fruit.", "He decided to sell his old bicycle."], exVn: ["Khu chợ địa phương bán trái cây tươi.", "Anh ấy quyết định bán chiếc xe đạp cũ."] },
    { word: "help", phonetic: "/help/", def: "To make it easier for someone to do something.", defVn: "giúp đỡ, trợ giúp", pos: "verb", ex: ["Can you help me carry this heavy bag?", "Thank you for helping me with my homework."], exVn: ["Bạn giúp tôi xách chiếc túi nặng này được không?", "Cảm ơn bạn đã giúp tôi làm bài tập."] },
    { word: "wait", phonetic: "/weɪt/", def: "To stay where one is until an expected event.", defVn: "chờ đợi, đợi một chút", pos: "verb", ex: ["Please wait for me at the bus stop.", "We waited for thirty minutes."], exVn: ["Làm ơn đợi tôi ở trạm xe buýt nhé.", "Chúng tôi đã chờ trong ba mươi phút."] },
    { word: "call", phonetic: "/kɔːl/", def: "To telephone someone or cry out loud.", defVn: "gọi điện thoại, gọi tên", pos: "verb", ex: ["I will call you when I arrive at the hotel.", "She called her best friend to chat."], exVn: ["Tôi sẽ gọi cho bạn khi đến khách sạn.", "Cô ấy đã gọi điện cho bạn thân để trò chuyện."] },
    { word: "send", phonetic: "/send/", def: "To cause to go or be taken to a particular destination.", defVn: "gửi đi (thư, tin nhắn, email)", pos: "verb", ex: ["Send me an email with the attached document.", "I sent a birthday postcard to my aunt."], exVn: ["Hãy gửi email kèm tài liệu đính kèm cho tôi nhé.", "Tôi đã gửi tấm bưu thiếp sinh nhật cho dì."] },
    { word: "receive", phonetic: "/rɪˈsiːv/", def: "To be given, presented with, or paid.", defVn: "nhận được, tiếp nhận", pos: "verb", ex: ["Did you receive my text message?", "She received a lovely gift from her parents."], exVn: ["Bạn đã nhận được tin nhắn của tôi chưa?", "Cô ấy nhận được món quà đáng yêu từ cha mẹ."] },
    { word: "open", phonetic: "/ˈoʊpən/", def: "To move so as to allow access; unlock.", defVn: "mở ra (cửa, sách, hộp)", pos: "verb", ex: ["Please open the window to let fresh air in.", "Open your notebook to page 10."], exVn: ["Làm ơn mở cửa sổ đón gió trong lành nhé.", "Mở vở ghi chép trang số 10 đi nào."] },
    { word: "close", phonetic: "/kloʊz/", def: "To move into position so as to block an opening.", defVn: "đóng lại, khép lại", pos: "verb", ex: ["Close the door gently when leaving.", "The bookstore closes at 9 PM."], exVn: ["Hãy đóng cửa nhẹ nhàng khi rời đi nhé.", "Hiệu sách đóng cửa lúc 9 giờ tối."] }
  ],

  // Theme 8: Ăn uống & Thực phẩm
  t_basic_food_drinks: [
    { word: "coffee", phonetic: "/ˈkɔːfi/", def: "A popular hot beverage made from roasted beans.", defVn: "cà phê", pos: "noun", ex: ["I drink a cup of black coffee every morning.", "Vietnamese iced coffee is famous worldwide."], exVn: ["Tôi uống một tách cà phê đen mỗi sáng.", "Cà phê sữa đá Việt Nam nổi tiếng khắp thế giới."] },
    { word: "juice", phonetic: "/dʒuːs/", def: "The liquid naturally contained in fruit or vegetables.", defVn: "nước ép hoa quả", pos: "noun", ex: ["Fresh orange juice is rich in vitamin C.", "Would you like apple juice or watermelon juice?"], exVn: ["Nước cam tươi rất giàu vitamin C.", "Bạn muốn uống nước ép táo hay dưa hấu?"] },
    { word: "cheese", phonetic: "/tʃiːz/", def: "A dairy food made from pressed curds of milk.", defVn: "phô mai, pho-mát", pos: "noun", ex: ["Pizza with extra melted cheese tastes amazing.", "She sliced some cheddar cheese for breakfast."], exVn: ["Bánh pizza thêm nhiều phô mai tan chảy rất ngon.", "Cô ấy cắt vài lát phô mai cho bữa sáng."] },
    { word: "butter", phonetic: "/ˈbʌtər/", def: "A pale yellow fatty food made by churning milk.", defVn: "bơ sữa", pos: "noun", ex: ["Spread butter on warm toast.", "Melt butter in the pan before cooking."], exVn: ["Phết bơ lên bánh mì nướng nóng hổi.", "Làm tan chảy bơ trong chảo trước khi nấu."] },
    { word: "soup", phonetic: "/suːp/", def: "A liquid dish prepared by boiling meat and vegetables.", defVn: "món súp, món canh", pos: "noun", ex: ["Hot chicken soup warms you up in winter.", "She cooked a bowl of vegetable soup."], exVn: ["Bát súp gà nóng hổi làm ấm người vào mùa đông.", "Cô ấy nấu một bát canh rau củ."] },
    { word: "salad", phonetic: "/ˈsæləd/", def: "A cold dish of fresh raw vegetables.", defVn: "món rau trộn xa-lát", pos: "noun", ex: ["Eating green salad daily is great for health.", "She ordered a fresh Caesar salad."], exVn: ["Ăn xa-lát rau xanh mỗi ngày rất tốt cho sức khỏe.", "Cô ấy gọi món xa-lát Caesar tươi ngon."] },
    { word: "sugar", phonetic: "/ˈʃʊɡər/", def: "A sweet crystalline substance obtained from cane.", defVn: "đường ngọt", pos: "noun", ex: ["Do you take sugar in your hot tea?", "Too much sugar is not good for your teeth."], exVn: ["Bạn có dùng đường trong trà nóng không?", "Quá nhiều đường không tốt cho răng miệng."] },
    { word: "salt", phonetic: "/sɔːlt/", def: "A white crystalline seasoning for flavoring food.", defVn: "muối ăn", pos: "noun", ex: ["Pass the salt shaker, please.", "Add a pinch of salt to the soup."], exVn: ["Làm ơn chuyển giúp tôi lọ muối.", "Thêm một nhúm muối nhỏ vào nồi canh."] },
    { word: "noodle", phonetic: "/ˈnuːdl/", def: "A strip, ring, or tube of pasta.", defVn: "mì sợi, bún phở", pos: "noun", ex: ["Vietnamese beef noodle soup is called pho.", "He cooked instant noodles for a late snack."], exVn: ["Món phở bò sợi truyền thống của Việt Nam.", "Anh ấy nấu mì ăn liền cho bữa ăn đêm."] },
    { word: "pork", phonetic: "/pɔːrk/", def: "The meat of a pig used as food.", defVn: "thịt lợn, thịt heo", pos: "noun", ex: ["Grilled pork with rice noodles is delicious.", "She bought lean pork at the market."], exVn: ["Bún chả thịt heo nướng rất thơm ngon.", "Cô ấy mua thịt heo nạc ở chợ."] },
    { word: "beef", phonetic: "/biːf/", def: "The culinary name for meat from cattle.", defVn: "thịt bò", pos: "noun", ex: ["A tender beef steak served with pepper sauce.", "Beef pho is my all-time favorite meal."], exVn: ["Miếng bít tết thịt bò mềm ăn kèm sốt tiêu.", "Phở bò là món ăn yêu thích nhất mọi thời đại của tôi."] },
    { word: "chicken", phonetic: "/ˈtʃɪkɪn/", def: "A domestic fowl kept for its eggs or meat.", defVn: "thịt gà, con gà", pos: "noun", ex: ["Crispy fried chicken is popular among children.", "Mom cooked a whole chicken soup."], exVn: ["Gà rán giòn rụm rất được trẻ em yêu thích.", "Mẹ đã nấu một nồi súp gà nguyên con."] },
    { word: "fish", phonetic: "/fɪʃ/", def: "A limbless cold-blooded vertebrate animal with gills living in water.", defVn: "cá, món cá", pos: "noun", ex: ["Steamed fish with ginger is healthy and light.", "Eating fish twice a week is good for your heart."], exVn: ["Cá hấp gừng rất thanh đạm và bổ dưỡng.", "Ăn cá hai lần một tuần rất tốt cho tim mạch."] },
    { word: "vegetable", phonetic: "/ˈvedʒtəbl/", def: "A plant or part of a plant used as food.", defVn: "rau củ tươi", pos: "noun", ex: ["Eat fresh green vegetables for strong immunity.", "The market sells organic vegetables."], exVn: ["Hãy ăn rau xanh tươi để tăng sức đề kháng.", "Khu chợ bán các loại rau hữu cơ sạch."] },
    { word: "fruit", phonetic: "/fruːt/", def: "The sweet and fleshy product of a tree or plant containing seeds.", defVn: "trái cây, hoa quả", pos: "noun", ex: ["Tropical fruits like mango and papaya are sweet.", "Always wash fruit before eating."], exVn: ["Các loại hoa quả nhiệt đới như xoài và đu đủ rất ngọt.", "Luôn rửa sạch hoa quả trước khi ăn nhé."] }
  ],

  // Theme 9: Cảm xúc & Tính từ
  t_basic_emotions_adjectives: [
    { word: "excited", phonetic: "/ɪkˈsaɪtɪd/", def: "Very enthusiastic and eager.", defVn: "hào hứng, phấn khích", pos: "adj", ex: ["The children are excited about the holiday trip.", "I am so excited to meet my favorite singer."], exVn: ["Lũ trẻ rất hào hứng về chuyến du lịch nghỉ lễ.", "Tôi vô cùng phấn khích khi được gặp ca sĩ yêu thích."] },
    { word: "bored", phonetic: "/bɔːrd/", def: "Feeling weary and restless through lack of interest.", defVn: "buồn chán, tẻ nhạt", pos: "adj", ex: ["He felt bored during the long meeting.", "The movie was so slow that I got bored."], exVn: ["Anh ấy cảm thấy buồn chán trong cuộc họp dài.", "Bộ phim quá chậm khiến tôi thấy chán ngắt."] },
    { word: "nervous", phonetic: "/ˈnɜːrvəs/", def: "Easily agitated or alarmed; anxious.", defVn: "lo lắng, hồi hộp, bồn chồn", pos: "adj", ex: ["She felt nervous before the job interview.", "Take a deep breath if you feel nervous."], exVn: ["Cô ấy cảm thấy hồi hộp trước buổi phỏng vấn xin việc.", "Hãy hít thở sâu nếu bạn cảm thấy lo lắng."] },
    { word: "calm", phonetic: "/kɑːm/", def: "Not showing or feeling nervousness or anger.", defVn: "bình tĩnh, điềm đạm, êm ả", pos: "adj", ex: ["Stay calm and follow the emergency instructions.", "The sea was very calm and peaceful this morning."], exVn: ["Hãy giữ bình tĩnh và làm theo chỉ dẫn khẩn cấp.", "Biển sáng nay rất êm ả và thanh bình."] },
    { word: "proud", phonetic: "/praʊd/", def: "Feeling deep satisfaction from achievements.", defVn: "tự hào, hãnh diện", pos: "adj", ex: ["Her parents were very proud of her graduation.", "I am proud of my progress in English."], exVn: ["Bố mẹ rất tự hào về ngày lễ tốt nghiệp của cô ấy.", "Tôi tự hào về sự tiến bộ tiếng Anh của mình."] },
    { word: "scared", phonetic: "/skerd/", def: "Fearful; frightened.", defVn: "sợ hãi, khiếp sợ", pos: "adj", ex: ["The little boy was scared of the dark.", "Don't be scared; the dog is friendly."], exVn: ["Cậu bé sợ bóng tối.", "Đừng sợ; chú chó này rất thân thiện."] },
    { word: "shy", phonetic: "/ʃaɪ/", def: "Being reserved or having or showing nervousness.", defVn: "nhút nhát, e thẹn, ngại ngùng", pos: "adj", ex: ["He was too shy to speak in front of the crowd.", "The new student smiled shyly at the class."], exVn: ["Cậu ấy quá nhút nhát để nói trước đám đông.", "Học sinh mới cười e thẹn trước cả lớp."] },
    { word: "confident", phonetic: "/ˈkɑːnfɪdənt/", def: "Feeling or showing certainty about something.", defVn: "tự tin, chắc chắn", pos: "adj", ex: ["She is confident about passing the English exam.", "A confident smile makes a great first impression."], exVn: ["Cô ấy tự tin sẽ thi đỗ kỳ thi tiếng Anh.", "Nụ cười tự tin tạo ấn tượng đầu tiên tuyệt vời."] },
    { word: "busy", phonetic: "/ˈbɪzi/", def: "Having a great deal to do.", defVn: "bận rộn, tấp nập", pos: "adj", ex: ["I am very busy with work this week.", "The city streets are always busy at rush hour."], exVn: ["Tuần này tôi rất bận rộn với công việc.", "Đường phố luôn tấp nập vào giờ cao điểm."] },
    { word: "lazy", phonetic: "/ˈleɪzi/", def: "Unwilling to work or use energy.", defVn: "lười biếng, lười nhác", pos: "adj", ex: ["He spent a lazy Sunday lying on the sofa.", "Don't be lazy; practice English every day."], exVn: ["Anh ấy trải qua ngày Chủ Nhật lười biếng nằm dài trên ghế.", "Đừng lười biếng; hãy luyện tiếng Anh mỗi ngày."] },
    { word: "lonely", phonetic: "/ˈloʊnli/", def: "Sad because one has no friends or company.", defVn: "cô đơn, cô độc", pos: "adj", ex: ["He felt lonely living alone in a big city.", "Adopt a pet if you feel lonely at home."], exVn: ["Anh ấy cảm thấy cô đơn khi sống một mình ở thành phố lớn.", "Hãy nuôi thú cưng nếu bạn thấy cô đơn ở nhà."] },
    { word: "grateful", phonetic: "/ˈɡreɪtfl/", def: "Feeling or showing an appreciation of kindness.", defVn: "biết ơn, cảm kích", pos: "adj", ex: ["I am deeply grateful for your generous help.", "Be grateful for every sunrise."], exVn: ["Tôi vô cùng biết ơn sự giúp đỡ hào phóng của bạn.", "Hãy biết ơn mỗi sớm mai thức dậy."] },
    { word: "generous", phonetic: "/ˈdʒenərəs/", def: "Showing a readiness to give more of something.", defVn: "hào phóng, rộng lượng", pos: "adj", ex: ["He made a generous donation to the charity.", "She is always generous with her time."], exVn: ["Ông ấy đã quyên góp hào phóng cho hội từ thiện.", "Cô ấy luôn sẵn lòng dành thời gian giúp đỡ mọi người."] },
    { word: "curious", phonetic: "/ˈkjʊriəs/", def: "Eager to know or learn something.", defVn: "tò mò, hiếu kỳ, ham học hỏi", pos: "adj", ex: ["Children are naturally curious about everything.", "I was curious to know what was in the box."], exVn: ["Trẻ con tự nhiên rất hiếu kỳ về mọi điều xung quanh.", "Tôi tò mò muốn biết có gì trong chiếc hộp."] },
    { word: "patient", phonetic: "/ˈpeɪʃnt/", def: "Able to accept or tolerate delays without becoming annoyed.", defVn: "kiên nhẫn, nhẫn nại", pos: "adj", ex: ["A good teacher is always patient with students.", "Be patient; good things take time."], exVn: ["Một giáo viên giỏi luôn kiên nhẫn với học trò.", "Hãy kiên nhẫn; những điều tuyệt vời cần có thời gian."] }
  ],

  // Theme 10: Thời gian & Lịch
  t_basic_time_calendar: [
    { word: "morning", phonetic: "/ˈmɔːrnɪŋ/", def: "The period of time between midnight and noon.", defVn: "buổi sáng", pos: "noun", ex: ["I jog around the lake every morning.", "Morning sunlight is warm and fresh."], exVn: ["Tôi chạy bộ quanh hồ vào mỗi buổi sáng.", "Ánh nắng ban mai ấm áp và trong lành."] },
    { word: "afternoon", phonetic: "/ˌæftərˈnuːn/", def: "The time from noon or lunchtime to evening.", defVn: "buổi chiều", pos: "noun", ex: ["We have a team meeting in the afternoon.", "She loves taking an afternoon nap."], exVn: ["Chúng tôi có buổi họp nhóm vào buổi chiều.", "Cô ấy thích có một giấc ngủ trưa nhẹ."] },
    { word: "evening", phonetic: "/ˈiːvnɪŋ/", def: "The period of time at the end of the day.", defVn: "buổi tối", pos: "noun", ex: ["We enjoy family dinner in the evening.", "The city looks gorgeous in the evening."], exVn: ["Chúng tôi thưởng thức bữa cơm gia đình vào buổi tối.", "Thành phố trông tuyệt đẹp vào ban đêm."] },
    { word: "night", phonetic: "/naɪt/", def: "The period of darkness in each twenty-four hours.", defVn: "ban đêm, buổi đêm", pos: "noun", ex: ["The stars shine brightly in the night sky.", "Good night, have sweet dreams!"], exVn: ["Các vì sao tỏa sáng lấp lánh trên bầu trời đêm.", "Chúc ngủ ngon, mơ những giấc mơ đẹp nhé!"] },
    { word: "spring", phonetic: "/sprɪŋ/", def: "The season after winter and before summer.", defVn: "mùa xuân", pos: "noun", ex: ["Flowers bloom beautifully in spring.", "Spring is the season of new beginnings."], exVn: ["Hoa nở rực rỡ vào mùa xuân.", "Mùa xuân là mùa của những khởi đầu mới."] },
    { word: "summer", phonetic: "/ˈsʌmər/", def: "The warmest season of the year.", defVn: "mùa hè, mùa hạ", pos: "noun", ex: ["We go swimming at the beach in summer.", "Summer vacation lasts for two months."], exVn: ["Chúng tôi đi bơi ở bãi biển vào mùa hè.", "Kỳ nghỉ hè kéo dài trong hai tháng."] },
    { word: "autumn", phonetic: "/ˈɔːtəm/", def: "The season between summer and winter; fall.", defVn: "mùa thu", pos: "noun", ex: ["Leaves turn golden and red in autumn.", "Autumn weather in Hanoi is cool and romantic."], exVn: ["Lá cây chuyển sang màu vàng và đỏ vào mùa thu.", "Thời tiết mùa thu ở Hà Nội mát mẻ và lãng mạn."] },
    { word: "winter", phonetic: "/ˈwɪntər/", def: "The coldest season of the year.", defVn: "mùa đông", pos: "noun", ex: ["Wear a warm jacket during cold winter.", "Snow covers the mountain in winter."], exVn: ["Hãy mặc áo ấm trong mùa đông lạnh giá.", "Tuyết phủ trắng ngọn núi vào mùa đông."] },
    { word: "clock", phonetic: "/klɑːk/", def: "An instrument to measure and indicate time.", defVn: "đồng hồ treo tường / để bàn", pos: "noun", ex: ["The wall clock says exactly three o'clock.", "Set the alarm clock for 6 AM."], exVn: ["Đồng hồ treo tường chỉ đúng 3 giờ.", "Đặt chuông báo thức lúc 6 giờ sáng."] },
    { word: "calendar", phonetic: "/ˈkælɪndər/", def: "A chart showing the days, weeks, and months.", defVn: "tờ lịch, cuốn lịch", pos: "noun", ex: ["Check the calendar for upcoming holidays.", "I marked your birthday on my calendar."], exVn: ["Kiểm tra lịch để biết các ngày nghỉ lễ sắp tới.", "Tôi đã đánh dấu ngày sinh nhật bạn trên lịch."] },
    { word: "midnight", phonetic: "/ˈmɪdnaɪt/", def: "Twelve o'clock at night.", defVn: "nửa đêm (12h đêm)", pos: "noun", ex: ["Fireworks illuminated the sky at midnight on New Year's Eve.", "He often studies until midnight."], exVn: ["Pháo hoa thắp sáng bầu trời lúc nửa đêm giao thừa.", "Anh ấy thường học bài đến tận nửa đêm."] },
    { word: "noon", phonetic: "/nuːn/", def: "Twelve o'clock in the middle of the day.", defVn: "buổi trưa (12h trưa)", pos: "noun", ex: ["Let's meet for lunch at noon.", "The sun is directly overhead at noon."], exVn: ["Chúng ta hãy gặp nhau ăn trưa lúc 12 giờ trưa nhé.", "Mặt trời chiếu thẳng đứng vào buổi trưa."] },
    { word: "century", phonetic: "/ˈsentʃəri/", def: "A period of one hundred years.", defVn: "thế kỷ (100 năm)", pos: "noun", ex: ["We live in the twenty-first century.", "This ancient temple was built a century ago."], exVn: ["Chúng ta đang sống ở thế kỷ hai mươi mốt.", "Ngôi đền cổ này được xây dựng cách đây một thế kỷ."] },
    { word: "decade", phonetic: "/ˈdekeɪd/", def: "A period of ten years.", defVn: "thập kỷ (10 năm)", pos: "noun", ex: ["Technology has advanced rapidly over the past decade.", "They lived in London for over a decade."], exVn: ["Công nghệ đã phát triển nhanh chóng trong thập kỷ qua.", "Họ đã sống ở Luân Đôn hơn một thập kỷ."] },
    { word: "weekend", phonetic: "/ˈwiːkend/", def: "Saturday and Sunday, especially regarded as a time for leisure.", defVn: "ngày cuối tuần (thứ Bảy & Chủ Nhật)", pos: "noun", ex: ["What are your plans for this weekend?", "We love going on family picnics on weekends."], exVn: ["Kế hoạch cuối tuần này của bạn là gì?", "Chúng tôi rất thích đi dã ngoại gia đình vào cuối tuần."] }
  ],

  // Theme 11: Động vật quen thuộc
  t_basic_animals: [
    { word: "rabbit", phonetic: "/ˈræbɪt/", def: "A burrowing plant-eating mammal with long ears and fluffy tail.", defVn: "con thỏ", pos: "noun", ex: ["The white rabbit hopped across the green lawn.", "Rabbits love eating fresh carrots."], exVn: ["Chú thỏ trắng nhảy thoăn thoắt qua bãi cỏ xanh.", "Thỏ rất thích ăn cà rốt tươi."] },
    { word: "horse", phonetic: "/hɔːrs/", def: "A large plant-eating domesticated mammal with hooves and a flowing mane.", defVn: "con ngựa", pos: "noun", ex: ["She learned how to ride a horse at the ranch.", "The wild horses galloped freely across plains."], exVn: ["Cô ấy đã học cách cưỡi ngựa tại trang trại.", "Đàn ngựa hoang phi nước đại tự do trên đồng cỏ."] },
    { word: "cow", phonetic: "/kaʊ/", def: "A fully grown female animal of a domesticated bovine species.", defVn: "con bò sữa, con bò cái", pos: "noun", ex: ["Dairy cows graze on green pasture every day.", "Cows provide rich and nutritious milk."], exVn: ["Những chú bò sữa gặm cỏ trên đồng cỏ xanh mỗi ngày.", "Bò cung cấp nguồn sữa thơm ngon và giàu dinh dưỡng."] },
    { word: "sheep", phonetic: "/ʃiːp/", def: "A domesticated ruminant animal with a thick woolly coat.", defVn: "con cừu", pos: "noun", ex: ["Fluffy white sheep were grazing on the hillside.", "Farmers shear wool from sheep in summer."], exVn: ["Những chú cừu trắng như bông đang gặm cỏ trên sườn đồi.", "Nông dân xén lông cừu vào mùa hè."] },
    { word: "goat", phonetic: "/ɡoʊt/", def: "A hardy domesticated ruminant animal with horns.", defVn: "con dê", pos: "noun", ex: ["The mountain goat climbed the steep rock effortlessly.", "Goat milk is very nutritious."], exVn: ["Chú dê núi leo lên mỏm đá dựng đứng một cách dễ dàng.", "Sữa dê rất giàu chất dinh dưỡng."] },
    { word: "pig", phonetic: "/pɪɡ/", def: "An omnivorous domesticated hoofed mammal with a snout.", defVn: "con lợn, con heo", pos: "noun", ex: ["Cute little piglets followed their mother pig.", "The pigs were resting under the cool shed."], exVn: ["Những chú lợn con đáng yêu đi theo lợn mẹ.", "Đàn lợn đang nằm nghỉ dưới bóng chuồng râm mát."] },
    { word: "duck", phonetic: "/dʌk/", def: "A waterbird with a broad blunt bill and webbed feet.", defVn: "con vịt", pos: "noun", ex: ["Ducks swam in a neat row across the pond.", "The yellow duckling made a gentle quack."], exVn: ["Đàn vịt bơi thành một hàng ngay ngắn qua ao.", "Chú vịt con màu vàng kêu cạp cạp nhẹ nhàng."] },
    { word: "chicken", phonetic: "/ˈtʃɪkɪn/", def: "A domestic fowl kept for its eggs or meat.", defVn: "con gà", pos: "noun", ex: ["Chickens search for grains in the farmyard.", "The rooster crows loudly at sunrise."], exVn: ["Đàn gà kiếm thóc trong sân nông trại.", "Chú gà trống gáy vang lúc mặt trời mọc."] },
    { word: "lion", phonetic: "/ˈlaɪən/", def: "A large tawny-coloured cat that lives in prides; king of beasts.", defVn: "con sư tử (chúa sơn lâm)", pos: "noun", ex: ["The majestic lion has a thick golden mane.", "Lions roam across the African savannah."], exVn: ["Chú sư tử dũng mãnh có chiếc bờm vàng rực.", "Những chú sư tử dạo bước trên thảo nguyên châu Phi."] },
    { word: "tiger", phonetic: "/ˈtaɪɡər/", def: "A very large solitary cat with a yellow-brown coat striped with black.", defVn: "con hổ, con cọp", pos: "noun", ex: ["The tiger moved silently through the dense jungle.", "Tigers are powerful and endangered big cats."], exVn: ["Chú hổ di chuyển êm ru trong khu rừng rậm rạp.", "Hổ là loài mèo lớn dũng mãnh và quý hiếm."] },
    { word: "bear", phonetic: "/ber/", def: "A large, heavy mammal with thick fur and a very short tail.", defVn: "con gấu", pos: "noun", ex: ["Brown bears catch fresh salmon from the river.", "Bears hibernate in cozy dens during winter."], exVn: ["Những chú gấu nâu bắt cá hồi tươi từ dòng sông.", "Gấu ngủ đông trong hang ấm áp suốt mùa đông."] },
    { word: "monkey", phonetic: "/ˈmʌŋki/", def: "A small to medium-sized primate with a long tail.", defVn: "con khỉ", pos: "noun", ex: ["Playful monkeys swing between tall jungle branches.", "The monkey peeled and ate a sweet banana."], exVn: ["Những chú khỉ tinh nghịch chuyền cành cây cao trong rừng.", "Chú khỉ bóc và ăn quả chuối ngọt lịm."] },
    { word: "elephant", phonetic: "/ˈelɪfənt/", def: "A very large herbivorous mammal with a trunk and long ivory tusks.", defVn: "con voi", pos: "noun", ex: ["The friendly elephant sprayed water with its trunk.", "Elephants are highly intelligent and caring animals."], exVn: ["Chú voi thân thiện dùng vòi phun nước mát rượi.", "Voi là loài động vật rất thông minh và tình cảm."] },
    { word: "dolphin", phonetic: "/ˈdɑːlfɪn/", def: "A small gregarious toothed whale that typically has a beaklike snout.", defVn: "cá heo (thông minh và thân thiện)", pos: "noun", ex: ["A pod of dolphins leaped gracefully beside our boat.", "Dolphins communicate using unique clicking sounds."], exVn: ["Một đàn cá heo nhảy múa uyển chuyển bên mạn thuyền chúng tôi.", "Cá heo giao tiếp bằng những âm thanh đặc biệt."] },
    { word: "whale", phonetic: "/weɪl/", def: "A very large marine mammal with a streamlined body.", defVn: "cá voi (động vật lớn nhất đại dương)", pos: "noun", ex: ["The blue whale is the largest animal on Earth.", "We went on a whale-watching boat tour."], exVn: ["Cá voi xanh là loài động vật lớn nhất trên Trái Đất.", "Chúng tôi đã đi tour du thuyền ngắm cá voi."] }
  ],

  // Theme 12: Bộ phận cơ thể
  t_basic_body_parts: [
    { word: "neck", phonetic: "/nek/", def: "The part of a person's body connecting the head to the rest of the body.", defVn: "cổ (nối đầu và thân)", pos: "noun", ex: ["She wore a warm woolen scarf around her neck.", "Turn your neck gently to relax tense muscles."], exVn: ["Cô ấy quàng chiếc khăn len ấm áp quanh cổ.", "Xoay nhẹ cổ để thư giãn các cơ bắp đang căng thẳng."] },
    { word: "shoulder", phonetic: "/ˈʃoʊldər/", def: "The upper joint of each of the human arms and the part of the body between neck and upper arm.", defVn: "bờ vai, vai", pos: "noun", ex: ["He carried a heavy backpack on his right shoulder.", "She tapped me on the shoulder to say hi."], exVn: ["Anh ấy đeo chiếc ba lô nặng trên vai phải.", "Cô ấy vỗ nhẹ vào vai tôi để chào."] },
    { word: "chest", phonetic: "/tʃest/", def: "The front surface of a person's body between the neck and the stomach.", defVn: "ngực (phần thân trên)", pos: "noun", ex: ["Take a deep breath and expand your chest.", "He placed his right hand over his heart on chest."], exVn: ["Hít một hơi thật sâu và mở rộng lồng ngực.", "Anh ấy đặt bàn tay phải lên tim trên ngực."] },
    { word: "stomach", phonetic: "/ˈstʌmək/", def: "The internal organ in which the first part of digestion occurs.", defVn: "bụng, dạ dày", pos: "noun", ex: ["My stomach is rumbling because I am hungry.", "Drinking warm ginger tea soothes your stomach."], exVn: ["Bụng tôi đang sôi ùng ục vì đói.", "Uống trà gừng ấm giúp làm dịu dạ dày."] },
    { word: "back", phonetic: "/bæk/", def: "The rear surface of the human body from the shoulders to the hips.", defVn: "lưng (phía sau cơ thể)", pos: "noun", ex: ["Sit up straight to keep your back healthy.", "He has muscle soreness in his lower back."], exVn: ["Hãy ngồi thẳng lưng để giữ cột sống khỏe mạnh.", "Anh ấy bị đau mỏi cơ ở phần thắt lưng."] },
    { word: "elbow", phonetic: "/ˈelboʊ/", def: "The joint between the forearm and the upper arm.", defVn: "khuỷu tay, cùi chỏ", pos: "noun", ex: ["He rested his elbows on the wooden desk.", "Bend your elbows when doing push-ups."], exVn: ["Anh ấy tựa khuỷu tay lên chiếc bàn gỗ.", "Gập khuỷu tay lại khi thực hiện động tác hít đất."] },
    { word: "wrist", phonetic: "/rɪst/", def: "The joint connecting the hand with the forearm.", defVn: "cổ tay", pos: "noun", ex: ["He wears a smart fitness watch on his wrist.", "Warm up your wrists before playing badminton."], exVn: ["Anh ấy đeo đồng hồ thể thao thông minh trên cổ tay.", "Khởi động cổ tay trước khi chơi cầu lông nhé."] },
    { word: "knee", phonetic: "/niː/", def: "The joint between the thigh and the lower leg.", defVn: "đầu gối", pos: "noun", ex: ["He bent his knees to lift the heavy box.", "Wear knee pads when roller skating."], exVn: ["Cậu ấy gập đầu gối để nhấc chiếc hộp nặng lên.", "Hãy đeo đồ bảo hộ đầu gối khi trượt pa-tanh nhé."] },
    { word: "ankle", phonetic: "/ˈæŋkl/", def: "The joint connecting the foot with the leg.", defVn: "mắt cá chân, cổ chân", pos: "noun", ex: ["She twisted her ankle while jogging in the park.", "Support your ankles with proper athletic shoes."], exVn: ["Cô ấy bị trẹo mắt cá chân khi chạy bộ trong công viên.", "Bảo vệ cổ chân bằng đôi giày thể thao phù hợp."] },
    { word: "finger", phonetic: "/ˈfɪŋɡər/", def: "Each of the four slender jointed parts attached to either hand.", defVn: "ngón tay", pos: "noun", ex: ["She has an elegant gold ring on her index finger.", "Point your finger at the map."], exVn: ["Cô ấy đeo chiếc nhẫn vàng thanh lịch ở ngón trỏ.", "Hãy chỉ ngón tay vào bản đồ nhé."] },
    { word: "toe", phonetic: "/toʊ/", def: "Any of the five digits at the end of the human foot.", defVn: "ngón chân", pos: "noun", ex: ["Wiggle your toes to improve blood circulation.", "She dipped her toes into the warm ocean water."], exVn: ["Cử động các ngón chân để tăng lưu thông máu.", "Cô ấy nhúng các ngón chân vào làn nước biển ấm áp."] },
    { word: "chin", phonetic: "/tʃɪn/", def: "The protruding part of the face below the mouth.", defVn: "cằm", pos: "noun", ex: ["He rested his chin in his hands while thinking.", "Keep your chin up and stay confident."], exVn: ["Anh ấy chống cằm suy nghĩ mông lung.", "Hãy ngẩng cao đầu tự tin lên nhé."] },
    { word: "forehead", phonetic: "/ˈfɔːrhed/", def: "The part of the face above the eyebrows.", defVn: "trán (phần trên khuôn mặt)", pos: "noun", ex: ["Mom touched my forehead to check for a fever.", "Wipe the sweat from your forehead."], exVn: ["Mẹ chạm vào trán tôi để kiểm tra xem có bị sốt không.", "Lau mồ hôi trên trán đi nào."] },
    { word: "eyebrow", phonetic: "/ˈaɪbraʊ/", def: "The strip of hair growing on the ridge above a person's eye socket.", defVn: "lông mày, chân mày", pos: "noun", ex: ["He raised his eyebrows in surprise.", "She has neatly shaped dark eyebrows."], exVn: ["Anh ấy nhướng đôi lông mày lên đầy ngạc nhiên.", "Cô ấy có hàng chân mày đen gọn gàng."] },
    { word: "tooth", phonetic: "/tuːθ/", def: "Each of a set of hard, bony enamel-coated structures in the jaws.", defVn: "răng (số ít)", pos: "noun", ex: ["Brush every tooth carefully for two minutes.", "The baby is cutting her first tooth."], exVn: ["Đánh răng cẩn thận trong hai phút nhé.", "Bé đang mọc chiếc răng đầu tiên."] }
  ],

  // Theme 13: Trang phục cơ bản
  t_basic_clothes: [
    { word: "coat", phonetic: "/koʊt/", def: "An outer garment worn outdoors, having sleeves and typically extending below the hips.", defVn: "áo khoác dài, áo măng-tô", pos: "noun", ex: ["Put on a thick woolen coat before stepping into snow.", "Hang your heavy coat by the entrance."], exVn: ["Mặc chiếc áo khoác len dày trước khi ra ngoài tuyết.", "Treo chiếc áo khoác dày ở gần lối vào nhé."] },
    { word: "jacket", phonetic: "/ˈdʒækɪt/", def: "An outer garment extending either to the waist or the hips.", defVn: "áo khoác ngắn, áo gió, áo da", pos: "noun", ex: ["He zipped up his warm waterproof jacket.", "A black leather jacket looks very stylish."], exVn: ["Anh ấy kéo khóa chiếc áo khoác chống nước ấm áp.", "Chiếc áo khoác da màu đen trông rất sành điệu."] },
    { word: "sweater", phonetic: "/ˈswetər/", def: "A knitted garment worn on the upper body, typically with long sleeves.", defVn: "áo len (chui đầu)", pos: "noun", ex: ["Grandmother knitted a soft green sweater for me.", "Wear a cozy sweater on chilly autumn evenings."], exVn: ["Bà đã đan cho tôi một chiếc áo len màu xanh mềm mại.", "Hãy mặc áo len ấm vào những buổi tối thu se lạnh."] },
    { word: "jeans", phonetic: "/dʒiːnz/", def: "Hard-wearing casual trousers made of denim fabric.", defVn: "quần bò, quần jean", pos: "noun", ex: ["Blue jeans and a white t-shirt never go out of style.", "These denim jeans are durable and comfortable."], exVn: ["Quần jean xanh kết hợp áo phông trắng không bao giờ lỗi mốt.", "Chiếc quần jean này rất bền và thoải mái."] },
    { word: "shorts", phonetic: "/ʃɔːrts/", def: "Short trousers that reach only to the knees or thighs.", defVn: "quần đùi, quần soóc", pos: "noun", ex: ["He wore cotton shorts and sandals to the beach.", "Running in comfortable shorts feels great."], exVn: ["Anh ấy mặc quần soóc cotton và đi dép lê ra bãi biển.", "Chạy bộ trong chiếc quần soóc êm ái thật tuyệt."] },
    { word: "skirt", phonetic: "/skɜːrt/", def: "A garment fastened around the waist and hanging down around the legs.", defVn: "chân váy (nữ)", pos: "noun", ex: ["She wore an elegant pleated skirt to the ceremony.", "A denim skirt pairs well with sneakers."], exVn: ["Cô ấy mặc chiếc chân váy xếp ly thanh lịch đến buổi lễ.", "Chân váy bò kết hợp rất đẹp với giày thể thao."] },
    { word: "suit", phonetic: "/suːt/", def: "A set of clothes made of the same fabric, typically consisting of a jacket and trousers.", defVn: "bộ vest, bộ âu phục trang trọng", pos: "noun", ex: ["He wore a tailored dark navy suit to the interview.", "A sharp suit creates a professional image."], exVn: ["Anh ấy mặc bộ vest màu xanh đậm vừa vặn đi phỏng vấn.", "Bộ âu phục lịch lãm tạo nên hình ảnh chuyên nghiệp."] },
    { word: "tie", phonetic: "/taɪ/", def: "A strip of material worn around the collar and tied in a knot at the front.", defVn: "cà vạt (thắt cổ áo)", pos: "noun", ex: ["He adjusted his silk necktie in the mirror.", "A red tie complements a crisp white shirt."], exVn: ["Anh ấy chỉnh lại chiếc cà vạt lụa trước gương.", "Cà vạt đỏ làm nổi bật chiếc áo sơ mi trắng tinh."] },
    { word: "scarf", phonetic: "/skɑːrf/", def: "A length of fabric worn around the neck or head for warmth or style.", defVn: "khăn quàng cổ, khăn choàng", pos: "noun", ex: ["Wrap this warm wool scarf around your neck.", "She chose a colorful silk scarf for the trip."], exVn: ["Quàng chiếc khăn len ấm này quanh cổ nhé.", "Cô ấy chọn chiếc khăn lụa rực rỡ cho chuyến đi."] },
    { word: "gloves", phonetic: "/ɡlʌvz/", def: "A covering for the hand made with a separate sheath for each finger.", defVn: "đôi găng tay, bao tay ấm", pos: "noun", ex: ["Wear leather gloves to protect your hands from frost.", "She lost one of her knitted gloves on the bus."], exVn: ["Đeo găng tay da để bảo vệ đôi bàn tay khỏi giá rét.", "Cô ấy đánh rơi một chiếc găng tay len trên xe buýt."] },
    { word: "belt", phonetic: "/belt/", def: "A strip of leather or other material worn around the waist.", defVn: "thắt lưng, dây nịt", pos: "noun", ex: ["Fasten your leather belt securely.", "He bought a classic brown belt for his trousers."], exVn: ["Hãy thắt dây nịt da thật vừa vặn nhé.", "Anh ấy đã mua chiếc thắt lưng da màu nâu cho quần âu."] },
    { word: "socks", phonetic: "/sɑːks/", def: "A garment for the foot and lower part of the leg.", defVn: "đôi tất, đôi vớ", pos: "noun", ex: ["Put on clean cotton socks before wearing sneakers.", "Thick wool socks keep your feet warm in winter."], exVn: ["Hãy đi tất cotton sạch trước khi mang giày thể thao.", "Những đôi tất len dày giữ ấm bàn chân vào mùa đông."] },
    { word: "boots", phonetic: "/buːts/", def: "A sturdy item of footwear covering the foot and ankle, and sometimes lower leg.", defVn: "đôi bốt, đôi ủng, giày cao cổ", pos: "noun", ex: ["She wore waterproof hiking boots on the mountain trail.", "Winter boots prevent your feet from getting wet."], exVn: ["Cô ấy đi đôi bốt leo núi chống nước trên đường mòn.", "Ủng mùa đông giúp chân bạn không bị ướt."] },
    { word: "sandals", phonetic: "/ˈsændlz/", def: "A shoe consisting of a sole fastened by straps to the foot.", defVn: "dép xăng-đan, dép quai hậu", pos: "noun", ex: ["Comfortable leather sandals are great for hot summer days.", "He kicked off his sandals on the sandy beach."], exVn: ["Dép xăng-đan da êm ái rất tuyệt cho ngày hè nóng nực.", "Cậu ấy cởi phăng đôi xăng-đan trên bãi cát mịn."] },
    { word: "pyjamas", phonetic: "/pəˈdʒɑːməz/", def: "A suit of loose trousers and jacket or shirt for sleeping in.", defVn: "bộ đồ ngủ pijama", pos: "noun", ex: ["Change into cozy silk pyjamas before going to bed.", "The little boy loves his dinosaur pyjamas."], exVn: ["Thay bộ đồ ngủ pijama lụa êm ái trước khi lên giường.", "Cậu bé rất thích bộ đồ ngủ hình khủng long của mình."] }
  ],

  // Theme 14: Địa điểm & Chỉ đường
  t_basic_places_directions: [
    { word: "hospital", phonetic: "/ˈhɑːspɪtl/", def: "An institution providing medical treatment and nursing care.", defVn: "bệnh viện", pos: "noun", ex: ["The city hospital has modern emergency facilities.", "He visited his friend in the hospital."], exVn: ["Bệnh viện thành phố có cơ sở cấp cứu hiện đại.", "Anh ấy đã đến thăm bạn trong bệnh viện."] },
    { word: "pharmacy", phonetic: "/ˈfɑːrməsi/", def: "A shop where medicinal drugs are prepared or sold.", defVn: "hiệu thuốc, nhà thuốc", pos: "noun", ex: ["Buy cold medicine at the corner pharmacy.", "The pharmacy is open 24 hours a day."], exVn: ["Mua thuốc cảm tại hiệu thuốc ở góc phố.", "Nhà thuốc mở cửa 24 giờ mỗi ngày."] },
    { word: "bank", phonetic: "/bæŋk/", def: "A financial establishment that uses money deposited by customers.", defVn: "ngân hàng", pos: "noun", ex: ["I need to go to the bank to open a savings account.", "The bank is closed on Sundays."], exVn: ["Tôi cần đến ngân hàng để mở tài khoản tiết kiệm.", "Ngân hàng đóng cửa vào ngày Chủ Nhật."] },
    { word: "post office", phonetic: "/ˈpoʊst ɔːfɪs/", def: "A building where postal services are provided to the public.", defVn: "bưu điện", pos: "noun", ex: ["Mail your international letter at the central post office.", "The post office sells stamps and boxes."], exVn: ["Gửi thư quốc tế tại bưu điện trung tâm nhé.", "Bưu điện bán tem và hộp đóng hàng."] },
    { word: "police station", phonetic: "/pəˈliːs ˈsteɪʃn/", def: "The office or headquarters of a local police force.", defVn: "đồn cảnh sát, công an", pos: "noun", ex: ["Report the lost passport at the nearest police station.", "The police station is located next to city hall."], exVn: ["Khai báo mất hộ chiếu tại đồn cảnh sát gần nhất.", "Đồn công an nằm ngay cạnh tòa thị chính."] },
    { word: "supermarket", phonetic: "/ˈsuːpərmɑːrkɪt/", def: "A large self-service grocery store.", defVn: "siêu thị", pos: "noun", ex: ["We buy weekly groceries at the local supermarket.", "The supermarket has fresh seafood and vegetables."], exVn: ["Chúng tôi mua thực phẩm hàng tuần tại siêu thị địa phương.", "Siêu thị có nhiều hải sản và rau củ tươi sống."] },
    { word: "bakery", phonetic: "/ˈbeɪkəri/", def: "A place where bread and cakes are made or sold.", defVn: "tiệm bánh mì, tiệm bánh ngọt", pos: "noun", ex: ["The aroma of fresh bread comes from the corner bakery.", "She bought a birthday cake at the bakery."], exVn: ["Hương thơm bánh mì mới nướng tỏa ra từ tiệm bánh góc phố.", "Cô ấy đã mua chiếc bánh sinh nhật ở tiệm bánh."] },
    { word: "restaurant", phonetic: "/ˈrestrɑːnt/", def: "A place where people pay to sit and eat meals.", defVn: "nhà hàng, quán ăn", pos: "noun", ex: ["We reserved a table at a traditional Vietnamese restaurant.", "The restaurant serves delicious pho."], exVn: ["Chúng tôi đã đặt bàn tại một nhà hàng món Việt truyền thống.", "Nhà hàng phục vụ món phở rất ngon."] },
    { word: "hotel", phonetic: "/hoʊˈtel/", def: "An establishment providing accommodation, meals, and other services for travelers.", defVn: "khách sạn", pos: "noun", ex: ["We booked a comfortable four-star hotel near the beach.", "The hotel staff is very hospitable."], exVn: ["Chúng tôi đặt khách sạn 4 sao tiện nghi gần bãi biển.", "Nhân viên khách sạn rất hiếu khách."] },
    { word: "airport", phonetic: "/ˈerpɔːrt/", def: "A complex of runways and buildings for takeoff, landing, and maintenance of civil aircraft.", defVn: "sân bay, phi trường", pos: "noun", ex: ["Arrive at the international airport two hours before departure.", "Noi Bai Airport connects Hanoi to the world."], exVn: ["Có mặt tại sân bay quốc tế 2 tiếng trước giờ khởi hành nhé.", "Sân bay Nội Bài kết nối Hà Nội với toàn thế giới."] },
    { word: "bridge", phonetic: "/brɪdʒ/", def: "A structure carrying a road, path, or railway across a river, ravine, or road.", defVn: "cây cầu (bắc qua sông, đường)", pos: "noun", ex: ["The iconic Dragon Bridge in Da Nang breathes fire on weekends.", "Walk across the pedestrian bridge safely."], exVn: ["Cầu Rồng biểu tượng ở Đà Nẵng phun lửa vào cuối tuần.", "Đi bộ qua cầu dành cho người đi bộ an toàn nhé."] },
    { word: "corner", phonetic: "/ˈkɔːrnər/", def: "A place or angle where two or more sides or edges meet.", defVn: "góc phố, góc đường", pos: "noun", ex: ["The cozy cafe is located at the street corner.", "Turn right at the next corner."], exVn: ["Quán cà phê ấm cúng nằm ngay góc phố.", "Rẽ phải ở góc đường tiếp theo nhé."] },
    { word: "straight", phonetic: "/streɪt/", def: "Extending or moving uniformly in one direction only; without a curve or bend.", defVn: "đi thẳng, thẳng hàng", pos: "adverb", ex: ["Go straight ahead for two hundred meters.", "Walk straight until you see the big clock tower."], exVn: ["Đi thẳng về phía trước 200 mét nhé.", "Hãy đi thẳng cho đến khi bạn thấy tháp đồng hồ lớn."] },
    { word: "left", phonetic: "/left/", def: "On, towards, or relating to the side of a human body or of a thing which is to the west when facing north.", defVn: "bên trái, rẽ trái", pos: "noun", ex: ["Turn left at the traffic light.", "The library is on your left."], exVn: ["Rẽ trái ở cột đèn giao thông.", "Thư viện nằm ở phía bên tay trái của bạn."] },
    { word: "right", phonetic: "/raɪt/", def: "On, towards, or relating to the side of a human body or of a thing which is to the east when facing north.", defVn: "bên phải, rẽ phải", pos: "noun", ex: ["Turn right after passing the bank.", "Keep to the right side of the escalator."], exVn: ["Rẽ phải sau khi đi qua ngân hàng.", "Hãy đứng về phía bên phải của thang cuốn."] }
  ],

  // Theme 15: Thời tiết & Thiên nhiên
  t_basic_weather_nature: [
    { word: "sunshine", phonetic: "/ˈsʌnʃaɪn/", def: "Direct sunlight unbroken by cloud, especially over a large area.", defVn: "ánh nắng mặt trời chan hòa", pos: "noun", ex: ["Enjoy the golden sunshine on the sandy beach.", "Sunshine brings warmth to the valley."], exVn: ["Tận hưởng ánh nắng vàng ươm trên bãi cát mịn.", "Ánh nắng mang hơi ấm đến thung lũng."] },
    { word: "rainfall", phonetic: "/ˈreɪnfɔːl/", def: "The quantity of rain falling within a given area in a given time.", defVn: "lượng mưa, cơn mưa rào", pos: "noun", ex: ["Tropical rainforests receive heavy annual rainfall.", "The rainfall refreshed the dry soil."], exVn: ["Những khu rừng mưa nhiệt đới đón lượng mưa hàng năm rất lớn.", "Cơn mưa rào đã làm tươi mới mảnh đất khô cằn."] },
    { word: "breeze", phonetic: "/briːz/", def: "A gentle, refreshing wind.", defVn: "cơn gió nhẹ, gió thoảng mát", pos: "noun", ex: ["A cool sea breeze blew gently through the open window.", "The evening breeze cooled down the summer heat."], exVn: ["Làn gió biển mát rượi thổi nhẹ qua ô cửa sổ mở.", "Cơn gió thoảng buổi chiều xua tan đi cái nóng mùa hè."] },
    { word: "cloudy", phonetic: "/ˈklaʊdi/", def: "Covered with or characterized by clouds; overcast.", defVn: "trời nhiều mây, râm mát", pos: "adj", ex: ["It is cloudy today, so bring an umbrella just in case.", "A cloudy morning kept the temperature pleasant."], exVn: ["Hôm nay trời nhiều mây, hãy mang theo ô đề phòng nhé.", "Buổi sáng nhiều mây giữ cho nhiệt độ dễ chịu."] },
    { word: "foggy", phonetic: "/ˈfɑːɡi/", def: "Full of or accompanied by fog.", defVn: "trời nhiều sương mù dày đặc", pos: "adj", ex: ["Drive slowly on foggy mountain roads in Sapa.", "The morning was quiet and foggy."], exVn: ["Hãy lái xe chậm trên những cung đường đèo nhiều sương mù ở Sa Pa.", "Buổi sáng thật yên ắng và mờ sương."] },
    { word: "stormy", phonetic: "/ˈstɔːrmi/", def: "Characterized by strong winds, heavy rain, or lightning.", defVn: "giông bão, bão bùng", pos: "adj", ex: ["The fishermen stayed onshore due to stormy sea weather.", "Thunder echoed across the stormy sky."], exVn: ["Các ngư dân ở lại bờ do thời tiết biển giông bão.", "Sấm sét vang rền trên bầu trời bão bùng."] },
    { word: "snowy", phonetic: "/ˈsnoʊi/", def: "Covered with snow or characterized by snowfall.", defVn: "có tuyết rơi, phủ đầy tuyết", pos: "adj", ex: ["Children love building snowmen on snowy winter days.", "The snowy mountains looked magical in the morning light."], exVn: ["Lũ trẻ rất thích đắp người tuyết vào những ngày đông có tuyết rơi.", "Những ngọn núi phủ tuyết trông thật kỳ ảo dưới ánh bình minh."] },
    { word: "rainbow", phonetic: "/ˈreɪnboʊ/", def: "An arch of colors formed in the sky in certain circumstances, caused by refraction of sun's rays.", defVn: "cầu vồng bảy sắc", pos: "noun", ex: ["A vibrant rainbow appeared in the sky after the summer shower.", "Look at the colorful double rainbow over the lake!"], exVn: ["Một chiếc cầu vồng rực rỡ xuất hiện trên bầu trời sau cơn mưa rào mùa hè.", "Hãy nhìn chiếc cầu vồng đôi đầy màu sắc trên mặt hồ kìa!"] },
    { word: "thunder", phonetic: "/ˈθʌndər/", def: "A loud rumbling or crashing noise heard after a lightning flash.", defVn: "tiếng sấm sét vang trời", pos: "noun", ex: ["The loud clap of thunder startled the sleeping puppy.", "We heard thunder rolling in the distance."], exVn: ["Tiếng sấm nổ vang trời khiến chú cún con đang ngủ giật mình.", "Chúng tôi nghe thấy tiếng sấm rền vang từ xa."] },
    { word: "lightning", phonetic: "/ˈlaɪtnɪŋ/", def: "The occurrence of a natural electrical discharge of very short duration between a cloud and ground.", defVn: "tia chớp, tia sét", pos: "noun", ex: ["A flash of brilliant lightning lit up the dark night.", "Never stand under tall trees during lightning."], exVn: ["Một tia chớp rực sáng thắp sáng cả màn đêm đen.", "Tuyệt đối không đứng dưới cây cao khi có sấm sét."] },
    { word: "island", phonetic: "/ˈaɪlənd/", def: "A piece of land surrounded by water.", defVn: "hòn đảo, hòn cù lao", pos: "noun", ex: ["Phu Quoc is a breathtaking tropical island in Vietnam.", "We took a ferry to explore the nearby island."], exVn: ["Phú Quốc là một hòn đảo nhiệt đới đẹp mê hồn của Việt Nam.", "Chúng tôi đi phà để khám phá hòn đảo lân cận."] },
    { word: "waterfall", phonetic: "/ˈwɔːtərfɔːl/", def: "A cascade of water falling from a height.", defVn: "thác nước hùng vĩ", pos: "noun", ex: ["Ban Gioc Waterfall is one of the most stunning waterfalls in Asia.", "The cool mist from the waterfall felt refreshing."], exVn: ["Thác Bản Giốc là một trong những thác nước ngoạn mục nhất châu Á.", "Làn sương mát lành từ thác nước mang lại cảm giác sảng khoái."] },
    { word: "forest", phonetic: "/ˈfɔːrɪst/", def: "A large area covered chiefly with trees and undergrowth.", defVn: "khu rừng rậm, cánh rừng", pos: "noun", ex: ["Birds sing melodiously inside the green tropical forest.", "Protecting natural forests preserves biodiversity."], exVn: ["Những chú chim hót líu lo trong cánh rừng nhiệt đới xanh mát.", "Bảo vệ rừng tự nhiên giúp bảo tồn đa dạng sinh học."] },
    { word: "river", phonetic: "/ˈrɪvər/", def: "A large natural stream of water flowing in a channel to the sea, a lake, or another such stream.", defVn: "dòng sông", pos: "noun", ex: ["The Red River flows peacefully through Hanoi.", "Boats cruise along the picturesque river at sunset."], exVn: ["Dòng sông Hồng êm đềm chảy qua Hà Nội.", "Những chiếc thuyền lướt dọc dòng sông thơ mộng lúc hoàng hôn."] },
    { word: "ocean", phonetic: "/ˈoʊʃn/", def: "A very large expanse of sea, in particular each of the main areas into which the sea is divided.", defVn: "đại dương bao la", pos: "noun", ex: ["The vast ocean is home to millions of fascinating marine creatures.", "We watched the sunrise over the turquoise ocean."], exVn: ["Đại dương bao la là ngôi nhà của hàng triệu sinh vật biển kỳ thú.", "Chúng tôi ngắm bình minh trên đại dương xanh ngắt."] }
  ]
};
