module.exports = {
  // Theme 16: Nghề nghiệp & Việc làm (Jobs & Occupations)
  t_basic_jobs_occupations: [
    { word: "dentist", phonetic: "/ˈdentɪst/", def: "A person qualified to treat diseases and conditions affecting the teeth.", defVn: "bác sĩ nha khoa, nha sĩ", pos: "noun", ex: ["Visit the dentist twice a year for healthy teeth.", "The gentle dentist cleaned my teeth painlessly."], exVn: ["Đi khám nha sĩ hai lần một năm để răng luôn chắc khỏe.", "Vị nha sĩ ân cần đã làm sạch răng cho tôi không hề đau."] },
    { word: "reporter", phonetic: "/rɪˈpɔːrtər/", def: "A person who reports on news or events for television or newspapers.", defVn: "phóng viên, nhà báo", pos: "noun", ex: ["The news reporter interviewed eyewitnesses on the scene.", "She works as an international travel reporter."], exVn: ["Phóng viên tin tức đã phỏng vấn các nhân chứng tại hiện trường.", "Cô ấy làm phóng viên du lịch quốc tế."] },
    { word: "photographer", phonetic: "/fəˈtɑːɡrəfər/", def: "A person who takes photographs, especially as a job.", defVn: "nhiếp ảnh gia, thợ chụp ảnh", pos: "noun", ex: ["The wedding photographer captured joyful moments.", "He is a talented nature photographer."], exVn: ["Nhiếp ảnh gia chụp lại những khoảnh khắc vui tươi trong đám cưới.", "Anh ấy là một nhiếp ảnh gia thiên nhiên tài ba."] },
    { word: "electrician", phonetic: "/ɪˌlekˈtrɪʃn/", def: "A person who installs and maintains electrical equipment.", defVn: "thợ điện", pos: "noun", ex: ["Call an electrician to fix the faulty kitchen wiring.", "The certified electrician tested the circuit safely."], exVn: ["Gọi thợ điện đến sửa hệ thống dây điện bị hỏng trong bếp.", "Thợ điện có chứng chỉ đã kiểm tra mạch điện an toàn."] },
    { word: "plumber", phonetic: "/ˈplʌmər/", def: "A person who installs and repairs pipes and fittings of water supply.", defVn: "thợ sửa ống nước", pos: "noun", ex: ["The plumber quickly repaired the leaking bathroom pipe.", "We need a plumber to install the new sink."], exVn: ["Người thợ sửa ống nước đã sửa nhanh đường ống bị rò rỉ.", "Chúng tôi cần thợ sửa ống nước để lắp bồn rửa mới."] },
    { word: "carpenter", phonetic: "/ˈkɑːrpəntər/", def: "A person who makes and repairs wooden objects and structures.", defVn: "thợ mộc (làm đồ gỗ)", pos: "noun", ex: ["The skilled carpenter crafted a solid wooden dining table.", "Carpenters use saws and chisels to shape wood."], exVn: ["Người thợ mộc lành nghề đã đóng một chiếc bàn ăn gỗ chắc chắn.", "Thợ mộc dùng cưa và đục để đẽo gọt gỗ."] },
    { word: "baker", phonetic: "/ˈbeɪkər/", def: "A person whose trade is making and selling bread and cakes.", defVn: "thợ làm bánh (bánh mì, bánh ngọt)", pos: "noun", ex: ["The baker wakes up at 4 AM to bake fresh croissants.", "Our local baker makes the crunchiest baguettes."], exVn: ["Người thợ làm bánh thức dậy lúc 4 giờ sáng để nướng bánh sừng bò tươi.", "Thợ làm bánh địa phương làm ra những chiếc bánh mì giòn tan."] },
    { word: "gardener", phonetic: "/ˈɡɑːrdnər/", def: "A person who tends and cultivates a garden as work or recreation.", defVn: "người làm vườn", pos: "noun", ex: ["The gardener trims the rose bushes and waters the lawn.", "She hired a gardener to design her backyard."], exVn: ["Người làm vườn tỉa những bụi hoa hồng và tưới bãi cỏ.", "Cô ấy đã thuê người làm vườn thiết kế sân sau."] },
    { word: "tailor", phonetic: "/ˈteɪlər/", def: "A person whose occupation is making or altering fitted clothes.", defVn: "thợ may (quần áo)", pos: "noun", ex: ["The tailor measured my shoulders for a custom suit.", "Hoi An is famous for its fast and skilled tailors."], exVn: ["Người thợ may đã đo vai tôi để may bộ vest vừa vặn.", "Hội An nổi tiếng với những thợ may nhanh nhẹn và khéo léo."] },
    { word: "cleaner", phonetic: "/ˈkliːnər/", def: "A person employed to clean the interior of a building.", defVn: "nhân viên vệ sinh, người dọn dẹp", pos: "noun", ex: ["The office cleaner keeps our workplace sparkling clean.", "Please thank the hardworking building cleaner."], exVn: ["Nhân viên vệ sinh giữ cho nơi làm việc của chúng tôi luôn sáng bóng.", "Hãy cảm ơn người dọn dẹp tòa nhà chăm chỉ nhé."] },
    { word: "security guard", phonetic: "/sɪˈkjʊrəti ɡɑːrd/", def: "A person employed to protect a building against intruders or damage.", defVn: "nhân viên bảo vệ", pos: "noun", ex: ["The friendly security guard greeted us at the entrance.", "Security guards monitor safety cameras 24/7."], exVn: ["Bác bảo vệ thân thiện đã chào đón chúng tôi ở cổng vào.", "Các nhân viên bảo vệ theo dõi camera an ninh 24/7."] },
    { word: "manager", phonetic: "/ˈmænɪdʒər/", def: "A person responsible for controlling or administering an organization or group.", defVn: "người quản lý, giám đốc chi nhánh", pos: "noun", ex: ["The hotel manager resolved the customer's request promptly.", "She was promoted to marketing manager."], exVn: ["Quản lý khách sạn đã giải quyết yêu cầu của khách hàng nhanh chóng.", "Cô ấy đã được thăng chức lên vị trí quản lý tiếp thị."] },
    { word: "pharmacist", phonetic: "/ˈfɑːrməsɪst/", def: "A person who is professionally qualified to prepare and dispense medicinal drugs.", defVn: "dược sĩ (bán thuốc)", pos: "noun", ex: ["Ask the pharmacist how many times a day to take the pills.", "The pharmacist explained the medicine label clearly."], exVn: ["Hãy hỏi dược sĩ uống thuốc mấy lần mỗi ngày nhé.", "Dược sĩ giải thích nhãn thuốc rất rõ ràng."] },
    { word: "veterinarian", phonetic: "/ˌvetərɪˈneriən/", def: "A person qualified to treat diseased or injured animals; vet.", defVn: "bác sĩ thú y", pos: "noun", ex: ["We took our sick puppy to the local veterinarian.", "The veterinarian vaccinated our cat against rabies."], exVn: ["Chúng tôi đưa chú cún bị ốm đến bác sĩ thú y địa phương.", "Bác sĩ thú y đã tiêm vắc-xin phòng dại cho chú mèo của chúng tôi."] },
    { word: "scientist", phonetic: "/ˈsaɪəntɪst/", def: "A person who is studying or has expert knowledge of one or more natural sciences.", defVn: "nhà khoa học", pos: "noun", ex: ["Scientists are researching clean renewable energy solutions.", "Marie Curie was a groundbreaking scientist."], exVn: ["Các nhà khoa học đang nghiên cứu các giải pháp năng lượng sạch tái tạo.", "Marie Curie là một nhà khoa học lỗi lạc."] }
  ],

  // Theme 17: Phương tiện giao thông (Vehicles & Transport)
  t_basic_transportation: [
    { word: "ambulance", phonetic: "/ˈæmbjələns/", def: "A vehicle equipped for taking sick or injured people to and from hospital.", defVn: "xe cứu thương, xe cấp cứu", pos: "noun", ex: ["Give way immediately when an ambulance flashes its sirens.", "The ambulance arrived within five minutes."], exVn: ["Nhường đường ngay khi xe cứu thương nháy còi báo động.", "Xe cứu thương đã đến trong vòng năm phút."] },
    { word: "fire truck", phonetic: "/ˈfaɪər trʌk/", def: "A vehicle carrying firefighters and equipment for extinguishing fires.", defVn: "xe cứu hỏa", pos: "noun", ex: ["The red fire truck rushed toward the burning building.", "Fire trucks carry powerful high-pressure water hoses."], exVn: ["Chiếc xe cứu hỏa màu đỏ lao nhanh về phía tòa nhà đang cháy.", "Xe cứu hỏa mang theo vòi rồng áp lực cao mạnh mẽ."] },
    { word: "van", phonetic: "/væn/", def: "A medium-sized motor vehicle used for carrying goods or people.", defVn: "xe tải nhỏ, xe van 16 chỗ", pos: "noun", ex: ["We rented a delivery van to move our furniture.", "The tourist van took us on a scenic countryside tour."], exVn: ["Chúng tôi thuê một chiếc xe van chở hàng để chuyển đồ đạc.", "Chiếc xe van du lịch đưa chúng tôi đi ngắm cảnh nông thôn."] },
    { word: "scooter", phonetic: "/ˈskuːtər/", def: "A small motorcycle with a step-through frame or a light two-wheeled platform.", defVn: "xe tay ga, xe trượt scooter", pos: "noun", ex: ["Automatic scooters are very popular in Vietnamese cities.", "He rides an electric scooter to work every morning."], exVn: ["Xe tay ga tự động rất phổ biến ở các thành phố Việt Nam.", "Anh ấy đi xe trượt scooter điện đi làm mỗi sáng."] },
    { word: "yacht", phonetic: "/jɑːt/", def: "A medium-sized sailing or motor boat equipped for cruising or racing.", defVn: "du thuyền buồm, du thuyền sang trọng", pos: "noun", ex: ["A luxury yacht anchored in Ha Long Bay at sunset.", "They spent the afternoon sailing on a private yacht."], exVn: ["Một chiếc du thuyền sang trọng thả neo ở Vịnh Hạ Long lúc hoàng hôn.", "Họ đã trải qua buổi chiều du ngoạn trên chiếc du thuyền riêng."] },
    { word: "ferry", phonetic: "/ˈferi/", def: "A boat or ship for conveying passengers and goods across a stretch of water.", defVn: "chuyến phà, thuyền đưa đò", pos: "noun", ex: ["We boarded the car ferry to cross the wide river.", "The island ferry runs every thirty minutes."], exVn: ["Chúng tôi lên chiếc phà chở ô tô để băng qua dòng sông rộng.", "Chuyến phà ra đảo chạy cứ ba mươi phút một chuyến."] },
    { word: "canoe", phonetic: "/kəˈnuː/", def: "A narrow, light boat with pointed ends, propelled with a paddle.", defVn: "thuyền ca-nô, xuồng chèo tay", pos: "noun", ex: ["We paddled a wooden canoe across the quiet mountain lake.", "Renting a canoe is a fun holiday activity."], exVn: ["Chúng tôi chèo chiếc ca-nô gỗ trên mặt hồ núi yên bình.", "Thuê thuyền ca-nô là một hoạt động dã ngoại rất thú vị."] },
    { word: "tram", phonetic: "/træm/", def: "A passenger vehicle powered by electricity that runs on rails along public streets.", defVn: "xe điện mặt đất, tàu điện bánh sắt", pos: "noun", ex: ["Hop on the historical yellow tram to tour the old town.", "Trams offer a smooth and scenic urban commute."], exVn: ["Nhảy lên chiếc xe điện màu vàng cổ kính để dạo quanh phố cổ.", "Xe điện mặt đất mang lại chuyến đi êm ái và ngắm cảnh đô thị."] },
    { word: "passenger", phonetic: "/ˈpæsɪndʒər/", def: "A traveler on a public or private conveyance other than the driver.", defVn: "hành khách (đi tàu, xe, máy bay)", pos: "noun", ex: ["All passengers must fasten their seatbelts securely.", "The subway carried hundreds of morning passengers."], exVn: ["Tất cả hành khách phải thắt dây an toàn cẩn thận.", "Chuyến tàu điện ngầm chở hàng trăm hành khách buổi sáng."] },
    { word: "traffic light", phonetic: "/ˈtræfɪk laɪt/", def: "A set of automatically operated colored lights for controlling traffic at road junctions.", defVn: "đèn giao thông, cột đèn tín hiệu", pos: "noun", ex: ["Stop when the traffic light turns red; go on green.", "The intersection has a modern countdown traffic light."], exVn: ["Dừng lại khi đèn giao thông chuyển sang đỏ; đi khi có đèn xanh.", "Ngã tư có cột đèn giao thông đếm ngược hiện đại."] },
    { word: "gas station", phonetic: "/ˈɡæs steɪʃn/", def: "An establishment beside a road selling fuel and lubricants for motor vehicles.", defVn: "cây xăng, trạm nạp nhiên liệu", pos: "noun", ex: ["Pull over at the next gas station to fill up the tank.", "The gas station has a clean convenience store."], exVn: ["Tấp vào cây xăng tiếp theo để đổ đầy bình xăng nhé.", "Cây xăng có một cửa hàng tiện lợi sạch sẽ."] },
    { word: "parking lot", phonetic: "/ˈpɑːrkɪŋ lɑːt/", def: "An area assigned for parking motor vehicles.", defVn: "bãi đỗ xe, bãi giữ xe", pos: "noun", ex: ["Park your motorbike in the underground parking lot.", "The shopping mall parking lot was completely full."], exVn: ["Gửi xe máy của bạn dưới bãi giữ xe tầng hầm nhé.", "Bãi đỗ xe của trung tâm thương mại đã kín chỗ."] },
    { word: "crosswalk", phonetic: "/ˈkrɔːswɔːk/", def: "A marked part of a road where pedestrians have right of way.", defVn: "vạch kẻ đường cho người đi bộ qua đường", pos: "noun", ex: ["Always use the zebra crosswalk to cross the busy street safely.", "Cars must yield to pedestrians at the crosswalk."], exVn: ["Luôn đi trên vạch kẻ qua đường để sang đường đông đúc an toàn.", "Ô tô phải nhường đường cho người đi bộ ở vạch kẻ đường."] },
    { word: "sidewalk", phonetic: "/ˈsaɪdwɔːk/", def: "A paved path for pedestrians at the side of a road.", defVn: "vỉa hè, lề đường dành cho người đi bộ", pos: "noun", ex: ["Joggers ran along the tree-lined pedestrian sidewalk.", "Keep bicycles off the walking sidewalk."], exVn: ["Những người chạy bộ chạy dọc theo vỉa hè rợp bóng cây.", "Không đi xe đạp lên vỉa hè đi bộ nhé."] },
    { word: "highway", phonetic: "/ˈhaɪweɪ/", def: "A main road, especially one connecting major towns or cities.", defVn: "đường cao tốc, quốc lộ", pos: "noun", ex: ["The new expressway highway cut travel time in half.", "Drive within the highway speed limit."], exVn: ["Tuyến đường cao tốc mới đã giảm một nửa thời gian di chuyển.", "Hãy lái xe đúng tốc độ quy định trên cao tốc nhé."] }
  ],

  // Theme 18: Trường học & Dụng cụ (School & Stationery)
  t_basic_school_stationery: [
    { word: "backpack", phonetic: "/ˈbækpæk/", def: "A bag with shoulder straps that allow it to be carried on one's back.", defVn: "chiếc ba lô đi học", pos: "noun", ex: ["Pack your books and pencil case into your backpack.", "He bought a durable waterproof school backpack."], exVn: ["Xếp sách vở và hộp bút vào chiếc ba lô của bạn nhé.", "Cậu ấy đã mua một chiếc ba lô đi học chống nước rất bền."] },
    { word: "pencil case", phonetic: "/ˈpensl keɪs/", def: "A small container for holding pencils, pens, erasers, and rulers.", defVn: "hộp đựng bút, bóp viết", pos: "noun", ex: ["Keep your colored markers organized inside your pencil case.", "She zipped up her cute cartoon pencil case."], exVn: ["Giữ những chiếc bút lông màu ngăn nắp trong hộp bút nhé.", "Cô bé kéo khóa chiếc bóp viết hoạt hình đáng yêu."] },
    { word: "highlighter", phonetic: "/ˈhaɪlaɪtər/", def: "A broad felt-tipped pen used to overlay text in bright translucent color.", defVn: "bút dạ quang, bút nhớ dòng", pos: "noun", ex: ["Highlight key vocabulary with a bright yellow highlighter.", "She used pastel highlighters to organize her study notes."], exVn: ["Đánh dấu từ vựng quan trọng bằng bút dạ quang màu vàng.", "Cô ấy dùng bút nhớ màu pastel để sắp xếp ghi chép học tập."] },
    { word: "sharpener", phonetic: "/ˈʃɑːrpnər/", def: "A device for sharpening pencils.", defVn: "chiếc gọt bút chì", pos: "noun", ex: ["Sharpen your blunt pencil with this rotary sharpener.", "Can I borrow your pencil sharpener for a moment?"], exVn: ["Gọt chiếc bút chì cùn bằng chiếc gọt bút chì này nhé.", "Tôi có thể mượn gọt bút chì của bạn một lát được không?"] },
    { word: "stapler", phonetic: "/ˈsteɪplər/", def: "A device for fastening together sheets of paper with thin wire staples.", defVn: "chiếc dập ghim, bấm kim", pos: "noun", ex: ["Use the heavy-duty stapler to bind your report pages.", "Refill the stapler with metal staples."], exVn: ["Dùng chiếc dập ghim để bấm các trang báo cáo lại.", "Nạp thêm ghim kim loại vào dập ghim nhé."] },
    { word: "folder", phonetic: "/ˈfoʊldər/", def: "A folding cover or holder, typically made of stiff card or plastic, for storing loose papers.", defVn: "bìa kẹp tài liệu, kẹp hồ sơ", pos: "noun", ex: ["Store your homework worksheets neatly inside a plastic folder.", "Label each folder with the subject name."], exVn: ["Lưu các bài tập gọn gàng bên trong bìa kẹp tài liệu nhựa.", "Dán nhãn tên môn học lên từng chiếc kẹp hồ sơ."] },
    { word: "calculator", phonetic: "/ˈkælkjəleɪtər/", def: "Something used for making mathematical calculations, in particular an electronic device.", defVn: "máy tính cầm tay bỏ túi", pos: "noun", ex: ["Use a scientific calculator during math problem solving.", "Bring your calculator to the physics exam."], exVn: ["Dùng máy tính bỏ túi khoa học khi giải bài toán.", "Mang máy tính cầm tay đến phòng thi vật lý nhé."] },
    { word: "compass", phonetic: "/ˈkʌmpəs/", def: "An instrument for drawing circles and arcs and measuring distances between points.", defVn: "chiếc com-pa (vẽ hình tròn)", pos: "noun", ex: ["Draw a precise 5-centimeter circle using a compass.", "Geometry class requires a ruler, protractor, and compass."], exVn: ["Vẽ một hình tròn chính xác 5cm bằng com-pa.", "Tiết học hình học yêu cầu thước kẻ, thước đo độ và com-pa."] },
    { word: "exam", phonetic: "/ɪɡˈzæm/", def: "A formal test of a person's knowledge or proficiency in a subject or skill.", defVn: "kỳ thi, bài kiểm tra lớn", pos: "noun", ex: ["She studied diligently and achieved top marks on the exam.", "The midterm English exam takes sixty minutes."], exVn: ["Cô ấy đã học tập chăm chỉ và đạt điểm cao nhất trong kỳ thi.", "Bài thi tiếng Anh giữa kỳ kéo dài sáu mươi phút."] },
    { word: "quiz", phonetic: "/kwɪz/", def: "A quick or informal test of knowledge.", defVn: "bài kiểm tra ngắn, câu đố nhanh", pos: "noun", ex: ["We take a 5-minute vocabulary quiz at the start of class.", "Play an interactive online English quiz."], exVn: ["Chúng tôi làm bài kiểm tra từ vựng 5 phút vào đầu giờ học.", "Chơi một bài trắc nghiệm tiếng Anh trực tuyến tương tác."] },
    { word: "grade", phonetic: "/ɡreɪd/", def: "A mark indicating the quality of a student's work.", defVn: "điểm số, cấp lớp học", pos: "noun", ex: ["He received an excellent 'A' grade on his essay.", "My sister is in the fifth grade of primary school."], exVn: ["Cậu ấy đã nhận điểm 'A' xuất sắc cho bài luận của mình.", "Em gái tôi đang học lớp năm trường tiểu học."] },
    { word: "homework", phonetic: "/ˈhoʊmwɜːrk/", def: "Schoolwork that a student is required to do at home.", defVn: "bài tập về nhà", pos: "noun", ex: ["Finish your English homework before dinner time.", "The teacher assigned three reading exercises as homework."], exVn: ["Làm xong bài tập tiếng Anh về nhà trước giờ ăn tối nhé.", "Thầy giáo đã giao ba bài đọc hiểu làm bài tập về nhà."] },
    { word: "library", phonetic: "/ˈlaɪbreri/", def: "A building or room containing collections of books and periodicals for reading or borrowing.", defVn: "thư viện trường học", pos: "noun", ex: ["Please maintain complete silence in the study library.", "You can borrow up to five books from the school library."], exVn: ["Xin vui lòng giữ trật tự tuyệt đối trong thư viện tự học.", "Bạn có thể mượn tối đa năm cuốn sách từ thư viện trường."] },
    { word: "lesson", phonetic: "/ˈlesn/", def: "A period of learning or teaching.", defVn: "tiết học, bài học", pos: "noun", ex: ["Today's English lesson focuses on everyday conversations.", "The teacher gave an engaging science lesson."], exVn: ["Bài học tiếng Anh hôm nay tập trung vào giao tiếp hàng ngày.", "Thầy giáo đã giảng một bài học khoa học đầy lôi cuốn."] },
    { word: "subject", phonetic: "/ˈsʌbdʒɪkt/", def: "A branch of knowledge studied or taught in a system, such as math, history, or science.", defVn: "môn học trong chương trình", pos: "noun", ex: ["What is your favorite school subject? — I love English.", "Math and science are core compulsory subjects."], exVn: ["Môn học yêu thích của bạn ở trường là gì? — Tôi yêu tiếng Anh.", "Toán và khoa học là các môn học bắt buộc cốt lõi."] }
  ],

  // Theme 19: Sở thích & Thể thao (Hobbies & Sports)
  t_basic_hobbies_sports: [
    { word: "swimming", phonetic: "/ˈswɪmɪŋ/", def: "The sport or activity of propelling oneself through water using the limbs.", defVn: "môn bơi lội", pos: "noun", ex: ["Swimming in the cool pool is refreshing during summer.", "He won a gold medal in the 100-meter swimming race."], exVn: ["Bơi trong làn nước mát của hồ bơi rất sảng khoái vào mùa hè.", "Cậu ấy đã đoạt huy chương vàng cự ly bơi 100 mét."] },
    { word: "badminton", phonetic: "/ˈbædmɪntən/", def: "A game with rackets in which a shuttlecock is hit across a net.", defVn: "môn cầu lông", pos: "noun", ex: ["We play badminton in the park every morning at dawn.", "Badminton improves your quick reflexes and stamina."], exVn: ["Chúng tôi chơi cầu lông trong công viên vào mỗi sáng sớm.", "Chơi cầu lông giúp cải thiện phản xạ nhanh và sự dẻo dai."] },
    { word: "tennis", phonetic: "/ˈtenɪs/", def: "A racket sport that is played individually against a single opponent or between two teams of two players.", defVn: "môn quần vợt, khúc côn cầu", pos: "noun", ex: ["He practiced his tennis serve on the court for two hours.", "Grand Slam tennis tournaments are world-famous."], exVn: ["Anh ấy luyện cú giao bóng quần vợt trên sân suốt hai tiếng.", "Các giải đấu quần vợt Grand Slam nổi tiếng khắp thế giới."] },
    { word: "basketball", phonetic: "/ˈbæskɪtbɔːl/", def: "A game played between two teams of five players in which goals are scored by throwing a ball through a netted hoop.", defVn: "môn bóng rổ", pos: "noun", ex: ["He jumped high and shot the basketball through the hoop.", "Playing basketball helps teenagers grow taller."], exVn: ["Cậu ấy bật nhảy thật cao và ném quả bóng rổ vào rổ.", "Chơi bóng rổ giúp các bạn thiếu niên phát triển chiều cao."] },
    { word: "volleyball", phonetic: "/ˈvɑːlibɔːl/", def: "A game in which two teams use their hands to hit a large ball back and forth over a high net.", defVn: "môn bóng chuyền", pos: "noun", ex: ["Playing beach volleyball on the sand is energetic fun.", "She spiked the volleyball over the net with power."], exVn: ["Chơi bóng chuyền bãi biển trên cát rất vui và tràn đầy năng lượng.", "Cô ấy đập bóng chuyền qua lưới đầy uy lực."] },
    { word: "cycling", phonetic: "/ˈsaɪklɪŋ/", def: "The activity of riding a bicycle.", defVn: "môn đi xe đạp, đạp xe thể thao", pos: "noun", ex: ["Cycling around West Lake in the morning is wonderful.", "Weekend cycling through the countryside keeps you fit."], exVn: ["Đạp xe dạo quanh Hồ Tây vào buổi sáng thật tuyệt vời.", "Đạp xe cuối tuần qua vùng nông thôn giúp giữ dáng khỏe mạnh."] },
    { word: "hiking", phonetic: "/ˈhaɪkɪŋ/", def: "The activity of going for long, brisk walks, especially in the country.", defVn: "đi bộ đường dài leo núi, dã ngoại", pos: "noun", ex: ["We packed water and trail snacks for our mountain hiking trip.", "Hiking through Sapa's hills offers breathtaking views."], exVn: ["Chúng tôi chuẩn bị nước và đồ ăn nhẹ cho chuyến leo núi dã ngoại.", "Đi bộ dã ngoại qua các ngọn đồi Sa Pa mang lại cảnh đẹp mê hồn."] },
    { word: "camping", phonetic: "/ˈkæmpɪŋ/", def: "The activity of spending a vacation living in a tent.", defVn: "cắm trại ngoài trời", pos: "noun", ex: ["We set up our camping tents beside the peaceful lake.", "Roasting marshmallows over the camping fire is magical."], exVn: ["Chúng tôi dựng lều cắm trại bên bờ hồ thanh bình.", "Nướng kẹo dẻo trên đống lửa trại thật kỳ diệu."] },
    { word: "gardening", phonetic: "/ˈɡɑːrdnɪŋ/", def: "The activity of tending and cultivating a garden.", defVn: "thú vui làm vườn, trồng hoa cây cảnh", pos: "noun", ex: ["Gardening is a relaxing and peaceful weekend hobby.", "She grows organic herbs and bright flowers through gardening."], exVn: ["Làm vườn là một sở thích cuối tuần đầy thư thái và an yên.", "Cô ấy trồng các loại rau thơm hữu cơ và hoa tươi qua việc làm vườn."] },
    { word: "cooking", phonetic: "/ˈkʊkɪŋ/", def: "The practice or skill of preparing food by combining and heating ingredients.", defVn: "sở thích nấu ăn, nghệ thuật ẩm thực", pos: "noun", ex: ["Cooking traditional Vietnamese pho is her passion.", "He watches masterclass cooking videos online."], exVn: ["Nấu món phở truyền thống Việt Nam là niềm đam mê của cô.", "Anh ấy xem các video dạy nấu ăn bậc thầy trên mạng."] },
    { word: "reading", phonetic: "/ˈriːdɪŋ/", def: "The action or skill of reading written or printed matter.", defVn: "thói quen đọc sách", pos: "noun", ex: ["Reading twenty pages of an English book daily expands your mind.", "She loves reading novels curled up with warm tea."], exVn: ["Đọc 20 trang sách tiếng Anh mỗi ngày mở mang trí óc của bạn.", "Cô ấy thích đọc tiểu thuyết trong lúc nhâm nhi tách trà ấm."] },
    { word: "painting", phonetic: "/ˈpeɪntɪŋ/", def: "The action or art of using paint to produce pictures.", defVn: "nghệ thuật hội họa, vẽ tranh", pos: "noun", ex: ["Watercolor painting is a creative and expressive hobby.", "She displayed her scenic oil paintings in a gallery."], exVn: ["Vẽ tranh màu nước là một sở thích sáng tạo và giàu cảm xúc.", "Cô ấy đã trưng bày các bức tranh sơn dầu phong cảnh tại phòng tranh."] },
    { word: "dancing", phonetic: "/ˈdænsɪŋ/", def: "The activity of dancing for pleasure or in order to entertain others.", defVn: "khiêu vũ, nhảy múa", pos: "noun", ex: ["Traditional folk dancing is celebrated during festivals.", "Dancing to lively music improves your cardiovascular health."], exVn: ["Những điệu múa dân gian truyền thống được biểu diễn trong dịp lễ hội.", "Nhảy múa theo điệu nhạc sôi động giúp nâng cao sức khỏe tim mạch."] },
    { word: "chess", phonetic: "/tʃes/", def: "A board game of strategic skill for two players, played on a checkered board.", defVn: "môn cờ vua (chiến thuật)", pos: "noun", ex: ["Playing chess sharpens strategic thinking and concentration.", "He checkmated his opponent's king in thirty moves."], exVn: ["Chơi cờ vua giúp rèn luyện tư duy chiến lược và sự tập trung.", "Anh ấy đã chiếu hết vua của đối thủ chỉ sau 30 nước đi."] },
    { word: "guitar", phonetic: "/ɡɪˈtɑːr/", def: "A stringed musical instrument, with a fretted fingerboard and six strings.", defVn: "đàn ghi-ta", pos: "noun", ex: ["He learned to strum chords on his acoustic guitar.", "Playing guitar by the campfire brought everyone together."], exVn: ["Cậu ấy học cách gảy hợp âm trên chiếc đàn ghi-ta mộc.", "Chơi đàn ghi-ta bên đống lửa trại gắn kết tất cả mọi người lại gần nhau."] }
  ],

  // Theme 20: Mua sắm & Tiền tệ (Shopping & Money)
  t_basic_shopping_money: [
    { word: "wallet", phonetic: "/ˈwɑːlɪt/", def: "A pocket-sized, flat, folding holder for money and plastic cards.", defVn: "chiếc ví tiền, bóp đựng tiền", pos: "noun", ex: ["Keep your cash, driver's license, and ID in your leather wallet.", "He took out his wallet to pay for coffee."], exVn: ["Giữ tiền mặt, bằng lái xe và căn cước trong chiếc ví da nhé.", "Anh ấy rút ví ra để trả tiền cà phê."] },
    { word: "purse", phonetic: "/pɜːrs/", def: "A small bag used especially by women for holding coins and currency.", defVn: "ví nữ cầm tay, túi xách nhỏ", pos: "noun", ex: ["She put her lip balm and coins back into her designer purse.", "Her stylish red purse matched her shoes."], exVn: ["Cô ấy cất son dưỡng và tiền xu vào chiếc ví cầm tay hàng hiệu.", "Chiếc ví đỏ sành điệu của cô ấy rất tông xuyệt tông với đôi giày."] },
    { word: "coin", phonetic: "/kɔɪn/", def: "A flat, typically round piece of metal with an official stamp, used as money.", defVn: "đồng tiền xu kim loại", pos: "noun", ex: ["Drop a metal coin into the vending machine for soda.", "He collected vintage foreign coins from his travels."], exVn: ["Thả một đồng xu kim loại vào máy bán hàng tự động để lấy nước.", "Anh ấy sưu tầm những đồng xu cổ từ các chuyến du lịch."] },
    { word: "bill", phonetic: "/bɪl/", def: "A printed or written statement of the money owed for goods or services.", defVn: "hóa đơn thanh toán, tờ tiền giấy", pos: "noun", ex: ["Can we have the restaurant bill, please?", "Check the electric bill every month."], exVn: ["Làm ơn cho chúng tôi xin hóa đơn thanh toán nhé?", "Kiểm tra hóa đơn tiền điện vào mỗi tháng."] },
    { word: "receipt", phonetic: "/rɪˈsiːt/", def: "A written acknowledgment of having received a specified amount of money or goods.", defVn: "biên lai, hóa đơn mua hàng", pos: "noun", ex: ["Always keep your store receipt in case you need an exchange.", "The cashier handed me the purchase receipt."], exVn: ["Luôn giữ lại biên lai mua hàng đề phòng trường hợp cần đổi trả.", "Người thu ngân đưa cho tôi hóa đơn mua hàng."] },
    { word: "cash", phonetic: "/kæʃ/", def: "Money in coins or notes, as distinct from checks or credit cards.", defVn: "tiền mặt", pos: "noun", ex: ["Do you accept credit cards, or cash only?", "I withdrew fifty dollars in cash from the ATM."], exVn: ["Cửa hàng chấp nhận quẹt thẻ hay chỉ nhận tiền mặt ạ?", "Tôi đã rút 50 đô la tiền mặt từ cây ATM."] },
    { word: "credit card", phonetic: "/ˈkredɪt kɑːrd/", def: "A small plastic card allowing the holder to purchase goods on credit.", defVn: "thẻ tín dụng", pos: "noun", ex: ["Tap your contactless credit card on the payment machine.", "Credit cards offer cashback rewards on grocery shopping."], exVn: ["Chạm thẻ tín dụng không tiếp xúc lên máy thanh toán nhé.", "Thẻ tín dụng có tính năng hoàn tiền khi mua sắm hàng tạp hóa."] },
    { word: "price", phonetic: "/praɪs/", def: "The amount of money expected, required, or given in payment for something.", defVn: "giá cả, mức giá", pos: "noun", ex: ["The price of this cotton shirt is twenty dollars.", "Look at the price tag before buying."], exVn: ["Mức giá của chiếc áo sơ mi cotton này là 20 đô la.", "Hãy nhìn vào mác giá trước khi mua sắm nhé."] },
    { word: "discount", phonetic: "/ˈdɪskaʊnt/", def: "A deduction from the usual cost of something.", defVn: "khoản giảm giá, chiết khấu", pos: "noun", ex: ["Students get a 20 percent discount on museum tickets.", "The year-end sale offers huge product discounts."], exVn: ["Học sinh sinh viên được giảm giá 20% khi mua vé bảo tàng.", "Đợt xả hàng cuối năm có nhiều ưu đãi giảm giá khủng."] },
    { word: "sale", phonetic: "/seɪl/", def: "An event for the rapid disposal of goods at reduced prices.", defVn: "đợt giảm giá, mùa khuyến mãi", pos: "noun", ex: ["The clothing store is having a massive summer sale.", "Items on sale are non-refundable."], exVn: ["Cửa hàng quần áo đang có đợt giảm giá mùa hè cực lớn.", "Các mặt hàng trong đợt sale không được hoàn tiền."] },
    { word: "customer", phonetic: "/ˈkʌstəmər/", def: "A person or organization that buys goods or services from a store or business.", defVn: "khách hàng, người mua hàng", pos: "noun", ex: ["The friendly shopkeeper greeted every customer with a smile.", "Customer satisfaction is our top priority."], exVn: ["Chủ cửa hàng thân thiện chào đón mọi khách hàng bằng nụ cười.", "Sự hài lòng của khách hàng là ưu tiên hàng đầu của chúng tôi."] },
    { word: "shopkeeper", phonetic: "/ˈʃɑːpkiːpər/", def: "An owner or manager of a small shop.", defVn: "chủ tiệm, người bán hàng", pos: "noun", ex: ["The helpful shopkeeper recommended fresh organic honey.", "Support local neighborhood shopkeepers."], exVn: ["Chủ tiệm nhiệt tình đã gợi ý mật ong hữu cơ tươi ngon.", "Hãy ủng hộ các chủ cửa hàng tạp hóa địa phương nhé."] },
    { word: "change", phonetic: "/tʃeɪndʒ/", def: "Coins or smaller banknotes given in exchange for a larger banknote.", defVn: "tiền lẻ thối lại, tiền thừa", pos: "noun", ex: ["Here is your coffee and three dollars in change.", "Keep the change as a tip, thank you!"], exVn: ["Cà phê của bạn đây và ba đô la tiền thừa nhé.", "Xin giữ lại tiền lẻ làm tiền tip, cảm ơn bạn!"] },
    { word: "expensive", phonetic: "/ɪkˈspensɪv/", def: "Costing a lot of money.", defVn: "đắt đỏ, giá cao", pos: "adj", ex: ["Dining at a Michelin-starred restaurant can be expensive.", "Designer luxury watches are very expensive."], exVn: ["Ăn tối tại nhà hàng gắn sao Michelin có thể rất đắt đỏ.", "Những chiếc đồng hồ hàng hiệu xa xỉ có giá rất cao."] },
    { word: "cheap", phonetic: "/tʃiːp/", def: "Costing little; inexpensive.", defVn: "rẻ, giá cả bình dân", pos: "adj", ex: ["Street food in Hanoi is both delicious and cheap.", "She found a cheap flight ticket online."], exVn: ["Ẩm thực đường phố Hà Nội vừa thơm ngon lại vừa rẻ.", "Cô ấy đã tìm được chiếc vé máy bay giá rẻ trực tuyến."] }
  ],

  // Theme 21: Cây cối & Hoa quả (Plants & Fruits)
  t_basic_plants_fruits: [
    { word: "watermelon", phonetic: "/ˈwɔːtərmelən/", def: "A large, round fruit with green rind and sweet red juicy pulp.", defVn: "quả dưa hấu", pos: "noun", ex: ["Chilled watermelon slices are delicious on hot summer days.", "Sweet seedless watermelon is a family favorite."], exVn: ["Những lát dưa hấu ướp lạnh rất ngon vào ngày hè nóng nực.", "Dưa hấu ngọt không hạt là món khoái khẩu của cả nhà."] },
    { word: "strawberry", phonetic: "/ˈstrɔːberi/", def: "A sweet soft red fruit with a seed-studded surface.", defVn: "quả dâu tây", pos: "noun", ex: ["Da Lat is famous for fresh sweet red strawberries.", "She topped her yogurt with ripe strawberries."], exVn: ["Đà Lạt nổi tiếng với những quả dâu tây đỏ mọng ngọt ngào.", "Cô ấy rắc dâu tây chín lên cốc sữa chua."] },
    { word: "grape", phonetic: "/ɡreɪp/", def: "A berry, typically green, purple, or black, growing in clusters on a grapevine.", defVn: "quả nho, chùm nho", pos: "noun", ex: ["A cluster of sweet purple grapes was on the fruit platter.", "Ninh Thuan is well-known for grape vineyards."], exVn: ["Một chùm nho tím ngọt ngào nằm trên đĩa hoa quả.", "Ninh Thuận nổi tiếng với những vườn nho trĩu quả."] },
    { word: "pineapple", phonetic: "/ˈpaɪnæpl/", def: "A large juicy tropical fruit consisting of edible yellow flesh and a tough spiky rind.", defVn: "quả dứa, quả thơm, quả khóm", pos: "noun", ex: ["Fresh pineapple juice is tart and refreshing.", "Add sliced pineapple to your sweet and sour soup."], exVn: ["Nước ép dứa tươi có vị chua ngọt thanh mát.", "Thêm vài lát thơm vào nồi canh chua nhé."] },
    { word: "mango", phonetic: "/ˈmæŋɡoʊ/", def: "A fleshy, oval yellowish-red tropical fruit that is eaten ripe or used green in pickles.", defVn: "quả xoài (chín / xanh)", pos: "noun", ex: ["Sweet ripe yellow mangoes smell heavenly.", "Green mango salad with dried beef is a popular street snack."], exVn: ["Những quả xoài cát chín vàng thơm ngát.", "Nộm xoài xanh thịt bò khô là món ăn vặt đường phố nổi tiếng."] },
    { word: "coconut", phonetic: "/ˈkoʊkənʌt/", def: "The large oval brown seed of a tropical palm, containing white flesh and sweet water.", defVn: "quả dừa, nước dừa tươi", pos: "noun", ex: ["Drinking fresh coconut water directly from the fruit is refreshing.", "Ben Tre is the coconut capital of Vietnam."], exVn: ["Uống nước dừa tươi trực tiếp từ quả rất sảng khoái.", "Bến Tre là thủ phủ dừa của Việt Nam."] },
    { word: "papaya", phonetic: "/pəˈpaɪə/", def: "An elongated tropical fruit with orange flesh and small black seeds.", defVn: "quả đu đủ", pos: "noun", ex: ["Sweet ripe papaya contains beneficial digestive enzymes.", "Green papaya is the main ingredient in traditional salads."], exVn: ["Đu đủ chín ngọt chứa nhiều men tiêu hóa có lợi.", "Đu đủ xanh là nguyên liệu chính trong món nộm truyền thống."] },
    { word: "dragon fruit", phonetic: "/ˈdræɡən fruːt/", def: "A tropical fruit with bright pink skin and sweet white or red flesh speckled with black seeds.", defVn: "quả thanh long (ruột trắng / ruột đỏ)", pos: "noun", ex: ["Red-fleshed dragon fruit has a vibrant magenta color.", "Dragon fruit is exported from Vietnam to many nations."], exVn: ["Thanh long ruột đỏ có màu đỏ tím rất rực rỡ.", "Thanh long được xuất khẩu từ Việt Nam sang nhiều quốc gia."] },
    { word: "durian", phonetic: "/ˈdʊriən/", def: "A large spiky tropical fruit with a strong distinctive odor and creamy custard-like flesh.", defVn: "quả sầu riêng (vua các loài quả)", pos: "noun", ex: ["Durian is famously known as the king of tropical fruits.", "The creamy golden flesh of durian has a rich aroma."], exVn: ["Sầu riêng nổi danh là vua của các loài hoa quả nhiệt đới.", "Múi sầu riêng vàng ươm béo ngậy tỏa hương thơm đậm đà."] },
    { word: "avocado", phonetic: "/ˌævəˈkɑːdoʊ/", def: "A pear-shaped fruit with a rough leathery skin, smooth oily edible flesh, and a large stone.", defVn: "quả bơ, trái bơ sáp", pos: "noun", ex: ["An avocado smoothie with condensed milk is rich and creamy.", "Spread mashed avocado on morning toast."], exVn: ["Sinh tố bơ sữa đặc béo ngậy và thơm ngon.", "Phết bơ dầm lên bánh mì nướng buổi sáng."] },
    { word: "bamboo", phonetic: "/ˌbæmˈbuː/", def: "A giant woody grass that grows chiefly in the tropics and is used for construction and crafts.", defVn: "cây tre, cây trúc", pos: "noun", ex: ["Green bamboo groves symbolize resilience in Vietnamese culture.", "Bamboo shoots are a delicious soup ingredient."], exVn: ["Những lũy tre xanh tượng trưng cho sự kiên cường trong văn hóa Việt.", "Măng tre là nguyên liệu nấu canh rất thơm ngon."] },
    { word: "lotus", phonetic: "/ˈloʊtəs/", def: "An aquatic plant with large pink or white flowers and round floating leaves; national flower.", defVn: "hoa sen (quốc hoa Việt Nam)", pos: "noun", ex: ["The pink lotus rises elegantly above the muddy pond.", "Lotus tea has a delicate and soothing fragrance."], exVn: ["Bông sen hồng vươn lên thanh cao trên mặt hồ bùn.", "Trà ướp hoa sen có hương thơm tao nhã và thanh tịnh."] },
    { word: "rose", phonetic: "/roʊz/", def: "A woody perennial flowering plant with prickles and fragrant flowers.", defVn: "hoa hồng (biểu tượng tình yêu)", pos: "noun", ex: ["He presented a bouquet of fragrant red roses to his mother.", "Dewdrops sparkled on the rose petals."], exVn: ["Anh ấy tặng mẹ một bó hoa hồng đỏ ngát hương.", "Những giọt sương mai lấp lánh trên từng cánh hoa hồng."] },
    { word: "sunflower", phonetic: "/ˈsʌnflaʊər/", def: "A tall plant with a very large golden-yellow flower head that turns towards the sun.", defVn: "hoa hướng dương (hướng về mặt trời)", pos: "noun", ex: ["A field of golden sunflowers swayed in the gentle wind.", "Sunflowers always track the warm morning sunlight."], exVn: ["Cánh đồng hoa hướng dương vàng rực đung đưa trong gió nhẹ.", "Hoa hướng dương luôn hướng theo ánh nắng ban mai ấm áp."] },
    { word: "root", phonetic: "/ruːt/", def: "The part of a plant which attaches it to the ground and conveys water and nutrients.", defVn: "rễ cây (hút nước và chất dinh dưỡng)", pos: "noun", ex: ["Deep tree roots anchor the tall tree during storms.", "Ginger is a flavorful underground root."], exVn: ["Bộ rễ cây ăn sâu giúp giữ vững thân cây trong giông bão.", "Gừng là một loại củ rễ dưới lòng đất rất thơm."] }
  ],

  // Theme 22: Sức khỏe & Y tế (Health & Medical)
  t_basic_health_medical: [
    { word: "headache", phonetic: "/ˈhedeɪk/", def: "A continuous pain in the head.", defVn: "cơn đau đầu, nhức đầu", pos: "noun", ex: ["I have a mild headache after working at the computer all day.", "Drink plenty of water to relieve tension headaches."], exVn: ["Tôi bị đau đầu nhẹ sau khi làm việc trên máy tính cả ngày.", "Uống nhiều nước để giảm những cơn đau đầu do căng thẳng."] },
    { word: "fever", phonetic: "/ˈfiːvər/", def: "An abnormally high body temperature, usually accompanied by shivering and headache.", defVn: "cơn sốt cao", pos: "noun", ex: ["The thermometer showed a fever of 38.5 degrees Celsius.", "Rest in bed and take fever medication."], exVn: ["Nhiệt kế chỉ nhiệt độ sốt 38.5 độ C.", "Hãy nghỉ ngơi trên giường và uống thuốc hạ sốt nhé."] },
    { word: "cough", phonetic: "/kɔːf/", def: "Expelling air from the lungs with a sudden sharp sound.", defVn: "cơn ho, tiếng ho", pos: "noun", ex: ["Warm honey lemon tea soothes a dry cough.", "Cover your mouth with a tissue when you cough."], exVn: ["Trà chanh mật ong ấm giúp làm dịu cơn ho khan.", "Hãy che miệng bằng khăn giấy khi bạn ho nhé."] },
    { word: "sore throat", phonetic: "/sɔːr θroʊt/", def: "A condition marked by pain in the throat, typically caused by inflammation.", defVn: "viêm họng, đau rát cổ họng", pos: "noun", ex: ["Gargling with warm salt water relieves a sore throat.", "I have a sore throat and trouble swallowing."], exVn: ["Súc miệng bằng nước muối ấm giúp làm dịu cơn đau họng.", "Tôi bị đau họng và cảm thấy khó nuốt."] },
    { word: "stomachache", phonetic: "/ˈstʌməkeɪk/", def: "A pain in a person's belly or stomach.", defVn: "cơn đau bụng, đau dạ dày", pos: "noun", ex: ["Eating spoiled street food can cause a stomachache.", "He took an antacid to relieve his stomachache."], exVn: ["Ăn đồ ăn ôi thiu có thể gây đau bụng.", "Anh ấy uống thuốc kháng axit để giảm đau dạ dày."] },
    { word: "toothache", phonetic: "/ˈtuːθeɪk/", def: "Pain in or around a tooth.", defVn: "cơn đau răng, nhức răng", pos: "noun", ex: ["See a dentist immediately if you have a throbbing toothache.", "Clove oil provides temporary relief for toothache."], exVn: ["Hãy đi khám nha sĩ ngay nếu bạn bị đau nhức răng.", "Tinh dầu đinh hương giúp giảm đau răng tạm thời."] },
    { word: "flu", phonetic: "/fluː/", def: "Influenza, a common viral infection that can be deadly, especially in high-risk groups.", defVn: "bệnh cảm cúm (do vi-rút)", pos: "noun", ex: ["Annual flu vaccinations help protect vulnerable elderly people.", "He stayed home from work to recover from the seasonal flu."], exVn: ["Tiêm vắc-xin cúm hàng năm giúp bảo vệ người cao tuổi.", "Anh ấy xin nghỉ làm ở nhà để hồi phục sau đợt cảm cúm mùa."] },
    { word: "medicine", phonetic: "/ˈmedɪsn/", def: "The science or practice of diagnosis and treatment; a drug or other preparation.", defVn: "thuốc uống, dược phẩm", pos: "noun", ex: ["Take this prescribed medicine three times daily after meals.", "Keep all medicines out of reach of children."], exVn: ["Uống thuốc theo đơn này 3 lần mỗi ngày sau bữa ăn nhé.", "Để mọi loại thuốc xa tầm tay trẻ em."] },
    { word: "bandage", phonetic: "/ˈbændɪdʒ/", def: "A strip of woven material used to bind up a wound or sprain.", defVn: "băng gạc cứu thương, băng cá nhân", pos: "noun", ex: ["The nurse wrapped a clean sterile bandage around the wound.", "Apply an adhesive bandage on small paper cuts."], exVn: ["Y tá quấn một dải băng gạc vô trùng quanh vết thương.", "Dán băng cá nhân lên những vết đứt tay nhỏ do giấy."] },
    { word: "injection", phonetic: "/ɪnˈdʒekʃn/", def: "An act of administering a liquid, especially a drug, into a person's body using a syringe.", defVn: "mũi tiêm thuốc, tiêm phòng", pos: "noun", ex: ["The routine vaccine injection takes just a split second.", "Breathe deeply and relax your arm during the injection."], exVn: ["Mũi tiêm vắc-xin định kỳ chỉ mất một tích tắc.", "Hãy hít thở sâu và thả lỏng cánh tay trong lúc tiêm nhé."] },
    { word: "prescription", phonetic: "/prɪˈskrɪpʃn/", def: "An instruction written by a medical practitioner that authorizes a patient to be provided a medicine.", defVn: "đơn thuốc, toa thuốc của bác sĩ", pos: "noun", ex: ["The doctor wrote a prescription for antibiotics.", "Take your doctor's prescription to the pharmacy."], exVn: ["Bác sĩ đã kê một đơn thuốc kháng sinh.", "Mang đơn thuốc của bác sĩ ra hiệu thuốc nhé."] },
    { word: "checkup", phonetic: "/ˈtʃekʌp/", def: "A thorough medical examination, especially a routine one.", defVn: "khám sức khỏe tổng quát định kỳ", pos: "noun", ex: ["Schedule an annual health checkup to stay healthy.", "The routine medical checkup took two hours."], exVn: ["Lên lịch khám sức khỏe tổng quát hàng năm để luôn khỏe mạnh.", "Buổi khám sức khỏe định kỳ mất hai tiếng."] },
    { word: "allergy", phonetic: "/ˈælərdʒi/", def: "A damaging immune response by the body to a substance, especially pollen, fur, a particular food.", defVn: "dị ứng (thức ăn, phấn hoa, thời tiết)", pos: "noun", ex: ["She has a severe allergy to peanuts and seafood.", "Inform the restaurant waiter of any food allergies."], exVn: ["Cô ấy bị dị ứng nghiêm trọng với đậu phộng và hải sản.", "Hãy báo cho nhân viên nhà hàng biết nếu bạn có dị ứng thức ăn."] },
    { word: "healthy", phonetic: "/ˈhelθi/", def: "In good health; possessing physical well-being.", defVn: "khỏe mạnh, lành mạnh", pos: "adj", ex: ["Eating fresh vegetables and exercising daily keeps you healthy.", "A balanced diet leads to a long, healthy life."], exVn: ["Ăn rau tươi và tập thể dục hàng ngày giúp bạn luôn khỏe mạnh.", "Chế độ ăn uống cân bằng mang lại cuộc sống trường thọ, khỏe khoắn."] },
    { word: "exercise", phonetic: "/ˈeksərsaɪz/", def: "Activity requiring physical effort, carried out to sustain or improve health and fitness.", defVn: "tập thể dục, rèn luyện thân thể", pos: "noun", ex: ["Thirty minutes of moderate exercise daily boosts heart health.", "Regular exercise reduces daily stress."], exVn: ["30 phút tập thể dục vừa sức mỗi ngày giúp nâng cao sức khỏe tim mạch.", "Tập thể dục đều đặn giúp giảm căng thẳng hàng ngày."] }
  ],

  // Theme 23: Dụng cụ nhà bếp (Kitchen Utensils)
  t_basic_kitchen_utensils: [
    { word: "frying pan", phonetic: "/ˈfraɪɪŋ pæn/", def: "A shallow pan with a long handle, used for frying food.", defVn: "chảo chống dính, chảo rán", pos: "noun", ex: ["Heat a spoonful of olive oil in the nonstick frying pan.", "Flip the egg pancake gently in the pan."], exVn: ["Làm nóng một thìa dầu ô-liu trong chảo rán chống dính.", "Lật nhẹ chiếc bánh trứng trong chảo."] },
    { word: "saucepan", phonetic: "/ˈsɔːspæn/", def: "A deep cooking pan, typically round, made of metal, and with one long handle and a lid.", defVn: "nồi nấu canh có tay cầm, xoong nhỏ", pos: "noun", ex: ["Boil chicken broth in the stainless steel saucepan.", "Simmer the pasta sauce in the saucepan for ten minutes."], exVn: ["Đun sôi nước dùng gà trong chiếc xoong inox.", "Đun liu riu nước sốt mì Ý trong nồi trong mười phút."] },
    { word: "pot", phonetic: "/pɑːt/", def: "A container, typically rounded or cylindrical and of ceramic or metal, used for cooking.", defVn: "nồi nấu lớn, nồi hầm", pos: "noun", ex: ["Mom simmered a big pot of fragrant beef pho overnight.", "Cover the cooking pot with its glass lid."], exVn: ["Mẹ ninh một nồi phở bò thơm lừng qua đêm.", "Đậy vung kính lên chiếc nồi nấu ăn nhé."] },
    { word: "knife", phonetic: "/naɪf/", def: "An instrument composed of a blade fixed into a handle, used for cutting.", defVn: "con dao (thái, cắt gọt)", pos: "noun", ex: ["Always be careful when using a sharp kitchen chef knife.", "Use a bread knife to slice the baguette."], exVn: ["Luôn cẩn thận khi sử dụng dao làm bếp sắc bén nhé.", "Dùng dao cắt bánh mì để cắt lát bánh mì que."] },
    { word: "cutting board", phonetic: "/ˈkʌtɪŋ bɔːrd/", def: "A durable board on which to place material for cutting.", defVn: "thớt thái (gỗ / nhựa)", pos: "noun", ex: ["Chop garlic and onions on the wooden cutting board.", "Use separate cutting boards for meat and fresh fruits."], exVn: ["Băm tỏi và hành tây trên thớt gỗ.", "Dùng thớt riêng cho thịt sống và hoa quả tươi nhé."] },
    { word: "spoon", phonetic: "/spuːn/", def: "An implement consisting of a small, shallow oval or round bowl on a long handle, used for eating.", defVn: "chiếc thìa, muỗng", pos: "noun", ex: ["Stir two teaspoons of honey into your warm tea with a spoon.", "Use a soup spoon for hot noodles."], exVn: ["Dùng thìa khuấy hai thìa mật ong vào tách trà ấm.", "Dùng muỗng súp để ăn bún phở nóng."] },
    { word: "fork", phonetic: "/fɔːrk/", def: "An implement with two or more prongs used for lifting food to the mouth or holding it when cutting.", defVn: "chiếc nĩa, dĩa ăn", pos: "noun", ex: ["Twirl spaghetti noodles neatly around your fork.", "Place the fork on the left side of the dinner plate."], exVn: ["Cuộn những sợi mì spaghetti gọn gàng quanh chiếc nĩa.", "Đặt nĩa ở phía bên trái đĩa ăn tối nhé."] },
    { word: "chopsticks", phonetic: "/ˈtʃɑːpstɪks/", def: "A pair of thin sticks that are held in one hand and used as eating utensils.", defVn: "đôi đũa ăn cơm", pos: "noun", ex: ["Bamboo chopsticks are traditional dining utensils across Asia.", "Practice holding chopsticks correctly between your fingers."], exVn: ["Đũa tre là dụng cụ ăn uống truyền thống khắp châu Á.", "Tập cầm đũa đúng cách giữa các ngón tay nhé."] },
    { word: "bowl", phonetic: "/boʊl/", def: "A round, deep dish used for food or liquid.", defVn: "bát ăn cơm, tô canh", pos: "noun", ex: ["She served hot vegetable soup in a ceramic bowl.", "Eat a wholesome bowl of oatmeal for breakfast."], exVn: ["Cô ấy múc canh rau củ nóng hổi vào chiếc bát sứ.", "Ăn một bát yến mạch bổ dưỡng cho bữa sáng."] },
    { word: "plate", phonetic: "/pleɪt/", def: "A flat dish, typically circular and made of china, from which food is eaten or served.", defVn: "chiếc đĩa ăn", pos: "noun", ex: ["Arrange crispy spring rolls beautifully on the serving plate.", "Clear the dinner plates from the dining table."], exVn: ["Xếp nem rán giòn rụm thật đẹp mắt lên đĩa phục vụ.", "Dọn đĩa ăn tối khỏi bàn ăn nhé."] },
    { word: "cup", phonetic: "/kʌp/", def: "A small bowl-shaped container for drinking from, typically having a handle.", defVn: "chiếc cốc, tách uống nước/trà", pos: "noun", ex: ["Enjoy a hot cup of green tea in the morning.", "Pour milk into the coffee cup."], exVn: ["Thưởng thức một tách trà xanh nóng vào buổi sáng.", "Rót sữa vào tách cà phê nhé."] },
    { word: "glass", phonetic: "/ɡlæs/", def: "A drinking container made from glass.", defVn: "chiếc ly thủy tinh", pos: "noun", ex: ["Drink eight glasses of clean water every day.", "She poured fresh orange juice into a tall glass."], exVn: ["Hãy uống tám ly nước sạch mỗi ngày nhé.", "Cô ấy rót nước cam tươi vào chiếc ly thủy tinh cao."] },
    { word: "kettle", phonetic: "/ˈketl/", def: "A container or device in which water is boiled, having a lid, spout, and handle.", defVn: "ấm đun nước siêu tốc", pos: "noun", ex: ["Boil water in the electric kettle to brew fragrant tea.", "The stainless steel kettle whistled on the stove."], exVn: ["Đun nước trong ấm siêu tốc để pha trà thơm.", "Chiếc ấm inox reo vang trên bếp ga."] },
    { word: "microwave", phonetic: "/ˈmaɪkrəweɪv/", def: "An oven that uses microwaves to cook or heat food quickly.", defVn: "lò vi sóng (hâm nóng thức ăn)", pos: "noun", ex: ["Heat leftover soup in the microwave for two minutes.", "Use microwave-safe ceramic containers."], exVn: ["Hâm nóng lại canh thừa trong lò vi sóng hai phút.", "Dùng hộp đựng bằng sứ an toàn cho lò vi sóng nhé."] },
    { word: "refrigerator", phonetic: "/rɪˈfrɪdʒəreɪtər/", def: "An appliance in which food and drinks are kept cool or frozen; fridge.", defVn: "tủ lạnh gia đình", pos: "noun", ex: ["Store fresh milk and green vegetables inside the refrigerator.", "Close the refrigerator door tightly."], exVn: ["Bảo quản sữa tươi và rau xanh trong tủ lạnh nhé.", "Đóng chặt cánh cửa tủ lạnh lại nhé."] }
  ],

  // Theme 24: Văn phòng & Công nghệ (Office & Basic Tech)
  t_basic_office_tech: [
    { word: "laptop", phonetic: "/ˈlæptɑːp/", def: "A computer that is portable and suitable for use while traveling.", defVn: "máy tính xách tay, laptop", pos: "noun", ex: ["She carries a lightweight laptop in her backpack to work.", "Charge your laptop battery before traveling."], exVn: ["Cô ấy mang chiếc laptop mỏng nhẹ trong ba lô đi làm.", "Sạc pin máy tính xách tay trước khi đi công tác nhé."] },
    { word: "mouse", phonetic: "/maʊs/", def: "A hand-operated electronic device that controls the cursor on a computer screen.", defVn: "con chuột máy tính", pos: "noun", ex: ["Click the left button on your wireless mouse to open the file.", "A comfortable ergonomic mouse prevents wrist strain."], exVn: ["Bấm nút chuột trái trên chuột không dây để mở tệp tin.", "Chuột công thái học êm ái giúp tránh mỏi cổ tay."] },
    { word: "keyboard", phonetic: "/ˈkiːbɔːrd/", def: "A panel of keys that operate a computer or typewriter.", defVn: "bàn phím máy tính", pos: "noun", ex: ["Practice touch typing on the mechanical keyboard.", "Clean dust between keyboard keys regularly."], exVn: ["Luyện gõ bàn phím mười ngón trên bàn phím cơ.", "Vệ sinh bụi bẩn giữa các phím bàn phím thường xuyên nhé."] },
    { word: "screen", phonetic: "/skriːn/", def: "A flat panel or area on an electronic device on which images and data are displayed.", defVn: "màn hình hiển thị", pos: "noun", ex: ["Take short eye breaks away from the computer screen every twenty minutes.", "The high-resolution screen displays crisp colors."], exVn: ["Hãy cho mắt nghỉ ngơi cách xa màn hình máy tính 20 phút một lần.", "Màn hình độ phân giải cao hiển thị màu sắc sắc nét."] },
    { word: "printer", phonetic: "/ˈprɪntər/", def: "A machine for printing text or pictures on paper, especially by a computer.", defVn: "máy in tài liệu", pos: "noun", ex: ["The office printer prints double-sided documents fast.", "Load fresh A4 paper into the printer tray."], exVn: ["Máy in văn phòng in tài liệu hai mặt rất nhanh chóng.", "Nạp thêm giấy A4 mới vào khay máy in nhé."] },
    { word: "email", phonetic: "/ˈiːmeɪl/", def: "Messages distributed by electronic means from one computer user to one or more recipients.", defVn: "thư điện tử, email", pos: "noun", ex: ["Send the project summary via email before Friday afternoon.", "Check your email inbox for the meeting invitation."], exVn: ["Gửi tóm tắt dự án qua thư điện tử trước chiều thứ Sáu.", "Kiểm tra hộp thư đến để nhận thư mời họp nhé."] },
    { word: "password", phonetic: "/ˈpæswɜːrd/", def: "A secret word or phrase that must be used to gain admission to a computer network.", defVn: "mật khẩu bảo mật", pos: "noun", ex: ["Create a strong password containing letters, numbers, and symbols.", "Never share your secret account password with anyone."], exVn: ["Tạo mật khẩu mạnh gồm chữ cái, số và ký tự đặc biệt.", "Tuyệt đối không chia sẻ mật khẩu tài khoản bí mật cho ai."] },
    { word: "wifi", phonetic: "/ˈwaɪfaɪ/", def: "A facility allowing computers, smartphones, or other devices to connect to the internet.", defVn: "mạng không dây, wifi", pos: "noun", ex: ["What is the wifi password for this coffee shop?", "High-speed optical wifi keeps video calls smooth."], exVn: ["Mật khẩu wifi của quán cà phê này là gì vậy bạn?", "Wifi cáp quang tốc độ cao giúp các cuộc gọi video mượt mà."] },
    { word: "internet", phonetic: "/ˈɪntərnet/", def: "A global computer network providing a variety of information and communication facilities.", defVn: "mạng internet toàn cầu", pos: "noun", ex: ["You can learn English anytime, anywhere thanks to the internet.", "Connect to the internet to stream English podcasts."], exVn: ["Bạn có thể học tiếng Anh mọi lúc mọi nơi nhờ mạng internet.", "Kết nối internet để nghe các kênh podcast tiếng Anh."] },
    { word: "document", phonetic: "/ˈdɑːkjumənt/", def: "A piece of written, printed, or electronic matter that provides information or evidence.", defVn: "tài liệu, văn bản", pos: "noun", ex: ["Save the Word document after completing your edits.", "Attach the required documents to your job application."], exVn: ["Lưu văn bản Word lại sau khi hoàn tất chỉnh sửa.", "Đính kèm các tài liệu yêu cầu vào hồ sơ xin việc của bạn."] },
    { word: "folder", phonetic: "/ˈfoʊldər/", def: "A digital directory for holding files and subfolders on a computer.", defVn: "thư mục dữ liệu máy tính", pos: "noun", ex: ["Create a new folder on your desktop called 'English Study'.", "Organize your audio files into organized folders."], exVn: ["Tạo một thư mục mới trên màn hình chính tên là 'Học tiếng Anh'.", "Sắp xếp các tệp âm thanh vào các thư mục gọn gàng."] },
    { word: "file", phonetic: "/faɪl/", def: "A folder or box for holding loose papers, or a digital resource on a computer.", defVn: "tệp tin, tệp dữ liệu", pos: "noun", ex: ["Download the PDF study file from the learning portal.", "Back up your essential project files on cloud storage."], exVn: ["Tải tệp tài liệu PDF từ cổng học tập nhé.", "Sao lưu các tệp dữ liệu quan trọng lên bộ nhớ đám mây."] },
    { word: "desk", phonetic: "/desk/", def: "A piece of furniture with a flat or sloped surface, typically with drawers, at which one can read or write.", defVn: "bàn làm việc, bàn học", pos: "noun", ex: ["Keep your study desk organized and free of clutter.", "He placed his laptop and coffee mug on the wooden desk."], exVn: ["Hãy giữ bàn học của bạn ngăn nắp và không bừa bộn.", "Anh ấy đặt laptop và cốc cà phê lên bàn làm việc gỗ."] },
    { word: "meeting", phonetic: "/ˈmiːtɪŋ/", def: "An assembly of people for a particular purpose, especially for formal discussion.", defVn: "cuộc họp, buổi họp công việc", pos: "noun", ex: ["The weekly team meeting starts promptly at 9:00 AM.", "Take active notes during the client meeting."], exVn: ["Cuộc họp nhóm hàng tuần bắt đầu đúng 9 giờ sáng.", "Hãy chủ động ghi chép trong suốt buổi họp với khách hàng."] },
    { word: "software", phonetic: "/ˈsɔːftwer/", def: "The programs and other operating information used by a computer.", defVn: "phần mềm máy tính / ứng dụng", pos: "noun", ex: ["This English vocabulary software helps you memorize words fast.", "Install the latest software update for security."], exVn: ["Phần mềm từ vựng tiếng Anh này giúp bạn nhớ từ rất nhanh.", "Cài đặt bản cập nhật phần mềm mới nhất để bảo mật."] }
  ],

  // Theme 25: Thành phố & Công trình (City & Buildings)
  t_basic_city_buildings: [
    { word: "skyscraper", phonetic: "/ˈskaɪskreɪpər/", def: "A very tall building of many stories.", defVn: "tòa nhà chọc trời, cao ốc", pos: "noun", ex: ["Landmark 81 is the tallest modern skyscraper in Vietnam.", "Gaze up at the glittering glass skyscrapers in downtown."], exVn: ["Landmark 81 là tòa nhà chọc trời hiện đại cao nhất Việt Nam.", "Ngước nhìn những tòa cao ốc kính lấp lánh ở trung tâm thành phố."] },
    { word: "museum", phonetic: "/mjuˈziːəm/", def: "A building in which objects of historical, scientific, or artistic interest are preserved and exhibited.", defVn: "bảo tàng lịch sử / nghệ thuật", pos: "noun", ex: ["The National History Museum showcases Vietnam's rich heritage.", "Admission to the art museum is free on weekends."], exVn: ["Bảo tàng Lịch sử Quốc gia trưng bày di sản phong phú của Việt Nam.", "Vé vào cửa bảo tàng nghệ thuật miễn phí vào cuối tuần."] },
    { word: "theatre", phonetic: "/ˈθiːətər/", def: "A building or outdoor area in which plays and other dramatic performances are given.", defVn: "nhà hát lớn, rạp kịch", pos: "noun", ex: ["The historic Hanoi Opera Theatre is an architectural masterpiece.", "We watched an enchanting live musical at the theatre."], exVn: ["Nhà hát Lớn Hà Nội cổ kính là một kiệt tác kiến trúc.", "Chúng tôi xem một vở nhạc kịch sống động đầy mê hoặc tại nhà hát."] },
    { word: "cinema", phonetic: "/ˈsɪnəmə/", def: "A movie theatre; a place where films are shown.", defVn: "rạp chiếu phim", pos: "noun", ex: ["Let's grab buttery popcorn and watch the new blockbuster at the cinema.", "The cinema has modern surround sound."], exVn: ["Cùng mua bắp rang bơ và xem bộ phim bom tấn mới ở rạp chiếu phim nhé.", "Rạp chiếu phim có hệ thống âm thanh vòm hiện đại."] },
    { word: "stadium", phonetic: "/ˈsteɪdiəm/", def: "A sports ground with tiers of seats for spectators.", defVn: "sân vận động thể thao", pos: "noun", ex: ["My Dinh National Stadium was packed with forty thousand cheering fans.", "The soccer final was held in the grand stadium."], exVn: ["Sân vận động Quốc gia Mỹ Đình chật kín 40.000 cổ động viên cổ vũ.", "Trận chung kết bóng đá được tổ chức tại sân vận động lớn."] },
    { word: "tower", phonetic: "/ˈtaʊər/", def: "A tall, narrow building, either freestanding or forming part of a building such as a church or castle.", defVn: "tòa tháp, tháp cao", pos: "noun", ex: ["The ancient turtle tower sits peacefully in Hoan Kiem Lake.", "Climb to the top of the tower for a 360-degree panoramic view."], exVn: ["Tháp Rùa cổ kính nằm bình yên giữa lòng Hồ Hoàn Kiếm.", "Leo lên đỉnh tháp để ngắm nhìn toàn cảnh 360 độ tuyệt đẹp."] },
    { word: "monument", phonetic: "/ˈmɑːnjumənt/", def: "A statue, building, or other structure erected to commemorate a notable person or event.", defVn: "đài tưởng niệm, tượng đài lịch sử", pos: "noun", ex: ["Tourists laid flowers at the heroic war monument.", "The historic stone monument honors national heroes."], exVn: ["Du khách đặt hoa tại đài tưởng niệm chiến tranh anh hùng.", "Tượng đài đá lịch sử tôn vinh những vị anh hùng dân tộc."] },
    { word: "palace", phonetic: "/ˈpæləs/", def: "A large and impressive building forming the official residence of a ruler or president.", defVn: "cung điện, hoàng cung", pos: "noun", ex: ["The Imperial Palace in Hue is a designated UNESCO World Heritage site.", "Walk through the royal golden gates of the palace."], exVn: ["Hoàng cung Huế là di sản văn hóa thế giới được UNESCO công nhận.", "Bước qua cánh cổng hoàng gia mạ vàng của cung điện."] },
    { word: "temple", phonetic: "/ˈtempl/", def: "A building devoted to the worship, or regarded as the dwelling place, of a god or other deity.", defVn: "ngôi đền, ngôi chùa tôn nghiêm", pos: "noun", ex: ["People visit the Temple of Literature to pray for academic success.", "Incense smoke drifted gently through the peaceful temple."], exVn: ["Mọi người đến Văn Miếu - Quốc Tử Giám để cầu mong học hành đỗ đạt.", "Khói hương trầm bay nhè nhẹ trong ngôi đền thanh tịnh."] },
    { word: "church", phonetic: "/tʃɜːrtʃ/", def: "A building used for public Christian worship.", defVn: "nhà thờ lớn, giáo đường", pos: "noun", ex: ["St. Joseph's Cathedral is a famous Gothic church in Hanoi.", "Church bells rang harmoniously on Sunday morning."], exVn: ["Nhà thờ Lớn Hà Nội là một nhà thờ kiến trúc Gothic nổi tiếng.", "Chuông nhà thờ ngân vang du dương vào sáng Chủ Nhật."] },
    { word: "square", phonetic: "/skwer/", def: "An open, typically four-sided, area surrounded by buildings in a village, town, or city.", defVn: "quảng trường công cộng", pos: "noun", ex: ["Ba Dinh Square is the historic political center of Vietnam.", "Families stroll across the pedestrian city square in the evening."], exVn: ["Quảng trường Ba Đình là trung tâm chính trị lịch sử của Việt Nam.", "Các gia đình đi dạo trên quảng trường đi bộ thành phố vào buổi tối."] },
    { word: "street", phonetic: "/striːt/", def: "A public road in a city or town, typically with houses and buildings on one or both sides.", defVn: "đường phố, con phố", pos: "noun", ex: ["The bustling streets of the Old Quarter are filled with colorful lanterns.", "Cross the street carefully on the crosswalk."], exVn: ["Những con phố nhộn nhịp của Phố Cổ treo đầy đèn lồng rực rỡ.", "Hãy sang đường cẩn thận trên vạch kẻ đường nhé."] },
    { word: "avenue", phonetic: "/ˈævənuː/", def: "A broad road in a town or city, typically having trees at regular intervals along its sides.", defVn: "đại lộ thênh thang, đường lớn", pos: "noun", ex: ["Walk down the grand boulevard avenue under shady mahogany trees.", "The parade marched down the main avenue."], exVn: ["Đi dạo trên đại lộ thênh thang rợp bóng cây xà cừ mát rượi.", "Đoàn diễu hành tiến bước dọc theo đại lộ chính."] },
    { word: "alley", phonetic: "/ˈæli/", def: "A narrow passageway between or behind buildings.", defVn: "con ngõ, ngõ hẻm nhỏ", pos: "noun", ex: ["Hanoi's hidden culinary gems are tucked inside quiet alleys.", "Follow the narrow brick alley to find the traditional tea house."], exVn: ["Những nét ẩm thực tinh túy của Hà Nội ẩn mình trong những con ngõ nhỏ.", "Đi theo con ngõ lát gạch nhỏ để tìm quán trà truyền thống."] },
    { word: "bridge", phonetic: "/brɪdʒ/", def: "A structure carrying a road, path, or railway across a river.", defVn: "cây cầu bắc qua sông", pos: "noun", ex: ["Long Bien Bridge is an iconic historical bridge spanning the Red River.", "Vehicles crossed the suspension bridge smoothly."], exVn: ["Cầu Long Biên là cây cầu lịch sử biểu tượng bắc qua sông Hồng.", "Các phương tiện di chuyển êm ái qua cây cầu treo."] }
  ],

  // Theme 26: Tính cách & Phẩm chất (Personality Traits)
  t_basic_personality_traits: [
    { word: "kind", phonetic: "/kaɪnd/", def: "Having or showing a friendly, generous, and considerate nature.", defVn: "tốt bụng, nhân hậu, tử tế", pos: "adj", ex: ["She is always kind and helpful to her neighbors.", "A kind word can brighten someone's entire day."], exVn: ["Cô ấy luôn tốt bụng và hay giúp đỡ hàng xóm.", "Một lời nói tử tế có thể làm bừng sáng cả ngày của ai đó."] },
    { word: "honest", phonetic: "/ˈɑːnɪst/", def: "Free of deceit and untruthfulness; sincere.", defVn: "trung thực, thật thà, chân thành", pos: "adj", ex: ["An honest friend always speaks the truth with kindness.", "He gave an honest answer during the interview."], exVn: ["Một người bạn trung thực luôn nói sự thật bằng sự chân thành.", "Anh ấy đã đưa ra câu trả lời thật thà trong buổi phỏng vấn."] },
    { word: "brave", phonetic: "/breɪv/", def: "Ready to face and endure danger or pain; showing courage.", defVn: "dũng cảm, can đảm, kiên cường", pos: "adj", ex: ["Brave firefighters entered the burning house to rescue the puppy.", "Be brave and speak English with foreigners."], exVn: ["Những người lính cứu hỏa dũng cảm đã vào nhà cháy cứu chú cún.", "Hãy can đảm và tự tin nói tiếng Anh với người nước ngoài nhé."] },
    { word: "clever", phonetic: "/ˈklevər/", def: "Quick to understand, learn, and devise or apply ideas; intelligent.", defVn: "thông minh, lanh lợi, khéo léo", pos: "adj", ex: ["The clever student solved the difficult math puzzle in minutes.", "She found a clever solution to the software bug."], exVn: ["Học sinh thông minh đã giải câu đố toán hóc búa chỉ trong vài phút.", "Cô ấy đã tìm ra giải pháp khéo léo cho lỗi phần mềm."] },
    { word: "friendly", phonetic: "/ˈfrendli/", def: "Kind and pleasant.", defVn: "thân thiện, cởi mở, hòa đồng", pos: "adj", ex: ["Vietnamese people are warmly known for being friendly and hospitable.", "She gave a friendly wave to the new neighbors."], exVn: ["Người Việt Nam nổi tiếng là thân thiện và vô cùng hiếu khách.", "Cô ấy vẫy tay thân thiện chào những người hàng xóm mới."] },
    { word: "polite", phonetic: "/pəˈlaɪt/", def: "Having or showing behavior that is respectful and considerate of other people.", defVn: "lịch sự, lễ phép, nhã nhặn", pos: "adj", ex: ["Saying 'please' and 'thank you' is always polite.", "The polite young boy opened the door for elderly people."], exVn: ["Nói 'làm ơn' và 'cảm ơn' luôn là cử chỉ lịch sự.", "Cậu bé lễ phép đã giữ cửa cho người cao tuổi."] },
    { word: "creative", phonetic: "/kriˈeɪtɪv/", def: "Relating to or involving the imagination or original ideas.", defVn: "sáng tạo, giàu trí tưởng tượng", pos: "adj", ex: ["Creative thinkers invent new technologies that change the world.", "She expressed her feelings through creative watercolor art."], exVn: ["Những người có tư duy sáng tạo phát minh công nghệ thay đổi thế giới.", "Cô ấy thể hiện cảm xúc qua tranh màu nước đầy sáng tạo."] },
    { word: "cheerful", phonetic: "/ˈtʃɪrfl/", def: "Noticeably happy and optimistic.", defVn: "vui tươi, hớn hở, yêu đời", pos: "adj", ex: ["Her cheerful laugh brought warmth to the entire room.", "A cheerful morning greeting boosts team energy."], exVn: ["Tiếng cười vui tươi của cô ấy mang lại sự ấm áp cho cả căn phòng.", "Lời chào buổi sáng rạng rỡ nâng cao năng lượng làm việc của nhóm."] },
    { word: "hardworking", phonetic: "/ˌhɑːrdˈwɜːrkɪŋ/", def: "Tending to work with energy and commitment; diligent.", defVn: "chăm chỉ, siêng năng, cần cù", pos: "adj", ex: ["Hardworking students achieve their academic dreams through dedication.", "My father is a hardworking and devoted craftsman."], exVn: ["Những học sinh chăm chỉ đạt được ước mơ học tập qua sự tận tâm.", "Bố tôi là một người thợ thủ công cần cù và hết lòng với nghề."] },
    { word: "calm", phonetic: "/kɑːm/", def: "Not showing or feeling nervousness, anger, or other strong emotions.", defVn: "bình tĩnh, điềm đạm, trầm tĩnh", pos: "adj", ex: ["Stay calm and think clearly during challenging situations.", "His calm demeanor helped reassure the anxious team."], exVn: ["Hãy giữ bình tĩnh và suy nghĩ sáng suốt trong mọi tình huống thử thách.", "Phong thái điềm đạm của anh ấy giúp trấn an cả nhóm."] },
    { word: "funny", phonetic: "/ˈfʌni/", def: "Causing laughter or amusement; humorous.", defVn: "hài hước, vui tính, buồn cười", pos: "adj", ex: ["He told a funny joke that made everyone burst into laughter.", "My uncle is the funniest storyteller in the family."], exVn: ["Anh ấy kể câu chuyện cười khiến mọi người phá lên cười giòn giã.", "Chú tôi là người kể chuyện hài hước nhất trong gia đình."] },
    { word: "shy", phonetic: "/ʃaɪ/", def: "Being reserved or having or showing nervousness or timidity in the company of other people.", defVn: "nhút nhát, e thẹn, rụt rè", pos: "adj", ex: ["The shy child hid gently behind her mother's dress.", "Joining speech clubs helps shy students become confident."], exVn: ["Đứa trẻ nhút nhát nép nhẹ nhàng sau tà áo của mẹ.", "Tham gia câu lạc bộ thuyết trình giúp học sinh rụt rè trở nên tự tin."] },
    { word: "generous", phonetic: "/ˈdʒenərəs/", def: "Showing a readiness to give more of something, especially money, than is strictly necessary.", defVn: "hào phóng, rộng lượng, bao dung", pos: "adj", ex: ["He made a generous donation to support poor children's education.", "She is generous with sharing her study notes."], exVn: ["Ông ấy đã quyên góp hào phóng hỗ trợ việc học cho trẻ em nghèo.", "Cô ấy rất rộng lượng chia sẻ ghi chép bài học cho bạn bè."] },
    { word: "patient", phonetic: "/ˈpeɪʃnt/", def: "Able to accept or tolerate delays, problems, or suffering without becoming annoyed.", defVn: "kiên nhẫn, nhẫn nại", pos: "adj", ex: ["Learning a new language requires a patient daily mindset.", "The doctor was extremely patient while listening to patients."], exVn: ["Học một ngôn ngữ mới đòi hỏi tinh thần kiên nhẫn mỗi ngày.", "Bác sĩ vô cùng nhẫn nại khi lắng nghe bệnh nhân."] },
    { word: "confident", phonetic: "/ˈkɑːnfɪdənt/", def: "Feeling or showing certainty about something; self-assured.", defVn: "tự tin, đĩnh đạc", pos: "adj", ex: ["Stand tall and speak with a confident, clear voice.", "She felt confident after preparing thoroughly for the presentation."], exVn: ["Hãy đứng thẳng và nói bằng giọng điệu tự tin, rõ ràng.", "Cô ấy cảm thấy rất tự tin sau khi đã chuẩn bị kỹ cho bài thuyết trình."] }
  ],

  // Theme 27: Giới từ & Vị trí (Prepositions & Space)
  t_basic_prepositions_positions: [
    { word: "in", phonetic: "/ɪn/", def: "Expressing the situation of something that is enclosed or surrounded.", defVn: "ở trong, bên trong", pos: "preposition", ex: ["The keys are in my jacket pocket.", "We live in a lively apartment in Hanoi."], exVn: ["Chìa khóa nằm ở trong túi áo khoác của tôi.", "Chúng tôi sống trong một căn hộ nhộn nhịp ở Hà Nội."] },
    { word: "on", phonetic: "/ɑːn/", def: "Physically in contact with and supported by a surface.", defVn: "ở trên bề mặt", pos: "preposition", ex: ["The English dictionary is on the wooden study table.", "A lovely picture hangs on the wall."], exVn: ["Cuốn từ điển tiếng Anh nằm trên bàn học gỗ.", "Một bức tranh xinh xắn treo trên tường."] },
    { word: "under", phonetic: "/ˈʌndər/", def: "Extending or directly below something.", defVn: "ở dưới, phía dưới", pos: "preposition", ex: ["The fluffy cat is sleeping under the chair.", "We took shelter under a big umbrella during rain."], exVn: ["Chú mèo lông xù đang ngủ dưới gầm ghế.", "Chúng tôi trú dưới chiếc ô to trong cơn mưa."] },
    { word: "above", phonetic: "/əˈbʌv/", def: "At a higher level or layer than.", defVn: "ở phía trên cao (không tiếp xúc)", pos: "preposition", ex: ["The bright ceiling fan rotates above our heads.", "Birds fly high above the green forest."], exVn: ["Chiếc quạt trần quay đều phía trên đầu chúng tôi.", "Những chú chim bay cao phía trên khu rừng xanh."] },
    { word: "below", phonetic: "/bɪˈloʊ/", def: "At a lower level or layer than.", defVn: "ở phía dưới thấp", pos: "preposition", ex: ["The valley lies far below the mountain peak.", "Temperatures dropped below freezing last night."], exVn: ["Thung lũng nằm sâu phía dưới đỉnh núi.", "Nhiệt độ đã giảm xuống dưới mức đóng băng đêm qua."] },
    { word: "between", phonetic: "/bɪˈtwiːn/", def: "In the space separating two points, objects, or people.", defVn: "ở giữa hai vật / hai người", pos: "preposition", ex: ["The coffee shop is located between the bank and bookstore.", "Sit between your mom and dad."], exVn: ["Quán cà phê nằm ở giữa ngân hàng và hiệu sách.", "Ngồi vào giữa bố và mẹ nhé."] },
    { word: "among", phonetic: "/əˈmʌŋ/", def: "Situated more or less centrally in relation to several other things or persons.", defVn: "ở giữa nhiều người / nhiều vật (từ 3 trở lên)", pos: "preposition", ex: ["A small cozy wooden cabin stood among tall pine trees.", "She felt happy among her supportive classmates."], exVn: ["Một căn nhà gỗ nhỏ ấm cúng nằm giữa những cây thông cao.", "Cô ấy cảm thấy hạnh phúc giữa những người bạn cùng lớp."] },
    { word: "behind", phonetic: "/bɪˈhaɪnd/", def: "At the back of someone or something.", defVn: "ở phía sau, đằng sau", pos: "preposition", ex: ["The sun set behind the majestic mountain range.", "The playground is located behind our primary school."], exVn: ["Mặt trời lặn sau dãy núi hùng vĩ.", "Sân chơi nằm ở phía sau trường tiểu học của chúng tôi."] },
    { word: "in front of", phonetic: "/ɪn frʌnt əv/", def: "Located further forward than someone or something else.", defVn: "ở phía trước, đằng trước mặt", pos: "phrase", ex: ["A tall leafy mango tree grows in front of our house.", "Please wait in front of the station entrance."], exVn: ["Một cây xoài cao rợp bóng mọc trước cửa nhà chúng tôi.", "Xin vui lòng đợi ở trước lối vào nhà ga nhé."] },
    { word: "next to", phonetic: "/nekst tuː/", def: "Adjacent to; beside.", defVn: "ở bên cạnh, sát cạnh", pos: "phrase", ex: ["Sit next to me so we can practice English together.", "The pharmacy is right next to the clinic."], exVn: ["Ngồi bên cạnh tôi để chúng ta cùng luyện tiếng Anh nhé.", "Hiệu thuốc nằm ngay cạnh phòng khám."] },
    { word: "opposite", phonetic: "/ˈɑːpəzɪt/", def: "Having a position on the other or further side of something; facing.", defVn: "đối diện, phía đối diện", pos: "preposition", ex: ["The bus stop is located opposite the supermarket.", "They sat opposite each other at the dining table."], exVn: ["Trạm xe buýt nằm đối diện siêu thị.", "Họ ngồi đối diện nhau trên bàn ăn."] },
    { word: "inside", phonetic: "/ˌɪnˈsaɪd/", def: "The inner part, interior, or surface of something.", defVn: "ở bên trong, phía trong", pos: "preposition", ex: ["Step inside the warm house out of the chilly rain.", "Keep your passport safe inside your backpack."], exVn: ["Hãy bước vào bên trong ngôi nhà ấm áp tránh cơn mưa lạnh.", "Giữ hộ chiếu an toàn bên trong ba lô nhé."] },
    { word: "outside", phonetic: "/ˌaʊtˈsaɪd/", def: "The outer side or surface of something; outdoors.", defVn: "ở bên ngoài, ngoài trời", pos: "preposition", ex: ["Children love playing football outside on sunny afternoons.", "Leave muddy shoes outside the front door."], exVn: ["Trẻ con thích chơi bóng đá ngoài trời vào những chiều nắng.", "Để giày dép lấm bùn ở bên ngoài cửa trước nhé."] },
    { word: "near", phonetic: "/nɪr/", def: "At or to a short distance away; close.", defVn: "ở gần, gần bên", pos: "preposition", ex: ["We live in a cozy apartment near the city center lake.", "Is there a convenience store near here?"], exVn: ["Chúng tôi sống trong căn hộ ấm cúng gần hồ trung tâm thành phố.", "Có cửa hàng tiện lợi nào ở gần đây không ạ?"] },
    { word: "far", phonetic: "/fɑːr/", def: "At, to, or by a great distance.", defVn: "ở xa, xa xôi", pos: "adverb", ex: ["The airport is not far; it takes only fifteen minutes.", "Stars shine from far away in outer space."], exVn: ["Sân bay không hề xa; chỉ mất mười lăm phút thôi.", "Các vì sao tỏa sáng từ nơi xa xôi ngoài vũ trụ."] }
  ],

  // Theme 28: Giác quan & Cảm nhận (Senses & Perception)
  t_basic_senses_perceptions: [
    { word: "sight", phonetic: "/saɪt/", def: "The faculty or power of seeing; vision.", defVn: "thị giác, tầm nhìn, cảnh tượng", pos: "noun", ex: ["Ha Long Bay at sunrise is an unforgettable sight.", "Protect your eye sight with anti-glare lenses."], exVn: ["Vịnh Hạ Long lúc bình minh là một cảnh tượng khó quên.", "Bảo vệ thị lực của bạn bằng tròng kính chống chói."] },
    { word: "sound", phonetic: "/saʊnd/", def: "Vibrations that travel through the air and can be heard when they reach a person's ear.", defVn: "âm thanh, tiếng động", pos: "noun", ex: ["The soothing sound of ocean waves relaxes the mind.", "I heard a strange sound outside the window."], exVn: ["Âm thanh êm đềm của sóng biển làm thư thái tâm hồn.", "Tôi nghe thấy một tiếng động lạ bên ngoài cửa sổ."] },
    { word: "smell", phonetic: "/smel/", def: "The faculty or power of perceiving odors or scents by means of the nose.", defVn: "khứu giác, mùi hương", pos: "noun", ex: ["The aromatic smell of fresh coffee filled the kitchen.", "Roses have a sweet and delightful smell."], exVn: ["Mùi hương thơm lừng của cà phê tươi ngập tràn căn bếp.", "Hoa hồng có một mùi hương ngọt ngào và dễ chịu."] },
    { word: "taste", phonetic: "/teɪst/", def: "The sensation of flavor perceived in the mouth and throat on contact with a substance.", defVn: "vị giác, hương vị món ăn", pos: "noun", ex: ["Fresh ripe mango has a rich, sweet tropical taste.", "This soup has a delicious savory taste."], exVn: ["Xoài chín tươi có vị ngọt đậm đà hương nhiệt đới.", "Món súp này có hương vị đậm đà rất ngon."] },
    { word: "touch", phonetic: "/tʌtʃ/", def: "The faculty of perceiving sensations of physical contact using the skin.", defVn: "xúc giác, sự chạm vào", pos: "noun", ex: ["Silk fabric feels soft and smooth to the touch.", "Human touch conveys warmth and empathy."], exVn: ["Vải lụa khi chạm vào mang lại cảm giác mềm mại và mịn màng.", "Cái chạm tay của con người truyền tải sự ấm áp và thấu cảm."] },
    { word: "see", phonetic: "/siː/", def: "Perceive with the eyes for visual comprehension.", defVn: "nhìn thấy, trông thấy", pos: "verb", ex: ["Can you see the colorful rainbow over the lake?", "I see what you mean; that makes sense."], exVn: ["Bạn có nhìn thấy chiếc cầu vồng rực rỡ trên hồ không?", "Tôi hiểu ý bạn rồi; điều đó rất hợp lý."] },
    { word: "look", phonetic: "/lʊk/", def: "Direct one's gaze toward someone or something.", defVn: "nhìn, ngắm nhìn", pos: "verb", ex: ["Look at this stunning photograph of the mountain sunset.", "Look both ways before crossing the road."], exVn: ["Hãy nhìn bức ảnh tuyệt đẹp về hoàng hôn trên núi này đi.", "Nhìn cả hai phía trước khi băng qua đường nhé."] },
    { word: "hear", phonetic: "/hɪr/", def: "Perceive with the ear the sound made by someone or something.", defVn: "nghe thấy (âm thanh lọt vào tai)", pos: "verb", ex: ["Did you hear the thunder rolling in the distance?", "I hear birds chirping outside my bedroom window."], exVn: ["Bạn có nghe thấy tiếng sấm rền vang đằng xa không?", "Tôi nghe thấy tiếng chim hót líu lo ngoài cửa sổ phòng ngủ."] },
    { word: "listen", phonetic: "/ˈlɪsn/", def: "Give one's attention to a sound with deliberate focus.", defVn: "lắng nghe (chú ý lắng nghe)", pos: "verb", ex: ["Listen attentively to the English audio recording.", "I love listening to acoustic guitar melodies."], exVn: ["Hãy chăm chú lắng nghe đoạn ghi âm tiếng Anh nhé.", "Tôi rất thích lắng nghe những giai điệu đàn ghi-ta mộc."] },
    { word: "feel", phonetic: "/fiːl/", def: "Experience an emotion or physical sensation.", defVn: "cảm thấy, cảm giác", pos: "verb", ex: ["I feel energetic and refreshed after morning exercise.", "Feel how soft this velvet blanket is."], exVn: ["Tôi cảm thấy tràn đầy năng lượng và sảng khoái sau khi tập thể dục buổi sáng.", "Hãy cảm nhận chiếc chăn nhung này mềm mại thế nào."] },
    { word: "soft", phonetic: "/sɔːft/", def: "Easy to mold, cut, compress, or fold; not hard or firm to the touch.", defVn: "mềm mại, êm ái", pos: "adj", ex: ["This feather pillow is incredibly soft and comfortable.", "Cotton clothes feel soft against sensitive skin."], exVn: ["Chiếc gối lông vũ này vô cùng mềm mại và êm ái.", "Quần áo cotton tạo cảm giác mềm mại trên làn da nhạy cảm."] },
    { word: "hard", phonetic: "/hɑːrd/", def: "Solid, firm, and rigid; not easily broken, bent, or pierced.", defVn: "cứng, rắn chắc", pos: "adj", ex: ["Diamonds are the hardest natural substance known on Earth.", "The wooden chair was hard, so I added a cushion."], exVn: ["Kim cương là vật chất tự nhiên cứng nhất được biết đến trên Trái Đất.", "Chiếc ghế gỗ hơi cứng nên tôi đã lót thêm một tấm đệm."] },
    { word: "sweet", phonetic: "/swiːt/", def: "Having the pleasant taste characteristic of sugar or honey.", defVn: "ngọt ngào, có vị ngọt", pos: "adj", ex: ["Ripe strawberries and honey are naturally sweet.", "She has a sweet voice when singing folk songs."], exVn: ["Dâu tây chín và mật ong có vị ngọt tự nhiên.", "Cô ấy có giọng hát ngọt ngào khi hát các làn điệu dân ca."] },
    { word: "sour", phonetic: "/ˈsaʊər/", def: "Having an acid taste like lemon or vinegar.", defVn: "chua, có vị chua", pos: "adj", ex: ["Fresh lemon juice is quite sour, so add honey.", "Unripe green mangoes have a crisp sour taste."], exVn: ["Nước cốt chanh tươi khá chua nên hãy thêm một chút mật ong.", "Xoài xanh chưa chín có vị chua giòn sần sật."] },
    { word: "bitter", phonetic: "/ˈbɪtər/", def: "Having a sharp, pungent taste or smell; not sweet.", defVn: "đắng, có vị đắng", pos: "adj", ex: ["Dark chocolate and black coffee have a rich bitter taste.", "Good herbal medicine often tastes bitter."], exVn: ["Sô-cô-la đen nguyên chất và cà phê đen có vị đắng đậm đà.", "Thuốc nam tốt thường có vị đắng."] }
  ],

  // Theme 29: Kỳ nghỉ & Du lịch (Vacation & Tourism)
  t_basic_vacation_tourism: [
    { word: "passport", phonetic: "/ˈpæspɔːrt/", def: "An official document issued by a government certifying holder's identity for international travel.", defVn: "hộ chiếu (xuất nhập cảnh)", pos: "noun", ex: ["Keep your passport and boarding pass in your carry-on bag.", "Make sure your passport is valid for six months."], exVn: ["Giữ hộ chiếu và thẻ lên máy bay trong hành lý xách tay nhé.", "Hãy đảm bảo hộ chiếu của bạn còn hạn ít nhất sáu tháng."] },
    { word: "luggage", phonetic: "/ˈlʌɡɪdʒ/", def: "Suitcases or other bags in which to pack personal belongings for traveling.", defVn: "hành lý du lịch", pos: "noun", ex: ["We checked in our heavy luggage at the airport counter.", "Pack lightweight luggage for easy city exploration."], exVn: ["Chúng tôi ký gửi hành lý nặng tại quầy sân bay.", "Hãy gói ghém hành lý gọn nhẹ để dễ dàng khám phá thành phố."] },
    { word: "suitcase", phonetic: "/ˈsuːtkeɪs/", def: "A case with a handle and a hinged lid, used for carrying clothes and other personal possessions.", defVn: "chiếc va-li du lịch", pos: "noun", ex: ["She packed her summer clothes into a rolling suitcase.", "Lock your suitcase before handing it to baggage check."], exVn: ["Cô ấy xếp quần áo mùa hè vào chiếc va-li có bánh kéo.", "Khóa va-li lại trước khi gửi hành lý nhé."] },
    { word: "tourist", phonetic: "/ˈtʊrɪst/", def: "A person who is traveling or visiting a place for pleasure.", defVn: "khách du lịch, du khách", pos: "noun", ex: ["Millions of international tourists visit Vietnam every year.", "Tourists love exploring Hanoi's charming Old Quarter."], exVn: ["Hàng triệu du khách quốc tế đến thăm Việt Nam mỗi năm.", "Khách du lịch rất thích khám phá Phố Cổ Hà Nội quyến rũ."] },
    { word: "guide", phonetic: "/ɡaɪd/", def: "A person who advises or shows the way to others.", defVn: "hướng dẫn viên du lịch", pos: "noun", ex: ["Our knowledgeable tour guide explained the history of the imperial citadel.", "Follow the guide through the cave."], exVn: ["Hướng dẫn viên du lịch uyên bác đã giải thích lịch sử hoàng thành.", "Đi theo người hướng dẫn viên qua hang động nhé."] },
    { word: "resort", phonetic: "/rɪˈzɔːrt/", def: "A place that is a popular destination for vacations or recreation.", defVn: "khu nghỉ dưỡng cao cấp, resort", pos: "noun", ex: ["We stayed at a luxury beachfront resort in Phu Quoc.", "The resort has an infinity swimming pool and spa."], exVn: ["Chúng tôi đã ở một khu nghỉ dưỡng ven biển sang trọng tại Phú Quốc.", "Khu nghỉ dưỡng có hồ bơi vô cực và dịch vụ spa."] },
    { word: "beach", phonetic: "/biːtʃ/", def: "A pebbly or sandy shore, especially by the ocean between high- and low-water marks.", defVn: "bãi biển cát trắng", pos: "noun", ex: ["My Khe Beach in Da Nang is voted among the world's most beautiful beaches.", "Stroll along the sunny sandy beach at sunset."], exVn: ["Bãi biển Mỹ Khê ở Đà Nẵng được bình chọn trong top bãi biển đẹp nhất thế giới.", "Đi dạo dọc bờ biển cát mịn lúc hoàng hôn."] },
    { word: "souvenir", phonetic: "/ˌsuːvəˈnɪr/", def: "A thing that is kept as a reminder of a person, place, or event.", defVn: "quà lưu niệm du lịch", pos: "noun", ex: ["I bought a traditional conical hat as a souvenir in Hue.", "Souvenir shops sell handmade silk crafts."], exVn: ["Tôi đã mua một chiếc nón lá truyền thống làm quà lưu niệm ở Huế.", "Các cửa hàng lưu niệm bán đồ thủ công bằng lụa làm bằng tay."] },
    { word: "flight", phonetic: "/flaɪt/", def: "A journey made through the air, especially in an aircraft.", defVn: "chuyến bay (hàng không)", pos: "noun", ex: ["The direct flight from Hanoi to Ho Chi Minh City takes two hours.", "Have a pleasant and safe flight!"], exVn: ["Chuyến bay thẳng từ Hà Nội vào TP. Hồ Chí Minh mất hai tiếng.", "Chúc bạn có một chuyến bay vui vẻ và an toàn!"] },
    { word: "ticket", phonetic: "/ˈtɪkɪt/", def: "A paper or digital document confirming payment for admission or travel.", defVn: "vé máy bay, vé tham quan", pos: "noun", ex: ["Book your domestic flight tickets early for discounted rates.", "Show your admission ticket at the museum entrance."], exVn: ["Đặt vé máy bay nội địa sớm để nhận giá ưu đãi nhé.", "Xuất trình vé vào cửa tại lối vào bảo tàng."] },
    { word: "map", phonetic: "/mæp/", def: "A diagrammatic representation of an area of land or sea showing physical features.", defVn: "bản đồ chỉ đường", pos: "noun", ex: ["Use the city metro map to navigate subway lines easily.", "Download offline maps on your smartphone."], exVn: ["Dùng bản đồ tàu điện ngầm thành phố để đi lại dễ dàng.", "Tải bản đồ ngoại tuyến về điện thoại thông minh nhé."] },
    { word: "hotel", phonetic: "/hoʊˈtel/", def: "An establishment providing accommodation, meals, and other services for travelers.", defVn: "khách sạn lưu trú", pos: "noun", ex: ["We reserved a boutique hotel in the historic city center.", "The hotel offers complimentary morning breakfast."], exVn: ["Chúng tôi đã đặt một khách sạn boutique ở trung tâm thành phố lịch sử.", "Khách sạn phục vụ bữa sáng miễn phí."] },
    { word: "sightseeing", phonetic: "/ˈsaɪtsiːɪŋ/", def: "The activity of visiting places of interest in a particular location by tourists.", defVn: "hoạt động ngắm cảnh, tham quan danh lam", pos: "noun", ex: ["We spent the sunny day sightseeing historical temples and landmarks.", "A double-decker bus is great for sightseeing."], exVn: ["Chúng tôi dành cả ngày nắng đẹp đi tham quan ngắm cảnh các đền đài lịch sử.", "Xe buýt hai tầng rất tuyệt vời để đi ngắm cảnh thành phố."] },
    { word: "vacation", phonetic: "/veɪˈkeɪʃn/", def: "An extended period of recreation, especially one spent away from home or traveling.", defVn: "kỳ nghỉ dưỡng, kỳ nghỉ phép", pos: "noun", ex: ["Summer vacation is the best time for family travel.", "Where are you going for your winter vacation?"], exVn: ["Kỳ nghỉ hè là thời điểm tuyệt vời nhất cho các chuyến đi gia đình.", "Bạn dự định đi đâu trong kỳ nghỉ đông sắp tới?"] },
    { word: "journey", phonetic: "/ˈdʒɜːrni/", def: "An act of traveling from one place to another.", defVn: "hành trình, chuyến đi ý nghĩa", pos: "noun", ex: ["A thousand-mile journey begins with a single confident step.", "Enjoy every moment of your learning journey."], exVn: ["Hành trình vạn dặm bắt đầu từ một bước chân tự tin.", "Hãy tận hưởng từng khoảnh khắc trong hành trình học tập của bạn."] }
  ],

  // Theme 30: Giải trí & Nghệ thuật (Entertainment & Arts)
  t_basic_entertainment_arts: [
    { word: "movie", phonetic: "/ˈmuːvi/", def: "A story or event recorded by a camera as a set of moving images.", defVn: "bộ phim điện ảnh", pos: "noun", ex: ["Let's watch an entertaining comedy movie together this weekend.", "The animated movie won an international film award."], exVn: ["Cuối tuần này chúng ta cùng xem một bộ phim hài giải trí nhé.", "Bộ phim hoạt hình đã đoạt giải thưởng điện ảnh quốc tế."] },
    { word: "music", phonetic: "/ˈmjuːzɪk/", def: "Vocal or instrumental sounds combined in such a way as to produce beauty of form, harmony, and expression.", defVn: "âm nhạc, giai điệu", pos: "noun", ex: ["Listening to gentle acoustic music helps you relax and study.", "Music connects people across different languages."], exVn: ["Lắng nghe âm nhạc acoustic nhẹ nhàng giúp bạn thư giãn và học tập.", "Âm nhạc kết nối con người vượt qua mọi rào cản ngôn ngữ."] },
    { word: "concert", phonetic: "/ˈkɑːnsərt/", def: "A musical performance given in public, typically by several performers or of several compositions.", defVn: "buổi hòa nhạc, buổi biểu diễn ca nhạc", pos: "noun", ex: ["Thousands of singing fans gathered at the live stadium concert.", "The symphony orchestra gave a mesmerizing classical concert."], exVn: ["Hàng ngàn người hâm mộ tụ họp tại buổi hòa nhạc trực tiếp ở sân vận động.", "Dàn nhạc giao hưởng đã mang đến buổi hòa nhạc cổ điển đầy mê hoặc."] },
    { word: "song", phonetic: "/sɔːŋ/", def: "A short poem or other set of words set to music or meant to be sung.", defVn: "bài hát, ca khúc", pos: "noun", ex: ["Sing along to your favorite English song to improve pronunciation.", "This folk song has a catchy and sweet melody."], exVn: ["Hát theo bài hát tiếng Anh yêu thích để nâng cao phát âm nhé.", "Bài hát dân ca này có giai điệu bắt tai và rất ngọt ngào."] },
    { word: "dance", phonetic: "/dæns/", def: "Move rhythmically to music, typically following a set sequence of steps.", defVn: "điệu nhảy, khiêu vũ", pos: "noun", ex: ["Traditional Vietnamese bamboo dance is lively and festive.", "Dancing to upbeat music burns calories and lifts your mood."], exVn: ["Điệu múa sạp tre truyền thống của Việt Nam rất sôi động và lễ hội.", "Nhảy theo nhạc sôi động giúp đốt cháy calo và nâng cao tinh thần."] },
    { word: "game", phonetic: "/ɡeɪm/", def: "A form of play or sport, especially a competitive one played according to rules.", defVn: "trò chơi, trò chơi điện tử / bàn cờ", pos: "noun", ex: ["Playing interactive vocabulary games makes English learning fun.", "They played a competitive board game on Saturday night."], exVn: ["Chơi các trò chơi từ vựng tương tác giúp việc học tiếng Anh thú vị hơn.", "Họ đã chơi trò chơi cờ bàn đầy kịch tính vào tối thứ Bảy."] },
    { word: "show", phonetic: "/ʃoʊ/", def: "A spectacle, display, or performance, typically in a theatre, on television, or in a circus.", defVn: "buổi trình diễn, chương trình biểu diễn", pos: "noun", ex: ["The traditional water puppet show in Hanoi is culturally unique.", "We watched an entertaining live magic show."], exVn: ["Chương trình múa rối nước truyền thống ở Hà Nội mang nét văn hóa độc đáo.", "Chúng tôi xem một buổi biểu diễn ảo thuật trực tiếp rất hấp dẫn."] },
    { word: "circus", phonetic: "/ˈsɜːrkəs/", def: "A travelling company of acrobats, clowns, and other entertainers which gives performances.", defVn: "gánh xiếc, rạp xiếc nghệ thuật", pos: "noun", ex: ["Acrobats performed breathtaking aerial stunts at the circus.", "Children laughed joyfully at the circus clowns."], exVn: ["Các nghệ sĩ xiếc biểu diễn những màn nhào lộn trên không ngoạn mục.", "Lũ trẻ cười giòn giã trước những chú hề rạp xiếc."] },
    { word: "magic", phonetic: "/ˈmædʒɪk/", def: "The power of apparently influencing events by using mysterious or supernatural forces; conjuring tricks.", defVn: "ảo thuật, phép màu kỳ diệu", pos: "noun", ex: ["The skilled magician pulled a white rabbit from his hat with magic.", "The fairy tale had a world filled with magic."], exVn: ["Nhà ảo thuật tài ba rút chú thỏ trắng từ chiếc mũ bằng ảo thuật.", "Câu chuyện cổ tích có một thế giới ngập tràn phép màu kỳ diệu."] },
    { word: "art", phonetic: "/ɑːrt/", def: "The expression or application of human creative skill and imagination.", defVn: "nghệ thuật (hội họa, điêu khắc)", pos: "noun", ex: ["Art allows us to express deep human emotions creatively.", "She studies traditional lacquer art in Hanoi."], exVn: ["Nghệ thuật cho phép chúng ta thể hiện cảm xúc sâu sắc một cách sáng tạo.", "Cô ấy học nghệ thuật tranh sơn mài truyền thống tại Hà Nội."] },
    { word: "gallery", phonetic: "/ˈɡæləri/", def: "A room or building for the display or sale of works of art.", defVn: "phòng triển lãm nghệ thuật, phòng tranh", pos: "noun", ex: ["The contemporary art gallery exhibited oil paintings by young artists.", "Admission to the city gallery is free on Fridays."], exVn: ["Phòng tranh đương đại trưng bày các tác phẩm sơn dầu của họa sĩ trẻ.", "Vé vào phòng triển lãm thành phố miễn phí vào các ngày thứ Sáu."] },
    { word: "actor", phonetic: "/ˈæktər/", def: "A person whose profession is acting on the stage, in movies, or on television.", defVn: "nam diễn viên điện ảnh / kịch", pos: "noun", ex: ["The talented actor delivered a powerful dramatic performance.", "He won the Best Actor award at the film festival."], exVn: ["Người nam diễn viên tài năng đã mang đến màn diễn xuất đầy nội lực.", "Anh ấy đoạt giải Nam diễn viên xuất sắc nhất tại liên hoan phim."] },
    { word: "actress", phonetic: "/ˈæktrəs/", def: "A female actor.", defVn: "nữ diễn viên điện ảnh / kịch", pos: "noun", ex: ["The famous actress starred in three international movies this year.", "She trained at the drama academy to become an actress."], exVn: ["Nữ diễn viên nổi tiếng đã đóng vai chính trong ba bộ phim quốc tế năm nay.", "Cô ấy theo học tại học viện kịch nghệ để trở thành diễn viên."] },
    { word: "festival", phonetic: "/ˈfestɪvl/", def: "A day or period of celebration, typically a religious or cultural commemoration.", defVn: "lễ hội văn hóa / âm nhạc", pos: "noun", ex: ["Hue Festival celebrates imperial culture with grand music and art.", "The international film festival takes place in autumn."], exVn: ["Festival Huế tôn vinh văn hóa cung đình bằng âm nhạc và nghệ thuật hoành tráng.", "Liên hoan phim quốc tế diễn ra vào mùa thu."] },
    { word: "sculpture", phonetic: "/ˈskʌlptʃər/", def: "The art of making two- or three-dimensional representative or abstract forms by carving stone or wood.", defVn: "tác phẩm điêu khắc, tượng nghệ thuật", pos: "noun", ex: ["The museum features ancient bronze and marble sculptures.", "The artist carved a graceful wooden sculpture."], exVn: ["Bảo tàng trưng bày các tác phẩm điêu khắc bằng đồng và đá cẩm thạch cổ.", "Người nghệ sĩ đã đẽo gọt một bức tượng gỗ đầy duyên dáng."] }
  ]
};
