module.exports = {
  // Theme 31: Đo lường & Kích cỡ (Measurements & Sizes)
  t_basic_measurements_sizes: [
    { word: "meter", phonetic: "/ˈmiːtər/", def: "The fundamental unit of length in the metric system, equal to 100 centimeters.", defVn: "mét (đơn vị đo chiều dài)", pos: "noun", ex: ["The swimming pool is 50 meters long.", "He jumped over two meters high in the competition."], exVn: ["Hồ bơi dài 50 mét.", "Cậu ấy đã nhảy cao hơn hai mét trong cuộc thi."] },
    { word: "centimeter", phonetic: "/ˈsentɪmiːtər/", def: "A metric unit of length, equal to one hundredth of a meter.", defVn: "xen-ti-mét, xăng-ti-mét (cm)", pos: "noun", ex: ["A standard ruler is 30 centimeters in length.", "The baby grew three centimeters this month."], exVn: ["Một cây thước kẻ tiêu chuẩn dài 30 cm.", "Em bé đã tăng thêm 3 cm trong tháng này."] },
    { word: "kilometer", phonetic: "/kɪˈlɑːmɪtər/", def: "A metric unit of measurement equal to 1,000 meters.", defVn: "ki-lô-mét, cây số (km)", pos: "noun", ex: ["The marathon running race is 42 kilometers long.", "It is only five kilometers from my house to school."], exVn: ["Cuộc thi chạy marathon dài 42 ki-lô-mét.", "Từ nhà tôi đến trường chỉ mất 5 cây số."] },
    { word: "gram", phonetic: "/ɡræm/", def: "A metric unit of mass equal to one thousandth of a kilogram.", defVn: "gam, gram (g)", pos: "noun", ex: ["Add 100 grams of pure sugar to the cake mixture.", "This light smartphone weighs only 180 grams."], exVn: ["Cho 100 gam đường tinh luyện vào hỗn hợp làm bánh.", "Chiếc điện thoại thông minh nhẹ này chỉ nặng 180 gam."] },
    { word: "kilogram", phonetic: "/ˈkɪləɡræm/", def: "The SI unit of mass equivalent to 1,000 grams; kilo.", defVn: "ki-lô-gam, ký (kg)", pos: "noun", ex: ["She bought two kilograms of fresh Da Lat strawberries.", "He lost five kilograms after regular jogging."], exVn: ["Cô ấy đã mua 2 kg dâu tây tươi Đà Lạt.", "Anh ấy đã giảm 5 ký sau khi chạy bộ đều đặn."] },
    { word: "liter", phonetic: "/ˈliːtər/", def: "A metric unit of capacity, formerly defined as the volume of 1 kilogram of water.", defVn: "lít (đơn vị đo dung tích)", pos: "noun", ex: ["Drink at least two liters of water every day for good health.", "Fill the car tank with forty liters of fuel."], exVn: ["Hãy uống ít nhất 2 lít nước mỗi ngày để cơ thể khỏe mạnh.", "Đổ đầy bình xăng với 40 lít nhiên liệu."] },
    { word: "inch", phonetic: "/ɪntʃ/", def: "A unit of linear measure equal to one twelfth of a foot (2.54 cm).", defVn: "in-sơ, inch (2,54 cm)", pos: "noun", ex: ["My new laptop has a crisp 15-inch screen.", "The rainfall reached three inches overnight."], exVn: ["Máy tính xách tay mới của tôi có màn hình 15 inch sắc nét.", "Lượng mưa đo được đạt ba inch chỉ sau một đêm."] },
    { word: "foot", phonetic: "/fʊt/", def: "A unit of linear measure equal to 12 inches (30.48 cm).", defVn: "bước chân, thước Anh (foot - 30,48 cm)", pos: "noun", ex: ["Mount Fansipan stands over 10,000 feet above sea level.", "The ceiling is nine feet high."], exVn: ["Đỉnh Fansipan cao hơn 10.000 feet so với mực nước biển.", "Trần nhà cao chín feet."] },
    { word: "height", phonetic: "/haɪt/", def: "The measurement of someone or something from head to foot or from base to top.", defVn: "chiều cao, độ cao", pos: "noun", ex: ["What is your height? — I am 1.75 meters tall.", "The height of this building is impressive."], exVn: ["Chiều cao của bạn là bao nhiêu? — Tôi cao 1m75.", "Chiều cao của tòa nhà này thật ấn tượng."] },
    { word: "weight", phonetic: "/weɪt/", def: "A body's relative mass or the quantity of matter contained by it.", defVn: "cân nặng, trọng lượng", pos: "noun", ex: ["Check your body weight on the bathroom scale.", "The maximum luggage weight allowance is 20 kg."], exVn: ["Kiểm tra cân nặng cơ thể trên chiếc cân phòng tắm.", "Mức trọng lượng hành lý tối đa cho phép là 20 kg."] },
    { word: "length", phonetic: "/leŋkθ/", def: "The measurement or extent of something from end to end.", defVn: "chiều dài, độ dài", pos: "noun", ex: ["Measure the exact length of the wooden board with a tape measure.", "The length of the bridge is 500 meters."], exVn: ["Đo chính xác chiều dài thanh gỗ bằng thước dây.", "Chiều dài của cây cầu là 500 mét."] },
    { word: "width", phonetic: "/wɪdθ/", def: "The measurement or extent of something from side to side.", defVn: "chiều rộng, bề ngang", pos: "noun", ex: ["The width of the doorway allows wheelchair access.", "Measure the table's width before buying."], exVn: ["Chiều rộng của cửa ra vào cho phép xe lăn đi qua dễ dàng.", "Hãy đo chiều rộng của chiếc bàn trước khi mua nhé."] },
    { word: "depth", phonetic: "/depθ/", def: "The distance from the top or surface to the bottom of something.", defVn: "độ sâu, chiều sâu", pos: "noun", ex: ["The maximum depth of the swimming pool is two meters.", "Divers explored the ocean depths."], exVn: ["Độ sâu tối đa của hồ bơi là hai mét.", "Các thợ lặn đã khám phá những tầng sâu của đại dương."] },
    { word: "heavy", phonetic: "/ˈhevi/", def: "Of great weight; difficult to lift or move.", defVn: "nặng nề, nặng cân", pos: "adj", ex: ["Can you give me a hand with this heavy suitcase?", "Elephants are heavy land mammals."], exVn: ["Bạn giúp tôi một tay khiêng chiếc va-li nặng này được không?", "Voi là loài động vật có vú trên cạn rất nặng."] },
    { word: "light", phonetic: "/laɪt/", def: "Of little weight; not heavy.", defVn: "nhẹ nhàng, nhẹ cân", pos: "adj", ex: ["A feather is as light as air.", "This jacket is warm yet extremely light."], exVn: ["Một chiếc lông vũ nhẹ bẫng như không khí.", "Chiếc áo khoác này rất ấm nhưng lại cực kỳ nhẹ."] }
  ],

  // Theme 32: Dụng cụ & Sửa chữa (Tools & Home Repair)
  t_basic_tools_repair: [
    { word: "hammer", phonetic: "/ˈhæmər/", def: "A tool with a heavy metal head mounted at right angles at the end of a handle.", defVn: "cây búa (đóng đinh)", pos: "noun", ex: ["Use a steel hammer to drive the nail firmly into the wooden wall.", "Be careful not to hit your fingers with the hammer."], exVn: ["Dùng búa thép đóng chặt chiếc đinh vào bức tường gỗ.", "Cẩn thận kẻo đập búa vào ngón tay nhé."] },
    { word: "nail", phonetic: "/neɪl/", def: "A small metal spike with a broadened flat head, driven into wood to join things.", defVn: "chiếc đinh kim loại", pos: "noun", ex: ["Hang the picture frame on a sturdy wall nail.", "Hammer the nail straight into the board."], exVn: ["Treo khung ảnh lên chiếc đinh tường chắc chắn nhé.", "Đóng chiếc đinh thẳng đứng vào tấm ván."] },
    { word: "screw", phonetic: "/skruː/", def: "A short, slender, sharp-pointed metal pin with a raised helical thread around it.", defVn: "con ốc vít, đinh vít", pos: "noun", ex: ["Tighten the loose screw on the chair leg.", "Use drywall screws for mounting the shelf."], exVn: ["Siết chặt con ốc vít bị lỏng ở chân ghế lại.", "Dùng ốc vít thạch cao để lắp kệ sách."] },
    { word: "screwdriver", phonetic: "/ˈskruːdraɪvər/", def: "A tool with a flattened or cross-shaped tip that fits into the head of a screw.", defVn: "cây tua-vít (vặn ốc)", pos: "noun", ex: ["Use a Phillips screwdriver to tighten the battery compartment.", "Every home toolbox needs a set of screwdrivers."], exVn: ["Dùng tua-vít bốn cạnh để vặn chặt nắp khay pin.", "Mọi hộp đồ nghề gia đình đều cần một bộ tua-vít."] },
    { word: "wrench", phonetic: "/rentʃ/", def: "A tool used for gripping and turning nuts or bolts.", defVn: "cờ-lê, mỏ-lết (vặn bu-lông)", pos: "noun", ex: ["Use an adjustable wrench to tighten the water pipe fitting.", "He loosened the bicycle bolt with a wrench."], exVn: ["Dùng mỏ-lết đa năng để siết chặt đầu nối ống nước.", "Anh ấy đã nới lỏng bu-lông xe đạp bằng chiếc cờ-lê."] },
    { word: "pliers", phonetic: "/ˈplaɪərz/", def: "Pincers with parallel, flat, and typically serrated surfaces, used for gripping small objects or bending wire.", defVn: "chiếc kìm (cắt dây, kẹp đồ)", pos: "noun", ex: ["Use wire-cutting pliers to trim electrical cables safely.", "Grip the small metal rod firmly with pliers."], exVn: ["Dùng kìm cắt dây để cắt cáp điện một cách an toàn.", "Kẹp chặt thanh kim loại nhỏ bằng kìm."] },
    { word: "saw", phonetic: "/sɔː/", def: "A hand tool for cutting wood or other hard materials, typically with a toothed blade.", defVn: "cây cưa gỗ / kim loại", pos: "noun", ex: ["The carpenter used a sharp hand saw to cut the wooden beam.", "Keep your hands clear of the spinning electric saw blade."], exVn: ["Người thợ mộc đã dùng cưa tay sắc bén để cắt thanh gỗ.", "Để tay cách xa lưỡi cưa máy đang quay nhé."] },
    { word: "drill", phonetic: "/drɪl/", def: "A tool or machine with a rotating cutting tip or reciprocating hammer used for making holes.", defVn: "máy khoan (khoan tường, gỗ)", pos: "noun", ex: ["Drill a neat hole in the concrete wall for the anchor plug.", "He bought a cordless electric drill."], exVn: ["Khoan một lỗ gọn gàng trên tường bê tông để đóng nở nhựa.", "Anh ấy đã mua chiếc máy khoan điện dùng pin."] },
    { word: "ladder", phonetic: "/ˈlædər/", def: "A structure consisting of a series of bars or steps between two upright lengths of wood or metal.", defVn: "cái thang (gỗ / nhôm)", pos: "noun", ex: ["Climb the sturdy aluminum ladder to replace the ceiling light bulb.", "Make sure the ladder is firmly balanced."], exVn: ["Leo lên chiếc thang nhôm chắc chắn để thay bóng đèn trần.", "Hãy đảm bảo chiếc thang được kê thăng bằng vững chắc."] },
    { word: "toolbox", phonetic: "/ˈtuːlbɑːks/", def: "A box or container for keeping tools organized.", defVn: "hộp đựng dụng cụ, hộp đồ nghề", pos: "noun", ex: ["Keep your hammers, wrenches, and tape in the metal toolbox.", "He carried his portable toolbox to the repair site."], exVn: ["Giữ búa, cờ-lê và băng dính trong hộp đồ nghề kim loại.", "Anh ấy mang theo hộp dụng cụ di động đến nơi sửa chữa."] },
    { word: "tape measure", phonetic: "/teɪp ˈmeʒər/", def: "A length of tape or thin flexible metal marked at intervals for measuring.", defVn: "thước dây, thước cuộn rút", pos: "noun", ex: ["Pull out the tape measure to check the room's dimensions.", "Measure the window width with a flexible tape measure."], exVn: ["Kéo thước dây cuộn ra để kiểm tra kích thước căn phòng.", "Đo chiều rộng cửa sổ bằng thước cuộn linh hoạt."] },
    { word: "glue", phonetic: "/ɡluː/", def: "An adhesive substance used for sticking objects together securely.", defVn: "keo dán siêu dính, hồ dán", pos: "noun", ex: ["Apply strong wood glue to repair the broken chair arm.", "Super glue bonds materials in seconds."], exVn: ["Bôi keo dán gỗ chuyên dụng để sửa tay vịn ghế bị gãy.", "Keo siêu dính liên kết các vật liệu chỉ trong vài giây."] },
    { word: "paint", phonetic: "/peɪnt/", def: "A colored substance which is spread over a surface and dries to leave a thin decorative or protective coating.", defVn: "sơn tường, màu sơn", pos: "noun", ex: ["They applied two coats of fresh white paint to the bedroom walls.", "Use weather-resistant exterior paint."], exVn: ["Họ đã quét hai lớp sơn trắng mới lên tường phòng ngủ.", "Dùng sơn ngoại thất chịu được thời tiết nhé."] },
    { word: "brush", phonetic: "/brʌʃ/", def: "An implement with a handle, consisting of bristles or hairs, used for painting or cleaning.", defVn: "chổi quét sơn, cọ sơn", pos: "noun", ex: ["Use a wide paint brush for smooth and even wall coverage.", "Clean your paint brushes with warm water after use."], exVn: ["Dùng chổi quét sơn bản rộng để sơn tường mịn và đều màu.", "Rửa sạch cọ sơn bằng nước ấm sau khi sử dụng."] },
    { word: "fix", phonetic: "/fɪks/", def: "Fasten something securely in a particular place or position; repair.", defVn: "sửa chữa, khắc phục sự cố", pos: "verb", ex: ["My father taught me how to fix a flat bicycle tire.", "Can you fix this leaking water faucet?"], exVn: ["Bố đã dạy tôi cách vá và sửa chiếc lốp xe đạp bị xẹp.", "Bạn có thể sửa chiếc vòi nước bị rò rỉ này được không?"] }
  ],

  // Theme 33: Thiên tai & Thời tiết xấu (Severe Weather)
  t_basic_severe_weather: [
    { word: "typhoon", phonetic: "/taɪˈfuːn/", def: "A tropical storm in the region of the Indian or western Pacific oceans.", defVn: "cơn bão nhiệt đới dữ dội", pos: "noun", ex: ["Coastal provinces prepared emergency shelters before the super typhoon.", "Typhoon winds reached over 150 km/h."], exVn: ["Các tỉnh ven biển đã chuẩn bị các điểm trú ẩn khẩn cấp trước siêu bão.", "Gió bão đạt vận tốc trên 150 km/h."] },
    { word: "flood", phonetic: "/flʌd/", def: "An overflow of a large amount of water beyond its normal limits, especially over what is normally dry land.", defVn: "trận lũ lụt, ngập úng", pos: "noun", ex: ["Heavy continuous rains caused severe street floods in the city.", "Rescue teams helped families evacuate during the flood."], exVn: ["Những trận mưa lớn kéo dài gây ra tình trạng ngập lụt nghiêm trọng trong thành phố.", "Các đội cứu hộ đã giúp đỡ các gia đình sơ tán trong trận lũ."] },
    { word: "drought", phonetic: "/draʊt/", def: "A prolonged period of abnormally low rainfall, leading to a shortage of water.", defVn: "nạn hạn hán, khô hạn kéo dài", pos: "noun", ex: ["The prolonged summer drought dried up irrigation reservoirs.", "Farmers used drip irrigation to conserve water during the drought."], exVn: ["Đợt hạn hán mùa hè kéo dài đã làm cạn kiệt các hồ chứa nước tưới tiêu.", "Nông dân dùng hệ thống tưới nhỏ giọt để tiết kiệm nước trong mùa hạn."] },
    { word: "thunderstorm", phonetic: "/ˈθʌndərstɔːrm/", def: "A storm with thunder and lightning and typically also heavy rain or hail.", defVn: "cơn giông bão sấm sét", pos: "noun", ex: ["Stay indoors away from windows during a severe thunderstorm.", "The sudden afternoon thunderstorm cooled down the heat."], exVn: ["Hãy ở trong nhà và tránh xa cửa sổ khi có cơn giông bão sấm sét.", "Cơn giông bất chợt buổi chiều đã xua tan cái nóng bức."] },
    { word: "lightning", phonetic: "/ˈlaɪtnɪŋ/", def: "The occurrence of a natural electrical discharge of very short duration between a cloud and ground.", defVn: "tia chớp, tia sét", pos: "noun", ex: ["A vivid flash of lightning illuminated the dark stormy sky.", "Never take shelter under tall trees during lightning."], exVn: ["Một tia chớp rực sáng thắp sáng bầu trời giông bão đen kịt.", "Tuyệt đối không trú ẩn dưới gốc cây cao khi có sấm sét."] },
    { word: "tornado", phonetic: "/tɔːrˈneɪdoʊ/", def: "A mobile, destructive vortex of violently rotating winds having the appearance of a funnel-shaped cloud.", defVn: "lốc xoáy, vòi rồng cuốn", pos: "noun", ex: ["The powerful tornado touched down and uprooted large trees.", "Seek shelter in an underground basement during a tornado warning."], exVn: ["Cơn lốc xoáy dữ dội quét qua và nhổ bật gốc những cây lớn.", "Hãy tìm nơi trú ẩn dưới tầng hầm khi có cảnh báo lốc xoáy."] },
    { word: "hail", phonetic: "/heɪl/", def: "Pellets of frozen rain which fall in showers from cumulonimbus clouds.", defVn: "mưa đá", pos: "noun", ex: ["A sudden hail storm covered the mountain village in ice pellets.", "Hail stones damaged the fruit orchards."], exVn: ["Trận mưa đá bất ngờ phủ kín ngôi làng miền núi bằng những viên băng.", "Mưa đá đã làm hư hại các vườn cây ăn trái."] },
    { word: "earthquake", phonetic: "/ˈɜːrθkweɪk/", def: "A sudden and violent shaking of the ground, sometimes causing great destruction.", defVn: "trận động đất, địa chấn", pos: "noun", ex: ["Drop, cover, and hold on under a sturdy desk during an earthquake.", "The earthquake tremor was felt across three provinces."], exVn: ["Hãy cúi xuống, che chắn và bám chặt dưới chiếc bàn vững chắc khi động đất.", "Rung chấn động đất đã được cảm nhận tại ba tỉnh thành."] },
    { word: "tsunami", phonetic: "/tsuːˈnɑːmi/", def: "A long high sea wave caused by an earthquake, submarine landslide, or other disturbance.", defVn: "sóng thần đại dương", pos: "noun", ex: ["Coastal early-warning siren systems protect residents from tsunamis.", "Move immediately to higher ground when a tsunami alert sounds."], exVn: ["Hệ thống còi báo động sớm ven biển giúp bảo vệ người dân khỏi sóng thần.", "Hãy di chuyển ngay lên vùng đất cao khi có còi báo động sóng thần."] },
    { word: "landslide", phonetic: "/ˈlændslaɪd/", def: "The sliding down of a mass of earth or rock from a mountain or cliff.", defVn: "sạt lở đất đá trên đồi núi", pos: "noun", ex: ["Heavy mountain rainfall triggered a dangerous landslide across the pass.", "Road crews cleared rocks from the landslide."], exVn: ["Mưa lớn trên núi đã gây ra vụ sạt lở đất nguy hiểm trên cung đèo.", "Các đội công nhân đã dọn dẹp đất đá sau vụ sạt lở."] },
    { word: "avalanche", phonetic: "/ˈævəlæntʃ/", def: "A mass of snow, ice, and rocks falling rapidly down a mountainside.", defVn: "tuyết lở trên sườn núi", pos: "noun", ex: ["Skiers must carry rescue beacons in case of an avalanche.", "The loud roar echoed as the snowy avalanche cascaded down."], exVn: ["Những người trượt tuyết phải mang thiết bị định vị cứu hộ đề phòng tuyết lở.", "Tiếng gầm vang dội khi trận tuyết lở cuồn cuộn đổ xuống sườn núi."] },
    { word: "heatwave", phonetic: "/ˈhiːtweɪv/", def: "A prolonged period of abnormally hot weather.", defVn: "đợt nắng nóng gay gắt kéo dài", pos: "noun", ex: ["Drink plenty of fluids and stay indoors during a summer heatwave.", "The record heatwave pushed temperatures above 40 degrees."], exVn: ["Hãy uống nhiều nước và ở trong nhà suốt đợt nắng nóng gay gắt.", "Đợt nắng nóng kỷ lục đã đẩy nhiệt độ vượt mốc 40 độ C."] },
    { word: "blizzard", phonetic: "/ˈblɪzərd/", def: "A severe snowstorm with high winds and low visibility.", defVn: "trận bão tuyết dữ dội", pos: "noun", ex: ["The winter blizzard brought sub-zero temperatures and whiteout conditions.", "Flights were grounded due to the heavy blizzard."], exVn: ["Trận bão tuyết mùa đông mang theo nhiệt độ âm và tầm nhìn trắng xóa.", "Các chuyến bay đã bị hoãn do cơn bão tuyết lớn."] },
    { word: "shelter", phonetic: "/ˈʃeltər/", def: "A place giving temporary protection from bad weather or danger.", defVn: "nơi trú ẩn, điểm trú bão an toàn", pos: "noun", ex: ["Villagers gathered inside the reinforced concrete storm shelter.", "Take shelter under a covered building."], exVn: ["Dân làng tụ họp bên trong khu nhà trú bão bê tông kiên cố.", "Hãy tìm nơi trú ẩn dưới một tòa nhà có mái che nhé."] },
    { word: "warning", phonetic: "/ˈwɔːrnɪŋ/", def: "A statement or event that indicates a possible or impending danger.", defVn: "lời cảnh báo, tin báo động", pos: "noun", ex: ["The national weather agency issued an urgent flood warning.", "Heed safety warnings and stay safe indoors."], exVn: ["Cơ quan khí tượng quốc gia đã phát đi cảnh báo lũ lụt khẩn cấp.", "Hãy chú ý đến các cảnh báo an toàn và ở yên trong nhà."] }
  ],

  // Theme 34: Địa hình & Cảnh quan (Landforms & Landscapes)
  t_basic_landforms_landscapes: [
    { word: "mountain", phonetic: "/ˈmaʊntn/", def: "A large natural elevation of the earth's surface rising abruptly from the surrounding level.", defVn: "ngọn núi cao, đồi núi", pos: "noun", ex: ["Fansipan is the highest mountain peak in Indochina.", "We hiked up the scenic mountain trail early in the morning."], exVn: ["Fansipan là đỉnh núi cao nhất bán đảo Đông Dương.", "Chúng tôi leo lên con đường mòn ngắm cảnh núi từ sáng sớm."] },
    { word: "hill", phonetic: "/hɪl/", def: "A naturally raised area of land, not as high or craggy as a mountain.", defVn: "ngọn đồi thoai thoải", pos: "noun", ex: ["Green rolling tea hills in Moc Chau look like a green carpet.", "Children ran joyfully down the grassy hill."], exVn: ["Những đồi chè xanh mướt uốn lượn ở Mộc Châu trông như tấm thảm xanh.", "Lũ trẻ chạy nhảy vui vẻ xuống sườn đồi cỏ."] },
    { word: "valley", phonetic: "/ˈvæli/", def: "A low area of land between hills or mountains, typically with a river or stream flowing through it.", defVn: "thung lũng xanh tươi", pos: "noun", ex: ["Muong Hoa Valley in Sapa is famous for cascading rice terraces.", "Morning mist nestled peacefully in the deep valley."], exVn: ["Thung lũng Mường Hoa ở Sa Pa nổi tiếng với những thửa ruộng bậc thang.", "Làn sương sớm nép mình yên bình trong thung lũng sâu."] },
    { word: "plain", phonetic: "/pleɪn/", def: "A large area of flat land with few trees.", defVn: "đồng bằng châu thổ", pos: "noun", ex: ["The fertile Mekong Delta plain produces vast quantities of rice.", "Golden wheat fields stretched across the open plain."], exVn: ["Vùng đồng bằng sông Cửu Long màu mỡ sản xuất lượng lúa gạo khổng lồ.", "Những cánh đồng lúa mì vàng óng trải dài trên vùng đồng bằng rộng mở."] },
    { word: "plateau", phonetic: "/plæˈtoʊ/", def: "An area of relatively level high ground.", defVn: "cao nguyên lộng gió", pos: "noun", ex: ["The Central Highlands plateau is famous for rich basalt soil and coffee.", "Da Lat sits on the scenic Langbiang plateau."], exVn: ["Cao nguyên Tây Nguyên nổi tiếng với đất đỏ bazan màu mỡ và cà phê.", "Đà Lạt nằm trên cao nguyên Langbiang thơ mộng."] },
    { word: "desert", phonetic: "/ˈdezərt/", def: "A dry, barren area of land, especially one covered with sand.", defVn: "sa mạc, đồi cát khô cằn", pos: "noun", ex: ["The white and red sand dunes in Mui Ne resemble a mini desert.", "Camels are well adapted to harsh desert environments."], exVn: ["Đồi cát trắng và cát đỏ ở Mũi Né trông như một sa mạc thu nhỏ.", "Lạc đà thích nghi rất tốt với môi trường sa mạc khắc nghiệt."] },
    { word: "jungle", phonetic: "/ˈdʒʌŋɡl/", def: "An area of land overgrown with dense forest and tangled vegetation, typically in the tropics.", defVn: "khu rừng rậm nhiệt đới", pos: "noun", ex: ["Cuc Phuong National Park contains a pristine tropical jungle.", "Tigers and exotic birds thrive inside the dense jungle."], exVn: ["Vườn Quốc gia Cúc Phương có khu rừng rậm nhiệt đới nguyên sinh.", "Hổ và các loài chim quý phát triển mạnh trong rừng rậm."] },
    { word: "cave", phonetic: "/keɪv/", def: "A natural underground chamber in a hillside or cliff.", defVn: "hang động kỳ vĩ", pos: "noun", ex: ["Son Doong is the world's largest natural cave, located in Quang Binh.", "Stalactites hang gracefully from the cave ceiling."], exVn: ["Sơn Đoòng là hang động tự nhiên lớn nhất thế giới, nằm ở Quảng Bình.", "Những nhũ đá rủ xuống đầy duyên dáng từ trần hang động."] },
    { word: "cliff", phonetic: "/klɪf/", def: "A steep rock face, especially at the edge of the sea.", defVn: "vách đá dựng đứng, vách núi", pos: "noun", ex: ["Waves crashed dramatically against the high sea cliff.", "Seabirds nest safely on the rocky cliff faces."], exVn: ["Sóng biển vỗ rì rào đầy ấn tượng vào vách đá dựng đứng.", "Chim biển làm tổ an toàn trên những vách đá chênh vênh."] },
    { word: "coast", phonetic: "/koʊst/", def: "The part of the land adjoining or near the sea.", defVn: "bờ biển, dải duyên hải", pos: "noun", ex: ["Vietnam has a stunning coastline extending over 3,260 kilometers.", "Lighthouses guide cargo ships along the rocky coast."], exVn: ["Việt Nam sở hữu đường bờ biển tuyệt đẹp dài hơn 3.260 km.", "Những ngọn hải đăng chỉ đường cho tàu hàng dọc bờ biển đá."] },
    { word: "bay", phonetic: "/beɪ/", def: "A broad inlet of the sea where the land curves inward.", defVn: "vịnh biển", pos: "noun", ex: ["Ha Long Bay is world-renowned for its emerald waters and limestone islets.", "Boats anchored peacefully inside the sheltered bay."], exVn: ["Vịnh Hạ Long nổi tiếng thế giới với làn nước ngọc bích và đảo đá vôi.", "Thuyền bè thả neo yên bình trong vịnh biển kín gió."] },
    { word: "lake", phonetic: "/leɪk/", def: "A large body of water surrounded by land.", defVn: "hồ nước", pos: "noun", ex: ["Hoan Kiem Lake is the historic heart and soul of Hanoi.", "We enjoyed a boat ride on Ba Be Lake."], exVn: ["Hồ Hoàn Kiếm là trái tim và linh hồn lịch sử của Hà Nội.", "Chúng tôi đã tận hưởng chuyến du ngoạn bằng thuyền trên Hồ Ba Bể."] },
    { word: "stream", phonetic: "/striːm/", def: "A small, narrow river.", defVn: "con suối nhỏ róc rách", pos: "noun", ex: ["Clear mountain water flowed gently down the stony stream.", "We cooled our feet in the refreshing stream."], exVn: ["Dòng nước núi trong vắt chảy róc rách êm đềm qua con suối đá.", "Chúng tôi ngâm chân làm mát trong dòng suối mát lành."] },
    { word: "dune", phonetic: "/duːn/", def: "A mound or ridge of sand formed by the wind, especially on the seacoast or in a desert.", defVn: "cồn cát, đồi cát bay", pos: "noun", ex: ["Visitors enjoy riding quad bikes over the golden sand dunes.", "The wind reshapes the desert sand dunes every day."], exVn: ["Du khách rất thích lái xe địa hình trên những đồi cát vàng.", "Những cơn gió thay đổi hình dáng cồn cát sa mạc mỗi ngày."] },
    { word: "canyon", phonetic: "/ˈkænjən/", def: "A deep gorge, typically one with a river flowing through it.", defVn: "hẻm núi sâu, vực sâu", pos: "noun", ex: ["Tu San Canyon in Ha Giang is the deepest canyon in Southeast Asia.", "The emerald Nho Que River flows through the deep canyon."], exVn: ["Hẻm vực Tu Sản ở Hà Giang là hẻm núi sâu nhất Đông Nam Á.", "Dòng sông Nho Quế màu ngọc bích chảy qua hẻm núi sâu thẳm."] }
  ],

  // Theme 35: Sinh vật biển & Đại dương (Marine Life & Ocean)
  t_basic_marine_life: [
    { word: "shark", phonetic: "/ʃɑːrk/", def: "A long-bodied chiefly marine fish, with a cartilaginous skeleton and toothlike scales.", defVn: "cá mập (loài săn mồi đại dương)", pos: "noun", ex: ["Whale sharks are gentle giants that feed only on tiny plankton.", "Sharks play a vital role in maintaining ocean balance."], exVn: ["Cá mập voi là những gã khổng lồ hiền lành chỉ ăn sinh vật phù du.", "Cá mập đóng vai trò sống còn trong việc cân bằng đại dương."] },
    { word: "octopus", phonetic: "/ˈɑːktəpʊs/", def: "An eight-armed cephalopod mollusk with a soft body, large eyes, and no internal shell.", defVn: "con bạch tuộc (8 xúc tu)", pos: "noun", ex: ["The clever octopus camouflaged itself perfectly against the reef.", "An octopus has three hearts and blue blood."], exVn: ["Chú bạch tuộc thông minh ngụy trang hoàn hảo vào rạn san hô.", "Bạch tuộc có ba trái tim và dòng máu màu xanh lam."] },
    { word: "squid", phonetic: "/skwɪd/", def: "An elongated, fast-swimming cephalopod mollusk with eight arms and two long tentacles.", defVn: "con mực ống, mực biển", pos: "noun", ex: ["Grilled squid with chili sauce is a mouthwatering coastal delicacy.", "Squid release dark ink to escape from predators."], exVn: ["Mực nướng muối ớt là món đặc sản biển thơm ngon nức mũi.", "Mực phun mực đen để trốn thoát kẻ săn mồi."] },
    { word: "crab", phonetic: "/kræb/", def: "A crustacean, typically having a broad carapace, stalked eyes, and five pairs of legs.", defVn: "con cua biển, ghẹ", pos: "noun", ex: ["Steamed sea crab with lemon pepper dip is delicious.", "Crabs walk sideways along the sandy ocean shoreline."], exVn: ["Cua biển hấp chấm muối tiêu chanh rất thơm ngon.", "Những chú cua bò ngang dọc theo bờ biển cát mịn."] },
    { word: "shrimp", phonetic: "/ʃrɪmp/", def: "A small free-swimming crustacean with an elongated body, typically marine.", defVn: "con tôm biển", pos: "noun", ex: ["Grilled garlic shrimp is a staple at beach barbecues.", "Vietnam is one of the world's leading shrimp exporters."], exVn: ["Tôm nướng tỏi là món ăn quen thuộc trong các bữa tiệc nướng bãi biển.", "Việt Nam là một trong những quốc gia xuất khẩu tôm hàng đầu thế giới."] },
    { word: "lobster", phonetic: "/ˈlɑːbstər/", def: "A large marine crustacean with a cylindrical body, stalked eyes, and the first of its five pairs of limbs modified as large claws.", defVn: "tôm hùm sang trọng", pos: "noun", ex: ["Binh Ba Island is celebrated for fresh, sweet local lobster.", "Grilled cheese lobster is a luxury gourmet dish."], exVn: ["Đảo Bình Ba nổi danh với món tôm hùm tươi ngon ngọt thịt.", "Tôm hùm nướng phô mai là món ăn cao cấp hảo hạng."] },
    { word: "jellyfish", phonetic: "/ˈdʒelifɪʃ/", def: "A free-swimming marine coelenterate with a gelatinous umbrella-shaped bell and trailing tentacles.", defVn: "con sứa biển (thân trong suốt)", pos: "noun", ex: ["Glowing translucent jellyfish drifted gracefully through the deep water.", "Avoid touching stinging jellyfish tentacles at the beach."], exVn: ["Những chú sứa phát sáng trong suốt trôi dạt duyên dáng dưới nước sâu.", "Tránh chạm vào xúc tu có nọc độc của sứa ở bãi biển nhé."] },
    { word: "seahorse", phonetic: "/ˈsiːhɔːrs/", def: "A small marine fish with an upright posture, a horse-like head, and a prehensile tail.", defVn: "con cá ngựa (sinh vật biển độc đáo)", pos: "noun", ex: ["Male seahorses carry and care for eggs in a specialized brood pouch.", "The tiny seahorse anchored its tail to sea grass."], exVn: ["Cá ngựa đực mang và chăm sóc trứng trong chiếc túi ấp đặc biệt.", "Chú cá ngựa nhỏ xíu dùng đuôi quấn chặt vào nhánh cỏ biển."] },
    { word: "sea turtle", phonetic: "/siː ˈtɜːrtl/", def: "A large marine turtle with paddle-like flippers, inhabiting tropical and subtropical seas.", defVn: "con rùa biển, vích", pos: "noun", ex: ["Con Dao National Park is a famous sanctuary for nesting sea turtles.", "Baby sea turtles crawl instinctively toward the moonlit ocean."], exVn: ["Vườn Quốc gia Côn Đảo là khu bảo tồn nổi tiếng cho rùa biển đẻ trứng.", "Rùa biển con bò theo bản năng về phía đại dương ngập ánh trăng."] },
    { word: "seal", phonetic: "/siːl/", def: "A fish-eating aquatic mammal with a streamlined body and feet developed as flippers.", defVn: "con hải cẩu", pos: "noun", ex: ["Playful seals basked under the warm sun on the rocky shore.", "Seals swim gracefully through freezing polar waters."], exVn: ["Những chú hải cẩu tinh nghịch sưởi nắng ấm trên bờ đá.", "Hải cẩu bơi lội uyển chuyển trong làn nước băng giá vùng cực."] },
    { word: "coral", phonetic: "/ˈkɔːrəl/", def: "A hard stony substance secreted by certain marine coelenterates as an external skeleton.", defVn: "rạn san hô rực rỡ", pos: "noun", ex: ["Colorful coral reefs in Phu Quoc are home to thousands of fish species.", "Snorkeling over the vibrant coral garden was breathtaking."], exVn: ["Những rạn san hô rực rỡ ở Phú Quốc là ngôi nhà của hàng ngàn loài cá.", "Lặn ngắm vườn san hô rực rỡ sắc màu là trải nghiệm tuyệt vời."] },
    { word: "seaweed", phonetic: "/ˈsiːwiːd/", def: "Large algae growing in the sea or on rocks below the high-water mark.", defVn: "rong biển, tảo biển bổ dưỡng", pos: "noun", ex: ["Seaweed soup is highly nutritious and rich in natural minerals.", "Dried crispy seaweed snacks are delicious and healthy."], exVn: ["Canh rong biển rất bổ dưỡng và giàu khoáng chất tự nhiên.", "Món ăn vặt rong biển sấy giòn rất thơm ngon và lành mạnh."] },
    { word: "starfish", phonetic: "/ˈstɑːrfɪʃ/", def: "A marine echinoderm with five or more radiating arms; sea star.", defVn: "con sao biển (hình ngôi sao)", pos: "noun", ex: ["Starfish Bay in Phu Quoc is famous for red starfish on the sand.", "A starfish can regenerate a lost arm over time."], exVn: ["Rạch Vẹm ở Phú Quốc nổi tiếng với bãi sao biển đỏ trên cát.", "Sao biển có thể tự tái tạo lại cánh tay đã mất theo thời gian."] },
    { word: "clam", phonetic: "/klæm/", def: "A marine bivalve mollusk with shells of equal size.", defVn: "con ngao, con nghêu", pos: "noun", ex: ["Steamed clams with fragrant lemongrass and chili is a classic dish.", "Clams burrow into wet sand on the beach."], exVn: ["Nghêu hấp sả ớt thơm lừng là món ăn kinh điển.", "Ngao vùi mình dưới lớp cát ướt trên bãi biển."] },
    { word: "oyster", phonetic: "/ˈɔɪstər/", def: "Any of a number of bivalve mollusks with rough irregular shells, some of which produce pearls.", defVn: "con hàu, con trai ngọc", pos: "noun", ex: ["Grilled oysters with scallion oil and crushed peanuts are mouthwatering.", "Oysters purify ocean water naturally by filtering it."], exVn: ["Hàu nướng mỡ hành rắc đậu phộng thơm ngon nức nở.", "Hàu làm sạch nước biển tự nhiên bằng cách lọc nước."] }
  ],

  // Theme 36: Côn trùng & Sâu bọ (Insects & Small Bugs)
  t_basic_insects_bugs: [
    { word: "bee", phonetic: "/biː/", def: "A flying insect closely related to wasps and ants, known for role in pollination and producing honey.", defVn: "con ong mật (thụ phấn và làm mật)", pos: "noun", ex: ["Worker bees collect sweet nectar from blooming spring flowers.", "Bees produce delicious pure organic honey."], exVn: ["Những chú ong thợ chăm chỉ lấy mật từ hoa xuân nở rộ.", "Ong tạo ra mật ong nguyên chất thơm ngon bổ dưỡng."] },
    { word: "ant", phonetic: "/ænt/", def: "A small insect, typically having a sting and living in a complex social colony.", defVn: "con kiến (chăm chỉ, đoàn kết)", pos: "noun", ex: ["Hardworking ants can carry items twenty times their body weight.", "A neat line of ants marched across the garden path."], exVn: ["Những chú kiến cần cù có thể vác vật nặng gấp 20 lần cơ thể mình.", "Một hàng kiến ngay ngắn hành quân qua lối đi trong vườn."] },
    { word: "mosquito", phonetic: "/məˈskiːtoʊ/", def: "A slender long-legged fly with aquatic larvae, the bite of which can transmit malaria.", defVn: "con muỗi (truyền bệnh)", pos: "noun", ex: ["Use a mosquito net and repellent spray to prevent bites.", "Mosquitoes breed in standing, stagnant water."], exVn: ["Hãy mắc màn và dùng xịt chống muỗi để tránh bị đốt.", "Muỗi sinh sản trong các vũng nước đọng."] },
    { word: "butterfly", phonetic: "/ˈbʌtərflaɪ/", def: "An insect with two pairs of large wings that are covered in tiny scales, usually brightly colored.", defVn: "con bướm sặc sỡ", pos: "noun", ex: ["A colorful monarch butterfly fluttered gracefully from flower to flower.", "Caterpillars transform into gorgeous butterflies."], exVn: ["Một chú bướm rực rỡ sắc màu bay lượn duyên dáng từ bông hoa này sang bông hoa khác.", "Sâu bướm biến hóa thành những cánh bướm tuyệt đẹp."] },
    { word: "dragonfly", phonetic: "/ˈdræɡənflaɪ/", def: "A fast-flying long-bodied predatory insect with two pairs of large transparent wings.", defVn: "con chuồn chuồn", pos: "noun", ex: ["A shimmering blue dragonfly hovered gracefully above the lotus pond.", "Dragonflies eat harmful mosquitoes in gardens."], exVn: ["Một chú chuồn chuồn xanh lấp lánh bay lượn trên hồ sen.", "Chuồn chuồn bắt muỗi gây hại trong vườn."] },
    { word: "ladybug", phonetic: "/ˈleɪdibʌɡ/", def: "A small round beetle which is typically red with black spots; ladybird.", defVn: "con bọ rùa (đỏ chấm đen)", pos: "noun", ex: ["A cute red ladybug with black dots crawled along the green leaf.", "Ladybugs are beneficial garden predators that eat aphids."], exVn: ["Một chú bọ rùa đỏ chấm đen đáng yêu bò trên chiếc lá xanh.", "Bọ rùa là loài côn trùng có ích giúp bắt rệp trong vườn."] },
    { word: "fly", phonetic: "/flaɪ/", def: "A flying insect of a large order characterized by the possession of two wings.", defVn: "con ruồi", pos: "noun", ex: ["Cover food on the table to keep flies away.", "A fly buzzed around the sunny kitchen window."], exVn: ["Đậy thức ăn trên bàn lại để ruồi không bậu vào.", "Một con ruồi bay vo ve quanh cửa sổ bếp nhiều nắng."] },
    { word: "spider", phonetic: "/ˈspaɪdər/", def: "An eight-legged predatory arachnid with an unsegmented body, having venomous fangs and spinning webs.", defVn: "con nhện (giăng tơ bắt mồi)", pos: "noun", ex: ["The industrious spider spun an intricate circular web overnight.", "Dewdrops sparkled on the spider's silky web."], exVn: ["Chú nhện chăm chỉ đã giăng một chiếc mạng tròn tinh xảo chỉ sau một đêm.", "Những giọt sương sớm lấp lánh trên chiếc mạng nhện tơ."] },
    { word: "cockroach", phonetic: "/ˈkɑːkroʊtʃ/", def: "A scavenging insect that resembles a beetle, with long antennae and legs.", defVn: "con gián (sống nơi ẩm tối)", pos: "noun", ex: ["Keep the kitchen clean and dry to prevent cockroaches.", "Cockroaches can survive in harsh environments."], exVn: ["Hãy giữ nhà bếp sạch sẽ và khô ráo để phòng chống gián.", "Gián có thể sinh tồn trong những môi trường khắc nghiệt."] },
    { word: "grasshopper", phonetic: "/ˈɡræshɑːpər/", def: "A plant-eating insect with long hind legs which are used for jumping and for producing a chirping sound.", defVn: "con cào cào, con châu chấu", pos: "noun", ex: ["A green grasshopper leaped high across the tall grass.", "Grasshoppers chirp rhythmically on warm summer evenings."], exVn: ["Một chú cào cào xanh bật nhảy thật cao qua bãi cỏ rậm.", "Châu chấu kêu rả rích nhịp nhàng vào những đêm hè ấm áp."] },
    { word: "cricket", phonetic: "/ˈkrɪkɪt/", def: "An insect related to the grasshoppers but with shorter legs, the male producing a characteristic chirping sound.", defVn: "con dế mèn", pos: "noun", ex: ["The soothing chirp of crickets filled the peaceful rural night.", "Children read the beloved adventure story of Men the Cricket."], exVn: ["Tiếng dế mèn gáy êm đềm lấp đầy màn đêm thôn quê thanh bình.", "Các em nhỏ đọc truyện phiêu lưu nổi tiếng 'Dế Mèn phiêu lưu ký'."] },
    { word: "caterpillar", phonetic: "/ˈkætərpɪlər/", def: "The larva of a butterfly or moth, having a segmented wormlike body with three pairs of true legs.", defVn: "con sâu bướm", pos: "noun", ex: ["The fuzzy green caterpillar munched hungrily on a fresh green leaf.", "The caterpillar spun a cozy silk cocoon."], exVn: ["Chú sâu bướm xanh mướt ngấu nghiến chiếc lá xanh tươi non.", "Sâu bướm đã nhả tơ dệt chiếc kén ấm áp."] },
    { word: "worm", phonetic: "/wɜːrm/", def: "Any of a number of creeping or burrowing invertebrate animals with long, slender soft bodies.", defVn: "con giun đất, con sâu", pos: "noun", ex: ["Earthworms enrich and aerate the garden soil naturally.", "Robins search for juicy earthworms after morning rain."], exVn: ["Giun đất làm tơi xốp và màu mỡ đất vườn một cách tự nhiên.", "Chim sâu tìm những chú giun đất béo ngậy sau cơn mưa sớm."] },
    { word: "snail", phonetic: "/sneɪl/", def: "A mollusk with a single spiral shell into which the whole body can be withdrawn.", defVn: "con ốc sên (chậm chạp)", pos: "noun", ex: ["A slow snail crawled across the garden path carrying its shell.", "Snails leave a shiny silver trail behind them."], exVn: ["Chú ốc sên chậm chạp bò qua lối đi trong vườn vác theo chiếc vỏ.", "Ốc sên để lại một vệt sáng ánh bạc sau lưng."] },
    { word: "beetle", phonetic: "/ˈbiːtl/", def: "An insect of a large order distinguished by forewings that are typically modified into hard wing cases.", defVn: "con bọ cánh cứng, bọ hung", pos: "noun", ex: ["The rhinoceros beetle has a strong horn on its head.", "Shiny green beetles crawled along the tree bark."], exVn: ["Bọ cánh cứng tê giác có chiếc sừng rất khỏe trên đầu.", "Những chú bọ cánh cứng màu xanh bóng bò dọc trên vỏ cây."] }
  ],

  // Theme 37: Gia vị & Hương vị (Spices, Herbs & Flavors)
  t_basic_spices_herbs: [
    { word: "pepper", phonetic: "/ˈpepər/", def: "A pungent, hot-tasting powder prepared from dried and ground peppercorns.", defVn: "hạt tiêu xay (cay nồng)", pos: "noun", ex: ["Phu Quoc black pepper is famous for its intense aroma.", "Grind fresh black pepper over your beef steak."], exVn: ["Tiêu đen Phú Quốc nổi tiếng với hương thơm nồng nàn đặc trưng.", "Xay tiêu đen tươi lên miếng bít tết bò nhé."] },
    { word: "chili", phonetic: "/ˈtʃɪli/", def: "A small hot-tasting pod of a variety of capsicum, used chopped, fresh, or dried in cooking.", defVn: "quả ớt (cay xé lưỡi)", pos: "noun", ex: ["Add a slice of fresh red chili to your pho broth for spicy kick.", "Bird's eye chili is extremely spicy."], exVn: ["Thêm một lát ớt tươi đỏ vào nước dùng phở để có vị cay nồng.", "Ớt chỉ thiên có vị cay xé lưỡi."] },
    { word: "ginger", phonetic: "/ˈdʒɪndʒər/", def: "A hot, fragrant spice made from the rhizome of a plant, used in cooking and herbal medicine.", defVn: "củ gừng (ấm bụng, thơm)", pos: "noun", ex: ["Warm ginger tea with honey soothes a sore throat instantly.", "Add sliced fresh ginger to steamed fish."], exVn: ["Trà gừng ấm pha mật ong giúp làm dịu cơn đau họng tức thì.", "Thêm vài lát gừng tươi vào món cá hấp nhé."] },
    { word: "garlic", phonetic: "/ˈɡɑːrlɪk/", def: "A strong-smelling pungent-tasting bulb, used as a flavoring in cooking and in herbal medicine.", defVn: "củ tỏi, nhánh tỏi", pos: "noun", ex: ["Ly Son Island is renowned for its delicious single-clove garlic.", "Sauté fresh morning spinach with crushed garlic."], exVn: ["Đảo Lý Sơn nức tiếng với tỏi cô đơn thơm ngon.", "Xào rau muống tươi với tỏi đập dập thơm lừng."] },
    { word: "onion", phonetic: "/ˈʌnjən/", def: "An edible bulb with a pungent taste and smell, composed of several concentric layers.", defVn: "củ hành tây", pos: "noun", ex: ["Caramelized sliced onions add natural sweetness to soup.", "Chop onions carefully to avoid tearing up."], exVn: ["Hành tây thái lát xào chín tạo vị ngọt tự nhiên cho nồi súp.", "Thái hành tây cẩn thận để tránh bị cay mắt nhé."] },
    { word: "fish sauce", phonetic: "/fɪʃ sɔːs/", def: "A liquid condiment made from fish or krill that have been coated in salt and fermented.", defVn: "nước mắm truyền thống", pos: "noun", ex: ["Traditional Vietnamese fish sauce gives authentic umami flavor to dishes.", "Phu Quoc fish sauce is nationally celebrated."], exVn: ["Nước mắm truyền thống Việt Nam tạo vị ngọt umami chuẩn vị cho các món ăn.", "Nước mắm Phú Quốc nức tiếng cả nước."] },
    { word: "soy sauce", phonetic: "/sɔɪ sɔːs/", def: "A dark, salty sauce made from fermented soybeans, used widely in Asian cooking.", defVn: "nước tương, xì dầu", pos: "noun", ex: ["Dip fried tofu into a bowl of rich garlic soy sauce.", "Soy sauce is a staple seasoning in vegetarian cuisine."], exVn: ["Chấm đậu phụ rán vào bát nước tương tỏi thơm ngon.", "Xì dầu là loại gia vị thiết yếu trong ẩm thực chay."] },
    { word: "vinegar", phonetic: "/ˈvɪnɪɡər/", def: "A sour-tasting liquid containing acetic acid, obtained by fermenting dilute alcoholic liquids.", defVn: "giấm ăn (vị chua thanh)", pos: "noun", ex: ["Add rice vinegar and sugar to make sweet and sour dipping sauce.", "Pickled garlic in vinegar is a popular pho condiment."], exVn: ["Thêm giấm gạo và đường để pha nước chấm chua ngọt.", "Tỏi ngâm giấm là gia vị ăn kèm phở rất được ưa chuộng."] },
    { word: "cinnamon", phonetic: "/ˈsɪnəmən/", def: "An aromatic spice made from the peeled, dried, and rolled bark of a Southeast Asian tree.", defVn: "thanh quế, bột quế thơm", pos: "noun", ex: ["Yen Bai cinnamon is famous for its rich warm fragrance.", "Simmer a stick of cinnamon in beef broth for pho."], exVn: ["Quế Yên Bái nổi tiếng với hương thơm ấm nồng đậm đà.", "Thả một thanh quế vào nồi nước dùng phở bò nhé."] },
    { word: "basil", phonetic: "/ˈbæzl/", def: "An aromatic annual herb of the mint family, native to tropical Asia.", defVn: "húng quế, rau quế", pos: "noun", ex: ["Fresh Thai basil leaves are served alongside steaming beef pho.", "Tear fresh basil leaves over Italian pizza."], exVn: ["Những lá húng quế tươi được phục vụ ăn kèm bát phở bò nóng hổi.", "Xé vài nhánh húng quế tươi lên bánh pizza Ý."] },
    { word: "mint", phonetic: "/mɪnt/", def: "An aromatic plant native to temperate regions, with leaves that yield a cooling flavoring.", defVn: "lá bạc hà, rau húng lủi", pos: "noun", ex: ["Fresh green mint leaves add a cooling taste to spring rolls.", "Drink a refreshing iced lemonade with crushed mint."], exVn: ["Lá bạc hà tươi tạo vị thơm mát cho món gỏi cuốn.", "Uống ly nước chanh đá mát lạnh dầm lá bạc hà."] },
    { word: "cilantro", phonetic: "/sɪˈlæntroʊ/", def: "The fresh leaves of the coriander plant, used as a culinary herb; coriander.", defVn: "rau mùi, rau ngò rí", pos: "noun", ex: ["Garnish hot chicken soup with finely chopped cilantro.", "Fresh cilantro adds vibrant aroma to banh mi sandwiches."], exVn: ["Rắc rau mùi thái nhỏ lên bát súp gà nóng hổi.", "Rau ngò rí tươi tạo hương thơm quyến rũ cho ổ bánh mì."] },
    { word: "lemongrass", phonetic: "/ˈlemənɡræs/", def: "A fragrant tropical grass that yields an oil with a lemon scent, used in Asian cooking.", defVn: "cây sả, củ sả thơm", pos: "noun", ex: ["Stir-fry tender chicken with fragrant minced lemongrass and chili.", "Lemongrass tea has a soothing citrus aroma."], exVn: ["Xào thịt gà mềm với sả băm thơm lừng và ớt.", "Trà sả có hương thơm cam chanh làm dịu tâm hồn."] },
    { word: "turmeric", phonetic: "/ˈtɜːrmərɪk/", def: "A bright yellow aromatic powder obtained from the rhizome of a plant of the ginger family.", defVn: "củ nghệ, bột nghệ vàng", pos: "noun", ex: ["Golden turmeric gives Cha Ca La Vong fish its iconic bright yellow color.", "Turmeric has powerful anti-inflammatory benefits."], exVn: ["Nghệ vàng tạo nên màu vàng óng đặc trưng cho món Chả cá Lã Vọng.", "Nghệ có tác dụng chống viêm cực kỳ hiệu quả."] },
    { word: "honey", phonetic: "/ˈhʌni/", def: "A sweet, sticky yellowish-brown fluid made by bees and other insects from nectar collected from flowers.", defVn: "mật ong nguyên chất", pos: "noun", ex: ["Pure forest honey is a healthy natural sweetener.", "Drink warm water with lemon and honey every morning."], exVn: ["Mật ong rừng nguyên chất là chất tạo ngọt tự nhiên tốt cho sức khỏe.", "Uống nước ấm pha chanh mật ong vào mỗi buổi sáng."] }
  ],

  // Theme 38: Bánh ngọt & Tráng miệng (Bakery & Desserts)
  t_basic_bakery_desserts: [
    { word: "cake", phonetic: "/keɪk/", def: "An item of soft sweet food made from a mixture of flour, shortening, eggs, and sugar.", defVn: "bánh ngọt, bánh kem sinh nhật", pos: "noun", ex: ["We blew out candles on the chocolate birthday cake.", "She baked a fluffy strawberry sponge cake."], exVn: ["Chúng tôi cùng thổi nến trên chiếc bánh sinh nhật sô-cô-la.", "Cô ấy nướng chiếc bánh bông lan dâu tây xốp mềm."] },
    { word: "cookie", phonetic: "/ˈkʊki/", def: "A small sweet, crispy or chewy baked treat, typically containing flour, sugar, and chocolate chips.", defVn: "bánh quy, bánh cookie", pos: "noun", ex: ["Freshly baked chocolate chip cookies smell irresistible.", "Dip a crispy butter cookie into warm milk."], exVn: ["Những chiếc bánh quy sô-cô-la mới nướng tỏa hương thơm nức.", "Chấm chiếc bánh quy bơ giòn tan vào cốc sữa ấm."] },
    { word: "bread", phonetic: "/bred/", def: "Food made of flour, water, and yeast or another leavening agent, mixed and baked.", defVn: "bánh mì (ổ, lát)", pos: "noun", ex: ["Crispy Vietnamese banh mi baguette is famous worldwide.", "Toast two slices of whole wheat bread for breakfast."], exVn: ["Bánh mì que giòn rụm của Việt Nam nổi tiếng khắp thế giới.", "Nướng hai lát bánh mì nguyên cám cho bữa sáng."] },
    { word: "croissant", phonetic: "/krwɑːˈsɑːnt/", def: "A French crescent-shaped roll made of sweet flaky yeast dough, like puff pastry.", defVn: "bánh sừng bò (ngàn lớp bơ giòn)", pos: "noun", ex: ["A warm flaky butter croissant pairs perfectly with morning coffee.", "The bakery bakes golden croissants fresh daily."], exVn: ["Chiếc bánh sừng bò bơ ngàn lớp giòn tan ăn cùng cà phê sáng thật tuyệt.", "Tiệm bánh nướng bánh sừng bò vàng ươm tươi mới mỗi ngày."] },
    { word: "donut", phonetic: "/ˈdoʊnʌt/", def: "A small fried cake of sweetened dough, typically in the shape of a ring or ball.", defVn: "bánh vòng donut (phủ đường/sô-cô-la)", pos: "noun", ex: ["Children love colorful glazed donuts with rainbow sprinkles.", "He ordered a chocolate frosted donut with hot tea."], exVn: ["Trẻ con rất thích những chiếc bánh donut phủ đường rắc kẹo màu.", "Anh ấy gọi chiếc bánh donut phủ sô-cô-la dùng cùng trà nóng."] },
    { word: "muffin", phonetic: "/ˈmʌfɪn/", def: "A small domed spongy cake made with yeast and baked in a cup-shaped foil.", defVn: "bánh nướng xốp muffin", pos: "noun", ex: ["Warm blueberry muffins fresh from the oven are delicious.", "She packed a banana walnut muffin for her school snack."], exVn: ["Những chiếc bánh muffin việt quất nóng hổi mới ra lò rất ngon.", "Cô bé mang theo chiếc bánh muffin chuối óc chó đi học."] },
    { word: "cupcake", phonetic: "/ˈkʌpkeɪk/", def: "A small cake baked in a cup-shaped foil or paper container and typically iced.", defVn: "bánh cupcake (trang trí kem bên trên)", pos: "noun", ex: ["Each party guest received a vanilla cupcake with pink frosting.", "She decorates handmade cupcakes with sugar flowers."], exVn: ["Mỗi khách dự tiệc đều nhận được chiếc bánh cupcake vani phủ kem hồng.", "Cô ấy trang trí những chiếc cupcake tự làm bằng hoa đường."] },
    { word: "pancake", phonetic: "/ˈpænkeɪk/", def: "A thin, flat cake of batter, fried on both sides in a pan and typically rolled up or topped with syrup.", defVn: "bánh kếp, bánh rán mỏng", pos: "noun", ex: ["Stack warm fluffy pancakes and drizzle pure maple syrup on top.", "Sunday morning pancakes with berries are a tradition."], exVn: ["Xếp chồng những chiếc bánh kếp xốp mềm và rưới si-rô phong lên trên.", "Bánh kếp ăn kèm quả mọng sáng Chủ Nhật là truyền thống gia đình."] },
    { word: "waffle", phonetic: "/ˈwɑːfl/", def: "A small crisp batter cake, baked in a waffle iron and eaten hot with butter or syrup.", defVn: "bánh quế tổ ong, bánh waffle", pos: "noun", ex: ["Crispy Belgian waffles topped with vanilla ice cream taste divine.", "The waffle iron leaves a classic checkered grid pattern."], exVn: ["Bánh waffle Bỉ giòn rụm ăn cùng kem vani ngon tuyệt hảo.", "Khuôn nướng waffle tạo hình kẻ ô bàn cờ kinh điển."] },
    { word: "pie", phonetic: "/paɪ/", def: "A baked dish of fruit, meat, or vegetables, typically with a top and base of pastry.", defVn: "bánh nướng có vỏ (bánh táo, bánh nhân)", pos: "noun", ex: ["Grandmother's warm homemade apple pie with cinnamon is comforting.", "Slice the golden baked pumpkin pie."], exVn: ["Món bánh táo nướng rắc quế ấm áp tự tay bà làm rất ấm cúng.", "Cắt lát chiếc bánh nướng bí ngô vàng ươm."] },
    { word: "tart", phonetic: "/tɑːrt/", def: "An open pastry case containing a sweet or savory filling.", defVn: "bánh tart (vỏ giòn nhân kem/trái cây)", pos: "noun", ex: ["The bakery serves miniature fruit tarts topped with fresh kiwi and berries.", "Portuguese egg tarts have a creamy custard filling."], exVn: ["Tiệm bánh phục vụ bánh tart trái cây mini trang trí kiwi và dâu tươi.", "Bánh tart trứng Bồ Đào Nha có lớp nhân kem trứng béo ngậy."] },
    { word: "ice cream", phonetic: "/ˈaɪs kriːm/", def: "A soft, frozen food made with sweetened and flavored milk fat.", defVn: "kem lạnh, kem ly", pos: "noun", ex: ["A scoop of Trang Tien coconut ice cream on a summer afternoon is blissful.", "What is your favorite ice cream flavor? — Matcha."], exVn: ["Một que kem dừa Tràng Tiền vào buổi chiều hè thật sảng khoái.", "Hương vị kem yêu thích của bạn là gì? — Trà xanh matcha."] },
    { word: "chocolate", phonetic: "/ˈtʃɑːklət/", def: "A food preparation in the form of a paste or solid block made from roasted and ground cacao seeds.", defVn: "sô-cô-la nguyên chất", pos: "noun", ex: ["Dark Vietnamese Marou chocolate has rich and complex notes.", "Hot melted chocolate sauce drizzled over dessert."], exVn: ["Sô-cô-la đen Marou của Việt Nam có hương vị đậm đà và tinh tế.", "Sốt sô-cô-la nóng chảy rưới lên món tráng miệng."] },
    { word: "pudding", phonetic: "/ˈpʊdɪŋ/", def: "A sweet cooked dish, typically of starch and milk, flavored with vanilla or fruit.", defVn: "bánh pudding mềm mịn", pos: "noun", ex: ["Silky smooth mango pudding with coconut cream is refreshing.", "Caramel egg pudding is a favorite treat for kids."], exVn: ["Món pudding xoài mềm mượt ăn cùng nước cốt dừa rất thanh mát.", "Bánh pudding trứng caramen là món khoái khẩu của trẻ nhỏ."] },
    { word: "dessert", phonetic: "/dɪˈzɜːrt/", def: "The sweet course eaten at the end of a meal.", defVn: "món tráng miệng ngọt ngào", pos: "noun", ex: ["Leave room for dessert; we have fresh fruit and flan cake.", "What would you like for dessert tonight?"], exVn: ["Hãy để bụng ăn món tráng miệng nhé; chúng ta có trái cây tươi và bánh flan.", "Tối nay bạn muốn dùng món tráng miệng gì nào?"] }
  ],

  // Theme 39: Đồ uống & Trà sữa (Drinks & Beverages)
  t_basic_drinks_beverages: [
    { word: "milk tea", phonetic: "/mɪlk tiː/", def: "A beverage made from tea mixed with milk, often served iced with tapioca boba pearls.", defVn: "trà sữa trân châu", pos: "noun", ex: ["Brown sugar boba milk tea is a popular drink among youth.", "Order milk tea with 50 percent sugar and less ice."], exVn: ["Trà sữa trân châu đường đen là thức uống rất được giới trẻ yêu thích.", "Gọi trà sữa với 50% đường và ít đá nhé."] },
    { word: "green tea", phonetic: "/ɡriːn tiː/", def: "Tea made from unfermented leaves that is pale in color and slightly bitter in flavor.", defVn: "trà xanh, chè xanh thanh nhiệt", pos: "noun", ex: ["Drinking antioxidant-rich green tea daily promotes longevity.", "Hot Thai Nguyen green tea is served to welcome guests."], exVn: ["Uống trà xanh giàu chất chống oxy hóa mỗi ngày giúp tăng tuổi thọ.", "Trà xanh Thái Nguyên nóng được rót mời khách quý."] },
    { word: "black tea", phonetic: "/blæk tiː/", def: "Tea that is more oxidized than oolong, green, and white teas, generally stronger in flavor.", defVn: "trà đen, hồng trà", pos: "noun", ex: ["English breakfast black tea tastes wonderful with a splash of milk.", "A cup of hot black tea warms you up in winter."], exVn: ["Hồng trà điểm tâm kiểu Anh uống cùng chút sữa tươi rất ngon.", "Tách trà đen nóng làm ấm người trong mùa đông."] },
    { word: "lemonade", phonetic: "/ˌleməˈneɪd/", def: "A drink made from lemon juice and water sweetened with sugar.", defVn: "nước chanh tươi mát lạnh", pos: "noun", ex: ["Ice-cold lemonade with mint leaves is the ultimate summer refresher.", "Freshly squeezed homemade lemonade tastes best."], exVn: ["Nước chanh đá mát lạnh với lá bạc hà là thức uống giải nhiệt mùa hè đỉnh cao.", "Nước chanh tự vắt ở nhà luôn thơm ngon nhất."] },
    { word: "smoothie", phonetic: "/ˈsmuːði/", def: "A thick, smooth drink of fresh fruit pureed with milk, yogurt, or ice cream.", defVn: "sinh tố trái cây xay nhuyễn", pos: "noun", ex: ["A mango and passionfruit smoothie is creamy and tangy.", "Start your energetic day with a green spinach smoothie."], exVn: ["Sinh tố xoài chanh leo béo ngậy và có vị chua ngọt thanh.", "Bắt đầu ngày mới tràn đầy năng lượng với ly sinh tố rau bina."] },
    { word: "soda", phonetic: "/ˈsoʊdə/", def: "Carbonated water, typically flavored and sweetened.", defVn: "nước ngọt có ga, nước soda", pos: "noun", ex: ["Sparkling lemon soda with salted preserved plum is refreshing.", "Limit sugary sodas to protect dental health."], exVn: ["Soda chanh muối xí muội có ga uống rất đã khát.", "Hạn chế uống nước ngọt có ga nhiều đường để bảo vệ răng."] },
    { word: "mineral water", phonetic: "/ˈmɪnərəl ˈwɔːtər/", def: "Water containing dissolved mineral salts or gases, especially taken for medicinal value.", defVn: "nước khoáng thiên nhiên", pos: "noun", ex: ["Natural mineral water bottled at the mountain spring is pure.", "Always stay hydrated with mineral water during workouts."], exVn: ["Nước khoáng thiên nhiên đóng chai từ nguồn suối núi rất tinh khiết.", "Luôn bổ sung nước khoáng trong suốt buổi tập luyện nhé."] },
    { word: "hot chocolate", phonetic: "/hɑːt ˈtʃɑːklət/", def: "A hot drink made with milk or water and chocolate or cocoa powder.", defVn: "sô-cô-la nóng, ca-cao nóng", pos: "noun", ex: ["A mug of rich hot chocolate topped with fluffy marshmallows warms cold nights.", "Sip hot chocolate by the fireplace."], exVn: ["Ly sô-cô-la nóng đậm đà rắc kẹo dẻo sưởi ấm những đêm lạnh giá.", "Nhâm nhi ca-cao nóng bên lò sưởi ấm cúng."] },
    { word: "iced coffee", phonetic: "/aɪst ˈkɔːfi/", def: "A beverage made from brewed coffee served cold over ice, often with condensed milk.", defVn: "cà phê sữa đá (đặc sản Việt Nam)", pos: "noun", ex: ["Vietnamese iced coffee with condensed milk is celebrated globally.", "Enjoying an iced coffee on a sidewalk stool is iconic."], exVn: ["Cà phê sữa đá Việt Nam được ca ngợi khắp toàn cầu.", "Thưởng thức ly cà phê sữa đá trên chiếc ghế vỉa hè là nét văn hóa đặc trưng."] },
    { word: "herbal tea", phonetic: "/ˈɜːrbl tiː/", def: "A beverage made from the infusion of herbs, spices, or other plant material in hot water.", defVn: "trà thảo mộc, trà thảo dược", pos: "noun", ex: ["Chamomile herbal tea helps calm the nervous system before bedtime.", "Drink artichoke herbal tea for liver health."], exVn: ["Trà thảo mộc hoa cúc giúp xoa dịu thần kinh trước giờ đi ngủ.", "Uống trà thảo mộc a-ti-sô rất tốt cho gan."] },
    { word: "coconut water", phonetic: "/ˈkoʊkənʌt ˈwɔːtər/", def: "The clear liquid found inside immature green coconuts, rich in electrolytes.", defVn: "nước dừa tươi ngọt mát", pos: "noun", ex: ["Fresh coconut water is a natural electrolyte beverage for athletes.", "Drink chilled sweet coconut water after exercise."], exVn: ["Nước dừa tươi là thức uống điện giải tự nhiên tuyệt vời cho vận động viên.", "Uống nước dừa ngọt ướp lạnh sau khi tập thể dục."] },
    { word: "orange juice", phonetic: "/ˈɔːrɪndʒ dʒuːs/", def: "The liquid extract of the orange tree fruit, produced by squeezing or reaming oranges.", defVn: "nước cam ép tươi", pos: "noun", ex: ["A glass of freshly squeezed orange juice provides your daily vitamin C.", "Start breakfast with chilled orange juice."], exVn: ["Một ly nước cam vắt tươi cung cấp đủ lượng vitamin C cho cả ngày.", "Bắt đầu bữa sáng với ly nước cam ép ướp lạnh."] },
    { word: "soy milk", phonetic: "/sɔɪ mɪlk/", def: "A beverage made from soybeans, resembling dairy milk and used as a substitute.", defVn: "sữa đậu nành nguyên chất", pos: "noun", ex: ["Hot fragrant soy milk served with fried dough sticks is classic.", "Organic soy milk is naturally lactose-free."], exVn: ["Sữa đậu nành nóng thơm lừng ăn kèm quẩy giòn là bữa sáng kinh điển.", "Sữa đậu nành hữu cơ tự nhiên không chứa lactose."] },
    { word: "bubble tea", phonetic: "/ˈbʌbl tiː/", def: "Another name for boba milk tea with chewy tapioca balls.", defVn: "trà sữa trân châu, trà sủi bọt", pos: "noun", ex: ["Chewy tapioca bubbles make bubble tea extra satisfying.", "She ordered matcha bubble tea with cheese foam."], exVn: ["Những hạt trân châu dẻo dai làm món trà sữa thêm phần thú vị.", "Cô ấy gọi trà sữa matcha thêm lớp kem phô mai."] },
    { word: "cocktail", phonetic: "/ˈkɑːkteɪl/", def: "An alcoholic drink consisting of a spirit or several spirits mixed with other ingredients.", defVn: "thức uống cocktail pha chế", pos: "noun", ex: ["Sip a tropical fruit mocktail cocktail while watching the ocean sunset.", "The bartender mixed an artisanal mint cocktail."], exVn: ["Nhâm nhi ly cocktail trái cây nhiệt đới trong lúc ngắm hoàng hôn biển.", "Người pha chế đã pha một ly cocktail bạc hà nghệ thuật."] }
  ],

  // Theme 40: Dọn dẹp & Việc nhà (Cleaning & House Chores)
  t_basic_cleaning_chores: [
    { word: "broom", phonetic: "/bruːm/", def: "A cleaning implement for sweeping, made of a bundle of straw or twigs attached to a long handle.", defVn: "cây chổi quét nhà (chổi rơm/nhựa)", pos: "noun", ex: ["Use a soft straw broom to sweep dust off the tiled floor.", "Hang the broom neatly behind the kitchen door."], exVn: ["Dùng chiếc chổi rơm mềm để quét sạch bụi bẩn trên sàn gạch.", "Treo chổi gọn gàng phía sau cánh cửa bếp."] },
    { word: "mop", phonetic: "/mɑːp/", def: "An implement consisting of a bundle of thick loose strings, a sponge, attached to a handle for wiping floors.", defVn: "cây lau nhà, chổi lau sàn", pos: "noun", ex: ["Mop the living room floor with scented floor cleaner.", "Wring out the wet mop before wiping wooden floors."], exVn: ["Lau sàn phòng khách bằng nước lau sàn thơm ngát.", "Vắt ráo cây lau nhà trước khi lau sàn gỗ nhé."] },
    { word: "dustpan", phonetic: "/ˈdʌstpæn/", def: "A flat handheld receptacle into which dust and waste can be swept from the floor.", defVn: "cái hót rác, xẻng hót rác", pos: "noun", ex: ["Sweep the floor sweepings directly into the plastic dustpan.", "Empty the dustpan into the trash can."], exVn: ["Quét rác trên sàn trực tiếp vào chiếc hót rác nhựa.", "Đổ rác từ xẻng hót rác vào thùng rác nhé."] },
    { word: "vacuum cleaner", phonetic: "/ˈvækjuːm ˈkliːnər/", def: "An electrical appliance for cleaning carpets and other surfaces by suction.", defVn: "máy hút bụi gia đình", pos: "noun", ex: ["Use the powerful vacuum cleaner to clean wool carpets thoroughly.", "A robotic vacuum cleaner cleans floors automatically."], exVn: ["Dùng máy hút bụi công suất lớn để làm sạch thảm len kỹ càng.", "Robot hút bụi tự động dọn dẹp sàn nhà mỗi ngày."] },
    { word: "sponge", phonetic: "/spʌndʒ/", def: "A piece of a light, absorbent substance used for washing, cleaning, or padding.", defVn: "miếng mút rửa bát, bọt biển", pos: "noun", ex: ["Apply dish soap on a wet sponge to scrub greasy plates.", "Rinse the cleaning sponge and let it air dry."], exVn: ["Cho nước rửa chén vào miếng bọt biển ướt để cọ đĩa dính dầu mỡ.", "Rửa sạch miếng mút rửa bát và để nơi khô thoáng."] },
    { word: "bucket", phonetic: "/ˈbʌkɪt/", def: "A roughly cylindrical open container with a handle, made of metal or plastic, used to hold and carry liquids.", defVn: "cái xô nước", pos: "noun", ex: ["Fill the cleaning bucket with warm soapy water for mopping.", "Carrying a full bucket of water builds arm strength."], exVn: ["Đổ đầy xô nước ấm pha xà phòng để lau nhà.", "Xách một xô nước đầy giúp rèn luyện cơ tay."] },
    { word: "detergent", phonetic: "/dɪˈtɜːrdʒənt/", def: "A water-soluble cleansing agent which combines with impurities and dirt to make them more soluble.", defVn: "bột giặt, nước giặt tẩy", pos: "noun", ex: ["Add liquid laundry detergent to the washing machine dispenser.", "Eco-friendly detergents are safe for sensitive skin."], exVn: ["Đổ nước giặt vào ngăn chứa của máy giặt.", "Chất tẩy rửa thân thiện với môi trường rất an toàn cho da nhạy cảm."] },
    { word: "iron", phonetic: "/ˈaɪərn/", def: "A handheld appliance with a flat heated bottom surface, used for smoothing clothes.", defVn: "bàn là, bàn ủi quần áo", pos: "noun", ex: ["Iron your cotton shirt to remove wrinkles before the interview.", "Be careful not to touch the hot soleplate of the iron."], exVn: ["Ủi chiếc áo sơ mi cotton để phẳng phiu nếp nhăn trước buổi phỏng vấn.", "Cẩn thận kẻo chạm vào mặt đế nóng của bàn là nhé."] },
    { word: "ironing board", phonetic: "/ˈaɪərnɪŋ bɔːrd/", def: "A long, narrow padded board, often with collapsible legs, on which clothes are ironed.", defVn: "cầu là, bàn để ủi quần áo", pos: "noun", ex: ["Set up the adjustable ironing board in the laundry room.", "Fold up the ironing board when finished."], exVn: ["Dựng chiếc cầu là có thể điều chỉnh độ cao trong phòng giặt.", "Gấp gọn bàn ủi lại khi đã ủi đồ xong."] },
    { word: "laundry", phonetic: "/ˈlɔːndri/", def: "Clothes and linens that need to be washed or that have been newly washed.", defVn: "quần áo cần giặt, việc giặt giũ", pos: "noun", ex: ["Sort white and colored clothes before doing the laundry.", "Hang the clean laundry in the warm sunshine to dry."], exVn: ["Phân loại quần áo trắng và quần áo màu trước khi giặt giũ.", "Phơi quần áo sạch dưới ánh nắng ấm áp cho mau khô."] },
    { word: "sweep", phonetic: "/swiːp/", def: "Clean an area by brushing away dirt or litter with a broom.", defVn: "quét dọn (nhà cửa, sân vườn)", pos: "verb", ex: ["Sweep the kitchen floor after cooking every meal.", "She swept fallen autumn leaves from the courtyard."], exVn: ["Quét sàn nhà bếp sau khi nấu ăn xong mỗi bữa.", "Cô ấy quét sạch lá thu rụng trên sân nhà."] },
    { word: "wipe", phonetic: "/waɪp/", def: "Clean or dry something by rubbing its surface with a cloth or one's hand.", defVn: "lau chùi, lau khô bề mặt", pos: "verb", ex: ["Wipe the dining table with a damp cloth after dinner.", "Wipe your glasses with a microfiber cloth."], exVn: ["Lau bàn ăn bằng khăn ẩm sau bữa tối.", "Lau mắt kính bằng khăn lau chuyên dụng mềm nhé."] },
    { word: "scrub", phonetic: "/skrʌb/", def: "Rub someone or something hard so as to clean them, typically with a brush and water.", defVn: "cọ rửa, chà xát thật sạch", pos: "verb", ex: ["Scrub the bathroom floor tiles until they sparkle.", "Scrub stubborn stains with a stiff brush."], exVn: ["Cọ rửa gạch sàn phòng tắm cho đến khi sáng bóng.", "Chà những vết bẩn cứng đầu bằng bàn chải cứng."] },
    { word: "wash", phonetic: "/wɑːʃ/", def: "Clean with water and, typically, soap or detergent.", defVn: "rửa sạch, giặt sạch", pos: "verb", ex: ["Always wash your hands thoroughly with soap for twenty seconds.", "Wash the dishes right after eating."], exVn: ["Luôn rửa tay thật kỹ bằng xà phòng trong 20 giây.", "Rửa sạch bát đĩa ngay sau khi ăn xong nhé."] },
    { word: "dry", phonetic: "/draɪ/", def: "Free from moisture or liquid; not wet or moist.", defVn: "phơi khô, lau khô, sấy khô", pos: "verb", ex: ["Dry your wet hair with a soft towel after showering.", "The sun dried the washed clothes in two hours."], exVn: ["Lau khô mái tóc ướt bằng khăn mềm sau khi tắm.", "Ánh mặt trời làm khô quần áo đã giặt chỉ trong hai tiếng."] }
  ],

  // Theme 41: Phụ kiện thời trang (Fashion Accessories)
  t_basic_fashion_accessories: [
    { word: "necklace", phonetic: "/ˈnekləs/", def: "An ornamental chain or string of beads, jewels, or links worn round the neck.", defVn: "dây chuyền, vòng cổ", pos: "noun", ex: ["She wore a delicate silver necklace with a pearl pendant.", "A gold necklace makes an elegant birthday gift."], exVn: ["Cô ấy đeo sợi dây chuyền bạc thanh mảnh có mặt ngọc trai.", "Sợi dây chuyền vàng là món quà sinh nhật vô cùng sang trọng."] },
    { word: "bracelet", phonetic: "/ˈbreɪslət/", def: "An ornamental band, hoop, or chain worn on the wrist or arm.", defVn: "vòng tay, lắc tay xinh xắn", pos: "noun", ex: ["She received a handcrafted silver charm bracelet for graduation.", "Traditional jade bracelets are cherished heirlooms."], exVn: ["Cô ấy nhận được chiếc lắc tay bạc thủ công nhân dịp tốt nghiệp.", "Những chiếc vòng ngọc bích truyền thống là bảo vật gia truyền quý giá."] },
    { word: "ring", phonetic: "/rɪŋ/", def: "A small circular band, typically of precious metal and often set with one or more gemstones.", defVn: "chiếc nhẫn đeo tay", pos: "noun", ex: ["He slipped a sparkling diamond engagement ring on her finger.", "She wears a simple gold band ring on her right hand."], exVn: ["Anh ấy đeo chiếc nhẫn đính hôn kim cương lấp lánh vào tay cô.", "Cô ấy đeo chiếc nhẫn vàng trơn giản dị trên tay phải."] },
    { word: "earring", phonetic: "/ˈɪr-rɪŋ/", def: "A piece of jewelry worn on the lobe or edge of the ear.", defVn: "hoa tai, bông tai, khuyên tai", pos: "noun", ex: ["Pearl earrings add timeless sophistication to an evening gown.", "She bought minimalist hoop earrings."], exVn: ["Đôi bông tai ngọc trai mang lại nét quý phái vượt thời gian cho dạ phục.", "Cô ấy đã mua đôi khuyên tai tròn tối giản."] },
    { word: "watch", phonetic: "/wɑːtʃ/", def: "A small timepiece worn on the wrist or carried in a pocket.", defVn: "đồng hồ đeo tay", pos: "noun", ex: ["He checked his leather-strap wristwatch to ensure he was on time.", "A smartwatch tracks your daily steps and heart rate."], exVn: ["Anh ấy nhìn đồng hồ đeo tay dây da để đảm bảo mình đến đúng giờ.", "Đồng hồ thông minh theo dõi bước chân và nhịp tim hàng ngày."] },
    { word: "sunglasses", phonetic: "/ˈsʌnɡlæsɪz/", def: "Glasses with tinted lenses to protect the eyes from sunlight or glare.", defVn: "kính râm, kính mát chống nắng", pos: "noun", ex: ["Wear UV-blocking sunglasses on sunny beach vacations.", "Stylish sunglasses protect your eyes from bright glare."], exVn: ["Hãy đeo kính râm chống tia UV trong các kỳ nghỉ bãi biển nhiều nắng.", "Kính mát sành điệu bảo vệ mắt bạn khỏi ánh nắng chói chang."] },
    { word: "handbag", phonetic: "/ˈhændbæɡ/", def: "A woman's bag used to carry everyday personal items; purse.", defVn: "túi xách tay nữ", pos: "noun", ex: ["She carries her wallet, keys, and phone in her leather handbag.", "The brown leather handbag matched her classic coat."], exVn: ["Cô ấy để ví tiền, chìa khóa và điện thoại trong chiếc túi xách da.", "Chiếc túi xách da màu nâu rất hợp với áo khoác cổ điển của cô."] },
    { word: "umbrella", phonetic: "/ʌmˈbrelə/", def: "A circular canopy of cloth on a folding metal frame supported by a central rod.", defVn: "chiếc ô, chiếc dù che mưa/nắng", pos: "noun", ex: ["Always keep a compact folding umbrella in your backpack.", "Open your umbrella when the rain shower starts."], exVn: ["Luôn giữ chiếc ô gập nhỏ gọn trong ba lô của bạn nhé.", "Hãy mở ô ra khi cơn mưa rào bắt đầu đổ xuống."] },
    { word: "hat", phonetic: "/hæt/", def: "A shaped covering for the head worn for warmth, as a fashion item, or as part of a uniform.", defVn: "chiếc nón, chiếc mũ rộng vành", pos: "noun", ex: ["The traditional Vietnamese conical leaf hat is iconic.", "Wear a wide-brimmed sun hat to protect your face."], exVn: ["Chiếc nón lá truyền thống của Việt Nam là biểu tượng văn hóa.", "Đội chiếc mũ rộng vành để che nắng cho khuôn mặt nhé."] },
    { word: "cap", phonetic: "/kæp/", def: "A kind of soft, flat hat, typically with a visor.", defVn: "mũ lưỡi trai, nón kết", pos: "noun", ex: ["He pulled his baseball cap down to shield his eyes from the sun.", "A black sports cap looks casual and youthful."], exVn: ["Cậu ấy kéo mũ lưỡi trai xuống để che bớt ánh nắng chiếu vào mắt.", "Chiếc mũ thể thao màu đen trông rất năng động và trẻ trung."] },
    { word: "scarf", phonetic: "/skɑːrf/", def: "A length of fabric worn around the neck or head for warmth or decoration.", defVn: "khăn choàng cổ, khăn lụa", pos: "noun", ex: ["Wrap this warm cashmere scarf around your neck in winter.", "A vibrant silk scarf brightens up a neutral outfit."], exVn: ["Quàng chiếc khăn cashmere ấm này quanh cổ trong mùa đông.", "Chiếc khăn lụa rực rỡ làm nổi bật bộ trang phục màu trung tính."] },
    { word: "belt", phonetic: "/belt/", def: "A strip of leather or other material worn around the waist to support clothes.", defVn: "thắt lưng, dây nịt", pos: "noun", ex: ["Fasten your classic leather belt securely around your waist.", "A matching leather belt completes a smart business suit."], exVn: ["Thắt chiếc dây nịt da cổ điển vừa vặn quanh eo nhé.", "Chiếc thắt lưng da đồng điệu hoàn thiện bộ âu phục công sở lịch lãm."] },
    { word: "gloves", phonetic: "/ɡlʌvz/", def: "A covering for the hand made with a separate sheath for each finger and thumb.", defVn: "đôi găng tay, bao tay giữ ấm", pos: "noun", ex: ["Wear insulated leather gloves when riding in chilly winter weather.", "She put on warm woolen gloves."], exVn: ["Đeo găng tay da lót ấm khi lái xe trong thời tiết đông giá lạnh.", "Cô ấy đeo đôi bao tay len ấm áp."] },
    { word: "tie", phonetic: "/taɪ/", def: "A long piece of cloth tied around the neck under a collar.", defVn: "cà vạt nam trang trọng", pos: "noun", ex: ["He tied a formal Windsor knot on his navy blue silk tie.", "A silk necktie adds polish to a dress shirt."], exVn: ["Anh ấy thắt nút Windsor trang trọng trên chiếc cà vạt lụa xanh thẫm.", "Cà vạt lụa tạo nên vẻ lịch thiệp cho chiếc áo sơ mi."] },
    { word: "perfume", phonetic: "/ˈpɜːrfjuːm/", def: "A fragrant liquid typically made from essential oils, used to impart a pleasant scent to one's body.", defVn: "nước hoa cao cấp, dầu thơm", pos: "noun", ex: ["A gentle spray of floral perfume leaves a lovely, subtle scent.", "She loves fresh citrus and lavender perfume."], exVn: ["Một làn xịt nước hoa hương hoa nhẹ nhàng để lại mùi thơm tinh tế.", "Cô ấy rất thích nước hoa hương cam chanh và hoa oải hương."] }
  ],

  // Theme 42: Phòng ngủ & Giấc ngủ (Bedroom & Sleep)
  t_basic_bedroom_sleep: [
    { word: "bed", phonetic: "/bed/", def: "A piece of furniture for sleep or rest, typically consisting of a mattress on a frame.", defVn: "chiếc giường ngủ êm ái", pos: "noun", ex: ["A comfortable king-size bed ensures restful night sleep.", "Make your bed neatly every morning after waking up."], exVn: ["Chiếc giường lớn êm ái đảm bảo giấc ngủ ngon trọn vẹn cả đêm.", "Hãy gấp chăn gối dọn giường ngăn nắp mỗi sáng sau khi thức dậy."] },
    { word: "mattress", phonetic: "/ˈmætrəs/", def: "A fabric case filled with deformable or resilient material, used for sleeping on.", defVn: "nệm ngủ, đệm lò xo", pos: "noun", ex: ["A supportive orthopedic mattress relieves back stiffness.", "We bought an eco-friendly natural latex mattress."], exVn: ["Chiếc nệm nâng đỡ cơ thể tốt giúp giảm đau mỏi lưng.", "Chúng tôi đã mua chiếc nệm cao su thiên nhiên thân thiện môi trường."] },
    { word: "pillow", phonetic: "/ˈpɪloʊ/", def: "A rectangular cloth bag filled with soft material, used to support the head when lying or sleeping.", defVn: "cái gối đầu", pos: "noun", ex: ["Rest your head on a soft feather pillow for deep sleep.", "She fluffed her pillow before closing her eyes."], exVn: ["Tựa đầu lên chiếc gối lông vũ êm ái để chìm vào giấc ngủ sâu.", "Cô ấy vỗ nhẹ chiếc gối đầu trước khi nhắm mắt ngủ."] },
    { word: "blanket", phonetic: "/ˈblæŋkɪt/", def: "A large piece of woolen or other fabric used as a warm covering on a bed.", defVn: "chiếc chăn ấm, mền ngủ", pos: "noun", ex: ["Snuggle under a warm fleece blanket on chilly winter nights.", "Fold the extra blanket at the foot of the bed."], exVn: ["Cuộn mình dưới chiếc chăn nỉ ấm áp trong những đêm đông se lạnh.", "Gấp chiếc chăn phụ gọn gàng ở phía cuối giường."] },
    { word: "quilt", phonetic: "/kwɪlt/", def: "A warm bed covering made of padding enclosed between layers of fabric and kept in place by lines of stitching.", defVn: "chăn bông trần bông dày", pos: "noun", ex: ["The thick down quilt keeps you cozy even in sub-zero weather.", "A handmade patchwork quilt covered the vintage bed."], exVn: ["Chiếc chăn bông lông vũ dày giữ bạn luôn ấm cúng trong thời tiết giá rét.", "Chiếc chăn trần bông ghép vải thủ công phủ trên chiếc giường cổ."] },
    { word: "sheet", phonetic: "/ʃiːt/", def: "A large piece of cotton or other fabric, used on a bed to lie on or under.", defVn: "ga trải giường, drap giường", pos: "noun", ex: ["Change bed sheets weekly to maintain optimal cleanliness.", "Crisp 100% cotton bed sheets feel cooling and fresh."], exVn: ["Thay ga trải giường hàng tuần để giữ gìn vệ sinh sạch sẽ tối đa.", "Ga giường 100% cotton tạo cảm giác mát mẻ và thoáng đãng."] },
    { word: "alarm clock", phonetic: "/əˈlɑːrm klɑːk/", def: "A clock that can be set to sound an alarm at a desired time, used to wake someone up.", defVn: "đồng hồ báo thức", pos: "noun", ex: ["Set your alarm clock for 6:00 AM to catch the early flight.", "The gentle chime of the alarm clock woke me up on time."], exVn: ["Đặt đồng hồ báo thức lúc 6 giờ sáng để kịp chuyến bay sớm.", "Tiếng chuông nhẹ nhàng của đồng hồ báo thức đánh thức tôi đúng giờ."] },
    { word: "nightstand", phonetic: "/ˈnaɪtstænd/", def: "A small bedside table, typically having drawers.", defVn: "tủ đầu giường, bàn cạnh giường", pos: "noun", ex: ["Keep a glass of water and your reading glasses on the nightstand.", "A bedside lamp sits on the wooden nightstand."], exVn: ["Để một ly nước và kính đọc sách trên chiếc tủ đầu giường nhé.", "Chiếc đèn ngủ đặt trên chiếc bàn cạnh giường bằng gỗ."] },
    { word: "lamp", phonetic: "/læmp/", def: "A device for giving light, especially one consisting of an electric bulb and shade.", defVn: "đèn ngủ, đèn đọc sách", pos: "noun", ex: ["Turn on the warm amber bedside lamp for evening reading.", "Dim the lamp light before drifting off to sleep."], exVn: ["Bật chiếc đèn ngủ ánh vàng ấm áp để đọc sách buổi tối.", "Giảm độ sáng của đèn trước khi chìm vào giấc ngủ."] },
    { word: "pajamas", phonetic: "/pəˈdʒɑːməz/", def: "A suit of loose trousers and jacket or shirt for sleeping in.", defVn: "bộ quần áo ngủ thoải mái", pos: "noun", ex: ["Change into breathable cotton pajamas after a warm bath.", "She wore cozy flannel pajamas on cold nights."], exVn: ["Thay bộ đồ ngủ cotton thoáng mát sau khi tắm nước ấm.", "Cô ấy mặc bộ quần áo ngủ vải nỉ ấm áp trong những đêm đông."] },
    { word: "sleep", phonetic: "/sliːp/", def: "A condition of body and mind that typically recurs for several hours every night.", defVn: "ngủ, giấc ngủ sâu", pos: "verb", ex: ["Getting eight hours of quality sleep nightly restores energy.", "Sleep peacefully and wake up refreshed."], exVn: ["Ngủ đủ tám tiếng chất lượng mỗi đêm giúp phục hồi năng lượng.", "Chúc bạn ngủ ngon và thức dậy tràn đầy sảng khoái."] },
    { word: "dream", phonetic: "/driːm/", def: "A series of thoughts, images, and sensations occurring in a person's mind during sleep.", defVn: "giấc mơ, mơ màng", pos: "noun", ex: ["I had a vivid, wonderful dream about flying over the ocean.", "Sweet dreams to you and your family!"], exVn: ["Tôi đã có một giấc mơ tuyệt đẹp về việc bay lượn trên đại dương.", "Chúc bạn và gia đình có những giấc mơ thật ngọt ngào!"] },
    { word: "wake up", phonetic: "/weɪk ʌp/", def: "Emerge or cause to emerge from sleep.", defVn: "thức dậy, tỉnh giấc", pos: "verb", ex: ["I wake up naturally at sunrise feeling rejuvenated.", "Wake up early to enjoy peaceful morning meditation."], exVn: ["Tôi tự thức dậy lúc bình minh với cảm giác sảng khoái.", "Thức dậy sớm để tận hưởng buổi thiền sáng an yên."] },
    { word: "snore", phonetic: "/snɔːr/", def: "Breathe with a snorting or grunting sound while asleep.", defVn: "ngáy khi ngủ", pos: "verb", ex: ["Sleeping on your side often prevents loud snoring.", "The tired puppy snored gently on the rug."], exVn: ["Nằm nghiêng khi ngủ thường giúp tránh ngáy to.", "Chú cún mệt mỏi ngáy nhè nhẹ trên tấm thảm."] },
    { word: "nap", phonetic: "/næp/", def: "A short sleep, especially during the day.", defVn: "giấc ngủ trưa ngắn", pos: "noun", ex: ["A 20-minute afternoon power nap boosts mental clarity.", "Take a quick nap to recharge your battery."], exVn: ["Một giấc ngủ trưa 20 phút giúp tăng cường sự tỉnh táo của trí óc.", "Hãy chợp mắt một chút để nạp lại năng lượng nhé."] }
  ],

  // Theme 43: Phòng tắm & Vệ sinh (Bathroom & Toiletries)
  t_basic_bathroom_toiletries: [
    { word: "shower", phonetic: "/ˈʃaʊər/", def: "An apparatus which produces a spray of water for washing oneself.", defVn: "vòi hoa sen, tắm vòi sen", pos: "noun", ex: ["A hot shower after a workout relaxes tense muscles.", "Take a refreshing morning shower to wake up."], exVn: ["Tắm vòi sen nước nóng sau khi tập thể dục giúp thư giãn cơ bắp.", "Tắm vòi sen sảng khoái buổi sáng giúp tỉnh táo tinh thần."] },
    { word: "bathtub", phonetic: "/ˈbæθtʌb/", def: "A tub, usually installed in a bathroom, in which to bathe.", defVn: "bồn tắm nằm thư giãn", pos: "noun", ex: ["Soak in a warm bubble bathtub scented with lavender essential oil.", "The hotel bathroom features a marble bathtub."], exVn: ["Ngâm mình trong bồn tắm bọt nước ấm ngát hương tinh dầu oải hương.", "Phòng tắm khách sạn có bồn tắm bằng đá cẩm thạch."] },
    { word: "sink", phonetic: "/sɪŋk/", def: "A fixed basin with a water supply and drain, used for washing hands and face.", defVn: "bồn rửa mặt, chậu rửa", pos: "noun", ex: ["Wash your hands with antibacterial soap at the bathroom sink.", "Wipe the ceramic sink clean after brushing teeth."], exVn: ["Rửa tay bằng xà phòng diệt khuẩn tại bồn rửa mặt phòng tắm.", "Lau sạch bồn rửa bằng sứ sau khi đánh răng nhé."] },
    { word: "toilet", phonetic: "/ˈtɔɪlət/", def: "A fixed receptacle consisting of a bowl and seat, used for urination and defecation.", defVn: "bồn cầu vệ sinh", pos: "noun", ex: ["Flush the toilet after every use and keep the lid down.", "The modern restroom has automated smart toilets."], exVn: ["Xả nước bồn cầu sau mỗi lần sử dụng và đậy nắp lại.", "Nhà vệ sinh hiện đại có bồn cầu thông minh tự động."] },
    { word: "towel", phonetic: "/ˈtaʊəl/", def: "A piece of thick absorbent cloth or paper used for drying oneself.", defVn: "khăn tắm, khăn lau", pos: "noun", ex: ["Dry your skin gently with a plush, fluffy cotton bath towel.", "Hang your wet towel on the bathroom rack to dry."], exVn: ["Lau khô da nhẹ nhàng bằng chiếc khăn tắm cotton mềm mại.", "Treo khăn ướt lên giá phòng tắm cho mau khô."] },
    { word: "shampoo", phonetic: "/ʃæmˈpuː/", def: "A liquid preparation containing soap or other detergent for washing the hair.", defVn: "dầu gội đầu", pos: "noun", ex: ["Use natural herbal shampoo with locust fruit for shiny, healthy hair.", "Lather the fragrant shampoo gently into your scalp."], exVn: ["Dùng dầu gội thảo mộc bồ kết thiên nhiên cho mái tóc bóng khỏe.", "Tạo bọt dầu gội thơm và mát-xa nhẹ nhàng da đầu."] },
    { word: "conditioner", phonetic: "/kənˈdɪʃənər/", def: "A fluid application that improves the condition of the hair by making it smooth and shiny.", defVn: "dầu xả dưỡng tóc", pos: "noun", ex: ["Apply hair conditioner to the ends of your hair after shampooing.", "Leave the conditioner on for three minutes before rinsing."], exVn: ["Thoa dầu xả vào phần ngọn tóc sau khi gội đầu xong.", "Ủ dầu xả trong ba phút trước khi xả sạch lại bằng nước."] },
    { word: "soap", phonetic: "/soʊp/", def: "A substance used with water for washing and cleaning, made of natural oils or fats.", defVn: "bánh xà phòng, xà bông", pos: "noun", ex: ["Lather organic olive oil soap between your hands.", "Wash with soap and water to eliminate germs."], exVn: ["Tạo bọt bánh xà phòng dầu ô-liu hữu cơ giữa hai lòng bàn tay.", "Rửa bằng xà phòng và nước để tiêu diệt vi khuẩn."] },
    { word: "body wash", phonetic: "/ˈbɑːdi wɑːʃ/", def: "A liquid product used for cleansing the body during showers.", defVn: "sữa tắm hương thơm", pos: "noun", ex: ["A moisturizing body wash keeps your skin soft and fragrant.", "Pour scented body wash onto your bath sponge."], exVn: ["Sữa tắm dưỡng ẩm giữ cho làn da luôn mịn màng và thơm mát.", "Đổ sữa tắm thơm lên miếng bọt biển tắm."] },
    { word: "toothpaste", phonetic: "/ˈtuːθpeɪst/", def: "A paste used with a toothbrush to clean and maintain the aesthetics and health of teeth.", defVn: "kem đánh răng", pos: "noun", ex: ["Squeeze a pea-sized amount of fluoride toothpaste onto your brush.", "Mint toothpaste leaves your breath fresh."], exVn: ["Bóp một lượng kem đánh răng bằng hạt đậu lên bàn chải.", "Kem đánh răng vị bạc hà mang lại hơi thở thơm tho."] },
    { word: "toothbrush", phonetic: "/ˈtuːθbrʌʃ/", def: "A small brush with a long handle, used for cleaning the teeth.", defVn: "bàn chải đánh răng", pos: "noun", ex: ["Replace your toothbrush every three months for optimal oral hygiene.", "An electric toothbrush cleans teeth effectively."], exVn: ["Thay bàn chải đánh răng ba tháng một lần để giữ vệ sinh răng miệng tối ưu.", "Bàn chải đánh răng điện làm sạch răng rất hiệu quả."] },
    { word: "razor", phonetic: "/ˈreɪzər/", def: "An instrument with a sharp blade or combination of blades, used to remove unwanted body hair.", defVn: "dao cạo râu", pos: "noun", ex: ["Apply rich shaving cream before using a clean, sharp razor.", "Store your safety razor in a dry place."], exVn: ["Thoa bọt cạo râu trước khi dùng dao cạo râu sạch sắc bén.", "Bảo quản dao cạo râu ở nơi khô ráo nhé."] },
    { word: "comb", phonetic: "/koʊm/", def: "A strip of plastic, metal, or wood with a row of narrow teeth, used for untangling or arranging hair.", defVn: "chiếc lược chải đầu", pos: "noun", ex: ["Use a wide-tooth wooden comb to untangle wet hair gently.", "She combed her long black hair before leaving."], exVn: ["Dùng lược gỗ răng thưa để chải mượt tóc ướt nhẹ nhàng.", "Cô ấy chải mái tóc đen dài trước khi ra ngoài."] },
    { word: "mirror", phonetic: "/ˈmɪrər/", def: "A reflective surface, now typically of glass coated with a metal amalgam.", defVn: "chiếc gương soi phòng tắm", pos: "noun", ex: ["Wipe the steam off the bathroom mirror after a hot shower.", "Look in the mirror to check your hairstyle."], exVn: ["Lau hơi nước bám trên gương phòng tắm sau khi tắm nước nóng.", "Soi gương để kiểm tra lại kiểu tóc của bạn nhé."] },
    { word: "toilet paper", phonetic: "/ˈtɔɪlət ˈpeɪpər/", def: "Paper on a roll, used for personal hygiene after using the toilet.", defVn: "giấy vệ sinh cuộn", pos: "noun", ex: ["Always keep extra rolls of soft toilet paper in the bathroom cabinet.", "Restock the toilet paper holder."], exVn: ["Luôn dự trữ những cuộn giấy vệ sinh mềm trong tủ phòng tắm.", "Nạp thêm giấy vệ sinh vào hộp đựng nhé."] }
  ],

  // Theme 44: Cảm giác cơ thể (Bodily Sensations)
  t_basic_bodily_sensations: [
    { word: "pain", phonetic: "/peɪn/", def: "Physical suffering or discomfort caused by illness or injury.", defVn: "cơn đau, cảm giác đau đớn", pos: "noun", ex: ["Apply an ice pack to reduce swelling and soothe joint pain.", "The doctor asked him where the pain was located."], exVn: ["Chườm túi đá để giảm sưng và xoa dịu cơn đau khớp.", "Bác sĩ đã hỏi anh ấy vị trí cơn đau nằm ở đâu."] },
    { word: "ache", phonetic: "/eɪk/", def: "A continuous or prolonged dull pain in a part of one's body.", defVn: "cảm giác đau nhức âm ỉ", pos: "noun", ex: ["His leg muscles ache after running a 10-kilometer race.", "Drinking warm milk helps ease stomach aches."], exVn: ["Cơ bắp chân của anh ấy đau nhức sau khi chạy cuộc đua 10 km.", "Uống sữa ấm giúp xoa dịu những cơn đau nhức dạ dày."] },
    { word: "itchy", phonetic: "/ˈɪtʃi/", def: "Experiencing an irritating sensation on the skin that causes a desire to scratch.", defVn: "ngứa ngáy, râm ran khó chịu", pos: "adj", ex: ["The mosquito bite on my arm is very red and itchy.", "Apply soothing aloe vera gel on itchy skin."], exVn: ["Vết muỗi đốt trên cánh tay tôi rất đỏ và ngứa ngáy.", "Bôi gel nha đam làm dịu lên vùng da bị ngứa."] },
    { word: "dizzy", phonetic: "/ˈdɪzi/", def: "Having a sensation of spinning around and losing one's balance.", defVn: "chóng mặt, hoa mắt, choáng váng", pos: "adj", ex: ["Sit down and sip water if you feel dizzy in the hot sun.", "Sudden standing can sometimes make you feel dizzy."], exVn: ["Hãy ngồi xuống và uống từng ngụm nước nếu bạn thấy chóng mặt dưới nắng gắt.", "Đột ngột đứng dậy đôi khi có thể khiến bạn bị choáng váng."] },
    { word: "sweat", phonetic: "/swet/", def: "Moisture exuded through the pores of the skin, typically in profuse drops as a reaction to heat or physical exertion.", defVn: "mồ hôi cơ thể", pos: "noun", ex: ["Wipe the sweat from your forehead after a high-intensity workout.", "Sweating is the body's natural cooling mechanism."], exVn: ["Lau mồ hôi trên trán sau buổi tập luyện cường độ cao.", "Toát mồ hôi là cơ chế làm mát tự nhiên của cơ thể."] },
    { word: "shiver", phonetic: "/ˈʃɪvər/", def: "Shake slightly and uncontrollably as a result of being cold, frightened, or excited.", defVn: "run rẩy vì lạnh, rùng mình", pos: "verb", ex: ["He started to shiver in the freezing winter wind without a coat.", "Wrap yourself in a warm blanket if you shiver."], exVn: ["Anh ấy bắt đầu run rẩy trong cơn gió đông giá rét khi không mặc áo khoác.", "Hãy quấn chiếc chăn ấm nếu bạn bị run lạnh."] },
    { word: "thirsty", phonetic: "/ˈθɜːrsti/", def: "Feeling a need to drink.", defVn: "khát nước, háo nước", pos: "adj", ex: ["Drink clean fresh water whenever you feel thirsty.", "I was very thirsty after cycling around the lake."], exVn: ["Hãy uống nước sạch bất cứ khi nào bạn cảm thấy khát nước.", "Tôi rất khát nước sau khi đạp xe một vòng quanh hồ."] },
    { word: "hungry", phonetic: "/ˈhʌŋɡri/", def: "Feeling or displaying the need for food.", defVn: "đói bụng, thèm ăn", pos: "adj", ex: ["My stomach rumbles when I am hungry before lunchtime.", "Eat a nutritious snack if you feel hungry while studying."], exVn: ["Bụng tôi kêu cồn cào khi tôi đói trước giờ ăn trưa.", "Hãy ăn một món ăn nhẹ bổ dưỡng nếu bạn thấy đói khi học bài."] },
    { word: "full", phonetic: "/fʊl/", def: "Having eaten to one's satisfaction; satiated.", defVn: "no bụng, no nê", pos: "adj", ex: ["I am completely full after that delicious three-course Vietnamese meal.", "No more for me, thank you, I am full."], exVn: ["Tôi đã hoàn toàn no nê sau bữa ăn ba món Việt Nam thơm ngon.", "Tôi không ăn thêm được nữa đâu, cảm ơn bạn, tôi no rồi."] },
    { word: "tired", phonetic: "/ˈtaɪərd/", def: "In need of sleep or rest; weary.", defVn: "mệt mỏi, uể oải", pos: "adj", ex: ["Take a refreshing rest if you feel tired after hard work.", "She felt tired but proud after finishing the marathon."], exVn: ["Hãy nghỉ ngơi thư giãn nếu bạn cảm thấy mệt mỏi sau giờ làm việc chăm chỉ.", "Cô ấy cảm thấy mệt nhưng rất tự hào sau khi hoàn thành cuộc đua marathon."] },
    { word: "sleepy", phonetic: "/ˈsliːpi/", def: "Needing or ready for sleep.", defVn: "buồn ngủ, ngái ngủ", pos: "adj", ex: ["Drinking warm chamomile tea makes you feel naturally sleepy.", "The sleepy toddler rubbed his eyes gently."], exVn: ["Uống trà hoa cúc ấm giúp bạn cảm thấy buồn ngủ tự nhiên.", "Đứa bé ngái ngủ dụi nhẹ đôi mắt."] },
    { word: "numb", phonetic: "/nʌm/", def: "Deprived of the power of physical sensation, typically as a result of cold or anesthesia.", defVn: "tê cóng, tê buốt, tê dại", pos: "adj", ex: ["My fingers were numb with freezing cold after building a snowman.", "The dentist numbed the gum before the procedure."], exVn: ["Những ngón tay tôi bị tê cóng vì lạnh sau khi nặn người tuyết.", "Nha sĩ đã gây tê lợi trước khi làm thủ thuật."] },
    { word: "faint", phonetic: "/feɪnt/", def: "Lose consciousness for a short time because of a temporarily insufficient supply of oxygen to the brain.", defVn: "ngất xỉu, ngất đi tạm thời", pos: "verb", ex: ["Lie flat and elevate your legs if you feel about to faint.", "She fainted from dehydration in the extreme heat."], exVn: ["Hãy nằm thẳng và kê cao chân nếu bạn cảm thấy sắp ngất xỉu.", "Cô ấy đã bị ngất đi vì mất nước dưới trời nắng gắt."] },
    { word: "cramp", phonetic: "/kræmp/", def: "A painful, involuntary contraction of a muscle or muscles, typically caused by fatigue or strain.", defVn: "chuột rút cơ bắp", pos: "noun", ex: ["Stretch and hydrate to prevent painful leg cramps while swimming.", "He stopped running due to a calf cramp."], exVn: ["Hãy kéo giãn cơ và uống đủ nước để tránh bị chuột rút bắp chân khi bơi.", "Anh ấy đã dừng chạy do bị chuột rút bắp chân."] },
    { word: "swelling", phonetic: "/ˈswelɪŋ/", def: "An abnormal enlargement of a part of the body, typically as a result of an accumulation of fluid.", defVn: "chỗ sưng tấy, sưng phù", pos: "noun", ex: ["Apply an ice compress to reduce the ankle swelling quickly.", "The swelling went down after two days of rest."], exVn: ["Chườm đá lạnh để giảm sưng mắt cá chân nhanh chóng.", "Vết sưng đã xẹp xuống sau hai ngày nghỉ ngơi."] }
  ],

  // Theme 45: Cảm xúc & Thái độ sống (Feelings & Attitudes)
  t_basic_feelings_attitudes: [
    { word: "joy", phonetic: "/dʒɔɪ/", def: "A feeling of great pleasure and happiness.", defVn: "niềm vui sướng hân hoan", pos: "noun", ex: ["The children's joyful laughter brought immense joy to the household.", "Find joy in everyday simple moments."], exVn: ["Tiếng cười tươi vui của lũ trẻ mang lại niềm vui sướng khôn xiết cho cả nhà.", "Hãy tìm thấy niềm vui trong những khoảnh khắc bình dị mỗi ngày."] },
    { word: "hope", phonetic: "/hoʊp/", def: "A feeling of expectation and desire for a certain thing to happen.", defVn: "hy vọng, niềm tin tươi sáng", pos: "noun", ex: ["Never lose hope, for tomorrow brings new bright opportunities.", "She radiates positive hope and optimism."], exVn: ["Đừng bao giờ đánh mất hy vọng, vì ngày mai sẽ mang đến những cơ hội tươi sáng mới.", "Cô ấy luôn tỏa ra niềm hy vọng và sự lạc quan tích cực."] },
    { word: "courage", phonetic: "/ˈkɜːrɪdʒ/", def: "The ability to do something that frightens one; bravery.", defVn: "sự can đảm, lòng dũng cảm", pos: "noun", ex: ["It takes courage to speak English in front of an international audience.", "She showed great courage during difficult times."], exVn: ["Cần có lòng can đảm để nói tiếng Anh trước khán giả quốc tế.", "Cô ấy đã thể hiện lòng dũng cảm tuyệt vời trong những lúc khó khăn."] },
    { word: "peace", phonetic: "/piːs/", def: "Freedom from disturbance; tranquility.", defVn: "sự bình yên, an lạc trong tâm hồn", pos: "noun", ex: ["Meditation by the peaceful lake brings inner peace and mental calm.", "We wish for harmony and global peace."], exVn: ["Thiền định bên bờ hồ thanh bình mang lại sự an lạc nội tâm và bình yên tinh thần.", "Chúng tôi cầu chúc sự hòa thuận và nền hòa bình toàn cầu."] },
    { word: "trust", phonetic: "/trʌst/", def: "Firm belief in the reliability, truth, ability, or strength of someone or something.", defVn: "lòng tin cậy, sự tin tưởng", pos: "noun", ex: ["True friendship is built on mutual trust and honesty.", "Trust yourself; you are capable of achieving great things."], exVn: ["Tình bạn đích thực được xây dựng trên sự tin tưởng lẫn nhau và lòng trung thực.", "Hãy tin tưởng vào chính mình; bạn có khả năng đạt được những điều tuyệt vời."] },
    { word: "respect", phonetic: "/rɪˈspekt/", def: "A feeling of deep admiration for someone or something elicited by their abilities or achievements.", defVn: "sự tôn trọng, lòng kính trọng", pos: "noun", ex: ["Always treat your teachers, elders, and peers with genuine respect.", "Mutual respect is vital in every relationship."], exVn: ["Hãy luôn đối xử với thầy cô, người lớn tuổi và bạn bè bằng sự tôn trọng chân thành.", "Sự tôn trọng lẫn nhau là yếu tố sống còn trong mọi mối quan hệ."] },
    { word: "gratitude", phonetic: "/ˈɡrætɪtuːd/", def: "The quality of being thankful; readiness to show appreciation.", defVn: "lòng biết ơn, sự cảm kích sâu sắc", pos: "noun", ex: ["Practicing daily gratitude makes you happier and more grounded.", "She expressed heartfelt gratitude to her supporters."], exVn: ["Thực hành lòng biết ơn mỗi ngày giúp bạn cảm thấy hạnh phúc và vững vàng hơn.", "Cô ấy đã bày tỏ lòng biết ơn chân thành đến những người ủng hộ mình."] },
    { word: "enthusiasm", phonetic: "/ɪnˈθuːziæzəm/", def: "Intense and eager enjoyment, interest, or approval.", defVn: "sự nhiệt huyết, lòng nhiệt tình", pos: "noun", ex: ["He tackled every new English learning challenge with boundless enthusiasm.", "Her enthusiasm inspired the entire team."], exVn: ["Anh ấy đón nhận mọi thử thách học tiếng Anh mới với lòng nhiệt huyết vô bờ.", "Sự nhiệt tình của cô ấy đã truyền cảm hứng cho cả nhóm."] },
    { word: "sympathy", phonetic: "/ˈsɪmpəθi/", def: "Feelings of pity and sorrow for someone else's misfortune.", defVn: "sự đồng cảm, lòng trắc ẩn", pos: "noun", ex: ["We sent flowers to express our deepest sympathy for their loss.", "A kind heart is always full of sympathy."], exVn: ["Chúng tôi đã gửi hoa để bày tỏ sự đồng cảm sâu sắc nhất trước mất mát của họ.", "Một trái tim nhân hậu luôn đong đầy lòng trắc ẩn."] },
    { word: "curiosity", phonetic: "/ˌkjʊriˈɑːsəti/", def: "A strong desire to know or learn something.", defVn: "tính tò mò, ham học hỏi khám phá", pos: "noun", ex: ["Intellectual curiosity is the engine of scientific discovery.", "Nurture children's natural curiosity about nature."], exVn: ["Tính tò mò tri thức là động cơ thúc đẩy mọi khám phá khoa học.", "Hãy nuôi dưỡng tính hiếu kỳ tự nhiên của trẻ nhỏ về thiên nhiên."] },
    { word: "pride", phonetic: "/praɪd/", def: "A feeling of deep pleasure or satisfaction derived from one's own achievements.", defVn: "niềm tự hào, lòng kiêu hãnh", pos: "noun", ex: ["Take healthy pride in your hard work and daily progress.", "Her parents watched with pride as she received her diploma."], exVn: ["Hãy tự hào chính đáng về sự chăm chỉ và những tiến bộ mỗi ngày của bạn.", "Cha mẹ cô ấy tự hào dõi theo khi cô nhận tấm bằng tốt nghiệp."] },
    { word: "patience", phonetic: "/ˈpeɪʃns/", def: "The capacity to accept or tolerate delay, trouble, or suffering without getting angry.", defVn: "sự kiên nhẫn, lòng nhẫn nại", pos: "noun", ex: ["Patience and persistence are essential keys to master English speaking.", "Have patience with yourself while learning."], exVn: ["Kiên nhẫn và bền bỉ là những chìa khóa thiết yếu để làm chủ việc nói tiếng Anh.", "Hãy kiên nhẫn với chính mình trong quá trình học tập nhé."] },
    { word: "optimism", phonetic: "/ˈɑːptɪmɪzəm/", def: "Hopefulness and confidence about the future or the success of something.", defVn: "tinh thần lạc quan, yêu đời", pos: "noun", ex: ["Her bright optimism helped the team overcome difficult obstacles.", "Face life challenges with courage and optimism."], exVn: ["Tinh thần lạc quan rạng rỡ của cô ấy đã giúp cả nhóm vượt qua các trở ngại khó khăn.", "Hãy đối mặt với những thử thách trong cuộc sống bằng lòng can đảm và sự lạc quan."] },
    { word: "humility", phonetic: "/hjuːˈmɪləti/", def: "A modest or low view of one's own importance; humbleness.", defVn: "lòng khiêm tốn, khiêm nhường", pos: "noun", ex: ["True masters of their craft lead with humility and kindness.", "Humility allows you to keep learning from everyone."], exVn: ["Những bậc thầy thực thụ luôn dẫn dắt bằng sự khiêm tốn và lòng nhân từ.", "Lòng khiêm nhường cho phép bạn không ngừng học hỏi từ mọi người."] },
    { word: "passion", phonetic: "/ˈpæʃn/", def: "Strong and barely controllable emotion; an intense enthusiasm for something.", defVn: "niềm đam mê cháy bỏng", pos: "noun", ex: ["Follow your true passion and dedication in life.", "Her passion for teaching English shines through in every lesson."], exVn: ["Hãy theo đuổi niềm đam mê đích thực và sự tận hiến trong cuộc sống.", "Niềm đam mê dạy tiếng Anh của cô ấy tỏa sáng trong từng tiết học."] }
  ]
};
