module.exports = {
  // Theme 41: Phụ kiện thời trang (Fashion Accessories)
  t_basic_fashion_accessories: [
    { word: "necklace", phonetic: "/ˈnekləs/", def: "An ornamental chain or string of beads, jewels, or links worn round the neck.", defVn: "dây chuyền, vòng cổ lấp lánh", pos: "noun", ex: ["A delicate silver necklace with a tiny pearl pendant.", "Fasten the clasp of your necklace."], exVn: ["Một sợi dây chuyền bạc thanh mảnh có mặt ngọc trai nhỏ xinh.", "Cài chốt dây chuyền lại nhé."] },
    { word: "bracelet", phonetic: "/ˈbreɪslət/", def: "An ornamental band, hoop, or chain worn on the wrist or arm.", defVn: "vòng đeo tay, lắc tay xinh xắn", pos: "noun", ex: ["She wore a braided silk charm bracelet on her right wrist.", "A sparkling gold bracelet."], exVn: ["Cô ấy đeo chiếc vòng tay bện lụa gắn hạt charm may mắn ở cổ tay phải.", "Một chiếc lắc tay bằng vàng lấp lánh."] },
    { word: "earring", phonetic: "/ˈɪrɪŋ/", def: "A piece of jewelry worn on the lobe or edge of the ear.", defVn: "đôi hoa tai, khuyên tai", pos: "noun", ex: ["Matching pearl stud earrings complement the elegant ao dai dress.", "Silver hoop earrings."], exVn: ["Đôi khuyên tai ngọc trai đồng điệu tôn lên vẻ thanh lịch của tà áo dài.", "Khuyên tai bạc hình tròn."] },
    { word: "ring", phonetic: "/rɪŋ/", def: "A small circular band, typically of precious metal, worn on a finger as an ornament.", defVn: "chiếc nhẫn đeo tay", pos: "noun", ex: ["A polished gold wedding ring worn on the fourth finger.", "A gemstone ring."], exVn: ["Chiếc nhẫn cưới bằng vàng sáng bóng đeo trên ngón áp út.", "Một chiếc nhẫn đính đá quý."] },
    { word: "scarf", phonetic: "/skɑːrf/", def: "A length of fabric worn around the neck or head for warmth or fashion.", defVn: "khăn quàng cổ, khăn choàng lụa", pos: "noun", ex: ["Wrap a soft silk scarf around your neck in breezy autumn weather.", "A warm wool winter scarf."], exVn: ["Quàng chiếc khăn lụa mềm quanh cổ trong tiết trời thu se lạnh.", "Chiếc khăn len ấm áp mùa đông."] },
    { word: "sunglasses", phonetic: "/ˈsʌnɡlæsɪz/", def: "Glasses tinted to protect the eyes from sunlight or glare.", defVn: "kính râm chống nắng, kính mát", pos: "noun", ex: ["Wear polarized sunglasses to protect your eyes from strong beach UV rays.", "Stylish dark sunglasses."], exVn: ["Đeo kính râm phân cực để bảo vệ mắt khỏi tia UV gay gắt trên bãi biển.", "Kính mát màu đen sành điệu."] },
    { word: "wristwatch", phonetic: "/ˈrɪstwɑːtʃ/", def: "A watch worn on a strap around the wrist.", defVn: "đồng hồ đeo tay", pos: "noun", ex: ["He checked his elegant leather wristwatch to arrive on time.", "A waterproof sports wristwatch."], exVn: ["Anh ấy liếc nhìn chiếc đồng hồ đeo tay dây da thanh lịch để đến đúng giờ.", "Đồng hồ thể thao chống nước."] },
    { word: "brooch", phonetic: "/broʊtʃ/", def: "An ornament fastened to clothing with a hinged pin and catch.", defVn: "chiếc ghim cài áo sang trọng", pos: "noun", ex: ["Pin a lotus blossom brooch onto the lapel of your blazer.", "An antique jewel brooch."], exVn: ["Cài một chiếc ghim cài áo hình hoa sen lên ve áo vest của bạn.", "Chiếc ghim cài áo cổ đính đá quý."] },
    { word: "handbag", phonetic: "/ˈhændbæɡ/", def: "A bag used by women to hold personal items such as keys, money, and cosmetics.", defVn: "túi xách tay nữ thời trang", pos: "noun", ex: ["She carries a compact leather handbag with her daily essentials.", "A stylish crossbody handbag."], exVn: ["Cô ấy xách chiếc túi da nhỏ gọn đựng những vật dụng thiết yếu hàng ngày.", "Túi xách đeo chéo thời thượng."] },
    { word: "hairpin", phonetic: "/ˈherpɪn/", def: "A pin used for fastening the hair or holding a hairstyle in place.", defVn: "cây trâm cài tóc truyền thống", pos: "noun", ex: ["Traditional wooden hairpins keep long hair coiled neatly.", "A silver floral hairpin."], exVn: ["Những cây trâm gỗ truyền thống giúp búi tóc dài gọn gàng.", "Chiếc trâm cài tóc hoa bằng bạc."] }
  ],

  // Theme 42: Phòng ngủ & Giấc ngủ (Bedroom & Sleep)
  t_basic_bedroom_sleep: [
    { word: "mattress", phonetic: "/ˈmætrəs/", def: "A fabric case filled with deformable or resilient material, used for sleeping on.", defVn: "tấm nệm êm ái nâng đỡ", pos: "noun", ex: ["A high-quality memory foam mattress ensures restorative, peaceful sleep.", "Rotate the mattress every six months."], exVn: ["Một tấm nệm mút xốp chất lượng cao mang lại giấc ngủ phục hồi và êm ái.", "Xoay chiều nệm sáu tháng một lần."] },
    { word: "duvet", phonetic: "/duːˈveɪ/", def: "A soft quilt filled with down, feathers, or synthetic fiber, used with a cover as a bed covering.", defVn: "chiếc chăn lông vũ ấm áp", pos: "noun", ex: ["Snuggle under the fluffy warm duvet on cold winter evenings.", "A lightweight summer duvet."], exVn: ["Cuộn mình ấm áp dưới chiếc chăn lông vũ bông xốp vào những đêm đông lạnh.", "Chiếc chăn mỏng nhẹ mùa hè."] },
    { word: "pillowcase", phonetic: "/ˈpɪloʊkeɪs/", def: "A removable cloth cover for a pillow.", defVn: "vỏ gối, áo gối", pos: "noun", ex: ["Change your breathable cotton pillowcases every week for clean skin.", "Silky smooth satin pillowcases."], exVn: ["Thay vỏ gối cotton thoáng khí hàng tuần để giữ làn da luôn sạch sẽ.", "Vỏ gối lụa phi bóng mềm mại."] },
    { word: "bedsheet", phonetic: "/ˈbedʃiːt/", def: "A large piece of cloth used to cover a mattress and as a warm bed covering.", defVn: "ga trải giường, drap giường", pos: "noun", ex: ["Smooth crisp linen bedsheets create a five-star hotel bed feeling.", "Fitted elastic bedsheets stay in place."], exVn: ["Tấm ga trải giường bằng vải lanh phẳng phiu tạo cảm giác như giường khách sạn 5 sao.", "Ga bọc đệm bo chun giữ nếp chắc chắn."] },
    { word: "wardrobe", phonetic: "/ˈwɔːrdroʊb/", def: "A large, tall cabinet in which clothes may be hung or stored.", defVn: "tủ quần áo lớn", pos: "noun", ex: ["Hang freshly ironed shirts neatly inside the wooden wardrobe.", "A mirrored sliding door wardrobe."], exVn: ["Treo những chiếc áo sơ mi vừa là phẳng gọn gàng vào trong tủ quần áo gỗ.", "Tủ quần áo cánh trượt có gương soi."] },
    { word: "nightstand", phonetic: "/ˈnaɪtstænd/", def: "A small low bedside table, typically with drawers; bedside table.", defVn: "tủ đầu giường, tab đầu giường", pos: "noun", ex: ["Keep a glass of water, your book, and glasses on the nightstand.", "A bedside lamp on the nightstand."], exVn: ["Để một cốc nước, cuốn sách và kính mắt trên tab đầu giường.", "Chiếc đèn ngủ đặt trên tủ đầu giường."] },
    { word: "alarm clock", phonetic: "/əˈlɑːrm klɑːk/", def: "A clock that can be set to sound at a specified time, used to wake someone up.", defVn: "đồng hồ báo thức buổi sáng", pos: "noun", ex: ["Set your morning alarm clock for 6:00 AM to review English vocabulary.", "A gentle ringing alarm clock."], exVn: ["Đặt đồng hồ báo thức lúc 6h sáng để ôn lại từ vựng tiếng Anh nhé.", "Chiếc đồng hồ báo thức reo chuông êm dịu."] },
    { word: "pajamas", phonetic: "/pəˈdʒɑːməz/", def: "A suit of loose trousers and jacket, worn in bed.", defVn: "bộ đồ ngủ pơ-gia-ma thoải mái", pos: "noun", ex: ["Slip into soft cotton pajamas after a soothing warm bath.", "Comfortable silk pajamas."], exVn: ["Mặc bộ đồ ngủ cotton mềm mại sau khi tắm nước ấm thư giãn.", "Bộ đồ ngủ bằng lụa thoải mái."] },
    { word: "snooze", phonetic: "/snuːz/", def: "A short, light sleep, especially during the day; or to delay an alarm.", defVn: "ngủ nướng thêm vài phút, chợp mắt", pos: "verb", ex: ["Resist the temptation to hit the snooze button in the morning.", "Take a refreshing ten-minute snooze."], exVn: ["Hãy cưỡng lại cám dỗ bấm nút hoãn báo thức vào buổi sáng nhé.", "Chợp mắt 10 phút để nạp lại năng lượng."] },
    { word: "slumber", phonetic: "/ˈslʌmbər/", def: "A deep, peaceful, undisturbed sleep.", defVn: "giấc ngủ say sưa an lành", pos: "noun", ex: ["The soft sound of rain on the roof lulled him into deep slumber.", "Awaken refreshed from sweet slumber."], exVn: ["Tiếng mưa rơi tí tách êm đềm trên mái nhà ru anh vào giấc ngủ say an lành.", "Thức dậy sảng khoái sau giấc ngủ ngon."] }
  ],

  // Theme 43: Phòng tắm & Vệ sinh (Bathroom & Toiletries)
  t_basic_bathroom_toiletries: [
    { word: "conditioner", phonetic: "/kənˈdɪʃənər/", def: "A substance applied to hair after shampooing to improve its condition and texture.", defVn: "dầu xả dưỡng tóc mượt mà", pos: "noun", ex: ["Apply herbal hair conditioner to keep your hair soft and shiny.", "Rinse hair conditioner with cool water."], exVn: ["Thoa dầu xả thảo dược để mái tóc luôn mềm mượt và bóng khỏe.", "Xả sạch dầu xả bằng nước mát."] },
    { word: "dental floss", phonetic: "/ˌdentl ˈflɔːs/", def: "Soft thread used to clean between the teeth.", defVn: "chỉ nha khoa làm sạch kẽ răng", pos: "noun", ex: ["Dentists recommend using waxed dental floss every night before brushing.", "Floss teeth gently between gaps."], exVn: ["Nha sĩ khuyên nên dùng chỉ nha khoa có phủ sáp mỗi tối trước khi đánh răng.", "Làm sạch kẽ răng nhẹ nhàng bằng chỉ nha khoa."] },
    { word: "bathrobe", phonetic: "/ˈbæθroʊb/", def: "A dressing gown made of absorbent fabric, typically toweling, worn after a bath or swim.", defVn: "áo choàng tắm bông mềm", pos: "noun", ex: ["Wrap yourself in a plush white cotton bathrobe after a warm shower.", "Hotel luxury bathrobe."], exVn: ["Quàng chiếc áo choàng tắm cotton trắng êm ái sau khi tắm vòi sen nước ấm.", "Áo choàng tắm cao cấp của khách sạn."] },
    { word: "shaving cream", phonetic: "/ˈʃeɪvɪŋ kriːm/", def: "A creamy preparation applied to the face or other body parts to facilitate shaving.", defVn: "bọt cạo râu mềm da", pos: "noun", ex: ["Apply moisturizing shaving cream before shaving for a smooth glide.", "Sensitive skin shaving foam."], exVn: ["Thoa bọt cạo râu dưỡng ẩm trước khi cạo để lưỡi dao lướt êm ái.", "Bọt cạo râu dành cho da nhạy cảm."] },
    { word: "drain", phonetic: "/dreɪn/", def: "A channel or pipe carrying off surplus liquid, especially rainwater or liquid waste.", defVn: "lỗ thoát nước sàn", pos: "noun", ex: ["Clear any hair from the bathroom shower floor drain regularly.", "Water spirals quickly down the drain."], exVn: ["Lau dọn sạch tóc rụng ở lỗ thoát nước sàn phòng tắm thường xuyên nhé.", "Nước xoáy nhanh xuống cống thoát nước."] },
    { word: "mirror", phonetic: "/ˈmɪrər/", def: "A reflective surface, now typically of glass coated with a metal amalgam, that reflects a clear image.", defVn: "gương soi phòng tắm sáng bóng", pos: "noun", ex: ["Wipe the steamy bathroom mirror after a hot shower.", "An LED illuminated vanity mirror."], exVn: ["Lau sạch hơi nước mờ trên gương phòng tắm sau khi tắm nước nóng.", "Gương trang điểm có đèn LED viền sáng."] },
    { word: "body wash", phonetic: "/ˈbɑːdi wɑːʃ/", def: "A liquid product used for cleaning the body while showering; shower gel.", defVn: "sữa tắm hương hoa thơm mát", pos: "noun", ex: ["A refreshing citrus and lavender body wash leaves skin fragrant.", "Lather body wash with a sponge."], exVn: ["Sữa tắm hương cam quýt và hoa oải hương làm làn da thơm mát sảng khoái.", "Tạo bọt sữa tắm bằng miếng bọt biển."] },
    { word: "lotion", phonetic: "/ˈloʊʃn/", def: "A thick, smooth liquid designed to be applied to the skin for medicinal or cosmetic purposes.", defVn: "sữa dưỡng thể dưỡng ẩm da", pos: "noun", ex: ["Apply hydrating body lotion immediately after drying off with a towel.", "Coconut moisturizing lotion."], exVn: ["Thoa sữa dưỡng thể cấp ẩm ngay sau khi thấm khô người bằng khăn tắm.", "Sữa dưỡng ẩm chiết xuất dừa."] }
  ],

  // Theme 44: Cảm giác cơ thể (Bodily Sensations)
  t_basic_bodily_sensations: [
    { word: "fatigue", phonetic: "/fəˈtiːɡ/", def: "Extreme tiredness resulting from mental or physical exertion or illness.", defVn: "sự mệt mỏi, suy nhược cơ thể", pos: "noun", ex: ["Proper rest and deep hydration relieve everyday physical fatigue.", "Combat mental fatigue with a brisk walk."], exVn: ["Nghỉ ngơi hợp lý và uống đủ nước giúp xua tan sự mệt mỏi thể chất hàng ngày.", "Đánh tan mệt mỏi tinh thần bằng một chuyến đi dạo nhanh."] },
    { word: "cramp", phonetic: "/kræmp/", def: "A painful involuntary contraction of a muscle or muscles, typically caused by fatigue or strain.", defVn: "chuột rút, co thắt cơ bắp", pos: "noun", ex: ["Stretch leg calves gently to relieve a sudden swimming muscle cramp.", "Drink electrolyte water to prevent cramps."], exVn: ["Kéo giãn bắp chân nhẹ nhàng để làm dịu cơn chuột rút bất ngờ khi bơi.", "Uống nước điện giải để phòng ngừa chuột rút."] },
    { word: "goosebumps", phonetic: "/ˈɡuːsbʌmps/", def: "A state of the skin caused by cold, fear, or excitement, in which small bumps appear.", defVn: "nổi da gà (vì lạnh/xúc động)", pos: "noun", ex: ["Listening to the moving national anthem gave me goosebumps of pride.", "Cold wind brought goosebumps on arms."], exVn: ["Lắng nghe giai điệu Quốc ca xúc động làm tôi nổi da gà vì niềm tự hào khôn xiết.", "Gió lạnh làm nổi da gà trên cánh tay."] },
    { word: "soreness", phonetic: "/ˈsɔːrnəs/", def: "Pain or discomfort resulting from injury, infection, or vigorous exercise.", defVn: "sự nhức mỏi cơ sau khi tập", pos: "noun", ex: ["Mild muscle soreness after your first gym session is completely normal.", "A warm bath eases muscle soreness."], exVn: ["Hiện tượng nhức mỏi cơ nhẹ sau buổi tập gym đầu tiên là hoàn toàn bình thường.", "Tắm nước ấm giúp làm dịu cảm giác nhức mỏi cơ."] },
    { word: "heartbeat", phonetic: "/ˈhɑːrtbiːt/", def: "The pulsation of the heart.", defVn: "nhịp đập trái tim", pos: "noun", ex: ["Cardio exercise strengthens your resting heartbeat and stamina.", "Listen to the steady calm heartbeat."], exVn: ["Tập thể dục tim mạch giúp tăng cường nhịp đập trái tim và sức bền cơ thể.", "Lắng nghe nhịp tim đập đều đặn và bình yên."] },
    { word: "thirst", phonetic: "/θɜːrst/", def: "A feeling of needing to drink something.", defVn: "cơn khát nước", pos: "noun", ex: ["Quench your intense thirst with a tall glass of cool mineral water.", "Recognize the early signs of thirst."], exVn: ["Giải tỏa cơn khát cồn cào bằng một ly nước khoáng mát lạnh đầy ắp.", "Nhận biết sớm các dấu hiệu khi cơ thể bị khát."] },
    { word: "tingling", phonetic: "/ˈtɪŋɡlɪŋ/", def: "An experience of a slight prickling or stinging sensation.", defVn: "cảm giác châm chích tê tê nhẹ", pos: "noun", ex: ["A tingling sensation in your foot means circulation is returning.", "Tingling warmth in cold hands."], exVn: ["Cảm giác châm chích tê tê ở bàn chân báo hiệu máu đang lưu thông trở lại.", "Hơi ấm tê tê lan tỏa trong đôi bàn tay lạnh."] }
  ],

  // Theme 46: Mối quan hệ & Xã hội (Social Relationships)
  t_basic_relationships_social: [
    { word: "mentor", phonetic: "/ˈmentɔːr/", def: "An experienced and trusted adviser.", defVn: "người thầy dẫn đường, cố vấn", pos: "noun", ex: ["A wise professional mentor guides your career growth with patient wisdom.", "Seek guidance from senior mentors."], exVn: ["Một người cố vấn thông thái sẽ dẫn dắt sự nghiệp của bạn bằng sự tận tâm và am hiểu.", "Tìm kiếm lời khuyên từ các bậc tiền bối."] },
    { word: "acquaintance", phonetic: "/əˈkweɪntəns/", def: "A person one knows slightly, but who is not a close friend.", defVn: "người quen biết xã giao", pos: "noun", ex: ["Turn casual acquaintances into meaningful lifelong friends through kindness.", "Wave hello to a neighborhood acquaintance."], exVn: ["Biến những người quen xã giao thành bạn bè tri kỷ cả đời bằng lòng tốt.", "Vẫy tay chào một người quen trong xóm."] },
    { word: "companion", phonetic: "/kəmˈpæniən/", def: "A person or animal with whom one spends a lot of time or with whom one travels.", defVn: "người bạn đồng hành tin cậy", pos: "noun", ex: ["A loyal dog is humanity's most faithful daily companion.", "A wonderful travel companion on road trips."], exVn: ["Chú chó trung thành là người bạn đồng hành thủy chung nhất của con người.", "Một người bạn đồng hành tuyệt vời trên những chuyến đi."] },
    { word: "teamwork", phonetic: "/ˈtiːmwɜːrk/", def: "The combined action of a group of people, especially when effective and efficient.", defVn: "tinh thần làm việc đồng đội", pos: "noun", ex: ["Great teamwork makes even the most difficult project succeed smoothly.", "Effective communication is the core of teamwork."], exVn: ["Tinh thần đồng đội tuyệt vời giúp dự án khó khăn nhất cũng thành công suôn sẻ.", "Giao tiếp hiệu quả là cốt lõi của làm việc nhóm."] },
    { word: "loyalty", phonetic: "/ˈlɔɪəlti/", def: "The quality of being loyal to someone or something.", defVn: "lòng trung thành, sự thủy chung", pos: "noun", ex: ["Loyalty and honesty are the unshakable pillars of true friendship.", "Demonstrate loyalty in times of trial."], exVn: ["Lòng trung thành và sự trung thực là những trụ cột vững chắc của tình bạn chân chính.", "Thể hiện lòng trung thành trong lúc gian nan."] },
    { word: "harmony", phonetic: "/ˈhɑːrməni/", def: "Agreement or concord; living together peacefully.", defVn: "sự hòa thuận, hòa hợp ấm êm", pos: "noun", ex: ["Living in peace and harmony with neighbors creates a blissful community.", "A family living in mutual harmony."], exVn: ["Sống chan hòa và hòa thuận với xóm giềng tạo nên một cộng đồng an lành.", "Một gia đình cùng nhau sống trong hòa thuận êm ấm."] }
  ],

  // Theme 47: Giao tiếp & Thư tín (Conversation & Communication)
  t_basic_conversation_communication: [
    { word: "announce", phonetic: "/əˈnaʊns/", def: "Make a formal public statement about a fact, occurrence, or intention.", defVn: "thông báo, công bố chính thức", pos: "verb", ex: ["The school principal announced the national competition winners proudly.", "Announce good news to your family."], exVn: ["Thầy hiệu trưởng tự hào công bố những học sinh đoạt giải cuộc thi quốc gia.", "Báo tin mừng cho cả gia đình cùng vui."] },
    { word: "debate", phonetic: "/dɪˈbeɪt/", def: "A formal discussion on a particular topic in a public meeting or legislative assembly.", defVn: "cuộc tranh biện, tranh luận", pos: "noun", ex: ["Participate actively in the high school English debate tournament.", "Debate opposing viewpoints respectfully."], exVn: ["Tích cực tham gia giải đấu tranh biện tiếng Anh cấp trường trung học.", "Tranh luận các quan điểm trái chiều một cách lịch sự."] },
    { word: "interview", phonetic: "/ˈɪntərvjuː/", def: "A meeting of people face to face, especially for consultation or job evaluation.", defVn: "buổi phỏng vấn xin việc / học bổng", pos: "noun", ex: ["Prepare confidently for your international scholarship English interview.", "The interviewer smiled warmly."], exVn: ["Tự tin chuẩn bị cho buổi phỏng vấn xin học bổng quốc tế bằng tiếng Anh.", "Người phỏng vấn mỉm cười nồng hậu."] },
    { word: "pronounce", phonetic: "/prəˈnaʊns/", def: "Make the sound of a word or part of a word in the correct way.", defVn: "phát âm chuẩn xác từ ngữ", pos: "verb", ex: ["Listen to the audio recording to pronounce English vowels accurately.", "Practice pronouncing tricky words daily."], exVn: ["Lắng nghe bản ghi âm để phát âm các nguyên âm tiếng Anh chuẩn xác.", "Luyện phát âm các từ khó mỗi ngày."] },
    { word: "compliment", phonetic: "/ˈkɑːmplɪmənt/", def: "A polite expression of praise or admiration.", defVn: "lời khen ngợi, lời tán dương", pos: "noun", ex: ["She blushed with joy when she received a genuine compliment on her presentation.", "Pay someone a sincere compliment."], exVn: ["Cô ấy đỏ mặt vì vui sướng khi nhận được lời khen chân thành về bài thuyết trình.", "Dành cho ai đó một lời khen chân thành."] },
    { word: "feedback", phonetic: "/ˈfiːdbæk/", def: "Information about reactions to a product, a person's performance of a task, etc. used as a basis for improvement.", defVn: "nhận xét góp ý xây dựng (feedback)", pos: "noun", ex: ["Constructive teacher feedback helps students write English essays better.", "Welcome constructive feedback gratefully."], exVn: ["Những nhận xét góp ý xây dựng của thầy cô giúp học sinh viết luận tiếng Anh tốt hơn.", "Biết ơn và đón nhận những lời góp ý xây dựng."] },
    { word: "clarify", phonetic: "/ˈklærəfaɪ/", def: "Make a statement or situation less confused and more clearly comprehensible.", defVn: "làm sáng tỏ, giải thích rõ ràng", pos: "verb", ex: ["Could you please clarify what that idiom means in this sentence context?", "Clarify misunderstandings gently."], exVn: ["Bạn có thể giải thích rõ thành ngữ đó có nghĩa là gì trong ngữ cảnh câu này không?", "Làm sáng tỏ những hiểu lầm một cách nhẹ nhàng."] }
  ],

  // Theme 50: Âm thanh & Nhạc cụ (Sounds & Instruments)
  t_basic_sounds_instruments: [
    { word: "saxophone", phonetic: "/ˈsæksəfoʊn/", def: "A member of a family of metal wind instruments with a single-reed mouthpiece, used especially in jazz.", defVn: "kèn sắc-xô-phôn (nhạc jazz)", pos: "noun", ex: ["The soulful golden saxophone melody echoed warmly in the cozy jazz cafe.", "Master the brass saxophone keys."], exVn: ["Giai điệu kèn sắc-xô-phôn da diết vàng rực vang vọng ấm cúng trong quán cà phê nhạc jazz.", "Luyện ngón bấm phím kèn saxophone đồng."] },
    { word: "harp", phonetic: "/hɑːrp/", def: "A musical instrument, roughly triangular in shape, consisting of a frame supporting a graduated series of parallel strings.", defVn: "đàn hạc, hạc cầm thánh thót", pos: "noun", ex: ["Gentle harp chords sound like heavenly raindrops falling on calm water.", "Pluck the golden harp strings."], exVn: ["Những hợp âm đàn hạc dịu êm nghe như những hạt mưa thiên đường rơi trên mặt nước phẳng lặng.", "Gảy những dây đàn hạc vàng óng."] },
    { word: "accordion", phonetic: "/əˈkɔːrdiən/", def: "A portable musical instrument with metal reeds blown by bellows, played by means of keys and buttons.", defVn: "đàn phong cầm, đàn xếp (accordion)", pos: "noun", ex: ["Street musicians play lively European folk waltzes on the accordion.", "Expand the accordion bellows rhythmically."], exVn: ["Các nghệ sĩ đường phố chơi những bản nhạc van-xơ dân gian châu Âu rộn rã bằng đàn phong cầm.", "Kéo mở hộp gió đàn xếp nhịp nhàng."] },
    { word: "harmonica", phonetic: "/hɑːrˈmɑːnɪkə/", def: "A small rectangular wind instrument with a row of tuned metal reeds; mouth organ.", defVn: "kèn hec-mô-ni-ca bỏ túi", pos: "noun", ex: ["He played a sweet folk song on his pocket silver harmonica around the campfire.", "Blow and draw air through the harmonica."], exVn: ["Anh ấy thổi một bài dân ca ngọt ngào bằng chiếc kèn harmonica bạc bỏ túi bên ánh lửa trại.", "Thổi và hít không khí qua kèn harmonica."] },
    { word: "xylophone", phonetic: "/ˈzaɪləfoʊn/", def: "A musical instrument played by striking a row of wooden bars of graduated length with small mallets.", defVn: "đàn mộc cầm (gần gũi với đàn T'rưng)", pos: "noun", ex: ["Children love striking colorful xylophone wooden bars with mallets.", "Traditional bamboo xylophone (Dan T'rung)."], exVn: ["Trẻ em rất thích dùng dùi gõ lên những thanh gỗ mộc cầm rực rỡ sắc màu.", "Đàn mộc cầm tre truyền thống (Đàn T'rưng Tây Nguyên)."] },
    { word: "rhythm", phonetic: "/ˈrɪðəm/", def: "A strong, regular, repeated pattern of movement or sound.", defVn: "tiết tấu, nhịp điệu bài hát", pos: "noun", ex: ["Tap your feet along with the energetic upbeat rhythm of the drums.", "A steady natural walking rhythm."], exVn: ["Gõ nhịp chân theo tiết tấu dồn dập đầy năng lượng của tiếng trống.", "Một nhịp bước đi tự nhiên đều đặn."] },
    { word: "tempo", phonetic: "/ˈtempoʊ/", def: "The speed at which a passage of music is, or should be, played.", defVn: "nhịp độ nhanh chậm của bản nhạc", pos: "noun", ex: ["The song transitions from a slow gentle tempo into a joyful fast beat.", "Accelerate the tempo at the chorus."], exVn: ["Bài hát chuyển từ nhịp độ chậm rãi dịu êm sang nhịp điệu nhanh vui tươi rộn rã.", "Đẩy nhanh nhịp độ ở đoạn điệp khúc."] }
  ]
};
