module.exports = {
  // Theme 18: Trường học & Dụng cụ (School & Stationery)
  t_basic_school_stationery: [
    { word: "blackboard", phonetic: "/ˈblækbɔːrd/", def: "A large smooth dark panel for writing on with chalk.", defVn: "bảng đen lớp học", pos: "noun", ex: ["The teacher writes grammar rules on the blackboard.", "Erase the blackboard after class."], exVn: ["Thầy giáo viết các quy tắc ngữ pháp lên bảng đen.", "Lau sạch bảng đen sau giờ học nhé."] },
    { word: "chalk", phonetic: "/tʃɔːk/", def: "A soft white limestone used for writing on blackboards.", defVn: "viên phấn viết bảng", pos: "noun", ex: ["Write new English words with white chalk.", "A box of colored chalk."], exVn: ["Viết từ vựng tiếng Anh mới bằng phấn trắng.", "Một hộp phấn nhiều màu."] },
    { word: "crayon", phonetic: "/ˈkreɪɑːn/", def: "A pencil or stick of colored chalk or wax, used for drawing.", defVn: "bút sáp màu vẽ tranh", pos: "noun", ex: ["Children love coloring pictures with bright wax crayons.", "Draw a rainbow with crayons."], exVn: ["Trẻ em rất thích tô màu bằng bút sáp rực rỡ.", "Vẽ cầu vồng bằng bút sáp màu."] },
    { word: "globe", phonetic: "/ɡloʊb/", def: "A spherical model of the Earth.", defVn: "quả địa cầu học tập", pos: "noun", ex: ["Spin the classroom globe to find Vietnam and the UK.", "Point to oceans on the globe."], exVn: ["Xoay quả địa cầu lớp học để tìm Việt Nam và nước Anh.", "Chỉ vào các đại dương trên quả địa cầu."] },
    { word: "textbook", phonetic: "/ˈtekstbʊk/", def: "A book used as a standard work for the study of a subject.", defVn: "sách giáo khoa", pos: "noun", ex: ["Open your English textbook to page twenty-five.", "Read the textbook dialogue aloud."], exVn: ["Mở sách giáo khoa tiếng Anh trang 25 nhé.", "Đọc to bài hội thoại trong sách giáo khoa."] },
    { word: "diploma", phonetic: "/dɪˈploʊmə/", def: "A certificate awarded by an educational establishment.", defVn: "bằng tốt nghiệp, chứng chỉ", pos: "noun", ex: ["She proudly received her high school graduation diploma.", "Frame the graduation diploma on the wall."], exVn: ["Cô ấy tự hào nhận tấm bằng tốt nghiệp trung học phổ thông.", "Treo khung bằng tốt nghiệp lên tường."] },
    { word: "locker", phonetic: "/ˈlɑːkər/", def: "A small lockable cupboard or compartment.", defVn: "tủ khóa đựng đồ cá nhân", pos: "noun", ex: ["Store your backpack and heavy books in your hallway locker.", "Remember your locker combination."], exVn: ["Cất ba-lô và sách vở nặng vào tủ khóa hành lang.", "Nhớ mật mã tủ khóa của bạn nhé."] },
    { word: "binder", phonetic: "/ˈbaɪndər/", def: "A cover or folder for holding papers together.", defVn: "bìa còng lưu trữ tài liệu", pos: "noun", ex: ["Organize all English worksheets in a three-ring binder.", "Label your binder tabs clearly."], exVn: ["Sắp xếp toàn bộ phiếu bài tập tiếng Anh vào bìa còng.", "Dán nhãn các ngăn bìa còng rõ ràng."] },
    { word: "essay", phonetic: "/ˈeseɪ/", def: "A short piece of writing on a particular subject.", defVn: "bài văn nghị luận, bài luận", pos: "noun", ex: ["Write a two-hundred-word essay about your dream career.", "The teacher praised her creative essay."], exVn: ["Viết một bài luận 200 từ về nghề nghiệp mơ ước của bạn.", "Thầy giáo đã khen ngợi bài văn giàu tính sáng tạo của cô ấy."] },
    { word: "semester", phonetic: "/sɪˈmestər/", def: "A half-year term in a school or college.", defVn: "học kỳ (học kỳ I, II)", pos: "noun", ex: ["The autumn semester begins in early September.", "Set ambitious goals for this new semester."], exVn: ["Học kỳ mùa thu bắt đầu vào đầu tháng Chín.", "Hãy đặt ra những mục tiêu lớn cho học kỳ mới này."] },
    { word: "scholarship", phonetic: "/ˈskɑːlərʃɪp/", def: "A grant or payment made to support a student's education.", defVn: "học bổng khuyến học", pos: "noun", ex: ["She won a prestigious university scholarship for academic excellence.", "Apply for international English scholarships."], exVn: ["Cô ấy đã giành được học bổng đại học danh giá nhờ thành tích học tập xuất sắc.", "Nộp hồ sơ xin học bổng tiếng Anh quốc tế."] },
    { word: "tutor", phonetic: "/ˈtuːtər/", def: "A private teacher, typically one who teaches a single student or very small group.", defVn: "gia sư kèm học", pos: "noun", ex: ["An experienced English tutor helps improve speaking pronunciation.", "Study with a patient online tutor."], exVn: ["Một gia sư tiếng Anh giàu kinh nghiệm giúp cải thiện phát âm khi nói.", "Học cùng một gia sư trực tuyến kiên nhẫn."] },
    { word: "paintbrush", phonetic: "/ˈpeɪntbrʌʃ/", def: "A brush for applying paint.", defVn: "cọ vẽ tranh mỹ thuật", pos: "noun", ex: ["Dip the fine paintbrush into blue watercolor.", "Wash paintbrushes thoroughly after art class."], exVn: ["Chấm cọ vẽ mảnh vào màu nước xanh dương.", "Rửa sạch cọ vẽ sau giờ học mỹ thuật nhé."] }
  ],

  // Theme 19: Sở thích & Thể thao (Hobbies & Sports)
  t_basic_hobbies_sports: [
    { word: "champion", phonetic: "/ˈtʃæmpiən/", def: "A person who has defeated or surpassed all rivals in a competition.", defVn: "nhà vô địch, quán quân", pos: "noun", ex: ["The national soccer team became the regional tournament champion.", "Train hard every day to become a champion."], exVn: ["Đội tuyển bóng đá quốc gia đã trở thành nhà vô địch giải đấu khu vực.", "Luyện tập chăm chỉ mỗi ngày để trở thành nhà vô địch."] },
    { word: "referee", phonetic: "/ˌrefəˈriː/", def: "An official who watches a game or match closely to enforce the rules.", defVn: "trọng tài điều khiển trận đấu", pos: "noun", ex: ["The impartial referee blew the whistle to signal the start.", "Respect the referee's decisions during sports."], exVn: ["Vị trọng tài công tâm đã thổi còi báo hiệu trận đấu bắt đầu.", "Tôn trọng các quyết định của trọng tài trong thể thao."] },
    { word: "tournament", phonetic: "/ˈtʊrnəmənt/", def: "A series of contests between a number of competitors.", defVn: "giải đấu thể thao", pos: "noun", ex: ["Our school participated in the annual basketball tournament.", "The tennis tournament final was thrilling."], exVn: ["Trường chúng tôi đã tham gia giải đấu bóng rổ thường niên.", "Trận chung kết giải đấu quần vợt diễn ra vô cùng kịch tính."] },
    { word: "medal", phonetic: "/ˈmedl/", def: "A metal disc awarded as a distinction for an achievement.", defVn: "huy chương vàng / bạc / đồng", pos: "noun", ex: ["The runner proudly wore her shining gold medal on the podium.", "Win a bronze medal in swimming."], exVn: ["Vận động viên chạy bộ tự hào đeo chiếc huy chương vàng sáng lấp lánh trên bục nhận giải.", "Giành huy chương đồng môn bơi lội."] },
    { word: "trophy", phonetic: "/ˈtroʊfi/", def: "A cup or other decorative object awarded as a prize for a victory.", defVn: "chiếc cúp vô địch", pos: "noun", ex: ["The captain hoisted the championship gold trophy high in the air.", "A shining silver trophy in the display cabinet."], exVn: ["Người đội trưởng giương cao chiếc cúp vô địch mạ vàng lên không trung.", "Chiếc cúp bạc sáng loáng trong tủ trưng bày."] },
    { word: "gymnastics", phonetic: "/dʒɪmˈnæstɪks/", def: "Exercises developing physical agility and coordination.", defVn: "môn thể dục dụng cụ", pos: "noun", ex: ["Gymnastics improves body flexibility, balance, and core strength.", "She started artistic gymnastics at age six."], exVn: ["Thể dục dụng cụ giúp tăng cường sự dẻo dai, thăng bằng và sức mạnh cơ thể.", "Cô ấy bắt đầu tập thể dục dụng cụ nghệ thuật từ năm 6 tuổi."] },
    { word: "bowling", phonetic: "/ˈboʊlɪŋ/", def: "A game played by rolling a heavy ball down a wooden lane to knock down pins.", defVn: "môn chơi bóng gỗ, bowling", pos: "noun", ex: ["Go bowling with close friends on a relaxing weekend evening.", "He scored a perfect strike in bowling."], exVn: ["Đi chơi bowling cùng bạn thân vào một buổi tối cuối tuần thư giãn.", "Anh ấy đã ghi điểm tuyệt đối khi ném đổ toàn bộ con gỗ."] },
    { word: "archery", phonetic: "/ˈɑːrtʃəri/", def: "The sport or skill of shooting with a bow and arrows.", defVn: "môn bắn cung nghệ thuật", pos: "noun", ex: ["Archery demands immense patience, deep focus, and steady breath.", "Hit the bullseye in target archery."], exVn: ["Bắn cung đòi hỏi sự kiên nhẫn to lớn, độ tập trung cao và hơi thở đều đặn.", "Bắn trúng hồng tâm trong môn bắn cung."] },
    { word: "marathon", phonetic: "/ˈmærəθɑːn/", def: "A long-distance running race with an official distance of 42.195 kilometers.", defVn: "cuộc chạy việt dã marathon (42km)", pos: "noun", ex: ["Thousands of runners joined the scenic Ha Long Bay Marathon.", "Crossing the marathon finish line is triumphant."], exVn: ["Hàng ngàn vận động viên đã tham gia giải Marathon ngắm cảnh Vịnh Hạ Long.", "Vượt qua vạch đích marathon là cảm giác chiến thắng vỡ òa."] },
    { word: "skateboarding", phonetic: "/ˈskeɪtbɔːrdɪŋ/", def: "The sport or pastime of riding on a skateboard.", defVn: "môn trượt ván đường phố", pos: "noun", ex: ["Skateboarding in the public park is popular among energetic youth.", "Wear a protective helmet while skateboarding."], exVn: ["Trượt ván trong công viên công cộng rất phổ biến trong giới trẻ năng động.", "Đội mũ bảo hiểm bảo hộ khi chơi trượt ván nhé."] },
    { word: "fitness", phonetic: "/ˈfɪtnəs/", def: "The condition of being physically fit and healthy.", defVn: "thể lực, sự cân đối thể hình", pos: "noun", ex: ["Daily cardiovascular exercise boosts overall fitness and mood.", "Join a local fitness gym."], exVn: ["Tập thể dục tim mạch hàng ngày giúp nâng cao thể lực và tâm trạng.", "Tham gia một phòng tập thể hình gần nhà."] },
    { word: "workout", phonetic: "/ˈwɜːrkaʊt/", def: "A session of vigorous physical exercise or training.", defVn: "buổi tập luyện thể dục thể thao", pos: "noun", ex: ["A thirty-minute full-body workout burns calories and reduces stress.", "Drink water after a heavy workout."], exVn: ["Buổi tập toàn thân 30 phút giúp đốt cháy calo và giảm căng thẳng.", "Uống nước sau buổi tập luyện nặng nhé."] }
  ],

  // Theme 20: Mua sắm & Tiền tệ (Shopping & Money)
  t_basic_shopping_money: [
    { word: "cashier", phonetic: "/kæˈʃɪr/", def: "A person handling payments and receipts in a store, bank, or restaurant.", defVn: "nhân viên thu ngân", pos: "noun", ex: ["Hand your shopping basket to the polite supermarket cashier.", "The cashier scanned items quickly."], exVn: ["Đưa giỏ hàng cho nhân viên thu ngân siêu thị lịch sự.", "Nhân viên thu ngân quét mã sản phẩm rất nhanh chóng."] },
    { word: "receipt", phonetic: "/rɪˈsiːt/", def: "A printed acknowledgment of having received a specified amount of money.", defVn: "biên lai, hóa đơn mua hàng", pos: "noun", ex: ["Always keep your purchase receipt in case you need an exchange.", "Check the receipt for listed items."], exVn: ["Luôn giữ lại biên lai mua hàng đề phòng trường hợp cần đổi trả.", "Kiểm tra hóa đơn để xem danh sách món đồ đã mua."] },
    { word: "coupon", phonetic: "/ˈkuːpɑːn/", def: "A voucher entitling the holder to a discount off a particular product.", defVn: "phiếu giảm giá, mã giảm giá", pos: "noun", ex: ["Apply an online discount coupon at checkout for twenty percent off.", "Clip paper coupons from the flyer."], exVn: ["Nhập mã phiếu giảm giá trực tuyến khi thanh toán để được giảm 20%.", "Cắt các phiếu giảm giá từ tờ rơi quảng cáo."] },
    { word: "barcode", phonetic: "/ˈbɑːrkoʊd/", def: "A machine-readable code in the form of parallel lines of varying widths.", defVn: "mã vạch sản phẩm", pos: "noun", ex: ["The scanner beeps when it reads the product barcode accurately.", "Scan the barcode on the price tag."], exVn: ["Máy quét kêu bíp khi đọc chính xác mã vạch của sản phẩm.", "Quét mã vạch trên nhãn giá nhé."] },
    { word: "cart", phonetic: "/kɑːrt/", def: "A small vehicle with wheels pushed by hand for carrying shopping goods.", defVn: "xe đẩy hàng siêu thị", pos: "noun", ex: ["Push a wheeled shopping cart through the spacious supermarket aisles.", "Fill the cart with fresh groceries."], exVn: ["Đẩy chiếc xe đẩy hàng có bánh lăn qua các lối đi rộng rãi trong siêu thị.", "Chất đầy đồ ăn tươi sống vào xe đẩy hàng."] },
    { word: "basket", phonetic: "/ˈbæskɪt/", def: "A container used to carry items while shopping.", defVn: "giỏ xách mua hàng", pos: "noun", ex: ["Pick up a handheld red plastic basket for quick shopping trips.", "Carry the basket on your arm."], exVn: ["Lấy chiếc giỏ nhựa màu đỏ xách tay cho chuyến mua sắm nhanh gọn.", "Xách giỏ hàng trên cánh tay."] },
    { word: "refund", phonetic: "/ˈriːfʌnd/", def: "A repayment of a sum of money, typically to a dissatisfied customer.", defVn: "tiền hoàn lại, sự hoàn tiền", pos: "noun", ex: ["The customer service desk granted a full cash refund for the defective item.", "Ask for a refund if unsatisfied."], exVn: ["Quầy chăm sóc khách hàng đã hoàn lại toàn bộ tiền mặt cho sản phẩm bị lỗi.", "Yêu cầu hoàn tiền nếu không hài lòng nhé."] },
    { word: "exchange", phonetic: "/ɪksˈtʃeɪndʒ/", def: "The act of giving one thing and receiving another in return.", defVn: "đổi hàng, đổi cỡ size", pos: "verb", ex: ["You can exchange this shirt for a larger size within seven days.", "Exchange currencies at the airport."], exVn: ["Bạn có thể đổi chiếc áo này lấy cỡ lớn hơn trong vòng 7 ngày.", "Đổi ngoại tệ tại sân bay nhé."] },
    { word: "aisle", phonetic: "/aɪl/", def: "A passage between rows of shelves in a supermarket.", defVn: "lối đi giữa các dãy kệ hàng", pos: "noun", ex: ["You can find cooking spices in supermarket Aisle 4.", "Walk down the beverage aisle."], exVn: ["Bạn có thể tìm thấy gia vị nấu ăn ở Lối đi số 4 trong siêu thị.", "Đi dọc theo dãy kệ đồ uống nhé."] },
    { word: "bargain", phonetic: "/ˈbɑːrɡən/", def: "A thing bought or offered for sale more cheaply than is usual or expected.", defVn: "món hời, mua được giá hời", pos: "noun", ex: ["Buying this winter wool coat at half price was a true bargain.", "Bargain politely at night markets."], exVn: ["Mua được chiếc áo khoác len mùa đông này với giá nửa tiền đúng là một món hời.", "Mặc cả lịch sự tại các khu chợ đêm nhé."] },
    { word: "banknote", phonetic: "/ˈbæŋknoʊt/", def: "A piece of paper money, constituting a central bank's promissory note.", defVn: "tờ tiền giấy, tiền mặt", pos: "noun", ex: ["Vietnamese polymer banknotes are durable and water-resistant.", "Fold the banknotes inside your wallet."], exVn: ["Những tờ tiền giấy polymer của Việt Nam rất bền và chống thấm nước.", "Gấp những tờ tiền gọn gàng vào trong ví."] },
    { word: "currency", phonetic: "/ˈkɜːrənsi/", def: "A system of money in common use within a particular country.", defVn: "tiền tệ quốc gia", pos: "noun", ex: ["The Vietnamese Dong is the official national currency of Vietnam.", "Check daily foreign currency exchange rates."], exVn: ["Đồng Việt Nam là đơn vị tiền tệ quốc gia chính thức của Việt Nam.", "Kiểm tra tỷ giá hối đoái tiền tệ hàng ngày."] }
  ],

  // Theme 21: Cây cối & Hoa quả (Plants & Fruits)
  t_basic_plants_fruits: [
    { word: "avocado", phonetic: "/ˌævəˈkɑːdoʊ/", def: "A pear-shaped tropical fruit with a rough skin and oily edible flesh.", defVn: "quả bơ sáp béo ngậy", pos: "noun", ex: ["Dak Lak creamy avocados make rich smoothies and salads.", "Spread ripe avocado on toast."], exVn: ["Những trái bơ sáp béo ngậy Đắk Lắk làm món sinh tố và sa-lát rất ngon.", "Phết bơ chín lên bánh mì nướng."] },
    { word: "guava", phonetic: "/ˈɡwɑːvə/", def: "An edible pale orange tropical fruit with pink or white juicy flesh.", defVn: "quả ổi giòn ngọt", pos: "noun", ex: ["Crispy sliced guava dipped in chili salt is a favorite snack.", "Guava is packed with vitamin C."], exVn: ["Ổi giòn thái lát chấm muối ớt là món ăn vặt khoái khẩu.", "Quả ổi chứa lượng vitamin C vô cùng dồi dào."] },
    { word: "jackfruit", phonetic: "/ˈdʒækfruːt/", def: "A large tropical fruit with sweet golden fragrant pods.", defVn: "quả mít thơm lừng", pos: "noun", ex: ["Fragrant sweet yellow jackfruit pods are irresistible.", "Crispy dried jackfruit chips."], exVn: ["Những múi mít vàng thơm ngọt lịm thật khó chối từ.", "Mít sấy giòn rụm."] },
    { word: "mangosteen", phonetic: "/ˈmæŋɡəstiːn/", def: "A tropical fruit with thick purple rind and sweet white juicy segments.", defVn: "quả măng cụt (nữ hoàng trái cây)", pos: "noun", ex: ["Mangosteen is called the queen of fruits for its refreshing taste.", "Sweet white mangosteen segments."], exVn: ["Măng cụt được mệnh danh là nữ hoàng của các loài trái cây bởi vị ngon thanh mát.", "Những múi măng cụt trắng ngọt thanh."] },
    { word: "lychee", phonetic: "/ˈlaɪtʃiː/", def: "A small rounded fruit with sweet white scented flesh and rough red skin.", defVn: "quả vải thiều", pos: "noun", ex: ["Luc Ngan sweet red lychees are famous across Southeast Asia.", "Chilled lychees in sweet syrup."], exVn: ["Vải thiều Lục Ngạn ngọt lịm nức danh khắp Đông Nam Á.", "Vải thiều ướp lạnh ngâm si-rô ngọt ngào."] },
    { word: "papaya", phonetic: "/pəˈpaɪə/", def: "A tropical fruit shaped like an elongated melon, with orange flesh and small black seeds.", defVn: "quả đu đủ", pos: "noun", ex: ["Ripe orange papaya aids digestion and promotes glowing skin.", "Green papaya salad with dried beef."], exVn: ["Đu đủ chín màu cam giúp tiêu hóa tốt và cho làn da sáng mịn.", "Nộm đu đủ xanh bò khô."] },
    { word: "pomelo", phonetic: "/ˈpɑːməloʊ/", def: "A large citrus fruit with a thick rind and sweet, mild grapefruit flavor.", defVn: "quả bưởi ngọt mát", pos: "noun", ex: ["Juicy green pomelo from Ben Tre is enjoyed during Mid-Autumn.", "Dip sweet pomelo segments in chili salt."], exVn: ["Những múi bưởi da xanh mọng nước Bến Tre được thưởng thức dịp Trung Thu.", "Chấm múi bưởi ngọt vào muối ớt."] },
    { word: "orchard", phonetic: "/ˈɔːrtʃərd/", def: "A piece of land planted with fruit trees.", defVn: "vườn cây ăn trái", pos: "noun", ex: ["The Mekong Delta is filled with lush tropical fruit orchards.", "Pick fresh ripe fruit in the orchard."], exVn: ["Vùng Đồng bằng sông Cửu Long bạt ngàn những vườn cây ăn trái xum xuê.", "Hái quả chín tươi ngon ngay tại vườn."] },
    { word: "blossom", phonetic: "/ˈblɑːsəm/", def: "A flower or a mass of flowers, especially on a fruit tree.", defVn: "hoa nở rộ, hoa đào/mai", pos: "noun", ex: ["Pink peach blossoms and yellow apricot blossoms announce Tet.", "Cherry blossoms bloom in spring."], exVn: ["Hoa đào hồng và hoa mai vàng báo hiệu mùa Tết về.", "Hoa anh đào nở rộ vào mùa xuân."] },
    { word: "petal", phonetic: "/ˈpetl/", def: "Each of the segments of the corolla of a flower, which are modified leaves and typically colored.", defVn: "cánh hoa tươi thắm", pos: "noun", ex: ["Soft velvety rose petals fell gently onto the grass.", "Lotus petals floating on water."], exVn: ["Những cánh hoa hồng mềm như nhung rụng nhẹ nhàng trên thảm cỏ.", "Những cánh sen bồng bềnh trôi trên mặt nước."] }
  ],

  // Theme 22: Sức khỏe & Y tế (Health & Medical)
  t_basic_health_medical: [
    { word: "capsule", phonetic: "/ˈkæpsuːl/", def: "A small gelatinous case enclosing a dose of medication.", defVn: "viên thuốc nhộng", pos: "noun", ex: ["Swallow this vitamin capsule with a full glass of water.", "Fish oil capsules support heart health."], exVn: ["Uống viên thuốc nhộng vitamin này cùng một ly nước đầy nhé.", "Viên nang dầu cá tốt cho tim mạch."] },
    { word: "syrup", phonetic: "/ˈsɪrəp/", def: "A thick, sweet liquid containing medication.", defVn: "si-rô thuốc ho", pos: "noun", ex: ["Take two spoonfuls of herbal cough syrup before going to sleep.", "Children drink sweet herbal syrup."], exVn: ["Uống hai thìa si-rô ho thảo dược trước khi đi ngủ.", "Trẻ em uống si-rô thảo dược có vị ngọt."] },
    { word: "surgeon", phonetic: "/ˈsɜːrdʒən/", def: "A medical practitioner qualified to practice surgery.", defVn: "bác sĩ phẫu thuật", pos: "noun", ex: ["The skilled surgeon performed the delicate operation successfully.", "Surgeons wear sterile green scrubs."], exVn: ["Bác sĩ phẫu thuật lành nghề đã thực hiện ca phẫu thuật tinh xảo thành công.", "Các bác sĩ mổ mặc trang phục phẫu thuật tiệt trùng màu xanh."] },
    { word: "ambulance", phonetic: "/ˈæmbjələns/", def: "A vehicle equipped for taking sick or injured people to and from hospital.", defVn: "xe cứu thương, xe cấp cứu", pos: "noun", ex: ["Yield right of way immediately when you hear the ambulance siren.", "The ambulance rushed to the hospital."], exVn: ["Hãy nhường đường ngay lập tức khi nghe thấy tiếng còi xe cứu thương.", "Xe cấp cứu lao nhanh đến bệnh viện."] },
    { word: "thermometer", phonetic: "/θərˈmɑːmɪtər/", def: "An instrument for measuring and indicating temperature.", defVn: "nhiệt kế đo thân nhiệt", pos: "noun", ex: ["Use a digital forehead thermometer to check for fever.", "The thermometer reads 37 degrees Celsius."], exVn: ["Dùng nhiệt kế điện tử đo trán để kiểm tra xem có bị sốt không.", "Nhiệt kế hiển thị 37 độ C."] },
    { word: "ointment", phonetic: "/ˈɔɪntmənt/", def: "A smooth oily substance that is rubbed on the skin for medicinal purposes.", defVn: "thuốc mỡ bôi da", pos: "noun", ex: ["Apply soothing antibacterial ointment to the small scrape.", "Herbal ointment relieves muscle aches."], exVn: ["Bôi thuốc mỡ kháng khuẩn làm dịu lên vết trầy xước nhỏ.", "Thuốc mỡ thảo dược làm dịu đau nhức cơ."] },
    { word: "wheelchair", phonetic: "/ˈwiːltʃer/", def: "A chair fitted with wheels for use as a means of transport by a person who is unable to walk.", defVn: "xe lăn y tế cho người bệnh", pos: "noun", ex: ["Hospitals provide smooth wheelchair ramps at all entrances.", "He pushed the comfortable wheelchair gently."], exVn: ["Bệnh viện bố trí các đường dốc thoải cho xe lăn ở tất cả các lối vào.", "Anh ấy đẩy chiếc xe lăn êm ái thật nhẹ nhàng."] },
    { word: "recovery", phonetic: "/rɪˈkʌvəri/", def: "A return to a normal state of health, mind, or strength.", defVn: "sự hồi phục sức khỏe", pos: "noun", ex: ["We wish you a very speedy and complete recovery!", "Nutritious food speeds up recovery."], exVn: ["Chúc bạn sớm hồi phục sức khỏe thật nhanh chóng và trọn vẹn!", "Thức ăn bổ dưỡng giúp đẩy nhanh quá trình hồi phục."] },
    { word: "hygiene", phonetic: "/ˈhaɪdʒiːn/", def: "Conditions or practices conducive to maintaining health and preventing disease.", defVn: "vệ sinh phòng bệnh", pos: "noun", ex: ["Proper hand hygiene prevents the spread of seasonal illnesses.", "Dental hygiene protects healthy teeth."], exVn: ["Giữ vệ sinh tay đúng cách giúp ngăn ngừa sự lây lan của các bệnh theo mùa.", "Vệ sinh răng miệng bảo vệ hàm răng luôn chắc khỏe."] },
    { word: "symptom", phonetic: "/ˈsɪmptəm/", def: "A physical or mental feature which indicates a condition of disease.", defVn: "triệu chứng của bệnh", pos: "noun", ex: ["A mild fever and runny nose are common flu symptoms.", "Describe your symptoms to the doctor."], exVn: ["Sốt nhẹ và sổ mũi là những triệu chứng cảm cúm thông thường.", "Hãy mô tả các triệu chứng của bạn cho bác sĩ biết."] }
  ],

  // Theme 23: Dụng cụ nhà bếp (Kitchen Utensils)
  t_basic_kitchen_utensils: [
    { word: "grater", phonetic: "/ˈɡreɪtər/", def: "A device having a surface covered with holes edged by sharp edges, used for grating cheese and vegetables.", defVn: "cái nạo, dụng cụ bào sợi", pos: "noun", ex: ["Use the stainless steel box grater to shred carrots for salad.", "Grate fresh cheese with the grater."], exVn: ["Dùng cái nạo inox để bào sợi cà rốt làm món nộm.", "Bào phô mai tươi bằng dụng cụ bào."] },
    { word: "peeler", phonetic: "/ˈpiːlər/", def: "A device for removing the skin from fruit and vegetables.", defVn: "dao nạo vỏ củ quả", pos: "noun", ex: ["Peel potato and cucumber skins quickly with the sharp vegetable peeler.", "A ceramic peeler stays sharp."], exVn: ["Gọt vỏ khoai tây và dưa chuột nhanh chóng bằng dao nạo củ quả sắc bén.", "Dao nạo bằng gốm sứ luôn giữ được độ sắc."] },
    { word: "whisk", phonetic: "/wɪsk/", def: "A utensil for whipping eggs or cream.", defVn: "cây đánh trứng, phới lồng", pos: "noun", ex: ["Whisk fresh eggs and milk until light and fluffy.", "Use a wire whisk for pancake batter."], exVn: ["Dùng phới lồng đánh trứng tươi và sữa cho đến khi bông xốp.", "Dùng phới đánh bột làm bánh kếp."] },
    { word: "ladle", phonetic: "/ˈleɪdl/", def: "A large long-handled spoon with a cup-shaped bowl, used for serving soup.", defVn: "chiếc muôi múc canh lớn", pos: "noun", ex: ["Use a soup ladle to serve steaming hot pho broth into bowls.", "Scoop delicious soup with the ladle."], exVn: ["Dùng muôi múc canh để múc nước dùng phở nóng hổi vào từng bát.", "Múc món súp thơm ngon bằng chiếc muôi lớn."] },
    { word: "colander", phonetic: "/ˈkɑːləndər/", def: "A perforated bowl used to strain off liquid from food.", defVn: "cái rổ lọc, chậu rửa rau có lỗ", pos: "noun", ex: ["Drain boiled noodles thoroughly in the stainless colander.", "Rinse fresh herbs in the colander."], exVn: ["Đổ ráo nước mì luộc trong chiếc rổ lọc bằng inox.", "Rửa rau thơm trong rổ thoát nước."] },
    { word: "tongs", phonetic: "/tɑːŋz/", def: "An instrument with two movable arms that are joined at one end, used for picking up and holding things.", defVn: "cái kẹp gắp thức ăn", pos: "noun", ex: ["Use metal barbecue tongs to turn sizzling grilled meat skewers.", "Grip hot corn with kitchen tongs."], exVn: ["Dùng kẹp nướng kim loại để lật những xiên thịt nướng xèo xèo.", "Gắp bắp ngô nóng bằng kẹp gắp nhà bếp."] },
    { word: "spatula", phonetic: "/ˈspætʃələ/", def: "An implement with a broad, flat, blunt blade, used for mixing and spreading things.", defVn: "xẻng lật thức ăn, phới dẹt", pos: "noun", ex: ["Flip the golden pancake gently with a silicone spatula.", "Scrape cake batter with the spatula."], exVn: ["Lật chiếc bánh kếp vàng ươm nhẹ nhàng bằng xẻng lật silicon.", "Vét sạch bột bánh bằng phới dẹt."] },
    { word: "rolling pin", phonetic: "/ˈroʊlɪŋ pɪn/", def: "A cylinder rolled over pastry or dough to flatten or shape it.", defVn: "cây cán bột làm bánh", pos: "noun", ex: ["Roll pizza dough into a thin circle using the wooden rolling pin.", "Dust the rolling pin with flour."], exVn: ["Cán bột bánh pizza thành hình tròn mỏng bằng cây cán bột gỗ.", "Rắc một lớp bột khô lên cây cán bột."] },
    { word: "apron", phonetic: "/ˈeɪprən/", def: "A protective garment worn over the front of one's clothes and tied at the back.", defVn: "chiếc tạp dề làm bếp", pos: "noun", ex: ["Tie your cotton kitchen apron before cooking to keep clothes clean.", "She wore a cheerful floral apron."], exVn: ["Thắt chiếc tạp dề cotton trước khi nấu nướng để giữ quần áo luôn sạch sẽ.", "Cô ấy đeo chiếc tạp dề hoa tươi tắn."] },
    { word: "toaster", phonetic: "/ˈtoʊstər/", def: "An electrical device for making toast.", defVn: "máy nướng bánh mì lát", pos: "noun", ex: ["Pop two slices of whole wheat bread into the morning toaster.", "Crispy golden toast from the toaster."], exVn: ["Thả hai lát bánh mì nguyên cám vào máy nướng bánh mì buổi sáng.", "Những lát bánh mì nướng giòn rụm từ máy nướng."] }
  ]
};
