module.exports = {
  // Theme 31: Đo lường & Kích cỡ (Measurements & Sizes)
  t_basic_measurements_sizes: [
    { word: "millimeter", phonetic: "/ˈmɪlɪmiːtər/", def: "One thousandth of a meter (mm).", defVn: "mi-li-mét (mm)", pos: "noun", ex: ["A tiny rain gauge measures water in millimeters.", "The thickness is two millimeters."], exVn: ["Một chiếc máy đo lượng mưa nhỏ đo nước theo từng mi-li-mét.", "Độ dày là 2 mi-li-mét."] },
    { word: "milliliter", phonetic: "/ˈmɪlɪliːtər/", def: "One thousandth of a liter (ml).", defVn: "mi-li-lít (ml)", pos: "noun", ex: ["Pour fifty milliliters of fresh milk into the cup.", "A 500-milliliter water bottle."], exVn: ["Rót 50 ml sữa tươi vào tách.", "Chai nước dung tích 500 ml."] },
    { word: "ton", phonetic: "/tʌn/", def: "A unit of weight equal to 1,000 kilograms (metric ton).", defVn: "tấn (1.000 kg)", pos: "noun", ex: ["The cargo vessel can transport thousands of tons of grain.", "Heavy machinery weighing five tons."], exVn: ["Tàu chở hàng có thể vận chuyển hàng ngàn tấn ngũ cốc.", "Máy móc hạng nặng nặng 5 tấn."] },
    { word: "inch", phonetic: "/ɪntʃ/", def: "A unit of linear measure equal to 2.54 cm.", defVn: "inch (đơn vị đo chiều dài)", pos: "noun", ex: ["This laptop features a compact fourteen-inch screen.", "A ten-inch pizza."], exVn: ["Chiếc laptop này sở hữu màn hình 14 inch nhỏ gọn.", "Một chiếc bánh pizza 10 inch."] },
    { word: "volume", phonetic: "/ˈvɑːljuːm/", def: "The amount of space that a substance or object occupies.", defVn: "thể tích, dung tích chứa", pos: "noun", ex: ["Calculate the cubic volume of the water storage tank.", "A container with large volume."], exVn: ["Tính thể tích khối của bể chứa nước.", "Một thùng chứa có dung tích lớn."] },
    { word: "capacity", phonetic: "/kəˈpæsəti/", def: "The maximum amount that something can contain.", defVn: "sức chứa tối đa, dung lượng", pos: "noun", ex: ["The conference hall has a seating capacity of three hundred guests.", "A large fuel tank capacity."], exVn: ["Hội trường có sức chứa 300 chỗ ngồi cho khách.", "Dung tích bình xăng lớn."] },
    { word: "gigantic", phonetic: "/dʒaɪˈɡæntɪk/", def: "Of very great size or extent; huge or enormous.", defVn: "khổng lồ, to lớn kỳ vĩ", pos: "adj", ex: ["Ha Long Bay has gigantic limestone mountains rising from the sea.", "A gigantic cruise ship."], exVn: ["Vịnh Hạ Long có những ngọn núi đá vôi khổng lồ mọc lên từ biển.", "Một con tàu du lịch khổng lồ."] },
    { word: "miniature", phonetic: "/ˈmɪnətʃər/", def: "Of a much smaller size than normal; very small.", defVn: "thu nhỏ, tí hon xinh xắn", pos: "adj", ex: ["Bat Trang artisans craft delightful miniature ceramic teapots.", "A miniature garden on the balcony."], exVn: ["Các nghệ nhân Bát Tràng tạo tác những chiếc ấm trà gốm tí hon xinh xắn.", "Một khu vườn thu nhỏ trên ban công."] },
    { word: "thickness", phonetic: "/ˈθɪknəs/", def: "The distance through an object, as distinct from width or height.", defVn: "độ dày, bề dày", pos: "noun", ex: ["Check the thickness of the warm wool blanket before buying.", "Wooden board of one-inch thickness."], exVn: ["Kiểm tra độ dày của chiếc chăn len ấm trước khi mua nhé.", "Tấm ván gỗ có độ dày một inch."] },
    { word: "perimeter", phonetic: "/pəˈrɪmɪtər/", def: "The continuous line forming the boundary of a closed geometric figure.", defVn: "chu vi hình học", pos: "noun", ex: ["Calculate the total outer perimeter of the rectangular soccer field.", "Trees planted along the park perimeter."], exVn: ["Tính chu vi vòng ngoài của sân bóng đá hình chữ nhật.", "Cây cối được trồng dọc theo chu vi công viên."] }
  ],

  // Theme 32: Dụng cụ & Sửa chữa (Tools & Repair)
  t_basic_tools_repair: [
    { word: "wrench", phonetic: "/rentʃ/", def: "A tool used for gripping and turning nuts or bolts; spanner.", defVn: "cờ-lê vặn ốc vít", pos: "noun", ex: ["Tighten the loose bicycle pedal securely with an adjustable wrench.", "A set of steel wrenches."], exVn: ["Xiết chặt bàn đạp xe đạp bị lỏng bằng chiếc cờ-lê có thể điều chỉnh.", "Một bộ cờ-lê bằng thép."] },
    { word: "screwdriver", phonetic: "/ˈskruːdraɪvər/", def: "A tool with a flattened or cross-shaped tip that fits into the head of a screw to turn it.", defVn: "tua-vít vặn ốc", pos: "noun", ex: ["Use a Phillips screwdriver to tighten the loose cabinet handle.", "A magnetic tip screwdriver."], exVn: ["Dùng tua-vít 4 cạnh để xiết chặt tay nắm tủ bị lỏng.", "Chiếc tua-vít có đầu nam châm hút ốc."] },
    { word: "pliers", phonetic: "/ˈplaɪərz/", def: "Pincers with parallel, flat, and typically serrated surfaces, used for gripping small objects or bending wire.", defVn: "chiếc kìm bấm, kìm điện", pos: "noun", ex: ["Use insulated pliers to bend and cut thin electrical wire safely.", "Grip the nail head with pliers."], exVn: ["Dùng kìm bọc cách điện để uốn và cắt dây điện mảnh an toàn.", "Kẹp chặt đầu đinh bằng kìm."] },
    { word: "drill", phonetic: "/drɪl/", def: "A tool or machine with a rotating cutting tip, used for making holes.", defVn: "máy khoan tường / gỗ", pos: "noun", ex: ["Drill a neat hole into the wall to hang the family picture frame.", "A cordless electric power drill."], exVn: ["Khoan một lỗ gọn trên tường để treo khung ảnh gia đình.", "Chiếc máy khoan điện cầm tay không dây."] },
    { word: "toolbox", phonetic: "/ˈtuːlbɑːks/", def: "A box or container for keeping tools in.", defVn: "hộp đựng đồ nghề sửa chữa", pos: "noun", ex: ["Keep your hammers, nails, and screwdrivers organized in a sturdy metal toolbox.", "Carry the portable toolbox."], exVn: ["Cất búa, đinh và tua-vít ngăn nắp trong hộp đồ nghề kim loại chắc chắn.", "Xách theo hộp đồ nghề di động."] },
    { word: "ladder", phonetic: "/ˈlædər/", def: "A structure consisting of a series of bars or steps between two upright lengths of wood, metal, or rope.", defVn: "chiếc thang chữ A, thang leo", pos: "noun", ex: ["Climb the sturdy aluminum folding ladder to replace the ceiling light bulb.", "Hold the ladder steady at the base."], exVn: ["Leo chiếc thang gấp nhôm chắc chắn để thay bóng đèn trần.", "Giữ chân thang thật vững vàng nhé."] },
    { word: "measuring tape", phonetic: "/ˈmeʒərɪŋ teɪp/", def: "A ribbon of cloth, plastic, or flexible metal with linear-measurement markings.", defVn: "thước dây cuộn rút", pos: "noun", ex: ["Pull out the metal measuring tape to check window curtain dimensions.", "A five-meter retractable measuring tape."], exVn: ["Kéo thước dây kim loại ra để đo kích thước rèm cửa sổ.", "Thước dây cuộn rút tự động dài 5 mét."] },
    { word: "sandpaper", phonetic: "/ˈsændpeɪpər/", def: "Paper with sand or another abrasive stuck to it, used for smoothing or polishing woodwork.", defVn: "giấy ráp, giấy nhám đánh bóng", pos: "noun", ex: ["Smooth the rough wooden table edges with fine sandpaper before painting.", "Rub sandpaper along the wood grain."], exVn: ["Đánh bóng các cạnh bàn gỗ thô ráp bằng giấy ráp mịn trước khi sơn.", "Chà giấy nhám dọc theo thớ gỗ."] },
    { word: "nail", phonetic: "/neɪl/", def: "A small metal spike with a broadened flat head, driven into wood with a hammer.", defVn: "cây đinh đóng tường/gỗ", pos: "noun", ex: ["Drive the steel nail firmly into the wooden plank with a hammer.", "A box of assorted nails."], exVn: ["Đóng chiếc đinh thép chắc chắn vào thanh ván gỗ bằng búa.", "Một hộp đinh các loại."] },
    { word: "screw", phonetic: "/skruː/", def: "A short, slender, sharp-pointed metal pin with a raised helical thread running around it.", defVn: "ốc vít kim loại có rãnh xoắn", pos: "noun", ex: ["Fasten the shelf bracket with stainless steel wood screws.", "Turn the screw clockwise to tighten."], exVn: ["Bắt chặt giá đỡ kệ bằng các vít gỗ inox.", "Vặn ốc vít theo chiều kim đồng hồ để siết chặt."] }
  ],

  // Theme 33: Thiên tai & Thời tiết xấu (Severe Weather)
  t_basic_severe_weather: [
    { word: "typhoon", phonetic: "/taɪˈfuːn/", def: "A tropical storm in the region of the Indian or western Pacific oceans.", defVn: "cơn bão nhiệt đới dữ dội", pos: "noun", ex: ["Coastal residents reinforced their roofs securely before the super typhoon arrived.", "Typhoon season occurs in late autumn."], exVn: ["Người dân ven biển gia cố mái nhà chắc chắn trước khi siêu bão đổ bộ.", "Mùa bão thường diễn ra vào cuối mùa thu."] },
    { word: "lightning", phonetic: "/ˈlaɪtnɪŋ/", def: "The occurrence of a natural electrical discharge of very short duration between a cloud and the ground.", defVn: "tia sét, ánh chớp xé trời", pos: "noun", ex: ["Spectacular flashes of purple lightning lit up the stormy evening sky.", "Stay indoors during lightning storms."], exVn: ["Những tia sét màu tím ngoạn mục thắp sáng bầu trời đêm giông bão.", "Hãy ở trong nhà an toàn trong cơn giông sét."] },
    { word: "thunder", phonetic: "/ˈθʌndər/", def: "A loud rumbling or crashing noise heard after a lightning flash.", defVn: "tiếng sấm ầm ầm", pos: "noun", ex: ["Deep rolling thunder rattled the bedroom windowpanes.", "Count the seconds between lightning and thunder."], exVn: ["Tiếng sấm rền vang rung chuyển cả những ô cửa kính phòng ngủ.", "Đếm số giây giữa lúc thấy chớp và nghe tiếng sấm."] },
    { word: "flood", phonetic: "/flʌd/", def: "An overflowing of a large amount of water beyond its normal confines.", defVn: "trận lũ lụt, ngập úng", pos: "noun", ex: ["Rescue boats evacuated flooded central provinces safely.", "Heavy seasonal rains caused river floods."], exVn: ["Những chiếc thuyền cứu hộ đã sơ tán bà con các tỉnh miền Trung bị ngập lụt an toàn.", "Mưa lớn theo mùa đã gây ra lũ lụt trên các dòng sông."] },
    { word: "drought", phonetic: "/draʊt/", def: "A prolonged period of abnormally low rainfall, leading to a shortage of water.", defVn: "nạn hạn hán kéo dài", pos: "noun", ex: ["Farmers conserve fresh water carefully during prolonged dry season droughts.", "Irrigation systems protect crops against drought."], exVn: ["Bà con nông dân tiết kiệm nước ngọt cẩn thận trong đợt hạn hán mùa khô kéo dài.", "Hệ thống tưới tiêu bảo vệ mùa màng trước nạn hạn hán."] },
    { word: "landslide", phonetic: "/ˈlændslaɪd/", def: "The sliding down of a mass of earth or rock from a mountain or cliff.", defVn: "sạt lở đất đá trên sườn núi", pos: "noun", ex: ["Highway warnings alerted drivers about potential mountain landslides after heavy rain.", "Plant trees on slopes to prevent landslides."], exVn: ["Biển cảnh báo trên quốc lộ nhắc nhở tài xế về nguy cơ sạt lở núi sau mưa lớn.", "Trồng cây trên sườn đồi để ngăn ngừa sạt lở đất."] },
    { word: "shelter", phonetic: "/ˈʃeltər/", def: "A place giving temporary protection from bad weather or danger.", defVn: "nơi trú ẩn an toàn, nhà tránh bão", pos: "noun", ex: ["Seek sturdy concrete shelter immediately when heavy storm winds strike.", "An emergency storm shelter."], exVn: ["Tìm nơi trú ẩn kiên cố bằng bê tông ngay khi gió bão mạnh tràn về.", "Một khu nhà tránh bão khẩn cấp."] },
    { word: "evacuation", phonetic: "/ɪˌvækjuˈeɪʃn/", def: "The action of evacuating a person or a place.", defVn: "sự sơ tán khẩn cấp đến nơi an toàn", pos: "noun", ex: ["Local authorities coordinated a peaceful evacuation before the floodwaters rose.", "Follow the official evacuation route."], exVn: ["Chính quyền địa phương đã điều phối cuộc sơ tán trật tự trước khi nước lũ dâng cao.", "Đi theo lộ trình sơ tán chính thức."] },
    { word: "tsunami", phonetic: "/tsuːˈnɑːmi/", def: "A long high sea wave caused by an earthquake, submarine landslide, or other disturbance.", defVn: "sóng thần đại dương khổng lồ", pos: "noun", ex: ["Early warning ocean buoys detect deep underwater tsunami waves promptly.", "Move to high ground during tsunami alerts."], exVn: ["Phao cảnh báo sớm ngoài đại dương phát hiện kịp thời các đợt sóng thần ngầm dưới nước.", "Di chuyển lên vùng đất cao khi có cảnh báo sóng thần."] },
    { word: "wildfire", phonetic: "/ˈwaɪldfaɪər/", def: "A large, destructive fire that spreads quickly over woodland or brush.", defVn: "cháy rừng, hỏa hoạn tự nhiên", pos: "noun", ex: ["Firefighting helicopters dropped water to contain the dry summer wildfire.", "Prevent wildfires by never leaving campfires unattended."], exVn: ["Trực thăng cứu hỏa trút nước để khống chế đám cháy rừng mùa khô.", "Ngăn ngừa cháy rừng bằng cách không bao giờ để lửa trại cháy mà không trông coi."] }
  ],

  // Theme 34: Địa hình & Cảnh quan (Landforms & Landscapes)
  t_basic_landforms_landscapes: [
    { word: "canyon", phonetic: "/ˈkænjən/", def: "A deep gorge, typically one with a river flowing through it.", defVn: "hẻm núi sâu thăm thẳm (như hẻm Tu Sản)", pos: "noun", ex: ["Tu San Canyon in Ha Giang is Southeast Asia's deepest spectacular canyon.", "Cruise through the emerald canyon river."], exVn: ["Hẻm Tu Sản ở Hà Giang là hẻm núi sâu kỳ vĩ bậc nhất Đông Nam Á.", "Du thuyền dọc dòng sông xanh ngọc bích giữa hẻm núi."] },
    { word: "cliff", phonetic: "/klɪf/", def: "A steep high face of rock, especially on a coast.", defVn: "vách đá dựng đứng cheo leo", pos: "noun", ex: ["Dramatic limestone cliffs rise majestically out of the blue waters of Lan Ha Bay.", "Stand safely behind the cliff railing."], exVn: ["Những vách đá vôi kỳ vĩ dựng đứng sừng sững trên làn nước xanh vịnh Lan Hạ.", "Đứng an toàn phía sau lan can vách đá nhé."] },
    { word: "cave", phonetic: "/keɪv/", def: "A natural underground space large enough for a human to enter.", defVn: "hang động kỳ vĩ (như Sơn Đoòng)", pos: "noun", ex: ["Son Doong Cave in Quang Binh is the largest known natural cave on planet Earth.", "Marvel at ancient stalactites inside the cave."], exVn: ["Hang Sơn Đoòng ở Quảng Bình là hang động tự nhiên lớn nhất từng được biết đến trên Trái Đất.", "Kinh ngạc trước những khối nhũ đá cổ kính bên trong hang."] },
    { word: "plateau", phonetic: "/plæˈtoʊ/", def: "An area of relatively level high ground.", defVn: "cao nguyên lộng gió (như Đồng Văn)", pos: "noun", ex: ["Dong Van Karst Plateau is recognized as a UNESCO Global Geopark.", "Cool fresh breezes sweep across the plateau."], exVn: ["Cao nguyên đá Đồng Văn được công nhận là Công viên địa chất toàn cầu UNESCO.", "Những làn gió mát lành thổi qua khắp cao nguyên."] },
    { word: "volcano", phonetic: "/vɑːlˈkeɪnoʊ/", def: "A mountain or hill having a crater through which lava, rock fragments, and hot vapor are erupted.", defVn: "ngọn núi lửa (đã ngủ yên)", pos: "noun", ex: ["Ly Son Island was formed millions of years ago by ancient volcanic eruptions.", "A dormant volcano crater lake."], exVn: ["Đảo Lý Sơn được kiến tạo hàng triệu năm trước từ những đợt phun trào núi lửa cổ.", "Hồ nước trên miệng núi lửa đã ngủ yên."] },
    { word: "desert", phonetic: "/ˈdezərt/", def: "A dry, barren area of land, especially one relatively uninhabited.", defVn: "sa mạc, đồi cát mênh mông", pos: "noun", ex: ["Mui Ne red and white sand dunes resemble a miniature desert beside the ocean.", "Camels walk across vast desert dunes."], exVn: ["Những đồi cát đỏ và cát trắng ở Mũi Né trông như một sa mạc thu nhỏ bên bờ đại dương.", "Những chú lạc đà thong dong bước qua đồi cát sa mạc."] },
    { word: "oasis", phonetic: "/oʊˈeɪsɪs/", def: "A fertile spot in a desert, where water is found.", defVn: "ốc đảo xanh tươi giữa sa mạc", pos: "noun", ex: ["Date palms and clear freshwater springs thrive around the desert oasis.", "Rest at the tranquil green oasis."], exVn: ["Cây chà là và những dòng suối nước ngọt trong vắt xanh tươi quanh ốc đảo sa mạc.", "Nghỉ ngơi tại ốc đảo xanh bình yên."] },
    { word: "waterfall", phonetic: "/ˈwɔːtərfɔːl/", def: "A cascade of water falling from a height.", defVn: "thác nước hùng vĩ (như Bản Giốc)", pos: "noun", ex: ["Ban Gioc Waterfall cascades thunderously in four majestic tiers amidst green mountains.", "Rainbows shimmer in the waterfall mist."], exVn: ["Thác Bản Giốc đổ ào ạt thành 4 tầng hùng vĩ giữa núi rừng xanh thẳm.", "Cầu vồng lung linh trong làn sương nước của thác."] },
    { word: "peninsula", phonetic: "/pəˈnɪnsələ/", def: "A piece of land almost surrounded by water or projecting out into a body of water.", defVn: "bán đảo nhô ra biển", pos: "noun", ex: ["Son Tra Peninsula in Da Nang is famous for green forests and rare langurs.", "Drive along the scenic peninsula coast."], exVn: ["Bán đảo Sơn Trà ở Đà Nẵng nổi tiếng với rừng xanh và loài voọc quý hiếm.", "Lái xe dọc bờ biển bán đảo nên thơ."] },
    { word: "glacier", phonetic: "/ˈɡleɪʃər/", def: "A slowly moving mass or river of ice formed by the accumulation and compaction of snow.", defVn: "sông băng, tảng băng vĩnh cửu", pos: "noun", ex: ["Massive blue glaciers carve deep valleys through polar mountains.", "Ancient ice stored inside the glacier."], exVn: ["Những dòng sông băng xanh khổng lồ tạc nên những thung lũng sâu qua các rặng núi vùng cực.", "Băng cổ kính được lưu giữ bên trong sông băng."] }
  ],

  // Theme 35: Sinh vật biển & Đại dương (Marine Life)
  t_basic_marine_life: [
    { word: "whale", phonetic: "/weɪl/", def: "A very large marine mammal with a streamlined body, a blowhole on top of the head, and horizontal tail flukes.", defVn: "cá voi khổng lồ (loài cá được ngư dân tôn kính)", pos: "noun", ex: ["Fishermen along the central coast revere the gentle blue whale as a protector.", "Whales migrate across deep oceans."], exVn: ["Ngư dân dọc dải duyên hải miền Trung tôn kính cá voi hiền hòa như vị thần bảo hộ.", "Cá voi di cư qua các vùng đại dương sâu."] },
    { word: "shark", phonetic: "/ʃɑːrk/", def: "A long-bodied chiefly marine fish, the majority being predatory.", defVn: "cá mập đại dương", pos: "noun", ex: ["Harmless reef sharks swim gracefully around colorful coral reefs.", "Sharks play a vital role in marine ecosystems."], exVn: ["Những chú cá mập rạn san hô vô hại bơi lượn duyên dáng quanh rạn san hô rực rỡ.", "Cá mập đóng vai trò sống còn trong hệ sinh thái biển."] },
    { word: "octopus", phonetic: "/ˈɑːktəpʊs/", def: "An eight-armed cephalopod mollusk with a soft body and sucker-bearing arms.", defVn: "bạch tuộc thông minh (8 xúc tu)", pos: "noun", ex: ["An octopus can change its skin color and texture in milliseconds to blend into rocks.", "Grilled spicy marinated octopus."], exVn: ["Bạch tuộc có thể biến đổi màu sắc và bề mặt da chỉ trong một phần nghìn giây để ẩn mình vào vách đá.", "Bạch tuộc nướng sa tế cay đậm đà."] },
    { word: "squid", phonetic: "/skwɪd/", def: "An elongated, fast-swimming cephalopod mollusk with ten arms.", defVn: "con mực ống, mực nang", pos: "noun", ex: ["Fresh steamed squid stuffed with ginger and scallions is a coastal delicacy.", "Night fishing for squid with green lights."], exVn: ["Mực ống tươi hấp gừng hành là món đặc sản nức lòng người sành ăn miền biển.", "Đi câu mực đêm dưới ánh đèn xanh."] },
    { word: "jellyfish", phonetic: "/ˈdʒelifɪʃ/", def: "A free-swimming marine coelenterate with a jellylike bell-shaped body.", defVn: "con sứa biển mềm mại", pos: "noun", ex: ["Translucent jellyfish drift gracefully through the deep blue ocean current.", "Crispy jellyfish salad with herbs."], exVn: ["Những chú sứa biển trong suốt trôi bồng bềnh duyên dáng theo dòng hải lưu xanh thẳm.", "Gỏi sứa giòn sần sật trộn rau thơm."] },
    { word: "seahorse", phonetic: "/ˈsiːhɔːrs/", def: "A small marine fish with an upright posture, horse-like head, and prehensile tail.", defVn: "cá ngựa, hải mã", pos: "noun", ex: ["Tiny yellow seahorses anchor their tails to swaying seagrass beds.", "Seahorses mate for life."], exVn: ["Những chú cá ngựa vàng nhỏ xíu dùng chiếc đuôi móc vào những thảm cỏ biển đung đưa.", "Cá ngựa là loài kết đôi trọn đời."] },
    { word: "lobster", phonetic: "/ˈlɑːbstər/", def: "A large marine crustacean with a cylindrical body and large edible claws.", defVn: "tôm hùm thượng hạng (Bình Ba)", pos: "noun", ex: ["Binh Ba Island is renowned as the lobster island of Vietnam.", "Grilled cheese lobster platter."], exVn: ["Đảo Bình Ba được mệnh danh là vương quốc tôm hùm của Việt Nam.", "Đĩa tôm hùm nướng phô mai béo ngậy."] },
    { word: "starfish", phonetic: "/ˈstɑːrfɪʃ/", def: "A marine echinoderm with five or more radiating arms; sea star.", defVn: "sao biển rực rỡ sắc màu", pos: "noun", ex: ["Red starfish rest peacefully on the white sands of Starfish Beach in Phu Quoc.", "Starfish can regenerate lost arms."], exVn: ["Những chú sao biển đỏ nằm yên bình trên bãi cát trắng mịn Bãi Sao ở Phú Quốc.", "Sao biển có thể tự tái tạo lại cánh tay bị đứt."] },
    { word: "coral", phonetic: "/ˈkɔːrəl/", def: "A hard stony substance formed by the skeletons of tiny colonial marine invertebrates.", defVn: "rạn san hô rực rỡ đáy biển", pos: "noun", ex: ["Snorkelers admire colorful living coral reefs in the clear waters of Cu Lao Cham.", "Protect fragile coral from pollution."], exVn: ["Khách lặn biển chiêm ngưỡng những rạn san hô sống rực rỡ sắc màu tại Cù Lao Chàm.", "Bảo vệ các rạn san hô mong manh khỏi ô nhiễm."] },
    { word: "seaweed", phonetic: "/ˈsiːwiːd/", def: "Large algae growing in the sea or on rocks below the high-water mark.", defVn: "rong biển, tảo biển giàu dinh dưỡng", pos: "noun", ex: ["Nutritious seaweed soup cooked with tofu is refreshing and healthy.", "Crispy roasted seasoned seaweed."], exVn: ["Canh rong biển bổ dưỡng nấu cùng đậu hũ rất thanh mát và tốt cho sức khỏe.", "Rong biển tẩm gia vị sấy giòn rụm."] }
  ]
};
