module.exports = {
  // Theme 51: Ánh sáng & Thị giác (Light & Visual Effects)
  t_basic_light_visual_effects: [
    { word: "twinkle", phonetic: "/ˈtwɪŋkl/", def: "Shine with a gleam that changes constantly from bright to faint.", defVn: "lấp lánh lung linh (như sao trời)", pos: "verb", ex: ["Countless silver stars twinkle brightly in the cloudless midnight sky.", "Her eyes twinkle with happiness."], exVn: ["Vô số vì sao bạc lấp lánh lung linh trên bầu trời đêm không một gợn mây.", "Đôi mắt cô ấy ánh lên niềm hạnh phúc lấp lánh."] },
    { word: "neon", phonetic: "/ˈniːɑːn/", def: "Fluorescent lighting tubes containing neon gas.", defVn: "đèn nê-ông rực rỡ phố đêm", pos: "noun", ex: ["Vibrant colorful neon signs brighten the bustling walking streets of Saigon.", "Glowing neon lights at night."], exVn: ["Những biển hiệu đèn nê-ông rực rỡ sắc màu thắp sáng các con phố đi bộ sầm uất ở Sài Gòn.", "Ánh đèn nê-ông rực rỡ trong đêm."] },
    { word: "silhouette", phonetic: "/ˌsɪluˈet/", def: "The dark shape and outline of someone or something visible against a lighter background.", defVn: "hình bóng đen ngược sáng (silhouette)", pos: "noun", ex: ["The silhouette of the traditional fisherman casting his net at sunrise was stunning.", "A tree silhouette against the orange sunset."], exVn: ["Hình bóng đen ngược sáng của người ngư dân quăng chài lúc bình minh đẹp ngỡ ngàng.", "Hình bóng cây in trên nền hoàng hôn màu cam."] },
    { word: "lantern", phonetic: "/ˈlæntərn/", def: "A lamp with a transparent case protecting the flame or electric bulb, and typically having a handle.", defVn: "chiếc đèn lồng phố cổ Hội An", pos: "noun", ex: ["Hoi An Old Town glows enchantingly under thousands of colorful handmade silk lanterns.", "Release paper lotus lanterns on the river."], exVn: ["Phố cổ Hội An bừng sáng mê hoặc dưới hàng ngàn chiếc đèn lồng lụa thủ công rực rỡ sắc màu.", "Thả đèn hoa đăng giấy bồng bềnh trên sông."] },
    { word: "rainbow", phonetic: "/ˈreɪnboʊ/", def: "An arch of colors formed in the sky in certain circumstances, caused by the refraction of the sun's rays in rain.", defVn: "cầu vồng 7 sắc rực rỡ", pos: "noun", ex: ["A vivid seven-colored rainbow appeared arched across the mountain after the sun shower.", "Follow the rainbow across the valley."], exVn: ["Chiếc cầu vồng bảy sắc rực rỡ hiện ra uốn cong qua dãy núi sau cơn mưa rào ngập nắng.", "Đi theo dải cầu vồng bắc qua thung lũng."] },
    { word: "glimmer", phonetic: "/ˈɡlɪmər/", def: "Shine faintly with a wavering light.", defVn: "ánh sáng le lói, lấp lánh mờ ảo", pos: "verb", ex: ["A faint glimmer of candle light guided them through the dark wooden hallway.", "A glimmer of hope in difficult times."], exVn: ["Một ánh nến le lói mờ ảo dẫn lối họ bước qua hành lang gỗ tối.", "Một tia hy vọng le lói giữa lúc gian khó."] },
    { word: "ray", phonetic: "/reɪ/", def: "Each of the lines in which light (and heat) may seem to stream from the sun or any luminous body.", defVn: "tia nắng ban mai, chùm sáng", pos: "noun", ex: ["Golden sun rays filtered warmly through the lush canopy of green trees.", "A laser light ray."], exVn: ["Những tia nắng vàng ban mai xuyên qua tán cây xanh tươi rợp bóng ấm áp.", "Một tia sáng la-de."] }
  ],

  // Theme 53: Dịch vụ & Tiện ích (Convenience Services)
  t_basic_convenience_services: [
    { word: "drugstore", phonetic: "/ˈdrʌɡstɔːr/", def: "A pharmacy which also sells toiletries and other articles.", defVn: "hiệu thuốc tây, tiệm thuốc", pos: "noun", ex: ["The neighborhood 24-hour drugstore sells medicines and medical supplies.", "Buy cough drops at the drugstore."], exVn: ["Hiệu thuốc tây 24/7 trong khu phố bán thuốc và các vật dụng y tế.", "Mua kẹo ngậm ho tại hiệu thuốc."] },
    { word: "florist", phonetic: "/ˈflɔːrɪst/", def: "A person who sells and arranges cut flowers; flower shop.", defVn: "tiệm hoa tươi, người bán hoa", pos: "noun", ex: ["The talented florist arranged a bouquet of fresh sunflowers and lilies.", "Order fresh roses from the florist."], exVn: ["Người bán hoa khéo tay đã cắm một bó hoa hướng dương và hoa ly tươi tắn.", "Đặt hoa hồng tươi tại tiệm hoa."] },
    { word: "gas station", phonetic: "/ˈɡæs steɪʃn/", def: "An establishment beside a road selling fuel and lubricants for motor vehicles; petrol station.", defVn: "cây xăng, trạm cấp xăng", pos: "noun", ex: ["Pull over at the next gas station to fill up your motorbike tank with fuel.", "Clean windshields at the gas station."], exVn: ["Tấp vào cây xăng tiếp theo để đổ đầy bình xăng xe máy nhé.", "Lau kính chắn gió tại cây xăng."] },
    { word: "tailor", phonetic: "/ˈteɪlər/", def: "A person whose occupation is making fitted clothes such as suits, pants, and dresses.", defVn: "thợ may trang phục (áo dài/vest)", pos: "noun", ex: ["Hoi An expert tailors can measure and craft a custom suit or ao dai in 24 hours.", "Get pants hemmed at the tailor."], exVn: ["Các thợ may lành nghề ở Hội An có thể đo và may đo bộ vest hoặc áo dài trong 24 giờ.", "Lên gấu quần ở tiệm may."] },
    { word: "courier", phonetic: "/ˈkʊriər/", def: "A company or employee that transports parcels and documents.", defVn: "người giao hàng nhanh, shipper", pos: "noun", ex: ["The express courier delivered the online shopping parcel right to my doorstep.", "Track the courier's motorbike on the map."], exVn: ["Nhân viên chuyển phát nhanh đã giao bưu kiện mua sắm online đến tận cửa nhà tôi.", "Theo dõi vị trí xe máy của shipper trên bản đồ."] }
  ],

  // Theme 54: Sân bay & Nhà ga (Airport & Station Travel)
  t_basic_airport_station_travel: [
    { word: "carry-on", phonetic: "/ˈkæri ɑːn/", def: "A small piece of luggage that can be brought on board an aircraft.", defVn: "hành lý xách tay lên máy bay", pos: "noun", ex: ["Keep important travel documents and your laptop in your cabin carry-on bag.", "Weigh the carry-on luggage at check-in."], exVn: ["Giữ giấy tờ tùy thân quan trọng và laptop trong túi hành lý xách tay.", "Cân hành lý xách tay tại quầy thủ tục."] },
    { word: "overhead bin", phonetic: "/ˌoʊvərhed ˈbɪn/", def: "An enclosed compartment above the passenger seats in an aircraft used for luggage storage.", defVn: "ngăn để hành lý phía trên ghế ngồi", pos: "noun", ex: ["Stow your roller bag carefully in the airplane overhead bin.", "Close the overhead bin securely."], exVn: ["Cất chiếc va-li kéo cẩn thận vào ngăn hành lý phía trên trần máy bay.", "Đóng chặt nắp ngăn hành lý lại nhé."] },
    { word: "runway", phonetic: "/ˈrʌnweɪ/", def: "A leveled strip of smooth ground along which aircraft take off and land.", defVn: "đường băng cất hạ cánh máy bay", pos: "noun", ex: ["The wide-body aircraft accelerated smoothly down the international airport runway.", "Aircraft taxiing on the runway."], exVn: ["Chiếc máy bay thân rộng tăng tốc êm ái trên đường băng sân bay quốc tế.", "Máy bay lăn bánh trên đường băng."] },
    { word: "turbulence", phonetic: "/ˈtɜːrbjələns/", def: "Violent or unsteady movement of air or water, or of some other fluid.", defVn: "vùng không khí nhiễu động, xóc máy bay", pos: "noun", ex: ["Fasten your seatbelt securely when the pilot announces unexpected air turbulence.", "Mild flight turbulence passed quickly."], exVn: ["Cài chặt dây an toàn khi cơ trưởng thông báo máy bay đi vào vùng nhiễu động không khí.", "Đợt rung lắc nhẹ của chuyến bay qua đi nhanh chóng."] },
    { word: "duty-free", phonetic: "/ˌduːti ˈfriː/", def: "Exempt from the payment of certain local or national taxes and duties.", defVn: "cửa hàng miễn thuế sân bay", pos: "adj", ex: ["Browse luxury perfumes and chocolates in the international airport duty-free shops.", "Duty-free shopping after security."], exVn: ["Dạo mua nước hoa cao cấp và sô-cô-la tại các cửa hàng miễn thuế ở sân bay quốc tế.", "Mua sắm miễn thuế sau cửa kiểm tra an ninh."] }
  ],

  // Theme 55: Khách sạn & Lưu trú (Hotel & Lodging)
  t_basic_hotel_accommodation: [
    { word: "concierge", phonetic: "/koʊnˈsjerʒ/", def: "A hotel staff member who assists guests with booking tours, transportation, and reservations.", defVn: "nhân viên hỗ trợ dịch vụ khách sạn", pos: "noun", ex: ["The knowledgeable hotel concierge booked tickets for the traditional evening show.", "Ask the concierge for restaurant recommendations."], exVn: ["Nhân viên hỗ trợ dịch vụ khách sạn đã đặt vé xem biểu diễn nghệ thuật truyền thống.", "Nhờ nhân viên concierge gợi ý nhà hàng ngon nhé."] },
    { word: "minibar", phonetic: "/ˈmɪnibɑːr/", def: "A small refrigerator in a hotel room filled with drinks and snacks.", defVn: "tủ lạnh mini trong phòng khách sạn", pos: "noun", ex: ["Chilled bottled juices and soda cans are stocked inside the room minibar.", "Check the minibar price list."], exVn: ["Nước ép hoa quả ướp lạnh và nước ngọt đóng lon được xếp đầy trong tủ lạnh mini của phòng.", "Kiểm tra bảng giá tủ minibar nhé."] },
    { word: "luggage storage", phonetic: "/ˈlʌɡɪdʒ ˈstɔːrɪdʒ/", def: "A designated secure room where guests can leave their bags before check-in or after check-out.", defVn: "nơi gửi giữ hành lý khách sạn", pos: "noun", ex: ["Leave your heavy backpacks at the hotel luggage storage while exploring the city.", "Free luggage storage service."], exVn: ["Gửi ba-lô nặng tại quầy giữ hành lý của khách sạn trong lúc đi khám phá thành phố.", "Dịch vụ gửi giữ hành lý miễn phí."] },
    { word: "front desk", phonetic: "/frʌnt desk/", def: "The reception desk in a hotel where guests register upon arrival.", defVn: "quầy lễ tân khách sạn", pos: "noun", ex: ["Present your passport at the hotel front desk to receive your electronic room keycard.", "The front desk is open 24/7."], exVn: ["Xuất trình hộ chiếu tại quầy lễ tân khách sạn để nhận thẻ từ phòng nghỉ.", "Quầy lễ tân phục vụ 24/7."] }
  ],

  // Theme 56: Ẩm thực đường phố & Ăn vặt (Street Food & Snacks)
  t_basic_street_food_snacks: [
    { word: "sugarcane juice", phonetic: "/ˈʃʊɡərkeɪn dʒuːs/", def: "A sweet refreshing natural beverage pressed from raw sugar cane stalks.", defVn: "nước mía ép tươi mát lạnh (nước mía tắc)", pos: "noun", ex: ["An ice-cold cup of fresh sugarcane juice with calamansi lime cools the body instantly.", "Watch sugarcane pressed fresh."], exVn: ["Một ly nước mía ép tươi có quất mát lạnh xua tan ngay cái nóng oi ả.", "Xem người bán ép mía tươi tại chỗ."] },
    { word: "sticky rice", phonetic: "/ˈstɪki raɪs/", def: "Glutinous rice with sweet or savory toppings; xoi.", defVn: "món xôi (xôi bắp, xôi xéo, xôi gấc)", pos: "noun", ex: ["Warm fragrant savory sticky rice wrapped in banana leaves makes the best breakfast.", "Sweet yellow sticky rice with peanuts."], exVn: ["Gói xôi mặn nóng hổi thơm nức bọc trong lá chuối là món ăn sáng tuyệt nhất.", "Xôi vàng ngọt bùi thơm hạt lạc."] },
    { word: "rice paper", phonetic: "/raɪs ˈpeɪpər/", def: "Edible thin sheets made from rice flour; used in spring rolls or street snacks.", defVn: "bánh tráng (bánh tráng nướng, bánh tráng trộn)", pos: "noun", ex: ["Grilled Vietnamese rice paper pizza (Banh Trang Nuong) is crispy and flavorful.", "Spicy mixed rice paper snack."], exVn: ["Bánh tráng nướng Đà Lạt giòn rụm và đậm đà hương vị.", "Bánh tráng trộn cay cay ngon miệng."] },
    { word: "steamed bun", phonetic: "/stiːmd bʌn/", def: "A soft, fluffy steamed dough filled with pork, mushrooms, and quail eggs; banh bao.", defVn: "chiếc bánh bao nóng hổi", pos: "noun", ex: ["A steaming hot savory bun filled with minced pork and quail egg warms cold mornings.", "Fluffy vegetarian steamed buns."], exVn: ["Chiếc bánh bao nhân thịt băm trứng cút nóng hổi làm ấm cả buổi sáng se lạnh.", "Bánh bao chay mềm xốp thơm ngon."] },
    { word: "quail egg", phonetic: "/kweɪl eɡ/", def: "The small, mottled egg of a quail, widely enjoyed as street food.", defVn: "quả trứng cút nhỏ xinh", pos: "noun", ex: ["Boiled quail eggs dipped in black pepper salt with fresh Vietnamese coriander.", "Fried quail eggs on rice paper."], exVn: ["Trứng cút luộc chấm muối tiêu chanh ăn kèm rau răm tươi.", "Trứng cút nướng mỡ hành trên bánh tráng."] }
  ],

  // Theme 58: Lễ hội & Phong tục (Holidays & Customs)
  t_basic_holidays_customs: [
    { word: "lucky money", phonetic: "/ˈlʌki ˈmʌni/", def: "Money given in bright red envelopes to children and elders during Lunar New Year; li xi.", defVn: "tiền lì xì mừng tuổi may mắn", pos: "noun", ex: ["Elders hand bright red lucky money envelopes to children with heartfelt blessing wishes.", "Receive lucky money on New Year's Day."], exVn: ["Người lớn trao những phong bao lì xì đỏ thắm cho con cháu cùng những lời chúc phúc chân thành.", "Nhận tiền lì xì mừng tuổi vào ngày mùng Một Tết."] },
    { word: "red envelope", phonetic: "/red ˈenvəloʊp/", def: "A decorative red packet containing money presented during social gatherings and holidays.", defVn: "phong bao lì xì đỏ thắm", pos: "noun", ex: ["Bright scarlet red envelopes symbolize good fortune, prosperity, and joy.", "Golden calligraphy on red envelopes."], exVn: ["Những phong bao đỏ thắm tượng trưng cho may mắn, thịnh vượng và hoan ca.", "Chữ thư pháp dát vàng trên phong bao lì xì."] },
    { word: "mooncake", phonetic: "/ˈmuːnkeɪk/", def: "A round Chinese pastry filled with lotus seed paste or bean paste, traditionally eaten during Mid-Autumn.", defVn: "bánh trung thu nướng / dẻo", pos: "noun", ex: ["Share sweet traditional baked mixed-nut mooncakes with green tea under the full moon.", "Snow-skin lotus seed mooncakes."], exVn: ["Cùng nhau chia sẻ chiếc bánh trung thu nướng thập cẩm bên chén trà xanh dưới ánh trăng rằm.", "Bánh dẻo trung thu nhân hạt sen thanh tao."] },
    { word: "dragon dance", phonetic: "/ˈdræɡən dæns/", def: "A traditional dance performed in Chinese and Vietnamese culture during festive periods.", defVn: "múa lân sư rồng rộn ràng", pos: "noun", ex: ["Lively dragon and lion dances with booming drums bring prosperity and ward off misfortune.", "A colorful dragon dance parade."], exVn: ["Màn múa lân sư rồng rộn ràng cùng tiếng trống dồn dập mang lại thịnh vượng và may mắn.", "Đoàn diễu hành múa rồng rực rỡ sắc màu."] },
    { word: "banquet", phonetic: "/ˈbæŋkwɪt/", def: "An elaborate and formal evening meal for many people.", defVn: "bữa tiệc liên hoan thịnh soạn", pos: "noun", ex: ["Families gather around an abundant Tet banquet table overflowing with festive dishes.", "A grand wedding banquet."], exVn: ["Cả gia đình sum họp bên mâm cỗ Tết thịnh soạn đầy ắp những món ăn truyền thống.", "Bữa tiệc cưới linh đình ấm cúng."] }
  ],

  // Theme 59: An toàn & Luật lệ (Safety & Rules)
  t_basic_safety_warnings_rules: [
    { word: "life jacket", phonetic: "/ˈlaɪf ˈdʒækɪt/", def: "A sleeveless buoyant jacket for keeping a person afloat in water; life vest.", defVn: "áo phao cứu sinh an toàn", pos: "noun", ex: ["Always fasten your bright orange life jacket securely when boarding any riverboat.", "Life jackets stored under seats."], exVn: ["Luôn cài chặt chiếc áo phao cứu sinh màu cam khi bước lên bất kỳ chiếc thuyền nào.", "Áo phao được cất gọn dưới ghế ngồi."] },
    { word: "fire alarm", phonetic: "/ˈfaɪər əˈlɑːrm/", def: "A device that makes a loud noise to warn people that a fire has started in a building.", defVn: "chuông báo cháy khẩn cấp", pos: "noun", ex: ["Evacuate the building in an orderly line immediately if the fire alarm rings.", "Test fire alarms monthly."], exVn: ["Sơ tán khỏi tòa nhà theo hàng lối trật tự ngay lập tức khi chuông báo cháy reo.", "Kiểm tra hệ thống báo cháy hàng tháng."] },
    { word: "seatbelt", phonetic: "/ˈsiːtbelt/", def: "A belt that fastens around you in a car or plane for safety.", defVn: "dây đai an toàn trên xe", pos: "noun", ex: ["Buckle up your seatbelt firmly as soon as you sit in an automobile.", "Seatbelts save lives every day."], exVn: ["Cài chặt dây an toàn ngay khi vừa ngồi vào trong xe ô tô nhé.", "Dây an toàn bảo vệ sinh mạng mỗi ngày."] },
    { word: "caution sign", phonetic: "/ˈkɔːʃn saɪn/", def: "A visual sign alerting people to potential hazards or slippery conditions.", defVn: "biển báo chú ý nguy hiểm / sàn trơn", pos: "noun", ex: ["The yellow caution sign warns pedestrians of a freshly washed slippery floor.", "Heed road caution signs carefully."], exVn: ["Biển báo chú ý màu vàng nhắc nhở người đi bộ về sàn nhà vừa lau trơn trượt.", "Tuân thủ cẩn thận các biển cảnh báo giao thông."] },
    { word: "speed limit", phonetic: "/ˈspiːd ˈlɪmɪt/", def: "The maximum speed at which a vehicle may legally travel on a particular stretch of road.", defVn: "tốc độ giới hạn cho phép", pos: "noun", ex: ["Maintain your motorbike speed within the posted 50 km/h urban speed limit.", "Obey highway speed limits."], exVn: ["Giữ tốc độ xe máy trong giới hạn cho phép 50 km/h trong khu vực đô thị.", "Tuân thủ tốc độ giới hạn trên đường cao tốc."] }
  ],

  // Theme 60: Thiết bị & Gia dụng (Appliances & Gadgets)
  t_basic_appliances_gadgets: [
    { word: "air purifier", phonetic: "/ˈer ˈpjʊrɪfaɪər/", def: "A device that removes contaminants from the air in a room.", defVn: "máy lọc không khí gia đình", pos: "noun", ex: ["An HEPA filter air purifier removes dust and allergens from the bedroom.", "Quiet night mode on the air purifier."], exVn: ["Máy lọc không khí màng lọc HEPA lọc sạch bụi mịn và phấn hoa trong phòng ngủ.", "Chế độ ban đêm êm ái trên máy lọc không khí."] },
    { word: "induction cooker", phonetic: "/ɪnˈdʌkʃn ˈkʊkər/", def: "A cooking stove that heats a cooking vessel by electrical induction; induction hob.", defVn: "bếp từ nấu ăn thông minh", pos: "noun", ex: ["The induction cooker heats soup pots quickly and cleans effortlessly with a wipe.", "Use induction-compatible pots."], exVn: ["Bếp từ nấu sôi nồi súp nhanh chóng và lau chùi cực kỳ dễ dàng chỉ bằng một lần lau.", "Dùng nồi tương thích với bếp từ nhé."] },
    { word: "electric kettle", phonetic: "/ɪˈlektrɪk ˈketl/", def: "An electrical appliance for boiling water quickly with auto shut-off.", defVn: "ấm siêu tốc đun nước tự ngắt", pos: "noun", ex: ["The rapid-boil electric kettle boils water in two minutes for morning green tea.", "Stainless steel electric kettle."], exVn: ["Ấm siêu tốc đun sôi nước chỉ trong 2 phút để pha tách trà xanh buổi sáng.", "Ấm đun nước siêu tốc bằng inox không gỉ."] },
    { word: "humidifier", phonetic: "/hjuːˈmɪdɪfaɪər/", def: "A device for keeping the atmosphere moist in a room.", defVn: "máy phun sương tạo độ ẩm", pos: "noun", ex: ["Run an ultrasonic cool mist humidifier when sleeping in air-conditioned rooms.", "Add soothing essential oils to the humidifier."], exVn: ["Bật máy phun sương tạo ẩm khi ngủ trong phòng điều hòa mát mẻ.", "Nhỏ thêm tinh dầu thư giãn vào máy tạo ẩm."] },
    { word: "power strip", phonetic: "/ˈpaʊər strɪp/", def: "A block of electrical sockets that attaches to the end of a flexible cable; extension cord.", defVn: "ổ cắm điện nối dài đa năng", pos: "noun", ex: ["Plug your computer, lamp, and phone charger safely into a surge-protected power strip.", "Turn off the power strip switch."], exVn: ["Cắm máy tính, đèn bàn và sạc điện thoại an toàn vào ổ cắm điện chống sét.", "Tắt công tắc ổ cắm khi không sử dụng."] }
  ]
};
