module.exports = {
  // Theme 1: Lời chào hỏi (Greetings)
  t_basic_greetings: [
    { word: "welcome", phonetic: "/ˈwelkəm/", def: "Greeting someone politely on their arrival.", defVn: "chào mừng, đón tiếp", pos: "interjection", ex: ["Welcome to our beautiful school!", "You are always welcome in my home."], exVn: ["Chào mừng bạn đến với ngôi trường xinh đẹp của chúng tôi!", "Bạn luôn luôn được chào đón tại nhà của tôi."] },
    { word: "howdy", phonetic: "/ˈhaʊdi/", def: "An informal friendly greeting; hello.", defVn: "chào bạn (thân mật)", pos: "interjection", ex: ["Howdy, partner! How was your weekend trip?", "He waved and gave a friendly howdy."], exVn: ["Chào bạn thân mến! Chuyến đi cuối tuần của bạn thế nào?", "Anh ấy vẫy tay và cất lời chào thân mật."] },
    { word: "greetings", phonetic: "/ˈɡriːtɪŋz/", def: "A polite word or sign of welcome or recognition.", defVn: "lời chào, lời chúc mừng", pos: "noun", ex: ["Warm season's greetings from all of us!", "The host offered warm greetings to every guest."], exVn: ["Gửi lời chào mùa lễ hội ấm áp từ tất cả chúng tôi!", "Người chủ nhà gửi lời chào nồng hậu tới từng vị khách."] },
    { word: "pleasure", phonetic: "/ˈpleʒər/", def: "A feeling of happy satisfaction and enjoyment.", defVn: "niềm hân hạnh, điều vinh dự", pos: "noun", ex: ["It is a great pleasure to meet you today.", "My pleasure to help you learn English."], exVn: ["Thật là một niềm vinh dự lớn khi được gặp bạn hôm nay.", "Rất hân hạnh được giúp bạn học tiếng Anh."] },
    { word: "farewell", phonetic: "/ˌferˈwel/", def: "An act of parting or of marking departure; goodbye.", defVn: "lời tạm biệt, buổi chia tay", pos: "noun", ex: ["We hosted a farewell dinner for our dear friend.", "She bid a fond farewell to her teacher."], exVn: ["Chúng tôi tổ chức bữa tối chia tay người bạn thân quý.", "Cô ấy gửi lời tạm biệt đầy lưu luyến tới người thầy."] },
    { word: "cheerio", phonetic: "/ˌtʃɪriˈoʊ/", def: "An informal friendly way of saying goodbye.", defVn: "tạm biệt nhé (thân mật)", pos: "interjection", ex: ["Cheerio, see you at the morning class tomorrow!", "He smiled and called out cheerio as he left."], exVn: ["Tạm biệt nhé, hẹn gặp bạn ở lớp sáng mai!", "Anh ấy mỉm cười và nói lời tạm biệt khi rời đi."] },
    { word: "pardon", phonetic: "/ˈpɑːrdn/", def: "Used to ask someone to repeat what they have just said.", defVn: "xin thứ lỗi, xin nhắc lại", pos: "interjection", ex: ["Pardon me, could you repeat that English word?", "I beg your pardon, I did not catch your name."], exVn: ["Xin thứ lỗi, bạn có thể nhắc lại từ tiếng Anh đó không?", "Xin thứ lỗi, tôi chưa kịp nghe rõ tên bạn."] },
    { word: "apology", phonetic: "/əˈpɑːlədʒi/", def: "A regretful acknowledgment of an offense or failure.", defVn: "lời xin lỗi chân thành", pos: "noun", ex: ["Please accept my sincere apology for arriving late.", "He sent a warm written apology."], exVn: ["Xin vui lòng nhận lời xin lỗi chân thành của tôi vì đã đến muộn.", "Anh ấy đã gửi một bức thư xin lỗi ấm áp."] },
    { word: "compliment", phonetic: "/ˈkɑːmplɪmənt/", def: "A polite expression of praise or admiration.", defVn: "lời khen ngợi, tán dương", pos: "noun", ex: ["She received a kind compliment on her English speech.", "Paying someone a genuine compliment brightens their day."], exVn: ["Cô ấy nhận được lời khen ngợi tử tế về bài phát biểu tiếng Anh.", "Dành cho ai đó một lời khen chân thành sẽ làm bừng sáng ngày của họ."] },
    { word: "respectful", phonetic: "/rɪˈspektfl/", def: "Feeling or showing deference and respect.", defVn: "lễ phép, kính trọng", pos: "adj", ex: ["Always use polite and respectful language with elders.", "The students gave a respectful bow to their teacher."], exVn: ["Luôn sử dụng ngôn từ lịch sự và lễ phép với người lớn tuổi.", "Các em học sinh cúi đầu chào kính trọng người thầy của mình."] }
  ],

  // Theme 2: Tự giới thiệu (Introductions & Basic Info)
  t_basic_introductions: [
    { word: "introduce", phonetic: "/ˌɪntrəˈduːs/", def: "Present someone by name to another person.", defVn: "giới thiệu bản thân / người khác", pos: "verb", ex: ["Allow me to introduce my English study partner.", "Please introduce yourself to the class in two sentences."], exVn: ["Cho phép tôi giới thiệu người bạn cùng học tiếng Anh của mình.", "Xin vui lòng giới thiệu bản thân trước lớp trong hai câu."] },
    { word: "identity", phonetic: "/aɪˈdentəti/", def: "The fact of being who or what a person or thing is.", defVn: "danh tính, thân phận", pos: "noun", ex: ["Keep your national identity card safe in your wallet.", "Cultural identity is celebrated through traditional festivals."], exVn: ["Hãy giữ căn cước công dân của bạn an toàn trong ví nhé.", "Bản sắc văn hóa được tôn vinh qua các lễ hội truyền thống."] },
    { word: "nationality", phonetic: "/ˌnæʃəˈnæləti/", def: "The status of belonging to a particular nation.", defVn: "quốc tịch", pos: "noun", ex: ["What is your nationality? — I am Vietnamese.", "Our international language class has students of many nationalities."], exVn: ["Quốc tịch của bạn là gì? — Tôi là người Việt Nam.", "Lớp học ngôn ngữ quốc tế của chúng tôi có học viên từ nhiều quốc tịch."] },
    { word: "hometown", phonetic: "/ˈhoʊmtaʊn/", def: "The town or city where one was born or grew up.", defVn: "quê quán, quê hương", pos: "noun", ex: ["My hometown is a peaceful coastal village in Da Nang.", "Visiting my hometown during Tet brings pure happiness."], exVn: ["Quê hương tôi là một ngôi làng ven biển yên bình ở Đà Nẵng.", "Về thăm quê vào dịp Tết mang lại niềm hạnh phúc thuần khiết."] },
    { word: "occupation", phonetic: "/ˌɑːkjuˈpeɪʃn/", def: "A job or profession.", defVn: "nghề nghiệp, công việc chính", pos: "noun", ex: ["Please state your full name, age, and occupation on the form.", "Teaching English is a noble and rewarding occupation."], exVn: ["Vui lòng ghi rõ họ tên, tuổi và nghề nghiệp vào biểu mẫu.", "Dạy tiếng Anh là một nghề cao quý và giàu ý nghĩa."] },
    { word: "background", phonetic: "/ˈbækɡraʊnd/", def: "A person's origin, education, and experience.", defVn: "lai lịch, nền tảng học vấn", pos: "noun", ex: ["She comes from an artistic and musical family background.", "Tell us briefly about your educational background."], exVn: ["Cô ấy xuất thân từ một gia đình có truyền thống nghệ thuật và âm nhạc.", "Hãy chia sẻ ngắn gọn về nền tảng học vấn của bạn."] },
    { word: "interest", phonetic: "/ˈɪntrəst/", def: "The feeling of wanting to know or learn about something.", defVn: "sở thích, mối quan tâm", pos: "noun", ex: ["Her main personal interests include photography and foreign languages.", "I have a strong interest in learning conversational English."], exVn: ["Sở thích cá nhân chính của cô ấy gồm nhiếp ảnh và ngoại ngữ.", "Tôi có mối quan tâm sâu sắc tới việc học tiếng Anh giao tiếp."] },
    { word: "strength", phonetic: "/streŋkθ/", def: "A good or beneficial quality or attribute of a person.", defVn: "điểm mạnh, thế mạnh cá nhân", pos: "noun", ex: ["Patience and active listening are his greatest professional strengths.", "Recognizing your strengths builds healthy self-confidence."], exVn: ["Sự kiên nhẫn và biết lắng nghe là những thế mạnh chuyên môn lớn nhất của anh ấy.", "Nhận biết điểm mạnh của mình giúp xây dựng sự tự tin lành mạnh."] },
    { word: "dream", phonetic: "/driːm/", def: "A cherished aspiration, ambition, or ideal.", defVn: "ước mơ, hoài bão lớn", pos: "noun", ex: ["My dream is to travel around the world and speak fluent English.", "Work diligently every single day to achieve your biggest dream."], exVn: ["Ước mơ của tôi là được đi du lịch vòng quanh thế giới và nói tiếng Anh lưu loát.", "Hãy làm việc chăm chỉ mỗi ngày để đạt được ước mơ lớn nhất của bạn."] },
    { word: "contact", phonetic: "/ˈkɑːntækt/", def: "The state or condition of physical touching; communication.", defVn: "thông tin liên hệ, liên lạc", pos: "noun", ex: ["Please write down your phone number and email contact details.", "Stay in contact with your international classmates."], exVn: ["Vui lòng ghi lại số điện thoại và thông tin liên hệ email của bạn.", "Hãy giữ liên lạc thường xuyên với các bạn học quốc tế nhé."] }
  ],

  // Theme 3: Chữ số & Số đếm (Numbers & Counting)
  t_basic_numbers_counting: [
    { word: "twenty", phonetic: "/ˈtwenti/", def: "The number equivalent to the product of two and ten; 20.", defVn: "số hai mươi (20)", pos: "noun", ex: ["There are twenty students in our English speaking club.", "She scored twenty out of twenty on the grammar quiz."], exVn: ["Có 20 học viên trong câu lạc bộ nói tiếng Anh của chúng tôi.", "Cô ấy đạt điểm 20 trên 20 trong bài kiểm tra ngữ pháp."] },
    { word: "thirty", phonetic: "/ˈθɜːrti/", def: "The number equivalent to the product of three and ten; 30.", defVn: "số ba mươi (30)", pos: "noun", ex: ["Each lesson takes thirty focused minutes daily.", "September has thirty calendar days."], exVn: ["Mỗi bài học kéo dài 30 phút tập trung mỗi ngày.", "Tháng Chín có 30 ngày theo lịch."] },
    { word: "forty", phonetic: "/ˈfɔːrti/", def: "The number equivalent to the product of four and ten; 40.", defVn: "số bốn mươi (40)", pos: "noun", ex: ["The bus can comfortably seat forty passengers.", "Temperatures reached forty degrees Celsius today."], exVn: ["Chiếc xe buýt có thể chở 40 hành khách một cách thoải mái.", "Nhiệt độ hôm nay đã chạm mốc 40 độ C."] },
    { word: "fifty", phonetic: "/ˈfɪfti/", def: "The number equivalent to the product of five and ten; 50.", defVn: "số năm mươi (50)", pos: "noun", ex: ["He memorized fifty new English words in one week.", "The speed limit on this city street is fifty km/h."], exVn: ["Cậu ấy đã ghi nhớ 50 từ vựng tiếng Anh mới trong một tuần.", "Tốc độ giới hạn trên con phố này là 50 km/h."] },
    { word: "billion", phonetic: "/ˈbɪljən/", def: "The number equivalent to a thousand million; 1,000,000,000.", defVn: "một tỷ (1.000.000.000)", pos: "noun", ex: ["Over eight billion people share planet Earth.", "English is spoken by over 1.5 billion people globally."], exVn: ["Hơn 8 tỷ người đang cùng chung sống trên Trái Đất.", "Tiếng Anh được nói bởi hơn 1,5 tỷ người trên toàn cầu."] },
    { word: "dozen", phonetic: "/ˈdʌzn/", def: "A group or set of twelve items.", defVn: "một tá (12 cái / quả)", pos: "noun", ex: ["She bought a dozen fresh farm eggs at the morning market.", "A dozen yellow roses sat in the vase."], exVn: ["Cô ấy đã mua một tá trứng gà tươi ở chợ sáng.", "Một tá hoa hồng vàng cắm trong lọ hoa."] },
    { word: "quarter", phonetic: "/ˈkwɔːrtər/", def: "Each of four equal or corresponding parts into which something is divided; one fourth.", defVn: "một phần tư (1/4)", pos: "noun", ex: ["Cut the apple into four equal quarters.", "It is a quarter past seven in the morning."], exVn: ["Cắt quả táo thành bốn phần tư bằng nhau nhé.", "Bây giờ là 7 giờ 15 phút sáng."] },
    { word: "average", phonetic: "/ˈævərɪdʒ/", def: "A number expressing the central or typical value in a set of data.", defVn: "số trung bình, mức bình quân", pos: "noun", ex: ["His average test score was an impressive ninety percent.", "The average daily study time is forty minutes."], exVn: ["Điểm kiểm tra trung bình của anh ấy đạt 90% rất ấn tượng.", "Thời gian học trung bình mỗi ngày là 40 phút."] },
    { word: "total", phonetic: "/ˈtoʊtl/", def: "Comprising the whole number or amount.", defVn: "tổng số, toàn bộ", pos: "noun", ex: ["The total cost of the books is thirty dollars.", "What is the total number of vocabulary words learned?"], exVn: ["Tổng chi phí của những cuốn sách là 30 đô la.", "Tổng số từ vựng đã học được là bao nhiêu?"] },
    { word: "calculate", phonetic: "/ˈkælkjuleɪt/", def: "Determine the amount or number of something mathematically.", defVn: "tính toán, làm phép tính", pos: "verb", ex: ["Use a calculator to calculate monthly household expenses.", "Calculate the correct total before paying."], exVn: ["Dùng máy tính để tính toán chi tiêu sinh hoạt hàng tháng.", "Hãy tính toán lại tổng tiền cho đúng trước khi thanh toán nhé."] }
  ],

  // Theme 4: Màu sắc & Hình khối (Colors & Shapes)
  t_basic_colors_shapes: [
    { word: "crimson", phonetic: "/ˈkrɪmzn/", def: "Of a rich deep red color inclining to purple.", defVn: "màu đỏ thẫm, đỏ thắm", pos: "adj", ex: ["The autumn maple leaves turned brilliant crimson.", "A velvet crimson dress looked stunning at the banquet."], exVn: ["Những chiếc lá phong mùa thu chuyển sang màu đỏ thắm rực rỡ.", "Chiếc váy nhung đỏ thẫm trông vô cùng lộng lẫy tại buổi tiệc."] },
    { word: "azure", phonetic: "/ˈæʒər/", def: "Bright cyan-blue in color like a cloudless sky.", defVn: "màu xanh da trời, xanh ngọc bích", pos: "adj", ex: ["Phu Quoc features calm azure waters and white sand beaches.", "Birds flew across the vast azure sky."], exVn: ["Phú Quốc sở hữu làn nước xanh ngọc êm đềm và những bãi cát trắng.", "Những cánh chim bay liệng trên bầu trời xanh biếc bao la."] },
    { word: "emerald", phonetic: "/ˈemərəld/", def: "A bright green precious stone or color.", defVn: "màu xanh ngọc lục bảo", pos: "adj", ex: ["Ha Long Bay is famous for its shimmering emerald water.", "She wore an exquisite emerald ring."], exVn: ["Vịnh Hạ Long nổi tiếng với làn nước ngọc lục bảo lấp lánh.", "Cô ấy đeo chiếc nhẫn ngọc lục bảo tinh xảo."] },
    { word: "turquoise", phonetic: "/ˈtɜːrkwɔɪz/", def: "A greenish-blue color.", defVn: "màu xanh ngọc lam", pos: "adj", ex: ["The tropical lagoon has clear turquoise waters.", "Handmade silver jewelry inlaid with turquoise stone is stunning."], exVn: ["Đầm phá nhiệt đới có làn nước màu xanh ngọc lam trong vắt.", "Trang sức bạc thủ công khảm đá ngọc lam rất đẹp mắt."] },
    { word: "charcoal", phonetic: "/ˈtʃɑːrkoʊl/", def: "A dark gray color like that of burnt wood.", defVn: "màu xám than, xám đậm", pos: "adj", ex: ["He wore a tailored charcoal gray wool suit.", "Artists sketch lifelike portraits with charcoal sticks."], exVn: ["Anh ấy mặc một bộ vest len màu xám than vừa vặn.", "Các họa sĩ vẽ chân dung sống động bằng những thỏi than chì."] },
    { word: "cone", phonetic: "/koʊn/", def: "A solid or hollow object that tapers smoothly from a circular base to a point.", defVn: "hình nón (như nón lá)", pos: "noun", ex: ["Traditional Vietnamese conical leaf hats have the shape of a cone.", "Enjoy a double-scoop vanilla ice cream cone."], exVn: ["Chiếc nón lá truyền thống của Việt Nam có hình chóp nón.", "Thưởng thức một cây kem ốc quế hai viên vani."] },
    { word: "cylinder", phonetic: "/ˈsɪlɪndər/", def: "A solid geometric figure with straight parallel sides and a circular or oval cross section.", defVn: "hình trụ, khối trụ tròn", pos: "noun", ex: ["A drinking glass and a soda can are shaped like a cylinder.", "Roll the clay into a smooth cylinder."], exVn: ["Chiếc ly uống nước và lon nước ngọt có hình khối trụ.", "Lăn miếng đất sét thành một khối trụ nhẵn bóng."] },
    { word: "cube", phonetic: "/kjuːb/", def: "A symmetrical three-dimensional shape, either solid or hollow, contained by six equal squares.", defVn: "hình lập phương, khối vuông 6 mặt", pos: "noun", ex: ["Drop two ice cubes into the iced lemon tea.", "Solving a Rubik's cube requires logical thinking."], exVn: ["Thả hai viên đá lạnh hình lập phương vào cốc trà chanh đá.", "Giải khối rubik đòi hỏi tư duy logic."] },
    { word: "crescent", phonetic: "/ˈkresnt/", def: "The curved sickle shape of the waxing or waning moon.", defVn: "hình trăng khuyết, hình lưỡi liềm", pos: "noun", ex: ["A shining crescent moon appeared in the evening sky.", "Croissants are baked in a golden crescent shape."], exVn: ["Một vầng trăng khuyết sáng lấp lánh xuất hiện trên bầu trời đêm.", "Bánh sừng bò được nướng thành hình lưỡi liềm vàng ươm."] },
    { word: "curved", phonetic: "/kɜːrvd/", def: "Having a shape that turns smoothly and continuously.", defVn: "uốn cong mềm mại", pos: "adj", ex: ["The ancient stone bridge has a graceful curved arch.", "A gentle curved smile appeared on her face."], exVn: ["Cây cầu đá cổ kính có nhịp vòm uốn cong duyên dáng.", "Một nụ cười cong nhẹ nhàng nở trên khuôn mặt cô ấy."] }
  ],

  // Theme 5: Gia đình & Họ hàng (Family & Relatives)
  t_basic_family_relatives: [
    { word: "ancestor", phonetic: "/ˈænsestər/", def: "A person, typically one more remote than a grandparent, from whom one is descended.", defVn: "tổ tiên, ông bà tổ phụ", pos: "noun", ex: ["Vietnamese families honor their ancestors with incense at the altar.", "We preserve traditions passed down from our ancestors."], exVn: ["Các gia đình Việt Nam tưởng nhớ tổ tiên bằng nén hương trên bàn thờ gia tiên.", "Chúng tôi gìn giữ các truyền thống được truyền lại từ tổ tiên."] },
    { word: "descendant", phonetic: "/dɪˈsendənt/", def: "A person, plant, or animal that is descended from a particular ancestor.", defVn: "con cháu đời sau, hậu duệ", pos: "noun", ex: ["Descendants gathered from near and far for the family clan reunion.", "We are proud descendants of the Lac Hong lineage."], exVn: ["Con cháu từ khắp nơi gần xa đã tụ họp về dự lễ họp dòng họ.", "Chúng ta là những hậu duệ tự hào của dòng giống Lạc Hồng."] },
    { word: "sibling", phonetic: "/ˈsɪblɪŋ/", def: "Each of two or more children or offspring having one or both parents in common; a brother or sister.", defVn: "anh chị em ruột trong nhà", pos: "noun", ex: ["Do you have any brothers or sisters? — I have two siblings.", "Siblings should love, protect, and support each other."], exVn: ["Bạn có anh chị em nào không? — Tôi có hai anh chị em ruột.", "Anh chị em ruột nên yêu thương, che chở và đùm bọc lẫn nhau."] },
    { word: "relative", phonetic: "/ˈrelətɪv/", def: "A person connected by blood or marriage.", defVn: "bà con họ hàng", pos: "noun", ex: ["We visit our relatives and wish them prosperity during Tet.", "A distant relative came to visit from the countryside."], exVn: ["Chúng tôi đi chúc Tết họ hàng và cầu chúc mọi người thịnh vượng.", "Một người họ hàng xa từ quê lên chơi thăm nhà."] },
    { word: "twin", phonetic: "/twɪn/", def: "One of two children or animals born at the same birth.", defVn: "anh/chị/em sinh đôi", pos: "noun", ex: ["The identical twin sisters share similar smiles and voices.", "They dressed their twin boys in matching blue shirts."], exVn: ["Hai chị em sinh đôi cùng trứng có nụ cười và giọng nói giống hệt nhau.", "Họ mặc cho hai bé trai sinh đôi những chiếc áo màu xanh giống nhau."] },
    { word: "nephew", phonetic: "/ˈnefjuː/", def: "A son of one's brother or sister, or of one's brother-in-law or sister-in-law.", defVn: "cháu trai (con của anh chị em)", pos: "noun", ex: ["My five-year-old nephew loves drawing funny cartoon animals.", "I bought a colorful toy car for my nephew's birthday."], exVn: ["Cháu trai năm tuổi của tôi rất thích vẽ các con thú hoạt hình ngộ nghĩnh.", "Tôi đã mua một chiếc ô tô đồ chơi màu sắc làm quà sinh nhật cho cháu trai."] },
    { word: "niece", phonetic: "/niːs/", def: "A daughter of one's brother or sister, or of one's brother-in-law or sister-in-law.", defVn: "cháu gái (con của anh chị em)", pos: "noun", ex: ["My cheerful niece recited an English poem beautifully.", "She taught her little niece how to bake cookies."], exVn: ["Cháu gái vui tươi của tôi đã đọc một bài thơ tiếng Anh rất hay.", "Cô ấy dạy cô cháu gái nhỏ cách nướng bánh quy."] },
    { word: "parent", phonetic: "/ˈperənt/", def: "A father or mother.", defVn: "cha mẹ, phụ huynh", pos: "noun", ex: ["Love and respect your parents for their lifelong dedication.", "Both parents attended the school meeting with pride."], exVn: ["Hãy yêu thương và kính trọng cha mẹ vì sự hy sinh cả đời của người.", "Cả bố mẹ đều tự hào tham dự buổi họp phụ huynh ở trường."] },
    { word: "spouse", phonetic: "/spaʊs/", def: "A husband or wife, considered in relation to their partner.", defVn: "vợ chồng, bạn đời hợp pháp", pos: "noun", ex: ["Employees may bring their spouse to the annual company gala.", "They have been devoted spouses for thirty wonderful years."], exVn: ["Nhân viên có thể mời vợ/chồng cùng tham dự đêm tiệc thường niên của công ty.", "Họ đã là vợ chồng chung thủy suốt 30 năm tuyệt vời."] },
    { word: "household", phonetic: "/ˈhaʊshoʊld/", def: "A house and its occupants regarded as a unit.", defVn: "hộ gia đình, mái nhà chung", pos: "noun", ex: ["Every member of the household shares daily cooking chores.", "A peaceful and supportive household nurtures happy children."], exVn: ["Mỗi thành viên trong gia đình đều cùng nhau san sẻ việc bếp núc mỗi ngày.", "Một mái ấm gia đình an yên và hòa thuận nuôi dưỡng những đứa trẻ hạnh phúc."] }
  ]
};
