module.exports = {
  // Theme 18: Trường học & Dụng cụ
  t_basic_school_stationery: [
    { word: "backpack", phonetic: "/ˈbækpæk/", def: "A bag carried on one's back.", defVn: "ba-lô đi học", pos: "noun", ex: ["Pack your books into the backpack.", "A durable school backpack."], exVn: ["Xếp sách vào ba-lô đi học.", "Một chiếc ba-lô đi học bền bỉ."] },
    { word: "highlighter", phonetic: "/ˈhaɪlaɪtər/", def: "A broad felt-tipped pen used for marking text.", defVn: "bút dạ quang, bút nhớ dòng", pos: "noun", ex: ["Highlight key vocabulary with yellow.", "Use pastel highlighters."], exVn: ["Đánh dấu từ vựng quan trọng bằng màu vàng.", "Dùng bút nhớ màu pastel."] },
    { word: "sharpener", phonetic: "/ˈʃɑːrpnər/", def: "A device for sharpening pencils.", defVn: "cái gọt bút chì", pos: "noun", ex: ["Sharpen your pencil with the sharpener.", "Can I borrow your sharpener?"], exVn: ["Gọt bút chì bằng cái gọt nhé.", "Tôi có thể mượn gọt bút chì của bạn không?"] },
    { word: "stapler", phonetic: "/ˈsteɪplər/", def: "A device for fastening paper sheets together with wire.", defVn: "cái dập ghim, bấm kim", pos: "noun", ex: ["Staple the report with the stapler.", "Refill the stapler with staples."], exVn: ["Dập ghim báo cáo bằng dập ghim.", "Nạp thêm ghim vào bấm kim."] },
    { word: "calculator", phonetic: "/ˈkælkjəleɪtər/", def: "An electronic device for calculating.", defVn: "máy tính cầm tay", pos: "noun", ex: ["Use a calculator in math class.", "A scientific calculator."], exVn: ["Dùng máy tính trong giờ toán.", "Máy tính khoa học cầm tay."] },
    { word: "folder", phonetic: "/ˈfoʊldər/", def: "A folding cover for storing loose papers.", defVn: "bìa kẹp tài liệu", pos: "noun", ex: ["Keep worksheets in a folder.", "Label each subject folder."], exVn: ["Lưu bài tập trong bìa kẹp tài liệu.", "Dán nhãn từng bìa hồ sơ."] },
    { word: "compass", phonetic: "/ˈkʌmpəs/", def: "An instrument for drawing circles.", defVn: "cây com-pa vẽ hình tròn", pos: "noun", ex: ["Draw a circle with a compass.", "Geometry tools include a compass."], exVn: ["Vẽ hình tròn bằng com-pa.", "Dụng cụ hình học gồm có com-pa."] },
    { word: "quiz", phonetic: "/kwɪz/", def: "A quick or informal test of knowledge.", defVn: "bài kiểm tra ngắn, đố vui", pos: "noun", ex: ["Take a quick vocabulary quiz.", "She passed the English quiz."], exVn: ["Làm bài trắc nghiệm từ vựng nhanh.", "Cô ấy đã vượt qua bài kiểm tra tiếng Anh."] },
    { word: "grade", phonetic: "/ɡreɪd/", def: "A mark indicating quality of a student's work.", defVn: "điểm số, cấp lớp", pos: "noun", ex: ["He received an 'A' grade.", "She is in fifth grade."], exVn: ["Cậu ấy nhận điểm 'A'.", "Em ấy đang học lớp năm."] },
    { word: "library", phonetic: "/ˈlaɪbreri/", def: "A building containing collections of books for reading.", defVn: "thư viện trường học", pos: "noun", ex: ["Study quietly in the library.", "Borrow books from the library."], exVn: ["Học tập trật tự trong thư viện.", "Mượn sách từ thư viện."] }
  ],

  // Theme 19: Sở thích & Thể thao
  t_basic_hobbies_sports: [
    { word: "badminton", phonetic: "/ˈbædmɪntən/", def: "A game with rackets in which a shuttlecock is hit.", defVn: "môn cầu lông", pos: "noun", ex: ["Play badminton in the morning.", "Badminton keeps you fit."], exVn: ["Chơi cầu lông vào buổi sáng.", "Cầu lông giúp bạn khỏe mạnh."] },
    { word: "tennis", phonetic: "/ˈtenɪs/", def: "A racket sport played with a felt-covered ball.", defVn: "môn quần vợt, tennis", pos: "noun", ex: ["Play tennis on the court.", "A tennis tournament."], exVn: ["Chơi quần vợt trên sân đấu.", "Giải đấu quần vợt."] },
    { word: "basketball", phonetic: "/ˈbæskɪtbɔːl/", def: "A game played with a ball through a netted hoop.", defVn: "môn bóng rổ", pos: "noun", ex: ["Shoot the basketball into the hoop.", "Basketball builds teamwork."], exVn: ["Ném bóng rổ vào rổ.", "Bóng rổ xây dựng tinh thần đồng đội."] },
    { word: "volleyball", phonetic: "/ˈvɑːlibɔːl/", def: "A game hitting a large ball over a high net.", defVn: "môn bóng chuyền", pos: "noun", ex: ["Play beach volleyball on the sand.", "Spike the volleyball over the net."], exVn: ["Chơi bóng chuyền bãi biển trên cát.", "Đập bóng chuyền qua lưới."] },
    { word: "cycling", phonetic: "/ˈsaɪklɪŋ/", def: "The activity of riding a bicycle.", defVn: "đạp xe thể thao", pos: "noun", ex: ["Morning cycling around the lake.", "Cycling is eco-friendly."], exVn: ["Đạp xe buổi sáng quanh hồ.", "Đi xe đạp rất thân thiện môi trường."] },
    { word: "hiking", phonetic: "/ˈhaɪkɪŋ/", def: "Going for long brisk walks in the countryside or hills.", defVn: "đi bộ leo núi dã ngoại", pos: "noun", ex: ["Go hiking in Sapa mountains.", "Pack water for hiking."], exVn: ["Đi leo núi dã ngoại ở Sa Pa.", "Chuẩn bị nước cho chuyến đi bộ dã ngoại."] },
    { word: "camping", phonetic: "/ˈkæmpɪŋ/", def: "Spending a vacation living in a tent.", defVn: "cắm trại ngoài trời", pos: "noun", ex: ["Set up a camping tent by the lake.", "Campfire stories at camping."], exVn: ["Dựng lều cắm trại bên hồ.", "Kể chuyện bên lửa trại khi cắm trại."] },
    { word: "gardening", phonetic: "/ˈɡɑːrdnɪŋ/", def: "Tending and cultivating a garden.", defVn: "làm vườn, trồng cây cảnh", pos: "noun", ex: ["Gardening is a relaxing hobby.", "Grow organic herbs through gardening."], exVn: ["Làm vườn là một sở thích thư giãn.", "Trồng rau thơm hữu cơ qua làm vườn."] },
    { word: "chess", phonetic: "/tʃes/", def: "A strategic board game for two players.", defVn: "môn cờ vua", pos: "noun", ex: ["Playing chess sharpens the mind.", "Checkmate in thirty moves."], exVn: ["Chơi cờ vua rèn luyện trí não.", "Chiếu hết trong 30 nước cờ."] },
    { word: "dancing", phonetic: "/ˈdænsɪŋ/", def: "Moving rhythmically to music.", defVn: "khiêu vũ, nhảy múa", pos: "noun", ex: ["Dancing burns calories.", "Traditional folk dancing."], exVn: ["Nhảy múa giúp đốt cháy calo.", "Múa dân gian truyền thống."] }
  ],

  // Theme 20: Mua sắm & Tiền tệ
  t_basic_shopping_money: [
    { word: "wallet", phonetic: "/ˈwɑːlɪt/", def: "A small flat case for money and cards.", defVn: "chiếc ví tiền, bóp", pos: "noun", ex: ["Keep money in your leather wallet.", "Take out the wallet to pay."], exVn: ["Để tiền trong ví da.", "Rút ví ra để thanh toán."] },
    { word: "purse", phonetic: "/pɜːrs/", def: "A small bag used for carrying money and personal items.", defVn: "ví nữ cầm tay, túi nhỏ", pos: "noun", ex: ["She put coins in her purse.", "A stylish red purse."], exVn: ["Cô ấy để tiền xu vào ví.", "Chiếc ví nữ màu đỏ sành điệu."] },
    { word: "coin", phonetic: "/kɔɪn/", def: "A flat metal disc used as money.", defVn: "đồng tiền xu", pos: "noun", ex: ["Drop a coin in the vending machine.", "Collect antique coins."], exVn: ["Thả đồng xu vào máy bán hàng.", "Sưu tầm tiền xu cổ."] },
    { word: "bill", phonetic: "/bɪl/", def: "A printed statement of money owed.", defVn: "hóa đơn thanh toán", pos: "noun", ex: ["Ask the waiter for the dinner bill.", "Pay the monthly electric bill."], exVn: ["Xin bồi bàn hóa đơn bữa tối.", "Thanh toán tiền điện hàng tháng."] },
    { word: "credit card", phonetic: "/ˈkredɪt kɑːrd/", def: "A card allowing purchase of goods on credit.", defVn: "thẻ tín dụng", pos: "noun", ex: ["Pay by credit card.", "Tap the contactless credit card."], exVn: ["Thanh toán bằng thẻ tín dụng.", "Chạm thẻ tín dụng không tiếp xúc."] },
    { word: "discount", phonetic: "/ˈdɪskaʊnt/", def: "A deduction from the regular price.", defVn: "giảm giá, chiết khấu", pos: "noun", ex: ["Students get a 20 percent discount.", "Look for store discounts."], exVn: ["Học sinh được giảm giá 20%.", "Tìm kiếm các đợt giảm giá của cửa hàng."] },
    { word: "customer", phonetic: "/ˈkʌstəmər/", def: "A person who buys goods or services.", defVn: "khách hàng", pos: "noun", ex: ["Greet every customer warmly.", "Customer satisfaction is key."], exVn: ["Chào đón mọi khách hàng niềm nở.", "Sự hài lòng của khách hàng là then chốt."] },
    { word: "shopkeeper", phonetic: "/ˈʃɑːpkiːpər/", def: "An owner or manager of a small shop.", defVn: "chủ tiệm, chủ quán", pos: "noun", ex: ["The friendly shopkeeper helped us.", "Support local shopkeepers."], exVn: ["Chủ quán thân thiện đã giúp chúng tôi.", "Ủng hộ các chủ tiệm địa phương."] },
    { word: "change", phonetic: "/tʃeɪndʒ/", def: "Money returned when payment exceeds price.", defVn: "tiền lẻ thối lại", pos: "noun", ex: ["Here is your coffee and change.", "Keep the change, thank you."], exVn: ["Cà phê và tiền thừa của bạn đây.", "Xin giữ lại tiền lẻ nhé, cảm ơn bạn."] },
    { word: "cheap", phonetic: "/tʃiːp/", def: "Costing little; low in price.", defVn: "rẻ, giá bình dân", pos: "adj", ex: ["Street food is cheap and delicious.", "Find cheap plane tickets."], exVn: ["Ẩm thực đường phố vừa rẻ vừa ngon.", "Tìm vé máy bay giá rẻ."] },
    { word: "expensive", phonetic: "/ɪkˈspensɪv/", def: "Costing a lot of money.", defVn: "đắt đỏ, giá cao", pos: "adj", ex: ["Dining in five-star hotels is expensive.", "Designer watches are expensive."], exVn: ["Ăn uống ở khách sạn 5 sao rất đắt đỏ.", "Đồng hồ hàng hiệu có giá cao."] },
    { word: "spend", phonetic: "/spend/", def: "Pay out money in buying or hiring goods.", defVn: "tiêu xài, chi tiêu", pos: "verb", ex: ["Spend money wisely on education.", "Don't spend too much on snacks."], exVn: ["Hãy chi tiêu tiền bạc khôn ngoan cho việc học.", "Đừng tiêu quá nhiều vào đồ ăn vặt."] },
    { word: "save", phonetic: "/seɪv/", def: "Keep money for future use.", defVn: "tiết kiệm tiền", pos: "verb", ex: ["Save money in the bank every month.", "Save up for a new laptop."], exVn: ["Tiết kiệm tiền gửi ngân hàng mỗi tháng.", "Tiết kiệm tiền để mua laptop mới."] }
  ],

  // Theme 21: Cây cối & Hoa quả
  t_basic_plants_fruits: [
    { word: "watermelon", phonetic: "/ˈwɔːtərmelən/", def: "A large green fruit with sweet red juicy flesh.", defVn: "quả dưa hấu", pos: "noun", ex: ["Chilled watermelon on hot summer days.", "Sweet seedless watermelon."], exVn: ["Dưa hấu ướp lạnh vào ngày hè nóng nực.", "Dưa hấu ngọt không hạt."] },
    { word: "strawberry", phonetic: "/ˈstrɔːberi/", def: "A sweet soft red fruit with tiny seeds.", defVn: "quả dâu tây", pos: "noun", ex: ["Da Lat sweet red strawberries.", "Yogurt topped with strawberries."], exVn: ["Dâu tây đỏ ngọt Đà Lạt.", "Sữa chua phủ dâu tây."] },
    { word: "grape", phonetic: "/ɡreɪp/", def: "A small round berry growing in clusters.", defVn: "quả nho, chùm nho", pos: "noun", ex: ["A cluster of sweet purple grapes.", "Ninh Thuan is famous for grapes."], exVn: ["Một chùm nho tím ngọt ngào.", "Ninh Thuận nổi tiếng với nho."] },
    { word: "pineapple", phonetic: "/ˈpaɪnæpl/", def: "A large tropical fruit with yellow spiky flesh.", defVn: "quả dứa, thơm, khóm", pos: "noun", ex: ["Fresh pineapple juice.", "Add pineapple to sweet and sour soup."], exVn: ["Nước ép dứa tươi.", "Cho dứa vào canh chua."] },
    { word: "coconut", phonetic: "/ˈkoʊkənʌt/", def: "A large brown tropical fruit with milk and meat.", defVn: "quả dừa, nước dừa", pos: "noun", ex: ["Drink sweet fresh coconut water.", "Ben Tre coconut candy."], exVn: ["Uống nước dừa tươi ngọt lành.", "Kẹo dừa Bến Tre."] },
    { word: "dragon fruit", phonetic: "/ˈdræɡən fruːt/", def: "A bright pink tropical fruit with white or red speckled flesh.", defVn: "quả thanh long", pos: "noun", ex: ["Red-fleshed dragon fruit is sweet.", "Export dragon fruit abroad."], exVn: ["Thanh long ruột đỏ rất ngọt.", "Xuất khẩu thanh long ra nước ngoài."] },
    { word: "durian", phonetic: "/ˈdʊriən/", def: "A large spiky fruit with strong aroma and rich custard flesh.", defVn: "quả sầu riêng", pos: "noun", ex: ["Durian is the king of fruits.", "Creamy golden durian flesh."], exVn: ["Sầu riêng là vua của các loài quả.", "Múi sầu riêng vàng ươm béo ngậy."] },
    { word: "lotus", phonetic: "/ˈloʊtəs/", def: "An aquatic plant with beautiful flowers; national flower.", defVn: "hoa sen (quốc hoa)", pos: "noun", ex: ["Pink lotus in the pond.", "Aromatic lotus tea."], exVn: ["Bông sen hồng trong hồ.", "Trà sen thơm ngát."] },
    { word: "bamboo", phonetic: "/ˌbæmˈbuː/", def: "A giant woody tropical grass.", defVn: "cây tre, cây trúc", pos: "noun", ex: ["Green bamboo groves in the village.", "Bamboo shoots for cooking."], exVn: ["Lũy tre xanh nơi làng quê.", "Măng tre dùng để nấu ăn."] }
  ],

  // Theme 22: Sức khỏe & Y tế
  t_basic_health_medical: [
    { word: "headache", phonetic: "/ˈhedeɪk/", def: "A continuous pain in the head.", defVn: "cơn đau đầu", pos: "noun", ex: ["I have a mild headache.", "Rest to relieve a headache."], exVn: ["Tôi bị đau đầu nhẹ.", "Nghỉ ngơi để làm dịu cơn đau đầu."] },
    { word: "cough", phonetic: "/kɔːf/", def: "Expelling air sharply from lungs.", defVn: "cơn ho, tiếng ho", pos: "noun", ex: ["Honey lemon tea soothes a cough.", "Cover your mouth when you cough."], exVn: ["Trà chanh mật ong làm dịu cơn ho.", "Che miệng khi ho nhé."] },
    { word: "stomachache", phonetic: "/ˈstʌməkeɪk/", def: "Pain in the stomach or belly.", defVn: "đau bụng, đau dạ dày", pos: "noun", ex: ["Eating spoiled food causes stomachache.", "Take medicine for stomachache."], exVn: ["Ăn đồ ôi thiu gây đau bụng.", "Uống thuốc trị đau bụng."] },
    { word: "toothache", phonetic: "/ˈtuːθeɪk/", def: "Pain in a tooth.", defVn: "đau răng, nhức răng", pos: "noun", ex: ["Visit the dentist for a toothache.", "Toothache hurts when eating cold food."], exVn: ["Đi khám nha sĩ khi đau răng.", "Đau răng khi ăn đồ lạnh."] },
    { word: "bandage", phonetic: "/ˈbændɪdʒ/", def: "A strip of cloth used to bind a wound.", defVn: "băng gạc, băng dán cá nhân", pos: "noun", ex: ["Wrap a clean bandage on the cut.", "Adhesive bandage for finger cuts."], exVn: ["Băng dải băng gạc sạch lên vết cắt.", "Băng dán cá nhân cho vết đứt tay."] },
    { word: "injection", phonetic: "/ɪnˈdʒekʃn/", def: "Administering liquid medicine via a needle.", defVn: "mũi tiêm thuốc, tiêm phòng", pos: "noun", ex: ["The routine vaccine injection.", "Relax your arm during injection."], exVn: ["Mũi tiêm vắc-xin định kỳ.", "Thả lỏng cánh tay trong lúc tiêm."] },
    { word: "prescription", phonetic: "/prɪˈskrɪpʃn/", def: "A doctor's written authorization for medicine.", defVn: "đơn thuốc của bác sĩ", pos: "noun", ex: ["Take the prescription to the pharmacy.", "The doctor wrote a prescription."], exVn: ["Mang đơn thuốc ra hiệu thuốc.", "Bác sĩ đã kê một đơn thuốc."] },
    { word: "allergy", phonetic: "/ˈælərdʒi/", def: "A damaging immune response to a substance.", defVn: "dị ứng thức ăn / thời tiết", pos: "noun", ex: ["He has a peanut allergy.", "Report allergies to your doctor."], exVn: ["Anh ấy bị dị ứng đậu phộng.", "Báo cho bác sĩ biết về các dị ứng."] },
    { word: "checkup", phonetic: "/ˈtʃekʌp/", def: "A thorough medical examination.", defVn: "khám sức khỏe định kỳ", pos: "noun", ex: ["An annual health checkup.", "The medical checkup took one hour."], exVn: ["Khám sức khỏe tổng quát hàng năm.", "Buổi khám sức khỏe mất một tiếng."] }
  ],

  // Theme 23: Dụng cụ nhà bếp
  t_basic_kitchen_utensils: [
    { word: "frying pan", phonetic: "/ˈfraɪɪŋ pæn/", def: "A shallow pan with a long handle used for frying.", defVn: "chảo rán, chảo chống dính", pos: "noun", ex: ["Fry an egg in the nonstick frying pan.", "Heat oil in the pan."], exVn: ["Rán một quả trứng trong chảo chống dính.", "Làm nóng dầu trong chảo."] },
    { word: "saucepan", phonetic: "/ˈsɔːspæn/", def: "A deep cooking pan with one handle and a lid.", defVn: "xoong nấu canh có cán", pos: "noun", ex: ["Boil soup in the stainless steel saucepan.", "Cover the saucepan with its lid."], exVn: ["Nấu súp trong chiếc xoong inox.", "Đậy vung xoong lại nhé."] },
    { word: "cutting board", phonetic: "/ˈkʌtɪŋ bɔːrd/", def: "A board for cutting food on.", defVn: "thớt thái (gỗ / nhựa)", pos: "noun", ex: ["Chop garlic on the wooden cutting board.", "Clean the cutting board after use."], exVn: ["Băm tỏi trên thớt gỗ.", "Rửa sạch thớt sau khi dùng."] },
    { word: "chopsticks", phonetic: "/ˈtʃɑːpstɪks/", def: "A pair of thin sticks used for eating.", defVn: "đôi đũa ăn cơm", pos: "noun", ex: ["Bamboo chopsticks are traditional utensils.", "Hold chopsticks properly."], exVn: ["Đũa tre là dụng cụ ăn uống truyền thống.", "Cầm đũa đúng cách nhé."] },
    { word: "spoon", phonetic: "/spuːn/", def: "An implement with a small oval bowl on a handle.", defVn: "chiếc thìa, muỗng", pos: "noun", ex: ["Stir sugar with a spoon.", "A soup spoon for hot broth."], exVn: ["Khuấy đường bằng thìa.", "Muỗng canh cho nước dùng nóng."] },
    { word: "fork", phonetic: "/fɔːrk/", def: "An implement with prongs used for eating.", defVn: "chiếc nĩa, dĩa ăn", pos: "noun", ex: ["Twirl noodles with a fork.", "Place the fork on the left."], exVn: ["Cuộn mì bằng nĩa.", "Đặt nĩa ở bên trái."] },
    { word: "bowl", phonetic: "/boʊl/", def: "A round deep dish for food or liquid.", defVn: "bát ăn cơm, tô canh", pos: "noun", ex: ["Eat a warm bowl of noodles.", "A ceramic soup bowl."], exVn: ["Ăn một bát bún nóng.", "Bát súp bằng sứ."] },
    { word: "plate", phonetic: "/pleɪt/", def: "A flat dish from which food is served.", defVn: "chiếc đĩa ăn", pos: "noun", ex: ["Serve spring rolls on the plate.", "Clear the dinner plates."], exVn: ["Bày nem rán lên đĩa.", "Dọn đĩa ăn tối."] },
    { word: "kettle", phonetic: "/ˈketl/", def: "A container for boiling water.", defVn: "ấm đun nước siêu tốc", pos: "noun", ex: ["Boil water in the electric kettle.", "Brew tea with hot kettle water."], exVn: ["Đun nước trong ấm siêu tốc.", "Pha trà bằng nước sôi từ ấm."] },
    { word: "microwave", phonetic: "/ˈmaɪkrəweɪv/", def: "An oven that cooks or warms food quickly with radiation.", defVn: "lò vi sóng", pos: "noun", ex: ["Heat soup in the microwave.", "Use microwave-safe bowls."], exVn: ["Hâm nóng súp trong lò vi sóng.", "Dùng bát an toàn cho lò vi sóng."] },
    { word: "blender", phonetic: "/ˈblendər/", def: "An electric machine for pureeing food or making smoothies.", defVn: "máy xay sinh tố", pos: "noun", ex: ["Blend fruit in the blender.", "Make a mango smoothie."], exVn: ["Xay hoa quả trong máy xay.", "Làm món sinh tố xoài."] },
    { word: "refrigerator", phonetic: "/rɪˈfrɪdʒəreɪtər/", def: "An appliance that keeps food cold; fridge.", defVn: "tủ lạnh gia đình", pos: "noun", ex: ["Store milk in the refrigerator.", "Close the refrigerator door."], exVn: ["Cất sữa trong tủ lạnh.", "Đóng cửa tủ lạnh lại nhé."] }
  ],

  // Theme 24: Văn phòng & Công nghệ
  t_basic_office_tech: [
    { word: "laptop", phonetic: "/ˈlæptɑːp/", def: "A portable personal computer.", defVn: "máy tính xách tay, laptop", pos: "noun", ex: ["Work on a lightweight laptop.", "Charge your laptop."], exVn: ["Làm việc trên chiếc laptop mỏng nhẹ.", "Sạc pin máy tính xách tay nhé."] },
    { word: "mouse", phonetic: "/maʊs/", def: "A handheld device controlling a computer cursor.", defVn: "chuột máy tính", pos: "noun", ex: ["Click with the wireless mouse.", "An ergonomic mouse."], exVn: ["Bấm bằng chuột không dây.", "Chuột công thái học."] },
    { word: "keyboard", phonetic: "/ˈkiːbɔːrd/", def: "A panel of keys for operating a computer.", defVn: "bàn phím máy tính", pos: "noun", ex: ["Type on the mechanical keyboard.", "Clean the keyboard keys."], exVn: ["Gõ trên bàn phím cơ.", "Vệ sinh các phím bàn phím."] },
    { word: "screen", phonetic: "/skriːn/", def: "A display on an electronic device.", defVn: "màn hình hiển thị", pos: "noun", ex: ["Look away from the screen.", "A high-resolution screen."], exVn: ["Nhìn ra xa khỏi màn hình.", "Màn hình độ phân giải cao."] },
    { word: "printer", phonetic: "/ˈprɪntər/", def: "A machine for printing text on paper.", defVn: "máy in tài liệu", pos: "noun", ex: ["Print double-sided with the printer.", "Load paper into the printer."], exVn: ["In hai mặt bằng máy in.", "Nạp giấy vào máy in."] },
    { word: "document", phonetic: "/ˈdɑːkjumənt/", def: "A piece of written or digital matter providing info.", defVn: "văn bản, tài liệu", pos: "noun", ex: ["Save the Word document.", "Attach documents to the email."], exVn: ["Lưu tài liệu Word lại.", "Đính kèm tài liệu vào email."] },
    { word: "folder", phonetic: "/ˈfoʊldər/", def: "A digital directory on a computer.", defVn: "thư mục dữ liệu", pos: "noun", ex: ["Create a new English folder.", "Organize audio files in folders."], exVn: ["Tạo một thư mục tiếng Anh mới.", "Sắp xếp tệp âm thanh vào thư mục."] },
    { word: "file", phonetic: "/faɪl/", def: "A collection of data stored under a name.", defVn: "tệp tin, tệp dữ liệu", pos: "noun", ex: ["Download the PDF study file.", "Back up essential files."], exVn: ["Tải tệp tài liệu PDF về.", "Sao lưu các tệp tin quan trọng."] },
    { word: "software", phonetic: "/ˈsɔːftwer/", def: "The programs used by a computer.", defVn: "phần mềm máy tính", pos: "noun", ex: ["Install English learning software.", "Update the computer software."], exVn: ["Cài đặt phần mềm học tiếng Anh.", "Cập nhật phần mềm máy tính."] },
    { word: "meeting", phonetic: "/ˈmiːtɪŋ/", def: "An assembly of people for discussion.", defVn: "cuộc họp, buổi họp", pos: "noun", ex: ["The morning team meeting starts at 9.", "Take notes during the meeting."], exVn: ["Cuộc họp nhóm buổi sáng bắt đầu lúc 9h.", "Ghi chép trong suốt cuộc họp."] },
    { word: "desk", phonetic: "/desk/", def: "A piece of furniture for writing and study.", defVn: "bàn làm việc, bàn học", pos: "noun", ex: ["Keep your desk tidy.", "A wooden study desk."], exVn: ["Giữ bàn học ngăn nắp.", "Bàn học bằng gỗ."] }
  ],

  // Theme 26: Tính cách & Phẩm chất
  t_basic_personality_traits: [
    { word: "honest", phonetic: "/ˈɑːnɪst/", def: "Free of deceit; truthful and sincere.", defVn: "trung thực, thật thà", pos: "adj", ex: ["An honest friend tells the truth.", "He gave an honest answer."], exVn: ["Người bạn trung thực luôn nói sự thật.", "Anh ấy đã trả lời thật thà."] },
    { word: "clever", phonetic: "/ˈklevər/", def: "Quick to understand and learn; intelligent.", defVn: "lanh lợi, thông minh", pos: "adj", ex: ["The clever student solved the puzzle.", "A clever idea."], exVn: ["Học sinh lanh lợi đã giải được câu đố.", "Một ý tưởng thông minh."] },
    { word: "polite", phonetic: "/pəˈlaɪt/", def: "Respectful and considerate of other people.", defVn: "lịch sự, lễ phép", pos: "adj", ex: ["Saying please and thank you is polite.", "A polite young boy."], exVn: ["Nói làm ơn và cảm ơn là cử chỉ lịch sự.", "Một cậu bé lễ phép."] },
    { word: "creative", phonetic: "/kriˈeɪtɪv/", def: "Involving imagination or original ideas.", defVn: "sáng tạo, giàu tưởng tượng", pos: "adj", ex: ["Creative thinkers solve big problems.", "She writes creative stories."], exVn: ["Những người có tư duy sáng tạo giải quyết vấn đề lớn.", "Cô ấy viết những câu chuyện đầy sáng tạo."] },
    { word: "cheerful", phonetic: "/ˈtʃɪrfl/", def: "Noticeably happy and optimistic.", defVn: "vui tươi, hớn hở", pos: "adj", ex: ["Her cheerful smile warmed the room.", "A cheerful greeting."], exVn: ["Nụ cười vui tươi của cô ấy làm ấm căn phòng.", "Lời chào hớn hở."] },
    { word: "hardworking", phonetic: "/ˌhɑːrdˈwɜːrkɪŋ/", def: "Working with energy and commitment.", defVn: "chăm chỉ, cần cù", pos: "adj", ex: ["Hardworking students achieve goals.", "My father is very hardworking."], exVn: ["Học sinh chăm chỉ sẽ đạt được mục tiêu.", "Bố tôi rất cần cù."] },
    { word: "calm", phonetic: "/kɑːm/", def: "Not showing or feeling nervousness or anger.", defVn: "bình tĩnh, điềm đạm", pos: "adj", ex: ["Stay calm during challenges.", "A calm and peaceful voice."], exVn: ["Hãy giữ bình tĩnh trong mọi thử thách.", "Giọng nói điềm đạm và bình yên."] },
    { word: "funny", phonetic: "/ˈfʌni/", def: "Causing laughter; humorous.", defVn: "hài hước, vui tính", pos: "adj", ex: ["He told a funny English joke.", "A funny movie."], exVn: ["Anh ấy kể câu chuyện cười tiếng Anh hài hước.", "Một bộ phim vui nhộn."] },
    { word: "shy", phonetic: "/ʃaɪ/", def: "Nervous or timid in the company of other people.", defVn: "nhút nhát, e thẹn", pos: "adj", ex: ["The shy child smiled gently.", "Don't be shy to speak English."], exVn: ["Đứa trẻ nhút nhát mỉm cười nhẹ nhàng.", "Đừng ngại ngùng khi nói tiếng Anh nhé."] },
    { word: "generous", phonetic: "/ˈdʒenərəs/", def: "Showing readiness to give more than expected.", defVn: "hào phóng, rộng lượng", pos: "adj", ex: ["A generous donation to poor kids.", "She is generous with her time."], exVn: ["Khoản quyên góp hào phóng cho trẻ em nghèo.", "Cô ấy rất rộng lượng chia sẻ thời gian."] },
    { word: "patient", phonetic: "/ˈpeɪʃnt/", def: "Able to tolerate delays or problems without anger.", defVn: "kiên nhẫn, nhẫn nại", pos: "adj", ex: ["Be patient when learning a language.", "A patient teacher."], exVn: ["Hãy kiên nhẫn khi học một ngôn ngữ.", "Một người giáo viên nhẫn nại."] },
    { word: "confident", phonetic: "/ˈkɑːnfɪdənt/", def: "Feeling self-assured and certain.", defVn: "tự tin, đĩnh đạc", pos: "adj", ex: ["Speak with a confident voice.", "She felt confident in the exam."], exVn: ["Hãy nói bằng giọng tự tin.", "Cô ấy cảm thấy tự tin trong kỳ thi."] },
    { word: "brave", phonetic: "/breɪv/", def: "Ready to face danger or pain; courageous.", defVn: "dũng cảm, can đảm", pos: "adj", ex: ["Brave firefighters saved the day.", "Be brave and try new things."], exVn: ["Những người lính cứu hỏa dũng cảm đã cứu nguy.", "Hãy can đảm và thử sức với những điều mới mẻ."] },
    { word: "humble", phonetic: "/ˈhʌmbl/", def: "Having a modest view of one's importance.", defVn: "khiêm tốn, nhún nhường", pos: "adj", ex: ["Great leaders remain humble.", "A humble and kind attitude."], exVn: ["Những nhà lãnh đạo vĩ đại luôn giữ đức tính khiêm tốn.", "Một thái độ khiêm nhường và tử tế."] }
  ],

  // Theme 27: Giới từ & Vị trí
  t_basic_prepositions_positions: [
    { word: "inside", phonetic: "/ˌɪnˈsaɪd/", def: "The inner part or interior of something.", defVn: "ở bên trong", pos: "preposition", ex: ["Step inside the warm room.", "Keep keys inside the bag."], exVn: ["Bước vào bên trong căn phòng ấm áp.", "Để chìa khóa bên trong túi xách."] },
    { word: "outside", phonetic: "/ˌaʊtˈsaɪd/", def: "The outer side or exterior; outdoors.", defVn: "ở bên ngoài, ngoài trời", pos: "preposition", ex: ["Children play outside.", "Leave shoes outside."], exVn: ["Trẻ em chơi đùa ngoài trời.", "Để giày dép ở bên ngoài."] },
    { word: "underneath", phonetic: "/ˌʌndərˈniːθ/", def: "Directly below something.", defVn: "ở ngay dưới đáy, bên dưới", pos: "preposition", ex: ["The cat slept underneath the sofa.", "Underneath the table."], exVn: ["Chú mèo ngủ ngay dưới ghế sô-pha.", "Bên dưới chiếc bàn."] },
    { word: "above", phonetic: "/əˈbʌv/", def: "At a higher level than.", defVn: "ở phía trên cao", pos: "preposition", ex: ["The lamp hangs above the desk.", "Birds fly above."], exVn: ["Chiếc đèn treo phía trên bàn học.", "Chim bay lượn trên cao."] },
    { word: "below", phonetic: "/bɪˈloʊ/", def: "At a lower level than.", defVn: "ở phía dưới thấp", pos: "preposition", ex: ["The valley lies far below.", "Sign your name below."], exVn: ["Thung lũng nằm sâu phía dưới.", "Ký tên bạn ở phía dưới nhé."] },
    { word: "between", phonetic: "/bɪˈtwiːn/", def: "In the space separating two points.", defVn: "ở giữa (hai vật/người)", pos: "preposition", ex: ["Sit between your parents.", "The shop between the bank and post office."], exVn: ["Ngồi ở giữa bố mẹ nhé.", "Cửa hàng nằm giữa ngân hàng và bưu điện."] },
    { word: "among", phonetic: "/əˈmʌŋ/", def: "In the middle of several things or people.", defVn: "ở giữa (nhiều vật/người)", pos: "preposition", ex: ["A cabin among tall pine trees.", "Happy among friends."], exVn: ["Ngôi nhà gỗ giữa những rặng thông cao.", "Hạnh phúc giữa bạn bè."] },
    { word: "behind", phonetic: "/bɪˈhaɪnd/", def: "At the back of someone or something.", defVn: "ở phía sau, đằng sau", pos: "preposition", ex: ["The sun set behind the mountain.", "Wait behind the line."], exVn: ["Mặt trời lặn sau dãy núi.", "Đứng đợi sau vạch kẻ nhé."] },
    { word: "in front of", phonetic: "/ɪn frʌnt əv/", def: "Located further forward than.", defVn: "ở đằng trước mặt", pos: "phrase", ex: ["A mango tree in front of our house.", "Stand in front of the board."], exVn: ["Cây xoài ở trước cửa nhà chúng tôi.", "Đứng trước bảng nhé."] },
    { word: "next to", phonetic: "/nekst tuː/", def: "Beside or adjacent to.", defVn: "ở bên cạnh, sát bên", pos: "phrase", ex: ["Sit next to me in class.", "The clinic next to the pharmacy."], exVn: ["Ngồi cạnh tôi trong lớp nhé.", "Phòng khám ở ngay sát bên hiệu thuốc."] },
    { word: "opposite", phonetic: "/ˈɑːpəzɪt/", def: "Facing on the other side.", defVn: "ở đối diện", pos: "preposition", ex: ["The bus stop opposite the school.", "Sit opposite each other."], exVn: ["Trạm xe buýt đối diện cổng trường.", "Ngồi đối diện nhau."] },
    { word: "near", phonetic: "/nɪr/", def: "At a short distance away.", defVn: "ở gần, gần bên", pos: "preposition", ex: ["We live near the city lake.", "Is there a cafe near here?"], exVn: ["Chúng tôi sống gần hồ thành phố.", "Có quán cà phê nào gần đây không?"] },
    { word: "far", phonetic: "/fɑːr/", def: "At a great distance.", defVn: "ở xa, xa xôi", pos: "adverb", ex: ["The airport is not far away.", "Travel far across oceans."], exVn: ["Sân bay không hề xa.", "Du hành xa qua đại dương."] },
    { word: "around", phonetic: "/əˈraʊnd/", def: "Located on every side of; surrounding.", defVn: "xung quanh, vòng quanh", pos: "preposition", ex: ["Walk around the park.", "Trees around the house."], exVn: ["Đi dạo vòng quanh công viên.", "Cây cối bao quanh ngôi nhà."] }
  ],

  // Theme 31: Đo lường & Kích cỡ
  t_basic_measurements_sizes: [
    { word: "meter", phonetic: "/ˈmiːtər/", def: "The fundamental unit of length; 100 cm.", defVn: "mét (đơn vị đo chiều dài)", pos: "noun", ex: ["The pool is 50 meters long.", "Jump two meters."], exVn: ["Hồ bơi dài 50 mét.", "Nhảy cao hai mét."] },
    { word: "centimeter", phonetic: "/ˈsentɪmiːtər/", def: "One hundredth of a meter (cm).", defVn: "xen-ti-mét (cm)", pos: "noun", ex: ["A 30-centimeter ruler.", "The plant grew five centimeters."], exVn: ["Thước kẻ 30 cm.", "Cây cao thêm 5 cm."] },
    { word: "kilometer", phonetic: "/kɪˈlɑːmɪtər/", def: "A metric unit equal to 1,000 meters (km).", defVn: "ki-lô-mét, cây số", pos: "noun", ex: ["A 10-kilometer run.", "It is five kilometers away."], exVn: ["Chạy bộ cự ly 10 km.", "Cách đây 5 cây số."] },
    { word: "gram", phonetic: "/ɡræm/", def: "A unit of mass equal to 1/1000 of a kilogram.", defVn: "gam, gram (g)", pos: "noun", ex: ["Add 100 grams of sugar.", "Weighs 200 grams."], exVn: ["Thêm 100 gam đường.", "Nặng 200 gam."] },
    { word: "kilogram", phonetic: "/ˈkɪləɡræm/", def: "A unit of mass equal to 1,000 grams (kg).", defVn: "ki-lô-gam, ký (kg)", pos: "noun", ex: ["Buy two kilograms of apples.", "Lost three kilograms."], exVn: ["Mua 2 kg táo.", "Giảm 3 ký."] },
    { word: "liter", phonetic: "/ˈliːtər/", def: "A metric unit of volume capacity.", defVn: "lít (dung tích)", pos: "noun", ex: ["Drink two liters of water daily.", "One liter of milk."], exVn: ["Uống 2 lít nước mỗi ngày.", "Một lít sữa tươi."] },
    { word: "height", phonetic: "/haɪt/", def: "Measurement from base to top.", defVn: "chiều cao, độ cao", pos: "noun", ex: ["What is your height? — 1.7 meters.", "Building height."], exVn: ["Chiều cao của bạn là bao nhiêu? — 1m70.", "Chiều cao tòa nhà."] },
    { word: "weight", phonetic: "/weɪt/", def: "A body's relative mass.", defVn: "cân nặng, trọng lượng", pos: "noun", ex: ["Check weight on the scale.", "Luggage weight limit."], exVn: ["Kiểm tra cân nặng trên chiếc cân.", "Giới hạn trọng lượng hành lý."] },
    { word: "length", phonetic: "/leŋkθ/", def: "Measurement from end to end.", defVn: "chiều dài, độ dài", pos: "noun", ex: ["Measure the board's length.", "The bridge length is 1 km."], exVn: ["Đo chiều dài thanh gỗ.", "Chiều dài cây cầu là 1 km."] },
    { word: "width", phonetic: "/wɪdθ/", def: "Measurement from side to side.", defVn: "chiều rộng, bề ngang", pos: "noun", ex: ["Measure the door width.", "Width of the street."], exVn: ["Đo chiều rộng cửa ra vào.", "Chiều rộng của con đường."] },
    { word: "depth", phonetic: "/depθ/", def: "Distance from top to bottom.", defVn: "độ sâu, chiều sâu", pos: "noun", ex: ["Pool depth is two meters.", "Ocean depths."], exVn: ["Độ sâu hồ bơi là hai mét.", "Những tầng sâu đại dương."] },
    { word: "heavy", phonetic: "/ˈhevi/", def: "Of great weight; hard to lift.", defVn: "nặng nề, nặng cân", pos: "adj", ex: ["This heavy suitcase.", "Elephants are heavy."], exVn: ["Chiếc va-li nặng này.", "Voi rất nặng cân."] },
    { word: "light", phonetic: "/laɪt/", def: "Of little weight; not heavy.", defVn: "nhẹ nhàng, nhẹ cân", pos: "adj", ex: ["A feather is light.", "A light winter jacket."], exVn: ["Một chiếc lông vũ rất nhẹ.", "Áo khoác mùa đông mỏng nhẹ."] },
    { word: "narrow", phonetic: "/ˈnæroʊ/", def: "Of small width.", defVn: "hẹp, chật hẹp", pos: "adj", ex: ["A narrow brick alley in Hanoi.", "A narrow path."], exVn: ["Con ngõ gạch nhỏ hẹp ở Hà Nội.", "Một lối mòn hẹp."] }
  ],

  // Theme 49: Chất liệu & Vật liệu
  t_basic_materials_substances: [
    { word: "timber", phonetic: "/ˈtɪmbər/", def: "Wood prepared for use in building and carpentry.", defVn: "gỗ xây dựng, gỗ xẻ", pos: "noun", ex: ["Solid timber for wooden houses.", "Sustainable timber sources."], exVn: ["Gỗ xẻ chắc chắn để dựng nhà gỗ.", "Nguồn gỗ xây dựng bền vững."] },
    { word: "aluminum", phonetic: "/əˈluːmɪnəm/", def: "A lightweight silvery-white metal.", defVn: "nhôm (siêu nhẹ)", pos: "noun", ex: ["Bicycle frames made of aluminum.", "Recycle aluminum cans."], exVn: ["Khung xe đạp làm bằng nhôm.", "Tái chế lon nhôm nhé."] },
    { word: "copper", phonetic: "/ˈkɑːpər/", def: "A red-brown metal that conducts electricity.", defVn: "đồng đỏ dẫn điện", pos: "noun", ex: ["Electrical wires contain copper.", "A shiny copper pot."], exVn: ["Dây điện có chứa đồng.", "Một chiếc nồi đồng sáng bóng."] },
    { word: "bronze", phonetic: "/brɑːnz/", def: "A yellowish-brown alloy of copper and tin.", defVn: "đồng thau, đồng thiếc", pos: "noun", ex: ["Ancient Dong Son bronze drums.", "A bronze sculpture."], exVn: ["Trống đồng Đông Sơn cổ kính.", "Tượng điêu khắc bằng đồng."] },
    { word: "porcelain", phonetic: "/ˈpɔːrsəlɪn/", def: "A white vitrified translucent ceramic; china.", defVn: "đồ gốm sứ trắng cao cấp", pos: "noun", ex: ["Bat Trang fine porcelain teacups.", "Delicate porcelain vase."], exVn: ["Tách trà gốm sứ Bát Tràng tinh xảo.", "Chiếc lọ hoa bằng sứ cao cấp."] },
    { word: "linen", phonetic: "/ˈlɪnɪn/", def: "Cloth woven from flax.", defVn: "vải đũi, vải lanh thoáng mát", pos: "noun", ex: ["Breathable linen shirts in summer.", "Pure linen bedsheets."], exVn: ["Áo vải đũi thoáng mát vào mùa hè.", "Ga trải giường bằng vải lanh."] },
    { word: "velvet", phonetic: "/ˈvelvɪt/", def: "A closely woven fabric of silk or cotton with a thick short pile.", defVn: "vải nhung mềm mại quý phái", pos: "noun", ex: ["A soft red velvet dress.", "Plush velvet cushions."], exVn: ["Chiếc váy nhung đỏ mềm mại.", "Những chiếc đệm nhung êm ái."] },
    { word: "marble", phonetic: "/ˈmɑːrbl/", def: "A hard crystalline metamorphic form of limestone.", defVn: "đá cẩm thạch sang trọng", pos: "noun", ex: ["Da Nang Marble Mountains.", "Polished marble floor."], exVn: ["Ngũ Hành Sơn đá cẩm thạch ở Đà Nẵng.", "Sàn nhà lát đá cẩm thạch bóng loáng."] },
    { word: "granite", phonetic: "/ˈɡrænɪt/", def: "A very hard, granular, crystalline igneous rock.", defVn: "đá hoa cương cứng cáp", pos: "noun", ex: ["Granite kitchen countertops.", "Solid granite steps."], exVn: ["Mặt bàn bếp bằng đá hoa cương.", "Những bậc thềm đá hoa cương vững chãi."] },
    { word: "wax", phonetic: "/wæks/", def: "A sticky yellowish moldable substance.", defVn: "sáp ong, sáp nến", pos: "noun", ex: ["Natural beeswax candles.", "Melted candle wax."], exVn: ["Nến làm từ sáp ong tự nhiên.", "Sáp nến nóng chảy."] },
    { word: "crystal", phonetic: "/ˈkrɪstl/", def: "A piece of a homogeneous solid substance having a natural geometrically regular form.", defVn: "pha lê lấp lánh", pos: "noun", ex: ["Sparkling crystal chandelier.", "A crystal clear glass."], exVn: ["Đèn chùm pha lê lấp lánh.", "Chiếc ly pha lê trong suốt."] },
    { word: "bamboo", phonetic: "/ˌbæmˈbuː/", def: "A fast-growing woody grass.", defVn: "cây tre, nan tre", pos: "noun", ex: ["Handmade bamboo baskets.", "Bamboo flooring."], exVn: ["Những chiếc rổ tre đan thủ công.", "Sàn nhà bằng tre."] },
    { word: "straw", phonetic: "/strɔː/", def: "Dried stalks of grain, used as fodder or for thatched roofs.", defVn: "rơm rạ, rơm khô", pos: "noun", ex: ["A straw hat for sunny days.", "Golden straw roof."], exVn: ["Chiếc mũ rơm che ngày nắng.", "Mái nhà lợp rơm vàng óng."] },
    { word: "canvas", phonetic: "/ˈkænvəs/", def: "A strong, unbleached cloth used for making sails and tents.", defVn: "vải bạt, vải bố vẽ tranh", pos: "noun", ex: ["Paint an oil painting on canvas.", "A durable canvas tote bag."], exVn: ["Vẽ tranh sơn dầu trên tấm vải bố.", "Túi xách vải bạt rất bền."] },
    { word: "foam", phonetic: "/foʊm/", def: "A mass of small bubbles formed on or in liquid, or a light spongy rubber.", defVn: "mút xốp, bọt mềm", pos: "noun", ex: ["Memory foam mattress.", "Milk foam on bubble tea."], exVn: ["Nệm mút xốp nâng đỡ cơ thể.", "Lớp bọt sữa trên ly trà sữa."] }
  ],

  // Theme 52: Vận động cơ thể
  t_basic_body_movements: [
    { word: "jog", phonetic: "/dʒɑːɡ/", def: "Run at a steady, gentle pace, especially as a form of physical exercise.", defVn: "chạy bộ chậm rãi, chạy rèn luyện", pos: "verb", ex: ["Jog around West Lake in the morning.", "He jogs three miles daily."], exVn: ["Chạy bộ quanh Hồ Tây vào buổi sáng.", "Anh ấy chạy bộ 3 dặm mỗi ngày."] },
    { word: "sprint", phonetic: "/sprɪnt/", def: "Run at full speed over a short distance.", defVn: "chạy nước rút tốc độ cao", pos: "verb", ex: ["Sprint to catch the departing bus.", "Athletes sprint 100 meters."], exVn: ["Chạy nước rút để kịp chiếc xe buýt.", "Các vận động viên chạy nước rút 100 mét."] },
    { word: "leap", phonetic: "/liːp/", def: "Jump or spring a long way, to a great height.", defVn: "bật nhảy xa, nhảy vọt", pos: "verb", ex: ["The dancer leaped gracefully across the stage.", "Leap over puddles."], exVn: ["Vũ công bật nhảy duyên dáng qua sân khấu.", "Nhảy qua những vũng nước mưa."] },
    { word: "skip", phonetic: "/skɪp/", def: "Move along lightly, stepping from one foot to the other with a hop.", defVn: "nhảy chân sáo, nhảy dây", pos: "verb", ex: ["Children skip happily on the sidewalk.", "Skip rope for cardio exercise."], exVn: ["Lũ trẻ nhảy chân sáo vui vẻ trên vỉa hè.", "Nhảy dây để rèn luyện tim mạch."] },
    { word: "spin", phonetic: "/spɪn/", def: "Turn or cause to turn round and round quickly.", defVn: "xoay tròn, quay vòng", pos: "verb", ex: ["The ice skater spun fast on the ice.", "Spin the prize wheel."], exVn: ["Vận động viên trượt băng xoay tròn tít trên băng.", "Quay vòng quay may mắn."] },
    { word: "tiptoe", phonetic: "/ˈtɪptoʊ/", def: "Walk quietly and carefully on one's toes.", defVn: "đi nhón chân rón rén", pos: "verb", ex: ["Tiptoe quietly past the sleeping baby.", "She tiptoed into the room."], exVn: ["Đi nhón chân rón rén qua em bé đang ngủ.", "Cô ấy rón rén bước vào phòng."] },
    { word: "dodge", phonetic: "/dɑːdʒ/", def: "Avoid someone or something by a sudden quick movement.", defVn: "né tránh, lách người tránh", pos: "verb", ex: ["Dodge the oncoming soccer ball.", "Dodge obstacles on the path."], exVn: ["Né quả bóng đá đang bay tới.", "Lách người tránh chướng ngại vật trên đường."] },
    { word: "lean", phonetic: "/liːn/", def: "Be in or move into a sloping position.", defVn: "dựa vào, tựa lưng", pos: "verb", ex: ["Lean back and relax on the sofa.", "Don't lean against the glass door."], exVn: ["Tựa lưng ra sau và thư giãn trên ghế sô-pha.", "Không tựa vào cửa kính nhé."] },
    { word: "squat", phonetic: "/skwɑːt/", def: "Crouch or sit with one's knees bent and one's heels close to or touching one's buttocks.", defVn: "ngồi xổm, tập squat", pos: "verb", ex: ["Do ten bodyweight squats to strengthen legs.", "Squat down to pick up keys."], exVn: ["Tập mười cái squat để đôi chân chắc khỏe.", "Ngồi xổm xuống để nhặt chìa khóa."] },
    { word: "bow", phonetic: "/baʊ/", def: "Bend the head or upper part of the body as a sign of respect.", defVn: "cúi đầu chào cung kính", pos: "verb", ex: ["Bow respectfully to your teacher.", "The actors bowed after the show."], exVn: ["Cúi đầu chào kính trọng thầy cô giáo.", "Các diễn viên cúi đầu cảm ơn sau buổi diễn."] },
    { word: "crouch", phonetic: "/kraʊtʃ/", def: "Adopt a position where the knees are bent and upper body is brought forward.", defVn: "ngồi khom người, nép mình", pos: "verb", ex: ["Crouch low to stay out of sight.", "He crouched behind the hedge."], exVn: ["Ngồi nép mình thấp xuống để không bị nhìn thấy.", "Anh ấy khom người sau hàng rào cây."] },
    { word: "crawl", phonetic: "/krɔːl/", def: "Move forward on hands and knees.", defVn: "bò trườn", pos: "verb", ex: ["The baby crawls across the rug.", "Crawled under the fence."], exVn: ["Em bé bò qua tấm thảm.", "Bò luồn qua hàng rào."] },
    { word: "flex", phonetic: "/fleks/", def: "Bend or contract a muscle or limb.", defVn: "gồng cơ, uốn dẻo", pos: "verb", ex: ["Flex your arm muscles.", "Flex your feet during stretching."], exVn: ["Gồng cơ bắp tay.", "Uốn cong bàn chân khi kéo giãn cơ."] },
    { word: "reach", phonetic: "/riːtʃ/", def: "Stretch out an arm in a specified direction in order to touch or grasp something.", defVn: "với tay tới, chạm tới", pos: "verb", ex: ["Reach high for the top shelf book.", "Reach for your English dreams."], exVn: ["Với tay lên cao lấy cuốn sách trên giá cao.", "Hãy vươn tới những ước mơ tiếng Anh của bạn."] },
    { word: "shrug", phonetic: "/ʃrʌɡ/", def: "Raise one's shoulders slightly and momentarily to express doubt, ignorance, or indifference.", defVn: "nhún vai biểu thị không biết", pos: "verb", ex: ["He shrugged his shoulders and smiled.", "Shrug in response."], exVn: ["Anh ấy nhún vai và mỉm cười.", "Nhún vai để đáp lại."] }
  ],

  // Theme 57: Giai đoạn cuộc đời
  t_basic_life_stages_age: [
    { word: "newborn", phonetic: "/ˈnuːbɔːrn/", def: "A child or animal that has recently been born.", defVn: "trẻ sơ sinh mới chào đời", pos: "noun", ex: ["Cradle the sweet newborn baby gently.", "Newborns sleep most of the day."], exVn: ["Bế em bé mới chào đời thật nhẹ nhàng.", "Trẻ sơ sinh ngủ phần lớn thời gian trong ngày."] },
    { word: "grown-up", phonetic: "/ˈɡroʊn ʌp/", def: "An adult, especially regarded as an authority figure by a child.", defVn: "người lớn, người đã trưởng thành", pos: "noun", ex: ["Ask a grown-up for help when crossing.", "When I become a grown-up."], exVn: ["Nhờ người lớn giúp đỡ khi sang đường nhé.", "Khi tôi trở thành người lớn."] },
    { word: "senior", phonetic: "/ˈsiːniər/", def: "An elderly person, especially one who is retired; senior citizen.", defVn: "người cao niên, bậc cao niên", pos: "noun", ex: ["Discounts for seniors on public transit.", "Respect our community seniors."], exVn: ["Giảm giá cho người cao tuổi trên phương tiện công cộng.", "Hãy kính trọng các bậc cao niên trong cộng đồng."] },
    { word: "teen", phonetic: "/tiːn/", def: "A teenager (13-19 years).", defVn: "tuổi thiếu niên, tuổi teen", pos: "noun", ex: ["Teens love discovering new hobbies.", "A magazine for teens."], exVn: ["Các bạn tuổi teen rất thích khám phá những sở thích mới.", "Tạp chí dành cho tuổi thiếu niên."] },
    { word: "adolescent", phonetic: "/ˌædəˈlesnt/", def: "A young person in the process of developing from a child into an adult.", defVn: "vị thành niên, tuổi thanh thiếu niên", pos: "noun", ex: ["Adolescents learn independence.", "Support healthy adolescent growth."], exVn: ["Thanh thiếu niên học cách sống tự lập.", "Hỗ trợ sự phát triển lành mạnh của lứa tuổi vị thành niên."] },
    { word: "middle-aged", phonetic: "/ˌmɪdl ˈeɪdʒd/", def: "Of a person aged between about 45 and 65.", defVn: "tuổi trung niên (45-65 tuổi)", pos: "adj", ex: ["Middle-aged professionals lead industries.", "Maintain fitness in middle age."], exVn: ["Các chuyên gia tuổi trung niên dẫn dắt các ngành công nghiệp.", "Giữ gìn thể lực ở tuổi trung niên."] },
    { word: "boyhood", phonetic: "/ˈbɔɪhʊd/", def: "The state or time of being a boy.", defVn: "thời niên thiếu bé trai", pos: "noun", ex: ["Memories of boyhood summer games.", "Boyhood adventures."], exVn: ["Kỷ niệm về những trò chơi mùa hè thời niên thiếu.", "Những cuộc phiêu lưu thời niên thiếu."] },
    { word: "girlhood", phonetic: "/ˈɡɜːrlhʊd/", def: "The state or time of being a girl.", defVn: "thời niên thiếu bé gái", pos: "noun", ex: ["Stories of her sweet girlhood.", "Girlhood friendships."], exVn: ["Những câu chuyện về thời thiếu nữ ngọt ngào của cô.", "Tình bạn thời niên thiếu."] },
    { word: "milestone", phonetic: "/ˈmaɪlstoʊn/", def: "An action or event marking a significant change or stage in development.", defVn: "cột mốc quan trọng cuộc đời", pos: "noun", ex: ["Graduation is a major life milestone.", "Celebrate each learning milestone."], exVn: ["Tốt nghiệp là một cột mốc lớn trong cuộc đời.", "Hãy ăn mừng từng cột mốc học tập nhé."] },
    { word: "career", phonetic: "/kəˈrɪr/", def: "An occupation undertaken for a significant period of a person's life.", defVn: "sự nghiệp, con đường công danh", pos: "noun", ex: ["Build a rewarding international career.", "English advances your career."], exVn: ["Xây dựng sự nghiệp quốc tế đầy triển vọng.", "Tiếng Anh thúc đẩy sự nghiệp của bạn."] },
    { word: "future", phonetic: "/ˈfjuːtʃər/", def: "A period of time following the moment of speaking or writing.", defVn: "tương lai tươi sáng", pos: "noun", ex: ["Study hard for a bright future.", "The future belongs to those who believe."], exVn: ["Học tập chăm chỉ cho một tương lai tươi sáng.", "Tương lai thuộc về những ai có niềm tin."] },
    { word: "destiny", phonetic: "/ˈdestəni/", def: "The events that will necessarily happen to a person or thing in the future.", defVn: "vận mệnh, định mệnh tươi đẹp", pos: "noun", ex: ["You shape your own bright destiny.", "Fulfil your true destiny."], exVn: ["Bạn tự kiến tạo nên vận mệnh tươi sáng của chính mình.", "Thực hiện sứ mệnh đích thực của bạn."] },
    { word: "past", phonetic: "/pæst/", def: "Gone by in time and no longer existing.", defVn: "quá khứ, ngày hôm qua", pos: "noun", ex: ["Learn from the past and live in the present.", "Cherished past memories."], exVn: ["Học từ quá khứ và sống trọn vẹn trong hiện tại.", "Những kỷ niệm êm đềm của ngày hôm qua."] },
    { word: "present", phonetic: "/ˈpreznt/", def: "The period of time now occurring.", defVn: "hiện tại (món quà của cuộc sống)", pos: "noun", ex: ["Today is a gift, that is why it is called the present.", "Live fully in the present."], exVn: ["Hôm nay là một món quà, đó là lý do nó được gọi là hiện tại.", "Hãy sống trọn vẹn trong từng phút giây hiện tại."] },
    { word: "memory", phonetic: "/ˈmeməri/", def: "Something remembered from the past; a recollection.", defVn: "kỷ niệm, ký ức đẹp", pos: "noun", ex: ["Create beautiful memories with family.", "A treasure chest of memories."], exVn: ["Tạo dựng những kỷ niệm đẹp bên gia đình.", "Một rương kho báu chứa đầy ký ức."] }
  ]
};
