module.exports = {
  // Theme 1: Chào hỏi & Giao tiếp (Greetings)
  t_basic_greetings: [
    { word: "howdy", phonetic: "/ˈhaʊdi/", def: "An informal friendly greeting; hello.", defVn: "chào bạn (thân mật)", pos: "interjection", ex: ["Howdy, partner! How was your day?", "He waved and gave a cheerful howdy."], exVn: ["Chào bạn thân mến! Ngày của bạn thế nào?", "Anh ấy vẫy tay và cất lời chào vui vẻ."] },
    { word: "welcome", phonetic: "/ˈwelkəm/", def: "Greeting someone politely on their arrival.", defVn: "chào mừng, đón tiếp", pos: "interjection", ex: ["Welcome to our English class!", "You are always welcome here."], exVn: ["Chào mừng bạn đến với lớp tiếng Anh của chúng tôi!", "Bạn luôn luôn được chào đón tại đây."] },
    { word: "pleasure", phonetic: "/ˈpleʒər/", def: "A feeling of happy satisfaction and enjoyment.", defVn: "niềm hân hạnh, điều vinh dự", pos: "noun", ex: ["It is a great pleasure to meet you.", "My pleasure to help you."], exVn: ["Thật là một niềm vinh dự lớn khi được gặp bạn.", "Rất hân hạnh được giúp đỡ bạn."] },
    { word: "farewell", phonetic: "/ˌferˈwel/", def: "An act of parting or of marking departure; goodbye.", defVn: "lời tạm biệt, chia tay", pos: "noun", ex: ["We bid farewell to our dear friends.", "She attended the farewell party."], exVn: ["Chúng tôi gửi lời tạm biệt tới những người bạn thân thương.", "Cô ấy đã tham dự bữa tiệc chia tay."] },
    { word: "pardon", phonetic: "/ˈpɑːrdn/", def: "Used to ask someone to repeat what they have just said.", defVn: "xin thứ lỗi, xin nhắc lại", pos: "interjection", ex: ["Pardon me, could you say that again?", "I beg your pardon, I did not hear."], exVn: ["Xin thứ lỗi, bạn có thể nói lại điều đó được không?", "Xin thứ lỗi, tôi đã không nghe rõ."] }
  ],

  // Theme 3: Số đếm & Thứ tự
  t_basic_numbers: [
    { word: "twenty", phonetic: "/ˈtwenti/", def: "The number equivalent to the product of two and ten; 20.", defVn: "số hai mươi (20)", pos: "noun", ex: ["There are twenty students in the class.", "She scored twenty points."], exVn: ["Có 20 học sinh trong lớp học.", "Cô ấy đã ghi được 20 điểm."] },
    { word: "thirty", phonetic: "/ˈθɜːrti/", def: "The number equivalent to the product of three and ten; 30.", defVn: "số ba mươi (30)", pos: "noun", ex: ["Each lesson takes thirty minutes.", "September has thirty days."], exVn: ["Mỗi bài học kéo dài 30 phút.", "Tháng Chín có 30 ngày."] },
    { word: "forty", phonetic: "/ˈfɔːrti/", def: "The number equivalent to the product of four and ten; 40.", defVn: "số bốn mươi (40)", pos: "noun", ex: ["The bus seats forty passengers.", "He is forty years old."], exVn: ["Chiếc xe buýt chở được 40 hành khách.", "Anh ấy 40 tuổi."] },
    { word: "fifty", phonetic: "/ˈfɪfti/", def: "The number equivalent to the product of five and ten; 50.", defVn: "số năm mươi (50)", pos: "noun", ex: ["He learned fifty new words.", "The speed limit is fifty."], exVn: ["Cậu ấy đã học 50 từ mới.", "Tốc độ giới hạn là 50."] },
    { word: "billion", phonetic: "/ˈbɪljən/", def: "The number equivalent to 1,000,000,000.", defVn: "một tỷ (1.000.000.000)", pos: "noun", ex: ["Over eight billion people live on Earth.", "The company earned one billion."], exVn: ["Hơn 8 tỷ người đang sống trên Trái Đất.", "Công ty đã kiếm được một tỷ."] },
    { word: "dozen", phonetic: "/ˈdʌzn/", def: "A group or set of twelve.", defVn: "một tá (12 cái)", pos: "noun", ex: ["She bought a dozen fresh eggs.", "A dozen roses were on the table."], exVn: ["Cô ấy đã mua một tá trứng tươi.", "Một tá hoa hồng đặt trên bàn."] },
    { word: "quarter", phonetic: "/ˈkwɔːrtər/", def: "One of four equal parts; 1/4.", defVn: "một phần tư (1/4)", pos: "noun", ex: ["Cut the pie into four quarters.", "It is a quarter past six."], exVn: ["Cắt chiếc bánh thành 4 phần tư.", "Bây giờ là 6 giờ 15 phút."] },
    { word: "calculate", phonetic: "/ˈkælkjuleɪt/", def: "Determine the amount mathematically.", defVn: "tính toán, làm tính", pos: "verb", ex: ["Calculate the total expenses.", "Use a machine to calculate."], exVn: ["Tính toán tổng chi phí.", "Dùng máy để tính toán."] }
  ],

  // Theme 4: Màu sắc & Hình khối
  t_basic_colors_shapes: [
    { word: "crimson", phonetic: "/ˈkrɪmzn/", def: "Of a rich deep red color.", defVn: "màu đỏ thắm, đỏ thẫm", pos: "adj", ex: ["Autumn leaves turned crimson.", "She wore a crimson scarf."], exVn: ["Lá mùa thu chuyển sang màu đỏ thắm.", "Cô ấy quàng chiếc khăn màu đỏ thẫm."] },
    { word: "azure", phonetic: "/ˈæʒər/", def: "Bright cyan-blue in color like the sky.", defVn: "màu xanh da trời, xanh biếc", pos: "adj", ex: ["Birds flew across the azure sky.", "The sea has an azure color."], exVn: ["Những chú chim bay trên bầu trời xanh biếc.", "Biển có màu xanh da trời."] },
    { word: "emerald", phonetic: "/ˈemərəld/", def: "A bright green color.", defVn: "màu xanh ngọc lục bảo", pos: "adj", ex: ["The lake is emerald green.", "She has an emerald necklace."], exVn: ["Hồ nước có màu xanh ngọc lục bảo.", "Cô ấy có chiếc vòng cổ ngọc lục bảo."] },
    { word: "turquoise", phonetic: "/ˈtɜːrkwɔɪz/", def: "A greenish-blue color.", defVn: "màu xanh ngọc lam", pos: "adj", ex: ["The beach water is turquoise.", "A turquoise gemstone."], exVn: ["Nước biển có màu xanh ngọc lam.", "Một viên đá quý màu ngọc lam."] },
    { word: "cube", phonetic: "/kjuːb/", def: "A symmetrical three-dimensional shape with six equal squares.", defVn: "khối lập phương, khối vuông", pos: "noun", ex: ["Put two ice cubes in the tea.", "A wooden puzzle cube."], exVn: ["Cho hai viên đá vuông vào trà.", "Khối xếp hình lập phương bằng gỗ."] },
    { word: "cylinder", phonetic: "/ˈsɪlɪndər/", def: "A solid geometric figure with straight parallel sides.", defVn: "hình trụ, khối trụ", pos: "noun", ex: ["The can is a metal cylinder.", "Roll the clay into a cylinder."], exVn: ["Lon nước là một khối trụ kim loại.", "Lăn đất sét thành khối trụ."] },
    { word: "cone", phonetic: "/koʊn/", def: "An object that tapers smoothly from a circular base.", defVn: "hình nón (như nón lá)", pos: "noun", ex: ["The hat has the shape of a cone.", "An ice cream cone."], exVn: ["Chiếc nón có hình chóp nón.", "Cây kem ốc quế."] }
  ],

  // Theme 5: Gia đình & Người thân
  t_basic_family: [
    { word: "ancestor", phonetic: "/ˈænsestər/", def: "A person from whom one is descended.", defVn: "tổ tiên, ông bà tổ phụ", pos: "noun", ex: ["Honor ancestors during holidays.", "Stories from our ancestors."], exVn: ["Tưởng nhớ tổ tiên trong các ngày lễ.", "Những câu chuyện từ tổ tiên chúng ta."] },
    { word: "descendant", phonetic: "/dɪˈsendənt/", def: "A person descended from a particular ancestor.", defVn: "con cháu, hậu duệ", pos: "noun", ex: ["Descendants gathered at the reunion.", "We are proud descendants."], exVn: ["Con cháu tụ họp tại buổi sum họp.", "Chúng ta là những hậu duệ tự hào."] },
    { word: "sibling", phonetic: "/ˈsɪblɪŋ/", def: "A brother or sister.", defVn: "anh chị em ruột", pos: "noun", ex: ["I have two younger siblings.", "Siblings help each other."], exVn: ["Tôi có hai người em ruột.", "Anh chị em giúp đỡ lẫn nhau."] },
    { word: "twin", phonetic: "/twɪn/", def: "One of two children born at the same birth.", defVn: "sinh đôi, sinh ba", pos: "noun", ex: ["The twin brothers look identical.", "Twin girls dressed alike."], exVn: ["Hai anh em sinh đôi trông giống hệt nhau.", "Hai bé gái sinh đôi mặc đồ giống nhau."] },
    { word: "nephew", phonetic: "/ˈnefjuː/", def: "A son of one's sibling.", defVn: "cháu trai (con anh chị em)", pos: "noun", ex: ["My nephew loves drawing.", "I bought a toy for my nephew."], exVn: ["Cháu trai tôi rất thích vẽ.", "Tôi đã mua đồ chơi cho cháu trai."] },
    { word: "niece", phonetic: "/niːs/", def: "A daughter of one's sibling.", defVn: "cháu gái (con anh chị em)", pos: "noun", ex: ["My niece reads English well.", "She smiled at her niece."], exVn: ["Cháu gái tôi đọc tiếng Anh rất tốt.", "Cô ấy mỉm cười với cháu gái."] },
    { word: "spouse", phonetic: "/spaʊs/", def: "A husband or wife.", defVn: "vợ chồng, bạn đời", pos: "noun", ex: ["Invite your spouse to dinner.", "They are devoted spouses."], exVn: ["Hãy mời vợ/chồng bạn đến ăn tối nhé.", "Họ là cặp vợ chồng rất chung thủy."] },
    { word: "household", phonetic: "/ˈhaʊshoʊld/", def: "A house and its occupants.", defVn: "hộ gia đình, gia quyến", pos: "noun", ex: ["Every household shares chores.", "A peaceful household."], exVn: ["Mỗi gia đình đều chia sẻ việc nhà.", "Một mái ấm gia đình an yên."] }
  ],

  // Theme 7: Động từ hàng ngày
  t_basic_daily_verbs: [
    { word: "prepare", phonetic: "/prɪˈper/", def: "Make something ready for use or consideration.", defVn: "chuẩn bị, sắp soạn", pos: "verb", ex: ["Prepare dinner for the family.", "Prepare your homework carefully."], exVn: ["Chuẩn bị bữa tối cho gia đình.", "Chuẩn bị bài tập về nhà cẩn thận."] },
    { word: "borrow", phonetic: "/ˈbɑːroʊ/", def: "Take and use something that belongs to someone else with intention to return.", defVn: "mượn, vay mượn", pos: "verb", ex: ["Can I borrow your English pen?", "Borrow books from the library."], exVn: ["Tôi có thể mượn cây bút của bạn không?", "Mượn sách từ thư viện."] },
    { word: "lend", phonetic: "/lend/", def: "Grant to someone the use of something on the understanding that it will be returned.", defVn: "cho mượn, cho vay", pos: "verb", ex: ["He lent me his umbrella.", "Lend a helping hand."], exVn: ["Anh ấy đã cho tôi mượn chiếc ô.", "Chung tay giúp đỡ một tay."] },
    { word: "deliver", phonetic: "/dɪˈlɪvər/", def: "Bring and hand over a letter, parcel, or goods to the recipient.", defVn: "giao hàng, chuyển phát", pos: "verb", ex: ["Deliver the package to the door.", "The courier delivered the mail."], exVn: ["Giao bưu kiện đến tận cửa.", "Người đưa thư đã chuyển phát thư."] },
    { word: "celebrate", phonetic: "/ˈselɪbreɪt/", def: "Acknowledge a significant day or event with a social gathering.", defVn: "ăn mừng, kỷ niệm", pos: "verb", ex: ["Celebrate a birthday with friends.", "Celebrate your English progress."], exVn: ["Ăn mừng sinh nhật cùng bạn bè.", "Ăn mừng sự tiến bộ tiếng Anh của bạn."] },
    { word: "organize", phonetic: "/ˈɔːrɡənaɪz/", def: "Arrange into a structured whole; order.", defVn: "sắp xếp, tổ chức ngăn nắp", pos: "verb", ex: ["Organize your desk neatly.", "Organize a study group."], exVn: ["Sắp xếp bàn học ngăn nắp.", "Tổ chức một nhóm học tập."] },
    { word: "remind", phonetic: "/rɪˈmaɪnd/", def: "Cause someone to remember someone or something.", defVn: "nhắc nhở, nhắc lại", pos: "verb", ex: ["Remind me to call mom at night.", "The alarm reminds us to study."], exVn: ["Nhắc tôi gọi điện cho mẹ vào buổi tối nhé.", "Chuông báo nhắc chúng ta học bài."] },
    { word: "improve", phonetic: "/ɪmˈpruːv/", def: "Make or become better.", defVn: "cải thiện, nâng cao", pos: "verb", ex: ["Practice daily to improve speaking.", "His English improved rapidly."], exVn: ["Luyện tập hàng ngày để nâng cao kỹ năng nói.", "Tiếng Anh của anh ấy tiến bộ nhanh chóng."] }
  ],

  // Theme 8: Ăn uống & Thực phẩm
  t_basic_food_drinks: [
    { word: "pork", phonetic: "/pɔːrk/", def: "The flesh of a pig used as food.", defVn: "thịt lợn, thịt heo", pos: "noun", ex: ["Grilled pork with rice noodles.", "Caramelized pork is a classic dish."], exVn: ["Bún thịt nướng thơm ngon.", "Thịt kho tàu là món ăn kinh điển."] },
    { word: "beef", phonetic: "/biːf/", def: "The flesh of a cow, bull, or ox, used as food.", defVn: "thịt bò tươi ngon", pos: "noun", ex: ["Hot beef pho is famous worldwide.", "Stir-fried beef with vegetables."], exVn: ["Phở bò nóng nổi tiếng khắp thế giới.", "Thịt bò xào rau củ."] },
    { word: "seafood", phonetic: "/ˈsiːfuːd/", def: "Shellfish and sea fish, served as food.", defVn: "hải sản tươi sống", pos: "noun", ex: ["Da Nang has delicious fresh seafood.", "Grilled seafood platter."], exVn: ["Đà Nẵng có hải sản tươi sống rất ngon.", "Đĩa hải sản nướng tổng hợp."] },
    { word: "tofu", phonetic: "/ˈtoʊfuː/", def: "Curd made from mashed soybeans, used chiefly in Asian cooking.", defVn: "đậu phụ, đậu hũ", pos: "noun", ex: ["Crispy fried tofu with tomato sauce.", "Tofu is rich in healthy protein."], exVn: ["Đậu phụ rán giòn sốt cà chua.", "Đậu hũ rất giàu đạm lành mạnh."] },
    { word: "salad", phonetic: "/ˈsæləd/", def: "A cold dish of various mixtures of raw or cooked vegetables.", defVn: "món sa-lát, món nộm", pos: "noun", ex: ["Fresh green salad with olive oil.", "Eat a healthy salad with lunch."], exVn: ["Sa-lát rau xanh tươi với dầu ô-liu.", "Ăn sa-lát lành mạnh cùng bữa trưa."] },
    { word: "soup", phonetic: "/suːp/", def: "A liquid dish, typically made by boiling meat, fish, or vegetables in stock.", defVn: "món canh, súp nóng", pos: "noun", ex: ["Hot vegetable soup warms the body.", "Mom cooked a pot of sweet soup."], exVn: ["Canh rau củ nóng làm ấm cơ thể.", "Mẹ nấu một nồi canh ngọt thanh."] },
    { word: "yogurt", phonetic: "/ˈjoʊɡərt/", def: "A semi-solid food prepared from milk fermented by bacteria.", defVn: "sữa chua bổ dưỡng", pos: "noun", ex: ["Yogurt with honey and berries.", "Eat yogurt daily for digestion."], exVn: ["Sữa chua ăn kèm mật ong và quả mọng.", "Ăn sữa chua mỗi ngày tốt cho tiêu hóa."] }
  ],

  // Theme 10: Thời gian & Lịch
  t_basic_time_calendar: [
    { word: "decade", phonetic: "/ˈdekeɪd/", def: "A period of ten years.", defVn: "thập kỷ (10 năm)", pos: "noun", ex: ["Technology advanced in the past decade.", "They lived here for a decade."], exVn: ["Công nghệ đã tiến bộ trong thập kỷ qua.", "Họ đã sống ở đây suốt một thập kỷ."] },
    { word: "century", phonetic: "/ˈsentʃəri/", def: "A period of one hundred years.", defVn: "thế kỷ (100 năm)", pos: "noun", ex: ["We live in the twenty-first century.", "The temple is centuries old."], exVn: ["Chúng ta đang sống ở thế kỷ 21.", "Ngôi đền đã có từ nhiều thế kỷ trước."] },
    { word: "dawn", phonetic: "/dɔːn/", def: "The first appearance of light in the sky before sunrise.", defVn: "bình minh, rạng đông", pos: "noun", ex: ["Birds start singing at dawn.", "Wake up at dawn to exercise."], exVn: ["Những chú chim bắt đầu hót lúc rạng đông.", "Thức dậy lúc bình minh để tập thể dục."] },
    { word: "dusk", phonetic: "/dʌsk/", def: "The darker stage of twilight.", defVn: "hoàng hôn, chập tối", pos: "noun", ex: ["The sky turned purple at dusk.", "We strolled along the lake at dusk."], exVn: ["Bầu trời chuyển màu tím lúc hoàng hôn.", "Chúng tôi đi dạo ven hồ lúc chập tối."] },
    { word: "twilight", phonetic: "/ˈtwaɪlaɪt/", def: "The soft glowing light from the sky when the sun is below the horizon.", defVn: "ánh hoàng hôn, chạng vạng", pos: "noun", ex: ["Gaze at the romantic twilight sky.", "Stars appear in the twilight."], exVn: ["Ngắm nhìn bầu trời chạng vạng lãng mạn.", "Những vì sao xuất hiện trong ánh hoàng hôn."] },
    { word: "schedule", phonetic: "/ˈskedʒuːl/", def: "A plan for carrying out a process or procedure.", defVn: "lịch trình, thời gian biểu", pos: "noun", ex: ["Check your study schedule daily.", "The train arrived on schedule."], exVn: ["Kiểm tra lịch học mỗi ngày.", "Tàu hỏa đã đến đúng lịch trình."] },
    { word: "deadline", phonetic: "/ˈdedlaɪn/", def: "The latest time or date by which something should be completed.", defVn: "hạn chót, thời hạn nộp", pos: "noun", ex: ["Finish the report before the deadline.", "The project deadline is Friday."], exVn: ["Hoàn thành báo cáo trước hạn chót nhé.", "Hạn chót của dự án là thứ Sáu."] }
  ],

  // Theme 11: Động vật quen thuộc
  t_basic_animals: [
    { word: "rabbit", phonetic: "/ˈræbɪt/", def: "A burrowing, gregarious plant-eating mammal with long ears.", defVn: "con thỏ trắng", pos: "noun", ex: ["The white rabbit hopped across the lawn.", "Rabbits love eating fresh carrots."], exVn: ["Chú thỏ trắng nhảy lon ton qua bãi cỏ.", "Thỏ rất thích ăn cà rốt tươi."] },
    { word: "monkey", phonetic: "/ˈmʌŋki/", def: "A small to medium-sized primate with a long tail.", defVn: "con khỉ tinh nghịch", pos: "noun", ex: ["Playful monkeys swung between trees.", "Monkeys live in the tropical forest."], exVn: ["Những chú khỉ tinh nghịch đu đưa giữa các cành cây.", "Khỉ sinh sống trong rừng rậm nhiệt đới."] },
    { word: "elephant", phonetic: "/ˈelɪfənt/", def: "A very large plant-eating mammal with a trunk and ivory tusks.", defVn: "con voi to lớn", pos: "noun", ex: ["Elephants in Dak Lak are gentle giants.", "The baby elephant drank water with its trunk."], exVn: ["Những chú voi ở Đắk Lắk là những gã khổng lồ hiền hòa.", "Chú voi con dùng vòi uống nước."] },
    { word: "tiger", phonetic: "/ˈtaɪɡər/", def: "A very large solitary cat with a yellow-brown coat striped with black.", defVn: "con hổ, con cọp", pos: "noun", ex: ["Tigers are powerful protected predators.", "The tiger walked quietly through the jungle."], exVn: ["Hổ là loài săn mồi dũng mãnh được bảo tồn.", "Con hổ bước đi êm ái qua khu rừng rậm."] },
    { word: "dolphin", phonetic: "/ˈdɑːlfɪn/", def: "A small gregarious toothed whale that has a beaklike snout.", defVn: "con cá heo thông minh", pos: "noun", ex: ["Friendly dolphins leaped alongside the boat.", "Dolphins communicate with clicks."], exVn: ["Những chú cá heo thân thiện nhảy lượn bên mạn thuyền.", "Cá heo giao tiếp bằng những tiếng lách cách."] },
    { word: "penguin", phonetic: "/ˈpeŋɡwɪn/", def: "A flightless seabird of southern polar waters with webbed feet.", defVn: "con chim cánh cụt", pos: "noun", ex: ["Penguins waddle cutely across Antarctic ice.", "Penguins are exceptional swimmers."], exVn: ["Chim cánh cụt lạch bạch bước đi đáng yêu trên băng Nam Cực.", "Chim cánh cụt là những tay bơi lội cừ khôi."] },
    { word: "kangaroo", phonetic: "/ˌkæŋɡəˈruː/", def: "A large plant-eating marsupial with a long powerful tail and strong hind legs.", defVn: "chuột túi căng-gu-ru", pos: "noun", ex: ["Kangaroos hop fast across Australian plains.", "A baby kangaroo rests in the pouch."], exVn: ["Chuột túi bật nhảy thoăn thoắt qua đồng cỏ Úc.", "Chú chuột túi con nằm nghỉ trong chiếc túi mẹ."] },
    { word: "parrot", phonetic: "/ˈpærət/", def: "A bird with brightly colored plumage and a curved bill, capable of mimicking speech.", defVn: "con chim vẹt sặc sỡ", pos: "noun", ex: ["The colorful parrot repeated hello.", "Parrots have brilliant green feathers."], exVn: ["Chú vẹt rực rỡ sắc màu lặp lại từ xin chào.", "Vẹt có bộ lông màu xanh lá tuyệt đẹp."] },
    { word: "turtle", phonetic: "/ˈtɜːrtl/", def: "A slow reptile whose body is covered with a bony shell.", defVn: "con rùa", pos: "noun", ex: ["The ancient turtle swam in Hoan Kiem Lake.", "Turtles move slowly and steadily."], exVn: ["Cụ rùa cổ kính bơi trong lòng Hồ Hoàn Kiếm.", "Rùa di chuyển chậm rãi và vững vàng."] },
    { word: "deer", phonetic: "/dɪr/", def: "A hoofed grazing animal with antlers in the male.", defVn: "con hươu, con nai", pos: "noun", ex: ["A graceful spotted deer drank at the stream.", "Deer graze quietly in the meadow."], exVn: ["Một chú hươu sao duyên dáng uống nước bên bờ suối.", "Đàn hươu gặm cỏ thanh bình trên đồng cỏ."] }
  ],

  // Theme 12: Bộ phận cơ thể
  t_basic_body_parts: [
    { word: "eyebrow", phonetic: "/ˈaɪbraʊ/", def: "The strip of hair growing on the ridge above a person's eye socket.", defVn: "lông mày, chân mày", pos: "noun", ex: ["He raised an eyebrow in surprise.", "Neatly shaped eyebrows."], exVn: ["Anh ấy nhướng một bên lông mày đầy ngạc nhiên.", "Đôi lông mày được tạo hình gọn gàng."] },
    { word: "eyelash", phonetic: "/ˈaɪlæʃ/", def: "Each of the short curved hairs growing on the edges of the eyelids.", defVn: "lông mi", pos: "noun", ex: ["Long dark eyelashes framed her eyes.", "A fallen eyelash on the cheek."], exVn: ["Hàng lông mi đen dài tô điểm cho đôi mắt của cô.", "Một sợi lông mi rơi trên má."] },
    { word: "forehead", phonetic: "/ˈfɔːrhed/", def: "The part of the face above the eyebrows.", defVn: "vầng trán", pos: "noun", ex: ["Wipe the sweat from your forehead.", "A high and intelligent forehead."], exVn: ["Lau mồ hôi trên trán nhé.", "Vầng trán cao và thông minh."] },
    { word: "chin", phonetic: "/tʃɪn/", def: "The protruding part of the face below the mouth.", defVn: "cằm", pos: "noun", ex: ["He rested his chin in his hand.", "Keep your chin up and smile."], exVn: ["Anh ấy chống cằm lên tay.", "Hãy ngẩng cao cằm và mỉm cười nhé."] },
    { word: "wrist", phonetic: "/rɪst/", def: "The joint connecting the hand with the forearm.", defVn: "cổ tay", pos: "noun", ex: ["Wear a watch around your left wrist.", "Rotate your wrists during warm-up."], exVn: ["Đeo đồng hồ trên cổ tay trái.", "Xoay cổ tay trong lúc khởi động nhé."] },
    { word: "ankle", phonetic: "/ˈæŋkl/", def: "The joint connecting the foot with the leg.", defVn: "mắt cá chân, cổ chân", pos: "noun", ex: ["Be careful not to twist your ankle.", "Wear ankle socks with sneakers."], exVn: ["Cẩn thận kẻo trật mắt cá chân nhé.", "Đi tất cổ chân cùng giày thể thao."] },
    { word: "spine", phonetic: "/spaɪn/", def: "The series of vertebrae extending from the skull to the small of the back; backbone.", defVn: "cột sống lưng", pos: "noun", ex: ["Sit straight to keep your spine healthy.", "Gentle yoga stretches the spine."], exVn: ["Ngồi thẳng lưng để giữ cột sống luôn khỏe mạnh.", "Bài tập yoga nhẹ nhàng giúp kéo giãn cột sống."] },
    { word: "palm", phonetic: "/pɑːm/", def: "The inner surface of the hand between the wrist and fingers.", defVn: "lòng bàn tay", pos: "noun", ex: ["Clap your palms together joyfully.", "Hold the coins in your open palm."], exVn: ["Vỗ hai lòng bàn tay vào nhau thật vui tươi.", "Giữ những đồng xu trong lòng bàn tay mở."] }
  ],

  // Theme 13: Trang phục cơ bản
  t_basic_clothes: [
    { word: "raincoat", phonetic: "/ˈreɪnkoʊt/", def: "A waterproof or water-resistant coat worn for protection from the rain.", defVn: "áo mưa (tiện lợi)", pos: "noun", ex: ["Keep a light raincoat in your motorbike trunk.", "Put on your raincoat when it pours."], exVn: ["Để một chiếc áo mưa nhẹ trong cốp xe máy nhé.", "Mặc áo mưa vào khi trời mưa to."] },
    { word: "sneakers", phonetic: "/ˈsniːkərz/", def: "Soft-soled shoes worn for sports or casual wear.", defVn: "giày thể thao êm chân", pos: "noun", ex: ["Comfortable sneakers are perfect for walking.", "Tie your sneakers tightly before running."], exVn: ["Đôi giày thể thao êm ái rất tuyệt để đi bộ.", "Buộc chặt dây giày thể thao trước khi chạy nhé."] },
    { word: "sandals", phonetic: "/ˈsændlz/", def: "Light shoes consisting of a sole fastened to the foot by straps.", defVn: "dép quai hậu, xăng-đan", pos: "noun", ex: ["Leather sandals are cool in the summer.", "Wear sandals on the sandy beach."], exVn: ["Dép xăng-đan da rất mát mẻ vào mùa hè.", "Đi dép xăng-đan trên bãi cát biển."] },
    { word: "boots", phonetic: "/buːts/", def: "Sturdy footwear covering the foot and ankle.", defVn: "đôi bốt, ủng giữ ấm", pos: "noun", ex: ["Warm leather boots keep feet dry in winter.", "Hiking boots provide ankle support."], exVn: ["Đôi bốt da ấm giữ ấm cho đôi chân vào mùa đông.", "Giày bốt leo núi giúp bảo vệ cổ chân."] },
    { word: "swimsuit", phonetic: "/ˈswɪmsuːt/", def: "A garment worn for swimming; bathing suit.", defVn: "đồ bơi, áo tắm", pos: "noun", ex: ["Pack your swimsuit for the resort vacation.", "A comfortable one-piece swimsuit."], exVn: ["Gói đồ bơi cho kỳ nghỉ dưỡng nhé.", "Một bộ đồ bơi một mảnh thoải mái."] },
    { word: "vest", phonetic: "/vest/", def: "A sleeveless garment worn on the upper body.", defVn: "áo ghi-lê, áo sát nách", pos: "noun", ex: ["He wore a smart tailored vest over his shirt.", "A reflective safety vest."], exVn: ["Anh ấy mặc một chiếc áo ghi-lê lịch sự bên ngoài áo sơ mi.", "Chiếc áo vest bảo hộ phản quang."] },
    { word: "slippers", phonetic: "/ˈslɪpərz/", def: "Comfortable, slip-on shoes worn indoors.", defVn: "dép đi trong nhà", pos: "noun", ex: ["Wear soft warm slippers inside the house.", "Fluffy slippers beside the bed."], exVn: ["Đi đôi dép mềm mại ấm áp trong nhà nhé.", "Đôi dép đi trong nhà bông xù bên cạnh giường."] },
    { word: "uniform", phonetic: "/ˈjuːnɪfɔːrm/", def: "The distinctive clothing worn by members of the same organization.", defVn: "đồng phục học sinh / cơ quan", pos: "noun", ex: ["Students wear neat white school uniforms.", "The flight crew uniform looks elegant."], exVn: ["Các em học sinh mặc đồng phục trường màu trắng gọn gàng.", "Đồng phục phi hành đoàn trông rất thanh lịch."] }
  ],

  // Theme 14: Địa điểm & Chỉ đường
  t_basic_places_directions: [
    { word: "stadium", phonetic: "/ˈsteɪdiəm/", def: "A sports ground with tiers of seats for spectators.", defVn: "sân vận động thể thao", pos: "noun", ex: ["The stadium was packed with cheering fans.", "The soccer match is at the national stadium."], exVn: ["Sân vận động chật kín các cổ động viên reo hò.", "Trận bóng đá diễn ra tại sân vận động quốc gia."] },
    { word: "intersection", phonetic: "/ˌɪntərˈsekʃn/", def: "A point at which two or more things intersect; road junction.", defVn: "ngã tư đường, giao lộ", pos: "noun", ex: ["Turn left at the busy traffic intersection.", "Be careful when crossing the intersection."], exVn: ["Rẽ trái ở ngã tư đường đông đúc nhé.", "Hãy cẩn thận khi băng qua giao lộ."] },
    { word: "roundabout", phonetic: "/ˈraʊndəbaʊt/", def: "A road junction at which traffic moves in one direction round a central island.", defVn: "vòng xuyến, bùng binh", pos: "noun", ex: ["Take the second exit at the roundabout.", "Vehicles yield inside the roundabout."], exVn: ["Đi theo lối ra thứ hai tại vòng xuyến nhé.", "Các phương tiện nhường đường bên trong bùng binh."] },
    { word: "avenue", phonetic: "/ˈævənuː/", def: "A broad road in a town or city, typically tree-lined.", defVn: "đại lộ rộng lớn", pos: "noun", ex: ["Walk down the shady boulevard avenue.", "The parade marched on the main avenue."], exVn: ["Đi dạo trên đại lộ rợp bóng cây mát rượi.", "Đoàn diễu hành tiến bước trên đại lộ chính."] },
    { word: "neighborhood", phonetic: "/ˈneɪbərhʊd/", def: "A district, especially one forming a community within a town or city.", defVn: "khu phố, khu dân cư", pos: "noun", ex: ["Our neighborhood is quiet and friendly.", "Explore the historic old neighborhood."], exVn: ["Khu phố của chúng tôi rất yên tĩnh và thân thiện.", "Khám phá khu dân cư cổ kính lâu đời."] },
    { word: "suburb", phonetic: "/ˈsʌbɜːrb/", def: "An outlying district of a city, especially a residential one.", defVn: "vùng ngoại ô, ngoại thành", pos: "noun", ex: ["They live in a green, peaceful suburb.", "Commute from the suburbs to downtown."], exVn: ["Họ sống ở một vùng ngoại ô xanh tươi và thanh bình.", "Đi lại từ ngoại thành vào trung tâm thành phố."] },
    { word: "crossroads", phonetic: "/ˈkrɔːsroʊdz/", def: "An intersection of two or more roads.", defVn: "ngã tư đường, ngã tư giao nhau", pos: "noun", ex: ["Meet me at the town center crossroads.", "A traffic light at the crossroads."], exVn: ["Gặp tôi ở ngã tư trung tâm thị trấn nhé.", "Một cột đèn giao thông ở ngã tư đường."] },
    { word: "corner", phonetic: "/ˈkɔːrnər/", def: "A place or angle where two or more sides or edges meet.", defVn: "góc phố, góc đường", pos: "noun", ex: ["The cozy coffee shop is on the street corner.", "Turn right at the corner."], exVn: ["Quán cà phê ấm cúng nằm ngay ở góc phố.", "Rẽ phải ở góc đường nhé."] }
  ]
};
