module.exports = {
  // Theme 27: Giới từ & Vị trí
  t_basic_prepositions_positions: [
    { word: "beside", phonetic: "/bɪˈsaɪd/", def: "At the side of; next to.", defVn: "ở bên cạnh", pos: "preposition", ex: ["Sit beside me during the English lesson.", "A flower bed beside the porch."], exVn: ["Ngồi bên cạnh tôi trong giờ học tiếng Anh nhé.", "Luống hoa ở bên cạnh hiên nhà."] },
    { word: "amidst", phonetic: "/əˈmɪdst/", def: "In the middle of or surrounded by.", defVn: "ở giữa, giữa lòng", pos: "preposition", ex: ["A tranquil pagoda amidst lush green hills.", "Stay calm amidst chaos."], exVn: ["Ngôi chùa thanh tịnh giữa lòng những ngọn đồi xanh mướt.", "Giữ bình tĩnh giữa sự hỗn loạn."] }
  ],

  // Theme 29: Kỳ nghỉ & Du lịch
  t_basic_vacation_tourism: [
    { word: "guesthouse", phonetic: "/ˈɡesthaʊs/", def: "A private house offering accommodation to paying guests; homestay.", defVn: "nhà nghỉ, homestay ấm cúng", pos: "noun", ex: ["We stayed at a cozy family guesthouse in Da Lat.", "The guesthouse owner was hospitable."], exVn: ["Chúng tôi đã ở tại một nhà nghỉ gia đình ấm cúng ở Đà Lạt.", "Chủ nhà nghỉ rất hiếu khách."] },
    { word: "sunscreen", phonetic: "/ˈsʌnskriːn/", def: "A cream or lotion rubbed onto the skin to protect it from sunburn.", defVn: "kem chống nắng bảo vệ da", pos: "noun", ex: ["Apply waterproof sunscreen before swimming at the beach.", "SPF 50 broad spectrum sunscreen."], exVn: ["Thoa kem chống nắng chống nước trước khi đi bơi ở biển.", "Kem chống nắng quang phổ rộng SPF 50."] }
  ],

  // Theme 30: Giải trí & Nghệ thuật
  t_basic_entertainment_arts: [
    { word: "magician", phonetic: "/məˈdʒɪʃn/", def: "A person who performs magic tricks for entertainment.", defVn: "nhà ảo thuật tài ba", pos: "noun", ex: ["The clever magician pulled a white dove out of an empty hat.", "Children gasped at the magician."], exVn: ["Nhà ảo thuật khéo tay đã rút một chú chim bồ câu trắng từ chiếc mũ rỗng.", "Lũ trẻ trầm trồ trước màn ảo thuật."] },
    { word: "melody", phonetic: "/ˈmelədi/", def: "A sequence of single notes that is musically satisfying; a tune.", defVn: "giai điệu êm đềm", pos: "noun", ex: ["A gentle acoustic guitar melody soothed our minds.", "Hum a catchy pop melody."], exVn: ["Giai điệu ghi-ta mộc êm dịu làm dịu mát tâm hồn chúng tôi.", "Ngâm nga một giai điệu nhạc trẻ bắt tai."] }
  ],

  // Theme 31: Đo lường & Kích cỡ
  t_basic_measurements_sizes: [
    { word: "acre", phonetic: "/ˈeɪkər/", def: "A unit of land area equal to 4,840 square yards (0.405 hectare).", defVn: "mẫu đất, sào đất (đo diện tích)", pos: "noun", ex: ["Ten acres of golden ripening rice fields.", "A vast estate spanning fifty acres."], exVn: ["Mười mẫu ruộng lúa chín vàng ươm.", "Một trang viên rộng lớn trải dài 50 mẫu."] }
  ],

  // Theme 32: Dụng cụ & Sửa chữa
  t_basic_tools_repair: [
    { word: "flashlight", phonetic: "/ˈflæʃlaɪt/", def: "A small portable battery-powered electric lamp; torch.", defVn: "đèn pin cầm tay chiếu sáng", pos: "noun", ex: ["Shine the bright LED flashlight in the dark basement.", "Keep a flashlight handy for power cuts."], exVn: ["Rọi chiếc đèn pin LED sáng trong tầng hầm tối.", "Để sẵn đèn pin khi mất điện nhé."] },
    { word: "padlock", phonetic: "/ˈpædlɑːk/", def: "A detachable lock hanging by a pivoted hook on the object fastened.", defVn: "ổ khóa móc an toàn", pos: "noun", ex: ["Secure the garden gate with a heavy brass padlock.", "A combination padlock."], exVn: ["Khóa cổng vườn bằng ổ khóa đồng chắc chắn.", "Ổ khóa móc dùng mã số."] },
    { word: "shovel", phonetic: "/ˈʃʌvl/", def: "A tool with a broad flat blade and typically upturned sides, used for moving earth or snow.", defVn: "cái xẻng xúc đất / cát", pos: "noun", ex: ["Dig garden soil with a steel shovel.", "Clear sand with a shovel."], exVn: ["Đào đất vườn bằng cái xẻng thép.", "Dọn cát bằng xẻng."] },
    { word: "wire", phonetic: "/ˈwaɪər/", def: "Metal drawn out into the form of a thin flexible thread or rod.", defVn: "dây thép, dây kẽm uốn", pos: "noun", ex: ["Bind the wooden fence with galvanized wire.", "Copper electrical wire."], exVn: ["Buộc hàng rào gỗ bằng dây kẽm chống gỉ.", "Dây điện bằng đồng."] },
    { word: "chisel", phonetic: "/ˈtʃɪzl/", def: "A long-bladed hand tool with a beveled cutting edge, used for cutting or shaping wood, stone, or metal.", defVn: "cây đục gỗ nghệ thuật", pos: "noun", ex: ["Woodcarvers shape intricate patterns with a sharp chisel.", "A stone carving chisel."], exVn: ["Thợ mộc đục các hoa văn tinh xảo bằng cây đục sắc bén.", "Cây đục tạc đá."] },
    { word: "chainsaw", phonetic: "/ˈtʃeɪnsɔː/", def: "A mechanical power-driven cutting tool with teeth set on a moving chain.", defVn: "máy cưa xích chạy điện/xăng", pos: "noun", ex: ["Prune dead tree branches safely with an electric chainsaw.", "Wear eye protection with chainsaws."], exVn: ["Cắt tỉa cành cây khô an toàn bằng máy cưa xích điện.", "Đeo kính bảo hộ khi dùng máy cưa xích."] },
    { word: "tape", phonetic: "/teɪp/", def: "A narrow strip of material with an adhesive surface.", defVn: "cuộn băng dính, băng keo", pos: "noun", ex: ["Seal the cardboard delivery box with clear packing tape.", "Electrical insulating tape."], exVn: ["Dán kín hộp bìa giao hàng bằng băng dính trong suốt.", "Băng keo cách điện."] }
  ],

  // Theme 33: Thiên tai & Thời tiết xấu
  t_basic_severe_weather: [
    { word: "monsoon", phonetic: "/mɑːnˈsuːn/", def: "A seasonal prevailing wind in the region of South and Southeast Asia, bringing heavy rain.", defVn: "gió mùa nhiệt đới, mùa mưa gió mùa", pos: "noun", ex: ["The southwest monsoon brings abundant summer rain to Southern Vietnam.", "Monsoon cloud formations."], exVn: ["Gió mùa Tây Nam mang mưa hè dồi dào về Nam Bộ.", "Những tầng mây gió mùa tích tụ."] },
    { word: "downpour", phonetic: "/ˈdaʊnpɔːr/", def: "A heavy fall of rain.", defVn: "trận mưa rào như trút nước", pos: "noun", ex: ["We took shelter under an awning during the sudden tropical downpour.", "A torrential afternoon downpour."], exVn: ["Chúng tôi trú tạm dưới mái hiên trong cơn mưa rào nhiệt đới trút nước bất ngờ.", "Trận mưa rào xối xả buổi chiều."] },
    { word: "cyclone", phonetic: "/ˈsaɪkloʊn/", def: "A system of winds rotating inwards to an area of low atmospheric pressure; tropical storm.", defVn: "cơn bão lốc nhiệt đới", pos: "noun", ex: ["Meteorologists track the powerful ocean cyclone on satellite radar.", "Cyclone warning signals."], exVn: ["Các nhà khí tượng học theo dõi cơn bão lốc đại dương trên ảnh vệ tinh.", "Tín hiệu cảnh báo bão lốc."] },
    { word: "smog", phonetic: "/smɑːɡ/", def: "Fog or haze intensified by smoke or other atmospheric pollutants.", defVn: "khói bụi ô nhiễm, sương mù quang hóa", pos: "noun", ex: ["Wear an anti-pollution face mask when urban smog levels rise.", "Air purifiers filter out indoor smog."], exVn: ["Đeo khẩu trang lọc bụi khi mức độ khói bụi đô thị gia tăng.", "Máy lọc không khí lọc sạch khói bụi trong nhà."] },
    { word: "heatwave", phonetic: "/ˈhiːtweɪv/", def: "A prolonged period of abnormally hot weather.", defVn: "đợt nắng nóng gay gắt kéo dài", pos: "noun", ex: ["Drink plenty of water and stay indoors during the peak summer heatwave.", "Survive the severe heatwave."], exVn: ["Uống nhiều nước và ở trong nhà suốt đợt nắng nóng hè đỉnh điểm.", "Vượt qua đợt nắng nóng gay gắt."] },
    { word: "aftershock", phonetic: "/ˈæftərʃɑːk/", def: "A smaller earthquake following the main shock of a large earthquake.", defVn: "dư chấn sau động đất", pos: "noun", ex: ["Minor aftershocks were felt after the main earthquake tremor.", "Inspect buildings after aftershocks."], exVn: ["Những đợt dư chấn nhẹ được ghi nhận sau chấn động động đất chính.", "Kiểm tra nhà cửa sau các đợt dư chấn."] },
    { word: "gale", phonetic: "/ɡeɪl/", def: "A very strong wind.", defVn: "cơn gió giật mạnh, cuồng phong", pos: "noun", ex: ["Gale force winds blew waves high against sea walls.", "A gale warning for coastal shipping."], exVn: ["Gió giật cấp cuồng phong đánh những ngọn sóng cao vào đê biển.", "Cảnh báo gió giật mạnh cho tàu bè ven biển."] },
    { word: "frostbite", phonetic: "/ˈfrɔːstbaɪt/", def: "Injury to body tissues caused by exposure to extreme cold.", defVn: "bỏng lạnh vì nhiệt độ quá thấp", pos: "noun", ex: ["Wear thermal insulated gloves to protect fingers from frostbite.", "Treat early frostbite gently."], exVn: ["Đeo găng tay giữ nhiệt để bảo vệ các ngón tay khỏi bị bỏng lạnh.", "Xử lý nhẹ nhàng khi mới bị cóng lạnh."] },
    { word: "sandstorm", phonetic: "/ˈsændstɔːrm/", def: "A strong wind in a desert carrying clouds of sand with it.", defVn: "cơn bão cát sa mạc mịt mù", pos: "noun", ex: ["Wrap a protective scarf around your face during a desert sandstorm.", "Visibility drops to zero in sandstorms."], exVn: ["Quấn khăn choàng bảo vệ mặt trong cơn bão cát sa mạc.", "Tầm nhìn giảm xuống bằng không trong bão cát."] }
  ],

  // Theme 34: Địa hình & Cảnh quan
  t_basic_landforms_landscapes: [
    { word: "bay", phonetic: "/beɪ/", def: "A broad inlet of the sea where the land curves inwards.", defVn: "vịnh biển (Vịnh Hạ Long, Lan Hạ)", pos: "noun", ex: ["Ha Long Bay is world-famous for emerald waters and limestone islets.", "Sail across the calm bay."], exVn: ["Vịnh Hạ Long nổi tiếng toàn cầu với làn nước xanh ngọc bích và các hòn đảo đá vôi.", "Giương buồm lướt qua vịnh biển êm đềm."] },
    { word: "delta", phonetic: "/ˈdeltə/", def: "A triangular tract of sediment deposited at the mouth of a river.", defVn: "vùng đồng bằng châu thổ phì nhiêu", pos: "noun", ex: ["The Mekong Delta is the fruit and rice basket of Vietnam.", "Boat markets in the river delta."], exVn: ["Đồng bằng sông Cửu Long là vựa lúa và trái cây trù phú của Việt Nam.", "Chợ nổi trên vùng châu thổ sông."] },
    { word: "lagoon", phonetic: "/ləˈɡuːn/", def: "A stretch of salt water separated from the sea by a low sandbank or coral reef.", defVn: "đầm phá nước lợ (phá Tam Giang)", pos: "noun", ex: ["Tam Giang Lagoon in Hue is Southeast Asia's largest brackish lagoon.", "Sunset over the peaceful lagoon."], exVn: ["Phá Tam Giang ở Huế là đầm phá nước lợ lớn nhất Đông Nam Á.", "Hoàng hôn buông xuống trên đầm phá yên bình."] },
    { word: "meadow", phonetic: "/ˈmedoʊ/", def: "A piece of grassland, especially one used for hay.", defVn: "đồng cỏ xanh tươi ngát hương", pos: "noun", ex: ["Cows graze peacefully on lush green alpine meadows in Moc Chau.", "Wildflowers bloom in the meadow."], exVn: ["Đàn bò thong thả gặm cỏ trên đồng cỏ xanh mướt ở Mộc Châu.", "Hoa dại nở rộ trên đồng cỏ."] },
    { word: "dune", phonetic: "/duːn/", def: "A mound or ridge of sand formed by the wind on the coast or in a desert.", defVn: "cồn cát, đồi cát uốn lượn (Mũi Né)", pos: "noun", ex: ["Slide down the golden sand dunes of Mui Ne at sunrise.", "Wind reshapes sand dunes continuously."], exVn: ["Trượt trên những đồi cát vàng óng ả Mũi Né lúc bình minh.", "Gió liên tục tạc nên những hình dáng mới cho đồi cát."] }
  ],

  // Theme 35: Sinh vật biển & Đại dương
  t_basic_marine_life: [
    { word: "pelican", phonetic: "/ˈpelɪkən/", def: "A large gregarious waterbird with a long bill and a large throat pouch for scooping up fish.", defVn: "chim bồ nông săn cá", pos: "noun", ex: ["Pelicans dive into coastal waters to catch fish in their large bill pouches.", "Pelicans nesting in bird sanctuaries."], exVn: ["Chim bồ nông lao mình xuống làn nước ven biển để xúc cá vào túi mỏ lớn.", "Bồ nông làm tổ trong các khu bảo tồn chim."] },
    { word: "penguin", phonetic: "/ˈpeŋɡwɪn/", def: "A flightless seabird of southern hemisphere waters with flipper-like wings.", defVn: "chú chim cánh cụt đáng yêu", pos: "noun", ex: ["Penguins waddle comically on polar ice sheets and swim fast underwater.", "Emperor penguins huddle for warmth."], exVn: ["Những chú chim cánh cụt lạch bạch bước đi trên băng và bơi cực nhanh dưới nước.", "Chim cánh cụt hoàng đế tụ lại để giữ ấm."] },
    { word: "plankton", phonetic: "/ˈplæŋktən/", def: "The small and microscopic organisms drifting or floating in the sea or freshwater.", defVn: "sinh vật phù du đại dương", pos: "noun", ex: ["Bioluminescent plankton glows blue when waves crash at night in Nha Trang.", "Whales feed on ocean plankton."], exVn: ["Sinh vật phù du phát quang sinh học phát ánh xanh biếc khi sóng vỗ ban đêm ở Nha Trang.", "Cá voi ăn các sinh vật phù du đại dương."] },
    { word: "stingray", phonetic: "/ˈstɪŋreɪ/", def: "A bottom-dwelling marine ray with one or more venomous spines on the tail.", defVn: "cá đuối gai độc đáy biển", pos: "noun", ex: ["A stingray rests buried under the fine ocean sand.", "Admire stingrays from a safe distance."], exVn: ["Chú cá đuối nằm vùi mình dưới lớp cát mịn đáy biển.", "Chiêm ngưỡng cá đuối gai từ khoảng cách an toàn."] },
    { word: "eel", phonetic: "/iːl/", def: "A snake-like fish with a slender elongated body and poorly developed fins.", defVn: "con lươn, cá chình biển", pos: "noun", ex: ["Crispy fried eel vermicelli soup (Mien Luon) is a Hanoi specialty.", "Moray eels hide in coral crevices."], exVn: ["Miến lươn giòn tan là món đặc sản nức danh Hà Nội.", "Cá chình biển ẩn mình trong các hốc san hô."] },
    { word: "anchovy", phonetic: "/ˈæntʃoʊvi/", def: "A small, silver-greenish fish, used as a food fish and salted to make fish sauce; ca com.", defVn: "cá cơm than làm nước mắm", pos: "noun", ex: ["Fresh black anchovies from Phu Quoc waters brew the finest golden fish sauce.", "Crisp fried garlic anchovies."], exVn: ["Cá cơm than tươi ngon vùng biển Phú Quốc ủ nên những giọt nước mắm vàng óng hảo hạng.", "Cá cơm chiên tỏi ớt giòn rụm."] },
    { word: "swordfish", phonetic: "/ˈsɔːrdfɪʃ/", def: "A large predatory ocean fish with a streamlined body and a long pointed bill resembling a sword.", defVn: "cá kiếm đại dương tốc độ cao", pos: "noun", ex: ["The fast-swimming swordfish leaps high above ocean swells.", "Grilled swordfish steak."], exVn: ["Chú cá kiếm bơi với tốc độ cực cao bật nhảy trên những đợt sóng biển.", "Cá kiếm nướng sốt thơm lừng."] },
    { word: "walrus", phonetic: "/ˈwɔːlrəs/", def: "A large marine mammal of Arctic seas, with large tusks and a tough wrinkled hide.", defVn: "con hải mã có ngà dài", pos: "noun", ex: ["The Arctic walrus rests on floating ice floes using its ivory tusks.", "A herd of walruses."], exVn: ["Hải mã Bắc Cực nằm nghỉ trên tảng băng trôi nhờ đôi ngà dài.", "Một đàn hải mã."] },
    { word: "otter", phonetic: "/ˈɑːtər/", def: "A semiaquatic fish-eating mammal with a long body, dense fur, and webbed feet.", defVn: "con rái cá bơi lội thông minh", pos: "noun", ex: ["Playful river otters slide down muddy banks into the clear stream.", "Otters hold hands while floating."], exVn: ["Những chú rái cá sông tinh nghịch trượt trên bờ đất xuống dòng suối trong vắt.", "Rái cá nắm tay nhau khi nổi trên mặt nước."] }
  ],

  // Theme 36: Côn trùng & Sâu bọ
  t_basic_insects_bugs: [
    { word: "moth", phonetic: "/mɔːθ/", def: "A chiefly nocturnal insect related to the butterflies.", defVn: "con bướm đêm, thiêu thân", pos: "noun", ex: ["Night moths are naturally drawn to porch light bulbs.", "Silk moths produce silk cocoons."], exVn: ["Những chú bướm đêm tự nhiên bị thu hút bởi ánh đèn hiên nhà.", "Bướm đêm nhả tơ dệt kén."] },
    { word: "spider", phonetic: "/ˈspaɪdər/", def: "An eight-legged predatory arachnid with an unsegmented body and silk-spinning spinnerets.", defVn: "con nhện giăng tơ", pos: "noun", ex: ["The garden spider wove an intricate dewy web overnight.", "Spiders control garden pests naturally."], exVn: ["Chú nhện hoa trong vườn đã dệt nên tấm mạng tơ đọng sương tinh xảo qua đêm.", "Nhện giúp kiểm soát sâu bọ có hại trong vườn."] },
    { word: "centipede", phonetic: "/ˈsentɪpiːd/", def: "A predatory myriapod invertebrate with a flattened body composed of many segments.", defVn: "con rết nhiều chân", pos: "noun", ex: ["Centipedes scurry rapidly under damp rocks and fallen bark.", "Avoid touching venomous centipedes."], exVn: ["Những chú rết bò thoăn thoắt dưới những tảng đá ẩm và vỏ cây rụng.", "Tránh chạm vào rết có nọc độc nhé."] },
    { word: "scorpion", phonetic: "/ˈskɔːrpiən/", def: "A terrestrial arachnid with lobster-like pincers and a poisonous sting at the end of its tail.", defVn: "con bọ cạp", pos: "noun", ex: ["Desert scorpions glow bright cyan under ultraviolet blacklight.", "Scorpions hide under rocks."], exVn: ["Bọ cạp sa mạc phát sáng màu xanh lam rực rỡ dưới ánh đèn tử ngoại.", "Bọ cạp ẩn nấp dưới phiến đá."] },
    { word: "termite", phonetic: "/ˈtɜːrmaɪt/", def: "A small, pale soft-bodied insect that lives in large colonies and feeds on wood.", defVn: "con mối ăn gỗ", pos: "noun", ex: ["Protect wooden house frames from destructive termites.", "Termite colonies build tall soil mounds."], exVn: ["Bảo vệ khung nhà gỗ khỏi loài mối phá hoại.", "Tổ mối đắp nên những gò đất cao."] },
    { word: "hornet", phonetic: "/ˈhɔːrnɪt/", def: "A large stinging wasp that typically nests in hollow trees or roof eaves.", defVn: "ong vò vẽ, ong bắp cày lớn", pos: "noun", ex: ["Keep a safe distance from hanging wild hornet nests.", "Hornets protect their queen fiercely."], exVn: ["Giữ khoảng cách an toàn với những tổ ong vò vẽ hoang dã treo trên cao.", "Ong vò vẽ bảo vệ ong chúa rất quyết liệt."] },
    { word: "flea", phonetic: "/fliː/", def: "A small wingless jumping insect that feeds on the blood of mammals and birds.", defVn: "con bọ chét chó mèo", pos: "noun", ex: ["Bathe pet dogs regularly to prevent itchy fleas.", "Flea treatment for cats."], exVn: ["Tắm cho chó cưng thường xuyên để phòng ngừa bọ chét gây ngứa.", "Thuốc trị bọ chét cho mèo."] },
    { word: "gnat", phonetic: "/næt/", def: "A small two-winged fly that resembles a mosquito.", defVn: "con dĩn, muỗi mắt nhỏ xíu", pos: "noun", ex: ["Tiny gnats hover near garden ponds on humid summer evenings.", "A swarm of tiny gnats."], exVn: ["Những chú dĩn nhỏ xíu bay là là gần hồ vườn vào những buổi tối hè ẩm ướt.", "Một đàn muỗi mắt nhỏ."] },
    { word: "tick", phonetic: "/tɪk/", def: "A tiny parasitic arachnid that attaches to the skin of animals.", defVn: "con ve chó, bọ ve", pos: "noun", ex: ["Check dogs for small ticks after walking in tall grass.", "Remove ticks carefully with tweezers."], exVn: ["Kiểm tra ve bọ cho cún cưng sau khi đi dạo trong bụi cỏ cao.", "Gắp ve cẩn thận bằng nhíp."] }
  ],

  // Theme 37: Gia vị & Hương vị
  t_basic_spices_herbs: [
    { word: "paprika", phonetic: "/pəˈpriːkə/", def: "A red powder made from dried sweet peppers, used in cooking for flavor and color.", defVn: "bột ớt cựa gà đỏ ngọt (paprika)", pos: "noun", ex: ["Dust sweet red paprika powder over roasted potato wedges.", "Smoked paprika adds deep flavor."], exVn: ["Rắc bột ớt cựa gà ngọt đỏ lên khoai tây bổ cau nướng.", "Ớt bột xông khói mang lại vị đậm đà."] },
    { word: "dill", phonetic: "/dɪl/", def: "An aromatic herb with feathery leaves, used in pickling and cooking fish; thi la.", defVn: "rau thì là thơm ngọt (nấu cá)", pos: "noun", ex: ["Fresh green dill is the indispensable herb for Hanoi turmeric grilled fish (Cha Ca).", "Add dill to fish soup."], exVn: ["Rau thì là xanh tươi là loại rau gia vị không thể thiếu trong món Chả cá Lã Vọng.", "Thêm thì là vào canh cá."] },
    { word: "rosemary", phonetic: "/ˈroʊzmeri/", def: "An evergreen aromatic shrub of the mint family, with narrow leaves used as a culinary herb.", defVn: "lá hương thảo thơm ngát", pos: "noun", ex: ["Roast beef steak with fresh rosemary sprigs and butter.", "The invigorating scent of garden rosemary."], exVn: ["Nướng bít tết bò với những nhánh lá hương thảo tươi và bơ thơm.", "Hương thơm sảng khoái của cây hương thảo trong vườn."] },
    { word: "thyme", phonetic: "/taɪm/", def: "A low-growing aromatic plant of the mint family, used as a culinary herb.", defVn: "cỏ xạ hương thơm dịu", pos: "noun", ex: ["Simmer chicken vegetable soup with sprigs of fresh garden thyme.", "Thyme pairs wonderfully with garlic."], exVn: ["Ninh súp gà rau củ với những nhánh cỏ xạ hương hái tại vườn.", "Cỏ xạ hương kết hợp tuyệt vời với tỏi."] },
    { word: "cardamom", phonetic: "/ˈkɑːrdəməm/", def: "The aromatic seeds of a ginger family plant, used as a spice; thao qua.", defVn: "thảo quả rừng Tây Bắc thơm nồng", pos: "noun", ex: ["Northwestern mountain black cardamom pods enrich the warm aroma of pho broth.", "Crushed green cardamom in tea."], exVn: ["Những quả thảo quả đen vùng núi Tây Bắc làm giàu thêm hương thơm nồng ấm cho nước dùng phở.", "Thảo quả nghiền trong trà ấm."] },
    { word: "fennel", phonetic: "/ˈfenl/", def: "An aromatic yellow-flowered European plant of the parsley family.", defVn: "hạt tiểu hồi, củ hồi thơm mát", pos: "noun", ex: ["Fennel seeds add sweet licorice notes to spice blends.", "Crunchy shaved fennel salad."], exVn: ["Hạt tiểu hồi mang lại nốt hương ngọt thanh cho các hỗn hợp gia vị.", "Nộm củ hồi bào mỏng giòn ngọt."] }
  ],

  // Theme 38: Bánh ngọt & Tráng miệng
  t_basic_bakery_desserts: [
    { word: "tiramisu", phonetic: "/ˌtɪrəmɪˈsuː/", def: "An Italian dessert consisting of layers of sponge cake soaked in coffee and brandy with powdered chocolate and mascarpone cheese.", defVn: "bánh ti-ra-mi-su cà phê phô mai Ý", pos: "noun", ex: ["A slice of delicate coffee tiramisu dusted with cocoa powder.", "Classic Italian mascarpone tiramisu."], exVn: ["Một lát bánh ti-ra-mi-su cà phê tinh tế rắc bột ca-cao thơm mịn.", "Bánh tiramisu phô mai mascarpone truyền thống của Ý."] },
    { word: "cupcake", phonetic: "/ˈkʌpkeɪk/", def: "A small cake baked in a cup-shaped foil or paper container, typically with icing.", defVn: "bánh bông lan nhỏ trang trí kem (cupcake)", pos: "noun", ex: ["Vanilla cupcakes decorated with colorful buttercream frosting and sprinkles.", "Bake chocolate cupcakes for birthdays."], exVn: ["Những chiếc bánh cupcake vani trang trí kem bơ nhiều màu sắc và kẹo cốm.", "Nướng bánh cupcake sô-cô-la cho tiệc sinh nhật."] },
    { word: "crepe", phonetic: "/kreɪp/", def: "A thin pancake, typically served folded with a sweet or savory filling.", defVn: "bánh kếp mỏng (crepe)", pos: "noun", ex: ["Thin French crepes filled with fresh banana slices and chocolate sauce.", "Fold sweet crepes neatly."], exVn: ["Những chiếc bánh kếp mỏng kiểu Pháp nhân chuối tươi và sốt sô-cô-la.", "Gấp bánh crepe ngọt gọn gàng."] },
    { word: "biscuit", phonetic: "/ˈbɪskɪt/", def: "A small, flat, crisp baked cake, typically sweet.", defVn: "bánh quy giòn tan", pos: "noun", ex: ["Enjoy butter biscuits with hot afternoon tea.", "Crisp ginger biscuits."], exVn: ["Thưởng thức bánh quy bơ cùng tách trà chiều nóng.", "Bánh quy gừng giòn rụm."] },
    { word: "eclair", phonetic: "/eɪˈkler/", def: "An oblong pastry made with choux dough filled with cream and topped with chocolate icing.", defVn: "bánh su kem dài phủ sô-cô-la (eclair)", pos: "noun", ex: ["A chocolate glazed French eclair filled with vanilla custard cream.", "Pastry chefs pipe eclair dough."], exVn: ["Chiếc bánh su kem dài kiểu Pháp phủ sô-cô-la ngập tràn kem trứng vani.", "Đầu bếp bánh bóp bột làm bánh eclair."] },
    { word: "fudge", phonetic: "/fʌdʒ/", def: "A soft, rich candy made of sugar, milk, butter, and flavoring.", defVn: "kẹo sô-cô-la mềm béo ngậy (fudge)", pos: "noun", ex: ["Rich dark chocolate peanut butter fudge squares.", "Homemade walnut fudge."], exVn: ["Những viên kẹo mềm sô-cô-la đen bơ đậu phộng béo ngậy.", "Kẹo fudge óc chó nhà làm."] }
  ],

  // Theme 39: Đồ uống & Trà sữa
  t_basic_drinks_beverages: [
    { word: "black tea", phonetic: "/ˌblæk ˈtiː/", def: "Tea that is fully fermented before drying.", defVn: "trà đen đậm đà (hồng trà)", pos: "noun", ex: ["Brew premium Ha Giang Shan Tuyet black tea for morning energy.", "Black tea with a slice of lemon."], exVn: ["Hãm trà đen Shan Tuyết Hà Giang hảo hạng cho buổi sáng tràn đầy năng lượng.", "Trà đen với một lát chanh tươi."] },
    { word: "cider", phonetic: "/ˈsaɪdər/", def: "An unfermented or fermented drink made from crushed apples.", defVn: "nước táo lên men thơm mát (cider)", pos: "noun", ex: ["Sparkling chilled apple cider served in champagne flutes.", "A mug of warm spiced cider."], exVn: ["Nước táo ép có ga ướp lạnh rót vào ly thanh lịch.", "Một ly nước táo nóng ủ quế thơm lừng."] },
    { word: "mocktail", phonetic: "/ˈmɑːkteɪl/", def: "A non-alcoholic drink consisting of a mixture of fruit juices or other soft drinks.", defVn: "thức uống trái cây pha chế không cồn (mocktail)", pos: "noun", ex: ["A tropical passion fruit and mint mocktail is refreshing for all ages.", "Order colorful mocktails."], exVn: ["Ly mocktail chanh dây và bạc hà nhiệt đới thanh mát phù hợp cho mọi lứa tuổi.", "Gọi những ly mocktail rực rỡ sắc màu."] }
  ],

  // Theme 40: Dọn dẹp & Việc nhà
  t_basic_cleaning_chores: [
    { word: "disinfectant", phonetic: "/ˌdɪsɪnˈfektənt/", def: "A chemical liquid that destroys bacteria.", defVn: "dung dịch sát khuẩn, nước lau sàn diệt khuẩn", pos: "noun", ex: ["Mop kitchen floors with lemon scented disinfectant cleaner.", "Spray disinfectant on surfaces."], exVn: ["Lau sàn bếp bằng nước lau sàn diệt khuẩn hương chanh thơm ngát.", "Xịt dung dịch sát khuẩn lên các bề mặt."] },
    { word: "trash bag", phonetic: "/ˈtræʃ bæɡ/", def: "A disposable plastic bag for holding household rubbish.", defVn: "túi đựng rác sinh hoạt tự phân hủy", pos: "noun", ex: ["Line the kitchen bin with a biodegradable trash bag.", "Tie the full trash bag securely."], exVn: ["Lót thùng rác nhà bếp bằng túi đựng rác sinh học tự phân hủy.", "Buộc chặt túi rác khi đầy nhé."] },
    { word: "rubber gloves", phonetic: "/ˈrʌbər ɡlʌvz/", def: "Gloves made of rubber, worn especially to protect the hands while doing household chores.", defVn: "đôi găng tay cao su bảo vệ da tay", pos: "noun", ex: ["Wear waterproof yellow rubber gloves while washing greasy dishes.", "Protect hands with rubber gloves."], exVn: ["Đeo đôi găng tay cao su màu vàng chống nước khi rửa bát đĩa nhiều dầu mỡ.", "Bảo vệ đôi tay bằng găng tay cao su."] },
    { word: "laundry basket", phonetic: "/ˈlɔːndri ˈbæskɪt/", def: "A hamper or container for holding clothes awaiting washing.", defVn: "giỏ đựng quần áo giặt", pos: "noun", ex: ["Place dirty clothes inside the woven bamboo laundry basket.", "Carry the laundry basket to the machine."], exVn: ["Bỏ quần áo bẩn vào chiếc giỏ đựng đồ giặt bằng tre đan.", "Bê giỏ quần áo đến máy giặt."] },
    { word: "feather duster", phonetic: "/ˈfeðər dʌstər/", def: "A duster made of feathers, used for clearing dust from delicate surfaces.", defVn: "chổi lông gà quét bụi", pos: "noun", ex: ["Gently sweep dust off picture frames with a soft feather duster.", "A fluffy feather duster."], exVn: ["Phủi nhẹ bụi trên các khung ảnh bằng cây chổi lông gà mềm mại.", "Chiếc chổi lông gà bông xốp."] }
  ],

  // Theme 41: Phụ kiện thời trang
  t_basic_fashion_accessories: [
    { word: "beanie", phonetic: "/ˈbiːni/", def: "A small close-fitting knitted cap.", defVn: "mũ len trùm đầu ấm áp", pos: "noun", ex: ["Wear a warm knitted wool beanie on cold winter walks in Sapa.", "A stylish ribbed beanie."], exVn: ["Đội chiếc mũ len dệt kim ấm áp khi đi dạo mùa đông ở Sa Pa.", "Chiếc mũ len gân sành điệu."] },
    { word: "beret", phonetic: "/bəˈreɪ/", def: "A round flattish cap of felt or cloth.", defVn: "mũ nồi bê-rê thanh lịch kiểu Pháp", pos: "noun", ex: ["She paired a stylish wool beret with her trench coat in Da Lat.", "A classic black beret."], exVn: ["Cô ấy kết hợp chiếc mũ nồi len thanh lịch cùng áo măng-tô ở Đà Lạt.", "Chiếc mũ bê-rê màu đen cổ điển."] },
    { word: "visor", phonetic: "/ˈvaɪzər/", def: "A stiff brim at the front of a cap or headband to protect the eyes from the sun.", defVn: "mũ lưỡi trai nửa đầu che nắng", pos: "noun", ex: ["Tennis players wear sun visors to keep glare out of eyes.", "An adjustable sports visor."], exVn: ["Các tay vợt quần vợt đội mũ nửa đầu che nắng để không bị chói mắt.", "Mũ nửa đầu thể thao có thể điều chỉnh."] },
    { word: "tote bag", phonetic: "/ˈtoʊt bæɡ/", def: "A large bag with two parallel handles, typically made of canvas.", defVn: "túi vải tote tiện lợi", pos: "noun", ex: ["Carry English books and a water bottle in an eco-friendly canvas tote bag.", "A printed cotton tote bag."], exVn: ["Đựng sách tiếng Anh và bình nước trong chiếc túi vải tote thân thiện môi trường.", "Chiếc túi tote cotton in hình xinh xắn."] },
    { word: "clutch", phonetic: "/klʌtʃ/", def: "A slim flat handbag without handles or a strap.", defVn: "ví cầm tay dự tiệc sang trọng (clutch)", pos: "noun", ex: ["An elegant satin clutch complements her evening gown.", "Hold a sparkling clutch."], exVn: ["Chiếc ví cầm tay bằng lụa satin thanh lịch tôn lên vẻ đẹp của chiếc đầm dạ hội.", "Cầm chiếc ví clutch lấp lánh."] },
    { word: "shawl", phonetic: "/ʃɔːl/", def: "A piece of fabric worn by women over the shoulders or head or wrapped round a baby.", defVn: "khăn choàng vai lụa/len", pos: "noun", ex: ["Drape a warm cashmere shawl over your shoulders on chilly evenings.", "A hand-woven ethnic brocade shawl."], exVn: ["Khoác chiếc khăn choàng vai len cashmere ấm áp qua vai vào những buổi tối se lạnh.", "Chiếc khăn choàng thổ cẩm dệt tay."] },
    { word: "sneakers", phonetic: "/ˈsniːkərz/", def: "Soft shoes with a rubber sole suitable for sports or casual wear.", defVn: "đôi giày thể thao êm ái", pos: "noun", ex: ["Lace up comfortable white sneakers for city walking.", "Cushioned running sneakers."], exVn: ["Buộc dây đôi giày thể thao trắng êm ái để đi dạo phố.", "Giày thể thao chạy bộ có đệm êm."] },
    { word: "cufflinks", phonetic: "/ˈkʌflɪŋks/", def: "A pair of decorative fasteners for joining the edges of a shirt cuff.", defVn: "khuy măng-sét cài cổ tay áo sơ mi", pos: "noun", ex: ["Fasten silver engraved cufflinks to the cuffs of your formal shirt.", "Gold monogrammed cufflinks."], exVn: ["Cài cặp khuy măng-sét bạc chạm khắc lên cổ tay áo sơ mi trang trọng.", "Khuy măng-sét mạ vàng khắc tên."] },
    { word: "pendant", phonetic: "/ˈpendənt/", def: "A piece of jewelry that hangs from a necklace.", defVn: "mặt dây chuyền ngọc / đá quý", pos: "noun", ex: ["A green jade lotus pendant hanging from a gold chain.", "A glowing crystal pendant."], exVn: ["Mặt dây chuyền hình hoa sen bằng ngọc bích xanh treo trên sợi dây chuyền vàng.", "Mặt dây chuyền pha lê lung linh."] },
    { word: "locket", phonetic: "/ˈlɑːkɪt/", def: "A small ornamental case worn on a chain round the neck, holding a photo or keepsake.", defVn: "mặt dây chuyền mở nắp lồng ảnh", pos: "noun", ex: ["She carries tiny photographs of her grandparents inside a silver heart locket.", "Open the vintage locket."], exVn: ["Cô ấy lưu giữ bức ảnh nhỏ của ông bà bên trong mặt dây chuyền hình trái tim bằng bạc.", "Mở chiếc mặt dây chuyền cổ."] }
  ],

  // Theme 42: Phòng ngủ & Giấc ngủ
  t_basic_bedroom_sleep: [
    { word: "pillow", phonetic: "/ˈpɪloʊ/", def: "A rectangular cloth bag stuffed with feathers, foam, or other soft materials, used to support the head when lying down.", defVn: "chiếc gối nằm êm ái", pos: "noun", ex: ["Rest your head on a soft, supportive ergonomic latex pillow.", "Fluff the pillows before bed."], exVn: ["Tựa đầu lên chiếc gối cao su công thái học êm ái nâng đỡ giấc ngủ.", "Vỗ phồng gối trước khi đi ngủ."] },
    { word: "comforter", phonetic: "/ˈkʌmfərtər/", def: "A warm quilt or thick bed covering.", defVn: "chiếc chăn bông ấm áp", pos: "noun", ex: ["Wrap yourself in a thick down comforter on freezing winter nights.", "A reversible floral comforter."], exVn: ["Cuộn mình trong chiếc chăn bông dày vào những đêm đông lạnh giá.", "Chiếc chăn bông hoa hai mặt."] },
    { word: "bunk bed", phonetic: "/ˈbʌŋk bed/", def: "A piece of furniture consisting of two beds, one above the other.", defVn: "giường tầng tiết kiệm diện tích", pos: "noun", ex: ["Children love climbing the wooden ladder to the top bunk bed.", "A sturdy solid wood bunk bed."], exVn: ["Lũ trẻ rất thích leo cầu thang gỗ lên tầng trên của chiếc giường tầng.", "Chiếc giường tầng bằng gỗ tự nhiên chắc chắn."] },
    { word: "headboard", phonetic: "/ˈhedbɔːrd/", def: "An upright panel forming or placed behind the head of a bed.", defVn: "tấm ốp đầu giường bọc nệm", pos: "noun", ex: ["Lean back comfortably against the padded velvet headboard to read.", "A carved wooden headboard."], exVn: ["Tựa lưng thoải mái vào tấm ốp đầu giường bọc nhung để đọc sách.", "Tấm ốp đầu giường bằng gỗ chạm khắc."] },
    { word: "dresser", phonetic: "/ˈdresər/", def: "A chest of drawers with a mirror above it, for clothes and dressing.", defVn: "bàn trang điểm có ngăn kéo", pos: "noun", ex: ["Keep accessories and folded clothes inside the six-drawer wooden dresser.", "Place perfume on the dresser."], exVn: ["Cất phụ kiện và quần áo gấp gọn trong bàn trang điểm gỗ 6 ngăn kéo.", "Đặt nước hoa lên bàn trang điểm."] },
    { word: "hanger", phonetic: "/ˈhæŋər/", def: "A shaped piece of wood, plastic, or wire with a hook at the top, used for hanging up clothes.", defVn: "cái móc treo quần áo", pos: "noun", ex: ["Hang jackets and dresses on smooth wooden clothes hangers.", "A set of velvet suit hangers."], exVn: ["Treo áo khoác và váy đầm lên những chiếc móc treo quần áo bằng gỗ nhẵn.", "Một bộ móc treo vest bọc nhung."] },
    { word: "sleep mask", phonetic: "/ˈsliːp mæsk/", def: "A mask made of cloth, worn over the eyes to block out light when sleeping.", defVn: "bịt mắt ngủ chống chói", pos: "noun", ex: ["Slip on a soft silk sleep mask to sleep soundly during flights.", "A memory foam contour sleep mask."], exVn: ["Đeo chiếc bịt mắt ngủ bằng lụa mềm để ngủ ngon giấc trong các chuyến bay.", "Bịt mắt ngủ mút xốp ôm sát khuôn mặt."] },
    { word: "earplugs", phonetic: "/ˈɪrplʌɡz/", def: "A pair of small pieces of soft material inserted into the ears to keep out noise.", defVn: "nút bịt tai chống ồn", pos: "noun", ex: ["Wear silicone earplugs for quiet, undisturbed deep sleep in busy cities.", "Noise-reducing foam earplugs."], exVn: ["Đeo nút bịt tai silicon để có giấc ngủ sâu yên tĩnh không bị làm phiền ở đô thị đông đúc.", "Nút bịt tai bằng bọt xốp giảm tiếng ồn."] },
    { word: "slippers", phonetic: "/ˈslɪpərz/", def: "Comfortable slip-on shoes worn indoors.", defVn: "đôi dép đi trong nhà êm chân", pos: "noun", ex: ["Slip into plush fleece indoor slippers when you arrive home.", "Warm fuzzy slippers in winter."], exVn: ["Xỏ chân vào đôi dép đi trong nhà bằng nỉ êm ái khi vừa về đến nhà.", "Đôi dép đi trong nhà lông ấm áp vào mùa đông."] },
    { word: "nightgown", phonetic: "/ˈnaɪtɡaʊn/", def: "A loose, comfortable dress worn in bed by women or girls.", defVn: "váy ngủ lụa mềm mại", pos: "noun", ex: ["A breathable silk nightgown for cool, comfortable summer sleep.", "A cozy cotton nightgown."], exVn: ["Chiếc váy ngủ bằng lụa thoáng mát cho giấc ngủ hè êm dịu.", "Váy ngủ cotton ấm cúng."] },
    { word: "yawn", phonetic: "/jɔːn/", def: "Involuntarily open one's mouth wide and inhale deeply due to tiredness.", defVn: "ngáp một hơi dài thư thái", pos: "verb", ex: ["He stretched and gave a wide sleepy yawn before climbing into bed.", "Yawning is naturally contagious."], exVn: ["Anh ấy vươn vai và ngáp một hơi dài buồn ngủ trước khi trèo lên giường.", "Ngáp là một phản xạ lây lan tự nhiên."] },
    { word: "dream", phonetic: "/driːm/", def: "A series of thoughts, images, and sensations occurring in a person's mind during sleep.", defVn: "giấc mơ đẹp, mơ ước", pos: "noun", ex: ["May you have sweet, peaceful dreams tonight.", "Chase your biggest English dreams."], exVn: ["Chúc bạn có những giấc mơ thật ngọt ngào và an lành đêm nay.", "Hãy theo đuổi những ước mơ tiếng Anh lớn lao của bạn."] },
    { word: "bedtime", phonetic: "/ˈbedtaɪm/", def: "The usual time when someone goes to bed.", defVn: "giờ đi ngủ buổi tối", pos: "noun", ex: ["Establish a relaxing bedtime routine with warm chamomile tea and a book.", "Children bedtime story."], exVn: ["Tạo thói quen giờ đi ngủ thư giãn cùng tách trà hoa cúc ấm và một cuốn sách hay.", "Kể chuyện cho trẻ nghe trước giờ đi ngủ."] }
  ],

  // Theme 43: Phòng tắm & Vệ sinh
  t_basic_bathroom_toiletries: [
    { word: "loofah", phonetic: "/ˈluːfə/", def: "A sponge made of the fibrous skeleton of the loofah fruit, used for washing and exfoliating.", defVn: "xơ mướp tắm thiên nhiên (tẩy tế bào chết)", pos: "noun", ex: ["Gentle natural loofah sponges exfoliate dead skin cells smoothly.", "Hang the natural loofah to dry."], exVn: ["Miếng xơ mướp tắm thiên nhiên tẩy tế bào chết nhẹ nhàng cho làn da mịn màng.", "Treo xơ mướp thiên nhiên cho ráo nước."] },
    { word: "cotton swab", phonetic: "/ˈkɑːtn swɑːb/", def: "A small wad of cotton wrapped around the end of a small rod; Q-tip.", defVn: "tăm bông ngoáy tai / trang điểm", pos: "noun", ex: ["Use hygienic cotton swabs for precise skincare and makeup touch-ups.", "Biodegradable paper cotton swabs."], exVn: ["Dùng tăm bông vệ sinh để chăm sóc da và chỉnh sửa lớp trang điểm chính xác.", "Tăm bông thân giấy tự phân hủy."] },
    { word: "mouthwash", phonetic: "/ˈmaʊθwɑːʃ/", def: "An antiseptic liquid for rinsing the mouth and freshening the breath.", defVn: "nước súc miệng diệt khuẩn thơm mát", pos: "noun", ex: ["Rinse with mint mouthwash for thirty seconds for fresh clean breath.", "Alcohol-free antibacterial mouthwash."], exVn: ["Súc miệng bằng nước súc miệng bạc hà trong 30 giây để có hơi thở thơm mát sạch sẽ.", "Nước súc miệng kháng khuẩn không cồn."] },
    { word: "lip balm", phonetic: "/ˈlɪp bɑːm/", def: "A preparation applied to the lips to prevent chapping.", defVn: "son dưỡng môi mềm mịn", pos: "noun", ex: ["Apply moisturizing coconut lip balm to soothe dry winter lips.", "Organic beeswax lip balm."], exVn: ["Thoa son dưỡng môi dầu dừa để làm dịu đôi môi khô nứt nẻ mùa đông.", "Son dưỡng môi sáp ong hữu cơ."] },
    { word: "nail clipper", phonetic: "/ˈneɪl klɪpər/", def: "A hand tool used for trimming fingernails and toenails.", defVn: "bấm móng tay, kềm cắt móng", pos: "noun", ex: ["Trim fingernails neatly with sharp stainless steel nail clippers.", "A personal nail clipper set."], exVn: ["Cắt tỉa móng tay gọn gàng bằng chiếc bấm móng tay inox sắc bén.", "Bộ bấm móng tay cá nhân."] },
    { word: "tweezers", phonetic: "/ˈtwiːzərz/", def: "A small instrument like a pair of pincers for plucking out hairs and picking up small objects.", defVn: "chiếc nhíp nhổ, kẹp nhỏ", pos: "noun", ex: ["Use precision slanted tweezers to shape eyebrows neatly.", "Sterilize tweezers with rubbing alcohol."], exVn: ["Dùng chiếc nhíp đầu vát chuẩn xác để tỉa lông mày gọn gàng.", "Khử trùng nhíp bằng cồn y tế."] },
    { word: "shower curtain", phonetic: "/ˈʃaʊər ˈkɜːrtn/", def: "A curtain hung around a bathtub or shower enclosure to prevent water from splashing.", defVn: "rèm chắn nước phòng tắm", pos: "noun", ex: ["Draw the waterproof shower curtain to keep the bathroom floor dry.", "A mildew-resistant shower curtain."], exVn: ["Kéo rèm tắm chống thấm nước để giữ cho sàn phòng tắm luôn khô ráo.", "Rèm phòng tắm chống ẩm mốc."] },
    { word: "bath mat", phonetic: "/ˈbæθ mæt/", def: "A mat for standing on when stepping out of a bath or shower.", defVn: "thảm chùi chân phòng tắm chống trượt", pos: "noun", ex: ["Step onto the soft, absorbent non-slip bath mat after showering.", "A machine-washable cotton bath mat."], exVn: ["Bước lên tấm thảm phòng tắm mềm mại, thấm hút và chống trơn trượt sau khi tắm.", "Thảm chùi chân cotton có thể giặt máy."] },
    { word: "hairdryer", phonetic: "/ˈherdraɪər/", def: "An electrical device for drying a person's hair by blowing warm or hot air over it.", defVn: "máy sấy tóc ion âm", pos: "noun", ex: ["Dry your wet hair quickly with a gentle cool-shot hairdryer.", "An ionic quiet hairdryer."], exVn: ["Sấy khô tóc ướt nhanh chóng bằng máy sấy tóc có chế độ gió mát dịu.", "Máy sấy tóc ion âm hoạt động êm ái."] }
  ],

  // Theme 44: Cảm giác cơ thể
  t_basic_bodily_sensations: [
    { word: "drowsiness", phonetic: "/ˈdraʊzinəs/", def: "A feeling of being sleepy and lethargic.", defVn: "cơn buồn ngủ, lơ mơ", pos: "noun", ex: ["Afternoon drowsiness disappears after a brisk five-minute walk.", "Overcome drowsiness with fresh water."], exVn: ["Cơn buồn ngủ buổi chiều tan biến sau 5 phút đi bộ nhanh nhẹn.", "Xua tan cơn buồn ngủ bằng một cốc nước mát."] },
    { word: "exhaustion", phonetic: "/ɪɡˈzɔːstʃən/", def: "A state of extreme physical or mental tiredness.", defVn: "sự kiệt sức sau ngày dài", pos: "noun", ex: ["Recover from complete physical exhaustion with nourishing soup and good rest.", "Signs of heat exhaustion."], exVn: ["Phục hồi sau sự kiệt sức hoàn toàn bằng bát súp bổ dưỡng và giấc ngủ ngon.", "Những dấu hiệu của sự kiệt sức vì nóng."] },
    { word: "palpitation", phonetic: "/ˌpælpɪˈteɪʃn/", def: "A noticeably rapid, strong, or irregular heartbeat.", defVn: "nhịp tim đập thình thịch hồi hộp", pos: "noun", ex: ["Deep calming breaths steady heart palpitations before public speaking.", "Feel gentle heart palpitations."], exVn: ["Hít thở sâu làm đều nhịp tim đập thình thịch trước khi phát biểu trước đám đông.", "Cảm nhận nhịp đập rộn ràng của trái tim."] },
    { word: "tremor", phonetic: "/ˈtremər/", def: "An involuntary quivering movement.", defVn: "sự run rẩy nhẹ (vì lạnh/hồi hộp)", pos: "noun", ex: ["A slight tremor in hands subsided as confidence grew.", "Cold brought shivering tremors."], exVn: ["Cơn run rẩy nhẹ ở bàn tay dịu đi khi sự tự tin tăng lên.", "Cái lạnh làm cơ thể run rẩy."] },
    { word: "vertigo", phonetic: "/ˈvɜːrtɪɡoʊ/", def: "A sensation of whirling and loss of balance, associated particularly with looking down from a great height.", defVn: "cảm giác chóng mặt khi nhìn từ trên cao (vertigo)", pos: "noun", ex: ["Sit down quietly if you experience sudden dizziness or mild vertigo.", "Vertigo on glass skywalk bridges."], exVn: ["Ngồi xuống nghỉ ngơi nếu bạn cảm thấy chóng mặt bất ngờ.", "Cảm giác chóng mặt khi bước trên cầu kính trên cao."] },
    { word: "itchiness", phonetic: "/ˈɪtʃinəs/", def: "An uncomfortable sensation on the skin that causes a desire to scratch.", defVn: "cảm giác ngứa ngáy da", pos: "noun", ex: ["Aloe vera gel soothes sunburn redness and annoying mosquito itchiness.", "Relieve skin itchiness with lotion."], exVn: ["Gel nha đam làm dịu vết đỏ cháy nắng và cảm giác ngứa ngáy do muỗi đốt.", "Làm dịu cơn ngứa da bằng sữa dưỡng ẩm."] },
    { word: "breathlessness", phonetic: "/ˈbreθləsnəs/", def: "The state of being short of breath.", defVn: "sự hụt hơi thở, thở dốc khi vận động", pos: "noun", ex: ["Rest on mountain trails if you feel brief high-altitude breathlessness.", "Cardio training reduces breathlessness."], exVn: ["Nghỉ ngơi trên đường mòn vùng cao nếu cảm thấy hơi thở dốc ở độ cao lớn.", "Rèn luyện thể lực giúp giảm tình trạng hụt hơi."] }
  ],

  // Theme 45: Cảm xúc & Thái độ
  t_basic_feelings_attitudes: [
    { word: "compassion", phonetic: "/kəmˈpæʃn/", def: "Sympathetic pity and concern for the sufferings or misfortunes of others.", defVn: "lòng trắc ẩn, tâm từ bi", pos: "noun", ex: ["Show deep compassion and helpfulness to people in need.", "Acts of quiet compassion."], exVn: ["Thể hiện lòng trắc ẩn sâu sắc và sự giúp đỡ nhiệt thành tới những hoàn cảnh khó khăn.", "Những nghĩa cử từ bi thầm lặng."] },
    { word: "serenity", phonetic: "/səˈrenəti/", def: "The state of being calm, peaceful, and untroubled.", defVn: "sự thanh thản, an nhiên trong tâm hồn", pos: "noun", ex: ["Walking around West Lake at dawn brings absolute mental serenity.", "Cultivate inner serenity."], exVn: ["Đi dạo quanh Hồ Tây lúc rạng đông mang lại sự thanh thản an nhiên tuyệt đối cho tâm hồn.", "Nuôi dưỡng sự bình yên trong tâm trí."] }
  ],

  // Theme 46: Mối quan hệ & Xã hội
  t_basic_relationships_social: [
    { word: "classmate", phonetic: "/ˈklæsmeɪt/", def: "A fellow member of a class at school, college, or university.", defVn: "người bạn cùng lớp thân thương", pos: "noun", ex: ["Support your classmates in English group study sessions.", "Reunite with old high school classmates."], exVn: ["Hỗ trợ các bạn cùng lớp trong những buổi học nhóm tiếng Anh.", "Họp mặt lại những người bạn cùng lớp cấp ba năm xưa."] },
    { word: "peer", phonetic: "/pɪr/", def: "A person of the same age, status, or ability as another specified person.", defVn: "bạn bè đồng trang lứa", pos: "noun", ex: ["Collaborate constructively with your study peers on projects.", "Positive peer motivation."], exVn: ["Hợp tác xây dựng cùng bạn bè đồng trang lứa trong các dự án học tập.", "Động lực tích cực từ bạn bè cùng lứa."] },
    { word: "soulmate", phonetic: "/ˈsoʊlmeɪt/", def: "A person ideally suited to another as a close friend or romantic partner.", defVn: "người bạn tâm giao tri kỷ", pos: "noun", ex: ["A true soulmate understands your unexpressed thoughts with a glance.", "Cherish a lifelong soulmate."], exVn: ["Một người bạn tâm giao tri kỷ hiểu được những tâm sự chưa nói chỉ qua một ánh nhìn.", "Trân quý người bạn tri kỷ cả đời."] },
    { word: "community", phonetic: "/kəˈmjuːnəti/", def: "A group of people living in the same place or having a particular characteristic in common.", defVn: "cộng đồng đoàn kết, tương thân tương ái", pos: "noun", ex: ["A close-knit community supports one another in times of challenge.", "Engage in community volunteering."], exVn: ["Một cộng đồng gắn kết luôn tương trợ lẫn nhau trong mọi lúc gian khó.", "Tham gia các hoạt động thiện nguyện vì cộng đồng."] },
    { word: "circle", phonetic: "/ˈsɜːrkl/", def: "A group of people who are connected by common interests, activities, or friendship.", defVn: "vòng tròn bạn bè, hội bạn thân", pos: "noun", ex: ["Surround yourself with a positive circle of encouraging friends.", "An English speaking study circle."], exVn: ["Hãy bao quanh mình bằng một vòng tròn bạn bè tích cực và luôn động viên nhau.", "Một hội nhóm cùng luyện nói tiếng Anh."] },
    { word: "kinship", phonetic: "/ˈkɪnʃɪp/", def: "Blood relationship; a sharing of characteristics or origins.", defVn: "tình thân ruột thịt, huyết thống thiêng liêng", pos: "noun", ex: ["Cherish warm bonds of family kinship during festive gatherings.", "A feeling of close kinship."], exVn: ["Trân trọng những mối liên kết tình thân gia đình ấm áp trong những dịp đoàn viên.", "Cảm giác thân thuộc gắn bó như người nhà."] },
    { word: "comrade", phonetic: "/ˈkɑːmræd/", def: "A colleague or a fellow member of an organization.", defVn: "người bạn đồng chí, đồng đội chí cốt", pos: "noun", ex: ["Stand shoulder to shoulder with loyal comrades to overcome hurdles.", "Comrades in academic study."], exVn: ["Sát cánh kề vai cùng những người bạn đồng đội chí cốt vượt qua mọi chướng ngại.", "Những người bạn đồng hành trên con đường học thuật."] }
  ],

  // Theme 47: Giao tiếp & Thư tín
  t_basic_conversation_communication: [
    { word: "pronunciation", phonetic: "/prəˌnʌnsiˈeɪʃn/", def: "The way in which a word is pronounced.", defVn: "cách phát âm chuẩn xác", pos: "noun", ex: ["Clear English pronunciation builds immense speaking confidence.", "Practice phonetic pronunciation."], exVn: ["Phát âm tiếng Anh chuẩn xác tạo nên sự tự tin to lớn khi giao tiếp.", "Luyện phát âm theo bảng phiên âm quốc tế."] },
    { word: "accent", phonetic: "/ˈæksent/", def: "A distinctive mode of pronunciation of a language, especially one associated with a particular nation, locality, or social class.", defVn: "chất giọng vùng miền, âm hưởng (accent)", pos: "noun", ex: ["Embrace your natural accent while speaking clear international English.", "A charming British accent."], exVn: ["Tự tin với chất giọng tự nhiên của bạn trong khi nói tiếng Anh quốc tế rõ ràng.", "Một chất giọng Anh lôi cuốn."] },
    { word: "vocabulary", phonetic: "/vəˈkæbjəleri/", def: "The body of words used in a particular language.", defVn: "vốn từ vựng phong phú", pos: "noun", ex: ["Expand your daily English vocabulary with five new practical words every morning.", "Rich active vocabulary."], exVn: ["Mở rộng vốn từ vựng tiếng Anh hàng ngày bằng 5 từ mới hữu ích mỗi sáng.", "Vốn từ vựng chủ động phong phú."] },
    { word: "grammar", phonetic: "/ˈɡræmər/", def: "The whole system and structure of a language or of languages in general.", defVn: "ngữ pháp nền tảng", pos: "noun", ex: ["Master practical English grammar rules through real-life example sentences.", "Grammar forms the backbone of language."], exVn: ["Nắm vững các quy tắc ngữ pháp tiếng Anh thực tế qua các câu ví dụ đời sống.", "Ngữ pháp là khung xương sống của ngôn ngữ."] },
    { word: "idiom", phonetic: "/ˈɪdiəm/", def: "A group of words established by usage as having a meaning not deducible from those of the individual words.", defVn: "thành ngữ tiếng Anh thú vị", pos: "noun", ex: ["Using colorful English idioms makes your speech natural and expressive.", "Learn common daily idioms."], exVn: ["Sử dụng những thành ngữ tiếng Anh sinh động giúp lời nói của bạn tự nhiên và giàu biểu cảm.", "Học các thành ngữ giao tiếp thông dụng."] },
    { word: "slang", phonetic: "/slæŋ/", def: "A type of language that consists of words and phrases that are regarded as very informal.", defVn: "tiếng lóng thân mật giới trẻ", pos: "noun", ex: ["Understand modern conversational slang when chatting with native English speakers.", "Casual spoken slang."], exVn: ["Hiểu được tiếng lóng hội thoại hiện đại khi trò chuyện cùng người bản xứ.", "Tiếng lóng thân mật trong văn nói."] },
    { word: "monologue", phonetic: "/ˈmɑːnəlɔːɡ/", def: "A long speech by one actor in a play or movie, or as part of a theatrical or broadcast program.", defVn: "đoạn độc thoại biểu diễn", pos: "noun", ex: ["Deliver a passionate English monologue on stage.", "A dramatic opening monologue."], exVn: ["Trình bày một đoạn độc thoại tiếng Anh đầy nhiệt huyết trên sân khấu.", "Đoạn độc thoại mở đầu đầy kịch tính."] },
    { word: "farewell", phonetic: "/ˌferˈwel/", def: "An act of parting or of marking someone's departure; goodbye.", defVn: "lời chào tạm biệt thân thương", pos: "noun", ex: ["Bid a fond farewell to classmates before summer holiday begins.", "A heartfelt farewell speech."], exVn: ["Gửi lời chào tạm biệt thân thương tới các bạn cùng lớp trước kỳ nghỉ hè.", "Bài phát biểu chia tay chân thành."] },
    { word: "question", phonetic: "/ˈkwestʃən/", def: "A sentence worded or expressed so as to elicit information.", defVn: "câu hỏi, thắc mắc cần giải đáp", pos: "noun", ex: ["Never hesitate to ask your teacher a thoughtful English question.", "Raise your hand with a question."], exVn: ["Đừng ngần ngại đặt câu hỏi tiếng Anh thấu đáo cho thầy cô giáo nhé.", "Giơ tay phát biểu câu hỏi."] },
    { word: "answer", phonetic: "/ˈænsər/", def: "A thing said, written, or done to deal with or as a reaction to a question, statement, or situation.", defVn: "câu trả lời, lời đáp", pos: "noun", ex: ["She gave a clear, articulate answer to the interviewer's query.", "Find answers in books."], exVn: ["Cô ấy đã đưa ra câu trả lời khúc chiết, mạch lạc cho câu hỏi của người phỏng vấn.", "Tìm kiếm câu trả lời trong trang sách."] },
    { word: "reply", phonetic: "/rɪˈplaɪ/", def: "Say or write something as an answer to someone.", defVn: "hồi đáp, trả lời thư / tin nhắn", pos: "verb", ex: ["Reply promptly and politely to incoming emails.", "She replied with a radiant smile."], exVn: ["Hồi đáp nhanh chóng và lịch sự các email gửi đến.", "Cô ấy đáp lại bằng một nụ cười rạng rỡ."] },
    { word: "message", phonetic: "/ˈmesɪdʒ/", def: "A verbal, written, or recorded communication sent to or left for a recipient.", defVn: "tin nhắn, thông điệp truyền tải", pos: "noun", ex: ["Send an encouraging text message to motivate your study partner.", "The inspirational core message."], exVn: ["Gửi một tin nhắn động viên để tiếp thêm động lực cho bạn học.", "Thông điệp cốt lõi đầy cảm hứng."] }
  ],

  // Theme 48: Hình học & Họa tiết
  t_basic_geometry_patterns: [
    { word: "polka dot", phonetic: "/ˈpoʊlkə dɑːt/", def: "One of a number of large round dots that make up a pattern on cloth.", defVn: "họa tiết chấm bi xinh xắn", pos: "noun", ex: ["A playful retro dress with white polka dots on navy blue silk.", "Polka dot pattern scarf."], exVn: ["Chiếc váy cổ điển xinh xắn có họa tiết chấm bi trắng trên nền lụa xanh navy.", "Chiếc khăn quàng họa tiết chấm bi."] }
  ],

  // Theme 50: Âm thanh & Nhạc cụ
  t_basic_sounds_instruments: [
    { word: "trumpet", phonetic: "/ˈtrʌmpɪt/", def: "A brass musical instrument with a flared bell and three valves.", defVn: "kèn trom-pet đồng vang dội", pos: "noun", ex: ["A triumphant trumpet fanfare announced the grand opening ceremony.", "Play high clear notes on the trumpet."], exVn: ["Hồi kèn trom-pet vang dội báo hiệu lễ khai mạc trọng thể bắt đầu.", "Thổi những nốt nhạc cao vút trong trẻo trên kèn trumpet."] },
    { word: "violin", phonetic: "/ˌvaɪəˈlɪn/", def: "A stringed musical instrument of treble pitch, played with a horsehair bow.", defVn: "đàn vĩ cầm, vi-ô-lông réo rắt", pos: "noun", ex: ["The gentle melodic weeping of the wooden violin moved listeners to tears.", "Play the violin bow smoothly."], exVn: ["Tiếng đàn vĩ cầm réo rắt dịu êm làm lay động hàng triệu trái tim người nghe.", "Kéo vĩ đàn vi-ô-lông thật êm ái."] },
    { word: "ukulele", phonetic: "/ˌjuːkəˈleɪli/", def: "A small four-stringed guitar of Hawaiian origin.", defVn: "đàn u-ku-le-le nhỏ xinh", pos: "noun", ex: ["Strum cheerful upbeat summer chords on a compact wooden ukulele.", "Learn easy ukulele tunes."], exVn: ["Gảy những hợp âm mùa hè rộn rã trên chiếc đàn ukulele gỗ nhỏ xinh.", "Học những giai điệu ukulele đơn giản."] },
    { word: "banjo", phonetic: "/ˈbændʒoʊ/", def: "A stringed musical instrument with a long neck and a round body like a small drum.", defVn: "đàn gảy ban-giô đồng quê", pos: "noun", ex: ["Lively folk bluegrass music played on a five-string plucked banjo.", "Fingerpick the banjo strings."], exVn: ["Bản nhạc dân ca đồng quê rộn rã chơi trên cây đàn ban-giô 5 dây.", "Gảy ngón trên các dây đàn banjo."] },
    { word: "tambourine", phonetic: "/ˌtæmbəˈriːn/", def: "A percussion instrument resembling a shallow drum with small metal jingles in the frame.", defVn: "trống lắc tay có lục lạc rung (tambourine)", pos: "noun", ex: ["Shake the lively tambourine to accompany the classroom singing.", "Tap the tambourine in rhythm."], exVn: ["Lắc chiếc trống lắc tay vui nhộn hòa nhịp cùng bài hát của cả lớp.", "Gõ trống lắc tay theo đúng nhịp điệu."] },
    { word: "cymbal", phonetic: "/ˈsɪmbl/", def: "A musical instrument consisting of a slightly concave round brass plate which is struck against another.", defVn: "chũm chọe đồng vang dội", pos: "noun", ex: ["Clash the shiny brass cymbals together at the musical climax.", "A drum kit crash cymbal."], exVn: ["Gõ đôi chũm chọe đồng sáng bóng vào nhau ở đoạn cao trào của bản nhạc.", "Chũm chọe trong bộ trống."] },
    { word: "gong", phonetic: "/ɡɑːŋ/", def: "A metal disc with a turned rim, giving a resonant note when struck; Cong Chieng.", defVn: "cồng chiêng Tây Nguyên (Di sản UNESCO)", pos: "noun", ex: ["Space of Gong Culture in the Central Highlands is a UNESCO Intangible Cultural Heritage.", "Strike the sacred bronze gong."], exVn: ["Không gian văn hóa Cồng chiêng Tây Nguyên là Di sản Văn hóa Phi vật thể của UNESCO.", "Đánh tiếng cồng chiêng đồng thiêng liêng."] },
    { word: "triangle", phonetic: "/ˈtraɪæŋɡl/", def: "A musical percussion instrument consisting of a steel rod bent into a triangle.", defVn: "nhạc cụ kẻng tam giác gõ leng keng", pos: "noun", ex: ["Strike the steel musical triangle for a clear, crisp ringing tone.", "A silver triangle percussion."], exVn: ["Gõ vào chiếc kẻng tam giác thép để tạo âm thanh leng keng trong trẻo.", "Nhạc cụ gõ tam giác bằng bạc."] },
    { word: "chime", phonetic: "/tʃaɪm/", def: "A melodious ringing sound, being one of a set of bells in a church tower.", defVn: "tiếng chuông gió ngân nga", pos: "noun", ex: ["Bamboo wind chimes tinkled peacefully on the breezy veranda.", "The grandfather clock chimed noon."], exVn: ["Những chiếc chuông gió bằng tre ngân nga thanh bình trên hiên nhà lộng gió.", "Chiếc đồng hồ quả lắc điểm chuông 12 giờ trưa."] },
    { word: "harmony", phonetic: "/ˈhɑːrməni/", def: "The combination of simultaneously sounded musical notes to produce chords and chord progressions.", defVn: "sự hòa âm phối khí, hòa thanh", pos: "noun", ex: ["Singing together in four-part vocal harmony creates heavenly music.", "Rich acoustic vocal harmonies."], exVn: ["Cùng nhau hát bè hòa âm 4 giọng tạo nên khúc ca tuyệt mỹ.", "Những hòa âm mộc mạc phong phú."] },
    { word: "beat", phonetic: "/biːt/", def: "The main accent or rhythmic unit in music or poetry.", defVn: "phách nhịp dồn dập", pos: "noun", ex: ["Nod your head along with the infectious hip-hop drum beat.", "Keep a steady drum beat."], exVn: ["Gật đầu theo nhịp phách trống hip-hop đầy cuốn hút.", "Giữ nhịp trống đều đặn."] }
  ],

  // Theme 51: Ánh sáng & Thị giác
  t_basic_light_visual_effects: [
    { word: "reflection", phonetic: "/rɪˈflekʃn/", def: "The throwing back by a body or surface of light, heat, or sound without absorbing it.", defVn: "hình ảnh phản chiếu lung linh", pos: "noun", ex: ["Admire the perfect mountain reflection on the mirror-like surface of Tuyen Lam Lake.", "Clear water reflections."], exVn: ["Chiêm ngưỡng bóng núi phản chiếu hoàn hảo trên mặt hồ Tuyền Lâm phẳng lặng như gương.", "Bóng phản chiếu trong vắt trên mặt nước."] },
    { word: "beam", phonetic: "/biːm/", def: "A ray or shaft of light.", defVn: "luồng ánh sáng, tia sáng rọi", pos: "noun", ex: ["Lighthouse beams guide ships safely across coastal waters at night.", "A beam of golden sunlight."], exVn: ["Những luồng sáng hải đăng dẫn đường cho tàu bè an toàn trên vùng biển đêm.", "Một chùm ánh nắng vàng rực rỡ."] },
    { word: "shadow", phonetic: "/ˈʃædoʊ/", def: "A dark area or shape produced by a body coming between rays of light and a surface.", defVn: "bóng râm mát rượi, bóng râm", pos: "noun", ex: ["Rest in the cool green shadow cast by ancient banyan trees.", "Shadows lengthen at sunset."], exVn: ["Nghỉ ngơi trong bóng râm xanh mát rượi của những cây đa cổ thụ.", "Bóng ngả dài khi hoàng hôn buông xuống."] },
    { word: "spark", phonetic: "/spɑːrk/", def: "A small fiery particle thrown off from a fire, alight in ashes, or produced by static electricity.", defVn: "tia lửa nhỏ lấp lánh, đốm lửa", pos: "noun", ex: ["Golden sparks flew upward into the night sky from the crackling campfire.", "A spark of creative genius."], exVn: ["Những tia lửa vàng bay lên bầu trời đêm từ đống lửa trại nổ lách tách.", "Một tia sáng sáng tạo thiên tài."] },
    { word: "flash", phonetic: "/flæʃ/", def: "A sudden brief burst of bright light or a sudden brief feeling.", defVn: "chớp sáng lóe lên", pos: "noun", ex: ["A sudden camera flash captured our joyful reunion smile.", "A flash of brilliant inspiration."], exVn: ["Ánh đèn flash máy ảnh bất ngờ bắt trọn nụ cười ngày hội ngộ vui sướng.", "Một tia cảm hứng sáng ngời."] },
    { word: "halo", phonetic: "/ˈheɪloʊ/", def: "A circle of white or colored light around the sun, moon, or other luminous body.", defVn: "vầng hào quang tỏa sáng", pos: "noun", ex: ["A golden sun halo shimmered in the sky over Mount Fansipan.", "A radiant lunar halo."], exVn: ["Vầng hào quang mặt trời tỏa sáng lung linh trên bầu trời đỉnh Fansipan.", "Vầng trăng tỏa hào quang rạng rỡ."] },
    { word: "mirage", phonetic: "/məˈrɑːʒ/", def: "An optical illusion caused by atmospheric conditions, especially the appearance of a sheet of water in a desert.", defVn: "ảo ảnh quang học (mirage)", pos: "noun", ex: ["Heat shimmering on highway asphalt creates the optical illusion of a water mirage.", "A desert oasis mirage."], exVn: ["Hơi nóng bốc lên trên mặt đường nhựa tạo nên ảo ảnh như có vũng nước phía trước.", "Ảo ảnh ốc đảo giữa sa mạc."] }
  ],

  // Theme 52: Vận động cơ thể
  t_basic_body_movements: [
    { word: "stretch", phonetic: "/stretʃ/", def: "Straighten or extend one's body or a part of one's body to its full length.", defVn: "vươn vai kéo giãn cơ thể", pos: "verb", ex: ["Stretch your arms and back gently after studying at your desk.", "Daily morning stretching."], exVn: ["Vươn vai và kéo giãn lưng nhẹ nhàng sau khi ngồi học bên bàn.", "Bài tập kéo giãn cơ thể mỗi sáng."] }
  ],

  // Theme 54: Sân bay & Nhà ga
  t_basic_airport_station_travel: [
    { word: "terminal", phonetic: "/ˈtɜːrmɪnl/", def: "A building at an airport where passengers transfer between ground transportation and the facilities.", defVn: "nhà ga sân bay quốc tế / nội địa", pos: "noun", ex: ["Noi Bai International Airport Terminal 2 is modern and spacious.", "Follow signs to the departure terminal."], exVn: ["Nhà ga T2 Sân bay Quốc tế Nội Bài rất hiện đại và rộng rãi.", "Đi theo biển chỉ dẫn tới nhà ga khởi hành."] },
    { word: "customs", phonetic: "/ˈkʌstəmz/", def: "The official department that administers and collects the duties levied by a government on imported goods.", defVn: "hải quan cửa khẩu", pos: "noun", ex: ["Declare any restricted goods truthfully at international airport customs.", "Pass through airport customs."], exVn: ["Khai báo trung thực các hàng hóa quy định tại quầy hải quan sân bay quốc tế.", "Đi qua cửa kiểm tra hải quan."] }
  ],

  // Theme 55: Khách sạn & Lưu trú
  t_basic_hotel_accommodation: [
    { word: "suite", phonetic: "/swiːt/", def: "A set of rooms designated for one person's or family's use or for a particular purpose.", defVn: "phòng thượng hạng (suite) cao cấp", pos: "noun", ex: ["The executive penthouse suite offers panoramic views of the city skyline.", "Book an oceanfront family suite."], exVn: ["Căn phòng thượng hạng tầng mái đem lại tầm nhìn toàn cảnh đường chân trời thành phố.", "Đặt phòng gia đình thượng hạng hướng biển."] },
    { word: "valet", phonetic: "/væˈleɪ/", def: "A person employed to park cars.", defVn: "dịch vụ đỗ xe hộ của khách sạn", pos: "noun", ex: ["Hand your car keys to the hotel valet upon arrival at the entrance.", "Complimentary valet parking."], exVn: ["Giao chìa khóa xe cho nhân viên đỗ xe hộ khi vừa đến sảnh khách sạn.", "Dịch vụ đỗ xe hộ miễn phí."] }
  ],

  // Theme 56: Ẩm thực đường phố & Ăn vặt
  t_basic_street_food_snacks: [
    { word: "grilled banana", phonetic: "/ɡrɪld bəˈnænə/", def: "Ripe bananas wrapped in sticky rice, grilled over charcoal and served with sweet coconut cream; chuoi nep nuong.", defVn: "món chuối nếp nướng thơm béo", pos: "noun", ex: ["Warm grilled sticky rice banana drizzled with rich coconut sauce and tapioca pearls.", "Fragrant charcoal grilled bananas."], exVn: ["Món chuối nếp nướng nóng hổi rưới nước cốt dừa béo ngậy và hạt trân châu.", "Chuối nướng than hoa thơm lừng."] },
    { word: "tofu pudding", phonetic: "/ˈtoʊfuː ˈpʊdɪŋ/", def: "Soft, silky soybean curd served warm or chilled in fragrant ginger syrup; tao pho.", defVn: "tào phớ nước đường gừng hoa nhài", pos: "noun", ex: ["A refreshing bowl of silky tofu pudding with jasmine flower syrup and jelly.", "Warm ginger tofu pudding in winter."], exVn: ["Bát tào phớ mềm mịn thanh mát ướp nước đường hoa nhài thơm ngát và thạch.", "Tào phớ nóng nước đường gừng vào mùa đông."] },
    { word: "sweet potato", phonetic: "/ˈswiːt pəˈteɪtoʊ/", def: "Roasted sweet tuber; street winter snack.", defVn: "khoai lang nướng than hoa thơm bùi", pos: "noun", ex: ["Steaming hot roasted sweet potatoes warm hands on Hanoi winter nights.", "Sweet golden roasted potatoes."], exVn: ["Những củ khoai lang nướng nóng hổi sưởi ấm đôi bàn tay trong đêm đông Hà Nội.", "Khoai lang nướng vàng ngọt bùi."] },
    { word: "corn milk", phonetic: "/kɔːrn mɪlk/", def: "A sweet, fragrant, creamy beverage prepared by blending fresh sweet corn kernels with milk.", defVn: "sữa bắp ngọt thơm dinh dưỡng", pos: "noun", ex: ["A bottle of chilled sweet corn milk is creamy, fragrant, and healthy.", "Drink warm corn milk in the morning."], exVn: ["Một chai sữa bắp ngọt thanh ướp lạnh vừa béo ngậy, thơm lừng lại bổ dưỡng.", "Uống sữa ngô ấm vào buổi sáng."] },
    { word: "shrimp fritter", phonetic: "/ʃrɪmp ˈfrɪtər/", def: "Crispy fried sweet potato and whole freshwater shrimp cake; banh tom.", defVn: "bánh tôm Hồ Tây vàng giòn rụm", pos: "noun", ex: ["West Lake crispy golden shrimp fritters dipped in sweet and sour green papaya sauce.", "Traditional Hanoi shrimp cakes."], exVn: ["Bánh tôm Hồ Tây vàng giòn rụm chấm nước mắm chua ngọt nộm đu đủ xanh.", "Bánh tôm truyền thống Hà Nội."] },
    { word: "caramel flan", phonetic: "/ˈkærəmel flæn/", def: "A baked custard dessert with a layer of caramel on top; banh flan.", defVn: "bánh caramen (bánh flan cà phê cốt dừa)", pos: "noun", ex: ["Creamy Vietnamese caramel flan topped with shaved ice and drip coffee.", "Silky smooth egg flan."], exVn: ["Bánh flan caramen béo ngậy ăn kèm đá bào và cà phê phin đậm đà.", "Bánh flan trứng mềm mịn."] }
  ],

  // Theme 58: Lễ hội & Phong tục
  t_basic_holidays_customs: [
    { word: "celebration", phonetic: "/ˌselɪˈbreɪʃn/", def: "The action of marking one's pleasure at an important event or occasion by engaging in enjoyable activity.", defVn: "lễ kỷ niệm, ngày hội ăn mừng", pos: "noun", ex: ["Family gatherings and joyful celebrations fill the atmosphere during Tet.", "Join the graduation celebration."], exVn: ["Những buổi sum họp gia đình và ngày hội ăn mừng rộn ràng ngập tràn trong không khí ngày Tết.", "Tham gia lễ ăn mừng tốt nghiệp."] },
    { word: "tradition", phonetic: "/trəˈdɪʃn/", def: "The transmission of customs or beliefs from generation to generation.", defVn: "truyền thống tốt đẹp ngàn đời", pos: "noun", ex: ["Wrapping square sticky rice cakes (Banh Chung) is a sacred Tet family tradition.", "Honor our cultural traditions."], exVn: ["Gói bánh chưng vuông là một truyền thống gia đình thiêng liêng mỗi dịp Tết đến xuân về.", "Tôn vinh những truyền thống văn hóa của dân tộc."] },
    { word: "heritage", phonetic: "/ˈherɪtɪdʒ/", def: "Property that is or may be inherited; an inheritance; valued objects and qualities passed down from previous generations.", defVn: "di sản văn hóa quý báu", pos: "noun", ex: ["Hoi An Ancient Town is recognized as a world cultural heritage site.", "Preserve our rich national heritage."], exVn: ["Đô thị cổ Hội An được công nhận là Di sản Văn hóa Thế giới.", "Bảo tồn di sản phong phú của đất nước."] },
    { word: "parade", phonetic: "/pəˈreɪd/", def: "A public procession, especially one with marching bands and floats in a festival.", defVn: "cuộc diễu hành lễ hội tưng bừng", pos: "noun", ex: ["Children carry star-shaped lanterns in a joyful Mid-Autumn night parade.", "A colorful floral parade."], exVn: ["Lũ trẻ rước đèn ông sao trong cuộc diễu hành đêm Trung Thu tưng bừng.", "Đoàn diễu hành xe hoa rực rỡ sắc màu."] },
    { word: "resolution", phonetic: "/ˌrezəˈluːʃn/", def: "A firm decision to do or not to do something, especially made at the start of a New Year.", defVn: "quyết tâm năm mới, lời hứa mục tiêu", pos: "noun", ex: ["My top New Year resolution is to achieve fluent English communication.", "Write down your yearly resolutions."], exVn: ["Quyết tâm năm mới hàng đầu của tôi là đạt được khả năng giao tiếp tiếng Anh lưu loát.", "Viết ra những mục tiêu quyết tâm của bạn."] },
    { word: "blessing", phonetic: "/ˈblesɪŋ/", def: "A prayer asking for divine favor and protection; a good wish.", defVn: "lời chúc phúc bình an, phước lành", pos: "noun", ex: ["We send our heartfelt wishes of health, peace, and blessings to you.", "Receive elder blessings at Tet."], exVn: ["Chúng tôi gửi tới bạn những lời chúc phúc bình an, dồi dào sức khỏe và may mắn.", "Nhận lời chúc phúc từ các bậc cao niên dịp Tết."] }
  ],

  // Theme 59: An toàn & Luật lệ
  t_basic_safety_warnings_rules: [
    { word: "caution", phonetic: "/ˈkɔːʃn/", def: "Care taken to avoid danger or mistakes.", defVn: "sự cẩn trọng, cảnh giác", pos: "noun", ex: ["Exercise great caution when driving on wet mountain roads.", "Proceed with caution."], exVn: ["Hãy hết sức cẩn trọng khi lái xe trên những cung đường núi trơn ướt.", "Tiến bước với sự thận trọng."] },
    { word: "hazard", phonetic: "/ˈhæzərd/", def: "A danger or risk.", defVn: "mối nguy hiểm, nguy cơ tiềm ẩn", pos: "noun", ex: ["Identify and eliminate workplace electrical hazards promptly.", "A road traffic hazard."], exVn: ["Nhận biết và loại bỏ các nguy cơ chập điện tại nơi làm việc kịp thời.", "Một chướng ngại nguy hiểm trên đường giao thông."] },
    { word: "first aid", phonetic: "/ˌfɜːrst ˈeɪd/", def: "Help given to a sick or injured person until full medical treatment is available.", defVn: "sơ cứu y tế ban đầu", pos: "noun", ex: ["Every household should keep a fully stocked first aid kit in an accessible spot.", "Basic first aid training."], exVn: ["Mỗi gia đình nên trang bị sẵn một hộp sơ cứu y tế đầy đủ ở vị trí dễ lấy.", "Khóa tập huấn kỹ năng sơ cứu cơ bản."] },
    { word: "fire extinguisher", phonetic: "/ˈfaɪər ɪkˈstɪŋɡwɪʃər/", def: "A portable device that discharges a jet of water, foam, gas, or other material to extinguish a fire.", defVn: "bình chữa cháy mini, bình cứu hỏa", pos: "noun", ex: ["Learn how to pull the safety pin and operate a dry chemical fire extinguisher.", "Check fire extinguisher pressure."], exVn: ["Học cách rút chốt an toàn và sử dụng bình chữa cháy bột khô.", "Kiểm tra đồng hồ áp suất bình cứu hỏa."] },
    { word: "prohibited", phonetic: "/prəˈhɪbɪtɪd/", def: "That has been forbidden; banned.", defVn: "bị cấm, hành vi cấm kỵ", pos: "adj", ex: ["Smoking is strictly prohibited inside all public transport vehicles.", "Prohibited entry area."], exVn: ["Hút thuốc lá bị nghiêm cấm hoàn toàn trên mọi phương tiện giao thông công cộng.", "Khu vực cấm vào."] },
    { word: "guardrail", phonetic: "/ˈɡɑːrdreɪl/", def: "A rail acting as a safety barrier at the side of a road, bridge, or balcony.", defVn: "hàng rào hộ lan bảo vệ, lan can an toàn", pos: "noun", ex: ["Steel guardrails along winding mountain passes protect motorists from cliffs.", "Hold the safety guardrail."], exVn: ["Hàng rào hộ lan thép dọc các con đèo quanh co bảo vệ người lái xe khỏi vực sâu.", "Bám vào lan can an toàn nhé."] },
    { word: "pedestrian", phonetic: "/pəˈdestriən/", def: "A person walking rather than traveling in a vehicle.", defVn: "người đi bộ trên đường", pos: "noun", ex: ["Drivers must always yield right-of-way to pedestrians crossing at crosswalks.", "A safe pedestrian zone."], exVn: ["Người lái xe phải luôn nhường đường cho người đi bộ sang đường tại vạch kẻ.", "Khu vực đi bộ an toàn."] }
  ],

  // Theme 60: Thiết bị & Gia dụng
  t_basic_appliances_gadgets: [
    { word: "smartwatch", phonetic: "/ˈsmɑːrtwɑːtʃ/", def: "A mobile device with a touchscreen display, designed to be worn on the wrist.", defVn: "đồng hồ đeo tay thông minh (smartwatch)", pos: "noun", ex: ["Track your daily walking steps and sleep patterns on your digital smartwatch.", "Receive notifications on the smartwatch."], exVn: ["Theo dõi số bước chân hàng ngày và giấc ngủ trên chiếc đồng hồ thông minh.", "Nhận thông báo trên đồng hồ thông minh."] },
    { word: "earbuds", phonetic: "/ˈɪrbʌdz/", def: "Very small headphones that are fitted directly into the outer ear; wireless earbuds.", defVn: "tai nghe không dây nhét tai", pos: "noun", ex: ["Put in your noise-cancelling wireless earbuds to listen to English podcasts anywhere.", "Charge earbuds in the case."], exVn: ["Đeo tai nghe không dây chống ồn để nghe bài phát thanh tiếng Anh mọi lúc mọi nơi.", "Sạc tai nghe trong hộp sạc."] },
    { word: "air conditioner", phonetic: "/ˈer kəndɪʃənər/", def: "A system or machine for cooling and drying the air in a room or building.", defVn: "máy điều hòa nhiệt độ, máy lạnh", pos: "noun", ex: ["Set the inverter air conditioner to an eco-friendly 26 degrees Celsius.", "Service the air conditioner filter."], exVn: ["Cài đặt máy điều hòa tiết kiệm điện ở mức 26 độ C thân thiện môi trường.", "Vệ sinh màng lọc máy điều hòa."] },
    { word: "dishwasher", phonetic: "/ˈdɪʃwɔːʃər/", def: "A machine for washing dishes automatically.", defVn: "máy rửa chén bát tự động", pos: "noun", ex: ["Load dirty plates and bowls into the automatic dishwasher after family dinner.", "Save water with the dishwasher."], exVn: ["Xếp bát đĩa bẩn vào máy rửa bát tự động sau bữa tối gia đình.", "Tiết kiệm nước nhờ máy rửa bát."] }
  ]
};
